OPENSNES := $(shell cd ../../.. && pwd)

TARGET   := sprite_swarm.sfc
ROM_NAME := SPRITE SWARM
USE_LIB  := 1
LIB_MODULES := console dma background sprite math tile

CSRC := main.c

include $(OPENSNES)/make/common.mk
