OPENSNES := $(shell cd ../../.. && pwd)

TARGET   := mode6.sfc
ROM_NAME := MODE 6 OPT HIRES
USE_LIB  := 1
LIB_MODULES := console dma background input math tile

CSRC := main.c

include $(OPENSNES)/make/common.mk
