# Object Size Example
# Interactive demo of all 6 SNES sprite size modes

OPENSNES := $(shell cd ../../../.. && pwd)

TARGET     := object_size.sfc
ROM_NAME   := OBJECT SIZE

USE_LIB    := 1
LIB_MODULES := console sprite dma text text4bpp input background

CSRC       := main.c
ASMSRC     := data.asm

include $(OPENSNES)/make/common.mk
