# Mode 5 Example - Hi-res 512x256
# Interlaced hi-res graphics

OPENSNES := $(shell cd ../../.. && pwd)

TARGET     := mode5.sfc
ROM_NAME   := MODE5 HI-RES

USE_LIB    := 1
LIB_MODULES := console sprite dma background

CSRC       := main.c
ASMSRC     := data.asm

include $(OPENSNES)/make/common.mk
