OPENSNES := $(shell cd ../../.. && pwd)
TARGET   := metasprite.sfc
ROM_NAME := METASPRITE_DEMO

CSRC     := main.c

USE_LIB  := 1
LIB_MODULES := console sprite dma text text4bpp background input anim

include $(OPENSNES)/make/common.mk
