# Sprite Unit Test Makefile

OPENSNES := $(shell cd ../../.. && pwd)
TARGET   := test_sprite.sfc
ROM_NAME := SPRITE TESTS

CSRC     := test_sprite.c
USE_LIB  := 1
LIB_MODULES := console sprite dma text

include $(OPENSNES)/make/common.mk
