OPENSNES := $(shell cd ../../.. && pwd)

TARGET     := map_scroll.sfc
ROM_NAME   := MAP SCROLL DEMO

USE_LIB    := 1
LIB_MODULES := console sprite dma input background map

CSRC       := main.c

include $(OPENSNES)/make/common.mk
