OPENSNES := $(shell cd ../../.. && pwd)

TARGET   := hdma_wave.sfc
ROM_NAME := HDMA WAVE DEMO

CSRC     := main.c
ASMSRC   := hdma_wave_asm.asm

USE_LIB     := 1
LIB_MODULES := console sprite dma input

include $(OPENSNES)/make/common.mk
