OPENSNES := $(shell cd ../../.. && pwd)

TARGET   := game_skeleton.sfc
ROM_NAME := GAME SKELETON
USE_LIB  := 1
LIB_MODULES := console dma background sprite text input tile

CSRC := main.c

include $(OPENSNES)/make/common.mk
