OPENSNES := $(shell cd ../../.. && pwd)

TARGET   := mosaic.sfc
ROM_NAME := MOSAIC DEMO

CSRC     := main.c

USE_LIB     := 1
LIB_MODULES := console sprite dma input mosaic

include $(OPENSNES)/make/common.mk
