#==============================================================================
# Two Players Example Makefile
#==============================================================================

OPENSNES := $(shell cd ../../.. && pwd)

TARGET     := two_players.sfc
ROM_NAME   := TWO PLAYERS DEMO

# Use the OpenSNES library
USE_LIB    := 1
LIB_MODULES := console input sprite text

# Source files
CSRC       := main.c

# Include common build rules
include $(OPENSNES)/make/common.mk
