# Mosaic - Demonstrates mosaic shading effect with fade transitions

OPENSNES := $(shell cd ../../../.. && pwd)

TARGET   := mosaic.sfc
ROM_NAME := OPENSNES MOSAIC

USE_LIB     := 1
LIB_MODULES := console dma background sprite input

CSRC   := main.c
ASMSRC := data.asm

include $(OPENSNES)/make/common.mk
