var annotated_dup =
[
    [ "AnimClip", "structAnimClip.html", "structAnimClip" ],
    [ "AnimPlayer", "structAnimPlayer.html", "structAnimPlayer" ],
    [ "AudioSample", "structAudioSample.html", "structAudioSample" ],
    [ "AudioVoiceState", "structAudioVoiceState.html", "structAudioVoiceState" ],
    [ "BgAsset", "structBgAsset.html", "structBgAsset" ],
    [ "EffectState", "structEffectState.html", "structEffectState" ],
    [ "Entity", "structEntity.html", "structEntity" ],
    [ "GameState", "structGameState.html", "structGameState" ],
    [ "GfxAsset", "structGfxAsset.html", "structGfxAsset" ],
    [ "LineClearResult", "structLineClearResult.html", "structLineClearResult" ],
    [ "MetaspriteItem", "structMetaspriteItem.html", "structMetaspriteItem" ],
    [ "Monster", "structMonster.html", "structMonster" ],
    [ "Npc", "structNpc.html", null ],
    [ "OamDynamicConfig", "structOamDynamicConfig.html", "structOamDynamicConfig" ],
    [ "Panel", "structPanel.html", "structPanel" ],
    [ "Player", "structPlayer.html", "structPlayer" ],
    [ "Rect", "structRect.html", "structRect" ],
    [ "SaveState", "structSaveState.html", "structSaveState" ],
    [ "Scene", "structScene.html", "structScene" ],
    [ "t_objs", "structt__objs.html", "structt__objs" ],
    [ "t_sprites", "structt__sprites.html", "structt__sprites" ],
    [ "TextConfig", "structTextConfig.html", "structTextConfig" ]
];