OPENSNES := $(shell cd ../../.. && pwd)

TARGET   := dsp1_cube.sfc
ROM_NAME := DSP1 CUBE

USE_LIB     := 1
USE_DSP1    := 1
LIB_MODULES := console dma sprite   # dsp1 auto-added by USE_DSP1

CSRC := main.c

include $(OPENSNES)/make/common.mk
