# Metasprite Example Makefile

OPENSNES := $(shell cd ../../.. && pwd)
TARGET   := metasprite.sfc
ROM_NAME := METASPRITE_DEMO

CSRC     := main.c
ASMSRC   := data.asm

USE_LIB  := 1
LIB_MODULES := console sprite dma background input

include $(OPENSNES)/make/common.mk
