var searchData=
[
  ['i_0',['i',['../games_2breakout_2main_8c.html#abf0a803c9f19fa09bc230ae54a46bb4c',1,'main.c']]],
  ['i_20build_20a_20world_1',['Stage 3 — &quot;Can I build a world?&quot;',['../learning_path.html#stage-3--can-i-build-a-world',1,'']]],
  ['i_20finish_20and_20ship_2',['Stage 6 — &quot;Can I finish and ship?&quot;',['../learning_path.html#stage-6--can-i-finish-and-ship',1,'']]],
  ['i_20hold_20it_20all_20together_3',['Stage 5 — &quot;Can I hold it all together?&quot;',['../learning_path.html#stage-5--can-i-hold-it-all-together',1,'']]],
  ['i_20make_20it_20feel_20good_4',['Stage 4 — &quot;Can I make it feel good?&quot;',['../learning_path.html#stage-4--can-i-make-it-feel-good',1,'']]],
  ['i_20need_5',['Which API do I need?',['../getting_started.html#which-api-do-i-need',1,'']]],
  ['i_20put_20something_20on_20screen_6',['Stage 1 — &quot;Can I put something on screen?&quot;',['../learning_path.html#stage-1--can-i-put-something-on-screen',1,'']]],
  ['i_20ram_20—_20the_20mailbox_7',['I-RAM — The Mailbox',['../tutorial_sa1.html#i-ram--the-mailbox',1,'']]],
  ['i_20ram_20layout_20convention_8',['I-RAM Layout Convention',['../tutorial_sa1.html#i-ram-layout-convention',1,'']]],
  ['icon_5fcoin_9',['ICON_COIN',['../games_2rpg_2main_8c.html#a638e0ca056784c6a2383b0598d23cc1a',1,'main.c']]],
  ['icon_5fheart_10',['ICON_HEART',['../games_2rpg_2main_8c.html#ac6ea2e993de0a9fac8491ef3777499bb',1,'main.c']]],
  ['icon_5fheart_5fempty_11',['ICON_HEART_EMPTY',['../games_2rpg_2main_8c.html#ad5a4ee24771b664a68097ee80da1a522',1,'main.c']]],
  ['idea_20in_20one_20screen_12',['idea in one screen',['../examples_audio.html#the-idea-in-one-screen',1,'The idea in one screen'],['../examples_backgrounds.html#the-idea-in-one-screen-1',1,'The idea in one screen'],['../examples_color.html#the-idea-in-one-screen-2',1,'The idea in one screen'],['../examples_hdma.html#the-idea-in-one-screen-3',1,'The idea in one screen'],['../examples_input.html#the-idea-in-one-screen-4',1,'The idea in one screen'],['../examples_maps.html#the-idea-in-one-screen-5',1,'The idea in one screen'],['../examples_mode7.html#the-idea-in-one-screen-6',1,'The idea in one screen'],['../examples_scrolling.html#the-idea-in-one-screen-7',1,'The idea in one screen'],['../examples_transitions.html#the-idea-in-one-screen-8',1,'The idea in one screen'],['../examples_windows.html#the-idea-in-one-screen-9',1,'The idea in one screen']]],
  ['identical_20to_20lorom_13',['2. The code is identical to LoROM',['../examples_memory_hirom_demo.html#autotoc_md2-the-code-is-identical-to-lorom',1,'']]],
  ['idiom_14',['The workspace idiom',['../tutorial_object.html#the-workspace-idiom',1,'']]],
  ['idle_20loop_15',['5. Idle Loop',['../examples_backgrounds_mode1_lz77.html#autotoc_md5-idle-loop',1,'']]],
  ['ids_16',['4. Animate by changing frame IDs',['../examples_sprites_dynamic_sprite.html#autotoc_md4-animate-by-changing-frame-ids',1,'']]],
  ['if_20it_20breaks_17',['if it breaks',['../examples_backgrounds_mode2.html#what-to-observe--if-it-breaks',1,'What to observe / if it breaks'],['../examples_basics_game_skeleton.html#what-to-observe--if-it-breaks-1',1,'What to observe / if it breaks'],['../examples_basics_panel_hud.html#what-to-observe--if-it-breaks-2',1,'What to observe / if it breaks'],['../examples_color_palette_cycle.html#what-to-observe--if-it-breaks-3',1,'What to observe / if it breaks'],['../examples_color_shadow_tint.html#what-to-observe--if-it-breaks-4',1,'What to observe / if it breaks'],['../examples_sprites_sprite_swarm.html#what-to-observe--if-it-breaks-5',1,'What to observe / if it breaks']]],
  ['ignored_20the_20bank_20byte_20of_20your_20pointer_20—_20fixed_202026_2009_2018_18',['🟢 &lt;span class=&quot;tt&quot;&gt;objLoadObjects&lt;/span&gt; ignored the bank byte of your pointer — fixed 2026-09-18',['../tutorial_object.html#autotoc_md-objloadobjects-ignored-the-bank-byte-of-your-pointer--fixed-2026-09-18',1,'']]],
  ['images_20to_20text_20tiles_19',['font2snes — font images to text tiles',['../tools_font2snes.html',1,'tools']]],
  ['images_20to_20tiles_20palettes_20maps_20',['gfx4snes — images to tiles, palettes &amp;amp; maps',['../tools_gfx4snes.html',1,'tools']]],
  ['img2snes_20—_20rgb_20artwork_20to_20indexed_20palettes_21',['img2snes — RGB artwork to indexed palettes',['../tools_img2snes.html',1,'tools']]],
  ['img2snes_2emd_22',['img2snes.md',['../img2snes_8md.html',1,'']]],
  ['implementation_23',['Implementation',['../examples_transitions_fading.html#basic-fade-implementation',1,'Basic Fade Implementation'],['../tutorial_game_states.html#title-screen-implementation',1,'Title Screen Implementation']]],
  ['important_3a_20call_20snesmodprocess_24',['Important: Call snesmodProcess()!',['../tutorial_audio.html#important-call-snesmodprocess',1,'']]],
  ['in_25',['Fade Out / Fade In',['../tutorial_game_states.html#fade-out--fade-in',1,'']]],
  ['in_26',['Opting the module in',['../tutorial_object.html#opting-the-module-in',1,'']]],
  ['in_20a_20ram_20buffer_20not_20on_20the_20screen_27',['Text lands in a RAM buffer, not on the screen',['../tutorial_text.html#text-lands-in-a-ram-buffer-not-on-the-screen',1,'']]],
  ['in_20any_20bank_20just_20work_28',['🟢 SUPERFREE assets in any bank just work',['../tutorial_dma.html#autotoc_md-superfree-assets-in-any-bank-just-work',1,'']]],
  ['in_20assembly_29',['2. Register Object Types in Assembly',['../examples_games_mapandobjects.html#autotoc_md2-register-object-types-in-assembly',1,'']]],
  ['in_20black_20to_20full_30',['Fade In (Black to Full)',['../examples_transitions_fading.html#fade-in-black-to-full',1,'']]],
  ['in_20ci_31',['Gating a budget in CI',['../tutorial_profiling.html#gating-a-budget-in-ci',1,'']]],
  ['in_20claude_32',['Project knowledge in &lt;span class=&quot;tt&quot;&gt;.claude/&lt;/span&gt;',['../contributing.html#project-knowledge-in-claude',1,'']]],
  ['in_20commercial_20games_33',['Window Shapes in Commercial Games',['../examples_windows_window.html#window-shapes-in-commercial-games',1,'']]],
  ['in_20force_20blank_34',['1. Initialize and Stay in Force Blank',['../examples_backgrounds_mode1_lz77.html#autotoc_md1-initialize-and-stay-in-force-blank',1,'']]],
  ['in_20framework_20tutorial_35',['The Opt-In Framework Tutorial',['../tutorial_framework.html',1,'index']]],
  ['in_20games_36',['Using rngNext() in Games',['../examples_basics_random.html#using-rngnext-in-games',1,'']]],
  ['in_20hex_37',['2. Drawing Letters in Hex',['../examples_fundamentals_text_glyphs.html#autotoc_md2-drawing-letters-in-hex',1,'']]],
  ['in_20mesen2_38',['Debugging in Mesen2',['../tutorial_sa1.html#debugging-in-mesen2',1,'']]],
  ['in_20mode_201_39',['in Mode 1',['../examples_sprites_sprite_sizes.html#autotoc_md1-set-up-text-on-bg1-4bpp-in-mode-1',1,'1. Set up text on BG1 (4bpp in Mode 1)'],['../examples_backgrounds_mode1_bg3_priority.html#bg3-is-2bpp-in-mode-1',1,'BG3 is 2bpp in Mode 1']]],
  ['in_20nmi_40',['🟡 WRAM data port &lt;span class=&quot;tt&quot;&gt;$2180&lt;/span&gt;–&lt;span class=&quot;tt&quot;&gt;$2183&lt;/span&gt; is NOT safe in NMI',['../tutorial_dma.html#autotoc_md-wram-data-port-21802183-is-not-safe-in-nmi',1,'']]],
  ['in_20nmi_20caught_20at_20build_20time_41',['🟢 WRAM data port &lt;span class=&quot;tt&quot;&gt;$2180–$2183&lt;/span&gt; race in NMI (caught at build time)',['../KNOWN_LIMITATIONS.html#autotoc_md-wram-data-port-21802183-race-in-nmi-caught-at-build-time',1,'']]],
  ['in_20oam_42',['16x16 Tiles in OAM',['../examples_sprites_animated_sprite.html#autotoc_md16x16-tiles-in-oam',1,'']]],
  ['in_20one_20call_43',['Setting up in one call',['../tutorial_text.html#setting-up-in-one-call',1,'']]],
  ['in_20one_20paragraph_44',['The handshake, in one paragraph',['../tutorial_dsp1.html#the-handshake-in-one-paragraph',1,'']]],
  ['in_20one_20screen_45',['in one screen',['../examples_sprites.html#reference--oam-in-one-screen',1,'Reference — OAM in one screen'],['../examples_audio.html#the-idea-in-one-screen',1,'The idea in one screen'],['../examples_backgrounds.html#the-idea-in-one-screen-1',1,'The idea in one screen'],['../examples_color.html#the-idea-in-one-screen-2',1,'The idea in one screen'],['../examples_hdma.html#the-idea-in-one-screen-3',1,'The idea in one screen'],['../examples_input.html#the-idea-in-one-screen-4',1,'The idea in one screen'],['../examples_maps.html#the-idea-in-one-screen-5',1,'The idea in one screen'],['../examples_mode7.html#the-idea-in-one-screen-6',1,'The idea in one screen'],['../examples_scrolling.html#the-idea-in-one-screen-7',1,'The idea in one screen'],['../examples_transitions.html#the-idea-in-one-screen-8',1,'The idea in one screen'],['../examples_windows.html#the-idea-in-one-screen-9',1,'The idea in one screen'],['../examples_chips.html#the-two-chips-in-one-screen',1,'The two chips, in one screen']]],
  ['in_20one_20table_46',['What is different, in one table',['../migrating_pvsneslib.html#what-is-different-in-one-table',1,'']]],
  ['in_20opensnes_47',['Audio Options in OpenSNES',['../tutorial_audio.html#audio-options-in-opensnes',1,'']]],
  ['in_20practice_48',['in practice',['../tools_gfx4snes.html#see-it-in-practice',1,'See it in practice'],['../tools_palplan.html#see-it-in-practice-1',1,'See it in practice'],['../tools_smconv.html#see-it-in-practice-2',1,'See it in practice'],['../tools_tmx2snes.html#see-it-in-practice-3',1,'See it in practice'],['../tools_wav2brr.html#see-it-in-practice-4',1,'See it in practice']]],
  ['in_20setup_20under_20forced_20blank_49',['These calls belong in setup, under forced blank',['../tutorial_framework.html#these-calls-belong-in-setup-under-forced-blank',1,'']]],
  ['in_20since_202026_2009_2019_50',['🟢 &lt;span class=&quot;tt&quot;&gt;objCollidMap1D&lt;/span&gt; had no friction, and no way to get any — opt-in since 2026-09-19',['../tutorial_object.html#autotoc_md-objcollidmap1d-had-no-friction-and-no-way-to-get-any--opt-in-since-2026-09-19',1,'']]],
  ['in_20sram_51',['🟠 Cannot store pointers in SRAM',['../tutorial_sram.html#autotoc_md-cannot-store-pointers-in-sram',1,'']]],
  ['in_20the_20asset_20banks_20since_20127_203_52',['🟢 Bank $00 ROM: code only — C const data lives in the asset banks (since #127.3)',['../KNOWN_LIMITATIONS.html#autotoc_md-bank-00-rom-code-only--c-const-data-lives-in-the-asset-banks-since-1273',1,'']]],
  ['in_20the_20lib_20chantier_20b6_202026_2005_2009_53',['&lt;span class=&quot;tt&quot;&gt;atan2&lt;/span&gt; and &lt;span class=&quot;tt&quot;&gt;sqrt&lt;/span&gt; ship in the lib (chantier B6, 2026-05-09)',['../tutorial_math.html#atan2-and-sqrt-ship-in-the-lib-chantier-b6-2026-05-09',1,'']]],
  ['in_20the_20main_20loop_54',['Per-frame DMA in the main loop',['../tutorial_dma.html#per-frame-dma-in-the-main-loop',1,'']]],
  ['in_20the_20makefile_55',['in the Makefile',['../examples_memory_hirom_demo.html#autotoc_md1-enable-hirom-in-the-makefile',1,'1. Enable HiROM in the Makefile'],['../examples_memory_save_game.html#autotoc_md4-enable-sram-in-the-makefile',1,'4. Enable SRAM in the Makefile']]],
  ['in_20the_20nmi_20handler_56',['🟡 HDMA fires before the user callback in the NMI handler',['../tutorial_hdma.html#autotoc_md-hdma-fires-before-the-user-callback-in-the-nmi-handler',1,'']]],
  ['in_20the_20way_57',['When the framework gets in the way',['../tutorial_framework.html#when-the-framework-gets-in-the-way',1,'']]],
  ['in_20tiled_58',['Authoring the level in Tiled',['../tools_tmx2snes.html#authoring-the-level-in-tiled',1,'']]],
  ['in_20tiled_20convert_20for_20the_20snes_59',['The workflow: design in Tiled, convert for the SNES',['../craft_tiles_to_levels.html#the-workflow-design-in-tiled-convert-for-the-snes',1,'']]],
  ['in_20time_60',['Recipe 1 — Inspect the machine at a point in time',['../tutorial_debugging.html#recipe-1--inspect-the-machine-at-a-point-in-time',1,'']]],
  ['in_20two_20lines_61',['5. Gravity in Two Lines',['../examples_games_likemario.html#autotoc_md5-gravity-in-two-lines',1,'']]],
  ['in_20vblank_20mapupdate_20does_20not_62',['🟠 &lt;span class=&quot;tt&quot;&gt;mapVblank()&lt;/span&gt; belongs in VBlank, &lt;span class=&quot;tt&quot;&gt;mapUpdate()&lt;/span&gt; does not',['../tutorial_map.html#autotoc_md-mapvblank-belongs-in-vblank-mapupdate-does-not',1,'']]],
  ['in_20vram_63',['Sprite Sheets in VRAM',['../examples_sprites_animated_sprite.html#sprite-sheets-in-vram',1,'']]],
  ['in_20what_20comes_20out_64',['in what comes out',['../tools_font2snes.html#what-goes-in-what-comes-out',1,'What goes in, what comes out'],['../tools_gfx4snes.html#what-goes-in-what-comes-out-1',1,'What goes in, what comes out'],['../tools_img2snes.html#what-goes-in-what-comes-out-2',1,'What goes in, what comes out'],['../tools_palplan.html#what-goes-in-what-comes-out-3',1,'What goes in, what comes out'],['../tools_smconv.html#what-goes-in-what-comes-out-4',1,'What goes in, what comes out'],['../tools_tmx2snes.html#what-goes-in-what-comes-out-5',1,'What goes in, what comes out'],['../tools_wav2brr.html#what-goes-in-what-comes-out-6',1,'What goes in, what comes out']]],
  ['in_20your_20makefile_65',['in Your Makefile',['../tutorial_sa1.html#autotoc_md1-enable-sa-1-in-your-makefile',1,'1. Enable SA-1 in Your Makefile'],['../tutorial_superfx.html#autotoc_md1-enable-superfx-in-your-makefile',1,'1. Enable SuperFX in Your Makefile']]],
  ['inclusive_20on_20both_20ends_66',['Boundaries are inclusive on both ends',['../tutorial_window.html#boundaries-are-inclusive-on-both-ends',1,'']]],
  ['increment_67',['$2115 - VMAIN (VRAM Address Increment)',['../registers.html#autotoc_md2115---vmain-vram-address-increment',1,'']]],
  ['independent_20background_20scrolling_68',['Independent Background Scrolling',['../examples_scrolling_mixed_scroll.html#independent-background-scrolling',1,'']]],
  ['independent_20control_69',['Independent Control',['../examples_input_two_players.html#independent-control',1,'']]],
  ['index_20—_20by_20what_20you_20are_20trying_20to_20do_70',['API index — by what you are trying to do',['../api_index.html',1,'']]],
  ['index_20tracking_20after_20branch_20merges_20lint_20enforced_71',['🟢 WLA-DX loses &lt;span class=&quot;tt&quot;&gt;.ACCU&lt;/span&gt; / &lt;span class=&quot;tt&quot;&gt;.INDEX&lt;/span&gt; tracking after branch merges (lint-enforced)',['../KNOWN_LIMITATIONS.html#autotoc_md-wla-dx-loses-accu--index-tracking-after-branch-merges-lint-enforced',1,'']]],
  ['indexed_20palettes_72',['img2snes — RGB artwork to indexed palettes',['../tools_img2snes.html',1,'tools']]],
  ['indirect_20gradient_73',['HDMA Indirect Gradient',['../examples_hdma_hdma_indirect_gradient.html',1,'examples_hdma']]],
  ['indirect_20hdma_20—_20examples_20hdma_20hdma_5findirect_5fgradient_74',['Indirect HDMA — &lt;span class=&quot;tt&quot;&gt;examples/hdma/hdma_indirect_gradient&lt;/span&gt;',['../tutorial_hdma.html#indirect-hdma--exampleshdmahdma_indirect_gradient',1,'']]],
  ['infinite_20scrolling_75',['Continuous / Infinite Scrolling',['../tutorial_scrolling.html#continuous--infinite-scrolling',1,'']]],
  ['inidisp_20display_20control_76',['$2100 - INIDISP (Display Control)',['../registers.html#autotoc_md2100---inidisp-display-control',1,'']]],
  ['inidisp_20register_77',['INIDISP Register',['../examples_transitions_fading.html#inidisp-register',1,'']]],
  ['inidisp_5fbrightness_78',['INIDISP_BRIGHTNESS',['../group__reg__const.html#gaaf3fc9440cf26732b7b05473e07bfec4',1,'registers.h']]],
  ['inidisp_5fforce_5fblank_79',['INIDISP_FORCE_BLANK',['../group__reg__const.html#gab18ce2bcee19d38256a74af702ebe4a3',1,'registers.h']]],
  ['init_80',['init',['../structScene.html#a792c89d6cc91c1e09330819a3f15fe10',1,'Scene']]],
  ['init_5fpalette_81',['init_palette',['../memory_2hirom__demo_2main_8c.html#af7061e0598975eadee3bb865f4cfdad0',1,'main.c']]],
  ['initdemomap32x32_82',['initDemoMap32x32',['../maps_2dynamic__map_2main_8c.html#a654d38d017c0c89fe361aa787dfcc0a5',1,'main.c']]],
  ['initdemomap64x64_83',['initDemoMap64x64',['../maps_2dynamic__map_2main_8c.html#a9f6bc00b38bcfe94d921eed5e1c10c76',1,'main.c']]],
  ['initial_20setup_84',['Force Blank for Initial Setup',['../examples_sprites_dynamic_sprite.html#force-blank-for-initial-setup',1,'']]],
  ['initialization_85',['Initialization',['../examples_input_superscope.html#autotoc_md1-initialization',1,'1. Initialization'],['../group__audio__init.html',1,'Initialization'],['../group__snesmod__init.html',1,'Initialization'],['../tutorial_animation.html#initialization',1,'Initialization'],['../examples_audio_snesmod_music.html#initialization-1',1,'Initialization'],['../examples_audio_snesmod_sfx.html#snesmod-initialization',1,'SNESMOD Initialization']]],
  ['initialize_20and_20stay_20in_20force_20blank_86',['1. Initialize and Stay in Force Blank',['../examples_backgrounds_mode1_lz77.html#autotoc_md1-initialize-and-stay-in-force-blank',1,'']]],
  ['initialize_20display_87',['Initialize Display',['../tutorial_graphics.html#initialize-display',1,'']]],
  ['initialize_20from_20c_88',['3. Initialize from C',['../tutorial_sa1.html#autotoc_md3-initialize-from-c',1,'']]],
  ['initialize_20oam_89',['Initialize OAM',['../tutorial_sprites.html#initialize-oam',1,'']]],
  ['initialize_20text_20and_20detect_20mouse_90',['1. Initialize Text and Detect Mouse',['../examples_input_mouse.html#autotoc_md1-initialize-text-and-detect-mouse',1,'']]],
  ['initialize_20the_20dynamic_20sprite_20engine_91',['1. Initialize the dynamic sprite engine',['../examples_sprites_dynamic_sprite.html#autotoc_md1-initialize-the-dynamic-sprite-engine',1,'']]],
  ['initialize_20the_20map_20and_20sprite_20system_92',['1. Initialize the Map and Sprite System',['../examples_games_mapandobjects.html#autotoc_md1-initialize-the-map-and-sprite-system',1,'']]],
  ['initialize_20the_20transformation_93',['2. Initialize the transformation',['../examples_mode7_rotate_scale.html#autotoc_md2-initialize-the-transformation',1,'']]],
  ['initializers_94',['Static variables with initializers',['../troubleshooting.html#static-variables-with-initializers',1,'']]],
  ['initspritemap32x32_95',['initSpriteMap32x32',['../map32x32_8c.html#aa2ad4600d3cbd188ae7ec1735ae02540',1,'initSpriteMap32x32(u16 len):&#160;map32x32.c'],['../map32x32_8h.html#aa2ad4600d3cbd188ae7ec1735ae02540',1,'initSpriteMap32x32(u16 len):&#160;map32x32.c']]],
  ['initspritemap64x64_96',['initSpriteMap64x64',['../map64x64_8c.html#a4188ed43499d3946aae9251087b1f175',1,'initSpriteMap64x64(u16 len):&#160;map64x64.c'],['../map64x64_8h.html#a4188ed43499d3946aae9251087b1f175',1,'initSpriteMap64x64(u16 len):&#160;map64x64.c']]],
  ['inline_20assembly_20is_20refused_97',['🟡 Inline assembly is refused',['../KNOWN_LIMITATIONS.html#autotoc_md-inline-assembly-is-refused',1,'']]],
  ['input_98',['Input',['../examples_input_controller.html',1,'Controller Input'],['../group__examples.html#input',1,'Input'],['../api_index.html#input-1',1,'Input'],['../group__mouse__input.html',1,'Mouse Input'],['../group__scope__input.html',1,'Super Scope Input']]],
  ['input_20and_20state_20changes_99',['Input and State Changes',['../tutorial_animation.html#input-and-state-changes',1,'']]],
  ['input_20latency_100',['Input Latency',['../examples_input_two_players.html#input-latency',1,'']]],
  ['input_20not_20working_101',['Controller input not working',['../troubleshooting.html#controller-input-not-working',1,'']]],
  ['input_20peripherals_102',['Input peripherals',['../examples_input.html',1,'Input &amp; peripherals'],['../examples_by_category.html#input--peripherals',1,'Input &amp;amp; peripherals']]],
  ['input_20reading_103',['4. Input Reading',['../examples_scrolling_continuous_scroll.html#autotoc_md4-input-reading',1,'']]],
  ['input_20tutorial_104',['Controller Input Tutorial',['../tutorial_input.html',1,'index']]],
  ['input_20works_20on_20the_20snes_105',['How Input Works on the SNES',['../examples_input_controller.html#how-input-works-on-the-snes',1,'']]],
  ['input_2eh_106',['input.h',['../input_8h.html',1,'']]],
  ['input_2emd_107',['input.md',['../input_8md.html',1,'']]],
  ['inputs_20interaction_108',['Inputs / interaction',['../basics_2fix32__orbit_2main_8c.html#inputs--interaction',1,'']]],
  ['ins_109',['Framework opt-ins',['../index.html#framework-opt-ins',1,'']]],
  ['inside_110',['Inversion: Show Inside',['../examples_windows_window.html#inversion-show-inside',1,'']]],
  ['inside_20nmiset_20callbacks_111',['🟡 &lt;span class=&quot;tt&quot;&gt;fixMul()&lt;/span&gt; / &lt;span class=&quot;tt&quot;&gt;fixLerp()&lt;/span&gt; are not safe inside nmiSet() callbacks',['../KNOWN_LIMITATIONS.html#autotoc_md-fixmul--fixlerp-are-not-safe-inside-nmiset-callbacks',1,'']]],
  ['inside_3a_112',['Profiling from inside: &lt;span class=&quot;tt&quot;&gt;&amp;lt;snes/profile.h&amp;gt;&lt;/span&gt;',['../tutorial_profiling.html#profiling-from-inside-snesprofileh',1,'']]],
  ['inspect_20the_20machine_20at_20a_20point_20in_20time_113',['Recipe 1 — Inspect the machine at a point in time',['../tutorial_debugging.html#recipe-1--inspect-the-machine-at-a-point-in-time',1,'']]],
  ['install_20prerequisites_114',['Install Prerequisites',['../getting_started.html#a1-install-prerequisites',1,'A1. Install Prerequisites'],['../getting_started.html#b1-install-prerequisites',1,'B1. Install Prerequisites']]],
  ['instead_20of_20a_20switch_115',['Why a framework instead of a switch',['../examples_basics_scene_stack.html#why-a-framework-instead-of-a-switch',1,'']]],
  ['instead_20of_20zeros_20fixed_202026_2009_2015_116',['🟢 &lt;span class=&quot;tt&quot;&gt;sramClear()&lt;/span&gt; wrote a byte ramp instead of zeros (fixed 2026-09-15)',['../KNOWN_LIMITATIONS.html#autotoc_md-sramclear-wrote-a-byte-ramp-instead-of-zeros-fixed-2026-09-15',1,'']]],
  ['int_20and_20long_20sizes_20and_20semantics_20match_20the_20w65816_20target_117',['🟢 &lt;span class=&quot;tt&quot;&gt;int&lt;/span&gt; and &lt;span class=&quot;tt&quot;&gt;long&lt;/span&gt; sizes AND semantics match the w65816 target',['../KNOWN_LIMITATIONS.html#autotoc_md-int-and-long-sizes-and-semantics-match-the-w65816-target',1,'']]],
  ['int_20and_20long_20sizes_20are_20correct_20on_20this_20target_20since_20chantier_20a1_118',['🟢 &lt;span class=&quot;tt&quot;&gt;int&lt;/span&gt; and &lt;span class=&quot;tt&quot;&gt;long&lt;/span&gt; sizes are correct on this target (since chantier A1)',['../tutorial_math.html#autotoc_md-int-and-long-sizes-are-correct-on-this-target-since-chantier-a1',1,'']]],
  ['integration_119',['Tiled Map Editor Integration',['../examples_maps_tiled.html',1,'examples_maps']]],
  ['integration_20lessons_20this_20port_20surfaced_120',['Two integration lessons this port surfaced',['../examples_mode7_perspective_rotate.html#two-integration-lessons-this-port-surfaced',1,'']]],
  ['intentionally_20absent_121',['🟡 SuperFX C support is intentionally absent',['../KNOWN_LIMITATIONS.html#autotoc_md-superfx-c-support-is-intentionally-absent',1,'']]],
  ['interact_122',['🟠 Half-mode and saturation interact',['../tutorial_colormath.html#autotoc_md-half-mode-and-saturation-interact',1,'']]],
  ['interaction_123',['Inputs / interaction',['../basics_2fix32__orbit_2main_8c.html#inputs--interaction',1,'']]],
  ['interactive_20debugging_20with_20luna_124',['Interactive Debugging with luna',['../tutorial_debugging.html',1,'index']]],
  ['interactive_20debugging_20with_20luna_125',['Interactive debugging with luna',['../troubleshooting.html#interactive-debugging-with-luna',1,'']]],
  ['interactive_20feedback_126',['4. Interactive feedback',['../examples_memory_hirom_demo.html#autotoc_md4-interactive-feedback',1,'']]],
  ['interlace_20512_20×_20448_127',['Hi-res text — BG Mode 5 + interlace (512 × 448)',['../examples_backgrounds_mode5_hires.html',1,'examples_backgrounds']]],
  ['interlace_20modes_205_206_20setini_128',['Hi-res and interlace (Modes 5/6, SETINI)',['../tutorial_graphics.html#hi-res-and-interlace-modes-56-setini',1,'']]],
  ['interleaved_20vram_20format_129',['The interleaved VRAM format',['../tutorial_mode7.html#the-interleaved-vram-format',1,'']]],
  ['interleaved_20vram_3a_20dmacopyvrammode7_20does_20the_20two_20passes_130',['🟢 Interleaved VRAM: &lt;span class=&quot;tt&quot;&gt;dmaCopyVramMode7&lt;/span&gt; does the two passes',['../tutorial_mode7.html#autotoc_md-interleaved-vram-dmacopyvrammode7-does-the-two-passes',1,'']]],
  ['interpolation_131',['Smooth interpolation',['../tutorial_math.html#smooth-interpolation',1,'']]],
  ['interrupt_20control_132',['Interrupt Control',['../registers.html#interrupt-control',1,'']]],
  ['interrupt_20enable_133',['$4200 - NMITIMEN (Interrupt Enable)',['../registers.html#autotoc_md4200---nmitimen-interrupt-enable',1,'']]],
  ['interrupt_2eh_134',['interrupt.h',['../interrupt_8h.html',1,'']]],
  ['into_20nowhere_20—_20fixed_202026_2009_2019_135',['🟢 A type with no registered callbacks jumped into nowhere — fixed 2026-09-19',['../tutorial_object.html#autotoc_md-a-type-with-no-registered-callbacks-jumped-into-nowhere--fixed-2026-09-19',1,'']]],
  ['into_20the_20world_136',['Bringing objects into the world',['../tutorial_object.html#bringing-objects-into-the-world',1,'']]],
  ['into_20vram_137',['1. Load sprite graphics into VRAM',['../examples_sprites_simple_sprite.html#autotoc_md1-load-sprite-graphics-into-vram',1,'']]],
  ['intuitive_138',['🟠 &lt;span class=&quot;tt&quot;&gt;colorMathSetSource&lt;/span&gt; polarity is opposite of intuitive',['../tutorial_colormath.html#autotoc_md-colormathsetsource-polarity-is-opposite-of-intuitive',1,'']]],
  ['inversion_3a_20show_20inside_139',['Inversion: Show Inside',['../examples_windows_window.html#inversion-show-inside',1,'']]],
  ['ir_20size_20is_204_20bytes_20chantier_20a6_20a7_202026_2005_2015_140',['🟢 Pointer IR size is 4 bytes (chantier A6+A7, 2026-05-15)',['../KNOWN_LIMITATIONS.html#autotoc_md-pointer-ir-size-is-4-bytes-chantier-a6a7-2026-05-15',1,'']]],
  ['iris_5fradius_141',['iris_radius',['../structEffectState.html#a343a7c940aad945667eb9b9d69f9ee8a',1,'EffectState']]],
  ['irq_20status_142',['$4211 - TIMEUP (IRQ Status)',['../registers.html#autotoc_md4211---timeup-irq-status',1,'']]],
  ['irq_20streaming_143',['When HDMA isn&apos;t enough: H-timer IRQ streaming',['../tutorial_hdma.html#when-hdma-isnt-enough-h-timer-irq-streaming',1,'']]],
  ['irq_20timer_144',['$4207-$420A - HTIMEx/VTIMEx (IRQ Timer)',['../registers.html#autotoc_md4207-420a---htimexvtimex-irq-timer',1,'']]],
  ['irq_5fhtimer_145',['IRQ_HTIMER',['../interrupt_8h.html#aaece8b46f8a1058e500a960282748b8e',1,'interrupt.h']]],
  ['irq_5fvtimer_146',['IRQ_VTIMER',['../interrupt_8h.html#a947b19bbddfaa5c9b41960ba1027bae9',1,'interrupt.h']]],
  ['irqclear_147',['irqClear',['../interrupt_8h.html#abb372cb6d422bba46803658ccce77f42',1,'interrupt.h']]],
  ['irqdisable_148',['irqDisable',['../interrupt_8h.html#a7824431e7a255f980b881a0e29773a1a',1,'interrupt.h']]],
  ['irqenable_149',['irqEnable',['../interrupt_8h.html#ada4c1ec4449e797d007bd17766156e9f',1,'interrupt.h']]],
  ['irqset_150',['irqSet',['../interrupt_8h.html#a69f348e722cc5916ff3b4007eadcc928',1,'interrupt.h']]],
  ['irqsetbank_151',['irqSetBank',['../interrupt_8h.html#ae06802aa2d547c5c1481fd24b5fd5785',1,'interrupt.h']]],
  ['irqsethtimer_152',['irqSetHTimer',['../interrupt_8h.html#a979596926059d6d8cab64e9b719a7df9',1,'interrupt.h']]],
  ['irqsetvtimer_153',['irqSetVTimer',['../interrupt_8h.html#a1579b3231b62226f9bf5ba4077660409',1,'interrupt.h']]],
  ['is_154',['is',['../tutorial_panel.html#what-a-panel-is',1,'What a panel is'],['../tutorial_colormath.html#what-colour-math-actually-is',1,'What colour math actually is'],['../tutorial_dma.html#what-dma-actually-is',1,'What DMA actually is'],['../tutorial_hdma.html#what-hdma-actually-is',1,'What HDMA actually is'],['../tutorial_mode7.html#what-mode-7-actually-is',1,'What Mode 7 actually is'],['../tutorial_mosaic.html#what-mosaic-actually-is',1,'What mosaic actually is'],['../tutorial_sram.html#what-sram-actually-is',1,'What SRAM actually is'],['../tutorial_dsp1.html#what-the-chip-actually-is',1,'What the chip actually is'],['../tutorial_map.html#what-the-map-module-is',1,'What the map module is']]],
  ['is_202bpp_20in_20mode_201_155',['BG3 is 2bpp in Mode 1',['../examples_backgrounds_mode1_bg3_priority.html#bg3-is-2bpp-in-mode-1',1,'']]],
  ['is_204_20bytes_20chantier_20a6_20a7_202026_2005_2015_156',['🟢 Pointer IR size is 4 bytes (chantier A6+A7, 2026-05-15)',['../KNOWN_LIMITATIONS.html#autotoc_md-pointer-ir-size-is-4-bytes-chantier-a6a7-2026-05-15',1,'']]],
  ['is_204_20kb_20per_20frame_157',['is 4 KB per frame',['../tutorial_dma.html#autotoc_md-vblank-dma-budget-is-4-kb-per-frame',1,'🔴 VBlank DMA budget is ~4 KB per frame'],['../KNOWN_LIMITATIONS.html#autotoc_md-vblank-dma-budget-is-4-kb-per-frame-1',1,'🔴 VBlank DMA budget is ~4 KB per frame']]],
  ['is_20a_20memset_20not_20a_20write_20protect_158',['🟡 &lt;span class=&quot;tt&quot;&gt;sramClear&lt;/span&gt; is a memset, not a write-protect',['../tutorial_sram.html#autotoc_md-sramclear-is-a-memset-not-a-write-protect',1,'']]],
  ['is_20a_20page_20number_20not_20a_20vram_20address_159',['The &lt;span class=&quot;tt&quot;&gt;name_base&lt;/span&gt; argument is a page number, not a VRAM address',['../tutorial_sprites.html#the-name_base-argument-is-a-page-number-not-a-vram-address',1,'']]],
  ['is_20always_20last_160',['Trap 2: &lt;span class=&quot;tt&quot;&gt;setScreenOn()&lt;/span&gt; is always last',['../migrating_pvsneslib.html#trap-2-setscreenon-is-always-last',1,'']]],
  ['is_20an_20empty_20window_161',['&lt;span class=&quot;tt&quot;&gt;left &amp;gt; right&lt;/span&gt; is an &quot;empty&quot; window',['../tutorial_window.html#left--right-is-an-empty-window',1,'']]],
  ['is_20and_20what_20it_20is_20not_162',['What the object engine is, and what it is not',['../tutorial_object.html#what-the-object-engine-is-and-what-it-is-not',1,'']]],
  ['is_20automated_20don_20t_20double_20up_163',['🟠 OAM DMA is automated, don&apos;t double-up',['../tutorial_dma.html#autotoc_md-oam-dma-is-automated-dont-double-up',1,'']]],
  ['is_20bigger_20than_20the_20screen_164',['1. The World Is Bigger Than the Screen',['../examples_games_likemario.html#autotoc_md1-the-world-is-bigger-than-the-screen',1,'']]],
  ['is_20bigger_20than_20vram_20—_20so_20stream_20it_165',['The level is bigger than VRAM — so stream it',['../craft_tiles_to_levels.html#the-level-is-bigger-than-vram--so-stream-it',1,'']]],
  ['is_20black_166',['ROM loads but screen is black',['../troubleshooting.html#rom-loads-but-screen-is-black',1,'']]],
  ['is_20different_20in_20one_20table_167',['What is different, in one table',['../migrating_pvsneslib.html#what-is-different-in-one-table',1,'']]],
  ['is_20drawn_168',['Fundamentals: how a glyph is drawn',['../examples_fundamentals_text_glyphs.html',1,'examples_fundamentals']]],
  ['is_20far_20and_20casting_20const_20away_20breaks_20it_169',['Trap 5: const data is far, and casting &lt;span class=&quot;tt&quot;&gt;const&lt;/span&gt; away breaks it',['../migrating_pvsneslib.html#trap-5-const-data-is-far-and-casting-const-away-breaks-it',1,'']]],
  ['is_20full_170',['🟡 &lt;span class=&quot;tt&quot;&gt;objNew&lt;/span&gt; leaves &lt;span class=&quot;tt&quot;&gt;objgetid&lt;/span&gt; stale when the pool is full',['../tutorial_object.html#autotoc_md-objnew-leaves-objgetid-stale-when-the-pool-is-full',1,'']]],
  ['is_20hdma_171',['1. What Is HDMA?',['../examples_hdma_hdma_wave.html#autotoc_md1-what-is-hdma',1,'']]],
  ['is_20identical_20to_20lorom_172',['2. The code is identical to LoROM',['../examples_memory_hirom_demo.html#autotoc_md2-the-code-is-identical-to-lorom',1,'']]],
  ['is_20intentionally_20absent_173',['🟡 SuperFX C support is intentionally absent',['../KNOWN_LIMITATIONS.html#autotoc_md-superfx-c-support-is-intentionally-absent',1,'']]],
  ['is_20jerky_174',['Scrolling is jerky',['../troubleshooting.html#scrolling-is-jerky',1,'']]],
  ['is_20no_20printf_175',['1. There Is No printf',['../examples_fundamentals_text_glyphs.html#autotoc_md1-there-is-no-printf',1,'']]],
  ['is_20not_176',['What the object engine is, and what it is not',['../tutorial_object.html#what-the-object-engine-is-and-what-it-is-not',1,'']]],
  ['is_20not_20reset_20by_20consoleinit_177',['🟡 Mosaic state is not reset by &lt;span class=&quot;tt&quot;&gt;consoleInit&lt;/span&gt;',['../tutorial_mosaic.html#autotoc_md-mosaic-state-is-not-reset-by-consoleinit',1,'']]],
  ['is_20not_20safe_20in_20nmi_178',['🟡 WRAM data port &lt;span class=&quot;tt&quot;&gt;$2180&lt;/span&gt;–&lt;span class=&quot;tt&quot;&gt;$2183&lt;/span&gt; is NOT safe in NMI',['../tutorial_dma.html#autotoc_md-wram-data-port-21802183-is-not-safe-in-nmi',1,'']]],
  ['is_20off_20by_20one_3a_20the_20ppu_20never_20outputs_20scanline_200_20hidden_20by_20the_20lib_179',['🟢 Vertical scroll is off by one: the PPU never outputs scanline 0 (hidden by the lib)',['../KNOWN_LIMITATIONS.html#autotoc_md-vertical-scroll-is-off-by-one-the-ppu-never-outputs-scanline-0-hidden-by-the-lib',1,'']]],
  ['is_20opposite_20of_20intuitive_180',['🟠 &lt;span class=&quot;tt&quot;&gt;colorMathSetSource&lt;/span&gt; polarity is opposite of intuitive',['../tutorial_colormath.html#autotoc_md-colormathsetsource-polarity-is-opposite-of-intuitive',1,'']]],
  ['is_20per_20byte_181',['🟡 Throughput is per-byte',['../tutorial_dsp1.html#autotoc_md-throughput-is-per-byte',1,'']]],
  ['is_20present_20but_20cannot_20be_20switched_20on_182',['🟡 The multitap (5-player) path is present but cannot be switched on',['../KNOWN_LIMITATIONS.html#autotoc_md-the-multitap-5-player-path-is-present-but-cannot-be-switched-on',1,'']]],
  ['is_20preserved_20through_20qbe_20since_20chantier_20a2_202026_2005_2009_183',['🟢 &lt;span class=&quot;tt&quot;&gt;volatile&lt;/span&gt; is preserved through QBE (since chantier A2, 2026-05-09)',['../KNOWN_LIMITATIONS.html#autotoc_md-volatile-is-preserved-through-qbe-since-chantier-a2-2026-05-09',1,'']]],
  ['is_20priority_20not_20layer_20order_184',['Depth is priority, not layer order',['../craft_backgrounds.html#depth-is-priority-not-layer-order',1,'']]],
  ['is_20read_20only_20the_20ram_20buffer_20pattern_185',['3. ROM is Read-Only (The RAM Buffer Pattern)',['../examples_games_breakout.html#autotoc_md3-rom-is-read-only-the-ram-buffer-pattern',1,'']]],
  ['is_20refused_186',['🟡 Inline assembly is refused',['../KNOWN_LIMITATIONS.html#autotoc_md-inline-assembly-is-refused',1,'']]],
  ['is_20reserved_20for_20oam_20dma_187',['🔴 Channel 7 is reserved for OAM DMA',['../tutorial_hdma.html#autotoc_md-channel-7-is-reserved-for-oam-dma',1,'']]],
  ['is_20sa_201_188',['What Is SA-1?',['../tutorial_sa1.html#what-is-sa-1',1,'']]],
  ['is_20size_201_20pixels_189',['🟡 Mosaic block size is &quot;size + 1&quot; pixels',['../tutorial_mosaic.html#autotoc_md-mosaic-block-size-is-size--1-pixels',1,'']]],
  ['is_20still_20for_190',['What Mesen2 is still for',['../tutorial_debugging.html#what-mesen2-is-still-for',1,'']]],
  ['is_20sub_20screen_20only_20trap_191',['🔴 The &quot;BG2 is sub-screen-only&quot; trap',['../tutorial_colormath.html#autotoc_md-the-bg2-is-sub-screen-only-trap',1,'']]],
  ['is_20superfx_192',['What Is SuperFX?',['../tutorial_superfx.html#what-is-superfx',1,'']]],
  ['is_20the_20atom_20the_20metatile_20is_20the_20word_193',['The tile is the atom; the metatile is the word',['../craft_tiles_to_levels.html#the-tile-is-the-atom-the-metatile-is-the-word',1,'']]],
  ['is_20the_20color_194',['direct_color — the pixel byte IS the color',['../examples_color_direct_color.html',1,'examples_color']]],
  ['is_20the_20gate_20to_20colour_20math_195',['🟠 &lt;span class=&quot;tt&quot;&gt;windowEnable(window, WINDOW_MATH)&lt;/span&gt; is the gate to colour math',['../tutorial_window.html#autotoc_md-windowenablewindow-window_math-is-the-gate-to-colour-math',1,'']]],
  ['is_20the_20same_196',['What is the same',['../migrating_pvsneslib.html#what-is-the-same',1,'']]],
  ['is_20the_20text_197',['Which colour is the text?',['../tutorial_text.html#which-colour-is-the-text',1,'']]],
  ['is_20the_20tilemap_20centre_20not_20the_20screen_20centre_198',['🟡 Centre default is the tilemap centre, not the screen centre',['../tutorial_mode7.html#autotoc_md-centre-default-is-the-tilemap-centre-not-the-screen-centre',1,'']]],
  ['is_20the_20way_20above_20it_199',['🟡 Plain C RAM lives below $2000; &lt;span class=&quot;tt&quot;&gt;FAR&lt;/span&gt; is the way above it',['../KNOWN_LIMITATIONS.html#autotoc_md-plain-c-ram-lives-below-2000-far-is-the-way-above-it',1,'']]],
  ['is_20the_20word_200',['The tile is the atom; the metatile is the word',['../craft_tiles_to_levels.html#the-tile-is-the-atom-the-metatile-is-the-word',1,'']]],
  ['is_20vs_20where_20it_20collides_201',['Where the sprite is vs where it collides',['../tutorial_collision.html#where-the-sprite-is-vs-where-it-collides',1,'']]],
  ['is_20your_20scroll_20values_202',['The camera &lt;em&gt;is&lt;/em&gt; your scroll values',['../craft_camera.html#the-camera-is-your-scroll-values',1,'']]],
  ['is_20yours_203',['The &lt;span class=&quot;tt&quot;&gt;Panel&lt;/span&gt; struct — the tilemap is yours',['../tutorial_panel.html#the-panel-struct--the-tilemap-is-yours',1,'']]],
  ['is_5fmap32x32_204',['is_map32x32',['../maps_2dynamic__map_2main_8c.html#aee4468215190b975dc2661b09e698851',1,'main.c']]],
  ['isinvblank_205',['isInVBlank',['../console_8h.html#a1bb80e4838ae89136bf886d0bc9ddfc2',1,'console.h']]],
  ['isn_20t_20enough_3a_20h_20timer_20irq_20streaming_206',['When HDMA isn&apos;t enough: H-timer IRQ streaming',['../tutorial_hdma.html#when-hdma-isnt-enough-h-timer-irq-streaming',1,'']]],
  ['ispal_207',['isPAL',['../console_8h.html#a3b56ab7f353055ded8e2960b94d6ba57',1,'console.h']]],
  ['issues_208',['Issues',['../troubleshooting.html#build-issues',1,'Build Issues'],['../examples_audio_snesmod_music.html#common-issues',1,'Common Issues'],['../contributing.html#good-first-issues',1,'Good First Issues'],['../troubleshooting.html#graphics-issues',1,'Graphics Issues'],['../troubleshooting.html#memory-issues',1,'Memory Issues']]],
  ['issues_20black_20screen_20crash_209',['Runtime Issues (Black Screen / Crash)',['../troubleshooting.html#runtime-issues-black-screen--crash',1,'']]],
  ['it_210',['it',['../tutorial_sram.html#autotoc_md-endianness--but-you-dont-have-to-think-about-it',1,'🟠 Endianness — but you don&apos;t have to think about it'],['../tutorial_dsp1.html#autotoc_md-a-raster-stream-cannot-be-resynced--let-the-lib-close-it',1,'🟡 A Raster stream cannot be &quot;resynced&quot; — let the lib close it'],['../KNOWN_LIMITATIONS.html#autotoc_md-plain-c-ram-lives-below-2000-far-is-the-way-above-it',1,'🟡 Plain C RAM lives below $2000; &lt;span class=&quot;tt&quot;&gt;FAR&lt;/span&gt; is the way above it'],['../examples_audio_speech_synth.html#debug-tooling-that-cracked-it',1,'Debug tooling that cracked it'],['../craft_tiles_to_levels.html#designing-the-level-not-just-building-it',1,'Designing the level, not just building it'],['../craft_camera.html#dont-glue-the-camera-to-the-player--deadzone-it',1,'Don&apos;t glue the camera to the player — deadzone it'],['../tools_smconv.html#how-you-actually-use-it',1,'How you actually use it'],['../tools_tmx2snes.html#how-you-actually-use-it-1',1,'How you actually use it'],['../tools_wav2brr.html#how-you-actually-use-it-2',1,'How you actually use it'],['../craft_tiles_to_levels.html#the-level-is-bigger-than-vram--so-stream-it',1,'The level is bigger than VRAM — so stream it'],['../migrating_pvsneslib.html#trap-5-const-data-is-far-and-casting-const-away-breaks-it',1,'Trap 5: const data is far, and casting &lt;span class=&quot;tt&quot;&gt;const&lt;/span&gt; away breaks it']]],
  ['it_20—_20fixed_202026_2009_2019_211',['🟢 A callback that peeked at another object became a copy of it — fixed 2026-09-19',['../tutorial_object.html#autotoc_md-a-callback-that-peeked-at-another-object-became-a-copy-of-it--fixed-2026-09-19',1,'']]],
  ['it_20all_20together_212',['Stage 5 — &quot;Can I hold it all together?&quot;',['../learning_path.html#stage-5--can-i-hold-it-all-together',1,'']]],
  ['it_20at_20the_20right_20moment_213',['Write it at the right moment',['../craft_camera.html#write-it-at-the-right-moment',1,'']]],
  ['it_20breaks_214',['it breaks',['../examples_backgrounds_mode2.html#what-to-observe--if-it-breaks',1,'What to observe / if it breaks'],['../examples_basics_game_skeleton.html#what-to-observe--if-it-breaks-1',1,'What to observe / if it breaks'],['../examples_basics_panel_hud.html#what-to-observe--if-it-breaks-2',1,'What to observe / if it breaks'],['../examples_color_palette_cycle.html#what-to-observe--if-it-breaks-3',1,'What to observe / if it breaks'],['../examples_color_shadow_tint.html#what-to-observe--if-it-breaks-4',1,'What to observe / if it breaks'],['../examples_sprites_sprite_swarm.html#what-to-observe--if-it-breaks-5',1,'What to observe / if it breaks']]],
  ['it_20collides_215',['Where the sprite is vs where it collides',['../tutorial_collision.html#where-the-sprite-is-vs-where-it-collides',1,'']]],
  ['it_20costs_216',['What it costs',['../tutorial_far_ram.html#what-it-costs',1,'']]],
  ['it_20feel_20good_217',['Stage 4 — &quot;Can I make it feel good?&quot;',['../learning_path.html#stage-4--can-i-make-it-feel-good',1,'']]],
  ['it_20fits_218',['it fits',['../tools_aseprite2snes.html#where-it-fits',1,'Where it fits'],['../tools_font2snes.html#where-it-fits-1',1,'Where it fits'],['../tools_img2snes.html#where-it-fits-2',1,'Where it fits']]],
  ['it_20in_20practice_219',['it in practice',['../tools_gfx4snes.html#see-it-in-practice',1,'See it in practice'],['../tools_palplan.html#see-it-in-practice-1',1,'See it in practice'],['../tools_smconv.html#see-it-in-practice-2',1,'See it in practice'],['../tools_tmx2snes.html#see-it-in-practice-3',1,'See it in practice'],['../tools_wav2brr.html#see-it-in-practice-4',1,'See it in practice']]],
  ['it_20is_20not_220',['What the object engine is, and what it is not',['../tutorial_object.html#what-the-object-engine-is-and-what-it-is-not',1,'']]],
  ['it_20matters_20for_20your_20game_221',['it matters for your game',['../examples_backgrounds_mode2.html#why-it-matters-for-your-game',1,'Why it matters for your game'],['../examples_basics_game_skeleton.html#why-it-matters-for-your-game-1',1,'Why it matters for your game'],['../examples_basics_panel_hud.html#why-it-matters-for-your-game-2',1,'Why it matters for your game'],['../examples_color_palette_cycle.html#why-it-matters-for-your-game-3',1,'Why it matters for your game'],['../examples_color_shadow_tint.html#why-it-matters-for-your-game-4',1,'Why it matters for your game'],['../examples_sprites_sprite_swarm.html#why-it-matters-for-your-game-5',1,'Why it matters for your game']]],
  ['it_20replaces_222',['gameLoopRun — the boilerplate it replaces',['../tutorial_framework.html#gamelooprun--the-boilerplate-it-replaces',1,'']]],
  ['it_20still_20looks_20wrong_223',['Step 6 — when it still looks wrong',['../migrating_pvsneslib.html#step-6--when-it-still-looks-wrong',1,'']]],
  ['it_20when_20not_20to_224',['When to use it, when not to',['../tutorial_far_ram.html#when-to-use-it-when-not-to',1,'']]],
  ['it_20works_225',['It Works',['../tutorial_animation.html#how-it-works',1,'How It Works'],['../examples_backgrounds_mode1_bg3_priority.html#how-it-works-1',1,'How It Works'],['../examples_backgrounds_mode1_lz77.html#how-it-works-2',1,'How It Works'],['../examples_games_mapandobjects.html#how-it-works-3',1,'How It Works'],['../examples_hdma_gradient_colors.html#how-it-works-4',1,'How It Works'],['../examples_input_mouse.html#how-it-works-5',1,'How It Works'],['../examples_maps_dynamic_map.html#how-it-works-6',1,'How It Works'],['../examples_maps_slope_collision.html#how-it-works-7',1,'How It Works'],['../examples_memory_hirom_demo.html#how-it-works-8',1,'How It Works'],['../examples_memory_save_game.html#how-it-works-9',1,'How It Works'],['../examples_mode7_perspective.html#how-it-works-11',1,'How It Works'],['../examples_mode7_rotate_scale.html#how-it-works-12',1,'How It Works'],['../examples_scrolling_mixed_scroll.html#how-it-works-13',1,'How It Works'],['../examples_scrolling_parallax_scroll.html#how-it-works-14',1,'How It Works'],['../examples_sprites_animated_sprite.html#how-it-works-15',1,'How It Works'],['../examples_sprites_dynamic_sprite.html#how-it-works-16',1,'How It Works'],['../examples_sprites_metasprite.html#how-it-works-17',1,'How It Works'],['../examples_sprites_simple_sprite.html#how-it-works-18',1,'How It Works'],['../examples_sprites_sprite_sizes.html#how-it-works-19',1,'How It Works'],['../examples_transitions_mosaic.html#how-it-works-20',1,'How It Works'],['../examples_windows_transparent_window.html#how-it-works-21',1,'How It Works'],['../examples_windows_window.html#how-it-works-22',1,'How It Works']]],
  ['it_20works_226',['How it works',['../examples_mode7_dsp1_ground.html#how-it-works-10',1,'']]],
  ['it_20yourself_20with_20setbrightness_200_227',['🔴 &lt;span class=&quot;tt&quot;&gt;panelFlush&lt;/span&gt; uploads under forced blank — do not do it yourself with &lt;span class=&quot;tt&quot;&gt;setBrightness(0)&lt;/span&gt;',['../tutorial_panel.html#autotoc_md-panelflush-uploads-under-forced-blank--do-not-do-it-yourself-with-setbrightness0',1,'']]],
  ['itable_228',['itable',['../hdma_2hdma__indirect__gradient_2main_8c.html#a0f089355db851d283a48715859fcb354',1,'main.c']]],
  ['itself_229',['Recipe 7 — the ROM tells you itself',['../tutorial_debugging.html#recipe-7--the-rom-tells-you-itself',1,'']]]
];
