var searchData=
[
  ['name_20base_0',['Name Base',['../examples_sprites_simple_sprite.html#name-base',1,'']]],
  ['name_5fbase_20argument_20is_20a_20page_20number_20not_20a_20vram_20address_1',['The &lt;span class=&quot;tt&quot;&gt;name_base&lt;/span&gt; argument is a page number, not a VRAM address',['../tutorial_sprites.html#the-name_base-argument-is-a-page-number-not-a-vram-address',1,'']]],
  ['naming_20conventions_2',['Naming Conventions',['../code_style.html#naming-conventions',1,'']]],
  ['natively_20resolved_20by_20the_20luna_20migration_3',['🟢 SuperFX / SA-1 chips: covered natively (resolved by the luna migration)',['../KNOWN_LIMITATIONS.html#autotoc_md-superfx--sa-1-chips-covered-natively-resolved-by-the-luna-migration',1,'']]],
  ['navigation_4',['Menu Navigation',['../tutorial_input.html#menu-navigation',1,'']]],
  ['nbands_5',['NBANDS',['../hdma_2hdma__indirect__gradient_2main_8c.html#a46ee023ac3f5d103e533843238d2e52a',1,'main.c']]],
  ['nbirds_6',['NBIRDS',['../chips_2sa1__starfield_2main_8c.html#ae33cce9568cb8d271c2d716d88786445',1,'NBIRDS:&#160;main.c'],['../sprites_2sprite__swarm_2main_8c.html#ae33cce9568cb8d271c2d716d88786445',1,'NBIRDS:&#160;main.c']]],
  ['nbobjects_7',['nbobjects',['../goomba_8c.html#a1f11a4fc65e8bd72a9ba9c513f6a24a9',1,'nbobjects:&#160;main.c'],['../koopatroopa_8c.html#a1f11a4fc65e8bd72a9ba9c513f6a24a9',1,'nbobjects:&#160;main.c'],['../games_2mapandobjects_2main_8c.html#a1f11a4fc65e8bd72a9ba9c513f6a24a9',1,'nbobjects:&#160;main.c'],['../games_2mapandobjects_2mario_8c.html#a1f11a4fc65e8bd72a9ba9c513f6a24a9',1,'nbobjects:&#160;main.c']]],
  ['ndash_20advanced_20topics_8',['Level 4 &amp;ndash; Advanced Topics',['../examples.html#level-4----advanced-topics',1,'']]],
  ['ndash_20first_20steps_9',['Level 1 &amp;ndash; First Steps',['../examples.html#level-1----first-steps',1,'']]],
  ['ndash_20graphics_20fundamentals_10',['Level 2 &amp;ndash; Graphics Fundamentals',['../examples.html#level-2----graphics-fundamentals',1,'']]],
  ['ndash_20hardware_20horizontal_20mirror_11',['OBJ_FLIPX &amp;ndash; Hardware Horizontal Mirror',['../examples_sprites_animated_sprite.html#obj_flipx----hardware-horizontal-mirror',1,'']]],
  ['ndash_20maps_20and_20complete_20projects_12',['Level 5 &amp;ndash; Maps and Complete Projects',['../examples.html#level-5----maps-and-complete-projects',1,'']]],
  ['ndash_20scrolling_20and_20effects_13',['Level 3 &amp;ndash; Scrolling and Effects',['../examples.html#level-3----scrolling-and-effects',1,'']]],
  ['ndash_20write_20twice_20register_14',['BG1HOFS ($210D) &amp;ndash; Write-Twice Register',['../examples_scrolling_parallax_scroll.html#bg1hofs-210d----write-twice-register',1,'']]],
  ['need_15',['Which API do I need?',['../getting_started.html#which-api-do-i-need',1,'']]],
  ['need_20more_20than_20layers_20can_20give_16',['When you need more than layers can give',['../craft_backgrounds.html#when-you-need-more-than-layers-can-give',1,'']]],
  ['needed_20by_20low_20level_20emulators_17',['🟡 Firmware needed by low-level emulators',['../tutorial_dsp1.html#autotoc_md-firmware-needed-by-low-level-emulators',1,'']]],
  ['needs_20dmacopyvrammode7_20not_20dmacopyvram_18',['🟡 Mode 7 needs &lt;span class=&quot;tt&quot;&gt;dmaCopyVramMode7&lt;/span&gt;, not &lt;span class=&quot;tt&quot;&gt;dmaCopyVram&lt;/span&gt;',['../tutorial_dma.html#autotoc_md-mode-7-needs-dmacopyvrammode7-not-dmacopyvram',1,'']]],
  ['never_20outputs_20scanline_200_20hidden_20by_20the_20lib_19',['🟢 Vertical scroll is off by one: the PPU never outputs scanline 0 (hidden by the lib)',['../KNOWN_LIMITATIONS.html#autotoc_md-vertical-scroll-is-off-by-one-the-ppu-never-outputs-scanline-0-hidden-by-the-lib',1,'']]],
  ['new_20entries_20',['Where to add new entries',['../KNOWN_LIMITATIONS.html#where-to-add-new-entries',1,'']]],
  ['new_5flevel_21',['new_level',['../games_2breakout_2main_8c.html#a0eb77c68ccd57e38a2365d1e3290c521',1,'main.c']]],
  ['next_22',['Next',['../getting_started.html#whats-next',1,'What&apos;s Next?'],['../examples_audio_snesmod_music.html#whats-next-1',1,'What&apos;s Next?'],['../examples_audio_snesmod_sfx.html#whats-next-2',1,'What&apos;s Next?'],['../examples_backgrounds_mode1.html#whats-next-3',1,'What&apos;s Next?'],['../examples_basics_collision_demo.html#whats-next-4',1,'What&apos;s Next?'],['../examples_color_transparency.html#whats-next-5',1,'What&apos;s Next?'],['../examples_input_two_players.html#whats-next-6',1,'What&apos;s Next?'],['../examples_transitions_fading.html#whats-next-7',1,'What&apos;s Next?']]],
  ['next_23',['next',['../structt__objs.html#afa684c5b49902511d45a104b147552c8',1,'t_objs']]],
  ['next_20rung_24',['Next rung',['../examples_text_print_string.html#next-rung',1,'']]],
  ['next_20steps_25',['Next Steps',['../tutorial_animation.html#next-steps',1,'Next Steps'],['../tutorial_audio.html#next-steps-1',1,'Next Steps'],['../tutorial_collision.html#next-steps-2',1,'Next Steps'],['../tutorial_game_states.html#next-steps-3',1,'Next Steps'],['../tutorial_graphics.html#next-steps-4',1,'Next Steps'],['../tutorial_input.html#next-steps-5',1,'Next Steps'],['../tutorial_scrolling.html#next-steps-6',1,'Next Steps'],['../tutorial_sprites.html#next-steps-7',1,'Next Steps']]],
  ['next_5fbox_5fcol_26',['NEXT_BOX_COL',['../render_8c.html#a6cb9fb4cb945dc633b05ab2e51d19f2e',1,'render.c']]],
  ['next_5fbox_5frow_27',['NEXT_BOX_ROW',['../render_8c.html#a7c92b0bbf13cad4d4606b341db08293a',1,'render.c']]],
  ['next_5ftype_28',['next_type',['../games_2tetris_2main_8c.html#ab8d32ebe6b1edb3e0429f2e4ceb04080',1,'main.c']]],
  ['nid_29',['nID',['../structt__objs.html#a6e28be5a50edb4be319d6a65e73b82ff',1,'t_objs']]],
  ['nmi_30',['🟡 WRAM data port &lt;span class=&quot;tt&quot;&gt;$2180&lt;/span&gt;–&lt;span class=&quot;tt&quot;&gt;$2183&lt;/span&gt; is NOT safe in NMI',['../tutorial_dma.html#autotoc_md-wram-data-port-21802183-is-not-safe-in-nmi',1,'']]],
  ['nmi_20callback_20safe_31',['🟡 Not NMI-callback-safe',['../tutorial_dsp1.html#autotoc_md-not-nmi-callback-safe',1,'']]],
  ['nmi_20caught_20at_20build_20time_32',['🟢 WRAM data port &lt;span class=&quot;tt&quot;&gt;$2180–$2183&lt;/span&gt; race in NMI (caught at build time)',['../KNOWN_LIMITATIONS.html#autotoc_md-wram-data-port-21802183-race-in-nmi-caught-at-build-time',1,'']]],
  ['nmi_20handler_33',['🟡 HDMA fires before the user callback in the NMI handler',['../tutorial_hdma.html#autotoc_md-hdma-fires-before-the-user-callback-in-the-nmi-handler',1,'']]],
  ['nmi_20status_34',['$4210 - RDNMI (NMI Status)',['../registers.html#autotoc_md4210---rdnmi-nmi-status',1,'']]],
  ['nmiclear_35',['nmiClear',['../interrupt_8h.html#a4a0a4690d2c70b58584eed95377325a1',1,'interrupt.h']]],
  ['nmiset_36',['nmiSet',['../interrupt_8h.html#a54a7e26f751984f6f3241ed2d2c5eda7',1,'interrupt.h']]],
  ['nmiset_20callbacks_37',['🟡 &lt;span class=&quot;tt&quot;&gt;fixMul()&lt;/span&gt; / &lt;span class=&quot;tt&quot;&gt;fixLerp()&lt;/span&gt; are not safe inside nmiSet() callbacks',['../KNOWN_LIMITATIONS.html#autotoc_md-fixmul--fixlerp-are-not-safe-inside-nmiset-callbacks',1,'']]],
  ['nmisetbank_38',['nmiSetBank',['../interrupt_8h.html#af408cb8d09dc9ab56ae7245c18792c2d',1,'interrupt.h']]],
  ['nmitimen_20interrupt_20enable_39',['$4200 - NMITIMEN (Interrupt Enable)',['../registers.html#autotoc_md4200---nmitimen-interrupt-enable',1,'']]],
  ['nmitimen_5fjoy_5fenable_40',['NMITIMEN_JOY_ENABLE',['../group__reg__const.html#ga25c5bb53354cc1a7d89d1174d15a313a',1,'registers.h']]],
  ['nmitimen_5fnmi_5fenable_41',['NMITIMEN_NMI_ENABLE',['../group__reg__const.html#gacb255c4531e73fb75513edadfc0d62fb',1,'registers.h']]],
  ['no_20audio_20output_42',['No audio output',['../examples_audio_snesmod_music.html#no-audio-output',1,'']]],
  ['no_20external_20assets_43',['3. Embedded font (no external assets)',['../examples_memory_hirom_demo.html#autotoc_md3-embedded-font-no-external-assets',1,'']]],
  ['no_20printf_44',['1. There Is No printf',['../examples_fundamentals_text_glyphs.html#autotoc_md1-there-is-no-printf',1,'']]],
  ['no_20rule_20to_20make_20target_20common_20mk_45',['&quot;OPENSNES not defined&quot; or &quot;No rule to make target &apos;common.mk&apos;&quot;',['../troubleshooting.html#opensnes-not-defined-or-no-rule-to-make-target-commonmk',1,'']]],
  ['no_20snesmod_46',['The raw APU path (no snesmod)',['../tutorial_audio.html#the-raw-apu-path-no-snesmod',1,'']]],
  ['no_20special_20timing_47',['🟠 SRAM access requires no special timing',['../tutorial_sram.html#autotoc_md-sram-access-requires-no-special-timing',1,'']]],
  ['no_20stx_20l_20—_20save_20x_20through_20a_48',['No &lt;span class=&quot;tt&quot;&gt;stx.l&lt;/span&gt; — Save X Through A',['../tutorial_sa1.html#no-stxl--save-x-through-a',1,'']]],
  ['noise_20frequencies_49',['Noise Frequencies',['../snes_sound_guide.html#noise-frequencies',1,'']]],
  ['non_20rectangular_20shapes_20with_20hdma_50',['Making Non-Rectangular Shapes with HDMA',['../examples_windows_window.html#making-non-rectangular-shapes-with-hdma',1,'']]],
  ['non_20repeat_20on_20wh0_20wh1_20—_20pick_20by_20data_20shape_20not_20by_20register_51',['🟡 Repeat vs non-repeat on &lt;span class=&quot;tt&quot;&gt;WH0&lt;/span&gt;/&lt;span class=&quot;tt&quot;&gt;WH1&lt;/span&gt; — pick by data shape, not by register',['../tutorial_window.html#autotoc_md-repeat-vs-non-repeat-on-wh0wh1--pick-by-data-shape-not-by-register',1,'']]],
  ['non_20repeat_20vs_20repeat_20mode_52',['Non-Repeat vs Repeat Mode',['../examples_hdma_gradient_colors.html#non-repeat-vs-repeat-mode',1,'']]],
  ['nop_20after_20every_20branch_20delay_20slot_53',['1. NOP After Every Branch (Delay Slot)',['../tutorial_superfx.html#autotoc_md1-nop-after-every-branch-delay-slot',1,'']]],
  ['nop_20padding_20before_20stop_54',['2. NOP Padding Before STOP',['../tutorial_superfx.html#autotoc_md2-nop-padding-before-stop',1,'']]],
  ['not_55',['🟠 &lt;span class=&quot;tt&quot;&gt;mapVblank()&lt;/span&gt; belongs in VBlank, &lt;span class=&quot;tt&quot;&gt;mapUpdate()&lt;/span&gt; does not',['../tutorial_map.html#autotoc_md-mapvblank-belongs-in-vblank-mapupdate-does-not',1,'']]],
  ['not_200_56',['🟡 Sprite palettes start at CGRAM offset 128, not 0',['../KNOWN_LIMITATIONS.html#autotoc_md-sprite-palettes-start-at-cgram-offset-128-not-0',1,'']]],
  ['not_20a_20blur_57',['Not a Blur',['../examples_transitions_mosaic.html#not-a-blur',1,'']]],
  ['not_20a_20layer_58',['🟡 Out-of-bounds with &lt;span class=&quot;tt&quot;&gt;MODE7_TRANSPARENT&lt;/span&gt; shows the backdrop, not a layer',['../tutorial_mode7.html#autotoc_md-out-of-bounds-with-mode7_transparent-shows-the-backdrop-not-a-layer',1,'']]],
  ['not_20a_20vram_20address_59',['The &lt;span class=&quot;tt&quot;&gt;name_base&lt;/span&gt; argument is a page number, not a VRAM address',['../tutorial_sprites.html#the-name_base-argument-is-a-page-number-not-a-vram-address',1,'']]],
  ['not_20a_20write_20protect_60',['🟡 &lt;span class=&quot;tt&quot;&gt;sramClear&lt;/span&gt; is a memset, not a write-protect',['../tutorial_sram.html#autotoc_md-sramclear-is-a-memset-not-a-write-protect',1,'']]],
  ['not_20affect_20obj_20sprites_61',['🟠 Mosaic does not affect OBJ (sprites)',['../tutorial_mosaic.html#autotoc_md-mosaic-does-not-affect-obj-sprites',1,'']]],
  ['not_20assumed_62',['not assumed',['../examples_hdma_hdma_indirect_gradient.html#fidelity-to-the-original-measured-not-assumed',1,'Fidelity to the original (measured, not assumed)'],['../examples_hdma_hdma_wave_table.html#fidelity-to-the-original-measured-not-assumed-1',1,'Fidelity to the original (measured, not assumed)']]],
  ['not_20built_63',['Build fails with &quot;Library not built&quot;',['../getting_started.html#build-fails-with-library-not-built',1,'']]],
  ['not_20by_20register_64',['🟡 Repeat vs non-repeat on &lt;span class=&quot;tt&quot;&gt;WH0&lt;/span&gt;/&lt;span class=&quot;tt&quot;&gt;WH1&lt;/span&gt; — pick by data shape, not by register',['../tutorial_window.html#autotoc_md-repeat-vs-non-repeat-on-wh0wh1--pick-by-data-shape-not-by-register',1,'']]],
  ['not_20defined_20or_20no_20rule_20to_20make_20target_20common_20mk_65',['&quot;OPENSNES not defined&quot; or &quot;No rule to make target &apos;common.mk&apos;&quot;',['../troubleshooting.html#opensnes-not-defined-or-no-rule-to-make-target-commonmk',1,'']]],
  ['not_20dmacopyvram_66',['🟡 Mode 7 needs &lt;span class=&quot;tt&quot;&gt;dmaCopyVramMode7&lt;/span&gt;, not &lt;span class=&quot;tt&quot;&gt;dmaCopyVram&lt;/span&gt;',['../tutorial_dma.html#autotoc_md-mode-7-needs-dmacopyvrammode7-not-dmacopyvram',1,'']]],
  ['not_20do_20it_20yourself_20with_20setbrightness_200_67',['🔴 &lt;span class=&quot;tt&quot;&gt;panelFlush&lt;/span&gt; uploads under forced blank — do not do it yourself with &lt;span class=&quot;tt&quot;&gt;setBrightness(0)&lt;/span&gt;',['../tutorial_panel.html#autotoc_md-panelflush-uploads-under-forced-blank--do-not-do-it-yourself-with-setbrightness0',1,'']]],
  ['not_20for_20bg_20masking_68',['Window for Color Math (Not for BG Masking)',['../examples_windows_transparent_window.html#window-for-color-math-not-for-bg-masking',1,'']]],
  ['not_20found_69',['not found',['../troubleshooting.html#clang-command-not-found-or-cc-command-not-found',1,'&quot;clang: command not found&quot; or &quot;cc: command not found&quot;'],['../troubleshooting.html#wla-65816-command-not-found',1,'&quot;wla-65816: command not found&quot;'],['../troubleshooting.html#empty-compiler-directories-or-cc65816-not-found',1,'Empty &lt;span class=&quot;tt&quot;&gt;compiler/&lt;/span&gt; directories or &quot;cc65816 not found&quot;']]],
  ['not_20found_20or_20cc_3a_20command_20not_20found_70',['&quot;clang: command not found&quot; or &quot;cc: command not found&quot;',['../troubleshooting.html#clang-command-not-found-or-cc-command-not-found',1,'']]],
  ['not_20found_20or_20empty_20compiler_20folder_71',['&quot;fatal: repository not found&quot; or empty compiler folder',['../getting_started.html#fatal-repository-not-found-or-empty-compiler-folder',1,'']]],
  ['not_20found_3a_20make_72',['&quot;command not found: make&quot;',['../getting_started.html#command-not-found-make',1,'']]],
  ['not_20just_20building_20it_73',['Designing the level, not just building it',['../craft_tiles_to_levels.html#designing-the-level-not-just-building-it',1,'']]],
  ['not_20just_20pixels_74',['A tile carries meaning, not just pixels',['../craft_tiles_to_levels.html#a-tile-carries-meaning-not-just-pixels',1,'']]],
  ['not_20layer_20order_75',['Depth is priority, not layer order',['../craft_backgrounds.html#depth-is-priority-not-layer-order',1,'']]],
  ['not_20nmi_20callback_20safe_76',['🟡 Not NMI-callback-safe',['../tutorial_dsp1.html#autotoc_md-not-nmi-callback-safe',1,'']]],
  ['not_20palette_20edits_77',['Hit flash — color math, not palette edits',['../craft_game_feel.html#hit-flash--color-math-not-palette-edits',1,'']]],
  ['not_20playing_78',['Audio not playing',['../troubleshooting.html#audio-not-playing',1,'']]],
  ['not_20propagate_20the_20high_20half_20through_20the_20call_79',['🟡 C function returning &lt;span class=&quot;tt&quot;&gt;long&lt;/span&gt; does not propagate the high half through the call',['../KNOWN_LIMITATIONS.html#autotoc_md-c-function-returning-long-does-not-propagate-the-high-half-through-the-call',1,'']]],
  ['not_20reset_20by_20consoleinit_80',['🟡 Mosaic state is not reset by &lt;span class=&quot;tt&quot;&gt;consoleInit&lt;/span&gt;',['../tutorial_mosaic.html#autotoc_md-mosaic-state-is-not-reset-by-consoleinit',1,'']]],
  ['not_20safe_20in_20nmi_81',['🟡 WRAM data port &lt;span class=&quot;tt&quot;&gt;$2180&lt;/span&gt;–&lt;span class=&quot;tt&quot;&gt;$2183&lt;/span&gt; is NOT safe in NMI',['../tutorial_dma.html#autotoc_md-wram-data-port-21802183-is-not-safe-in-nmi',1,'']]],
  ['not_20safe_20inside_20nmiset_20callbacks_82',['🟡 &lt;span class=&quot;tt&quot;&gt;fixMul()&lt;/span&gt; / &lt;span class=&quot;tt&quot;&gt;fixLerp()&lt;/span&gt; are not safe inside nmiSet() callbacks',['../KNOWN_LIMITATIONS.html#autotoc_md-fixmul--fixlerp-are-not-safe-inside-nmiset-callbacks',1,'']]],
  ['not_20sprites_83',['4. Bricks Are Not Sprites',['../examples_games_breakout.html#autotoc_md4-bricks-are-not-sprites',1,'']]],
  ['not_20the_20screen_20centre_84',['🟡 Centre default is the tilemap centre, not the screen centre',['../tutorial_mode7.html#autotoc_md-centre-default-is-the-tilemap-centre-not-the-screen-centre',1,'']]],
  ['not_20tilemaps_85',['Why Compress Tiles but Not Tilemaps?',['../examples_backgrounds_mode1_lz77.html#why-compress-tiles-but-not-tilemaps',1,'']]],
  ['not_20to_86',['When to use it, when not to',['../tutorial_far_ram.html#when-to-use-it-when-not-to',1,'']]],
  ['not_20working_87',['Controller input not working',['../troubleshooting.html#controller-input-not-working',1,'']]],
  ['notes_88',['Notes',['../examples_audio_snesmod_music.html#technical-notes',1,'Technical Notes'],['../examples_backgrounds_mode1.html#technical-notes-1',1,'Technical Notes'],['../examples_input_two_players.html#technical-notes-2',1,'Technical Notes'],['../examples_transitions_fading.html#technical-notes-3',1,'Technical Notes']]],
  ['notes_20luna_20v1_209_200_89',['Validation notes (luna v1.9.0)',['../examples_backgrounds_mode5_hires.html#validation-notes-luna-v190',1,'']]],
  ['nothing_90',['When something silently does nothing',['../api_index.html#when-something-silently-does-nothing',1,'']]],
  ['npc_91',['Npc',['../structNpc.html',1,'']]],
  ['npc_5fpal_92',['npc_pal',['../games_2rpg_2main_8c.html#a2a3683e0c24cf6a0d11b6ab83ca5d930',1,'main.c']]],
  ['npcs_93',['npcs',['../games_2rpg_2main_8c.html#aef67a614243f6a40b8e9d467b6383c3c',1,'main.c']]],
  ['nudge_20the_20scroll_94',['Screen shake — nudge the scroll',['../craft_game_feel.html#screen-shake--nudge-the-scroll',1,'']]],
  ['null_95',['NULL',['../group__macros.html#ga070d2ce7b6bb7e5c05602aa8c308d0c4',1,'types.h']]],
  ['num_5feffects_96',['NUM_EFFECTS',['../audio_2snesmod__sfx_2main_8c.html#adae8021d63052c74619497c15c70595e',1,'main.c']]],
  ['num_5fenemies_97',['NUM_ENEMIES',['../basics_2collision__demo_2main_8c.html#a7bdeb427cc72fabd831b0ab942f0b9a0',1,'main.c']]],
  ['num_5fpiece_5ftypes_98',['NUM_PIECE_TYPES',['../piece_8h.html#a91553c0e2fac0272cc71951d9787bf7e',1,'piece.h']]],
  ['num_5frotations_99',['NUM_ROTATIONS',['../piece_8h.html#ad166377d181c8c40cdb6363f644de7ec',1,'piece.h']]],
  ['number_20not_20a_20vram_20address_100',['The &lt;span class=&quot;tt&quot;&gt;name_base&lt;/span&gt; argument is a page number, not a VRAM address',['../tutorial_sprites.html#the-name_base-argument-is-a-page-number-not-a-vram-address',1,'']]],
  ['numbering_101',['VRAM Tile Numbering',['../tutorial_animation.html#vram-tile-numbering',1,'']]],
  ['numbers_102',['Numbers',['../examples_basics_random.html',1,'Random Numbers'],['../examples_sprites_metasprite.html#vram-tile-layout-and-oam-tile-numbers',1,'VRAM Tile Layout and OAM Tile Numbers']]]
];
