var searchData=
[
  ['h_0',['Headers (.h)',['../code_style.html#autotoc_md481',1,'']]],
  ['h_20b_20source_20address_1',['$43x2-$43x4 - A1TxL/H/B (Source Address)',['../registers.html#autotoc_md704',1,'']]],
  ['h_20oam_20address_2',['$2102-$2103 - OAMADDL/H (OAM Address)',['../registers.html#autotoc_md666',1,'']]],
  ['h_20timer_20irq_20streaming_3',['When HDMA isn&apos;t enough: H-timer IRQ streaming',['../tutorial_hdma.html#autotoc_md220',1,'']]],
  ['h_20transfer_20size_4',['$43x5-$43x6 - DASxL/H (Transfer Size)',['../registers.html#autotoc_md705',1,'']]],
  ['h_20vram_20address_5',['$2116-$2117 - VMADDL/H (VRAM Address)',['../registers.html#autotoc_md677',1,'']]],
  ['h_20vram_20data_20write_6',['$2118-$2119 - VMDATAL/H (VRAM Data Write)',['../registers.html#autotoc_md678',1,'']]],
  ['half_20mode_20and_20saturation_20interact_7',['🟠 Half-mode and saturation interact',['../tutorial_colormath.html#autotoc_md143',1,'']]],
  ['handler_8',['🟡 HDMA fires before the user callback in the NMI handler',['../tutorial_hdma.html#autotoc_md225',1,'']]],
  ['handling_9',['Handling',['../examples_input_mouse.html#autotoc_md1372',1,'5. Button Handling'],['../code_style.html#autotoc_md473',1,'Error Handling']]],
  ['hardcodes_20source_20bank_20—_20superfree_20spillover_20trap_10',['🔴 &lt;span class=&quot;tt&quot;&gt;dmaCopyVram&lt;/span&gt; hardcodes source bank &lt;span class=&quot;tt&quot;&gt;$00&lt;/span&gt; — SUPERFREE spillover trap',['../tutorial_dma.html#autotoc_md170',1,'']]],
  ['hardware_11',['Hardware',['../registers.html#autotoc_md693',1,'Math Hardware'],['../examples_input_mouse.html#autotoc_md1363',1,'SNES Mouse Hardware']]],
  ['hardware_12',['Recipe 4 — Sprite/OAM debugging (shadow buffer vs hardware)',['../tutorial_debugging.html#autotoc_md154',1,'']]],
  ['hardware_20horizontal_20mirror_13',['OBJ_FLIPX &amp;ndash; Hardware Horizontal Mirror',['../examples_graphics_sprites_animated_sprite.html#autotoc_md1283',1,'']]],
  ['hardware_20multiplier_20and_20divider_14',['Hardware multiplier and divider',['../tutorial_math.html#autotoc_md248',1,'']]],
  ['hardware_20multiplier_20read_20timing_15',['🟡 Hardware multiplier read timing',['../tutorial_math.html#autotoc_md261',1,'']]],
  ['hardware_20overview_16',['SNES Hardware Overview',['../hardware_overview.html',1,'index']]],
  ['hardware_20reference_17',['Hardware Reference',['../index.html#autotoc_md3',1,'']]],
  ['hardware_20register_20reference_18',['SNES Hardware Register Reference',['../registers.html',1,'index']]],
  ['hardware_20registers_19',['Hardware Registers',['../tutorial_input.html#autotoc_md239',1,'']]],
  ['hardware_20tilemaps_20',['Hardware Tilemaps',['../examples_maps.html#autotoc_md1459',1,'']]],
  ['hardware_20windows_20_242123_20_24212b_21',['Hardware Windows ($2123-$212B)',['../examples_graphics_effects.html#autotoc_md1212',1,'']]],
  ['have_20to_20think_20about_20it_22',['🟠 Endianness — but you don&apos;t have to think about it',['../tutorial_sram.html#autotoc_md365',1,'']]],
  ['have_20wrong_20values_23',['Variables have wrong values',['../troubleshooting.html#autotoc_md596',1,'']]],
  ['haven_20t_20configured_24',['🟡 Don&apos;t enable channels you haven&apos;t configured',['../tutorial_hdma.html#autotoc_md226',1,'']]],
  ['hdma_25',['HDMA',['../tutorial_window.html#autotoc_md405',1,'🟡 Boundary register sequencing during HDMA'],['../examples_graphics_backgrounds_mode7_perspective.html#autotoc_md1059',1,'1. Split-screen with HDMA'],['../examples_graphics_effects_hdma_wave.html#autotoc_md1139',1,'1. What Is HDMA?'],['../tutorial_dma.html#autotoc_md159',1,'DMA vs HDMA'],['../examples_graphics_effects_window.html#autotoc_md1254',1,'Making Non-Rectangular Shapes with HDMA'],['../examples_graphics_effects_transparent_window.html',1,'Transparent Window -- Color Math + HDMA']]],
  ['hdma_20—_20both_20windows_20animated_20per_20scanline_26',['Multi-window HDMA — both windows animated per scanline',['../examples_graphics_effects_window_multi_hdma.html',1,'examples_graphics_effects']]],
  ['hdma_20—_20examples_20graphics_20backgrounds_20mode7_5fperspective_27',['F-Zero perspective via HDMA — &lt;span class=&quot;tt&quot;&gt;examples/graphics/backgrounds/mode7_perspective&lt;/span&gt;',['../tutorial_mode7.html#autotoc_md276',1,'']]],
  ['hdma_20—_20examples_20graphics_20effects_20hdma_5findirect_5fgradient_28',['Indirect HDMA — &lt;span class=&quot;tt&quot;&gt;examples/graphics/effects/hdma_indirect_gradient&lt;/span&gt;',['../tutorial_hdma.html#autotoc_md216',1,'']]],
  ['hdma_20actually_20is_29',['What HDMA actually is',['../tutorial_hdma.html#autotoc_md204',1,'']]],
  ['hdma_20budget_30',['HDMA Budget',['../examples_graphics_backgrounds_mode7_perspective.html#autotoc_md1065',1,'']]],
  ['hdma_20channel_31',['4. Setting Up the HDMA Channel',['../examples_graphics_effects_hdma_wave.html#autotoc_md1142',1,'']]],
  ['hdma_20color_20gradients_32',['Gradient Colors -- HDMA Color Gradients',['../examples_graphics_effects_gradient_colors.html',1,'examples_graphics_effects']]],
  ['hdma_20enable_33',['$420C - HDMAEN (HDMA Enable)',['../registers.html#autotoc_md698',1,'']]],
  ['hdma_20fires_20before_20the_20user_20callback_20in_20the_20nmi_20handler_34',['🟡 HDMA fires before the user callback in the NMI handler',['../tutorial_hdma.html#autotoc_md225',1,'']]],
  ['hdma_20gradient_20table_20generation_35',['HDMA gradient table generation',['../tutorial_math.html#autotoc_md254',1,'']]],
  ['hdma_20helpers_20demo_36',['HDMA Helpers Demo',['../examples_graphics_effects_hdma_helpers.html',1,'examples_graphics_effects']]],
  ['hdma_20horizontal_20blank_20dma_37',['HDMA (Horizontal Blank DMA)',['../examples_graphics_effects.html#autotoc_md1213',1,'']]],
  ['hdma_20indirect_20gradient_38',['HDMA Indirect Gradient',['../examples_graphics_effects_hdma_indirect_gradient.html',1,'examples_graphics_effects']]],
  ['hdma_20isn_20t_20enough_3a_20h_20timer_20irq_20streaming_39',['When HDMA isn&apos;t enough: H-timer IRQ streaming',['../tutorial_hdma.html#autotoc_md220',1,'']]],
  ['hdma_20mode_203_202reg_5f2x_40',['HDMA Mode 3 (2REG_2X)',['../examples_graphics_effects_gradient_colors.html#autotoc_md1122',1,'']]],
  ['hdma_20on_20channel_200_41',['🟠 Channel 0 vs HDMA on channel 0',['../tutorial_dma.html#autotoc_md171',1,'']]],
  ['hdma_20on_20wh0_20wh1_20requires_20repeat_20mode_42',['🟠 HDMA on &lt;span class=&quot;tt&quot;&gt;WH0&lt;/span&gt;/&lt;span class=&quot;tt&quot;&gt;WH1&lt;/span&gt; requires repeat mode',['../tutorial_window.html#autotoc_md401',1,'']]],
  ['hdma_20parallax_20per_20scanline_20scroll_43',['HDMA Parallax (Per-Scanline Scroll)',['../tutorial_scrolling.html#autotoc_md327',1,'']]],
  ['hdma_20rectangle_44',['HDMA Rectangle',['../examples_graphics_effects_transparent_window.html#autotoc_md1243',1,'']]],
  ['hdma_20scroll_20table_45',['HDMA Scroll Table',['../examples_graphics_effects_parallax_scrolling.html#autotoc_md1199',1,'']]],
  ['hdma_20setup_46',['HDMA Setup',['../examples_graphics_effects_parallax_scrolling.html#autotoc_md1200',1,'']]],
  ['hdma_20table_20format_47',['2. The HDMA Table Format',['../examples_graphics_effects_hdma_wave.html#autotoc_md1140',1,'']]],
  ['hdma_20targets_20cgadd_20_242121_48',['1. HDMA targets CGADD ($2121)',['../examples_graphics_effects_gradient_colors.html#autotoc_md1117',1,'']]],
  ['hdma_20triangle_20masking_49',['Window -- HDMA Triangle Masking',['../examples_graphics_effects_window.html',1,'examples_graphics_effects']]],
  ['hdma_20tutorial_50',['HDMA Tutorial',['../tutorial_hdma.html',1,'index']]],
  ['hdma_20wave_51',['HDMA Wave',['../examples_graphics_effects_hdma_wave.html',1,'examples_graphics_effects']]],
  ['hdma_20wave_20table_52',['HDMA Wave Table',['../examples_graphics_effects_hdma_wave_table.html',1,'examples_graphics_effects']]],
  ['hdma_20works_53',['How HDMA Works',['../hdma_8h.html#autotoc_md29',1,'']]],
  ['hdma_5fhelpers_54',['Helpers showcase — &lt;span class=&quot;tt&quot;&gt;examples/graphics/effects/hdma_helpers&lt;/span&gt;',['../tutorial_hdma.html#autotoc_md213',1,'']]],
  ['hdma_5findirect_5fgradient_55',['Indirect HDMA — &lt;span class=&quot;tt&quot;&gt;examples/graphics/effects/hdma_indirect_gradient&lt;/span&gt;',['../tutorial_hdma.html#autotoc_md216',1,'']]],
  ['hdma_5fwave_56',['Per-scanline wave distortion — &lt;span class=&quot;tt&quot;&gt;examples/graphics/effects/hdma_wave&lt;/span&gt;',['../tutorial_hdma.html#autotoc_md210',1,'']]],
  ['hdma_5fwave_5ftable_57',['Table repointing as animation — &lt;span class=&quot;tt&quot;&gt;examples/graphics/effects/hdma_wave_table&lt;/span&gt;',['../tutorial_hdma.html#autotoc_md217',1,'']]],
  ['hdmaen_20hdma_20enable_58',['$420C - HDMAEN (HDMA Enable)',['../registers.html#autotoc_md698',1,'']]],
  ['hdmasetup_59',['🔴 Bank byte trap on &lt;span class=&quot;tt&quot;&gt;hdmaSetup&lt;/span&gt;',['../tutorial_hdma.html#autotoc_md223',1,'']]],
  ['header_60',['2. ROM header',['../tutorial_sram.html#autotoc_md353',1,'']]],
  ['header_20requirement_61',['ROM Header Requirement',['../sram_8h.html#autotoc_md63',1,'']]],
  ['headers_20h_62',['Headers (.h)',['../code_style.html#autotoc_md481',1,'']]],
  ['hello_63',['SuperFX Hello',['../examples_memory_superfx_hello.html',1,'examples_memory']]],
  ['hello_20world_64',['Hello World',['../examples_text_hello_world.html',1,'Hello World'],['../examples_memory_sa1_hello.html',1,'SA-1 Hello World']]],
  ['help_65',['Help',['../getting_started.html#autotoc_md435',1,'Getting Help'],['../troubleshooting.html#autotoc_md597',1,'Getting More Help']]],
  ['helper_20today_66',['🔴 Interleaved VRAM, no &lt;span class=&quot;tt&quot;&gt;mode7LoadGraphics&lt;/span&gt; helper today',['../tutorial_mode7.html#autotoc_md279',1,'']]],
  ['helpers_67',['Extended WRAM and Assembly Helpers',['../examples_maps_dynamic_map.html#autotoc_md1441',1,'']]],
  ['helpers_20and_20what_20they_20do_68',['The lib helpers and what they do',['../tutorial_mode7.html#autotoc_md273',1,'']]],
  ['helpers_20demo_69',['HDMA Helpers Demo',['../examples_graphics_effects_hdma_helpers.html',1,'examples_graphics_effects']]],
  ['helpers_20showcase_20—_20examples_20graphics_20effects_20hdma_5fhelpers_70',['Helpers showcase — &lt;span class=&quot;tt&quot;&gt;examples/graphics/effects/hdma_helpers&lt;/span&gt;',['../tutorial_hdma.html#autotoc_md213',1,'']]],
  ['here_71',['Start Here',['../index.html#autotoc_md0',1,'']]],
  ['here_72',['What &quot;main&quot; and &quot;sub&quot; mean here',['../tutorial_colormath.html#autotoc_md132',1,'']]],
  ['hex_73',['2. Drawing Letters in Hex',['../examples_text_hello_world.html#autotoc_md1551',1,'']]],
  ['hi_20res_20512×256_20background_74',['Mode 5 — Hi-Res 512×256 Background',['../examples_graphics_backgrounds_mode5.html',1,'examples_graphics_backgrounds']]],
  ['hi_20res_20and_20interlace_20modes_205_206_20setini_75',['Hi-res and interlace (Modes 5/6, SETINI)',['../tutorial_graphics.html#autotoc_md202',1,'']]],
  ['hi_20res_20text_20—_20bg_20mode_205_20interlace_20512_20×_20448_76',['Hi-res text — BG Mode 5 + interlace (512 × 448)',['../examples_graphics_effects_hires_text.html',1,'examples_graphics_effects']]],
  ['hicolor_20—_201792_20colors_20from_20a_204bpp_20background_77',['HiColor — 1792 colors from a 4bpp background',['../examples_graphics_effects_hicolor_1792.html',1,'examples_graphics_effects']]],
  ['hiding_20sprites_78',['Hiding Sprites',['../tutorial_sprites.html#autotoc_md339',1,'Hiding Sprites'],['../oam.html#autotoc_md638',1,'Hiding Sprites']]],
  ['high_79',['Mode 1 with BG3 Priority High',['../examples_graphics_effects_transparency.html#autotoc_md1228',1,'']]],
  ['high_20priority_80',['3. Enable BG3 high priority',['../examples_graphics_backgrounds_mode1_bg3_priority.html#autotoc_md1007',1,'']]],
  ['high_20priority_20hud_20layer_20over_20backgrounds_81',['Mode 1 BG3 High Priority -- HUD Layer Over Backgrounds',['../examples_graphics_backgrounds_mode1_bg3_priority.html',1,'examples_graphics_backgrounds']]],
  ['high_20table_82',['OAM High Table',['../examples_graphics_sprites_object_size.html#autotoc_md1326',1,'']]],
  ['hirom_83',['HiROM',['../hardware_overview.html#autotoc_md656',1,'LoROM vs HiROM'],['../examples_memory_hirom_demo.html#autotoc_md1494',1,'LoROM vs HiROM'],['../examples_memory.html#autotoc_md1501',1,'LoROM vs HiROM'],['../examples_memory_hirom_demo.html#autotoc_md1495',1,'When to Use HiROM']]],
  ['hirom_20demo_20understanding_20snes_20memory_20mapping_84',['HiROM Demo -- Understanding SNES Memory Mapping',['../examples_memory_hirom_demo.html',1,'examples_memory']]],
  ['hirom_20in_20the_20makefile_85',['1. Enable HiROM in the Makefile',['../examples_memory_hirom_demo.html#autotoc_md1489',1,'']]],
  ['hirom_20music_86',['SNESMOD HiROM Music',['../examples_audio_snesmod_music_hirom.html',1,'examples_audio']]],
  ['hood_3a_20the_20build_87',['Hood: The Build',['../examples_games_breakout.html#autotoc_md861',1,'Under the Hood: The Build'],['../examples_games_likemario.html#autotoc_md887',1,'Under the Hood: The Build'],['../examples_graphics_backgrounds_continuous_scroll.html#autotoc_md940',1,'Under the Hood: The Build'],['../examples_graphics_effects_hdma_wave.html#autotoc_md1150',1,'Under the Hood: The Build'],['../examples_input_superscope.html#autotoc_md1392',1,'Under the Hood: The Build'],['../examples_text_hello_world.html#autotoc_md1562',1,'Under the Hood: The Build']]],
  ['horizontal_20blank_20dma_88',['HDMA (Horizontal Blank DMA)',['../examples_graphics_effects.html#autotoc_md1213',1,'']]],
  ['horizontal_20mirror_89',['OBJ_FLIPX &amp;ndash; Hardware Horizontal Mirror',['../examples_graphics_sprites_animated_sprite.html#autotoc_md1283',1,'']]],
  ['hot_20loops_90',['4. CACHE Before Hot Loops',['../tutorial_superfx.html#autotoc_md382',1,'']]],
  ['how_20bg_20scrolling_20works_91',['How BG Scrolling Works',['../tutorial_scrolling.html#autotoc_md320',1,'']]],
  ['how_20color_20math_20works_92',['How Color Math Works',['../colormath_8h.html#autotoc_md16',1,'']]],
  ['how_20hdma_20works_93',['How HDMA Works',['../hdma_8h.html#autotoc_md29',1,'']]],
  ['how_20input_20works_20on_20the_20snes_94',['How Input Works on the SNES',['../examples_input_controller.html#autotoc_md1356',1,'']]],
  ['how_20it_20works_95',['How It Works',['../tutorial_animation.html#autotoc_md81',1,'How It Works'],['../examples_games_mapandobjects.html#autotoc_md902',1,'How It Works'],['../examples_graphics_backgrounds_mixed_scroll.html#autotoc_md954',1,'How It Works'],['../examples_graphics_backgrounds_mode1_bg3_priority.html#autotoc_md1004',1,'How It Works'],['../examples_graphics_backgrounds_mode1_lz77.html#autotoc_md1021',1,'How It Works'],['../examples_graphics_backgrounds_mode7.html#autotoc_md1042',1,'How It Works'],['../examples_graphics_backgrounds_mode7_perspective.html#autotoc_md1058',1,'How It Works'],['../examples_graphics_effects_gradient_colors.html#autotoc_md1116',1,'How It Works'],['../examples_graphics_effects_mosaic.html#autotoc_md1184',1,'How It Works'],['../examples_graphics_effects_parallax_scrolling.html#autotoc_md1197',1,'How It Works'],['../examples_graphics_effects_transparent_window.html#autotoc_md1240',1,'How It Works'],['../examples_graphics_effects_window.html#autotoc_md1252',1,'How It Works'],['../examples_graphics_sprites_animated_sprite.html#autotoc_md1277',1,'How It Works'],['../examples_graphics_sprites_dynamic_sprite.html#autotoc_md1296',1,'How It Works'],['../examples_graphics_sprites_metasprite.html#autotoc_md1313',1,'How It Works'],['../examples_graphics_sprites_object_size.html#autotoc_md1319',1,'How It Works'],['../examples_graphics_sprites_simple_sprite.html#autotoc_md1341',1,'How It Works'],['../examples_input_mouse.html#autotoc_md1367',1,'How It Works'],['../examples_maps_dynamic_map.html#autotoc_md1444',1,'How It Works'],['../examples_maps_slopemario.html#autotoc_md1471',1,'How It Works'],['../examples_memory_hirom_demo.html#autotoc_md1488',1,'How It Works'],['../examples_memory_save_game.html#autotoc_md1516',1,'How It Works'],['../examples_text_text_test.html#autotoc_md1582',1,'How It Works']]],
  ['how_20text_20works_20on_20snes_96',['How Text Works on SNES',['../examples_text.html#autotoc_md1571',1,'']]],
  ['how_20to_20build_97',['How to Build',['../examples_basics_aim_target.html#autotoc_md794',1,'How to Build'],['../examples_basics_fix32_orbit.html#autotoc_md814',1,'How to Build'],['../examples_basics_scene_stack.html#autotoc_md833',1,'How to Build'],['../examples_graphics_effects_gradient_9bit.html#autotoc_md1110',1,'How to Build'],['../examples_graphics_effects_hdma_indirect_gradient.html#autotoc_md1132',1,'How to Build'],['../examples_graphics_effects_hdma_wave_table.html#autotoc_md1159',1,'How to Build'],['../examples_graphics_effects_hicolor_1792.html#autotoc_md1165',1,'How to Build'],['../examples_graphics_effects_hires_text.html#autotoc_md1171',1,'How to Build'],['../examples_graphics_effects_mode7_perspective_rotate.html#autotoc_md1178',1,'How to Build'],['../examples_graphics_effects_window_multi_hdma.html#autotoc_md1266',1,'How to Build']]],
  ['how_20windows_20work_98',['How Windows Work',['../window_8h.html#autotoc_md65',1,'']]],
  ['htimex_20vtimex_20irq_20timer_99',['$4207-$420A - HTIMEx/VTIMEx (IRQ Timer)',['../registers.html#autotoc_md689',1,'']]],
  ['hud_20layer_20over_20backgrounds_100',['Mode 1 BG3 High Priority -- HUD Layer Over Backgrounds',['../examples_graphics_backgrounds_mode1_bg3_priority.html',1,'examples_graphics_backgrounds']]],
  ['hud_20on_20bg3_101',['Open chantier — S6 HUD on BG3',['../examples_games_shmup_1942.html#autotoc_md915',1,'']]],
  ['hvbjoy_20blank_20joypad_20status_102',['$4212 - HVBJOY (Blank/Joypad Status)',['../registers.html#autotoc_md692',1,'']]]
];
