var searchData=
[
  ['f_20zero_20perspective_20via_20hdma_20—_20examples_20mode7_20perspective_0',['F-Zero perspective via HDMA — &lt;span class=&quot;tt&quot;&gt;examples/mode7/perspective&lt;/span&gt;',['../tutorial_mode7.html#f-zero-perspective-via-hdma--examplesmode7perspective',1,'']]],
  ['f_20zero_20style_20mini_20game_1',['mode7_racing — an F-Zero-style mini game',['../examples_games_mode7_racing.html',1,'examples_games']]],
  ['fade_2',['Fade',['../examples_transitions_fading.html#alternative-palette-fade',1,'Alternative: Palette Fade'],['../examples_transitions_fading.html#exercise-1-smooth-fade',1,'Exercise 1: Smooth Fade'],['../examples_transitions_fading.html#exercise-3-color-fade',1,'Exercise 3: Color Fade'],['../tutorial_game_states.html#game-over-with-fade',1,'Game Over with Fade']]],
  ['fade_20during_20gameplay_3',['Fade During Gameplay',['../examples_transitions_fading.html#fade-during-gameplay',1,'']]],
  ['fade_20effect_20brightness_4',['1. Fade effect (brightness)',['../examples_transitions_mosaic.html#autotoc_md1-fade-effect-brightness',1,'']]],
  ['fade_20implementation_5',['Basic Fade Implementation',['../examples_transitions_fading.html#basic-fade-implementation',1,'']]],
  ['fade_20in_6',['Fade Out / Fade In',['../tutorial_game_states.html#fade-out--fade-in',1,'']]],
  ['fade_20in_20black_20to_20full_7',['Fade In (Black to Full)',['../examples_transitions_fading.html#fade-in-black-to-full',1,'']]],
  ['fade_20out_20fade_20in_8',['Fade Out / Fade In',['../tutorial_game_states.html#fade-out--fade-in',1,'']]],
  ['fade_20out_20full_20to_20black_9',['Fade Out (Full to Black)',['../examples_transitions_fading.html#fade-out-full-to-black',1,'']]],
  ['fade_20speeds_10',['Fade Speeds',['../examples_transitions_fading.html#fade-speeds',1,'']]],
  ['fade_20to_20black_20fade_20to_20white_11',['Fade-to-black / fade-to-white',['../tutorial_colormath.html#fade-to-black--fade-to-white',1,'']]],
  ['fade_20to_20white_12',['Fade-to-black / fade-to-white',['../tutorial_colormath.html#fade-to-black--fade-to-white',1,'']]],
  ['fades_20and_20dissolves_13',['Punctuate scene changes — fades and dissolves',['../craft_game_feel.html#punctuate-scene-changes--fades-and-dissolves',1,'']]],
  ['fading_20example_14',['Fading Example',['../examples_transitions_fading.html',1,'examples_transitions']]],
  ['fails_20with_20library_20not_20built_15',['Build fails with &quot;Library not built&quot;',['../getting_started.html#build-fails-with-library-not-built',1,'']]],
  ['fails_20with_20refusing_20to_20emit_20silently_20wrong_20code_16',['fails with refusing to emit silently wrong code',['../getting_started.html#build-fails-with-refusing-to-emit-silently-wrong-code',1,'Build fails with &quot;refusing to emit silently-wrong code&quot;'],['../troubleshooting.html#build-fails-with-refusing-to-emit-silently-wrong-code-1',1,'Build fails with &quot;refusing to emit silently-wrong code&quot;']]],
  ['fails_20with_20smconv_20error_17',['Build fails with smconv error',['../examples_audio_snesmod_music.html#build-fails-with-smconv-error',1,'']]],
  ['family_18',['The family',['../tools_conventions.html#the-family',1,'']]],
  ['far_20and_20casting_20const_20away_20breaks_20it_19',['Trap 5: const data is far, and casting &lt;span class=&quot;tt&quot;&gt;const&lt;/span&gt; away breaks it',['../migrating_pvsneslib.html#trap-5-const-data-is-far-and-casting-const-away-breaks-it',1,'']]],
  ['far_20fewer_20per_20line_20',['3. OAM — 128 sprites, but far fewer per line',['../craft_planning.html#autotoc_md3-oam--128-sprites-but-far-fewer-per-line',1,'']]],
  ['far_20is_20the_20way_20above_20it_21',['🟡 Plain C RAM lives below $2000; &lt;span class=&quot;tt&quot;&gt;FAR&lt;/span&gt; is the way above it',['../KNOWN_LIMITATIONS.html#autotoc_md-plain-c-ram-lives-below-2000-far-is-the-way-above-it',1,'']]],
  ['far_20objects_20beyond_20the_208_20kb_20band_22',['Far RAM Tutorial — FAR objects beyond the 8 KB band',['../tutorial_far_ram.html',1,'index']]],
  ['far_20pointer_20at_200_2049_23',['&lt;span class=&quot;tt&quot;&gt;dmaTransfer()&lt;/span&gt; takes the source as one far pointer at 0.49',['../upgrading.html#dmatransfer-takes-the-source-as-one-far-pointer-at-049',1,'']]],
  ['far_20ram_20tutorial_20—_20far_20objects_20beyond_20the_208_20kb_20band_24',['Far RAM Tutorial — FAR objects beyond the 8 KB band',['../tutorial_far_ram.html',1,'index']]],
  ['far_20struct_20is_20copied_20field_20by_20field_25',['🟡 Struct parameters and struct returns by value are refused; a FAR struct is copied field by field',['../KNOWN_LIMITATIONS.html#autotoc_md-struct-parameters-and-struct-returns-by-value-are-refused-a-far-struct-is-copied-field-by-field',1,'']]],
  ['fast_20transfers_26',['DMA Registers (for fast transfers)',['../snes_graphics_guide.html#dma-registers-for-fast-transfers',1,'']]],
  ['faster_27',['Going faster',['../api_index.html#going-faster',1,'']]],
  ['fatal_3a_20repository_20not_20found_20or_20empty_20compiler_20folder_28',['&quot;fatal: repository not found&quot; or empty compiler folder',['../getting_started.html#fatal-repository-not-found-or-empty-compiler-folder',1,'']]],
  ['feature_20runtime_20rom_202026_2009_2013_29',['🟢 Five silent miscompilations found and fixed by the C-feature runtime ROM (2026-09-13)',['../KNOWN_LIMITATIONS.html#autotoc_md-five-silent-miscompilations-found-and-fixed-by-the-c-feature-runtime-rom-2026-09-13',1,'']]],
  ['features_30',['Features',['../audio_8h.html#features',1,'Features'],['../examples_games_tetris.html#features-1',1,'Features'],['../examples_audio_snesmod_music.html#key-features',1,'Key Features'],['../contributing.html#suggesting-features',1,'Suggesting Features']]],
  ['features_31',['Acceptance criteria for new features',['../PHILOSOPHY.html#acceptance-criteria-for-new-features',1,'']]],
  ['feedback_32',['4. Interactive feedback',['../examples_memory_hirom_demo.html#autotoc_md4-interactive-feedback',1,'']]],
  ['feel_20good_33',['Stage 4 — &quot;Can I make it feel good?&quot;',['../learning_path.html#stage-4--can-i-make-it-feel-good',1,'']]],
  ['feel_3a_20juice_20on_20real_20hardware_34',['Game feel: juice on real hardware',['../craft_game_feel.html',1,'craft']]],
  ['few_20seconds_35',['ROM runs but crashes after a few seconds',['../troubleshooting.html#rom-runs-but-crashes-after-a-few-seconds',1,'']]],
  ['fewer_20per_20line_36',['3. OAM — 128 sprites, but far fewer per line',['../craft_planning.html#autotoc_md3-oam--128-sprites-but-far-fewer-per-line',1,'']]],
  ['fidelity_20to_20the_20original_20hand_20mode_20measured_20not_20assumed_37',['Fidelity to the original (hand mode; measured, not assumed)',['../examples_hdma_hdma_wave.html#fidelity-to-the-original-hand-mode-measured-not-assumed',1,'']]],
  ['fidelity_20to_20the_20original_20measured_20not_20assumed_38',['Fidelity to the original (measured, not assumed)',['../examples_hdma_hdma_indirect_gradient.html#fidelity-to-the-original-measured-not-assumed',1,'']]],
  ['fidelity_20vs_20the_20original_39',['fidelity vs the original',['../examples_audio_speech_synth.html#register-fidelity-vs-the-original',1,'Register fidelity vs the original'],['../examples_backgrounds_mode5_hires.html#register-fidelity-vs-the-original-1',1,'Register fidelity vs the original'],['../examples_color_hicolor_1792.html#register-fidelity-vs-the-original-2',1,'Register fidelity vs the original'],['../examples_mode7_perspective_rotate.html#register-fidelity-vs-the-original-3',1,'Register fidelity vs the original'],['../examples_windows_window_multi_hdma.html#register-fidelity-vs-the-original-4',1,'Register fidelity vs the original']]],
  ['field_40',['field',['../KNOWN_LIMITATIONS.html#autotoc_md-struct-parameters-and-struct-returns-by-value-are-refused-a-far-struct-is-copied-field-by-field',1,'🟡 Struct parameters and struct returns by value are refused; a FAR struct is copied field by field'],['../tutorial_object.html#who-owns-which-field',1,'Who owns which field']]],
  ['field_20by_20field_41',['🟡 Struct parameters and struct returns by value are refused; a FAR struct is copied field by field',['../KNOWN_LIMITATIONS.html#autotoc_md-struct-parameters-and-struct-returns-by-value-are-refused-a-far-struct-is-copied-field-by-field',1,'']]],
  ['file_42',['The settings file',['../tools_opensnes_level.html#the-settings-file',1,'']]],
  ['file_20organization_43',['File Organization',['../code_style.html#file-organization',1,'']]],
  ['files_44',['Files',['../examples_audio_snesmod_music.html#files',1,'Files'],['../examples_audio_snesmod_sfx.html#files-1',1,'Files'],['../examples_backgrounds_mode1.html#files-2',1,'Files'],['../examples_basics_collision_demo.html#files-3',1,'Files'],['../examples_color_transparency.html#files-4',1,'Files'],['../examples_fundamentals_text_glyphs.html#files-5',1,'Files'],['../examples_games_breakout.html#files-6',1,'Files'],['../examples_games_likemario.html#files-7',1,'Files'],['../examples_hdma_hdma_wave.html#files-8',1,'Files'],['../examples_input_superscope.html#files-9',1,'Files'],['../examples_input_two_players.html#files-10',1,'Files'],['../examples_scrolling_continuous_scroll.html#files-11',1,'Files'],['../examples_transitions_fading.html#files-12',1,'Files'],['../examples_audio_snesmod_music.html#generated-files',1,'Generated Files'],['../examples_chips_superfx_3d.html#per-example-files',1,'Per-Example Files'],['../examples_chips_superfx_game_skeleton.html#per-example-files-1',1,'Per-Example Files']]],
  ['files_45',['opensnes-save — battery save files',['../tools_opensnes_save.html',1,'tools']]],
  ['filter_20coefficients_20coef_200f_207f_46',['FIR Filter Coefficients (COEF 0F-7F)',['../snes_sound_guide.html#fir-filter-coefficients-coef-0f-7f',1,'']]],
  ['filters_47',['Filters',['../snes_sound_guide.html#filters',1,'']]],
  ['finish_48',['Scope a first game you can finish',['../craft_planning.html#scope-a-first-game-you-can-finish',1,'']]],
  ['finish_20and_20ship_49',['Stage 6 — &quot;Can I finish and ship?&quot;',['../learning_path.html#stage-6--can-i-finish-and-ship',1,'']]],
  ['fir_20filter_20coefficients_20coef_200f_207f_50',['FIR Filter Coefficients (COEF 0F-7F)',['../snes_sound_guide.html#fir-filter-coefficients-coef-0f-7f',1,'']]],
  ['fires_20before_20the_20user_20callback_20in_20the_20nmi_20handler_51',['🟡 HDMA fires before the user callback in the NMI handler',['../tutorial_hdma.html#autotoc_md-hdma-fires-before-the-user-callback-in-the-nmi-handler',1,'']]],
  ['firmware_20needed_20by_20low_20level_20emulators_52',['🟡 Firmware needed by low-level emulators',['../tutorial_dsp1.html#autotoc_md-firmware-needed-by-low-level-emulators',1,'']]],
  ['firmware_20requirement_53',['Firmware requirement',['../examples_chips_dsp1_cube.html#firmware-requirement',1,'']]],
  ['first_20boot_20are_20undefined_54',['🔴 SRAM contents on first boot are undefined',['../tutorial_sram.html#autotoc_md-sram-contents-on-first-boot-are-undefined',1,'']]],
  ['first_20game_20you_20can_20finish_55',['Scope a first game you can finish',['../craft_planning.html#scope-a-first-game-you-can-finish',1,'']]],
  ['first_20issues_56',['Good First Issues',['../contributing.html#good-first-issues',1,'']]],
  ['first_20oam_20sprite_57',['Simple Sprite -- Your First OAM Sprite',['../examples_sprites_simple_sprite.html',1,'examples_sprites']]],
  ['first_20rom_58',['A4. Run Your First ROM',['../getting_started.html#a4-run-your-first-rom',1,'']]],
  ['first_20steps_59',['Level 1 &amp;ndash; First Steps',['../examples.html#level-1----first-steps',1,'']]],
  ['first_20vblank_60',['🟡 Expecting text before the first VBlank',['../tutorial_text.html#autotoc_md-expecting-text-before-the-first-vblank',1,'']]],
  ['fit_20with_20the_20rest_20of_20the_20docs_61',['Where they fit with the rest of the docs',['../tools.html#where-they-fit-with-the-rest-of-the-docs',1,'']]],
  ['fits_62',['fits',['../tools_aseprite2snes.html#where-it-fits',1,'Where it fits'],['../tools_font2snes.html#where-it-fits-1',1,'Where it fits'],['../tools_img2snes.html#where-it-fits-2',1,'Where it fits']]],
  ['five_20principles_63',['The five principles',['../PHILOSOPHY.html#the-five-principles',1,'']]],
  ['five_20silent_20miscompilations_20found_20and_20fixed_20by_20the_20c_20feature_20runtime_20rom_202026_2009_2013_64',['🟢 Five silent miscompilations found and fixed by the C-feature runtime ROM (2026-09-13)',['../KNOWN_LIMITATIONS.html#autotoc_md-five-silent-miscompilations-found-and-fixed-by-the-c-feature-runtime-rom-2026-09-13',1,'']]],
  ['five_20traps_65',['Step 2 — the five traps',['../migrating_pvsneslib.html#step-2--the-five-traps',1,'']]],
  ['fix_20s5_202_66',['Bullet despawn fix (S5.2)',['../examples_games_shmup_1942.html#bullet-despawn-fix-s52',1,'']]],
  ['fix_20x_20overflows_20for_20x_20≥_20128_67',['🔴 &lt;span class=&quot;tt&quot;&gt;FIX(x)&lt;/span&gt; overflows for &lt;span class=&quot;tt&quot;&gt;|x| ≥ 128&lt;/span&gt;',['../tutorial_math.html#autotoc_md-fixx-overflows-for-x--128',1,'']]],
  ['fix32_5forbit_68',['fix32_orbit',['../examples_basics_fix32_orbit.html',1,'examples_basics']]],
  ['fixdiv_20returns_200_20on_20divide_20by_20zero_69',['🟠 &lt;span class=&quot;tt&quot;&gt;fixDiv&lt;/span&gt; returns 0 on divide-by-zero',['../tutorial_math.html#autotoc_md-fixdiv-returns-0-on-divide-by-zero',1,'']]],
  ['fixed_202026_2005_2021_70',['🟢 C function returning &lt;span class=&quot;tt&quot;&gt;long&lt;/span&gt; propagates the high half (fixed 2026-05-21)',['../KNOWN_LIMITATIONS.html#autotoc_md-c-function-returning-long-propagates-the-high-half-fixed-2026-05-21',1,'']]],
  ['fixed_202026_2009_2015_71',['🟢 &lt;span class=&quot;tt&quot;&gt;sramClear()&lt;/span&gt; wrote a byte ramp instead of zeros (fixed 2026-09-15)',['../KNOWN_LIMITATIONS.html#autotoc_md-sramclear-wrote-a-byte-ramp-instead-of-zeros-fixed-2026-09-15',1,'']]],
  ['fixed_202026_2009_2018_72',['fixed 2026 09 18',['../tutorial_object.html#autotoc_md-act_burn-and-act_die-went-to-slot-0--fixed-2026-09-18',1,'🟢 &lt;span class=&quot;tt&quot;&gt;ACT_BURN&lt;/span&gt; and &lt;span class=&quot;tt&quot;&gt;ACT_DIE&lt;/span&gt; went to slot 0 — fixed 2026-09-18'],['../tutorial_object.html#autotoc_md-objinitfunctions-stored-garbage--fixed-2026-09-18',1,'🟢 &lt;span class=&quot;tt&quot;&gt;objInitFunctions&lt;/span&gt; stored garbage — fixed 2026-09-18'],['../tutorial_object.html#autotoc_md-objinitgravitys-gravity-argument-did-nothing--fixed-2026-09-18',1,'🟢 &lt;span class=&quot;tt&quot;&gt;objInitGravity&lt;/span&gt;&apos;s gravity argument did nothing — fixed 2026-09-18'],['../tutorial_object.html#autotoc_md-objloadobjects-ignored-the-bank-byte-of-your-pointer--fixed-2026-09-18',1,'🟢 &lt;span class=&quot;tt&quot;&gt;objLoadObjects&lt;/span&gt; ignored the bank byte of your pointer — fixed 2026-09-18']]],
  ['fixed_202026_2009_2019_73',['fixed 2026 09 19',['../tutorial_object.html#autotoc_md-objkillall-leaked-slots--fixed-2026-09-19',1,'🟢 &lt;span class=&quot;tt&quot;&gt;objKillAll&lt;/span&gt; leaked slots — fixed 2026-09-19'],['../tutorial_object.html#autotoc_md-a-callback-that-peeked-at-another-object-became-a-copy-of-it--fixed-2026-09-19',1,'🟢 A callback that peeked at another object became a copy of it — fixed 2026-09-19'],['../tutorial_object.html#autotoc_md-a-type-with-no-registered-callbacks-jumped-into-nowhere--fixed-2026-09-19',1,'🟢 A type with no registered callbacks jumped into nowhere — fixed 2026-09-19']]],
  ['fixed_202026_2009_2020_74',['fixed 2026 09 20',['../tutorial_object.html#autotoc_md-objcollidobj-returned-garbage-for-no-contact--fixed-2026-09-20',1,'🟢 &lt;span class=&quot;tt&quot;&gt;objCollidObj&lt;/span&gt; returned garbage for &quot;no contact&quot; — fixed 2026-09-20'],['../KNOWN_LIMITATIONS.html#autotoc_md-hirom-every-c-pointer-to-ram-carried-a-rom-bank-fixed-2026-09-20',1,'🟢 HiROM: every C pointer to RAM carried a ROM bank (fixed 2026-09-20)'],['../KNOWN_LIMITATIONS.html#autotoc_md-sram-used-the-lorom-address-on-every-build-fixed-2026-09-20',1,'🟢 SRAM used the LoROM address on every build (fixed 2026-09-20)'],['../tutorial_object.html#autotoc_md-three-ways-a-pending-workspace-edit-could-be-lost-or-do-damage--fixed-2026-09-20',1,'🟢 Three ways a pending workspace edit could be lost or do damage — fixed 2026-09-20']]],
  ['fixed_202026_2009_2021_75',['🟢 The address of a local variable had an undefined bank (fixed 2026-09-21)',['../KNOWN_LIMITATIONS.html#autotoc_md-the-address-of-a-local-variable-had-an-undefined-bank-fixed-2026-09-21',1,'']]],
  ['fixed_202026_2009_2023_76',['fixed 2026 09 23',['../tutorial_object.html#autotoc_md-the-collision-routines-read-the-map-from-bank-00--fixed-2026-09-23',1,'🟢 The collision routines read the map from bank &lt;span class=&quot;tt&quot;&gt;$00&lt;/span&gt; — fixed 2026-09-23'],['../KNOWN_LIMITATIONS.html#autotoc_md-the-object-engine-read-the-map-from-bank-00-whatever-bank-it-was-in-fixed-2026-09-23',1,'🟢 The object engine read the map from bank $00 whatever bank it was in (fixed 2026-09-23)']]],
  ['fixed_202026_2009_2024_77',['🟢 The HiROM header claimed 256 KB for a 512 KB ROM; ROM size is a knob now (fixed 2026-09-24)',['../KNOWN_LIMITATIONS.html#autotoc_md-the-hirom-header-claimed-256-kb-for-a-512-kb-rom-rom-size-is-a-knob-now-fixed-2026-09-24',1,'']]],
  ['fixed_202026_2009_2025_78',['🟢 Super FX: VBlanks were lost during every GSU job (fixed 2026-09-25)',['../KNOWN_LIMITATIONS.html#autotoc_md-super-fx-vblanks-were-lost-during-every-gsu-job-fixed-2026-09-25',1,'']]],
  ['fixed_202026_2009_2026_79',['fixed 2026 09 26',['../KNOWN_LIMITATIONS.html#autotoc_md-padisconnected-answered-1-for-an-empty-port-fixed-2026-09-26',1,'🟢 &lt;span class=&quot;tt&quot;&gt;padIsConnected()&lt;/span&gt; answered 1 for an empty port (fixed 2026-09-26)'],['../KNOWN_LIMITATIONS.html#autotoc_md-snesmod-stop-and-pause-sometimes-left-a-voice-sounding-fixed-2026-09-26',1,'🟢 SNESMOD stop and pause sometimes left a voice sounding (fixed 2026-09-26)']]],
  ['fixed_202026_2009_2029_80',['🟢 Super FX: &lt;span class=&quot;tt&quot;&gt;gsuDmaFullFrame()&lt;/span&gt; wrote a third of the framebuffer on visible lines (fixed 2026-09-29)',['../KNOWN_LIMITATIONS.html#autotoc_md-super-fx-gsudmafullframe-wrote-a-third-of-the-framebuffer-on-visible-lines-fixed-2026-09-29',1,'']]],
  ['fixed_202026_2010_2003_81',['🟢 &lt;span class=&quot;tt&quot;&gt;snesmodProcess()&lt;/span&gt; latched the H/V counters and cut its own wait short; the command queue wrapped (fixed 2026-10-03)',['../KNOWN_LIMITATIONS.html#autotoc_md-snesmodprocess-latched-the-hv-counters-and-cut-its-own-wait-short-the-command-queue-wrapped-fixed-2026-10-03',1,'']]],
  ['fixed_20by_20the_20c_20feature_20runtime_20rom_202026_2009_2013_82',['🟢 Five silent miscompilations found and fixed by the C-feature runtime ROM (2026-09-13)',['../KNOWN_LIMITATIONS.html#autotoc_md-five-silent-miscompilations-found-and-fixed-by-the-c-feature-runtime-rom-2026-09-13',1,'']]],
  ['fixed_20point_83',['Positions are 24-bit fixed point',['../tutorial_object.html#positions-are-24-bit-fixed-point',1,'']]],
  ['fixed_20point_20arithmetic_84',['Fixed-point arithmetic',['../tutorial_math.html#fixed-point-arithmetic',1,'']]],
  ['fixed_20point_20format_85',['Fixed-Point Format',['../math_8h.html#fixed-point-format',1,'']]],
  ['fixed_20point_20format_86',['The 8.8 fixed-point format',['../tutorial_math.html#the-88-fixed-point-format',1,'']]],
  ['fixed_20point_20math_20tutorial_87',['Fixed-Point Math Tutorial',['../tutorial_math.html',1,'index']]],
  ['fixed_20point_20on_20the_20snes_88',['Why fixed-point on the SNES',['../tutorial_math.html#why-fixed-point-on-the-snes',1,'']]],
  ['fixed_20point_20physics_89',['4. Fixed-Point Physics',['../examples_games_likemario.html#autotoc_md4-fixed-point-physics',1,'']]],
  ['fixed_20point_20scale_90',['8.8 Fixed-Point Scale',['../examples_mode7_rotate_scale.html#autotoc_md88-fixed-point-scale',1,'']]],
  ['fixed_20point_3a_20three_20slot_20types_91',['Fixed-point: three slot types',['../tutorial_dsp1.html#fixed-point-three-slot-types',1,'']]],
  ['fixlerp_20are_20not_20safe_20inside_20nmiset_20callbacks_92',['🟡 &lt;span class=&quot;tt&quot;&gt;fixMul()&lt;/span&gt; / &lt;span class=&quot;tt&quot;&gt;fixLerp()&lt;/span&gt; are not safe inside nmiSet() callbacks',['../KNOWN_LIMITATIONS.html#autotoc_md-fixmul--fixlerp-are-not-safe-inside-nmiset-callbacks',1,'']]],
  ['fixmul_20fixlerp_20are_20not_20safe_20inside_20nmiset_20callbacks_93',['🟡 &lt;span class=&quot;tt&quot;&gt;fixMul()&lt;/span&gt; / &lt;span class=&quot;tt&quot;&gt;fixLerp()&lt;/span&gt; are not safe inside nmiSet() callbacks',['../KNOWN_LIMITATIONS.html#autotoc_md-fixmul--fixlerp-are-not-safe-inside-nmiset-callbacks',1,'']]],
  ['fixmul_20truncates_20fractional_20precision_94',['🔴 &lt;span class=&quot;tt&quot;&gt;fixMul&lt;/span&gt; truncates fractional precision',['../tutorial_math.html#autotoc_md-fixmul-truncates-fractional-precision',1,'']]],
  ['flag_20sync_20producer_20consumer_95',['Pattern 1: Flag Sync (Producer/Consumer)',['../tutorial_sa1.html#pattern-1-flag-sync-producerconsumer',1,'']]],
  ['flags_96',['3. Scroll Updates via bgSetScroll Dirty Flags',['../examples_scrolling_continuous_scroll.html#autotoc_md3-scroll-updates-via-bgsetscroll-dirty-flags',1,'']]],
  ['flags_20behind_20the_20makefile_97',['The flags behind the Makefile',['../tools_smconv.html#the-flags-behind-the-makefile',1,'']]],
  ['flags_20that_20decide_20everything_3a_20u_20and_20s_98',['The two flags that decide everything: &lt;span class=&quot;tt&quot;&gt;-u&lt;/span&gt; and &lt;span class=&quot;tt&quot;&gt;-s&lt;/span&gt;',['../tools_gfx4snes.html#the-two-flags-that-decide-everything--u-and--s',1,'']]],
  ['flags_20you_20will_20actually_20use_99',['flags you will actually use',['../tools_font2snes.html#the-flags-you-will-actually-use',1,'The flags you will actually use'],['../tools_gfx4snes.html#the-flags-you-will-actually-use-1',1,'The flags you will actually use'],['../tools_img2snes.html#the-flags-you-will-actually-use-2',1,'The flags you will actually use'],['../tools_palplan.html#the-flags-you-will-actually-use-3',1,'The flags you will actually use'],['../tools_wav2brr.html#the-flags-you-will-actually-use-4',1,'The flags you will actually use']]],
  ['flash_100',['Quick Flash',['../examples_transitions_fading.html#quick-flash',1,'']]],
  ['flash_20—_20color_20math_20not_20palette_20edits_101',['Hit flash — color math, not palette edits',['../craft_game_feel.html#hit-flash--color-math-not-palette-edits',1,'']]],
  ['flicker_20page_20flip_20desync_102',['Recipe 6 — Temporal artefacts (flicker, page-flip desync)',['../tutorial_debugging.html#recipe-6--temporal-artefacts-flicker-page-flip-desync',1,'']]],
  ['flip_103',['Exercise 3: Tile Flip',['../examples_backgrounds_mode1.html#exercise-3-tile-flip',1,'']]],
  ['flip_20desync_104',['Recipe 6 — Temporal artefacts (flicker, page-flip desync)',['../tutorial_debugging.html#recipe-6--temporal-artefacts-flicker-page-flip-desync',1,'']]],
  ['floor_105',['DSP-1 Ground — the Super Mario Kart floor',['../examples_mode7_dsp1_ground.html',1,'examples_mode7']]],
  ['floor_20via_20the_20dsp_201_20—_20examples_20mode7_20dsp1_5fground_106',['The Super Mario Kart floor via the DSP-1 — &lt;span class=&quot;tt&quot;&gt;examples/mode7/dsp1_ground&lt;/span&gt;',['../tutorial_mode7.html#the-super-mario-kart-floor-via-the-dsp-1--examplesmode7dsp1_ground',1,'']]],
  ['flow_107',['Complete Title Flow',['../tutorial_game_states.html#complete-title-flow',1,'']]],
  ['folder_108',['&quot;fatal: repository not found&quot; or empty compiler folder',['../getting_started.html#fatal-repository-not-found-or-empty-compiler-folder',1,'']]],
  ['following_20the_20music_20and_20managing_20the_20queue_109',['Following the music and managing the queue',['../tutorial_audio.html#following-the-music-and-managing-the-queue',1,'']]],
  ['following_20the_20player_3a_20the_20camera_110',['Following the player: the camera',['../craft_camera.html',1,'craft']]],
  ['font_111',['Font',['../tools_opensnes_text.html#font',1,'']]],
  ['font_20images_20to_20text_20tiles_112',['font2snes — font images to text tiles',['../tools_font2snes.html',1,'tools']]],
  ['font_20no_20external_20assets_113',['3. Embedded font (no external assets)',['../examples_memory_hirom_demo.html#autotoc_md3-embedded-font-no-external-assets',1,'']]],
  ['font_20or_20calling_20textinit_20with_20the_20screen_20on_114',['🔴 Loading the font or calling &lt;span class=&quot;tt&quot;&gt;textInit&lt;/span&gt; with the screen on',['../tutorial_text.html#autotoc_md-loading-the-font-or-calling-textinit-with-the-screen-on',1,'']]],
  ['font2snes_115',['From font2snes',['../tools_opensnes_text.html#from-font2snes',1,'']]],
  ['font2snes_20—_20font_20images_20to_20text_20tiles_116',['font2snes — font images to text tiles',['../tools_font2snes.html',1,'tools']]],
  ['fonts_20bit_20depth_20and_20palettes_117',['Fonts, bit depth and palettes',['../tutorial_text.html#fonts-bit-depth-and-palettes',1,'']]],
  ['fonts_20for_20the_20text_20module_118',['opensnes-text — bitmap fonts for the text module',['../tools_opensnes_text.html',1,'tools']]],
  ['fonts_20tutorial_119',['Text &amp;amp; Fonts Tutorial',['../tutorial_text.html',1,'index']]],
  ['for_120',['What Mesen2 is still for',['../tutorial_debugging.html#what-mesen2-is-still-for',1,'']]],
  ['for_20a_20512_20kb_20rom_20rom_20size_20is_20a_20knob_20now_20fixed_202026_2009_2024_121',['🟢 The HiROM header claimed 256 KB for a 512 KB ROM; ROM size is a knob now (fixed 2026-09-24)',['../KNOWN_LIMITATIONS.html#autotoc_md-the-hirom-header-claimed-256-kb-for-a-512-kb-rom-rom-size-is-a-knob-now-fixed-2026-09-24',1,'']]],
  ['for_20a_20game_122',['Why &lt;span class=&quot;tt&quot;&gt;ASMSRC&lt;/span&gt; for a Game?',['../examples_games_breakout.html#why-asmsrc-for-a-game',1,'']]],
  ['for_20an_20empty_20port_20fixed_202026_2009_2026_123',['🟢 &lt;span class=&quot;tt&quot;&gt;padIsConnected()&lt;/span&gt; answered 1 for an empty port (fixed 2026-09-26)',['../KNOWN_LIMITATIONS.html#autotoc_md-padisconnected-answered-1-for-an-empty-port-fixed-2026-09-26',1,'']]],
  ['for_20animated_20sprites_124',['Dynamic Sprite -- VRAM Streaming for Animated Sprites',['../examples_sprites_dynamic_sprite.html',1,'examples_sprites']]],
  ['for_20bg_20masking_125',['Window for Color Math (Not for BG Masking)',['../examples_windows_transparent_window.html#window-for-color-math-not-for-bg-masking',1,'']]],
  ['for_20call_126',['Against PVSnesLib, call for call',['../perf.html#perf-libbench',1,'']]],
  ['for_20color_20math_20not_20for_20bg_20masking_127',['Window for Color Math (Not for BG Masking)',['../examples_windows_transparent_window.html#window-for-color-math-not-for-bg-masking',1,'']]],
  ['for_20everything_128',['Use &lt;span class=&quot;tt&quot;&gt;sta.l&lt;/span&gt; / &lt;span class=&quot;tt&quot;&gt;lda.l&lt;/span&gt; for Everything',['../tutorial_sa1.html#use-stal--ldal-for-everything',1,'']]],
  ['for_20fast_20transfers_129',['DMA Registers (for fast transfers)',['../snes_graphics_guide.html#dma-registers-for-fast-transfers',1,'']]],
  ['for_20initial_20setup_130',['Force Blank for Initial Setup',['../examples_sprites_dynamic_sprite.html#force-blank-for-initial-setup',1,'']]],
  ['for_20large_20dma_131',['Force Blank for Large DMA',['../examples_sprites_sprite_sizes.html#force-blank-for-large-dma',1,'']]],
  ['for_20new_20features_132',['Acceptance criteria for new features',['../PHILOSOPHY.html#acceptance-criteria-for-new-features',1,'']]],
  ['for_20no_20contact_20—_20fixed_202026_2009_2020_133',['🟢 &lt;span class=&quot;tt&quot;&gt;objCollidObj&lt;/span&gt; returned garbage for &quot;no contact&quot; — fixed 2026-09-20',['../tutorial_object.html#autotoc_md-objcollidobj-returned-garbage-for-no-contact--fixed-2026-09-20',1,'']]],
  ['for_20oam_20dma_134',['🔴 Channel 7 is reserved for OAM DMA',['../tutorial_hdma.html#autotoc_md-channel-7-is-reserved-for-oam-dma',1,'']]],
  ['for_20seamless_20wrapping_135',['64x32 Tilemap for Seamless Wrapping',['../examples_scrolling_parallax_scroll.html#autotoc_md64x32-tilemap-for-seamless-wrapping',1,'']]],
  ['for_20snes_20compatibility_136',['For SNES Compatibility',['../snes_graphics_guide.html#for-snes-compatibility',1,'']]],
  ['for_20text_137',['VRAM Layout for Text',['../examples_text.html#vram-layout-for-text',1,'']]],
  ['for_20the_20snes_138',['The workflow: design in Tiled, convert for the SNES',['../craft_tiles_to_levels.html#the-workflow-design-in-tiled-convert-for-the-snes',1,'']]],
  ['for_20the_20text_20module_139',['opensnes-text — bitmap fonts for the text module',['../tools_opensnes_text.html',1,'tools']]],
  ['for_20transitions_140',['3. Combining both for transitions',['../examples_transitions_mosaic.html#autotoc_md3-combining-both-for-transitions',1,'']]],
  ['for_20vram_20access_141',['Force Blank for VRAM Access',['../examples_backgrounds_mode1_lz77.html#force-blank-for-vram-access',1,'']]],
  ['for_20which_20register_142',['Which mode for which register',['../hdma_8h.html#which-mode-for-which-register',1,'']]],
  ['for_20x_20≥_20128_143',['🔴 &lt;span class=&quot;tt&quot;&gt;FIX(x)&lt;/span&gt; overflows for &lt;span class=&quot;tt&quot;&gt;|x| ≥ 128&lt;/span&gt;',['../tutorial_math.html#autotoc_md-fixx-overflows-for-x--128',1,'']]],
  ['for_20you_144',['What gameLoopRun will not do for you',['../tutorial_framework.html#what-gamelooprun-will-not-do-for-you',1,'']]],
  ['for_20your_20game_145',['for your game',['../examples_backgrounds_mode2.html#why-it-matters-for-your-game',1,'Why it matters for your game'],['../examples_basics_game_skeleton.html#why-it-matters-for-your-game-1',1,'Why it matters for your game'],['../examples_basics_panel_hud.html#why-it-matters-for-your-game-2',1,'Why it matters for your game'],['../examples_color_palette_cycle.html#why-it-matters-for-your-game-3',1,'Why it matters for your game'],['../examples_color_shadow_tint.html#why-it-matters-for-your-game-4',1,'Why it matters for your game'],['../examples_sprites_sprite_swarm.html#why-it-matters-for-your-game-5',1,'Why it matters for your game']]],
  ['force_20blank_146',['1. Initialize and Stay in Force Blank',['../examples_backgrounds_mode1_lz77.html#autotoc_md1-initialize-and-stay-in-force-blank',1,'']]],
  ['force_20blank_147',['2. Load sprites with force blank',['../examples_sprites_sprite_sizes.html#autotoc_md2-load-sprites-with-force-blank',1,'']]],
  ['force_20blank_20are_20silently_20dropped_148',['🔴 VRAM/CGRAM/OAM writes outside VBlank or force blank are silently dropped',['../tutorial_dma.html#autotoc_md-vramcgramoam-writes-outside-vblank-or-force-blank-are-silently-dropped',1,'']]],
  ['force_20blank_20for_20initial_20setup_149',['Force Blank for Initial Setup',['../examples_sprites_dynamic_sprite.html#force-blank-for-initial-setup',1,'']]],
  ['force_20blank_20for_20large_20dma_150',['Force Blank for Large DMA',['../examples_sprites_sprite_sizes.html#force-blank-for-large-dma',1,'']]],
  ['force_20blank_20for_20vram_20access_151',['Force Blank for VRAM Access',['../examples_backgrounds_mode1_lz77.html#force-blank-for-vram-access',1,'']]],
  ['force_20blank_20vs_20brightness_200_152',['Force Blank vs Brightness 0',['../examples_transitions_fading.html#force-blank-vs-brightness-0',1,'']]],
  ['forced_20blank_153',['These calls belong in setup, under forced blank',['../tutorial_framework.html#these-calls-belong-in-setup-under-forced-blank',1,'']]],
  ['forced_20blank_20—_20do_20not_20do_20it_20yourself_20with_20setbrightness_200_154',['🔴 &lt;span class=&quot;tt&quot;&gt;panelFlush&lt;/span&gt; uploads under forced blank — do not do it yourself with &lt;span class=&quot;tt&quot;&gt;setBrightness(0)&lt;/span&gt;',['../tutorial_panel.html#autotoc_md-panelflush-uploads-under-forced-blank--do-not-do-it-yourself-with-setbrightness0',1,'']]],
  ['forces_20a_20full_20sprite_20refresh_155',['🟡 A screen-edge crossing forces a full sprite refresh',['../tutorial_object.html#autotoc_md-a-screen-edge-crossing-forces-a-full-sprite-refresh',1,'']]],
  ['foreground_20occlusion_20—_20walking_20behind_20things_156',['Foreground occlusion — walking behind things',['../craft_backgrounds.html#foreground-occlusion--walking-behind-things',1,'']]],
  ['format_157',['Format',['../examples_text.html#autotoc_md2bpp-tile-format',1,'2BPP Tile Format'],['../examples_backgrounds_mode1.html#autotoc_md4bpp-tile-format',1,'4bpp Tile Format'],['../snes_sound_guide.html#brr-sample-format',1,'BRR Sample Format'],['../math_8h.html#fixed-point-format',1,'Fixed-Point Format'],['../code_style.html#format',1,'Format'],['../lzss_8h.html#lz77-format',1,'LZ77 Format'],['../hdma_8h.html#table-format',1,'Table Format'],['../examples_backgrounds_mode1.html#tilemap-format',1,'Tilemap Format']]],
  ['format_158',['format',['../examples_mode7_rotate_scale.html#autotoc_md1-mode-7-vram-format',1,'1. Mode 7 VRAM format'],['../tutorial_hdma.html#table-format-1',1,'Table format'],['../tutorial_math.html#the-88-fixed-point-format',1,'The 8.8 fixed-point format'],['../tutorial_mode7.html#the-interleaved-vram-format',1,'The interleaved VRAM format']]],
  ['format_2015_20bit_20bgr_159',['Color Format (15-bit BGR)',['../snes_graphics_guide.html#color-format-15-bit-bgr',1,'']]],
  ['format_20example_160',['Data Format Example',['../snes_graphics_guide.html#data-format-example',1,'']]],
  ['formats_161',['Tile Formats',['../snes_graphics_guide.html#tile-formats',1,'']]],
  ['formatting_20tools_162',['Formatting Tools',['../code_style.html#formatting-tools',1,'']]],
  ['found_163',['found',['../troubleshooting.html#clang-command-not-found-or-cc-command-not-found',1,'&quot;clang: command not found&quot; or &quot;cc: command not found&quot;'],['../troubleshooting.html#wla-65816-command-not-found',1,'&quot;wla-65816: command not found&quot;'],['../troubleshooting.html#empty-compiler-directories-or-cc65816-not-found',1,'Empty &lt;span class=&quot;tt&quot;&gt;compiler/&lt;/span&gt; directories or &quot;cc65816 not found&quot;']]],
  ['found_20and_20fixed_20by_20the_20c_20feature_20runtime_20rom_202026_2009_2013_164',['🟢 Five silent miscompilations found and fixed by the C-feature runtime ROM (2026-09-13)',['../KNOWN_LIMITATIONS.html#autotoc_md-five-silent-miscompilations-found-and-fixed-by-the-c-feature-runtime-rom-2026-09-13',1,'']]],
  ['found_20or_20cc_3a_20command_20not_20found_165',['&quot;clang: command not found&quot; or &quot;cc: command not found&quot;',['../troubleshooting.html#clang-command-not-found-or-cc-command-not-found',1,'']]],
  ['found_20or_20empty_20compiler_20folder_166',['&quot;fatal: repository not found&quot; or empty compiler folder',['../getting_started.html#fatal-repository-not-found-or-empty-compiler-folder',1,'']]],
  ['found_3a_20make_167',['&quot;command not found: make&quot;',['../getting_started.html#command-not-found-make',1,'']]],
  ['four_20bytes_168',['5. Two Colors, Four Bytes',['../examples_fundamentals_text_glyphs.html#autotoc_md5-two-colors-four-bytes',1,'']]],
  ['four_20channel_20registers_169',['The four channel registers',['../tutorial_hdma.html#the-four-channel-registers',1,'']]],
  ['four_20corners_170',['Checking All Four Corners',['../tutorial_collision.html#checking-all-four-corners',1,'']]],
  ['fractional_20precision_171',['🔴 &lt;span class=&quot;tt&quot;&gt;fixMul&lt;/span&gt; truncates fractional precision',['../tutorial_math.html#autotoc_md-fixmul-truncates-fractional-precision',1,'']]],
  ['frame_172',['Mode Switching Mid-Frame',['../examples_mode7_perspective.html#mode-switching-mid-frame',1,'']]],
  ['frame_173',['frame',['../tutorial_dma.html#autotoc_md-vblank-dma-budget-is-4-kb-per-frame',1,'🔴 VBlank DMA budget is ~4 KB per frame'],['../KNOWN_LIMITATIONS.html#autotoc_md-vblank-dma-budget-is-4-kb-per-frame-1',1,'🔴 VBlank DMA budget is ~4 KB per frame'],['../examples_sprites_dynamic_sprite.html#autotoc_md3-draw-and-upload-every-frame',1,'3. Draw and upload every frame'],['../examples_mode7_rotate_scale.html#autotoc_md3-update-the-matrix-every-frame',1,'3. Update the matrix every frame'],['../tutorial_profiling.html#the-unit-master-cycles-per-frame',1,'The unit: master cycles per frame']]],
  ['frame_20—_20hitstop_174',['Freeze the frame — hitstop',['../craft_game_feel.html#freeze-the-frame--hitstop',1,'']]],
  ['frame_20based_20animation_175',['Frame-Based Animation',['../tutorial_animation.html#frame-based-animation',1,'']]],
  ['frame_20based_20animation_176',['Frame-based Animation',['../tutorial_sprites.html#frame-based-animation-1',1,'']]],
  ['frame_20budget_177',['The frame budget',['../craft_frame_budget.html',1,'craft']]],
  ['frame_20costs_20of_20the_20library_178',['Measured frame costs of the library',['../perf.html',1,'index']]],
  ['frame_20dma_20in_20the_20main_20loop_179',['Per-frame DMA in the main loop',['../tutorial_dma.html#per-frame-dma-in-the-main-loop',1,'']]],
  ['frame_20goes_180',['Profiling: measuring where the frame goes',['../tutorial_profiling.html',1,'index']]],
  ['frame_20ids_181',['4. Animate by changing frame IDs',['../examples_sprites_dynamic_sprite.html#autotoc_md4-animate-by-changing-frame-ids',1,'']]],
  ['frame_20order_182',['The exact per-frame order',['../tutorial_framework.html#the-exact-per-frame-order',1,'']]],
  ['frame_20the_20engine_20expects_183',['The frame the engine expects',['../tutorial_object.html#the-frame-the-engine-expects',1,'']]],
  ['frame_20timing_184',['Frame Timing',['../tutorial_animation.html#frame-timing',1,'']]],
  ['frame_5fcount_185',['VBlank and frame_count',['../examples_basics_timer.html#vblank-and-frame_count',1,'']]],
  ['framebuffer_20on_20visible_20lines_20fixed_202026_2009_2029_186',['🟢 Super FX: &lt;span class=&quot;tt&quot;&gt;gsuDmaFullFrame()&lt;/span&gt; wrote a third of the framebuffer on visible lines (fixed 2026-09-29)',['../KNOWN_LIMITATIONS.html#autotoc_md-super-fx-gsudmafullframe-wrote-a-third-of-the-framebuffer-on-visible-lines-fixed-2026-09-29',1,'']]],
  ['frames_187',['&lt;span class=&quot;tt&quot;&gt;luna frames&lt;/span&gt;',['../tools_luna.html#luna-frames',1,'']]],
  ['frames_3a_20a_20double_20buffer_20the_20nmi_20moves_188',['Presenting Frames: a Double Buffer the NMI Moves',['../tutorial_superfx.html#presenting-frames-a-double-buffer-the-nmi-moves',1,'']]],
  ['framesize_20cliff_20—_20resolved_20via_20asm_20rewrite_202026_2003_2003_189',['🟢 &lt;span class=&quot;tt&quot;&gt;oamSet()&lt;/span&gt; framesize cliff — RESOLVED via ASM rewrite (2026-03-03)',['../KNOWN_LIMITATIONS.html#autotoc_md-oamset-framesize-cliff--resolved-via-asm-rewrite-2026-03-03',1,'']]],
  ['framework_20gets_20in_20the_20way_190',['When the framework gets in the way',['../tutorial_framework.html#when-the-framework-gets-in-the-way',1,'']]],
  ['framework_20instead_20of_20a_20switch_191',['Why a framework instead of a switch',['../examples_basics_scene_stack.html#why-a-framework-instead-of-a-switch',1,'']]],
  ['framework_20opt_20ins_192',['Framework opt-ins',['../index.html#framework-opt-ins',1,'']]],
  ['framework_20tutorial_193',['The Opt-In Framework Tutorial',['../tutorial_framework.html',1,'index']]],
  ['free_20asset_20sources_20cc0_20public_20domain_194',['Free Asset Sources (CC0/Public Domain)',['../snes_graphics_guide.html#free-asset-sources-cc0public-domain',1,'']]],
  ['free_20depth_195',['7. Drop Shadows (Free Depth)',['../examples_games_breakout.html#autotoc_md7-drop-shadows-free-depth',1,'']]],
  ['free_20running_20counter_196',['Pattern 2: Free-Running Counter',['../tutorial_sa1.html#pattern-2-free-running-counter',1,'']]],
  ['freeze_197',['What 1.0 will freeze',['../stability.html',1,'']]],
  ['freeze_20the_20frame_20—_20hitstop_198',['Freeze the frame — hitstop',['../craft_game_feel.html#freeze-the-frame--hitstop',1,'']]],
  ['frequencies_199',['Noise Frequencies',['../snes_sound_guide.html#noise-frequencies',1,'']]],
  ['frequently_20asked_20questions_200',['Frequently asked questions',['../faq.html',1,'index']]],
  ['friction_20and_20no_20way_20to_20get_20any_20—_20opt_20in_20since_202026_2009_2019_201',['🟢 &lt;span class=&quot;tt&quot;&gt;objCollidMap1D&lt;/span&gt; had no friction, and no way to get any — opt-in since 2026-09-19',['../tutorial_object.html#autotoc_md-objcollidmap1d-had-no-friction-and-no-way-to-get-any--opt-in-since-2026-09-19',1,'']]],
  ['from_202',['from',['../tutorial_text.html#mistakes-the-module-will-not-save-you-from',1,'Mistakes the module will not save you from'],['../examples_backgrounds_mode0.html#ported-from',1,'Ported from'],['../examples_backgrounds_mode3.html#ported-from-1',1,'Ported from'],['../tools_opensnes_rom.html#where-the-checks-came-from',1,'Where the checks came from']]],
  ['from_200_2048_20to_200_2049_203',['Upgrading from 0.48 to 0.49',['../upgrading.html',1,'']]],
  ['from_20a_204bpp_20background_204',['HiColor — 1792 colors from a 4bpp background',['../examples_color_hicolor_1792.html',1,'examples_color']]],
  ['from_20a_20tilemap_20platformer_20pattern_205',['Tile Properties from a Tilemap (Platformer Pattern)',['../tutorial_collision.html#tile-properties-from-a-tilemap-platformer-pattern',1,'']]],
  ['from_20bank_20—_20fixed_202026_2009_2023_206',['🟢 The collision routines read the map from bank &lt;span class=&quot;tt&quot;&gt;$00&lt;/span&gt; — fixed 2026-09-23',['../tutorial_object.html#autotoc_md-the-collision-routines-read-the-map-from-bank-00--fixed-2026-09-23',1,'']]],
  ['from_20bank_20_2400_20whatever_20bank_20it_20was_20in_20fixed_202026_2009_2023_207',['🟢 The object engine read the map from bank $00 whatever bank it was in (fixed 2026-09-23)',['../KNOWN_LIMITATIONS.html#autotoc_md-the-object-engine-read-the-map-from-bank-00-whatever-bank-it-was-in-fixed-2026-09-23',1,'']]],
  ['from_20bg3_208',['mode2 — offset-per-tile: per-column scroll from BG3',['../examples_backgrounds_mode2.html',1,'examples_backgrounds']]],
  ['from_20c_209',['from C',['../tutorial_sa1.html#autotoc_md3-initialize-from-c',1,'3. Initialize from C'],['../tutorial_superfx.html#autotoc_md4-launch-from-c',1,'4. Launch from C'],['../examples_audio_soundboard.html',1,'soundboard — the audio v2 engine, driven entirely from C']]],
  ['from_20font2snes_210',['From font2snes',['../tools_opensnes_text.html#from-font2snes',1,'']]],
  ['from_20gfx4snes_211',['From gfx4snes',['../tools_opensnes_tileset.html#from-gfx4snes',1,'']]],
  ['from_20gfx4snes_20and_20aseprite2snes_212',['From gfx4snes and aseprite2snes',['../tools_opensnes_sprite.html#from-gfx4snes-and-aseprite2snes',1,'']]],
  ['from_20inside_3a_213',['Profiling from inside: &lt;span class=&quot;tt&quot;&gt;&amp;lt;snes/profile.h&amp;gt;&lt;/span&gt;',['../tutorial_profiling.html#profiling-from-inside-snesprofileh',1,'']]],
  ['from_20map_20data_214',['3. Load Objects from Map Data',['../examples_games_mapandobjects.html#autotoc_md3-load-objects-from-map-data',1,'']]],
  ['from_20map_20data_215',['Spawning from map data',['../tutorial_object.html#spawning-from-map-data',1,'']]],
  ['from_20motion_216',['Parallax — depth from motion',['../craft_backgrounds.html#parallax--depth-from-motion',1,'']]],
  ['from_20outside_3a_20luna_20profile_217',['Profiling from outside: luna profile',['../tutorial_profiling.html#profiling-from-outside-luna-profile',1,'']]],
  ['from_20palplan_20and_20img2snes_218',['From palplan and img2snes',['../tools_opensnes_palette.html#from-palplan-and-img2snes',1,'']]],
  ['from_20pure_20c_219',['The audio module (v2) — samples and effects from pure C',['../tutorial_audio.html#the-audio-module-v2--samples-and-effects-from-pure-c',1,'']]],
  ['from_20pvsneslib_220',['Migrating from PVSnesLib',['../migrating_pvsneslib.html',1,'index']]],
  ['from_20smconv_221',['From smconv',['../tools_opensnes_music.html#from-smconv',1,'']]],
  ['from_20sram_222',['3. Load from SRAM',['../examples_memory_save_game.html#autotoc_md3-load-from-sram',1,'']]],
  ['from_20the_20hdma_20module_223',['3. The same ripple from the &lt;span class=&quot;tt&quot;&gt;hdma&lt;/span&gt; module',['../examples_hdma_hdma_wave.html#autotoc_md3-the-same-ripple-from-the-hdma-module',1,'']]],
  ['from_20the_20original_20a_20true_20story_224',['Why the envelope differs from the original (a true story)',['../examples_audio_pitch_mod.html#why-the-envelope-differs-from-the-original-a-true-story',1,'']]],
  ['from_20tiles_20to_20levels_225',['From tiles to levels',['../craft_tiles_to_levels.html',1,'craft']]],
  ['from_20wav_226',['SFX from WAV',['../examples_audio_sfx_from_wav.html',1,'examples_audio']]],
  ['from_20wav_20wav2brr_227',['One-shot samples from WAV (wav2brr)',['../tutorial_audio.html#audio_wav2brr',1,'']]],
  ['from_20wav2brr_228',['From wav2brr',['../tools_opensnes_sample.html#from-wav2brr',1,'']]],
  ['from_20your_20genre_229',['Choose a background mode from your genre',['../craft_planning.html#choose-a-background-mode-from-your-genre',1,'']]],
  ['front_230',['front',['../tools_font2snes.html#gotchas-worth-knowing-up-front',1,'Gotchas worth knowing up front'],['../tools_gfx4snes.html#gotchas-worth-knowing-up-front-1',1,'Gotchas worth knowing up front'],['../tools_img2snes.html#gotchas-worth-knowing-up-front-2',1,'Gotchas worth knowing up front'],['../tools_palplan.html#gotchas-worth-knowing-up-front-3',1,'Gotchas worth knowing up front'],['../tools_smconv.html#gotchas-worth-knowing-up-front-4',1,'Gotchas worth knowing up front'],['../tools_tmx2snes.html#gotchas-worth-knowing-up-front-5',1,'Gotchas worth knowing up front'],['../tools_wav2brr.html#gotchas-worth-knowing-up-front-6',1,'Gotchas worth knowing up front']]],
  ['frozen_231',['What is not frozen',['../stability.html#what-is-not-frozen',1,'']]],
  ['full_232',['Fade In (Black to Full)',['../examples_transitions_fading.html#fade-in-black-to-full',1,'']]],
  ['full_233',['🟡 &lt;span class=&quot;tt&quot;&gt;objNew&lt;/span&gt; leaves &lt;span class=&quot;tt&quot;&gt;objGetCurrentId()&lt;/span&gt; stale when the pool is full',['../tutorial_object.html#autotoc_md-objnew-leaves-objgetcurrentid-stale-when-the-pool-is-full',1,'']]],
  ['full_20matrix_20per_20scanline_234',['Mode 7 rotating perspective — the full matrix, per scanline',['../examples_mode7_perspective_rotate.html',1,'examples_mode7']]],
  ['full_20mode_207_20matrix_20per_20line_20—_20examples_20mode7_20perspective_5frotate_235',['Full Mode 7 matrix per line — &lt;span class=&quot;tt&quot;&gt;examples/mode7/perspective_rotate&lt;/span&gt;',['../tutorial_hdma.html#full-mode-7-matrix-per-line--examplesmode7perspective_rotate',1,'']]],
  ['full_20results_236',['Full Results',['../BENCHMARK.html#full-results',1,'']]],
  ['full_20screen_20pictures_20and_20their_20tables_237',['opensnes-image — full-screen pictures and their tables',['../tools_opensnes_image.html',1,'tools']]],
  ['full_20sprite_20refresh_238',['🟡 A screen-edge crossing forces a full sprite refresh',['../tutorial_object.html#autotoc_md-a-screen-edge-crossing-forces-a-full-sprite-refresh',1,'']]],
  ['full_20to_20black_239',['Fade Out (Full to Black)',['../examples_transitions_fading.html#fade-out-full-to-black',1,'']]],
  ['function_240',['function',['../perf.html#per-function',1,'Per function'],['../tutorial_debugging.html#recipe-3--break-at-a-function',1,'Recipe 3 — Break at a function']]],
  ['function_20args_20left_20to_20right_241',['🟠 cc65816 pushes function args &lt;b&gt;LEFT-TO-RIGHT&lt;/b&gt;',['../KNOWN_LIMITATIONS.html#autotoc_md-cc65816-pushes-function-args-left-to-right',1,'']]],
  ['function_20documentation_242',['Function Documentation',['../code_style.html#function-documentation',1,'']]],
  ['function_20engine_20resolved_20size_243',['One Draw Function, Engine-Resolved Size',['../tutorial_animation.html#one-draw-function-engine-resolved-size',1,'']]],
  ['function_20returning_20long_20propagates_20the_20high_20half_20fixed_202026_2005_2021_244',['🟢 C function returning &lt;span class=&quot;tt&quot;&gt;long&lt;/span&gt; propagates the high half (fixed 2026-05-21)',['../KNOWN_LIMITATIONS.html#autotoc_md-c-function-returning-long-propagates-the-high-half-fixed-2026-05-21',1,'']]],
  ['functions_245',['Using OpenSNES Sprite Functions',['../tutorial_sprites.html#using-opensnes-sprite-functions',1,'']]],
  ['functions_20are_20refused_246',['🟡 Variadic functions are refused',['../KNOWN_LIMITATIONS.html#autotoc_md-variadic-functions-are-refused',1,'']]],
  ['functions_20same_20behaviour_247',['2. Renamed functions (same behaviour)',['../upgrading.html#autotoc_md2-renamed-functions-same-behaviour',1,'']]],
  ['fundamentals_248',['Fundamentals',['../examples_fundamentals.html',1,'Fundamentals'],['../examples_by_category.html#fundamentals',1,'Fundamentals'],['../examples.html#level-2----graphics-fundamentals',1,'Level 2 &amp;ndash; Graphics Fundamentals']]],
  ['fundamentals_3a_20how_20a_20glyph_20is_20drawn_249',['Fundamentals: how a glyph is drawn',['../examples_fundamentals_text_glyphs.html',1,'examples_fundamentals']]],
  ['further_250',['Further',['../examples_fundamentals_text_glyphs.html#go-further',1,'Go Further'],['../examples_games_breakout.html#go-further-1',1,'Go Further'],['../examples_games_likemario.html#go-further-2',1,'Go Further'],['../examples_hdma_hdma_wave.html#go-further-3',1,'Go Further'],['../examples_scrolling_continuous_scroll.html#go-further-4',1,'Go Further'],['../examples_backgrounds_mode1_bg3_priority.html#going-further',1,'Going Further'],['../examples_hdma_gradient_colors.html#going-further-1',1,'Going Further'],['../examples_memory_hirom_demo.html#going-further-2',1,'Going Further'],['../examples_memory_save_game.html#going-further-3',1,'Going Further'],['../examples_mode7_dsp1_ground.html#going-further-4',1,'Going Further'],['../examples_mode7_perspective.html#going-further-5',1,'Going Further'],['../examples_mode7_rotate_scale.html#going-further-6',1,'Going Further'],['../examples_scrolling_parallax_scroll.html#going-further-7',1,'Going Further'],['../examples_sprites_animated_sprite.html#going-further-8',1,'Going Further'],['../examples_sprites_dynamic_sprite.html#going-further-9',1,'Going Further'],['../examples_sprites_simple_sprite.html#going-further-10',1,'Going Further'],['../examples_sprites_sprite_sizes.html#going-further-11',1,'Going Further'],['../examples_transitions_mosaic.html#going-further-12',1,'Going Further'],['../examples_windows_transparent_window.html#going-further-13',1,'Going Further'],['../examples_windows_window.html#going-further-14',1,'Going Further']]],
  ['further_20reading_251',['Further Reading',['../tutorial_sa1.html#further-reading',1,'Further Reading'],['../tutorial_superfx.html#further-reading-1',1,'Further Reading'],['../memory_map.html#further-reading-2',1,'Further Reading'],['../hardware_overview.html#further-reading-3',1,'Further Reading'],['../registers.html#further-reading-4',1,'Further Reading']]],
  ['further_3a_203840_20colours_20by_20splitting_20the_20channels_252',['Further: 3840 colours by splitting the channels',['../examples_color_hicolor_1792.html#further-3840-colours-by-splitting-the-channels',1,'']]],
  ['further_3a_20mode_205_20without_20interlace_20512_20x_20256_253',['Further: Mode 5 without interlace (512 x 256)',['../examples_backgrounds_mode5_hires.html#further-mode-5-without-interlace-512-x-256',1,'']]],
  ['further_3a_20the_209_20bit_20backdrop_20two_20channels_20one_20visual_254',['Further: the &quot;9-bit&quot; backdrop (two channels, one visual)',['../examples_hdma_gradient_colors.html#further-the-9-bit-backdrop-two-channels-one-visual',1,'']]],
  ['fx_20game_20skeleton_255',['Super FX Game Skeleton',['../examples_chips_superfx_game_skeleton.html',1,'examples_chips']]],
  ['fx_20save_256',['Super FX Save',['../examples_chips_superfx_save.html',1,'examples_chips']]],
  ['fx_3a_20gsudmafullframe_20wrote_20a_20third_20of_20the_20framebuffer_20on_20visible_20lines_20fixed_202026_2009_2029_257',['🟢 Super FX: &lt;span class=&quot;tt&quot;&gt;gsuDmaFullFrame()&lt;/span&gt; wrote a third of the framebuffer on visible lines (fixed 2026-09-29)',['../KNOWN_LIMITATIONS.html#autotoc_md-super-fx-gsudmafullframe-wrote-a-third-of-the-framebuffer-on-visible-lines-fixed-2026-09-29',1,'']]],
  ['fx_3a_20vblanks_20were_20lost_20during_20every_20gsu_20job_20fixed_202026_2009_2025_258',['🟢 Super FX: VBlanks were lost during every GSU job (fixed 2026-09-25)',['../KNOWN_LIMITATIONS.html#autotoc_md-super-fx-vblanks-were-lost-during-every-gsu-job-fixed-2026-09-25',1,'']]]
];
