var searchData=
[
  ['f_20zero_20perspective_20via_20hdma_20—_20examples_20mode7_20perspective_0',['F-Zero perspective via HDMA — &lt;span class=&quot;tt&quot;&gt;examples/mode7/perspective&lt;/span&gt;',['../tutorial_mode7.html#autotoc_md296',1,'']]],
  ['f_20zero_20style_20mini_20game_1',['mode7_racing — an F-Zero-style mini game',['../examples_games_mode7_racing.html',1,'examples_games']]],
  ['fade_2',['Fade',['../examples_transitions_fading.html#autotoc_md1744',1,'Alternative: Palette Fade'],['../examples_transitions_fading.html#autotoc_md1736',1,'Exercise 1: Smooth Fade'],['../examples_transitions_fading.html#autotoc_md1738',1,'Exercise 3: Color Fade'],['../tutorial_game_states.html#autotoc_md197',1,'Game Over with Fade']]],
  ['fade_20during_20gameplay_3',['Fade During Gameplay',['../examples_transitions_fading.html#autotoc_md1743',1,'']]],
  ['fade_20effect_20brightness_4',['1. Fade effect (brightness)',['../examples_transitions_mosaic.html#autotoc_md1752',1,'']]],
  ['fade_20implementation_5',['Basic Fade Implementation',['../examples_transitions_fading.html#autotoc_md1722',1,'']]],
  ['fade_20in_6',['Fade Out / Fade In',['../tutorial_game_states.html#autotoc_md188',1,'']]],
  ['fade_20in_20black_20to_20full_7',['Fade In (Black to Full)',['../examples_transitions_fading.html#autotoc_md1723',1,'']]],
  ['fade_20out_20fade_20in_8',['Fade Out / Fade In',['../tutorial_game_states.html#autotoc_md188',1,'']]],
  ['fade_20out_20full_20to_20black_9',['Fade Out (Full to Black)',['../examples_transitions_fading.html#autotoc_md1724',1,'']]],
  ['fade_20speeds_10',['Fade Speeds',['../examples_transitions_fading.html#autotoc_md1726',1,'']]],
  ['fade_20to_20black_20fade_20to_20white_11',['Fade-to-black / fade-to-white',['../tutorial_colormath.html#autotoc_md141',1,'']]],
  ['fade_20to_20white_12',['Fade-to-black / fade-to-white',['../tutorial_colormath.html#autotoc_md141',1,'']]],
  ['fades_20and_20dissolves_13',['Punctuate scene changes — fades and dissolves',['../craft_game_feel.html#autotoc_md465',1,'']]],
  ['fading_20example_14',['Fading Example',['../examples_transitions_fading.html',1,'examples_transitions']]],
  ['fails_20with_20library_20not_20built_15',['Build fails with &quot;Library not built&quot;',['../getting_started.html#autotoc_md557',1,'']]],
  ['fails_20with_20smconv_20error_16',['Build fails with smconv error',['../examples_audio_snesmod_music.html#autotoc_md918',1,'']]],
  ['fails_20with_20unhandled_20op_20or_20assembly_20errors_17',['Build fails with &quot;unhandled op&quot; or assembly errors',['../getting_started.html#autotoc_md559',1,'']]],
  ['fails_20with_20unhandled_20op_3a_20xxx_18',['Build fails with &quot;unhandled op: XXX&quot;',['../troubleshooting.html#autotoc_md721',1,'']]],
  ['far_20fewer_20per_20line_19',['3. OAM — 128 sprites, but far fewer per line',['../craft_planning.html#autotoc_md473',1,'']]],
  ['fast_20transfers_20',['DMA Registers (for fast transfers)',['../snes_graphics_guide.html#autotoc_md666',1,'']]],
  ['fatal_3a_20repository_20not_20found_20or_20empty_20compiler_20folder_21',['&quot;fatal: repository not found&quot; or empty compiler folder',['../getting_started.html#autotoc_md556',1,'']]],
  ['features_22',['Features',['../audio_8h.html#autotoc_md14',1,'Features'],['../examples_games_tetris.html#autotoc_md1291',1,'Features'],['../examples_audio_snesmod_music.html#autotoc_md888',1,'Key Features'],['../contributing.html#autotoc_md1808',1,'Suggesting Features']]],
  ['feedback_23',['4. Interactive feedback',['../examples_memory_hirom_demo.html#autotoc_md1479',1,'']]],
  ['feel_20good_24',['Stage 4 — &quot;Can I make it feel good?&quot;',['../learning_path.html#autotoc_md566',1,'']]],
  ['feel_3a_20juice_20on_20real_20hardware_25',['Game feel: juice on real hardware',['../craft_game_feel.html',1,'craft']]],
  ['few_20seconds_26',['ROM runs but crashes after a few seconds',['../troubleshooting.html#autotoc_md725',1,'']]],
  ['fewer_20per_20line_27',['3. OAM — 128 sprites, but far fewer per line',['../craft_planning.html#autotoc_md473',1,'']]],
  ['fidelity_20to_20the_20original_20measured_20not_20assumed_28',['Fidelity to the original measured not assumed',['../examples_hdma_hdma_indirect_gradient.html#autotoc_md1313',1,'Fidelity to the original (measured, not assumed)'],['../examples_hdma_hdma_wave_table.html#autotoc_md1340',1,'Fidelity to the original (measured, not assumed)']]],
  ['fidelity_20vs_20the_20original_29',['fidelity vs the original',['../examples_audio_speech_synth.html#autotoc_md950',1,'Register fidelity vs the original'],['../examples_backgrounds_mode5_hires.html#autotoc_md1039',1,'Register fidelity vs the original'],['../examples_color_gradient_9bit.html#autotoc_md1136',1,'Register fidelity vs the original'],['../examples_color_hicolor_1792.html#autotoc_md1140',1,'Register fidelity vs the original'],['../examples_mode7_perspective_rotate.html#autotoc_md1524',1,'Register fidelity vs the original'],['../examples_windows_window_multi_hdma.html#autotoc_md1792',1,'Register fidelity vs the original']]],
  ['file_20organization_30',['File Organization',['../code_style.html#autotoc_md619',1,'']]],
  ['files_31',['Files',['../examples_audio_snesmod_music.html#autotoc_md904',1,'Files'],['../examples_audio_snesmod_sfx.html#autotoc_md944',1,'Files'],['../examples_backgrounds_mode1.html#autotoc_md980',1,'Files'],['../examples_basics_collision_demo.html#autotoc_md1061',1,'Files'],['../examples_color_transparency.html#autotoc_md1174',1,'Files'],['../examples_fundamentals_text_glyphs.html#autotoc_md1201',1,'Files'],['../examples_games_breakout.html#autotoc_md1228',1,'Files'],['../examples_games_likemario.html#autotoc_md1254',1,'Files'],['../examples_hdma_hdma_wave.html#autotoc_md1339',1,'Files'],['../examples_input_superscope.html#autotoc_md1388',1,'Files'],['../examples_input_two_players.html#autotoc_md1416',1,'Files'],['../examples_scrolling_continuous_scroll.html#autotoc_md1578',1,'Files'],['../examples_transitions_fading.html#autotoc_md1733',1,'Files'],['../examples_audio_snesmod_music.html#autotoc_md900',1,'Generated Files'],['../examples_chips_superfx_3d.html#autotoc_md1125',1,'Per-Example Files']]],
  ['filter_20coefficients_20coef_200f_207f_32',['FIR Filter Coefficients (COEF 0F-7F)',['../snes_sound_guide.html#autotoc_md695',1,'']]],
  ['filters_33',['Filters',['../snes_sound_guide.html#autotoc_md683',1,'']]],
  ['finish_34',['Scope a first game you can finish',['../craft_planning.html#autotoc_md476',1,'']]],
  ['finish_20and_20ship_35',['Stage 6 — &quot;Can I finish and ship?&quot;',['../learning_path.html#autotoc_md568',1,'']]],
  ['fir_20filter_20coefficients_20coef_200f_207f_36',['FIR Filter Coefficients (COEF 0F-7F)',['../snes_sound_guide.html#autotoc_md695',1,'']]],
  ['fires_20before_20the_20user_20callback_20in_20the_20nmi_20handler_37',['🟡 HDMA fires before the user callback in the NMI handler',['../tutorial_hdma.html#autotoc_md234',1,'']]],
  ['firmware_20requirement_38',['Firmware requirement',['../examples_chips_dsp1_cube.html#autotoc_md1108',1,'']]],
  ['first_20boot_20are_20undefined_39',['🔴 SRAM contents on first boot are undefined',['../tutorial_sram.html#autotoc_md392',1,'']]],
  ['first_20game_20you_20can_20finish_40',['Scope a first game you can finish',['../craft_planning.html#autotoc_md476',1,'']]],
  ['first_20issues_41',['Good First Issues',['../contributing.html#autotoc_md1823',1,'']]],
  ['first_20oam_20sprite_42',['Simple Sprite -- Your First OAM Sprite',['../examples_sprites_simple_sprite.html',1,'examples_sprites']]],
  ['first_20rom_43',['A4. Run Your First ROM',['../getting_started.html#autotoc_md540',1,'']]],
  ['first_20steps_44',['Level 1 &amp;ndash; First Steps',['../examples.html#autotoc_md1549',1,'']]],
  ['fit_20with_20the_20rest_20of_20the_20docs_45',['Where they fit with the rest of the docs',['../tools.html#autotoc_md518',1,'']]],
  ['fits_46',['fits',['../tools_aseprite2snes.html#autotoc_md488',1,'Where it fits'],['../tools_font2snes.html#autotoc_md497',1,'Where it fits'],['../tools_img2snes.html#autotoc_md508',1,'Where it fits']]],
  ['fix_20s5_202_47',['Bullet despawn fix (S5.2)',['../examples_games_shmup_1942.html#autotoc_md1284',1,'']]],
  ['fix_20x_20overflows_20for_20x_20≥_20128_48',['🔴 &lt;span class=&quot;tt&quot;&gt;FIX(x)&lt;/span&gt; overflows for &lt;span class=&quot;tt&quot;&gt;|x| ≥ 128&lt;/span&gt;',['../tutorial_math.html#autotoc_md277',1,'']]],
  ['fix32_5forbit_49',['fix32_orbit',['../examples_basics_fix32_orbit.html',1,'examples_basics']]],
  ['fixdiv_20returns_200_20on_20divide_20by_20zero_50',['🟠 &lt;span class=&quot;tt&quot;&gt;fixDiv&lt;/span&gt; returns 0 on divide-by-zero',['../tutorial_math.html#autotoc_md279',1,'']]],
  ['fixed_20point_20arithmetic_51',['Fixed-point arithmetic',['../tutorial_math.html#autotoc_md266',1,'']]],
  ['fixed_20point_20format_52',['Fixed-Point Format',['../math_8h.html#autotoc_md45',1,'']]],
  ['fixed_20point_20format_53',['The 8.8 fixed-point format',['../tutorial_math.html#autotoc_md264',1,'']]],
  ['fixed_20point_20math_20tutorial_54',['Fixed-Point Math Tutorial',['../tutorial_math.html',1,'index']]],
  ['fixed_20point_20on_20the_20snes_55',['Why fixed-point on the SNES',['../tutorial_math.html#autotoc_md263',1,'']]],
  ['fixed_20point_20physics_56',['4. Fixed-Point Physics',['../examples_games_likemario.html#autotoc_md1238',1,'']]],
  ['fixed_20point_20scale_57',['8.8 Fixed-Point Scale',['../examples_mode7_rotate_scale.html#autotoc_md1544',1,'']]],
  ['fixmul_20truncates_20fractional_20precision_58',['🔴 &lt;span class=&quot;tt&quot;&gt;fixMul&lt;/span&gt; truncates fractional precision',['../tutorial_math.html#autotoc_md278',1,'']]],
  ['flag_20sync_20producer_20consumer_59',['Pattern 1: Flag Sync (Producer/Consumer)',['../tutorial_sa1.html#autotoc_md338',1,'']]],
  ['flags_60',['3. Scroll Updates via bgSetScroll Dirty Flags',['../examples_scrolling_continuous_scroll.html#autotoc_md1565',1,'']]],
  ['flags_20behind_20the_20makefile_61',['The flags behind the Makefile',['../tools_smconv.html#autotoc_md521',1,'']]],
  ['flags_20that_20decide_20everything_3a_20u_20and_20s_62',['The two flags that decide everything: &lt;span class=&quot;tt&quot;&gt;-u&lt;/span&gt; and &lt;span class=&quot;tt&quot;&gt;-s&lt;/span&gt;',['../tools_gfx4snes.html#autotoc_md499',1,'']]],
  ['flags_20you_20will_20actually_20use_63',['flags you will actually use',['../tools_font2snes.html#autotoc_md494',1,'The flags you will actually use'],['../tools_gfx4snes.html#autotoc_md500',1,'The flags you will actually use'],['../tools_img2snes.html#autotoc_md505',1,'The flags you will actually use'],['../tools_palplan.html#autotoc_md511',1,'The flags you will actually use'],['../tools_wav2brr.html#autotoc_md530',1,'The flags you will actually use']]],
  ['flash_64',['Quick Flash',['../examples_transitions_fading.html#autotoc_md1727',1,'']]],
  ['flash_20—_20color_20math_20not_20palette_20edits_65',['Hit flash — color math, not palette edits',['../craft_game_feel.html#autotoc_md463',1,'']]],
  ['flicker_20page_20flip_20desync_66',['Recipe 6 — Temporal artefacts (flicker, page-flip desync)',['../tutorial_debugging.html#autotoc_md163',1,'']]],
  ['flip_67',['Exercise 3: Tile Flip',['../examples_backgrounds_mode1.html#autotoc_md985',1,'']]],
  ['flip_20desync_68',['Recipe 6 — Temporal artefacts (flicker, page-flip desync)',['../tutorial_debugging.html#autotoc_md163',1,'']]],
  ['flow_69',['Complete Title Flow',['../tutorial_game_states.html#autotoc_md191',1,'']]],
  ['folder_70',['&quot;fatal: repository not found&quot; or empty compiler folder',['../getting_started.html#autotoc_md556',1,'']]],
  ['following_20the_20player_3a_20the_20camera_71',['Following the player: the camera',['../craft_camera.html',1,'craft']]],
  ['font_20images_20to_20text_20tiles_72',['font2snes — font images to text tiles',['../tools_font2snes.html',1,'tools']]],
  ['font_20no_20external_20assets_73',['3. Embedded font (no external assets)',['../examples_memory_hirom_demo.html#autotoc_md1478',1,'']]],
  ['font2snes_20—_20font_20images_20to_20text_20tiles_74',['font2snes — font images to text tiles',['../tools_font2snes.html',1,'tools']]],
  ['for_75',['What Mesen2 is still for',['../tutorial_debugging.html#autotoc_md164',1,'']]],
  ['for_20a_20game_76',['Why &lt;span class=&quot;tt&quot;&gt;ASMSRC&lt;/span&gt; for a Game?',['../examples_games_breakout.html#autotoc_md1223',1,'']]],
  ['for_20animated_20sprites_77',['Dynamic Sprite -- VRAM Streaming for Animated Sprites',['../examples_sprites_dynamic_sprite.html',1,'examples_sprites']]],
  ['for_20bg_20masking_78',['Window for Color Math (Not for BG Masking)',['../examples_windows_transparent_window.html#autotoc_md1769',1,'']]],
  ['for_20color_20math_20not_20for_20bg_20masking_79',['Window for Color Math (Not for BG Masking)',['../examples_windows_transparent_window.html#autotoc_md1769',1,'']]],
  ['for_20everything_80',['Use &lt;span class=&quot;tt&quot;&gt;sta.l&lt;/span&gt; / &lt;span class=&quot;tt&quot;&gt;lda.l&lt;/span&gt; for Everything',['../tutorial_sa1.html#autotoc_md342',1,'']]],
  ['for_20fast_20transfers_81',['DMA Registers (for fast transfers)',['../snes_graphics_guide.html#autotoc_md666',1,'']]],
  ['for_20initial_20setup_82',['Force Blank for Initial Setup',['../examples_sprites_dynamic_sprite.html#autotoc_md1645',1,'']]],
  ['for_20large_20dma_83',['Force Blank for Large DMA',['../examples_sprites_sprite_sizes.html#autotoc_md1686',1,'']]],
  ['for_20oam_20dma_84',['🔴 Channel 7 is reserved for OAM DMA',['../tutorial_hdma.html#autotoc_md230',1,'']]],
  ['for_20seamless_20wrapping_85',['64x32 Tilemap for Seamless Wrapping',['../examples_scrolling_parallax_scroll.html#autotoc_md1604',1,'']]],
  ['for_20snes_20compatibility_86',['For SNES Compatibility',['../snes_graphics_guide.html#autotoc_md656',1,'']]],
  ['for_20text_87',['VRAM Layout for Text',['../examples_text.html#autotoc_md1705',1,'']]],
  ['for_20the_20snes_88',['The workflow: design in Tiled, convert for the SNES',['../craft_tiles_to_levels.html#autotoc_md485',1,'']]],
  ['for_20transitions_89',['3. Combining both for transitions',['../examples_transitions_mosaic.html#autotoc_md1754',1,'']]],
  ['for_20vram_20access_90',['Force Blank for VRAM Access',['../examples_backgrounds_mode1_lz77.html#autotoc_md1012',1,'']]],
  ['for_20x_20≥_20128_91',['🔴 &lt;span class=&quot;tt&quot;&gt;FIX(x)&lt;/span&gt; overflows for &lt;span class=&quot;tt&quot;&gt;|x| ≥ 128&lt;/span&gt;',['../tutorial_math.html#autotoc_md277',1,'']]],
  ['for_20your_20game_92',['for your game',['../examples_backgrounds_mode2.html#autotoc_md1023',1,'Why it matters for your game'],['../examples_basics_game_skeleton.html#autotoc_md1070',1,'Why it matters for your game'],['../examples_basics_panel_hud.html#autotoc_md1076',1,'Why it matters for your game'],['../examples_color_palette_cycle.html#autotoc_md1146',1,'Why it matters for your game'],['../examples_color_shadow_tint.html#autotoc_md1154',1,'Why it matters for your game'],['../examples_sprites_sprite_swarm.html#autotoc_md1690',1,'Why it matters for your game']]],
  ['force_20blank_93',['1. Initialize and Stay in Force Blank',['../examples_backgrounds_mode1_lz77.html#autotoc_md1015',1,'']]],
  ['force_20blank_94',['2. Load sprites with force blank',['../examples_sprites_sprite_sizes.html#autotoc_md1680',1,'']]],
  ['force_20blank_20are_20silently_20dropped_95',['🔴 VRAM/CGRAM/OAM writes outside VBlank or force blank are silently dropped',['../tutorial_dma.html#autotoc_md175',1,'']]],
  ['force_20blank_20for_20initial_20setup_96',['Force Blank for Initial Setup',['../examples_sprites_dynamic_sprite.html#autotoc_md1645',1,'']]],
  ['force_20blank_20for_20large_20dma_97',['Force Blank for Large DMA',['../examples_sprites_sprite_sizes.html#autotoc_md1686',1,'']]],
  ['force_20blank_20for_20vram_20access_98',['Force Blank for VRAM Access',['../examples_backgrounds_mode1_lz77.html#autotoc_md1012',1,'']]],
  ['force_20blank_20vs_20brightness_200_99',['Force Blank vs Brightness 0',['../examples_transitions_fading.html#autotoc_md1742',1,'']]],
  ['forced_20blank_20—_20do_20not_20do_20it_20yourself_20with_20setbrightness_200_100',['🔴 &lt;span class=&quot;tt&quot;&gt;panelFlush&lt;/span&gt; uploads under forced blank — do not do it yourself with &lt;span class=&quot;tt&quot;&gt;setBrightness(0)&lt;/span&gt;',['../tutorial_panel.html#autotoc_md326',1,'']]],
  ['foreground_20occlusion_20—_20walking_20behind_20things_101',['Foreground occlusion — walking behind things',['../craft_backgrounds.html#autotoc_md446',1,'']]],
  ['format_102',['Format',['../examples_hdma_hdma_wave.html#autotoc_md1323',1,'2. The HDMA Table Format'],['../examples_text.html#autotoc_md1704',1,'2BPP Tile Format'],['../examples_backgrounds_mode1.html#autotoc_md976',1,'4bpp Tile Format'],['../snes_sound_guide.html#autotoc_md681',1,'BRR Sample Format'],['../math_8h.html#autotoc_md45',1,'Fixed-Point Format'],['../code_style.html#autotoc_md616',1,'Format'],['../lzss_8h.html#autotoc_md40',1,'LZ77 Format'],['../hdma_8h.html#autotoc_md32',1,'Table Format'],['../examples_backgrounds_mode1.html#autotoc_md974',1,'Tilemap Format']]],
  ['format_103',['format',['../examples_mode7_rotate_scale.html#autotoc_md1536',1,'1. Mode 7 VRAM format'],['../tutorial_hdma.html#autotoc_md215',1,'Table format'],['../tutorial_math.html#autotoc_md264',1,'The 8.8 fixed-point format'],['../tutorial_mode7.html#autotoc_md289',1,'The interleaved VRAM format']]],
  ['format_2015_20bit_20bgr_104',['Color Format (15-bit BGR)',['../snes_graphics_guide.html#autotoc_md652',1,'']]],
  ['format_20example_105',['Data Format Example',['../snes_graphics_guide.html#autotoc_md643',1,'']]],
  ['formats_106',['Tile Formats',['../snes_graphics_guide.html#autotoc_md634',1,'']]],
  ['formatting_20tools_107',['Formatting Tools',['../code_style.html#autotoc_md622',1,'']]],
  ['found_108',['found',['../troubleshooting.html#autotoc_md720',1,'&quot;clang: command not found&quot; or &quot;cc: command not found&quot;'],['../troubleshooting.html#autotoc_md719',1,'&quot;wla-65816: command not found&quot;'],['../troubleshooting.html#autotoc_md718',1,'Empty &lt;span class=&quot;tt&quot;&gt;compiler/&lt;/span&gt; directories or &quot;cc65816 not found&quot;']]],
  ['found_20or_20cc_3a_20command_20not_20found_109',['&quot;clang: command not found&quot; or &quot;cc: command not found&quot;',['../troubleshooting.html#autotoc_md720',1,'']]],
  ['found_20or_20empty_20compiler_20folder_110',['&quot;fatal: repository not found&quot; or empty compiler folder',['../getting_started.html#autotoc_md556',1,'']]],
  ['found_3a_20make_111',['&quot;command not found: make&quot;',['../getting_started.html#autotoc_md555',1,'']]],
  ['four_20bytes_112',['5. Two Colors, Four Bytes',['../examples_fundamentals_text_glyphs.html#autotoc_md1187',1,'']]],
  ['four_20channel_20registers_113',['The four channel registers',['../tutorial_hdma.html#autotoc_md213',1,'']]],
  ['four_20corners_114',['Checking All Four Corners',['../tutorial_collision.html#autotoc_md125',1,'']]],
  ['fractional_20precision_115',['🔴 &lt;span class=&quot;tt&quot;&gt;fixMul&lt;/span&gt; truncates fractional precision',['../tutorial_math.html#autotoc_md278',1,'']]],
  ['frame_116',['Mode Switching Mid-Frame',['../examples_mode7_perspective.html#autotoc_md1517',1,'']]],
  ['frame_117',['frame',['../tutorial_dma.html#autotoc_md176',1,'🔴 VBlank DMA budget is ~4 KB per frame'],['../examples_sprites_dynamic_sprite.html#autotoc_md1640',1,'3. Draw and upload every frame'],['../examples_mode7_rotate_scale.html#autotoc_md1538',1,'3. Update the matrix every frame']]],
  ['frame_20—_20hitstop_118',['Freeze the frame — hitstop',['../craft_game_feel.html#autotoc_md464',1,'']]],
  ['frame_20based_20animation_119',['Frame-Based Animation',['../tutorial_animation.html#autotoc_md71',1,'']]],
  ['frame_20based_20animation_120',['Frame-based Animation',['../tutorial_sprites.html#autotoc_md375',1,'']]],
  ['frame_20budget_121',['The frame budget',['../craft_frame_budget.html',1,'craft']]],
  ['frame_20dma_20in_20the_20main_20loop_122',['Per-frame DMA in the main loop',['../tutorial_dma.html#autotoc_md172',1,'']]],
  ['frame_20ids_123',['4. Animate by changing frame IDs',['../examples_sprites_dynamic_sprite.html#autotoc_md1641',1,'']]],
  ['frame_20timing_124',['Frame Timing',['../tutorial_animation.html#autotoc_md72',1,'']]],
  ['frame_5fcount_125',['VBlank and frame_count',['../examples_basics_timer.html#autotoc_md1103',1,'']]],
  ['framework_20instead_20of_20a_20switch_126',['Why a framework instead of a switch',['../examples_basics_scene_stack.html#autotoc_md1097',1,'']]],
  ['framework_20opt_20ins_127',['Framework opt-ins',['../index.html#autotoc_md8',1,'']]],
  ['free_20asset_20sources_20cc0_20public_20domain_128',['Free Asset Sources (CC0/Public Domain)',['../snes_graphics_guide.html#autotoc_md661',1,'']]],
  ['free_20depth_129',['7. Drop Shadows (Free Depth)',['../examples_games_breakout.html#autotoc_md1213',1,'']]],
  ['free_20running_20counter_130',['Pattern 2: Free-Running Counter',['../tutorial_sa1.html#autotoc_md339',1,'']]],
  ['freeze_20the_20frame_20—_20hitstop_131',['Freeze the frame — hitstop',['../craft_game_feel.html#autotoc_md464',1,'']]],
  ['frequencies_132',['Noise Frequencies',['../snes_sound_guide.html#autotoc_md715',1,'']]],
  ['from_133',['from',['../examples_backgrounds_mode0.html#autotoc_md956',1,'Ported from'],['../examples_backgrounds_mode3.html#autotoc_md1031',1,'Ported from'],['../examples_backgrounds_mode5.html#autotoc_md1035',1,'Ported from']]],
  ['from_20a_204bpp_20background_134',['HiColor — 1792 colors from a 4bpp background',['../examples_color_hicolor_1792.html',1,'examples_color']]],
  ['from_20a_20tilemap_20platformer_20pattern_135',['Tile Properties from a Tilemap (Platformer Pattern)',['../tutorial_collision.html#autotoc_md127',1,'']]],
  ['from_20bg3_136',['mode2 — offset-per-tile: per-column scroll from BG3',['../examples_backgrounds_mode2.html',1,'examples_backgrounds']]],
  ['from_20c_137',['from C',['../tutorial_sa1.html#autotoc_md336',1,'3. Initialize from C'],['../tutorial_superfx.html#autotoc_md408',1,'4. Launch from C'],['../examples_audio_soundboard.html',1,'soundboard — the audio v2 engine, driven entirely from C']]],
  ['from_20map_20data_138',['3. Load Objects from Map Data',['../examples_games_mapandobjects.html#autotoc_md1265',1,'']]],
  ['from_20motion_139',['Parallax — depth from motion',['../craft_backgrounds.html#autotoc_md444',1,'']]],
  ['from_20pure_20c_140',['The audio module (v2) — samples and effects from pure C',['../tutorial_audio.html#autotoc_md113',1,'']]],
  ['from_20sram_141',['3. Load from SRAM',['../examples_memory_save_game.html#autotoc_md1498',1,'']]],
  ['from_20the_20original_20a_20true_20story_142',['Why the envelope differs from the original (a true story)',['../examples_audio_pitch_mod.html#autotoc_md866',1,'']]],
  ['from_20tiles_20to_20levels_143',['From tiles to levels',['../craft_tiles_to_levels.html',1,'craft']]],
  ['from_20wav_144',['SFX from WAV',['../examples_audio_sfx_from_wav.html',1,'examples_audio']]],
  ['from_20wav_20wav2brr_145',['One-shot samples from WAV (wav2brr)',['../tutorial_audio.html#audio_wav2brr',1,'']]],
  ['from_20your_20genre_146',['Choose a background mode from your genre',['../craft_planning.html#autotoc_md474',1,'']]],
  ['front_147',['front',['../tools_font2snes.html#autotoc_md496',1,'Gotchas worth knowing up front'],['../tools_gfx4snes.html#autotoc_md502',1,'Gotchas worth knowing up front'],['../tools_img2snes.html#autotoc_md507',1,'Gotchas worth knowing up front'],['../tools_palplan.html#autotoc_md513',1,'Gotchas worth knowing up front'],['../tools_smconv.html#autotoc_md522',1,'Gotchas worth knowing up front'],['../tools_tmx2snes.html#autotoc_md527',1,'Gotchas worth knowing up front'],['../tools_wav2brr.html#autotoc_md532',1,'Gotchas worth knowing up front']]],
  ['full_148',['Fade In (Black to Full)',['../examples_transitions_fading.html#autotoc_md1723',1,'']]],
  ['full_20matrix_20per_20scanline_149',['Mode 7 rotating perspective — the full matrix, per scanline',['../examples_mode7_perspective_rotate.html',1,'examples_mode7']]],
  ['full_20mode_207_20matrix_20per_20line_20—_20examples_20mode7_20perspective_5frotate_150',['Full Mode 7 matrix per line — &lt;span class=&quot;tt&quot;&gt;examples/mode7/perspective_rotate&lt;/span&gt;',['../tutorial_hdma.html#autotoc_md226',1,'']]],
  ['full_20to_20black_151',['Fade Out (Full to Black)',['../examples_transitions_fading.html#autotoc_md1724',1,'']]],
  ['function_152',['Recipe 3 — Break at a function',['../tutorial_debugging.html#autotoc_md160',1,'']]],
  ['function_20documentation_153',['Function Documentation',['../code_style.html#autotoc_md611',1,'']]],
  ['function_20engine_20resolved_20size_154',['One Draw Function, Engine-Resolved Size',['../tutorial_animation.html#autotoc_md88',1,'']]],
  ['functions_155',['Using OpenSNES Sprite Functions',['../tutorial_sprites.html#autotoc_md365',1,'']]],
  ['fundamentals_156',['Fundamentals',['../examples_fundamentals.html',1,'Fundamentals'],['../examples_by_category.html#autotoc_md573',1,'Fundamentals'],['../examples.html#autotoc_md1550',1,'Level 2 &amp;ndash; Graphics Fundamentals']]],
  ['fundamentals_3a_20how_20a_20glyph_20is_20drawn_157',['Fundamentals: how a glyph is drawn',['../examples_fundamentals_text_glyphs.html',1,'examples_fundamentals']]],
  ['further_158',['Further',['../examples_fundamentals_text_glyphs.html#autotoc_md1193',1,'Go Further'],['../examples_games_breakout.html#autotoc_md1219',1,'Go Further'],['../examples_games_likemario.html#autotoc_md1245',1,'Go Further'],['../examples_hdma_hdma_wave.html#autotoc_md1331',1,'Go Further'],['../examples_scrolling_continuous_scroll.html#autotoc_md1571',1,'Go Further'],['../examples_backgrounds_mode1_bg3_priority.html#autotoc_md1007',1,'Going Further'],['../examples_hdma_gradient_colors.html#autotoc_md1308',1,'Going Further'],['../examples_memory_hirom_demo.html#autotoc_md1485',1,'Going Further'],['../examples_memory_save_game.html#autotoc_md1507',1,'Going Further'],['../examples_mode7_perspective.html#autotoc_md1521',1,'Going Further'],['../examples_mode7_rotate_scale.html#autotoc_md1546',1,'Going Further'],['../examples_scrolling_parallax_scroll.html#autotoc_md1607',1,'Going Further'],['../examples_sprites_animated_sprite.html#autotoc_md1624',1,'Going Further'],['../examples_sprites_dynamic_sprite.html#autotoc_md1647',1,'Going Further'],['../examples_sprites_simple_sprite.html#autotoc_md1674',1,'Going Further'],['../examples_sprites_sprite_sizes.html#autotoc_md1689',1,'Going Further'],['../examples_transitions_mosaic.html#autotoc_md1760',1,'Going Further'],['../examples_windows_transparent_window.html#autotoc_md1776',1,'Going Further'],['../examples_windows_window.html#autotoc_md1790',1,'Going Further']]],
  ['further_20reading_159',['Further Reading',['../tutorial_sa1.html#autotoc_md349',1,'Further Reading'],['../tutorial_superfx.html#autotoc_md420',1,'Further Reading'],['../memory_map.html#autotoc_md765',1,'Further Reading'],['../hardware_overview.html#autotoc_md796',1,'Further Reading'],['../registers.html#autotoc_md852',1,'Further Reading']]]
];
