var searchData=
[
  ['map_0',['map',['../examples_maps_dynamic_map.html',1,'Dynamic Map'],['../memory_map.html',1,'SNES Memory Map']]],
  ['map_20and_20objects_1',['Map and Objects',['../examples_games_mapandobjects.html',1,'examples_by_category']]],
  ['mapping_2',['HiROM Demo -- Understanding SNES Memory Mapping',['../examples_memory_hirom_demo.html',1,'examples_by_category']]],
  ['maps_3',['Maps',['../examples_maps.html',1,'']]],
  ['mario_4',['Slope Mario',['../examples_maps_slopemario.html',1,'examples_by_category']]],
  ['masking_5',['Window -- HDMA Triangle Masking',['../examples_graphics_effects_window.html',1,'examples_by_category']]],
  ['math_20hdma_6',['Transparent Window -- Color Math + HDMA',['../examples_graphics_effects_transparent_window.html',1,'examples_by_category']]],
  ['math_20transparency_20example_7',['Color Math Transparency Example',['../examples_graphics_effects_transparency.html',1,'examples_by_category']]],
  ['memory_8',['SNES OAM (Object Attribute Memory)',['../oam.html',1,'index']]],
  ['memory_20examples_9',['Memory Examples',['../examples_memory.html',1,'']]],
  ['memory_20map_10',['SNES Memory Map',['../memory_map.html',1,'index']]],
  ['memory_20mapping_11',['HiROM Demo -- Understanding SNES Memory Mapping',['../examples_memory_hirom_demo.html',1,'examples_by_category']]],
  ['metasprite_12',['Metasprite',['../examples_graphics_sprites_metasprite.html',1,'examples_by_category']]],
  ['mixed_20scroll_13',['Mixed Scroll',['../examples_graphics_backgrounds_mixed_scroll.html',1,'examples_by_category']]],
  ['mode_200_20—_204_20layer_202bpp_20background_14',['Mode 0 — 4-Layer 2bpp Background',['../examples_graphics_backgrounds_mode0.html',1,'examples_by_category']]],
  ['mode_201_20bg3_20high_20priority_20hud_20layer_20over_20backgrounds_15',['Mode 1 BG3 High Priority -- HUD Layer Over Backgrounds',['../examples_graphics_backgrounds_mode1_bg3_priority.html',1,'examples_by_category']]],
  ['mode_201_20example_16',['Mode 1 Example',['../examples_graphics_backgrounds_mode1.html',1,'examples_by_category']]],
  ['mode_201_20lz77_17',['Mode 1 LZ77',['../examples_graphics_backgrounds_mode1_lz77.html',1,'examples_by_category']]],
  ['mode_203_20—_20256_20color_20background_18',['Mode 3 — 256-Color Background',['../examples_graphics_backgrounds_mode3.html',1,'examples_by_category']]],
  ['mode_205_20—_20hi_20res_20512×256_20background_19',['Mode 5 — Hi-Res 512×256 Background',['../examples_graphics_backgrounds_mode5.html',1,'examples_by_category']]],
  ['mode_207_20perspective_20pseudo_203d_20ground_20effect_20',['Mode 7 Perspective -- Pseudo-3D Ground Effect',['../examples_graphics_backgrounds_mode7_perspective.html',1,'examples_by_category']]],
  ['mode_207_20rotation_20and_20scaling_21',['Mode 7 -- Rotation and Scaling',['../examples_graphics_backgrounds_mode7.html',1,'examples_by_category']]],
  ['modes_22',['Object Size -- All 6 SNES Sprite Size Modes',['../examples_graphics_sprites_object_size.html',1,'examples_by_category']]],
  ['module_20test_23',['Text Module Test',['../examples_text_text_test.html',1,'examples_by_category']]],
  ['mosaic_20ppu_20pixel_20block_20effect_24',['Mosaic -- PPU Pixel Block Effect',['../examples_graphics_effects_mosaic.html',1,'examples_by_category']]],
  ['mouse_25',['SNES Mouse',['../examples_input_mouse.html',1,'examples_by_category']]],
  ['music_20example_26',['SNESMOD Music Example',['../examples_audio_snesmod_music.html',1,'examples_by_category']]],
  ['music_20tutorial_27',['Audio &amp; Music Tutorial',['../tutorial_audio.html',1,'index']]]
];
