var searchData=
[
  ['ui_20elements_0',['Sprites as UI Elements',['../examples_input_mouse.html#autotoc_md1408',1,'']]],
  ['unaffected_1',['Sprites Are Unaffected',['../examples_graphics_effects_mosaic.html#autotoc_md1234',1,'']]],
  ['uncompressed_2',['3. Load Palette and Tilemap (Uncompressed)',['../examples_graphics_backgrounds_mode1_lz77.html#autotoc_md1061',1,'']]],
  ['undefined_3',['🔴 SRAM contents on first boot are undefined',['../tutorial_sram.html#autotoc_md366',1,'']]],
  ['under_20the_20hood_3a_20the_20build_4',['Under the Hood: The Build',['../examples_games_breakout.html#autotoc_md888',1,'Under the Hood: The Build'],['../examples_games_likemario.html#autotoc_md914',1,'Under the Hood: The Build'],['../examples_graphics_backgrounds_continuous_scroll.html#autotoc_md977',1,'Under the Hood: The Build'],['../examples_graphics_effects_hdma_wave.html#autotoc_md1190',1,'Under the Hood: The Build'],['../examples_input_superscope.html#autotoc_md1435',1,'Under the Hood: The Build'],['../examples_text_hello_world.html#autotoc_md1605',1,'Under the Hood: The Build']]],
  ['understanding_20snes_20memory_20mapping_5',['HiROM Demo -- Understanding SNES Memory Mapping',['../examples_memory_hirom_demo.html',1,'examples_memory']]],
  ['understanding_20what_20you_20see_6',['Understanding what you see',['../examples_graphics_effects_hires_text.html#autotoc_md1211',1,'']]],
  ['unhandled_20op_20or_20assembly_20errors_7',['Build fails with &quot;unhandled op&quot; or assembly errors',['../getting_started.html#autotoc_md440',1,'']]],
  ['unhandled_20op_3a_20xxx_8',['Build fails with &quot;unhandled op: XXX&quot;',['../troubleshooting.html#autotoc_md589',1,'']]],
  ['unsigned_20angle_20signed_20result_9',['🟡 Sin/cos LUTs are unsigned-angle, signed-result',['../tutorial_math.html#autotoc_md267',1,'']]],
  ['unusual_10',['🟠 Mosaic + Mode 7 = unusual',['../tutorial_mosaic.html#autotoc_md299',1,'']]],
  ['up_11',['🟠 OAM DMA is automated, don&apos;t double-up',['../tutorial_dma.html#autotoc_md177',1,'']]],
  ['up_20a_20dynamic_20sprite_12',['Setting Up a Dynamic Sprite',['../tutorial_animation.html#autotoc_md83',1,'']]],
  ['up_20background_13',['2. Set Up Background',['../examples_graphics_backgrounds_mode1.html#autotoc_md1014',1,'']]],
  ['up_20graphics_14',['Setting Up Graphics',['../tutorial_graphics.html#autotoc_md198',1,'']]],
  ['up_20memory_15',['Example: Setting Up Memory',['../memory_map.html#autotoc_md629',1,'']]],
  ['up_20oam_20directly_16',['3. Set Up OAM Directly',['../examples_input_mouse.html#autotoc_md1413',1,'']]],
  ['up_20sprites_20via_20the_20oambuffer_17',['2. Set up sprites via the oambuffer',['../examples_graphics_sprites_dynamic_sprite.html#autotoc_md1341',1,'']]],
  ['up_20text_20on_20bg1_204bpp_20in_20mode_201_18',['1. Set up text on BG1 (4bpp in Mode 1)',['../examples_graphics_sprites_object_size.html#autotoc_md1363',1,'']]],
  ['up_20the_20hdma_20channel_19',['4. Setting Up the HDMA Channel',['../examples_graphics_effects_hdma_wave.html#autotoc_md1182',1,'']]],
  ['up_20the_20ppu_20',['3. Setting Up the PPU',['../examples_text_hello_world.html#autotoc_md1595',1,'']]],
  ['up_20three_20background_20layers_21',['1. Set up three background layers',['../examples_graphics_backgrounds_mode1_bg3_priority.html#autotoc_md1042',1,'']]],
  ['up_20tilemaps_22',['Setting Up Tilemaps',['../tutorial_graphics.html#autotoc_md201',1,'']]],
  ['update_23',['Map Engine Two-Phase Update',['../examples_maps_mapscroll.html#autotoc_md1493',1,'']]],
  ['update_20cursor_24',['4. Main Loop: Read Mouse, Update Cursor',['../examples_input_mouse.html#autotoc_md1414',1,'']]],
  ['update_20draw_20sync_25',['4. Main Loop: Update, Draw, Sync',['../examples_games_mapandobjects.html#autotoc_md933',1,'']]],
  ['update_20the_20matrix_20every_20frame_26',['3. Update the matrix every frame',['../examples_graphics_backgrounds_mode7.html#autotoc_md1082',1,'']]],
  ['updates_20via_20bgsetscroll_20dirty_20flags_27',['3. Scroll Updates via bgSetScroll Dirty Flags',['../examples_graphics_backgrounds_continuous_scroll.html#autotoc_md969',1,'']]],
  ['updating_20oam_28',['Updating OAM',['../tutorial_sprites.html#autotoc_md343',1,'']]],
  ['upload_20every_20frame_29',['3. Draw and upload every frame',['../examples_graphics_sprites_dynamic_sprite.html#autotoc_md1342',1,'']]],
  ['upload_20protocol_20boot_30',['Upload Protocol (Boot)',['../snes_sound_guide.html#autotoc_md566',1,'']]],
  ['uploading_20tiles_20to_20vram_31',['4. Uploading Tiles to VRAM',['../examples_text_hello_world.html#autotoc_md1596',1,'']]],
  ['usage_32',['Usage',['../console_8h.html#autotoc_md19',1,'Basic Usage'],['../snesmod_8h.html#autotoc_md56',1,'Memory Usage'],['../tutorial_audio.html#autotoc_md107',1,'Memory Usage'],['../snes_sound_guide.html#autotoc_md562',1,'Memory Usage'],['../debug_8h.html#autotoc_md21',1,'Usage'],['../input_8h.html#autotoc_md35',1,'Usage'],['../group__mouse__input.html#autotoc_md36',1,'Usage'],['../group__scope__input.html#autotoc_md37',1,'Usage'],['../lzss_8h.html#autotoc_md39',1,'Usage'],['../map_8h.html#autotoc_md40',1,'Usage'],['../mode7_8h.html#autotoc_md45',1,'Usage'],['../registers_8h.html#autotoc_md51',1,'Usage'],['../sprite_8h.html#autotoc_md58',1,'Usage']]],
  ['usage_20example_33',['Usage Example',['../collision_8h.html#autotoc_md15',1,'Usage Example'],['../colormath_8h.html#autotoc_md18',1,'Usage Example'],['../hdma_8h.html#autotoc_md31',1,'Usage Example'],['../sram_8h.html#autotoc_md62',1,'Usage Example'],['../window_8h.html#autotoc_md67',1,'Usage Example']]],
  ['use_34',['Practical Use',['../examples_graphics_effects_transparent_window.html#autotoc_md1290',1,'']]],
  ['use_20hirom_35',['When to Use HiROM',['../examples_memory_hirom_demo.html#autotoc_md1538',1,'']]],
  ['use_20sta_20l_20lda_20l_20for_20everything_36',['Use &lt;span class=&quot;tt&quot;&gt;sta.l&lt;/span&gt; / &lt;span class=&quot;tt&quot;&gt;lda.l&lt;/span&gt; for Everything',['../tutorial_sa1.html#autotoc_md317',1,'']]],
  ['used_37',['Used',['../examples_audio_apu_switch.html#autotoc_md728',1,'Modules Used'],['../examples_audio_pitch_mod.html#autotoc_md733',1,'Modules Used'],['../examples_audio_play_noise.html#autotoc_md736',1,'Modules Used'],['../examples_audio_snesmod_music_hirom.html#autotoc_md794',1,'Modules Used'],['../examples_audio_snesmod_music_large.html#autotoc_md798',1,'Modules Used'],['../examples_audio_soundboard.html#autotoc_md814',1,'Modules Used'],['../examples_audio_speech_synth.html#autotoc_md818',1,'Modules Used'],['../examples_basics_aim_target.html#autotoc_md822',1,'Modules Used'],['../examples_basics_fix32_orbit.html#autotoc_md842',1,'Modules Used'],['../examples_basics_random.html#autotoc_md849',1,'Modules Used'],['../examples_basics_scene_stack.html#autotoc_md861',1,'Modules Used'],['../examples_basics_timer.html#autotoc_md867',1,'Modules Used'],['../examples_games_mode7_flying.html#autotoc_md939',1,'Modules Used'],['../examples_games_mode7_racing.html#autotoc_md942',1,'Modules Used'],['../examples_games_rpg.html#autotoc_md949',1,'Modules Used'],['../examples_games_shmup_1942.html#autotoc_md956',1,'Modules Used'],['../examples_graphics_effects_direct_color.html#autotoc_md1113',1,'Modules Used'],['../examples_graphics_effects_gradient_9bit.html#autotoc_md1151',1,'Modules Used'],['../examples_graphics_effects_hdma_indirect_gradient.html#autotoc_md1173',1,'Modules Used'],['../examples_graphics_effects_hdma_wave_table.html#autotoc_md1200',1,'Modules Used'],['../examples_graphics_effects_hicolor_1792.html#autotoc_md1206',1,'Modules Used'],['../examples_graphics_effects_hicolor_blend.html#autotoc_md1207',1,'Modules Used'],['../examples_graphics_effects_hicolor_hires.html#autotoc_md1209',1,'Modules Used'],['../examples_graphics_effects_hires_text.html#autotoc_md1215',1,'Modules Used'],['../examples_graphics_effects_mode7_perspective_rotate.html#autotoc_md1222',1,'Modules Used'],['../examples_graphics_effects_superfx_3d.html#autotoc_md1264',1,'Modules Used'],['../examples_graphics_effects_window_multi_hdma.html#autotoc_md1310',1,'Modules Used'],['../examples_graphics_sprites_dynamic_metasprite.html#autotoc_md1334',1,'Modules Used'],['../examples_input_controller.html#autotoc_md1402',1,'Modules Used'],['../examples_maps_mapscroll.html#autotoc_md1496',1,'Modules Used'],['../examples_maps_tiled.html#autotoc_md1524',1,'Modules Used'],['../examples_memory_sa1_hello.html#autotoc_md1550',1,'Modules Used'],['../examples_memory_sa1_starfield.html#autotoc_md1554',1,'Modules Used'],['../examples_memory_superfx_hello.html#autotoc_md1576',1,'Modules Used']]],
  ['user_20callback_20in_20the_20nmi_20handler_38',['🟡 HDMA fires before the user callback in the NMI handler',['../tutorial_hdma.html#autotoc_md230',1,'']]],
  ['using_20getframecount_39',['Using getFrameCount()',['../tutorial_animation.html#autotoc_md72',1,'']]],
  ['using_20gfx4snes_40',['Using gfx4snes',['../tutorial_graphics.html#autotoc_md205',1,'']]],
  ['using_20mesen_20debugger_20alternative_41',['Using Mesen Debugger (alternative)',['../troubleshooting.html#autotoc_md607',1,'']]],
  ['using_20mode_201_42',['Games Using Mode 1',['../examples_graphics_backgrounds_mode1.html#autotoc_md1010',1,'']]],
  ['using_20openmpt_20recommended_43',['Using OpenMPT (Recommended)',['../examples_audio_snesmod_music.html#autotoc_md758',1,'']]],
  ['using_20opensnes_20sprite_20functions_44',['Using OpenSNES Sprite Functions',['../tutorial_sprites.html#autotoc_md340',1,'']]],
  ['using_20rand_20in_20games_45',['Using rand() in Games',['../examples_basics_random.html#autotoc_md848',1,'']]],
  ['utilities_46',['Utilities',['../tutorial_math.html#autotoc_md254',1,'']]]
];
