var searchData=
[
  ['v1_209_200_0',['v1 9 0',['../examples_mode7_perspective_rotate.html#autotoc_md1523',1,'Measured parity (luna v1.9.0)'],['../examples_backgrounds_mode5_hires.html#autotoc_md1038',1,'Validation notes (luna v1.9.0)']]],
  ['v1_209_200_20mesen2_20cross_20check_1',['Measured parity (luna v1.9.0 + Mesen2 cross-check)',['../examples_color_hicolor_1792.html#autotoc_md1139',1,'']]],
  ['v2_20—_20samples_20and_20effects_20from_20pure_20c_2',['The audio module (v2) — samples and effects from pure C',['../tutorial_audio.html#autotoc_md113',1,'']]],
  ['v2_20engine_20driven_20entirely_20from_20c_3',['soundboard — the audio v2 engine, driven entirely from C',['../examples_audio_soundboard.html',1,'examples_audio']]],
  ['validation_4',['Validation',['../examples_memory_save_game.html#autotoc_md1502',1,'Checksum Validation'],['../examples_audio_apu_switch.html#autotoc_md856',1,'Validation']]],
  ['validation_20notes_20luna_20v1_209_200_5',['Validation notes (luna v1.9.0)',['../examples_backgrounds_mode5_hires.html#autotoc_md1038',1,'']]],
  ['values_6',['Timing Values',['../snes_sound_guide.html#autotoc_md687',1,'']]],
  ['values_7',['values',['../craft_camera.html#autotoc_md447',1,'The camera &lt;em&gt;is&lt;/em&gt; your scroll values'],['../troubleshooting.html#autotoc_md733',1,'Variables have wrong values']]],
  ['variable_8',['Recipe 2 — &quot;Who writes this variable?&quot;',['../tutorial_debugging.html#autotoc_md159',1,'']]],
  ['variables_20have_20wrong_20values_9',['Variables have wrong values',['../troubleshooting.html#autotoc_md733',1,'']]],
  ['variables_20with_20initializers_10',['Static variables with initializers',['../troubleshooting.html#autotoc_md720',1,'']]],
  ['varies_11',['🟡 Emulator persistence varies',['../tutorial_sram.html#autotoc_md396',1,'']]],
  ['vblank_12',['VBlank',['../hardware_overview.html#autotoc_md789',1,'Vertical Blank (VBlank)'],['../examples_sprites_dynamic_sprite.html#autotoc_md1641',1,'VRAM Budget During VBlank']]],
  ['vblank_20and_20frame_5fcount_13',['VBlank and frame_count',['../examples_basics_timer.html#autotoc_md1101',1,'']]],
  ['vblank_20budget_14',['VBlank Budget',['../tutorial_animation.html#autotoc_md92',1,'']]],
  ['vblank_20dma_20budget_20is_204_20kb_20per_20frame_15',['🔴 VBlank DMA budget is ~4 KB per frame',['../tutorial_dma.html#autotoc_md176',1,'']]],
  ['vblank_20dma_20budget_3a_204_20kb_16',['The VBlank DMA budget: ~4 KB',['../craft_frame_budget.html#autotoc_md455',1,'']]],
  ['vblank_20dma_20pattern_17',['1-Page-Per-VBlank DMA Pattern',['../examples_maps_dynamic_map.html#autotoc_md1434',1,'']]],
  ['vblank_20mapupdate_20does_20not_18',['🟠 &lt;span class=&quot;tt&quot;&gt;mapVblank()&lt;/span&gt; belongs in VBlank, &lt;span class=&quot;tt&quot;&gt;mapUpdate()&lt;/span&gt; does not',['../tutorial_map.html#autotoc_md259',1,'']]],
  ['vblank_20or_20force_20blank_20are_20silently_20dropped_19',['🔴 VRAM/CGRAM/OAM writes outside VBlank or force blank are silently dropped',['../tutorial_dma.html#autotoc_md175',1,'']]],
  ['vblank_20timer_20',['VBlank Timer',['../examples_basics_timer.html',1,'examples_basics']]],
  ['vblank_20timing_21',['VBlank Timing',['../tutorial_scrolling.html#autotoc_md359',1,'']]],
  ['vblank_20timing_20requirement_22',['VBlank Timing Requirement',['../dma_8h.html#autotoc_md26',1,'']]],
  ['vertical_20blank_20vblank_23',['Vertical Blank (VBlank)',['../hardware_overview.html#autotoc_md789',1,'']]],
  ['vertical_20wants_20different_20rules_24',['Vertical wants different rules',['../craft_camera.html#autotoc_md450',1,'']]],
  ['via_20bgsetscroll_20dirty_20flags_25',['3. Scroll Updates via bgSetScroll Dirty Flags',['../examples_scrolling_continuous_scroll.html#autotoc_md1563',1,'']]],
  ['via_20hdma_20—_20examples_20mode7_20perspective_26',['F-Zero perspective via HDMA — &lt;span class=&quot;tt&quot;&gt;examples/mode7/perspective&lt;/span&gt;',['../tutorial_mode7.html#autotoc_md295',1,'']]],
  ['via_20pitch_20modulation_27',['pitch_mod — hardware vibrato via pitch modulation',['../examples_audio_pitch_mod.html',1,'examples_audio']]],
  ['via_20the_20oambuffer_28',['2. Set up sprites via the oambuffer',['../examples_sprites_dynamic_sprite.html#autotoc_md1637',1,'']]],
  ['viable_20colour_20math_29',['The minimum viable colour math',['../tutorial_colormath.html#autotoc_md140',1,'']]],
  ['viable_20dialog_20box_30',['The minimum viable dialog box',['../tutorial_panel.html#autotoc_md321',1,'']]],
  ['viable_20mosaic_31',['The minimum viable mosaic',['../tutorial_mosaic.html#autotoc_md307',1,'']]],
  ['viable_20save_32',['The minimum viable save',['../tutorial_sram.html#autotoc_md385',1,'']]],
  ['viable_20scroller_33',['The minimum viable scroller',['../tutorial_map.html#autotoc_md253',1,'']]],
  ['viable_20window_34',['The minimum viable window',['../tutorial_window.html#autotoc_md420',1,'']]],
  ['vibrato_20via_20pitch_20modulation_35',['pitch_mod — hardware vibrato via pitch modulation',['../examples_audio_pitch_mod.html',1,'examples_audio']]],
  ['video_20mode_36',['1. Configure Video Mode',['../examples_backgrounds_mode1.html#autotoc_md967',1,'']]],
  ['video_20modes_37',['Video Modes',['../tutorial_graphics.html#autotoc_md200',1,'SNES Video Modes'],['../snes_graphics_guide.html#autotoc_md626',1,'Video Modes']]],
  ['video_20ram_20_242116_20_242119_38',['Video RAM ($2116-$2119)',['../memory_map.html#autotoc_md753',1,'']]],
  ['visual_20—_20examples_20color_20gradient_5f9bit_39',['Two channels, one visual — &lt;span class=&quot;tt&quot;&gt;examples/color/gradient_9bit&lt;/span&gt;',['../tutorial_hdma.html#autotoc_md227',1,'']]],
  ['vmaddl_20h_20vram_20address_40',['$2116-$2117 - VMADDL/H (VRAM Address)',['../registers.html#autotoc_md814',1,'']]],
  ['vmain_20vram_20address_20increment_41',['$2115 - VMAIN (VRAM Address Increment)',['../registers.html#autotoc_md813',1,'']]],
  ['vmdatal_20h_20vram_20data_20write_42',['$2118-$2119 - VMDATAL/H (VRAM Data Write)',['../registers.html#autotoc_md815',1,'']]],
  ['voice_200_207_43',['Per-Voice Registers (x = voice 0-7)',['../snes_sound_guide.html#autotoc_md676',1,'']]],
  ['voice_20registers_20x_20voice_200_207_44',['Per-Voice Registers (x = voice 0-7)',['../snes_sound_guide.html#autotoc_md676',1,'']]],
  ['volume_20control_45',['Volume Control',['../tutorial_audio.html#autotoc_md103',1,'Volume Control'],['../examples_audio_snesmod_music.html#autotoc_md892',1,'Volume Control']]],
  ['vram_46',['VRAM',['../examples_sprites_simple_sprite.html#autotoc_md1662',1,'1. Load sprite graphics into VRAM'],['../examples_backgrounds_mode1_lz77.html#autotoc_md1014',1,'2. Decompress Tiles to VRAM'],['../examples_scrolling_mixed_scroll.html#autotoc_md1587',1,'2. Load Tilemaps to VRAM'],['../examples_fundamentals_text_glyphs.html#autotoc_md1184',1,'4. Uploading Tiles to VRAM'],['../tutorial_graphics.html#autotoc_md203',1,'Loading Tiles to VRAM'],['../examples_sprites_animated_sprite.html#autotoc_md1619',1,'Sprite Sheets in VRAM']]],
  ['vram_20—_2064_20kb_20shared_20by_20everything_20on_20screen_47',['1. VRAM — 64 KB, shared by everything on screen',['../craft_planning.html#autotoc_md469',1,'']]],
  ['vram_20—_20so_20stream_20it_48',['The level is bigger than VRAM — so stream it',['../craft_tiles_to_levels.html#autotoc_md482',1,'']]],
  ['vram_20access_49',['VRAM Access',['../examples_backgrounds_mode1_lz77.html#autotoc_md1010',1,'Force Blank for VRAM Access'],['../registers.html#autotoc_md812',1,'VRAM Access']]],
  ['vram_20address_50',['$2116-$2117 - VMADDL/H (VRAM Address)',['../registers.html#autotoc_md814',1,'']]],
  ['vram_20address_51',['The &lt;span class=&quot;tt&quot;&gt;name_base&lt;/span&gt; argument is a page number, not a VRAM address',['../tutorial_sprites.html#autotoc_md368',1,'']]],
  ['vram_20address_20increment_52',['$2115 - VMAIN (VRAM Address Increment)',['../registers.html#autotoc_md813',1,'']]],
  ['vram_20address_20registers_53',['VRAM Address Registers',['../snes_graphics_guide.html#autotoc_md646',1,'']]],
  ['vram_20budget_20during_20vblank_54',['VRAM Budget During VBlank',['../examples_sprites_dynamic_sprite.html#autotoc_md1641',1,'']]],
  ['vram_20cgram_20oam_20writes_20are_20safe_55',['When VRAM/CGRAM/OAM writes are safe',['../tutorial_dma.html#autotoc_md170',1,'']]],
  ['vram_20cgram_20oam_20writes_20outside_20vblank_20or_20force_20blank_20are_20silently_20dropped_56',['🔴 VRAM/CGRAM/OAM writes outside VBlank or force blank are silently dropped',['../tutorial_dma.html#autotoc_md175',1,'']]],
  ['vram_20data_20write_57',['$2118-$2119 - VMDATAL/H (VRAM Data Write)',['../registers.html#autotoc_md815',1,'']]],
  ['vram_20format_58',['VRAM format',['../examples_mode7_rotate_scale.html#autotoc_md1534',1,'1. Mode 7 VRAM format'],['../tutorial_mode7.html#autotoc_md288',1,'The interleaved VRAM format']]],
  ['vram_20layout_59',['VRAM Layout',['../examples_games_likemario.html#autotoc_md1234',1,'2. The VRAM Layout'],['../mode7_8h.html#autotoc_md48',1,'Mode 7 VRAM Layout'],['../snes_graphics_guide.html#autotoc_md644',1,'VRAM Layout'],['../examples_backgrounds_mode1.html#autotoc_md971',1,'VRAM Layout'],['../examples_backgrounds_mode1_bg3_priority.html#autotoc_md1003',1,'VRAM Layout'],['../examples_sprites_sprite_sizes.html#autotoc_md1685',1,'VRAM Layout'],['../examples_windows_window.html#autotoc_md1786',1,'VRAM Layout']]],
  ['vram_20layout_20for_20text_60',['VRAM Layout for Text',['../examples_text.html#autotoc_md1703',1,'']]],
  ['vram_20layout_20planning_61',['VRAM Layout Planning',['../examples_scrolling_mixed_scroll.html#autotoc_md1581',1,'']]],
  ['vram_20map_20—_20a_20deliberate_20overlap_62',['2. The VRAM Map — A Deliberate Overlap',['../examples_games_breakout.html#autotoc_md1206',1,'']]],
  ['vram_20no_20mode7loadgraphics_20helper_20today_63',['🔴 Interleaved VRAM, no &lt;span class=&quot;tt&quot;&gt;mode7LoadGraphics&lt;/span&gt; helper today',['../tutorial_mode7.html#autotoc_md298',1,'']]],
  ['vram_20reload_20between_20states_64',['VRAM Reload Between States',['../tutorial_game_states.html#autotoc_md189',1,'']]],
  ['vram_20streaming_20for_20animated_20sprites_65',['Dynamic Sprite -- VRAM Streaming for Animated Sprites',['../examples_sprites_dynamic_sprite.html',1,'examples_sprites']]],
  ['vram_20tile_20layout_20and_20oam_20tile_20numbers_66',['VRAM Tile Layout and OAM Tile Numbers',['../examples_sprites_metasprite.html#autotoc_md1650',1,'']]],
  ['vram_20tile_20numbering_67',['VRAM Tile Numbering',['../tutorial_animation.html#autotoc_md76',1,'']]],
  ['vram_20transfer_68',['SRAM to VRAM Transfer',['../tutorial_superfx.html#autotoc_md416',1,'']]],
  ['vs_20animated_20shapes_69',['Static shapes vs animated shapes',['../tutorial_window.html#autotoc_md421',1,'']]],
  ['vs_20bg_20window_70',['Color Math Window vs BG Window',['../examples_windows_transparent_window.html#autotoc_md1771',1,'']]],
  ['vs_20brightness_200_71',['Force Blank vs Brightness 0',['../examples_transitions_fading.html#autotoc_md1740',1,'']]],
  ['vs_20dynamic_20sprites_72',['Static vs Dynamic Sprites',['../examples_sprites_dynamic_sprite.html#autotoc_md1642',1,'']]],
  ['vs_20hardware_73',['Recipe 4 — Sprite/OAM debugging (shadow buffer vs hardware)',['../tutorial_debugging.html#autotoc_md161',1,'']]],
  ['vs_20hdma_74',['DMA vs HDMA',['../tutorial_dma.html#autotoc_md166',1,'']]],
  ['vs_20hdma_20on_20channel_200_75',['🟠 Channel 0 vs HDMA on channel 0',['../tutorial_dma.html#autotoc_md178',1,'']]],
  ['vs_20hirom_76',['vs HiROM',['../hardware_overview.html#autotoc_md793',1,'LoROM vs HiROM'],['../examples_memory_hirom_demo.html#autotoc_md1479',1,'LoROM vs HiROM'],['../examples_memory.html#autotoc_md1486',1,'LoROM vs HiROM']]],
  ['vs_20mul16_77',['🟠 Compiler &lt;span class=&quot;tt&quot;&gt;*&lt;/span&gt; vs &lt;span class=&quot;tt&quot;&gt;mul16&lt;/span&gt;',['../tutorial_math.html#autotoc_md279',1,'']]],
  ['vs_20padpressed_78',['padHeld vs padPressed',['../examples_input_controller.html#autotoc_md1348',1,'']]],
  ['vs_20rectangle_79',['Point-vs-Rectangle',['../tutorial_collision.html#autotoc_md122',1,'']]],
  ['vs_20repeat_20mode_80',['Non-Repeat vs Repeat Mode',['../examples_hdma_gradient_colors.html#autotoc_md1304',1,'']]],
  ['vs_20sprites_81',['2. CGRAM — 256 colours, split BG vs sprites',['../craft_planning.html#autotoc_md470',1,'']]],
  ['vs_20sub_20screen_82',['Main Screen vs Sub Screen',['../colormath_8h.html#autotoc_md19',1,'']]],
  ['vs_20the_20original_83',['vs the original',['../examples_audio_speech_synth.html#autotoc_md948',1,'Register fidelity vs the original'],['../examples_backgrounds_mode5_hires.html#autotoc_md1037',1,'Register fidelity vs the original'],['../examples_color_gradient_9bit.html#autotoc_md1134',1,'Register fidelity vs the original'],['../examples_color_hicolor_1792.html#autotoc_md1138',1,'Register fidelity vs the original'],['../examples_mode7_perspective_rotate.html#autotoc_md1522',1,'Register fidelity vs the original'],['../examples_windows_window_multi_hdma.html#autotoc_md1790',1,'Register fidelity vs the original']]],
  ['vs_20where_20it_20collides_84',['Where the sprite is vs where it collides',['../tutorial_collision.html#autotoc_md128',1,'']]],
  ['vtimex_20irq_20timer_85',['$4207-$420A - HTIMEx/VTIMEx (IRQ Timer)',['../registers.html#autotoc_md826',1,'']]]
];
