var searchData=
[
  ['oam_0',['OAM',['../examples_graphics_sprites_animated_sprite.html#autotoc_md1350',1,'16x16 Tiles in OAM'],['../tutorial_sprites.html#autotoc_md362',1,'Initialize OAM'],['../tutorial_sprites.html#autotoc_md364',1,'Updating OAM']]],
  ['oam_20address_1',['OAM Address',['../registers.html#autotoc_md695',1,'$2102-$2103 - OAMADDL/H (OAM Address)'],['../oam.html#autotoc_md665',1,'Setting OAM Address']]],
  ['oam_20data_20write_2',['$2104 - OAMDATA (OAM Data Write)',['../registers.html#autotoc_md696',1,'']]],
  ['oam_20debugging_20shadow_20buffer_20vs_20hardware_3',['Recipe 4 — Sprite/OAM debugging (shadow buffer vs hardware)',['../tutorial_debugging.html#autotoc_md159',1,'']]],
  ['oam_20directly_4',['3. Set Up OAM Directly',['../examples_input_mouse.html#autotoc_md1435',1,'']]],
  ['oam_20dma_5',['🔴 Channel 7 is reserved for OAM DMA',['../tutorial_hdma.html#autotoc_md228',1,'']]],
  ['oam_20dma_20is_20automated_20don_20t_20double_20up_6',['🟠 OAM DMA is automated, don&apos;t double-up',['../tutorial_dma.html#autotoc_md177',1,'']]],
  ['oam_20high_20table_7',['OAM High Table',['../examples_graphics_sprites_object_size.html#autotoc_md1391',1,'']]],
  ['oam_20object_20attribute_20memory_8',['OAM Object Attribute Memory',['../memory_map.html#autotoc_md646',1,'OAM (Object Attribute Memory)'],['../examples_graphics_sprites_simple_sprite.html#autotoc_md1413',1,'OAM (Object Attribute Memory)'],['../oam.html',1,'SNES OAM (Object Attribute Memory)']]],
  ['oam_20registers_9',['OAM Registers',['../oam.html#autotoc_md664',1,'']]],
  ['oam_20setup_10',['5. Direct OAM Setup',['../examples_input_superscope.html#autotoc_md1454',1,'']]],
  ['oam_20sprite_11',['Simple Sprite -- Your First OAM Sprite',['../examples_graphics_sprites_simple_sprite.html',1,'examples_graphics_sprites']]],
  ['oam_20sprite_20memory_12',['OAM (Sprite Memory)',['../registers.html#autotoc_md694',1,'']]],
  ['oam_20structure_13',['OAM Structure',['../tutorial_sprites.html#autotoc_md360',1,'OAM Structure'],['../oam.html#autotoc_md656',1,'OAM Structure'],['../examples_graphics_sprites.html#autotoc_md1398',1,'OAM Structure']]],
  ['oam_20structure_20544_20bytes_20total_14',['OAM Structure (544 bytes total)',['../snes_graphics_guide.html#autotoc_md527',1,'']]],
  ['oam_20tile_20numbers_15',['VRAM Tile Layout and OAM Tile Numbers',['../examples_graphics_sprites_metasprite.html#autotoc_md1376',1,'']]],
  ['oam_20write_20buffer_16',['Critical: OAM Write Buffer',['../oam.html#autotoc_md660',1,'']]],
  ['oam_20writes_20are_20safe_17',['When VRAM/CGRAM/OAM writes are safe',['../tutorial_dma.html#autotoc_md168',1,'']]],
  ['oam_20writes_20outside_20vblank_20or_20force_20blank_20are_20silently_20dropped_18',['🔴 VRAM/CGRAM/OAM writes outside VBlank or force blank are silently dropped',['../tutorial_dma.html#autotoc_md173',1,'']]],
  ['oamaddl_20h_20oam_20address_19',['$2102-$2103 - OAMADDL/H (OAM Address)',['../registers.html#autotoc_md695',1,'']]],
  ['oambuffer_20',['2. Set up sprites via the oambuffer',['../examples_graphics_sprites_dynamic_sprite.html#autotoc_md1363',1,'']]],
  ['oamdata_20oam_20data_20write_21',['$2104 - OAMDATA (OAM Data Write)',['../registers.html#autotoc_md696',1,'']]],
  ['oammemory_20writes_22',['Direct oamMemory[] Writes',['../examples_basics_collision_demo.html#autotoc_md854',1,'']]],
  ['obj_20math_20depends_20on_20palette_23',['🟡 OBJ math depends on palette',['../tutorial_colormath.html#autotoc_md151',1,'']]],
  ['obj_20size_24',['3. Configure OBJ size',['../examples_graphics_sprites_simple_sprite.html#autotoc_md1409',1,'']]],
  ['obj_20size_20modes_20register_20_242101_25',['OBJ Size Modes (Register $2101)',['../examples_graphics_sprites_metasprite.html#autotoc_md1374',1,'']]],
  ['obj_20sprites_26',['🟠 Mosaic does not affect OBJ (sprites)',['../tutorial_mosaic.html#autotoc_md310',1,'']]],
  ['obj_5fflipx_20ndash_20hardware_20horizontal_20mirror_27',['OBJ_FLIPX &amp;ndash; Hardware Horizontal Mirror',['../examples_graphics_sprites_animated_sprite.html#autotoc_md1348',1,'']]],
  ['object_20attribute_20memory_28',['Object Attribute Memory',['../memory_map.html#autotoc_md646',1,'OAM (Object Attribute Memory)'],['../examples_graphics_sprites_simple_sprite.html#autotoc_md1413',1,'OAM (Object Attribute Memory)'],['../oam.html',1,'SNES OAM (Object Attribute Memory)']]],
  ['object_20engine_29',['Object Engine',['../examples_games_mapandobjects.html#autotoc_md948',1,'']]],
  ['object_20engine_20and_20slope_20collision_30',['Object Engine and Slope Collision',['../examples_maps_slopemario.html#autotoc_md1532',1,'']]],
  ['object_20size_20all_206_20snes_20sprite_20size_20modes_31',['Object Size -- All 6 SNES Sprite Size Modes',['../examples_graphics_sprites_object_size.html',1,'examples_graphics_sprites']]],
  ['object_20types_20in_20assembly_32',['2. Register Object Types in Assembly',['../examples_games_mapandobjects.html#autotoc_md953',1,'']]],
  ['objectives_33',['Objectives',['../examples_audio_snesmod_music.html#autotoc_md763',1,'Learning Objectives'],['../examples_graphics_backgrounds_mode1.html#autotoc_md1024',1,'Learning Objectives'],['../examples_graphics_effects_fading.html#autotoc_md1136',1,'Learning Objectives'],['../examples_input_two_players.html#autotoc_md1460',1,'Learning Objectives']]],
  ['objects_34',['Map and Objects',['../examples_games_mapandobjects.html',1,'examples_games']]],
  ['objects_20from_20map_20data_35',['3. Load Objects from Map Data',['../examples_games_mapandobjects.html#autotoc_md954',1,'']]],
  ['objsel_20_242101_36',['Sprite Sizes (OBJSEL $2101)',['../examples_graphics_sprites.html#autotoc_md1399',1,'']]],
  ['objsel_20register_20_242101_37',['OBJSEL Register ($2101)',['../examples_graphics_sprites_object_size.html#autotoc_md1390',1,'']]],
  ['objsel_20sprite_20settings_38',['$2101 - OBJSEL (Sprite Settings)',['../registers.html#autotoc_md693',1,'']]],
  ['observe_39',['Observe',['../examples_basics_aim_target.html#autotoc_md842',1,'What to Observe'],['../examples_basics_fix32_orbit.html#autotoc_md862',1,'What to Observe'],['../examples_memory_sa1_starfield.html#autotoc_md1575',1,'What to Observe']]],
  ['observe_40',['Recipe 5 — Poke and observe',['../tutorial_debugging.html#autotoc_md160',1,'']]],
  ['of_20a_20switch_41',['Why a framework instead of a switch',['../examples_basics_scene_stack.html#autotoc_md881',1,'']]],
  ['of_20bounds_20behaviour_42',['Out-of-bounds behaviour',['../tutorial_mode7.html#autotoc_md289',1,'']]],
  ['of_20bounds_20with_20mode7_5ftransparent_20shows_20the_20backdrop_20not_20a_20layer_43',['🟡 Out-of-bounds with &lt;span class=&quot;tt&quot;&gt;MODE7_TRANSPARENT&lt;/span&gt; shows the backdrop, not a layer',['../tutorial_mode7.html#autotoc_md300',1,'']]],
  ['of_20conduct_44',['Code of Conduct',['../contributing.html#autotoc_md1666',1,'']]],
  ['of_20contents_45',['of Contents',['../snes_graphics_guide.html#autotoc_md513',1,'Table of Contents'],['../snes_sound_guide.html#autotoc_md557',1,'Table of Contents'],['../registers.html#autotoc_md688',1,'Table of Contents']]],
  ['of_20intuitive_46',['🟠 &lt;span class=&quot;tt&quot;&gt;colorMathSetSource&lt;/span&gt; polarity is opposite of intuitive',['../tutorial_colormath.html#autotoc_md147',1,'']]],
  ['of_20overlap_47',['Pushing Out of Overlap',['../tutorial_collision.html#autotoc_md129',1,'']]],
  ['off_20load_20everything_48',['1. Lights Off, Load Everything',['../examples_games_breakout.html#autotoc_md896',1,'']]],
  ['on_49',['7. Lights On',['../examples_text_hello_world.html#autotoc_md1621',1,'']]],
  ['on_20a_20different_20layer_20above_20the_20panel_50',['🟡 Text goes on a &lt;em&gt;different&lt;/em&gt; layer, above the panel',['../tutorial_panel.html#autotoc_md323',1,'']]],
  ['on_20bg1_204bpp_20in_20mode_201_51',['1. Set up text on BG1 (4bpp in Mode 1)',['../examples_graphics_sprites_object_size.html#autotoc_md1385',1,'']]],
  ['on_20bg3_52',['Open chantier — S6 HUD on BG3',['../examples_games_shmup_1942.html#autotoc_md974',1,'']]],
  ['on_20both_20ends_53',['Boundaries are inclusive on both ends',['../tutorial_window.html#autotoc_md422',1,'']]],
  ['on_20channel_200_54',['🟠 Channel 0 vs HDMA on channel 0',['../tutorial_dma.html#autotoc_md176',1,'']]],
  ['on_20divide_20by_20zero_55',['🟠 &lt;span class=&quot;tt&quot;&gt;fixDiv&lt;/span&gt; returns 0 on divide-by-zero',['../tutorial_math.html#autotoc_md276',1,'']]],
  ['on_20first_20boot_20are_20undefined_56',['🔴 SRAM contents on first boot are undefined',['../tutorial_sram.html#autotoc_md388',1,'']]],
  ['on_20hdmasetup_57',['🔴 Bank byte trap on &lt;span class=&quot;tt&quot;&gt;hdmaSetup&lt;/span&gt;',['../tutorial_hdma.html#autotoc_md229',1,'']]],
  ['on_20palette_58',['🟡 OBJ math depends on palette',['../tutorial_colormath.html#autotoc_md151',1,'']]],
  ['on_20snes_59',['How Text Works on SNES',['../examples_text.html#autotoc_md1636',1,'']]],
  ['on_20the_20backdrop_60',['🟡 Colour-math on the backdrop',['../tutorial_colormath.html#autotoc_md149',1,'']]],
  ['on_20the_20snes_61',['on the SNES',['../examples_input_controller.html#autotoc_md1421',1,'How Input Works on the SNES'],['../examples_text_text_test.html#autotoc_md1643',1,'Text Rendering on the SNES'],['../tutorial_math.html#autotoc_md260',1,'Why fixed-point on the SNES']]],
  ['on_20this_20target_20since_20chantier_20a1_62',['🟢 &lt;span class=&quot;tt&quot;&gt;int&lt;/span&gt; and &lt;span class=&quot;tt&quot;&gt;long&lt;/span&gt; sizes are correct on this target (since chantier A1)',['../tutorial_math.html#autotoc_md273',1,'']]],
  ['on_20wh0_20wh1_20requires_20repeat_20mode_63',['🟠 HDMA on &lt;span class=&quot;tt&quot;&gt;WH0&lt;/span&gt;/&lt;span class=&quot;tt&quot;&gt;WH1&lt;/span&gt; requires repeat mode',['../tutorial_window.html#autotoc_md429',1,'']]],
  ['one_20draw_20function_20engine_20resolved_20size_64',['One Draw Function, Engine-Resolved Size',['../tutorial_animation.html#autotoc_md86',1,'']]],
  ['one_20layer_65',['Why This Works with One Layer',['../examples_graphics_effects_parallax_scrolling.html#autotoc_md1270',1,'']]],
  ['one_20layer_20one_20upload_66',['Several panels, one layer, one upload',['../tutorial_panel.html#autotoc_md320',1,'']]],
  ['one_20layer_20only_67',['One Layer Only',['../examples_graphics_backgrounds_mode7.html#autotoc_md1108',1,'']]],
  ['one_20topic_20per_20pr_68',['One topic per PR',['../contributing.html#autotoc_md1674',1,'']]],
  ['one_20upload_69',['Several panels, one layer, one upload',['../tutorial_panel.html#autotoc_md320',1,'']]],
  ['one_20visual_20—_20examples_20graphics_20effects_20gradient_5f9bit_70',['Two channels, one visual — &lt;span class=&quot;tt&quot;&gt;examples/graphics/effects/gradient_9bit&lt;/span&gt;',['../tutorial_hdma.html#autotoc_md225',1,'']]],
  ['one_20way_20and_20second_20layer_20options_71',['One-way and second-layer options',['../tutorial_map.html#autotoc_md253',1,'']]],
  ['only_72',['One Layer Only',['../examples_graphics_backgrounds_mode7.html#autotoc_md1108',1,'']]],
  ['only_20the_20ram_20buffer_20pattern_73',['3. ROM is Read-Only (The RAM Buffer Pattern)',['../examples_games_breakout.html#autotoc_md898',1,'']]],
  ['only_20trap_74',['🔴 The &quot;BG2 is sub-screen-only&quot; trap',['../tutorial_colormath.html#autotoc_md146',1,'']]],
  ['op_20or_20assembly_20errors_75',['Build fails with &quot;unhandled op&quot; or assembly errors',['../getting_started.html#autotoc_md462',1,'']]],
  ['op_20trap_76',['The window logic op trap',['../tutorial_window.html#autotoc_md423',1,'']]],
  ['op_3a_20xxx_77',['Build fails with &quot;unhandled op: XXX&quot;',['../troubleshooting.html#autotoc_md611',1,'']]],
  ['open_20chantier_20—_20s6_20hud_20on_20bg3_78',['Open chantier — S6 HUD on BG3',['../examples_games_shmup_1942.html#autotoc_md974',1,'']]],
  ['open_20snes_79',['speech_synth — the SNES says &quot;OPEN SNES&quot;',['../examples_audio_speech_synth.html',1,'examples_audio']]],
  ['openmpt_80',['Creating Music with OpenMPT',['../tutorial_audio.html#autotoc_md102',1,'']]],
  ['openmpt_20recommended_81',['Using OpenMPT (Recommended)',['../examples_audio_snesmod_music.html#autotoc_md780',1,'']]],
  ['opensnes_82',['OpenSNES',['../tutorial_audio.html#autotoc_md95',1,'Audio Options in OpenSNES'],['../contributing.html',1,'Contributing to OpenSNES'],['../getting_started.html',1,'Getting Started with OpenSNES'],['../troubleshooting.html',1,'Troubleshooting OpenSNES']]],
  ['opensnes_20code_20style_20guide_83',['OpenSNES Code Style Guide',['../code_style.html',1,'index']]],
  ['opensnes_20documentation_84',['OpenSNES Documentation',['../index.html',1,'']]],
  ['opensnes_20examples_85',['OpenSNES Examples',['../examples.html',1,'index']]],
  ['opensnes_20not_20defined_20or_20no_20rule_20to_20make_20target_20common_20mk_86',['&quot;OPENSNES not defined&quot; or &quot;No rule to make target &apos;common.mk&apos;&quot;',['../troubleshooting.html#autotoc_md607',1,'']]],
  ['opensnes_20register_20macros_87',['OpenSNES Register Macros',['../registers.html#autotoc_md740',1,'']]],
  ['opensnes_20sdk_88',['A3. Download OpenSNES SDK',['../getting_started.html#autotoc_md442',1,'']]],
  ['opensnes_20sdk_20convention_89',['OpenSNES SDK convention',['../oam.html#autotoc_md669',1,'']]],
  ['opensnes_20sprite_20functions_90',['Using OpenSNES Sprite Functions',['../tutorial_sprites.html#autotoc_md361',1,'']]],
  ['operations_91',['Common Operations',['../snes_sound_guide.html#autotoc_md604',1,'']]],
  ['operations_20available_92',['Operations available',['../fixed32_8h.html#autotoc_md27',1,'']]],
  ['opposite_20of_20intuitive_93',['🟠 &lt;span class=&quot;tt&quot;&gt;colorMathSetSource&lt;/span&gt; polarity is opposite of intuitive',['../tutorial_colormath.html#autotoc_md147',1,'']]],
  ['opt_20ins_94',['Framework opt-ins',['../index.html#autotoc_md6',1,'']]],
  ['options_95',['smconv Options',['../examples_audio_snesmod_music.html#autotoc_md806',1,'']]],
  ['options_96',['One-way and second-layer options',['../tutorial_map.html#autotoc_md253',1,'']]],
  ['options_20in_20opensnes_97',['Audio Options in OpenSNES',['../tutorial_audio.html#autotoc_md95',1,'']]],
  ['or_20assembly_20errors_98',['Build fails with &quot;unhandled op&quot; or assembly errors',['../getting_started.html#autotoc_md462',1,'']]],
  ['or_20cc65816_20not_20found_99',['Empty &lt;span class=&quot;tt&quot;&gt;compiler/&lt;/span&gt; directories or &quot;cc65816 not found&quot;',['../troubleshooting.html#autotoc_md608',1,'']]],
  ['or_20cc_3a_20command_20not_20found_100',['&quot;clang: command not found&quot; or &quot;cc: command not found&quot;',['../troubleshooting.html#autotoc_md610',1,'']]],
  ['or_20empty_20compiler_20folder_101',['&quot;fatal: repository not found&quot; or empty compiler folder',['../getting_started.html#autotoc_md459',1,'']]],
  ['or_20force_20blank_20are_20silently_20dropped_102',['🔴 VRAM/CGRAM/OAM writes outside VBlank or force blank are silently dropped',['../tutorial_dma.html#autotoc_md173',1,'']]],
  ['or_20linker_20errors_20about_20size_103',['&quot;ROM too large&quot; or linker errors about size',['../troubleshooting.html#autotoc_md624',1,'']]],
  ['or_20no_20rule_20to_20make_20target_20common_20mk_104',['&quot;OPENSNES not defined&quot; or &quot;No rule to make target &apos;common.mk&apos;&quot;',['../troubleshooting.html#autotoc_md607',1,'']]],
  ['organization_105',['Organization',['../code_style.html#autotoc_md509',1,'File Organization'],['../tutorial_animation.html#autotoc_md75',1,'Sprite Sheet Organization']]],
  ['original_106',['original',['../examples_audio_speech_synth.html#autotoc_md837',1,'Register fidelity vs the original'],['../examples_graphics_effects_gradient_9bit.html#autotoc_md1171',1,'Register fidelity vs the original'],['../examples_graphics_effects_hicolor_1792.html#autotoc_md1224',1,'Register fidelity vs the original'],['../examples_graphics_effects_hicolor_hires.html#autotoc_md1230',1,'Register fidelity vs the original'],['../examples_graphics_effects_hires_text.html#autotoc_md1234',1,'Register fidelity vs the original'],['../examples_graphics_effects_mode7_perspective_rotate.html#autotoc_md1240',1,'Register fidelity vs the original'],['../examples_graphics_effects_window_multi_hdma.html#autotoc_md1330',1,'Register fidelity vs the original']]],
  ['original_20a_20true_20story_107',['Why the envelope differs from the original (a true story)',['../examples_audio_pitch_mod.html#autotoc_md751',1,'']]],
  ['original_20measured_20not_20assumed_108',['original measured not assumed',['../examples_graphics_effects_hdma_indirect_gradient.html#autotoc_md1192',1,'Fidelity to the original (measured, not assumed)'],['../examples_graphics_effects_hdma_wave_table.html#autotoc_md1219',1,'Fidelity to the original (measured, not assumed)']]],
  ['out_20fade_20in_109',['Fade Out / Fade In',['../tutorial_game_states.html#autotoc_md186',1,'']]],
  ['out_20full_20to_20black_110',['Fade Out (Full to Black)',['../examples_graphics_effects_fading.html#autotoc_md1147',1,'']]],
  ['out_20of_20bounds_20behaviour_111',['Out-of-bounds behaviour',['../tutorial_mode7.html#autotoc_md289',1,'']]],
  ['out_20of_20bounds_20with_20mode7_5ftransparent_20shows_20the_20backdrop_20not_20a_20layer_112',['🟡 Out-of-bounds with &lt;span class=&quot;tt&quot;&gt;MODE7_TRANSPARENT&lt;/span&gt; shows the backdrop, not a layer',['../tutorial_mode7.html#autotoc_md300',1,'']]],
  ['out_20of_20overlap_113',['Pushing Out of Overlap',['../tutorial_collision.html#autotoc_md129',1,'']]],
  ['output_114',['No audio output',['../examples_audio_snesmod_music.html#autotoc_md799',1,'']]],
  ['outside_20vblank_20or_20force_20blank_20are_20silently_20dropped_115',['🔴 VRAM/CGRAM/OAM writes outside VBlank or force blank are silently dropped',['../tutorial_dma.html#autotoc_md173',1,'']]],
  ['over_116',['Game Over',['../tutorial_game_states.html#autotoc_md192',1,'']]],
  ['over_20100_20bricks_117',['5. Grid Collision (Don&apos;t Loop Over 100 Bricks)',['../examples_games_breakout.html#autotoc_md900',1,'']]],
  ['over_20backgrounds_118',['Mode 1 BG3 High Priority -- HUD Layer Over Backgrounds',['../examples_graphics_backgrounds_mode1_bg3_priority.html',1,'examples_graphics_backgrounds']]],
  ['over_20breakout_119',['Simple Game Over (Breakout)',['../tutorial_game_states.html#autotoc_md193',1,'']]],
  ['over_20tetris_120',['Restart Game Over (Tetris)',['../tutorial_game_states.html#autotoc_md194',1,'']]],
  ['over_20with_20fade_121',['Game Over with Fade',['../tutorial_game_states.html#autotoc_md195',1,'']]],
  ['overflows_20for_20x_20≥_20128_122',['🔴 &lt;span class=&quot;tt&quot;&gt;FIX(x)&lt;/span&gt; overflows for &lt;span class=&quot;tt&quot;&gt;|x| ≥ 128&lt;/span&gt;',['../tutorial_math.html#autotoc_md274',1,'']]],
  ['overlap_123',['Overlap',['../examples_games_breakout.html#autotoc_md897',1,'2. The VRAM Map — A Deliberate Overlap'],['../tutorial_collision.html#autotoc_md129',1,'Pushing Out of Overlap']]],
  ['overlap_20test_124',['Basic Overlap Test',['../tutorial_collision.html#autotoc_md118',1,'']]],
  ['overlay_20—_20examples_20graphics_20effects_20transparency_125',['Additive cloud overlay — &lt;span class=&quot;tt&quot;&gt;examples/graphics/effects/transparency&lt;/span&gt;',['../tutorial_colormath.html#autotoc_md143',1,'']]],
  ['overview_126',['Overview',['../memory_map.html#autotoc_md641',1,'Address Space Overview'],['../snes_sound_guide.html#autotoc_md559',1,'Architecture Overview'],['../dma_8h.html#autotoc_md23',1,'DMA Overview'],['../examples_graphics_backgrounds_mode1.html#autotoc_md1031',1,'Mode 1 Overview'],['../background_8h.html#autotoc_md13',1,'Overview'],['../collision_8h.html#autotoc_md14',1,'Overview'],['../fixed32_8h.html#autotoc_md26',1,'Overview'],['../math_8h.html#autotoc_md42',1,'Overview'],['../hardware_overview.html',1,'SNES Hardware Overview'],['../examples_audio_snesmod_music.html#autotoc_md770',1,'SNESMOD Overview'],['../sram_8h.html#autotoc_md60',1,'SRAM Overview']]],
  ['overwrite_20tile_20graphics_127',['Approach 2: Overwrite Tile Graphics',['../tutorial_animation.html#autotoc_md89',1,'']]],
  ['own_20level_128',['Making Your Own Level',['../examples_maps_tiled.html#autotoc_md1548',1,'']]],
  ['own_20project_129',['A5. Create Your Own Project',['../getting_started.html#autotoc_md444',1,'']]],
  ['owner_20listening_20test_20driven_130',['The debugging archaeology (all owner-listening-test driven)',['../examples_audio_speech_synth.html#autotoc_md838',1,'']]]
];
