var searchData=
[
  ['s_0',['The two flags that decide everything: &lt;span class=&quot;tt&quot;&gt;-u&lt;/span&gt; and &lt;span class=&quot;tt&quot;&gt;-s&lt;/span&gt;',['../tools_gfx4snes.html#the-two-flags-that-decide-everything--u-and--s',1,'']]],
  ['s_20map_1',['Controls (krom&apos;s map)',['../examples_mode7_perspective_rotate.html#controls-kroms-map',1,'']]],
  ['s_20must_20match_20the_20sprite_20size_2',['Converting a sheet: &lt;span class=&quot;tt&quot;&gt;-s&lt;/span&gt; must match the sprite size',['../tutorial_sprites.html#converting-a-sheet--s-must-match-the-sprite-size',1,'']]],
  ['s_20next_3',['s Next',['../getting_started.html#whats-next',1,'What&apos;s Next?'],['../examples_audio_snesmod_music.html#whats-next-1',1,'What&apos;s Next?'],['../examples_audio_snesmod_sfx.html#whats-next-2',1,'What&apos;s Next?'],['../examples_backgrounds_mode1.html#whats-next-3',1,'What&apos;s Next?'],['../examples_basics_collision_demo.html#whats-next-4',1,'What&apos;s Next?'],['../examples_color_transparency.html#whats-next-5',1,'What&apos;s Next?'],['../examples_input_two_players.html#whats-next-6',1,'What&apos;s Next?'],['../examples_transitions_fading.html#whats-next-7',1,'What&apos;s Next?']]],
  ['s_20spc_20dump_4',['Debugging audio: luna&apos;s spc-dump',['../tutorial_audio.html#debugging-audio-lunas-spc-dump',1,'']]],
  ['s_20still_20missing_3a_20pow_20exp_20log_5',['What&apos;s still missing: &lt;span class=&quot;tt&quot;&gt;pow&lt;/span&gt;, &lt;span class=&quot;tt&quot;&gt;exp&lt;/span&gt;, &lt;span class=&quot;tt&quot;&gt;log&lt;/span&gt;',['../tutorial_math.html#whats-still-missing-pow-exp-log',1,'']]],
  ['s5_202_6',['Bullet despawn fix (S5.2)',['../examples_games_shmup_1942.html#bullet-despawn-fix-s52',1,'']]],
  ['s6_20hud_20on_20bg3_7',['Open chantier — S6 HUD on BG3',['../examples_games_shmup_1942.html#open-chantier--s6-hud-on-bg3',1,'']]],
  ['sa_201_8',['What Is SA-1?',['../tutorial_sa1.html#what-is-sa-1',1,'']]],
  ['sa_201_20assembly_20tips_9',['SA-1 Assembly Tips',['../tutorial_sa1.html#sa-1-assembly-tips',1,'']]],
  ['sa_201_20boot_20code_10',['2. Write Your SA-1 Boot Code',['../tutorial_sa1.html#autotoc_md2-write-your-sa-1-boot-code',1,'']]],
  ['sa_201_20can_20t_20do_11',['What SA-1 Can&apos;t Do',['../tutorial_sa1.html#what-sa-1-cant-do',1,'']]],
  ['sa_201_20cartridge_12',['SA-1 Cartridge',['../memory_map.html#sa-1-cartridge',1,'']]],
  ['sa_201_20chips_3a_20covered_20natively_20resolved_20by_20the_20luna_20migration_13',['🟢 SuperFX / SA-1 chips: covered natively (resolved by the luna migration)',['../KNOWN_LIMITATIONS.html#autotoc_md-superfx--sa-1-chips-covered-natively-resolved-by-the-luna-migration',1,'']]],
  ['sa_201_20coprocessor_14',['SA-1 Coprocessor',['../examples_by_category.html#sa-1-coprocessor',1,'']]],
  ['sa_201_20enhancement_20chip_20tutorial_15',['SA-1 Enhancement Chip Tutorial',['../tutorial_sa1.html',1,'index']]],
  ['sa_201_20hello_20world_16',['SA-1 Hello World',['../examples_chips_sa1_hello.html',1,'examples_chips']]],
  ['sa_201_20in_20your_20makefile_17',['1. Enable SA-1 in Your Makefile',['../tutorial_sa1.html#autotoc_md1-enable-sa-1-in-your-makefile',1,'']]],
  ['sa_201_20registers_20_242200_20_24230e_18',['SA-1 Registers ($2200-$230E)',['../registers.html#sa-1-registers-2200-230e',1,'']]],
  ['sa_201_20siwp_20ciwp_20write_20protection_20polarity_20resolved_3a_20bit_201_20write_20enable_19',['🟢 SA-1 SIWP/CIWP write-protection polarity (resolved: bit=1 = write-enable)',['../KNOWN_LIMITATIONS.html#autotoc_md-sa-1-siwpciwp-write-protection-polarity-resolved-bit1--write-enable',1,'']]],
  ['sa_201_20starfield_20murmuration_20',['SA-1 Starfield (Murmuration)',['../examples_chips_sa1_starfield.html',1,'examples_chips']]],
  ['safe_21',['safe',['../tutorial_dsp1.html#autotoc_md-not-nmi-callback-safe',1,'🟡 Not NMI-callback-safe'],['../tutorial_dma.html#when-vramcgramoam-writes-are-safe',1,'When VRAM/CGRAM/OAM writes are safe']]],
  ['safe_20in_20nmi_22',['🟡 WRAM data port &lt;span class=&quot;tt&quot;&gt;$2180&lt;/span&gt;–&lt;span class=&quot;tt&quot;&gt;$2183&lt;/span&gt; is NOT safe in NMI',['../tutorial_dma.html#autotoc_md-wram-data-port-21802183-is-not-safe-in-nmi',1,'']]],
  ['safe_20inside_20nmiset_20callbacks_23',['🟡 &lt;span class=&quot;tt&quot;&gt;fixMul()&lt;/span&gt; / &lt;span class=&quot;tt&quot;&gt;fixLerp()&lt;/span&gt; are not safe inside nmiSet() callbacks',['../KNOWN_LIMITATIONS.html#autotoc_md-fixmul--fixlerp-are-not-safe-inside-nmiset-callbacks',1,'']]],
  ['same_24',['What is the same',['../migrating_pvsneslib.html#what-is-the-same',1,'']]],
  ['sample_25',['How the WAV becomes a sample',['../examples_audio_sfx_from_wav.html#how-the-wav-becomes-a-sample',1,'']]],
  ['sample_20directory_26',['Sample Directory',['../snes_sound_guide.html#sample-directory',1,'']]],
  ['sample_20format_27',['BRR Sample Format',['../snes_sound_guide.html#brr-sample-format',1,'']]],
  ['sample_20preparation_28',['Sample Preparation',['../snes_sound_guide.html#sample-preparation',1,'']]],
  ['sample_20provenance_29',['Sample provenance',['../examples_audio_pitch_mod.html#sample-provenance',1,'Sample provenance'],['../examples_audio_soundboard.html#sample-provenance-1',1,'Sample provenance']]],
  ['sample_20sizes_30',['Typical Sample Sizes',['../snes_sound_guide.html#typical-sample-sizes',1,'']]],
  ['sample_20sources_31',['Sample Sources',['../snes_sound_guide.html#sample-sources',1,'']]],
  ['samples_32',['samples',['../examples_audio_play_noise.html',1,'play_noise — a drum kit with zero samples'],['../tools_wav2brr.html',1,'wav2brr — WAV to BRR sound samples']]],
  ['samples_20and_20effects_20from_20pure_20c_33',['The audio module (v2) — samples and effects from pure C',['../tutorial_audio.html#the-audio-module-v2--samples-and-effects-from-pure-c',1,'']]],
  ['samples_20from_20wav_20wav2brr_34',['One-shot samples from WAV (wav2brr)',['../tutorial_audio.html#audio_wav2brr',1,'']]],
  ['saturation_20interact_35',['🟠 Half-mode and saturation interact',['../tutorial_colormath.html#autotoc_md-half-mode-and-saturation-interact',1,'']]],
  ['save_36',['save',['../tutorial_sram.html#delete-save',1,'&quot;Delete save&quot;'],['../tutorial_sram.html#the-minimum-viable-save',1,'The minimum viable save']]],
  ['save_20game_20sram_20persistence_37',['Save Game -- SRAM Persistence',['../examples_memory_save_game.html',1,'examples_memory']]],
  ['save_20slots_38',['Save Slots',['../examples_memory_save_game.html#save-slots',1,'']]],
  ['save_20structure_39',['1. Define a save structure',['../examples_memory_save_game.html#autotoc_md1-define-a-save-structure',1,'']]],
  ['save_20to_20sram_40',['2. Save to SRAM',['../examples_memory_save_game.html#autotoc_md2-save-to-sram',1,'']]],
  ['save_20tutorial_41',['SRAM Save Tutorial',['../tutorial_sram.html',1,'index']]],
  ['save_20x_20through_20a_42',['No &lt;span class=&quot;tt&quot;&gt;stx.l&lt;/span&gt; — Save X Through A',['../tutorial_sa1.html#no-stxl--save-x-through-a',1,'']]],
  ['saves_43',['Multi-slot saves',['../tutorial_sram.html#multi-slot-saves',1,'']]],
  ['says_20open_20snes_44',['speech_synth — the SNES says &quot;OPEN SNES&quot;',['../examples_audio_speech_synth.html',1,'examples_audio']]],
  ['sc_5f64x64_20tilemap_20layout_45',['SC_64x64 Tilemap Layout',['../examples_maps_dynamic_map.html#sc_64x64-tilemap-layout',1,'']]],
  ['scale_46',['8.8 Fixed-Point Scale',['../examples_mode7_rotate_scale.html#autotoc_md88-fixed-point-scale',1,'']]],
  ['scale_20before_20angle_47',['🟡 Set scale BEFORE angle',['../tutorial_mode7.html#autotoc_md-set-scale-before-angle',1,'']]],
  ['scaling_48',['Scaling',['../examples_mode7_rotate_scale.html',1,'Mode 7 -- Rotation and Scaling'],['../examples_mode7_perspective.html#per-scanline-scaling',1,'Per-Scanline Scaling']]],
  ['scaling_49',['Squash and stretch without scaling',['../craft_game_feel.html#squash-and-stretch-without-scaling',1,'']]],
  ['scaling_20—_20examples_20mode7_20rotate_5fscale_50',['Basic rotation + scaling — &lt;span class=&quot;tt&quot;&gt;examples/mode7/rotate_scale&lt;/span&gt;',['../tutorial_mode7.html#basic-rotation--scaling--examplesmode7rotate_scale',1,'']]],
  ['scanline_51',['scanline',['../examples_mode7_perspective_rotate.html',1,'Mode 7 rotating perspective — the full matrix, per scanline'],['../examples_windows_window_multi_hdma.html',1,'Multi-window HDMA — both windows animated per scanline']]],
  ['scanline_20—_20examples_20windows_20window_5fmulti_5fhdma_52',['Both windows per scanline — &lt;span class=&quot;tt&quot;&gt;examples/windows/window_multi_hdma&lt;/span&gt;',['../tutorial_window.html#both-windows-per-scanline--exampleswindowswindow_multi_hdma',1,'']]],
  ['scanline_200_20hidden_20by_20the_20lib_53',['🟢 Vertical scroll is off by one: the PPU never outputs scanline 0 (hidden by the lib)',['../KNOWN_LIMITATIONS.html#autotoc_md-vertical-scroll-is-off-by-one-the-ppu-never-outputs-scanline-0-hidden-by-the-lib',1,'']]],
  ['scanline_20limits_20critical_54',['Scanline Limits (Critical!)',['../snes_graphics_guide.html#scanline-limits-critical',1,'']]],
  ['scanline_20matrix_3a_20rotating_20perspective_55',['Per-scanline matrix: rotating perspective',['../tutorial_mode7.html#per-scanline-matrix-rotating-perspective',1,'']]],
  ['scanline_20quirk_56',['Sprite Y +1 Scanline Quirk',['../oam.html#sprite-y-1-scanline-quirk',1,'']]],
  ['scanline_20scaling_57',['Per-Scanline Scaling',['../examples_mode7_perspective.html#per-scanline-scaling',1,'']]],
  ['scanline_20scroll_58',['HDMA Parallax (Per-Scanline Scroll)',['../tutorial_scrolling.html#hdma-parallax-per-scanline-scroll',1,'']]],
  ['scanline_20wave_20distortion_20—_20examples_20hdma_20hdma_5fwave_59',['Per-scanline wave distortion — &lt;span class=&quot;tt&quot;&gt;examples/hdma/hdma_wave&lt;/span&gt;',['../tutorial_hdma.html#per-scanline-wave-distortion--exampleshdmahdma_wave',1,'']]],
  ['scene_20at_20once_60',['shadow_tint — recolour a whole scene at once',['../examples_color_shadow_tint.html',1,'examples_color']]],
  ['scene_20changes_20—_20fades_20and_20dissolves_61',['Punctuate scene changes — fades and dissolves',['../craft_game_feel.html#punctuate-scene-changes--fades-and-dissolves',1,'']]],
  ['scene_20module_62',['The scene stack (recommended) — &lt;span class=&quot;tt&quot;&gt;scene&lt;/span&gt; module',['../tutorial_game_states.html#the-scene-stack-recommended--scene-module',1,'']]],
  ['scene_20stack_63',['Scene Stack',['../examples_basics_scene_stack.html',1,'examples_basics']]],
  ['scene_20stack_20recommended_20—_20scene_20module_64',['The scene stack (recommended) — &lt;span class=&quot;tt&quot;&gt;scene&lt;/span&gt; module',['../tutorial_game_states.html#the-scene-stack-recommended--scene-module',1,'']]],
  ['scene_20struct_65',['The Scene struct',['../examples_basics_scene_stack.html#the-scene-struct',1,'']]],
  ['scene_20transition_20pattern_66',['Scene Transition Pattern',['../examples_transitions_fading.html#scene-transition-pattern',1,'']]],
  ['scenes_67',['🟡 Window state survives between scenes',['../tutorial_window.html#autotoc_md-window-state-survives-between-scenes',1,'']]],
  ['scope_68',['Scope',['../tools_aseprite2snes.html#scope',1,'Scope'],['../examples_input_superscope.html',1,'Super Scope']]],
  ['scope_20a_20first_20game_20you_20can_20finish_69',['Scope a first game you can finish',['../craft_planning.html#scope-a-first-game-you-can-finish',1,'']]],
  ['screen_70',['Screen',['../examples_games_likemario.html#autotoc_md1-the-world-is-bigger-than-the-screen',1,'1. The World Is Bigger Than the Screen'],['../examples_color_transparency.html#color-math-main-screen--sub-screen',1,'Color Math: Main Screen + Sub Screen'],['../examples_input_two_players.html#exercise-4-split-screen',1,'Exercise 4: Split Screen'],['../colormath_8h.html#main-screen-vs-sub-screen',1,'Main Screen vs Sub Screen'],['../tutorial_game_states.html#pause-screen',1,'Pause Screen']]],
  ['screen_71',['screen',['../craft_planning.html#autotoc_md1-vram--64-kb-shared-by-everything-on-screen',1,'1. VRAM — 64 KB, shared by everything on screen'],['../api_index.html#getting-something-on-screen',1,'Getting something on screen'],['../examples_sprites.html#reference--oam-in-one-screen',1,'Reference — OAM in one screen'],['../learning_path.html#stage-1--can-i-put-something-on-screen',1,'Stage 1 — &quot;Can I put something on screen?&quot;'],['../examples_audio.html#the-idea-in-one-screen',1,'The idea in one screen'],['../examples_backgrounds.html#the-idea-in-one-screen-1',1,'The idea in one screen'],['../examples_color.html#the-idea-in-one-screen-2',1,'The idea in one screen'],['../examples_hdma.html#the-idea-in-one-screen-3',1,'The idea in one screen'],['../examples_input.html#the-idea-in-one-screen-4',1,'The idea in one screen'],['../examples_maps.html#the-idea-in-one-screen-5',1,'The idea in one screen'],['../examples_mode7.html#the-idea-in-one-screen-6',1,'The idea in one screen'],['../examples_scrolling.html#the-idea-in-one-screen-7',1,'The idea in one screen'],['../examples_transitions.html#the-idea-in-one-screen-8',1,'The idea in one screen'],['../examples_windows.html#the-idea-in-one-screen-9',1,'The idea in one screen'],['../examples_chips.html#the-two-chips-in-one-screen',1,'The two chips, in one screen']]],
  ['screen_20centre_72',['🟡 Centre default is the tilemap centre, not the screen centre',['../tutorial_mode7.html#autotoc_md-centre-default-is-the-tilemap-centre-not-the-screen-centre',1,'']]],
  ['screen_20crash_73',['Runtime Issues (Black Screen / Crash)',['../troubleshooting.html#runtime-issues-black-screen--crash',1,'']]],
  ['screen_20enable_74',['Screen Enable',['../registers.html#autotoc_md212c---tm-main-screen-enable',1,'$212C - TM (Main Screen Enable)'],['../registers.html#autotoc_md212d---ts-sub-screen-enable',1,'$212D - TS (Sub Screen Enable)'],['../registers.html#screen-enable',1,'Screen Enable']]],
  ['screen_20implementation_75',['Title Screen Implementation',['../tutorial_game_states.html#title-screen-implementation',1,'']]],
  ['screen_20is_20black_76',['ROM loads but screen is black',['../troubleshooting.html#rom-loads-but-screen-is-black',1,'']]],
  ['screen_20only_20trap_77',['🔴 The &quot;BG2 is sub-screen-only&quot; trap',['../tutorial_colormath.html#autotoc_md-the-bg2-is-sub-screen-only-trap',1,'']]],
  ['screen_20shake_20—_20nudge_20the_20scroll_78',['Screen shake — nudge the scroll',['../craft_game_feel.html#screen-shake--nudge-the-scroll',1,'']]],
  ['screen_20sub_20screen_79',['Color Math: Main Screen + Sub Screen',['../examples_color_transparency.html#color-math-main-screen--sub-screen',1,'']]],
  ['screen_20vs_20sub_20screen_80',['Main Screen vs Sub Screen',['../colormath_8h.html#main-screen-vs-sub-screen',1,'']]],
  ['screen_20when_20running_20rom_81',['Black screen when running ROM',['../getting_started.html#black-screen-when-running-rom',1,'']]],
  ['screen_20with_20hdma_82',['1. Split-screen with HDMA',['../examples_mode7_perspective.html#autotoc_md1-split-screen-with-hdma',1,'']]],
  ['scroll_83',['Scroll',['../registers.html#background-scroll',1,'Background Scroll'],['../examples_scrolling_continuous_scroll.html',1,'Continuous Scroll'],['../tutorial_scrolling.html#hdma-parallax-per-scanline-scroll',1,'HDMA Parallax (Per-Scanline Scroll)'],['../examples_maps_map_scroll.html',1,'Map Scroll'],['../examples_scrolling_mixed_scroll.html',1,'Mixed Scroll']]],
  ['scroll_84',['Screen shake — nudge the scroll',['../craft_game_feel.html#screen-shake--nudge-the-scroll',1,'']]],
  ['scroll_20a_20message_85',['Scroll a message',['../examples_text_scroll_message.html',1,'examples_text']]],
  ['scroll_20already_20has_20the_201_86',['Trap 4: vertical scroll already has the -1',['../migrating_pvsneslib.html#trap-4-vertical-scroll-already-has-the--1',1,'']]],
  ['scroll_20and_20mode_207_20matrix_20share_20one_20write_20twice_20latch_87',['🟡 BG1 scroll and Mode 7 matrix share one write-twice latch',['../KNOWN_LIMITATIONS.html#autotoc_md-bg1-scroll-and-mode-7-matrix-share-one-write-twice-latch',1,'']]],
  ['scroll_20and_20the_20mode_207_20registers_20share_20one_20write_20twice_20latch_88',['🟡 BG1 scroll and the Mode 7 registers share one write-twice latch',['../tutorial_mode7.html#autotoc_md-bg1-scroll-and-the-mode-7-registers-share-one-write-twice-latch',1,'']]],
  ['scroll_20bg1_89',['4. Auto-Scroll BG1',['../examples_scrolling_mixed_scroll.html#autotoc_md4-auto-scroll-bg1',1,'']]],
  ['scroll_20can_20corrupt_20mode_207_20writes_20shared_20latch_90',['🟡 HDMA on BG1 scroll can corrupt Mode 7 writes (shared latch)',['../tutorial_hdma.html#autotoc_md-hdma-on-bg1-scroll-can-corrupt-mode-7-writes-shared-latch',1,'']]],
  ['scroll_20from_20bg3_91',['mode2 — offset-per-tile: per-column scroll from BG3',['../examples_backgrounds_mode2.html',1,'examples_backgrounds']]],
  ['scroll_20is_20off_20by_20one_3a_20the_20ppu_20never_20outputs_20scanline_200_20hidden_20by_20the_20lib_92',['🟢 Vertical scroll is off by one: the PPU never outputs scanline 0 (hidden by the lib)',['../KNOWN_LIMITATIONS.html#autotoc_md-vertical-scroll-is-off-by-one-the-ppu-never-outputs-scanline-0-hidden-by-the-lib',1,'']]],
  ['scroll_20pattern_93',['2. The Threshold Scroll Pattern',['../examples_scrolling_continuous_scroll.html#autotoc_md2-the-threshold-scroll-pattern',1,'']]],
  ['scroll_20registers_94',['$210D-$2114 - BGnHOFS/BGnVOFS (Scroll Registers)',['../registers.html#autotoc_md210d-2114---bgnhofsbgnvofs-scroll-registers',1,'']]],
  ['scroll_20registers_20require_20repeat_20mode_95',['IMPORTANT: Scroll Registers Require Repeat Mode',['../hdma_8h.html#important-scroll-registers-require-repeat-mode',1,'']]],
  ['scroll_20static_20moving_20layers_96',['Mixed Scroll (Static + Moving Layers)',['../tutorial_scrolling.html#mixed-scroll-static--moving-layers',1,'']]],
  ['scroll_20table_97',['HDMA Scroll Table',['../examples_scrolling_parallax_scroll.html#hdma-scroll-table',1,'']]],
  ['scroll_20updates_20via_20bgsetscroll_20dirty_20flags_98',['3. Scroll Updates via bgSetScroll Dirty Flags',['../examples_scrolling_continuous_scroll.html#autotoc_md3-scroll-updates-via-bgsetscroll-dirty-flags',1,'']]],
  ['scroll_20values_99',['The camera &lt;em&gt;is&lt;/em&gt; your scroll values',['../craft_camera.html#the-camera-is-your-scroll-values',1,'']]],
  ['scroller_100',['The minimum viable scroller',['../tutorial_map.html#the-minimum-viable-scroller',1,'']]],
  ['scrolling_101',['Scrolling',['../examples_mode7_perspective.html#autotoc_md3-scrolling',1,'3. Scrolling'],['../tutorial_graphics.html#background-scrolling',1,'Background Scrolling'],['../tutorial_scrolling.html#basic-bg-scrolling',1,'Basic BG Scrolling'],['../tutorial_scrolling.html#continuous--infinite-scrolling',1,'Continuous / Infinite Scrolling'],['../tutorial_scrolling.html#d-pad-controlled-scrolling',1,'D-PAD Controlled Scrolling'],['../examples_scrolling_mixed_scroll.html#independent-background-scrolling',1,'Independent Background Scrolling'],['../examples_scrolling_parallax_scroll.html',1,'Parallax Scrolling'],['../tutorial_graphics.html#parallax-scrolling',1,'Parallax Scrolling'],['../tutorial_scrolling.html#parallax-scrolling-1',1,'Parallax Scrolling'],['../examples_scrolling.html',1,'Scrolling'],['../examples_by_category.html#scrolling',1,'Scrolling']]],
  ['scrolling_20—_20examples_20scrolling_20parallax_5fscroll_102',['Parallax scrolling — &lt;span class=&quot;tt&quot;&gt;examples/scrolling/parallax_scroll&lt;/span&gt;',['../tutorial_hdma.html#parallax-scrolling--examplesscrollingparallax_scroll',1,'']]],
  ['scrolling_20and_20effects_103',['Level 3 &amp;ndash; Scrolling and Effects',['../examples.html#level-3----scrolling-and-effects',1,'']]],
  ['scrolling_20is_20jerky_104',['Scrolling is jerky',['../troubleshooting.html#scrolling-is-jerky',1,'']]],
  ['scrolling_20maps_105',['Scrolling maps',['../tutorial_map.html',1,'index']]],
  ['scrolling_20parallax_20tutorial_106',['Scrolling &amp;amp; Parallax Tutorial',['../tutorial_scrolling.html',1,'index']]],
  ['scrolling_20parallax_5fscroll_107',['Parallax scrolling — &lt;span class=&quot;tt&quot;&gt;examples/scrolling/parallax_scroll&lt;/span&gt;',['../tutorial_hdma.html#parallax-scrolling--examplesscrollingparallax_scroll',1,'']]],
  ['scrolling_20works_108',['How BG Scrolling Works',['../tutorial_scrolling.html#how-bg-scrolling-works',1,'']]],
  ['sdk_109',['A3. Download OpenSNES SDK',['../getting_started.html#a3-download-opensnes-sdk',1,'']]],
  ['sdk_20bugs_20this_20port_20surfaced_110',['Two SDK bugs this port surfaced',['../examples_color_hicolor_1792.html#two-sdk-bugs-this-port-surfaced',1,'']]],
  ['sdk_20convention_111',['OpenSNES SDK convention',['../oam.html#opensnes-sdk-convention',1,'']]],
  ['sdk_20developer_112',['Path B: SDK Developer',['../getting_started.html#path-b-sdk-developer',1,'']]],
  ['seamless_20wrapping_113',['64x32 Tilemap for Seamless Wrapping',['../examples_scrolling_parallax_scroll.html#autotoc_md64x32-tilemap-for-seamless-wrapping',1,'']]],
  ['second_20layer_114',['Exercise 1: Add a Second Layer',['../examples_backgrounds_mode1.html#exercise-1-add-a-second-layer',1,'']]],
  ['second_20layer_20options_115',['One-way and second-layer options',['../tutorial_map.html#one-way-and-second-layer-options',1,'']]],
  ['seconds_116',['ROM runs but crashes after a few seconds',['../troubleshooting.html#rom-runs-but-crashes-after-a-few-seconds',1,'']]],
  ['see_117',['Understanding what you see',['../examples_backgrounds_mode5_hires.html#understanding-what-you-see',1,'']]],
  ['see_20also_118',['See Also',['../oam.html#see-also-13',1,'See Also'],['../examples_sprites_aseprite_pipeline.html#see-also-16',1,'See Also']]],
  ['see_20also_119',['See also',['../tutorial_colormath.html#see-also',1,'See also'],['../tutorial_dma.html#see-also-1',1,'See also'],['../tutorial_dsp1.html#see-also-2',1,'See also'],['../tutorial_far_ram.html#see-also-3',1,'See also'],['../tutorial_hdma.html#see-also-4',1,'See also'],['../tutorial_map.html#see-also-5',1,'See also'],['../tutorial_math.html#see-also-6',1,'See also'],['../tutorial_mode7.html#see-also-7',1,'See also'],['../tutorial_mosaic.html#see-also-8',1,'See also'],['../tutorial_panel.html#see-also-9',1,'See also'],['../tutorial_profiling.html#see-also-10',1,'See also'],['../tutorial_sram.html#see-also-11',1,'See also'],['../tutorial_window.html#see-also-12',1,'See also'],['../examples_basics_aim_target.html#see-also-14',1,'See also'],['../examples_basics_fix32_orbit.html#see-also-15',1,'See also']]],
  ['see_20it_20in_20practice_120',['See it in practice',['../tools_gfx4snes.html#see-it-in-practice',1,'See it in practice'],['../tools_palplan.html#see-it-in-practice-1',1,'See it in practice'],['../tools_smconv.html#see-it-in-practice-2',1,'See it in practice'],['../tools_tmx2snes.html#see-it-in-practice-3',1,'See it in practice'],['../tools_wav2brr.html#see-it-in-practice-4',1,'See it in practice']]],
  ['seed_20matters_121',['Why Seed Matters',['../examples_basics_random.html#why-seed-matters',1,'']]],
  ['selecting_20the_20clip_20and_20ticking_122',['Selecting the Clip and Ticking',['../tutorial_animation.html#selecting-the-clip-and-ticking',1,'']]],
  ['selection_123',['Palette Selection',['../snes_graphics_guide.html#palette-selection',1,'']]],
  ['self_20review_20checklist_124',['Self-review checklist',['../contributing.html#self-review-checklist',1,'']]],
  ['semantics_125',['Push/pop semantics',['../examples_basics_scene_stack.html#pushpop-semantics',1,'']]],
  ['semantics_20match_20the_20w65816_20target_126',['🟢 &lt;span class=&quot;tt&quot;&gt;int&lt;/span&gt; and &lt;span class=&quot;tt&quot;&gt;long&lt;/span&gt; sizes AND semantics match the w65816 target',['../KNOWN_LIMITATIONS.html#autotoc_md-int-and-long-sizes-and-semantics-match-the-w65816-target',1,'']]],
  ['sensitivity_127',['Mouse Sensitivity',['../examples_input_mouse.html#mouse-sensitivity',1,'']]],
  ['sep_128',['Explicit &lt;span class=&quot;tt&quot;&gt;.ACCU&lt;/span&gt; After Every &lt;span class=&quot;tt&quot;&gt;rep&lt;/span&gt;/&lt;span class=&quot;tt&quot;&gt;sep&lt;/span&gt;',['../tutorial_sa1.html#explicit-accu-after-every-repsep',1,'']]],
  ['separate_20palettes_129',['Separate Palettes',['../examples_input_two_players.html#separate-palettes',1,'']]],
  ['sequencing_130',['🟠 Double-write register sequencing',['../tutorial_mode7.html#autotoc_md-double-write-register-sequencing',1,'']]],
  ['sequencing_20during_20hdma_131',['🟡 Boundary register sequencing during HDMA',['../tutorial_window.html#autotoc_md-boundary-register-sequencing-during-hdma',1,'']]],
  ['set_20scale_20before_20angle_132',['🟡 Set scale BEFORE angle',['../tutorial_mode7.html#autotoc_md-set-scale-before-angle',1,'']]],
  ['set_20up_20background_133',['2. Set Up Background',['../examples_backgrounds_mode1.html#autotoc_md2-set-up-background',1,'']]],
  ['set_20up_20oam_20directly_134',['3. Set Up OAM Directly',['../examples_input_mouse.html#autotoc_md3-set-up-oam-directly',1,'']]],
  ['set_20up_20sprites_20via_20the_20oambuffer_135',['2. Set up sprites via the oambuffer',['../examples_sprites_dynamic_sprite.html#autotoc_md2-set-up-sprites-via-the-oambuffer',1,'']]],
  ['set_20up_20text_20on_20bg1_204bpp_20in_20mode_201_136',['1. Set up text on BG1 (4bpp in Mode 1)',['../examples_sprites_sprite_sizes.html#autotoc_md1-set-up-text-on-bg1-4bpp-in-mode-1',1,'']]],
  ['set_20up_20three_20background_20layers_137',['1. Set up three background layers',['../examples_backgrounds_mode1_bg3_priority.html#autotoc_md1-set-up-three-background-layers',1,'']]],
  ['setbrightness_200_138',['🔴 &lt;span class=&quot;tt&quot;&gt;panelFlush&lt;/span&gt; uploads under forced blank — do not do it yourself with &lt;span class=&quot;tt&quot;&gt;setBrightness(0)&lt;/span&gt;',['../tutorial_panel.html#autotoc_md-panelflush-uploads-under-forced-blank--do-not-do-it-yourself-with-setbrightness0',1,'']]],
  ['setini_139',['Hi-res and interlace (Modes 5/6, SETINI)',['../tutorial_graphics.html#hi-res-and-interlace-modes-56-setini',1,'']]],
  ['setscreenon_140',['🔴 &lt;span class=&quot;tt&quot;&gt;mapLoad()&lt;/span&gt; must run before &lt;span class=&quot;tt&quot;&gt;setScreenOn()&lt;/span&gt;',['../tutorial_map.html#autotoc_md-mapload-must-run-before-setscreenon',1,'']]],
  ['setscreenon_20is_20always_20last_141',['Trap 2: &lt;span class=&quot;tt&quot;&gt;setScreenOn()&lt;/span&gt; is always last',['../migrating_pvsneslib.html#trap-2-setscreenon-is-always-last',1,'']]],
  ['setting_20a_20sprite_142',['Setting a Sprite',['../tutorial_sprites.html#setting-a-sprite',1,'']]],
  ['setting_20oam_20address_143',['Setting OAM Address',['../oam.html#setting-oam-address',1,'']]],
  ['setting_20palettes_144',['Setting Palettes',['../tutorial_graphics.html#setting-palettes',1,'']]],
  ['setting_20up_20a_20dynamic_20sprite_145',['Setting Up a Dynamic Sprite',['../tutorial_animation.html#setting-up-a-dynamic-sprite',1,'']]],
  ['setting_20up_20graphics_146',['Setting Up Graphics',['../tutorial_graphics.html#setting-up-graphics',1,'']]],
  ['setting_20up_20memory_147',['Example: Setting Up Memory',['../memory_map.html#example-setting-up-memory',1,'']]],
  ['setting_20up_20the_20hdma_20channel_148',['4. Setting Up the HDMA Channel',['../examples_hdma_hdma_wave.html#autotoc_md4-setting-up-the-hdma-channel',1,'']]],
  ['setting_20up_20the_20ppu_149',['3. Setting Up the PPU',['../examples_fundamentals_text_glyphs.html#autotoc_md3-setting-up-the-ppu',1,'']]],
  ['setting_20up_20tilemaps_150',['Setting Up Tilemaps',['../tutorial_graphics.html#setting-up-tilemaps',1,'']]],
  ['settings_151',['$2101 - OBJSEL (Sprite Settings)',['../registers.html#autotoc_md2101---objsel-sprite-settings',1,'']]],
  ['setup_152',['Setup',['../examples_input_superscope.html#autotoc_md5-direct-oam-setup',1,'5. Direct OAM Setup'],['../examples_backgrounds_mode1.html#basic-setup',1,'Basic Setup'],['../tutorial_graphics.html#example-complete-background-setup',1,'Example: Complete Background Setup'],['../examples_sprites_dynamic_sprite.html#force-blank-for-initial-setup',1,'Force Blank for Initial Setup'],['../examples_scrolling_parallax_scroll.html#hdma-setup',1,'HDMA Setup'],['../tutorial_audio.html#setup',1,'Setup'],['../tutorial_debugging.html#setup-1',1,'Setup'],['../tutorial_superfx.html#setup-2',1,'Setup'],['../examples_color_transparency.html#setup-3',1,'Setup'],['../contributing.html#setup-4',1,'Setup'],['../examples_input_two_players.html#sprite-setup',1,'Sprite Setup']]],
  ['setup_153',['setup',['../tutorial_sram.html#build-setup',1,'Build setup'],['../getting_started.html#troubleshooting-the-setup',1,'Troubleshooting the setup']]],
  ['setup_20even_20work_154',['Stage 0 — &quot;Does my setup even work?&quot;',['../learning_path.html#stage-0--does-my-setup-even-work',1,'']]],
  ['setup_20pattern_155',['Setup pattern',['../tutorial_hdma.html#setup-pattern',1,'Setup pattern'],['../tutorial_mode7.html#setup-pattern-1',1,'Setup pattern']]],
  ['setup_20pattern_156',['The setup pattern',['../tutorial_dma.html#the-setup-pattern',1,'']]],
  ['setup_20recommended_157',['Mode 1 Setup (Recommended)',['../snes_graphics_guide.html#mode-1-setup-recommended',1,'']]],
  ['setup_20the_20long_20way_158',['Manual setup (the long way)',['../getting_started.html#manual-setup-the-long-way',1,'']]],
  ['seven_20amplitude_20levels_159',['3. Seven Amplitude Levels',['../examples_hdma_hdma_wave.html#autotoc_md3-seven-amplitude-levels',1,'']]],
  ['several_20panels_20one_20layer_20one_20upload_160',['Several panels, one layer, one upload',['../tutorial_panel.html#several-panels-one-layer-one-upload',1,'']]],
  ['severity_20legend_161',['Severity legend',['../KNOWN_LIMITATIONS.html#severity-legend',1,'']]],
  ['sfx_162',['Example: Music + SFX',['../tutorial_audio.html#example-music--sfx',1,'']]],
  ['sfx_20from_20wav_163',['SFX from WAV',['../examples_audio_sfx_from_wav.html',1,'examples_audio']]],
  ['shadow_20buffer_20vs_20hardware_164',['Recipe 4 — Sprite/OAM debugging (shadow buffer vs hardware)',['../tutorial_debugging.html#recipe-4--spriteoam-debugging-shadow-buffer-vs-hardware',1,'']]],
  ['shadow_5ftint_20—_20recolour_20a_20whole_20scene_20at_20once_165',['shadow_tint — recolour a whole scene at once',['../examples_color_shadow_tint.html',1,'examples_color']]],
  ['shadows_20free_20depth_166',['7. Drop Shadows (Free Depth)',['../examples_games_breakout.html#autotoc_md7-drop-shadows-free-depth',1,'']]],
  ['shake_20—_20nudge_20the_20scroll_167',['Screen shake — nudge the scroll',['../craft_game_feel.html#screen-shake--nudge-the-scroll',1,'']]],
  ['shape_20not_20by_20register_168',['🟡 Repeat vs non-repeat on &lt;span class=&quot;tt&quot;&gt;WH0&lt;/span&gt;/&lt;span class=&quot;tt&quot;&gt;WH1&lt;/span&gt; — pick by data shape, not by register',['../tutorial_window.html#autotoc_md-repeat-vs-non-repeat-on-wh0wh1--pick-by-data-shape-not-by-register',1,'']]],
  ['shapes_169',['Static shapes vs animated shapes',['../tutorial_window.html#static-shapes-vs-animated-shapes',1,'']]],
  ['shapes_20in_20commercial_20games_170',['Window Shapes in Commercial Games',['../examples_windows_window.html#window-shapes-in-commercial-games',1,'']]],
  ['shapes_20vs_20animated_20shapes_171',['Static shapes vs animated shapes',['../tutorial_window.html#static-shapes-vs-animated-shapes',1,'']]],
  ['shapes_20with_20hdma_172',['Making Non-Rectangular Shapes with HDMA',['../examples_windows_window.html#making-non-rectangular-shapes-with-hdma',1,'']]],
  ['share_20one_20write_20twice_20latch_173',['share one write twice latch',['../KNOWN_LIMITATIONS.html#autotoc_md-bg1-scroll-and-mode-7-matrix-share-one-write-twice-latch',1,'🟡 BG1 scroll and Mode 7 matrix share one write-twice latch'],['../tutorial_mode7.html#autotoc_md-bg1-scroll-and-the-mode-7-registers-share-one-write-twice-latch',1,'🟡 BG1 scroll and the Mode 7 registers share one write-twice latch']]],
  ['shared_20by_20everything_20on_20screen_174',['1. VRAM — 64 KB, shared by everything on screen',['../craft_planning.html#autotoc_md1-vram--64-kb-shared-by-everything-on-screen',1,'']]],
  ['shared_20latch_175',['🟡 HDMA on BG1 scroll can corrupt Mode 7 writes (shared latch)',['../tutorial_hdma.html#autotoc_md-hdma-on-bg1-scroll-can-corrupt-mode-7-writes-shared-latch',1,'']]],
  ['shared_20palette_20planner_176',['palplan — project shared-palette planner',['../tools_palplan.html',1,'tools']]],
  ['sheet_177',['Register Cheat Sheet',['../snes_graphics_guide.html#register-cheat-sheet',1,'']]],
  ['sheet_20layout_178',['Sprite Sheet Layout',['../tutorial_animation.html#sprite-sheet-layout',1,'']]],
  ['sheet_20layout_179',['1. Sprite sheet layout',['../examples_sprites_animated_sprite.html#autotoc_md1-sprite-sheet-layout',1,'']]],
  ['sheet_20organization_180',['Sprite Sheet Organization',['../tutorial_animation.html#sprite-sheet-organization',1,'']]],
  ['sheet_20was_20converted_181',['🟡 Match &lt;span class=&quot;tt&quot;&gt;base_tile&lt;/span&gt;/&lt;span class=&quot;tt&quot;&gt;stride&lt;/span&gt; to how the sheet was converted',['../tutorial_panel.html#autotoc_md-match-base_tilestride-to-how-the-sheet-was-converted',1,'']]],
  ['sheet_3a_20s_20must_20match_20the_20sprite_20size_182',['Converting a sheet: &lt;span class=&quot;tt&quot;&gt;-s&lt;/span&gt; must match the sprite size',['../tutorial_sprites.html#converting-a-sheet--s-must-match-the-sprite-size',1,'']]],
  ['sheets_183',['Animated Sprite -- Direction States and Sprite Sheets',['../examples_sprites_animated_sprite.html',1,'examples_sprites']]],
  ['sheets_20in_20vram_184',['Sprite Sheets in VRAM',['../examples_sprites_animated_sprite.html#sprite-sheets-in-vram',1,'']]],
  ['sheets_20with_20gfx4snes_185',['Converting Sprite Sheets with gfx4snes',['../tutorial_animation.html#converting-sprite-sheets-with-gfx4snes',1,'']]],
  ['shelf_186',['Go deeper — the curated shelf',['../craft.html#go-deeper--the-curated-shelf',1,'']]],
  ['ship_187',['Stage 6 — &quot;Can I finish and ship?&quot;',['../learning_path.html#stage-6--can-i-finish-and-ship',1,'']]],
  ['ship_20in_20the_20lib_20chantier_20b6_202026_2005_2009_188',['&lt;span class=&quot;tt&quot;&gt;atan2&lt;/span&gt; and &lt;span class=&quot;tt&quot;&gt;sqrt&lt;/span&gt; ship in the lib (chantier B6, 2026-05-09)',['../tutorial_math.html#atan2-and-sqrt-ship-in-the-lib-chantier-b6-2026-05-09',1,'']]],
  ['shipped_20example_189',['shipped example',['../tutorial_mosaic.html#worked-pattern-the-shipped-example',1,'Worked pattern (the shipped example)'],['../tutorial_sram.html#worked-pattern-the-shipped-example-1',1,'Worked pattern (the shipped example)']]],
  ['shipped_20examples_190',['shipped examples',['../tutorial_hdma.html#worked-patterns-the-shipped-examples',1,'Worked patterns (the shipped examples)'],['../tutorial_map.html#worked-patterns-the-shipped-examples-1',1,'Worked patterns (the shipped examples)'],['../tutorial_mode7.html#worked-patterns-the-shipped-examples-2',1,'Worked patterns (the shipped examples)'],['../tutorial_window.html#worked-patterns-the-shipped-examples-3',1,'Worked patterns (the shipped examples)'],['../tutorial_colormath.html#worked-patterns-the-two-shipped-examples',1,'Worked patterns (the two shipped examples)']]],
  ['shipping_191',['Building and shipping',['../faq.html#building-and-shipping',1,'']]],
  ['shmup_5f1942_192',['shmup_1942',['../examples_games_shmup_1942.html',1,'examples_games']]],
  ['shot_20samples_20from_20wav_20wav2brr_193',['One-shot samples from WAV (wav2brr)',['../tutorial_audio.html#audio_wav2brr',1,'']]],
  ['show_20inside_194',['Inversion: Show Inside',['../examples_windows_window.html#inversion-show-inside',1,'']]],
  ['showcase_20—_20examples_20hdma_20hdma_5fhelpers_195',['Helpers showcase — &lt;span class=&quot;tt&quot;&gt;examples/hdma/hdma_helpers&lt;/span&gt;',['../tutorial_hdma.html#helpers-showcase--exampleshdmahdma_helpers',1,'']]],
  ['shows_196',['Shows',['../examples_backgrounds_mode1_bg3_priority.html#what-this-example-shows',1,'What This Example Shows'],['../examples_hdma_gradient_colors.html#what-this-example-shows-1',1,'What This Example Shows'],['../examples_memory_hirom_demo.html#what-this-example-shows-2',1,'What This Example Shows'],['../examples_memory_save_game.html#what-this-example-shows-3',1,'What This Example Shows'],['../examples_mode7_perspective.html#what-this-example-shows-4',1,'What This Example Shows'],['../examples_mode7_rotate_scale.html#what-this-example-shows-5',1,'What This Example Shows'],['../examples_scrolling_parallax_scroll.html#what-this-example-shows-6',1,'What This Example Shows'],['../examples_sprites_animated_sprite.html#what-this-example-shows-7',1,'What This Example Shows'],['../examples_sprites_dynamic_sprite.html#what-this-example-shows-8',1,'What This Example Shows'],['../examples_sprites_simple_sprite.html#what-this-example-shows-9',1,'What This Example Shows'],['../examples_sprites_sprite_sizes.html#what-this-example-shows-10',1,'What This Example Shows'],['../examples_transitions_mosaic.html#what-this-example-shows-11',1,'What This Example Shows']]],
  ['shows_20the_20backdrop_20not_20a_20layer_197',['🟡 Out-of-bounds with &lt;span class=&quot;tt&quot;&gt;MODE7_TRANSPARENT&lt;/span&gt; shows the backdrop, not a layer',['../tutorial_mode7.html#autotoc_md-out-of-bounds-with-mode7_transparent-shows-the-backdrop-not-a-layer',1,'']]],
  ['side_3a_20tiles_20by_20mode_198',['The cost side: tiles by mode',['../craft_planning.html#the-cost-side-tiles-by-mode',1,'']]],
  ['sign_20convention_199',['Sign convention',['../fixed32_8h.html#sign-convention',1,'']]],
  ['signed_20result_200',['🟡 Sin/cos LUTs are unsigned-angle, signed-result',['../tutorial_math.html#autotoc_md-sincos-luts-are-unsigned-angle-signed-result',1,'']]],
  ['silent_20corruption_201',['🔴 Battery dies → silent corruption',['../tutorial_sram.html#autotoc_md-battery-dies--silent-corruption',1,'']]],
  ['silent_20miscompilations_20found_20and_20fixed_20by_20the_20c_20feature_20runtime_20rom_202026_2009_2013_202',['🟢 Five silent miscompilations found and fixed by the C-feature runtime ROM (2026-09-13)',['../KNOWN_LIMITATIONS.html#autotoc_md-five-silent-miscompilations-found-and-fixed-by-the-c-feature-runtime-rom-2026-09-13',1,'']]],
  ['silently_203',['Things that go wrong silently',['../faq.html#things-that-go-wrong-silently',1,'']]],
  ['silently_20does_20nothing_204',['When something silently does nothing',['../api_index.html#when-something-silently-does-nothing',1,'']]],
  ['silently_20dropped_205',['silently dropped',['../KNOWN_LIMITATIONS.html#autotoc_md-vram-writes-outside-vblank-are-silently-dropped',1,'🔴 VRAM writes outside VBlank are silently dropped'],['../tutorial_dma.html#autotoc_md-vramcgramoam-writes-outside-vblank-or-force-blank-are-silently-dropped',1,'🔴 VRAM/CGRAM/OAM writes outside VBlank or force blank are silently dropped']]],
  ['simple_20game_20over_20breakout_206',['Simple Game Over (Breakout)',['../tutorial_game_states.html#simple-game-over-breakout',1,'']]],
  ['simple_20parallax_20multiple_20bgs_207',['Simple Parallax (Multiple BGs)',['../tutorial_scrolling.html#simple-parallax-multiple-bgs',1,'']]],
  ['simple_20sprite_20your_20first_20oam_20sprite_208',['Simple Sprite -- Your First OAM Sprite',['../examples_sprites_simple_sprite.html',1,'examples_sprites']]],
  ['sin_20cos_20lookup_20tables_209',['Trigonometry (sin/cos lookup tables)',['../tutorial_math.html#trigonometry-sincos-lookup-tables',1,'']]],
  ['sin_20cos_20luts_20are_20unsigned_20angle_20signed_20result_210',['🟡 Sin/cos LUTs are unsigned-angle, signed-result',['../tutorial_math.html#autotoc_md-sincos-luts-are-unsigned-angle-signed-result',1,'']]],
  ['since_20127_203_211',['🟢 Bank $00 ROM: code only — C const data lives in the asset banks (since #127.3)',['../KNOWN_LIMITATIONS.html#autotoc_md-bank-00-rom-code-only--c-const-data-lives-in-the-asset-banks-since-1273',1,'']]],
  ['since_20chantier_20a1_212',['🟢 &lt;span class=&quot;tt&quot;&gt;int&lt;/span&gt; and &lt;span class=&quot;tt&quot;&gt;long&lt;/span&gt; sizes are correct on this target (since chantier A1)',['../tutorial_math.html#autotoc_md-int-and-long-sizes-are-correct-on-this-target-since-chantier-a1',1,'']]],
  ['since_20chantier_20a2_202026_2005_2009_213',['🟢 &lt;span class=&quot;tt&quot;&gt;volatile&lt;/span&gt; is preserved through QBE (since chantier A2, 2026-05-09)',['../KNOWN_LIMITATIONS.html#autotoc_md-volatile-is-preserved-through-qbe-since-chantier-a2-2026-05-09',1,'']]],
  ['single_20bg_20layer_214',['🔴 Single BG layer',['../tutorial_mode7.html#autotoc_md-single-bg-layer',1,'']]],
  ['siwp_20ciwp_20write_20protection_20polarity_20resolved_3a_20bit_201_20write_20enable_215',['🟢 SA-1 SIWP/CIWP write-protection polarity (resolved: bit=1 = write-enable)',['../KNOWN_LIMITATIONS.html#autotoc_md-sa-1-siwpciwp-write-protection-polarity-resolved-bit1--write-enable',1,'']]],
  ['size_216',['Size',['../registers.html#autotoc_md2107-210a---bg1sc-bg4sc-tilemap-addresssize',1,'$2107-$210A - BG1SC-BG4SC (Tilemap Address/Size)'],['../registers.html#autotoc_md43x5-43x6---dasxlh-transfer-size',1,'$43x5-$43x6 - DASxL/H (Transfer Size)'],['../tutorial_animation.html#one-draw-function-engine-resolved-size',1,'One Draw Function, Engine-Resolved Size']]],
  ['size_217',['size',['../troubleshooting.html#rom-too-large-or-linker-errors-about-size',1,'&quot;ROM too large&quot; or linker errors about size'],['../examples_sprites_simple_sprite.html#autotoc_md3-configure-obj-size',1,'3. Configure OBJ size'],['../tutorial_sprites.html#converting-a-sheet--s-must-match-the-sprite-size',1,'Converting a sheet: &lt;span class=&quot;tt&quot;&gt;-s&lt;/span&gt; must match the sprite size']]],
  ['size_201_20pixels_218',['🟡 Mosaic block size is &quot;size + 1&quot; pixels',['../tutorial_mosaic.html#autotoc_md-mosaic-block-size-is-size--1-pixels',1,'']]],
  ['size_20all_206_20snes_20sprite_20size_20modes_219',['Object Size -- All 6 SNES Sprite Size Modes',['../examples_sprites_sprite_sizes.html',1,'examples_sprites']]],
  ['size_20is_204_20bytes_20chantier_20a6_20a7_202026_2005_2015_220',['🟢 Pointer IR size is 4 bytes (chantier A6+A7, 2026-05-15)',['../KNOWN_LIMITATIONS.html#autotoc_md-pointer-ir-size-is-4-bytes-chantier-a6a7-2026-05-15',1,'']]],
  ['size_20is_20size_201_20pixels_221',['🟡 Mosaic block size is &quot;size + 1&quot; pixels',['../tutorial_mosaic.html#autotoc_md-mosaic-block-size-is-size--1-pixels',1,'']]],
  ['size_20modes_222',['Size Modes',['../examples_sprites_sprite_sizes.html',1,'Object Size -- All 6 SNES Sprite Size Modes'],['../examples_sprites_sprite_sizes.html#the-6-size-modes',1,'The 6 Size Modes']]],
  ['size_20modes_20register_20_242101_223',['OBJ Size Modes (Register $2101)',['../examples_sprites_metasprite.html#obj-size-modes-register-2101',1,'']]],
  ['sizes_224',['Sizes',['../tutorial_collision.html#custom-tile-sizes',1,'Custom Tile Sizes'],['../tutorial_sprites.html#sprite-sizes',1,'Sprite Sizes'],['../snes_graphics_guide.html#sprite-sizes-1',1,'Sprite Sizes'],['../oam.html#sprite-sizes-2',1,'Sprite Sizes'],['../snes_graphics_guide.html#tilemap-sizes',1,'Tilemap Sizes'],['../snes_sound_guide.html#typical-sample-sizes',1,'Typical Sample Sizes']]],
  ['sizes_20and_20semantics_20match_20the_20w65816_20target_225',['🟢 &lt;span class=&quot;tt&quot;&gt;int&lt;/span&gt; and &lt;span class=&quot;tt&quot;&gt;long&lt;/span&gt; sizes AND semantics match the w65816 target',['../KNOWN_LIMITATIONS.html#autotoc_md-int-and-long-sizes-and-semantics-match-the-w65816-target',1,'']]],
  ['sizes_20are_20correct_20on_20this_20target_20since_20chantier_20a1_226',['🟢 &lt;span class=&quot;tt&quot;&gt;int&lt;/span&gt; and &lt;span class=&quot;tt&quot;&gt;long&lt;/span&gt; sizes are correct on this target (since chantier A1)',['../tutorial_math.html#autotoc_md-int-and-long-sizes-are-correct-on-this-target-since-chantier-a1',1,'']]],
  ['slice_20panels_227',['9-slice panels',['../tutorial_panel.html',1,'index']]],
  ['slide_20along_20walls_228',['Stopping Movement (Slide Along Walls)',['../tutorial_collision.html#stopping-movement-slide-along-walls',1,'']]],
  ['sliding_229',['Per-Axis Sliding',['../examples_basics_collision_demo.html#per-axis-sliding',1,'']]],
  ['slope_20collision_230',['Object Engine and Slope Collision',['../examples_maps_slope_collision.html#object-engine-and-slope-collision',1,'']]],
  ['slope_20mario_231',['Slope Mario',['../examples_maps_slope_collision.html',1,'examples_maps']]],
  ['slot_232',['1. NOP After Every Branch (Delay Slot)',['../tutorial_superfx.html#autotoc_md1-nop-after-every-branch-delay-slot',1,'']]],
  ['slot_20saves_233',['Multi-slot saves',['../tutorial_sram.html#multi-slot-saves',1,'']]],
  ['slot_20types_234',['Fixed-point: three slot types',['../tutorial_dsp1.html#fixed-point-three-slot-types',1,'']]],
  ['slots_235',['Slots',['../examples_scrolling_mixed_scroll.html#palette-slots',1,'Palette Slots'],['../examples_memory_save_game.html#save-slots',1,'Save Slots']]],
  ['small_236',['Keep PRs small',['../contributing.html#keep-prs-small',1,'']]],
  ['smallest_20complete_20game_237',['game_skeleton — the smallest complete game',['../examples_basics_game_skeleton.html',1,'examples_basics']]],
  ['smconv_238',['smconv',['../third_party.html#smconv',1,'']]],
  ['smconv_20—_20tracker_20modules_20to_20snesmod_20soundbanks_239',['smconv — tracker modules to SNESMOD soundbanks',['../tools_smconv.html',1,'tools']]],
  ['smconv_20error_240',['Build fails with smconv error',['../examples_audio_snesmod_music.html#build-fails-with-smconv-error',1,'']]],
  ['smconv_20options_241',['smconv Options',['../examples_audio_snesmod_music.html#smconv-options',1,'']]],
  ['smconv_20tool_242',['smconv Tool',['../tutorial_audio.html#smconv-tool',1,'']]],
  ['smooth_20fade_243',['Exercise 1: Smooth Fade',['../examples_transitions_fading.html#exercise-1-smooth-fade',1,'']]],
  ['smooth_20interpolation_244',['Smooth interpolation',['../tutorial_math.html#smooth-interpolation',1,'']]],
  ['smooth_20sprite_20movement_245',['Smooth sprite movement',['../tutorial_math.html#smooth-sprite-movement',1,'']]],
  ['snapping_20to_20tile_20grid_20platformer_20landing_246',['Snapping to Tile Grid (Platformer Landing)',['../tutorial_collision.html#snapping-to-tile-grid-platformer-landing',1,'']]],
  ['snes_247',['SNES',['../examples_input_controller.html#how-input-works-on-the-snes',1,'How Input Works on the SNES'],['../examples_text.html#how-text-works-on-snes',1,'How Text Works on SNES'],['../examples_audio_speech_synth.html',1,'speech_synth — the SNES says &quot;OPEN SNES&quot;'],['../craft_tiles_to_levels.html#the-workflow-design-in-tiled-convert-for-the-snes',1,'The workflow: design in Tiled, convert for the SNES'],['../tutorial_math.html#why-fixed-point-on-the-snes',1,'Why fixed-point on the SNES']]],
  ['snes_20audio_20architecture_248',['SNES Audio Architecture',['../tutorial_audio.html#snes-audio-architecture',1,'']]],
  ['snes_20compatibility_249',['For SNES Compatibility',['../snes_graphics_guide.html#for-snes-compatibility',1,'']]],
  ['snes_20concepts_250',['SNES Concepts',['../examples_audio_apu_switch.html#snes-concepts',1,'SNES Concepts'],['../examples_audio_pitch_mod.html#snes-concepts-2',1,'SNES Concepts'],['../examples_audio_play_noise.html#snes-concepts-3',1,'SNES Concepts'],['../examples_audio_sfx_from_wav.html#snes-concepts-4',1,'SNES Concepts'],['../examples_audio_snesmod_sfx.html#snes-concepts-5',1,'SNES Concepts'],['../examples_audio_soundboard.html#snes-concepts-6',1,'SNES Concepts'],['../examples_backgrounds_mode1_bg3_priority.html#snes-concepts-7',1,'SNES Concepts'],['../examples_backgrounds_mode1_lz77.html#snes-concepts-8',1,'SNES Concepts'],['../examples_backgrounds_mode5_hires.html#snes-concepts-9',1,'SNES Concepts'],['../examples_basics_aim_target.html#snes-concepts-10',1,'SNES Concepts'],['../examples_basics_collision_demo.html#snes-concepts-11',1,'SNES Concepts'],['../examples_basics_fix32_orbit.html#snes-concepts-12',1,'SNES Concepts'],['../examples_basics_random.html#snes-concepts-13',1,'SNES Concepts'],['../examples_basics_scene_stack.html#snes-concepts-14',1,'SNES Concepts'],['../examples_basics_timer.html#snes-concepts-15',1,'SNES Concepts'],['../examples_chips_dsp1_cube.html#snes-concepts-16',1,'SNES Concepts'],['../examples_color_direct_color.html#snes-concepts-17',1,'SNES Concepts'],['../examples_color_gradient_9bit.html#snes-concepts-18',1,'SNES Concepts'],['../examples_color_hicolor_1792.html#snes-concepts-19',1,'SNES Concepts'],['../examples_color_transparency.html#snes-concepts-20',1,'SNES Concepts'],['../examples_games_mapandobjects.html#snes-concepts-21',1,'SNES Concepts'],['../examples_games_mode7_flying.html#snes-concepts-22',1,'SNES Concepts'],['../examples_games_mode7_racing.html#snes-concepts-23',1,'SNES Concepts'],['../examples_games_rpg.html#snes-concepts-24',1,'SNES Concepts'],['../examples_hdma_gradient_colors.html#snes-concepts-25',1,'SNES Concepts'],['../examples_hdma_hdma_indirect_gradient.html#snes-concepts-26',1,'SNES Concepts'],['../examples_hdma_hdma_wave_table.html#snes-concepts-27',1,'SNES Concepts'],['../examples_input_controller.html#snes-concepts-28',1,'SNES Concepts'],['../examples_input_mouse.html#snes-concepts-29',1,'SNES Concepts'],['../examples_maps_dynamic_map.html#snes-concepts-31',1,'SNES Concepts'],['../examples_maps_map_scroll.html#snes-concepts-32',1,'SNES Concepts'],['../examples_maps_slope_collision.html#snes-concepts-33',1,'SNES Concepts'],['../examples_maps_tiled.html#snes-concepts-34',1,'SNES Concepts'],['../examples_memory_hirom_demo.html#snes-concepts-35',1,'SNES Concepts'],['../examples_memory_save_game.html#snes-concepts-36',1,'SNES Concepts'],['../examples_mode7_dsp1_ground.html#snes-concepts-37',1,'SNES Concepts'],['../examples_mode7_perspective.html#snes-concepts-38',1,'SNES Concepts'],['../examples_mode7_perspective_rotate.html#snes-concepts-39',1,'SNES Concepts'],['../examples_mode7_rotate_scale.html#snes-concepts-40',1,'SNES Concepts'],['../examples_scrolling_mixed_scroll.html#snes-concepts-41',1,'SNES Concepts'],['../examples_scrolling_parallax_scroll.html#snes-concepts-42',1,'SNES Concepts'],['../examples_sprites_animated_sprite.html#snes-concepts-43',1,'SNES Concepts'],['../examples_sprites_aseprite_pipeline.html#snes-concepts-44',1,'SNES Concepts'],['../examples_sprites_dynamic_sprite.html#snes-concepts-45',1,'SNES Concepts'],['../examples_sprites_metasprite.html#snes-concepts-46',1,'SNES Concepts'],['../examples_sprites_simple_sprite.html#snes-concepts-47',1,'SNES Concepts'],['../examples_sprites_sprite_sizes.html#snes-concepts-48',1,'SNES Concepts'],['../examples_transitions_mosaic.html#snes-concepts-51',1,'SNES Concepts'],['../examples_windows_transparent_window.html#snes-concepts-52',1,'SNES Concepts'],['../examples_windows_window.html#snes-concepts-53',1,'SNES Concepts'],['../examples_windows_window_multi_hdma.html#snes-concepts-54',1,'SNES Concepts']]],
  ['snes_20concepts_251',['SNES concepts',['../examples_audio_echo.html#snes-concepts-1',1,'SNES concepts'],['../examples_input_move_sprite.html#snes-concepts-30',1,'SNES concepts'],['../examples_text_print_string.html#snes-concepts-49',1,'SNES concepts'],['../examples_text_scroll_message.html#snes-concepts-50',1,'SNES concepts']]],
  ['snes_20controller_20layout_252',['SNES Controller Layout',['../tutorial_input.html#snes-controller-layout',1,'']]],
  ['snes_20development_253',['Learn SNES Development',['../learning_path.html',1,'index']]],
  ['snes_20game_254',['Planning your SNES game',['../craft_planning.html',1,'craft']]],
  ['snes_20graphics_20programming_20guide_255',['SNES Graphics Programming Guide',['../snes_graphics_guide.html',1,'index']]],
  ['snes_20hardware_20overview_256',['SNES Hardware Overview',['../hardware_overview.html',1,'index']]],
  ['snes_20hardware_20register_20reference_257',['SNES Hardware Register Reference',['../registers.html',1,'index']]],
  ['snes_20map_20data_258',['tmx2snes — Tiled levels to SNES map data',['../tools_tmx2snes.html',1,'tools']]],
  ['snes_20memory_20map_259',['SNES Memory Map',['../memory_map.html',1,'index']]],
  ['snes_20memory_20mapping_260',['HiROM Demo -- Understanding SNES Memory Mapping',['../examples_memory_hirom_demo.html',1,'examples_memory']]],
  ['snes_20mouse_261',['SNES Mouse',['../examples_input_mouse.html',1,'examples_input']]],
  ['snes_20mouse_20hardware_262',['SNES Mouse Hardware',['../examples_input_mouse.html#snes-mouse-hardware',1,'']]],
  ['snes_20oam_20object_20attribute_20memory_263',['SNES OAM (Object Attribute Memory)',['../oam.html',1,'index']]],
  ['snes_20says_20open_20snes_264',['speech_synth — the SNES says &quot;OPEN SNES&quot;',['../examples_audio_speech_synth.html',1,'examples_audio']]],
  ['snes_20sound_20programming_20guide_265',['SNES Sound Programming Guide',['../snes_sound_guide.html',1,'index']]],
  ['snes_20sprite_20basics_266',['SNES Sprite Basics',['../tutorial_sprites.html#snes-sprite-basics',1,'']]],
  ['snes_20sprite_20limits_267',['SNES Sprite Limits',['../sprite_8h.html#snes-sprite-limits',1,'']]],
  ['snes_20sprite_20size_20modes_268',['Object Size -- All 6 SNES Sprite Size Modes',['../examples_sprites_sprite_sizes.html',1,'examples_sprites']]],
  ['snes_20video_20modes_269',['SNES Video Modes',['../tutorial_graphics.html#snes-video-modes',1,'']]],
  ['snes_20window_20system_270',['SNES Window System',['../examples_windows_window.html#snes-window-system',1,'']]],
  ['snesmod_271',['The raw APU path (no snesmod)',['../tutorial_audio.html#the-raw-apu-path-no-snesmod',1,'']]],
  ['snesmod_20api_272',['SNESMOD API',['../examples_audio_snesmod_music.html#snesmod-api',1,'']]],
  ['snesmod_20initialization_273',['SNESMOD Initialization',['../examples_audio_snesmod_sfx.html#snesmod-initialization',1,'']]],
  ['snesmod_20large_20soundbank_20music_274',['SNESMOD Large Soundbank Music',['../examples_audio_snesmod_music_large.html',1,'examples_audio']]],
  ['snesmod_20music_20example_275',['SNESMOD Music Example',['../examples_audio_snesmod_music.html',1,'examples_audio']]],
  ['snesmod_20overview_276',['SNESMOD Overview',['../examples_audio_snesmod_music.html#snesmod-overview',1,'']]],
  ['snesmod_20recommended_277',['SNESMOD (Recommended)',['../tutorial_audio.html#snesmod-recommended',1,'']]],
  ['snesmod_20sound_20effects_278',['SNESMOD Sound Effects',['../examples_audio_snesmod_sfx.html',1,'examples_audio']]],
  ['snesmod_20soundbanks_279',['smconv — tracker modules to SNESMOD soundbanks',['../tools_smconv.html',1,'tools']]],
  ['snesmodprocess_280',['Important: Call snesmodProcess()!',['../tutorial_audio.html#important-call-snesmodprocess',1,'']]],
  ['so_20many_20modules_281',['Why So Many Modules?',['../examples_games_likemario.html#why-so-many-modules',1,'']]],
  ['so_20stream_20it_282',['The level is bigger than VRAM — so stream it',['../craft_tiles_to_levels.html#the-level-is-bigger-than-vram--so-stream-it',1,'']]],
  ['solution_283',['The Solution',['../oam.html#the-solution',1,'']]],
  ['something_20on_20screen_284',['something on screen',['../api_index.html#getting-something-on-screen',1,'Getting something on screen'],['../learning_path.html#stage-1--can-i-put-something-on-screen',1,'Stage 1 — &quot;Can I put something on screen?&quot;']]],
  ['something_20silently_20does_20nothing_285',['When something silently does nothing',['../api_index.html#when-something-silently-does-nothing',1,'']]],
  ['sound_286',['Sound',['../api_index.html#sound',1,'']]],
  ['sound_20creation_20tools_287',['Sound Creation Tools',['../snes_sound_guide.html#sound-creation-tools',1,'']]],
  ['sound_20effects_288',['Sound Effects',['../examples_audio_snesmod_music.html#exercise-1-add-sound-effects',1,'Exercise 1: Add Sound Effects'],['../examples_audio_snesmod_sfx.html',1,'SNESMOD Sound Effects'],['../tutorial_audio.html#sound-effects',1,'Sound Effects']]],
  ['sound_20programming_20guide_289',['SNES Sound Programming Guide',['../snes_sound_guide.html',1,'index']]],
  ['sound_20samples_290',['wav2brr — WAV to BRR sound samples',['../tools_wav2brr.html',1,'tools']]],
  ['soundbank_291',['The Soundbank',['../examples_audio_snesmod_sfx.html#the-soundbank',1,'']]],
  ['soundbank_20creation_292',['Soundbank Creation',['../snesmod_8h.html#soundbank-creation',1,'']]],
  ['soundbank_20music_293',['SNESMOD Large Soundbank Music',['../examples_audio_snesmod_music_large.html',1,'examples_audio']]],
  ['soundbanks_294',['smconv — tracker modules to SNESMOD soundbanks',['../tools_smconv.html',1,'tools']]],
  ['soundboard_20—_20the_20audio_20v2_20engine_20driven_20entirely_20from_20c_295',['soundboard — the audio v2 engine, driven entirely from C',['../examples_audio_soundboard.html',1,'examples_audio']]],
  ['sounds_20wrong_296',['Music sounds wrong',['../examples_audio_snesmod_music.html#music-sounds-wrong',1,'']]],
  ['source_20address_297',['$43x2-$43x4 - A1TxL/H/B (Source Address)',['../registers.html#autotoc_md43x2-43x4---a1txlhb-source-address',1,'']]],
  ['source_20addressing_298',['Direction and source addressing',['../tutorial_dma.html#direction-and-source-addressing',1,'']]],
  ['source_20c_299',['Source (.c)',['../code_style.html#source-c',1,'']]],
  ['source_20code_300',['Source Code',['../example_sources.html',1,'Example Source Code'],['../index.html#examples-annotated-source-code',1,'Examples (Annotated Source Code)']]],
  ['sources_301',['Sample Sources',['../snes_sound_guide.html#sample-sources',1,'']]],
  ['sources_20cc0_20public_20domain_302',['Free Asset Sources (CC0/Public Domain)',['../snes_graphics_guide.html#free-asset-sources-cc0public-domain',1,'']]],
  ['space_303',['SRAM Address Space',['../examples_memory_save_game.html#sram-address-space',1,'']]],
  ['space_20overview_304',['Address Space Overview',['../memory_map.html#address-space-overview',1,'']]],
  ['spc_20dump_305',['spc dump',['../tools_luna.html#luna-spc-dump',1,'&lt;span class=&quot;tt&quot;&gt;luna spc-dump&lt;/span&gt;'],['../tutorial_audio.html#debugging-audio-lunas-spc-dump',1,'Debugging audio: luna&apos;s spc-dump']]],
  ['spc_20ram_306',['SPC RAM',['../examples_audio_snesmod_music.html#spc-ram',1,'']]],
  ['spc700_20cpu_307',['SPC700 CPU',['../snes_sound_guide.html#spc700-cpu',1,'']]],
  ['spc700_20registers_308',['SPC700 registers',['../snes_sound_guide.html#spc700-registers',1,'']]],
  ['special_20timing_309',['🟠 SRAM access requires no special timing',['../tutorial_sram.html#autotoc_md-sram-access-requires-no-special-timing',1,'']]],
  ['specifications_310',['Specifications',['../hardware_overview.html#specifications',1,'']]],
  ['specifics_311',['BG3 Specifics',['../examples_backgrounds_mode1.html#bg3-specifics',1,'']]],
  ['speech_5fsynth_20—_20the_20snes_20says_20open_20snes_312',['speech_synth — the SNES says &quot;OPEN SNES&quot;',['../examples_audio_speech_synth.html',1,'examples_audio']]],
  ['speeds_313',['Speeds',['../examples_scrolling_continuous_scroll.html#autotoc_md1-two-layers-two-speeds',1,'1. Two Layers, Two Speeds'],['../examples_input_two_players.html#exercise-2-different-speeds',1,'Exercise 2: Different Speeds'],['../examples_transitions_fading.html#fade-speeds',1,'Fade Speeds']]],
  ['spelling_20the_20message_314',['6. Spelling the Message',['../examples_fundamentals_text_glyphs.html#autotoc_md6-spelling-the-message',1,'']]],
  ['split_315',['CGRAM Split',['../examples_sprites_simple_sprite.html#cgram-split',1,'']]],
  ['split_20bg_20vs_20sprites_316',['2. CGRAM — 256 colours, split BG vs sprites',['../craft_planning.html#autotoc_md2-cgram--256-colours-split-bg-vs-sprites',1,'']]],
  ['split_20blend_317',['&quot;3840 colors&quot; — RGB channel-split blend',['../examples_color_hicolor_blend.html',1,'examples_color']]],
  ['split_20screen_318',['Exercise 4: Split Screen',['../examples_input_two_players.html#exercise-4-split-screen',1,'']]],
  ['split_20screen_20with_20hdma_319',['1. Split-screen with HDMA',['../examples_mode7_perspective.html#autotoc_md1-split-screen-with-hdma',1,'']]],
  ['spotlight_20blend_20—_20examples_20windows_20transparent_5fwindow_320',['Window-gated spotlight blend — &lt;span class=&quot;tt&quot;&gt;examples/windows/transparent_window&lt;/span&gt;',['../tutorial_colormath.html#window-gated-spotlight-blend--exampleswindowstransparent_window',1,'']]],
  ['sprite_321',['Sprite',['../examples_input_mouse.html#autotoc_md2-load-cursor-sprite',1,'2. Load Cursor Sprite'],['../tutorial_sprites.html#setting-a-sprite',1,'Setting a Sprite'],['../tutorial_animation.html#setting-up-a-dynamic-sprite',1,'Setting Up a Dynamic Sprite'],['../examples_sprites_simple_sprite.html',1,'Simple Sprite -- Your First OAM Sprite']]],
  ['sprite_322',['sprite',['../examples_sprites_simple_sprite.html#autotoc_md4-place-the-sprite',1,'4. Place the sprite'],['../oam.html#extended-table-2-bits-per-sprite',1,'Extended Table (2 bits per sprite)'],['../oam.html#main-table-4-bytes-per-sprite',1,'Main Table (4 bytes per sprite)']]],
  ['sprite_20basics_323',['SNES Sprite Basics',['../tutorial_sprites.html#snes-sprite-basics',1,'']]],
  ['sprite_20collision_324',['Sprite-to-Sprite Collision',['../tutorial_collision.html#sprite-to-sprite-collision',1,'']]],
  ['sprite_20direction_20states_20and_20sprite_20sheets_325',['Animated Sprite -- Direction States and Sprite Sheets',['../examples_sprites_animated_sprite.html',1,'examples_sprites']]],
  ['sprite_20engine_326',['Sprite Engine',['../examples_maps_slope_collision.html#dynamic-sprite-engine',1,'Dynamic Sprite Engine'],['../tutorial_animation.html#the-dynamic-sprite-engine',1,'The Dynamic Sprite Engine']]],
  ['sprite_20engine_327',['1. Initialize the dynamic sprite engine',['../examples_sprites_dynamic_sprite.html#autotoc_md1-initialize-the-dynamic-sprite-engine',1,'']]],
  ['sprite_20functions_328',['Using OpenSNES Sprite Functions',['../tutorial_sprites.html#using-opensnes-sprite-functions',1,'']]],
  ['sprite_20graphics_20into_20vram_329',['1. Load sprite graphics into VRAM',['../examples_sprites_simple_sprite.html#autotoc_md1-load-sprite-graphics-into-vram',1,'']]],
  ['sprite_20is_20vs_20where_20it_20collides_330',['Where the sprite is vs where it collides',['../tutorial_collision.html#where-the-sprite-is-vs-where-it-collides',1,'']]],
  ['sprite_20limits_331',['SNES Sprite Limits',['../sprite_8h.html#snes-sprite-limits',1,'']]],
  ['sprite_20memory_332',['OAM (Sprite Memory)',['../registers.html#oam-sprite-memory',1,'']]],
  ['sprite_20movement_333',['Smooth sprite movement',['../tutorial_math.html#smooth-sprite-movement',1,'']]],
  ['sprite_20oam_20debugging_20shadow_20buffer_20vs_20hardware_334',['Recipe 4 — Sprite/OAM debugging (shadow buffer vs hardware)',['../tutorial_debugging.html#recipe-4--spriteoam-debugging-shadow-buffer-vs-hardware',1,'']]],
  ['sprite_20palette_335',['2. Load the sprite palette',['../examples_sprites_simple_sprite.html#autotoc_md2-load-the-sprite-palette',1,'']]],
  ['sprite_20palettes_336',['Sprite Palettes',['../tutorial_sprites.html#sprite-palettes',1,'']]],
  ['sprite_20palettes_20start_20at_20cgram_20128_337',['Trap 3: sprite palettes start at CGRAM 128',['../migrating_pvsneslib.html#trap-3-sprite-palettes-start-at-cgram-128',1,'']]],
  ['sprite_20palettes_20start_20at_20cgram_20offset_20128_20not_200_338',['🟡 Sprite palettes start at CGRAM offset 128, not 0',['../KNOWN_LIMITATIONS.html#autotoc_md-sprite-palettes-start-at-cgram-offset-128-not-0',1,'']]],
  ['sprite_20per_20line_20budget_3a_2032_339',['The sprite-per-line budget: 32',['../craft_frame_budget.html#the-sprite-per-line-budget-32',1,'']]],
  ['sprite_20positioning_340',['Camera-Relative Sprite Positioning',['../examples_maps_map_scroll.html#camera-relative-sprite-positioning',1,'']]],
  ['sprite_20priority_341',['Sprite Priority',['../snes_graphics_guide.html#sprite-priority',1,'']]],
  ['sprite_20settings_342',['$2101 - OBJSEL (Sprite Settings)',['../registers.html#autotoc_md2101---objsel-sprite-settings',1,'']]],
  ['sprite_20setup_343',['Sprite Setup',['../examples_input_two_players.html#sprite-setup',1,'']]],
  ['sprite_20sheet_20layout_344',['Sprite Sheet Layout',['../tutorial_animation.html#sprite-sheet-layout',1,'']]],
  ['sprite_20sheet_20layout_345',['1. Sprite sheet layout',['../examples_sprites_animated_sprite.html#autotoc_md1-sprite-sheet-layout',1,'']]],
  ['sprite_20sheet_20organization_346',['Sprite Sheet Organization',['../tutorial_animation.html#sprite-sheet-organization',1,'']]],
  ['sprite_20sheets_347',['Animated Sprite -- Direction States and Sprite Sheets',['../examples_sprites_animated_sprite.html',1,'examples_sprites']]],
  ['sprite_20sheets_20in_20vram_348',['Sprite Sheets in VRAM',['../examples_sprites_animated_sprite.html#sprite-sheets-in-vram',1,'']]],
  ['sprite_20sheets_20with_20gfx4snes_349',['Converting Sprite Sheets with gfx4snes',['../tutorial_animation.html#converting-sprite-sheets-with-gfx4snes',1,'']]],
  ['sprite_20size_350',['Converting a sheet: &lt;span class=&quot;tt&quot;&gt;-s&lt;/span&gt; must match the sprite size',['../tutorial_sprites.html#converting-a-sheet--s-must-match-the-sprite-size',1,'']]],
  ['sprite_20size_20modes_351',['Object Size -- All 6 SNES Sprite Size Modes',['../examples_sprites_sprite_sizes.html',1,'examples_sprites']]],
  ['sprite_20sizes_352',['Sprite Sizes',['../tutorial_sprites.html#sprite-sizes',1,'Sprite Sizes'],['../snes_graphics_guide.html#sprite-sizes-1',1,'Sprite Sizes'],['../oam.html#sprite-sizes-2',1,'Sprite Sizes']]],
  ['sprite_20system_353',['1. Initialize the Map and Sprite System',['../examples_games_mapandobjects.html#autotoc_md1-initialize-the-map-and-sprite-system',1,'']]],
  ['sprite_20tiles_354',['Loading Sprite Tiles',['../tutorial_sprites.html#loading-sprite-tiles',1,'']]],
  ['sprite_20to_20background_20collision_355',['Sprite-to-Background Collision',['../tutorial_collision.html#sprite-to-background-collision',1,'']]],
  ['sprite_20to_20sprite_20collision_356',['Sprite-to-Sprite Collision',['../tutorial_collision.html#sprite-to-sprite-collision',1,'']]],
  ['sprite_20vram_20streaming_20for_20animated_20sprites_357',['Dynamic Sprite -- VRAM Streaming for Animated Sprites',['../examples_sprites_dynamic_sprite.html',1,'examples_sprites']]],
  ['sprite_20with_20the_20pad_358',['Drive a sprite with the pad',['../examples_input_move_sprite.html',1,'examples_input']]],
  ['sprite_20y_201_20scanline_20quirk_359',['Sprite Y +1 Scanline Quirk',['../oam.html#sprite-y-1-scanline-quirk',1,'']]],
  ['sprite_20your_20first_20oam_20sprite_360',['Simple Sprite -- Your First OAM Sprite',['../examples_sprites_simple_sprite.html',1,'examples_sprites']]],
  ['sprite_5fswarm_20—_20a_20bouncing_20swarm_20and_20the_20oam_20throughput_20ceiling_361',['sprite_swarm — a bouncing swarm, and the OAM throughput ceiling',['../examples_sprites_sprite_swarm.html',1,'examples_sprites']]],
  ['sprites_362',['Sprites',['../examples_games_breakout.html#autotoc_md4-bricks-are-not-sprites',1,'4. Bricks Are Not Sprites'],['../examples_input_superscope.html#autotoc_md4-sprites',1,'4. Sprites'],['../examples_sprites_dynamic_sprite.html',1,'Dynamic Sprite -- VRAM Streaming for Animated Sprites'],['../examples_games_mapandobjects.html#dynamic-sprites',1,'Dynamic Sprites'],['../tutorial_sprites.html#hiding-sprites',1,'Hiding Sprites'],['../oam.html#hiding-sprites-1',1,'Hiding Sprites'],['../examples_sprites.html',1,'Sprites'],['../examples_by_category.html#sprites',1,'Sprites'],['../snes_graphics_guide.html#sprites-1',1,'Sprites'],['../group__examples.html#sprites-2',1,'Sprites'],['../examples_sprites_dynamic_sprite.html#static-vs-dynamic-sprites',1,'Static vs Dynamic Sprites'],['../hardware_overview.html#tiles-and-sprites',1,'Tiles and Sprites']]],
  ['sprites_363',['sprites',['../tutorial_mosaic.html#autotoc_md-mosaic-does-not-affect-obj-sprites',1,'🟠 Mosaic does not affect OBJ (sprites)'],['../craft_planning.html#autotoc_md2-cgram--256-colours-split-bg-vs-sprites',1,'2. CGRAM — 256 colours, split BG vs sprites']]],
  ['sprites_20animation_20tutorial_364',['Sprites &amp;amp; Animation Tutorial',['../tutorial_sprites.html',1,'index']]],
  ['sprites_20are_20unaffected_365',['Sprites Are Unaffected',['../examples_transitions_mosaic.html#sprites-are-unaffected',1,'']]],
  ['sprites_20as_20ui_20elements_366',['Sprites as UI Elements',['../examples_input_mouse.html#sprites-as-ui-elements',1,'']]],
  ['sprites_20but_20far_20fewer_20per_20line_367',['3. OAM — 128 sprites, but far fewer per line',['../craft_planning.html#autotoc_md3-oam--128-sprites-but-far-fewer-per-line',1,'']]],
  ['sprites_20don_20t_20appear_368',['Sprites don&apos;t appear',['../troubleshooting.html#sprites-dont-appear',1,'']]],
  ['sprites_20per_20mode_369',['3. Two sprites per mode',['../examples_sprites_sprite_sizes.html#autotoc_md3-two-sprites-per-mode',1,'']]],
  ['sprites_20via_20the_20oambuffer_370',['2. Set up sprites via the oambuffer',['../examples_sprites_dynamic_sprite.html#autotoc_md2-set-up-sprites-via-the-oambuffer',1,'']]],
  ['sprites_20with_20force_20blank_371',['2. Load sprites with force blank',['../examples_sprites_sprite_sizes.html#autotoc_md2-load-sprites-with-force-blank',1,'']]],
  ['sqrt_20ship_20in_20the_20lib_20chantier_20b6_202026_2005_2009_372',['&lt;span class=&quot;tt&quot;&gt;atan2&lt;/span&gt; and &lt;span class=&quot;tt&quot;&gt;sqrt&lt;/span&gt; ship in the lib (chantier B6, 2026-05-09)',['../tutorial_math.html#atan2-and-sqrt-ship-in-the-lib-chantier-b6-2026-05-09',1,'']]],
  ['squash_20and_20stretch_20without_20scaling_373',['Squash and stretch without scaling',['../craft_game_feel.html#squash-and-stretch-without-scaling',1,'']]],
  ['sram_374',['SRAM',['../tutorial_sram.html#autotoc_md-cannot-store-pointers-in-sram',1,'🟠 Cannot store pointers in SRAM'],['../examples_memory_save_game.html#autotoc_md2-save-to-sram',1,'2. Save to SRAM'],['../examples_memory_save_game.html#autotoc_md3-load-from-sram',1,'3. Load from SRAM']]],
  ['sram_20access_20requires_20no_20special_20timing_375',['🟠 SRAM access requires no special timing',['../tutorial_sram.html#autotoc_md-sram-access-requires-no-special-timing',1,'']]],
  ['sram_20actually_20is_376',['What SRAM actually is',['../tutorial_sram.html#what-sram-actually-is',1,'']]],
  ['sram_20address_20space_377',['SRAM Address Space',['../examples_memory_save_game.html#sram-address-space',1,'']]],
  ['sram_20battery_20backup_378',['SRAM (Battery Backup)',['../examples_memory.html#sram-battery-backup',1,'']]],
  ['sram_20contents_20on_20first_20boot_20are_20undefined_379',['🔴 SRAM contents on first boot are undefined',['../tutorial_sram.html#autotoc_md-sram-contents-on-first-boot-are-undefined',1,'']]],
  ['sram_20in_20the_20makefile_380',['4. Enable SRAM in the Makefile',['../examples_memory_save_game.html#autotoc_md4-enable-sram-in-the-makefile',1,'']]],
  ['sram_20overview_381',['SRAM Overview',['../sram_8h.html#sram-overview',1,'']]],
  ['sram_20persistence_382',['Save Game -- SRAM Persistence',['../examples_memory_save_game.html',1,'examples_memory']]],
  ['sram_20save_20tutorial_383',['SRAM Save Tutorial',['../tutorial_sram.html',1,'index']]],
  ['sram_20to_20vram_20transfer_384',['SRAM to VRAM Transfer',['../tutorial_superfx.html#sram-to-vram-transfer',1,'']]],
  ['sram_5fsize_20mismatch_20between_20makefile_20and_20code_385',['🔴 &lt;span class=&quot;tt&quot;&gt;SRAM_SIZE&lt;/span&gt; mismatch between Makefile and code',['../tutorial_sram.html#autotoc_md-sram_size-mismatch-between-makefile-and-code',1,'']]],
  ['sramclear_20is_20a_20memset_20not_20a_20write_20protect_386',['🟡 &lt;span class=&quot;tt&quot;&gt;sramClear&lt;/span&gt; is a memset, not a write-protect',['../tutorial_sram.html#autotoc_md-sramclear-is-a-memset-not-a-write-protect',1,'']]],
  ['sramclear_20wrote_20a_20byte_20ramp_20instead_20of_20zeros_20fixed_202026_2009_2015_387',['🟢 &lt;span class=&quot;tt&quot;&gt;sramClear()&lt;/span&gt; wrote a byte ramp instead of zeros (fixed 2026-09-15)',['../KNOWN_LIMITATIONS.html#autotoc_md-sramclear-wrote-a-byte-ramp-instead-of-zeros-fixed-2026-09-15',1,'']]],
  ['sta_20l_20lda_20l_20for_20everything_388',['Use &lt;span class=&quot;tt&quot;&gt;sta.l&lt;/span&gt; / &lt;span class=&quot;tt&quot;&gt;lda.l&lt;/span&gt; for Everything',['../tutorial_sa1.html#use-stal--ldal-for-everything',1,'']]],
  ['stack_389',['Scene Stack',['../examples_basics_scene_stack.html',1,'examples_basics']]],
  ['stack_20recommended_20—_20scene_20module_390',['The scene stack (recommended) — &lt;span class=&quot;tt&quot;&gt;scene&lt;/span&gt; module',['../tutorial_game_states.html#the-scene-stack-recommended--scene-module',1,'']]],
  ['stage_200_20—_20does_20my_20setup_20even_20work_391',['Stage 0 — &quot;Does my setup even work?&quot;',['../learning_path.html#stage-0--does-my-setup-even-work',1,'']]],
  ['stage_201_20—_20can_20i_20put_20something_20on_20screen_392',['Stage 1 — &quot;Can I put something on screen?&quot;',['../learning_path.html#stage-1--can-i-put-something-on-screen',1,'']]],
  ['stage_202_20—_20can_20the_20player_20act_393',['Stage 2 — &quot;Can the player act?&quot;',['../learning_path.html#stage-2--can-the-player-act',1,'']]],
  ['stage_203_20—_20can_20i_20build_20a_20world_394',['Stage 3 — &quot;Can I build a world?&quot;',['../learning_path.html#stage-3--can-i-build-a-world',1,'']]],
  ['stage_204_20—_20can_20i_20make_20it_20feel_20good_395',['Stage 4 — &quot;Can I make it feel good?&quot;',['../learning_path.html#stage-4--can-i-make-it-feel-good',1,'']]],
  ['stage_205_20—_20can_20i_20hold_20it_20all_20together_396',['Stage 5 — &quot;Can I hold it all together?&quot;',['../learning_path.html#stage-5--can-i-hold-it-all-together',1,'']]],
  ['stage_206_20—_20can_20i_20finish_20and_20ship_397',['Stage 6 — &quot;Can I finish and ship?&quot;',['../learning_path.html#stage-6--can-i-finish-and-ship',1,'']]],
  ['starfield_20murmuration_398',['SA-1 Starfield (Murmuration)',['../examples_chips_sa1_starfield.html',1,'examples_chips']]],
  ['start_399',['Start',['../audio_8h.html#quick-start',1,'Quick Start'],['../profile_8h.html#quick-start-1',1,'Quick Start'],['../snesmod_8h.html#quick-start-2',1,'Quick Start']]],
  ['start_20at_20cgram_20128_400',['Trap 3: sprite palettes start at CGRAM 128',['../migrating_pvsneslib.html#trap-3-sprite-palettes-start-at-cgram-128',1,'']]],
  ['start_20at_20cgram_20offset_20128_20not_200_401',['🟡 Sprite palettes start at CGRAM offset 128, not 0',['../KNOWN_LIMITATIONS.html#autotoc_md-sprite-palettes-start-at-cgram-offset-128-not-0',1,'']]],
  ['start_20here_402',['Start Here',['../index.html#start-here',1,'']]],
  ['started_403',['Started',['../tutorial_sa1.html#getting-started',1,'Getting Started'],['../tutorial_superfx.html#getting-started-1',1,'Getting Started'],['../group__examples.html#getting-started-3',1,'Getting Started']]],
  ['started_404',['Getting started',['../faq.html#getting-started-2',1,'']]],
  ['started_20with_20opensnes_405',['Getting Started with OpenSNES',['../getting_started.html',1,'index']]],
  ['state_406',['Player State',['../examples_input_two_players.html#player-state',1,'']]],
  ['state_407',['&lt;span class=&quot;tt&quot;&gt;luna state&lt;/span&gt;',['../tools_luna.html#luna-state',1,'']]],
  ['state_20changes_408',['Input and State Changes',['../tutorial_animation.html#input-and-state-changes',1,'']]],
  ['state_20is_20not_20reset_20by_20consoleinit_409',['🟡 Mosaic state is not reset by &lt;span class=&quot;tt&quot;&gt;consoleInit&lt;/span&gt;',['../tutorial_mosaic.html#autotoc_md-mosaic-state-is-not-reset-by-consoleinit',1,'']]],
  ['state_20machine_410',['State Machine',['../examples_input_superscope.html#autotoc_md6-state-machine',1,'6. State Machine'],['../snes_graphics_guide.html#animation-state-machine',1,'Animation State Machine']]],
  ['state_20machine_411',['2. State machine',['../examples_sprites_animated_sprite.html#autotoc_md2-state-machine',1,'']]],
  ['state_20machine_20summary_412',['State Machine Summary',['../tutorial_game_states.html#state-machine-summary',1,'']]],
  ['state_20machine_20under_20the_20hood_413',['The manual state machine (under the hood)',['../tutorial_game_states.html#the-manual-state-machine-under-the-hood',1,'']]],
  ['state_20struct_414',['5. The Game State Struct',['../examples_scrolling_continuous_scroll.html#autotoc_md5-the-game-state-struct',1,'']]],
  ['state_20survives_20between_20scenes_415',['🟡 Window state survives between scenes',['../tutorial_window.html#autotoc_md-window-state-survives-between-scenes',1,'']]],
  ['state_20transitions_416',['State Transitions',['../tutorial_game_states.html#state-transitions',1,'']]],
  ['states_417',['States',['../tutorial_game_states.html#vram-reload-between-states',1,'VRAM Reload Between States'],['../tutorial_game_states.html#what-are-game-states',1,'What Are Game States?']]],
  ['states_20and_20sprite_20sheets_418',['Animated Sprite -- Direction States and Sprite Sheets',['../examples_sprites_animated_sprite.html',1,'examples_sprites']]],
  ['states_20tutorial_419',['Game States Tutorial',['../tutorial_game_states.html',1,'index']]],
  ['static_20colour_20gradient_20—_20examples_20hdma_20gradient_5fcolors_420',['Static colour gradient — &lt;span class=&quot;tt&quot;&gt;examples/hdma/gradient_colors&lt;/span&gt;',['../tutorial_hdma.html#static-colour-gradient--exampleshdmagradient_colors',1,'']]],
  ['static_20moving_20layers_421',['Mixed Scroll (Static + Moving Layers)',['../tutorial_scrolling.html#mixed-scroll-static--moving-layers',1,'']]],
  ['static_20shapes_20vs_20animated_20shapes_422',['Static shapes vs animated shapes',['../tutorial_window.html#static-shapes-vs-animated-shapes',1,'']]],
  ['static_20variables_20with_20initializers_423',['Static variables with initializers',['../troubleshooting.html#static-variables-with-initializers',1,'']]],
  ['static_20vs_20dynamic_20sprites_424',['Static vs Dynamic Sprites',['../examples_sprites_dynamic_sprite.html#static-vs-dynamic-sprites',1,'']]],
  ['stationary_20window_20—_20examples_20windows_20window_425',['Stationary window — &lt;span class=&quot;tt&quot;&gt;examples/windows/window&lt;/span&gt;',['../tutorial_hdma.html#stationary-window--exampleswindowswindow',1,'']]],
  ['status_426',['Status',['../registers.html#autotoc_md4210---rdnmi-nmi-status',1,'$4210 - RDNMI (NMI Status)'],['../registers.html#autotoc_md4211---timeup-irq-status',1,'$4211 - TIMEUP (IRQ Status)'],['../registers.html#autotoc_md4212---hvbjoy-blankjoypad-status',1,'$4212 - HVBJOY (Blank/Joypad Status)']]],
  ['status_427',['Roadmap status',['../examples_games_shmup_1942.html#roadmap-status',1,'']]],
  ['status_20codes_428',['Status Codes',['../examples_chips_sa1_hello.html#status-codes',1,'Status Codes'],['../examples_chips_superfx_hello.html#status-codes-1',1,'Status Codes']]],
  ['stay_20in_20force_20blank_429',['1. Initialize and Stay in Force Blank',['../examples_backgrounds_mode1_lz77.html#autotoc_md1-initialize-and-stay-in-force-blank',1,'']]],
  ['step_201_20—_20the_20makefile_430',['Step 1 — the Makefile',['../migrating_pvsneslib.html#step-1--the-makefile',1,'']]],
  ['step_202_20—_20the_20five_20traps_431',['Step 2 — the five traps',['../migrating_pvsneslib.html#step-2--the-five-traps',1,'']]],
  ['step_203_20—_20constructs_20cc65816_20refuses_432',['Step 3 — constructs cc65816 refuses',['../migrating_pvsneslib.html#step-3--constructs-cc65816-refuses',1,'']]],
  ['step_204_20—_20the_20api_20map_433',['Step 4 — the API map',['../migrating_pvsneslib.html#step-4--the-api-map',1,'']]],
  ['step_205_20—_20assets_434',['Step 5 — assets',['../migrating_pvsneslib.html#step-5--assets',1,'']]],
  ['step_206_20—_20when_20it_20still_20looks_20wrong_435',['Step 6 — when it still looks wrong',['../migrating_pvsneslib.html#step-6--when-it-still-looks-wrong',1,'']]],
  ['steps_436',['Steps',['../examples.html#level-1----first-steps',1,'Level 1 &amp;ndash; First Steps'],['../tutorial_animation.html#next-steps',1,'Next Steps'],['../tutorial_audio.html#next-steps-1',1,'Next Steps'],['../tutorial_collision.html#next-steps-2',1,'Next Steps'],['../tutorial_game_states.html#next-steps-3',1,'Next Steps'],['../tutorial_graphics.html#next-steps-4',1,'Next Steps'],['../tutorial_input.html#next-steps-5',1,'Next Steps'],['../tutorial_scrolling.html#next-steps-6',1,'Next Steps'],['../tutorial_sprites.html#next-steps-7',1,'Next Steps']]],
  ['still_20for_437',['What Mesen2 is still for',['../tutorial_debugging.html#what-mesen2-is-still-for',1,'']]],
  ['still_20looks_20wrong_438',['Step 6 — when it still looks wrong',['../migrating_pvsneslib.html#step-6--when-it-still-looks-wrong',1,'']]],
  ['still_20missing_3a_20pow_20exp_20log_439',['What&apos;s still missing: &lt;span class=&quot;tt&quot;&gt;pow&lt;/span&gt;, &lt;span class=&quot;tt&quot;&gt;exp&lt;/span&gt;, &lt;span class=&quot;tt&quot;&gt;log&lt;/span&gt;',['../tutorial_math.html#whats-still-missing-pow-exp-log',1,'']]],
  ['stop_440',['2. NOP Padding Before STOP',['../tutorial_superfx.html#autotoc_md2-nop-padding-before-stop',1,'']]],
  ['stopping_20movement_20slide_20along_20walls_441',['Stopping Movement (Slide Along Walls)',['../tutorial_collision.html#stopping-movement-slide-along-walls',1,'']]],
  ['store_20pointers_20in_20sram_442',['🟠 Cannot store pointers in SRAM',['../tutorial_sram.html#autotoc_md-cannot-store-pointers-in-sram',1,'']]],
  ['story_443',['Why the envelope differs from the original (a true story)',['../examples_audio_pitch_mod.html#why-the-envelope-differs-from-the-original-a-true-story',1,'']]],
  ['strange_444',['When the window register acts strange',['../tutorial_window.html#when-the-window-register-acts-strange',1,'']]],
  ['stream_20cannot_20be_20resynced_20—_20let_20the_20lib_20close_20it_445',['🟡 A Raster stream cannot be &quot;resynced&quot; — let the lib close it',['../tutorial_dsp1.html#autotoc_md-a-raster-stream-cannot-be-resynced--let-the-lib-close-it',1,'']]],
  ['stream_20it_446',['The level is bigger than VRAM — so stream it',['../craft_tiles_to_levels.html#the-level-is-bigger-than-vram--so-stream-it',1,'']]],
  ['streaming_447',['Map Engine Streaming',['../examples_maps_tiled.html#map-engine-streaming',1,'']]],
  ['streaming_448',['When HDMA isn&apos;t enough: H-timer IRQ streaming',['../tutorial_hdma.html#when-hdma-isnt-enough-h-timer-irq-streaming',1,'']]],
  ['streaming_20for_20animated_20sprites_449',['Dynamic Sprite -- VRAM Streaming for Animated Sprites',['../examples_sprites_dynamic_sprite.html',1,'examples_sprites']]],
  ['streaming_20pattern_450',['The Streaming Pattern',['../tutorial_scrolling.html#the-streaming-pattern',1,'']]],
  ['streaming_20tips_451',['Streaming Tips',['../tutorial_scrolling.html#streaming-tips',1,'']]],
  ['streaming_3a_20the_20column_20pipeline_452',['3. Streaming: The Column Pipeline',['../examples_games_likemario.html#autotoc_md3-streaming-the-column-pipeline',1,'']]],
  ['streams_20m16_20background_20wants_20q16_453',['🟡 &lt;span class=&quot;tt&quot;&gt;map&lt;/span&gt; streams &lt;span class=&quot;tt&quot;&gt;.m16&lt;/span&gt;; &lt;span class=&quot;tt&quot;&gt;background&lt;/span&gt; wants &lt;span class=&quot;tt&quot;&gt;.q16&lt;/span&gt;',['../tutorial_map.html#autotoc_md-map-streams-m16-background-wants-q16',1,'']]],
  ['stretch_20without_20scaling_454',['Squash and stretch without scaling',['../craft_game_feel.html#squash-and-stretch-without-scaling',1,'']]],
  ['stride_20to_20how_20the_20sheet_20was_20converted_455',['🟡 Match &lt;span class=&quot;tt&quot;&gt;base_tile&lt;/span&gt;/&lt;span class=&quot;tt&quot;&gt;stride&lt;/span&gt; to how the sheet was converted',['../tutorial_panel.html#autotoc_md-match-base_tilestride-to-how-the-sheet-was-converted',1,'']]],
  ['string_456',['Print a string',['../examples_text_print_string.html',1,'examples_text']]],
  ['struct_457',['5. The Game State Struct',['../examples_scrolling_continuous_scroll.html#autotoc_md5-the-game-state-struct',1,'']]],
  ['struct_458',['The Scene struct',['../examples_basics_scene_stack.html#the-scene-struct',1,'']]],
  ['struct_20—_20the_20tilemap_20is_20yours_459',['The &lt;span class=&quot;tt&quot;&gt;Panel&lt;/span&gt; struct — the tilemap is yours',['../tutorial_panel.html#the-panel-struct--the-tilemap-is-yours',1,'']]],
  ['struct_20assignment_20by_20value_20are_20refused_460',['🟡 Struct parameters, struct returns and struct assignment by value are refused',['../KNOWN_LIMITATIONS.html#autotoc_md-struct-parameters-struct-returns-and-struct-assignment-by-value-are-refused',1,'']]],
  ['struct_20parameters_20struct_20returns_20and_20struct_20assignment_20by_20value_20are_20refused_461',['🟡 Struct parameters, struct returns and struct assignment by value are refused',['../KNOWN_LIMITATIONS.html#autotoc_md-struct-parameters-struct-returns-and-struct-assignment-by-value-are-refused',1,'']]],
  ['struct_20pattern_20required_462',['Struct Pattern (Required)',['../examples_input_two_players.html#struct-pattern-required',1,'']]],
  ['struct_20returns_20and_20struct_20assignment_20by_20value_20are_20refused_463',['🟡 Struct parameters, struct returns and struct assignment by value are refused',['../KNOWN_LIMITATIONS.html#autotoc_md-struct-parameters-struct-returns-and-struct-assignment-by-value-are-refused',1,'']]],
  ['structure_464',['Structure',['../examples_sprites_metasprite.html#metaspriteitem-structure',1,'MetaspriteItem Structure'],['../tutorial_sprites.html#oam-structure',1,'OAM Structure'],['../oam.html#oam-structure-1',1,'OAM Structure'],['../getting_started.html#project-structure',1,'Project Structure'],['../examples_backgrounds_mode1_bg3_priority.html#project-structure-1',1,'Project Structure'],['../examples_backgrounds_mode1_lz77.html#project-structure-2',1,'Project Structure'],['../examples_games_mapandobjects.html#project-structure-3',1,'Project Structure'],['../examples_hdma_gradient_colors.html#project-structure-4',1,'Project Structure'],['../examples_input_mouse.html#project-structure-5',1,'Project Structure'],['../examples_maps_dynamic_map.html#project-structure-6',1,'Project Structure'],['../examples_maps_slope_collision.html#project-structure-7',1,'Project Structure'],['../examples_maps_tiled.html#project-structure-8',1,'Project Structure'],['../examples_memory_hirom_demo.html#project-structure-9',1,'Project Structure'],['../examples_memory_save_game.html#project-structure-10',1,'Project Structure'],['../examples_mode7_dsp1_ground.html#project-structure-11',1,'Project Structure'],['../examples_mode7_perspective.html#project-structure-12',1,'Project Structure'],['../examples_mode7_rotate_scale.html#project-structure-13',1,'Project Structure'],['../examples_scrolling_mixed_scroll.html#project-structure-14',1,'Project Structure'],['../examples_scrolling_parallax_scroll.html#project-structure-15',1,'Project Structure'],['../examples_sprites_animated_sprite.html#project-structure-16',1,'Project Structure'],['../examples_sprites_dynamic_sprite.html#project-structure-17',1,'Project Structure'],['../examples_sprites_metasprite.html#project-structure-18',1,'Project Structure'],['../examples_sprites_simple_sprite.html#project-structure-19',1,'Project Structure'],['../examples_sprites_sprite_sizes.html#project-structure-20',1,'Project Structure'],['../examples_transitions_mosaic.html#project-structure-21',1,'Project Structure'],['../examples_windows_transparent_window.html#project-structure-22',1,'Project Structure'],['../examples_windows_window.html#project-structure-23',1,'Project Structure'],['../snes_graphics_guide.html#tilemap-structure',1,'Tilemap Structure']]],
  ['structure_465',['1. Define a save structure',['../examples_memory_save_game.html#autotoc_md1-define-a-save-structure',1,'']]],
  ['structure_20544_20bytes_20total_466',['OAM Structure (544 bytes total)',['../snes_graphics_guide.html#oam-structure-544-bytes-total',1,'']]],
  ['structure_209_20bytes_467',['Block Structure (9 bytes)',['../snes_sound_guide.html#block-structure-9-bytes',1,'']]],
  ['structuring_20a_20game_468',['Structuring a game',['../api_index.html#structuring-a-game',1,'']]],
  ['stx_20l_20—_20save_20x_20through_20a_469',['No &lt;span class=&quot;tt&quot;&gt;stx.l&lt;/span&gt; — Save X Through A',['../tutorial_sa1.html#no-stxl--save-x-through-a',1,'']]],
  ['style_20demo_470',['mode7_flying — a Pilotwings-style demo',['../examples_games_mode7_flying.html',1,'examples_games']]],
  ['style_20guide_471',['OpenSNES Code Style Guide',['../code_style.html',1,'index']]],
  ['style_20mini_20game_472',['mode7_racing — an F-Zero-style mini game',['../examples_games_mode7_racing.html',1,'examples_games']]],
  ['sub_20mean_20here_473',['What &quot;main&quot; and &quot;sub&quot; mean here',['../tutorial_colormath.html#what-main-and-sub-mean-here',1,'']]],
  ['sub_20screen_474',['Sub Screen',['../examples_color_transparency.html#color-math-main-screen--sub-screen',1,'Color Math: Main Screen + Sub Screen'],['../colormath_8h.html#main-screen-vs-sub-screen',1,'Main Screen vs Sub Screen']]],
  ['sub_20screen_20enable_475',['$212D - TS (Sub Screen Enable)',['../registers.html#autotoc_md212d---ts-sub-screen-enable',1,'']]],
  ['sub_20screen_20only_20trap_476',['🔴 The &quot;BG2 is sub-screen-only&quot; trap',['../tutorial_colormath.html#autotoc_md-the-bg2-is-sub-screen-only-trap',1,'']]],
  ['submitting_20code_477',['Submitting Code',['../contributing.html#submitting-code',1,'']]],
  ['submodule_20drift_20caught_20by_20verify_20toolchain_478',['🟢 Compiler submodule drift (caught by verify-toolchain)',['../KNOWN_LIMITATIONS.html#autotoc_md-compiler-submodule-drift-caught-by-verify-toolchain',1,'']]],
  ['suggesting_20features_479',['Suggesting Features',['../contributing.html#suggesting-features',1,'']]],
  ['summary_480',['State Machine Summary',['../tutorial_game_states.html#state-machine-summary',1,'']]],
  ['summary_481',['Cycle cost summary',['../tutorial_math.html#cycle-cost-summary',1,'']]],
  ['super_20mario_20kart_20floor_482',['DSP-1 Ground — the Super Mario Kart floor',['../examples_mode7_dsp1_ground.html',1,'examples_mode7']]],
  ['super_20mario_20kart_20floor_20via_20the_20dsp_201_20—_20examples_20mode7_20dsp1_5fground_483',['The Super Mario Kart floor via the DSP-1 — &lt;span class=&quot;tt&quot;&gt;examples/mode7/dsp1_ground&lt;/span&gt;',['../tutorial_mode7.html#the-super-mario-kart-floor-via-the-dsp-1--examplesmode7dsp1_ground',1,'']]],
  ['super_20scope_484',['Super Scope',['../examples_input_superscope.html',1,'examples_input']]],
  ['superfree_20assets_20in_20any_20bank_20just_20work_485',['🟢 SUPERFREE assets in any bank just work',['../tutorial_dma.html#autotoc_md-superfree-assets-in-any-bank-just-work',1,'']]],
  ['superfx_486',['What Is SuperFX?',['../tutorial_superfx.html#what-is-superfx',1,'']]],
  ['superfx_203d_20cube_487',['SuperFX 3D Cube',['../examples_chips_superfx_3d.html',1,'examples_chips']]],
  ['superfx_20assembly_20rules_488',['SuperFX Assembly Rules',['../tutorial_superfx.html#superfx-assembly-rules',1,'']]],
  ['superfx_20c_20support_20is_20intentionally_20absent_489',['🟡 SuperFX C support is intentionally absent',['../KNOWN_LIMITATIONS.html#autotoc_md-superfx-c-support-is-intentionally-absent',1,'']]],
  ['superfx_20cartridge_490',['SuperFX Cartridge',['../memory_map.html#superfx-cartridge',1,'']]],
  ['superfx_20gsu_491',['SuperFX (GSU)',['../examples_by_category.html#superfx-gsu',1,'']]],
  ['superfx_20gsu_20registers_20_243000_20_24303f_492',['SuperFX / GSU Registers ($3000-$303F)',['../registers.html#superfx--gsu-registers-3000-303f',1,'']]],
  ['superfx_20gsu_20tutorial_493',['SuperFX (GSU) Tutorial',['../tutorial_superfx.html',1,'index']]],
  ['superfx_20hello_494',['SuperFX Hello',['../examples_chips_superfx_hello.html',1,'examples_chips']]],
  ['superfx_20in_20your_20makefile_495',['1. Enable SuperFX in Your Makefile',['../tutorial_superfx.html#autotoc_md1-enable-superfx-in-your-makefile',1,'']]],
  ['superfx_20sa_201_20chips_3a_20covered_20natively_20resolved_20by_20the_20luna_20migration_496',['🟢 SuperFX / SA-1 chips: covered natively (resolved by the luna migration)',['../KNOWN_LIMITATIONS.html#autotoc_md-superfx--sa-1-chips-covered-natively-resolved-by-the-luna-migration',1,'']]],
  ['support_497',['Multitap Support',['../examples_input_two_players.html#multitap-support',1,'']]],
  ['support_20is_20intentionally_20absent_498',['🟡 SuperFX C support is intentionally absent',['../KNOWN_LIMITATIONS.html#autotoc_md-superfx-c-support-is-intentionally-absent',1,'']]],
  ['surfaced_499',['surfaced',['../examples_mode7_perspective_rotate.html#two-integration-lessons-this-port-surfaced',1,'Two integration lessons this port surfaced'],['../examples_color_hicolor_1792.html#two-sdk-bugs-this-port-surfaced',1,'Two SDK bugs this port surfaced']]],
  ['survives_20a_20dialog_20box_500',['panel_hud — a HUD that survives a dialog box',['../examples_basics_panel_hud.html',1,'examples_basics']]],
  ['survives_20between_20scenes_501',['🟡 Window state survives between scenes',['../tutorial_window.html#autotoc_md-window-state-survives-between-scenes',1,'']]],
  ['swap_20tilemap_20entries_502',['Approach 1: Swap Tilemap Entries',['../tutorial_animation.html#approach-1-swap-tilemap-entries',1,'']]],
  ['swapping_20apu_20programs_503',['Hot-swapping APU programs',['../tutorial_audio.html#hot-swapping-apu-programs',1,'']]],
  ['swapping_20apu_20programs_20at_20runtime_504',['apu_switch — hot-swapping APU programs at runtime',['../examples_audio_apu_switch.html',1,'examples_audio']]],
  ['swarm_20and_20the_20oam_20throughput_20ceiling_505',['sprite_swarm — a bouncing swarm, and the OAM throughput ceiling',['../examples_sprites_sprite_swarm.html',1,'examples_sprites']]],
  ['switch_506',['Why a framework instead of a switch',['../examples_basics_scene_stack.html#why-a-framework-instead-of-a-switch',1,'']]],
  ['switched_20on_507',['🟡 The multitap (5-player) path is present but cannot be switched on',['../KNOWN_LIMITATIONS.html#autotoc_md-the-multitap-5-player-path-is-present-but-cannot-be-switched-on',1,'']]],
  ['switching_20layers_508',['Switching Layers',['../examples_windows_window.html#switching-layers',1,'']]],
  ['switching_20mid_20frame_509',['Mode Switching Mid-Frame',['../examples_mode7_perspective.html#mode-switching-mid-frame',1,'']]],
  ['symbols_510',['Working with symbols',['../tutorial_debugging.html#working-with-symbols',1,'']]],
  ['sync_511',['4. Main Loop: Update, Draw, Sync',['../examples_games_mapandobjects.html#autotoc_md4-main-loop-update-draw-sync',1,'']]],
  ['sync_20producer_20consumer_512',['Pattern 1: Flag Sync (Producer/Consumer)',['../tutorial_sa1.html#pattern-1-flag-sync-producerconsumer',1,'']]],
  ['system_513',['System',['../examples_games_mapandobjects.html#autotoc_md1-initialize-the-map-and-sprite-system',1,'1. Initialize the Map and Sprite System'],['../snes_sound_guide.html#echo-system',1,'Echo System'],['../examples_backgrounds_mode1_bg3_priority.html#mode-1-priority-system',1,'Mode 1 Priority System'],['../examples_windows_window.html#snes-window-system',1,'SNES Window System']]],
  ['system_514',['Coordinate system',['../tutorial_mode7.html#coordinate-system',1,'']]],
  ['system_20bg1_515',['2. Text System (BG1)',['../examples_input_superscope.html#autotoc_md2-text-system-bg1',1,'']]],
  ['systems_516',['Memory Systems',['../snes_graphics_guide.html#memory-systems',1,'']]]
];
