var searchData=
[
  ['l_20—_20save_20x_20through_20a_0',['No &lt;span class=&quot;tt&quot;&gt;stx.l&lt;/span&gt; — Save X Through A',['../tutorial_sa1.html#autotoc_md299',1,'']]],
  ['l_20for_20everything_1',['Use &lt;span class=&quot;tt&quot;&gt;sta.l&lt;/span&gt; / &lt;span class=&quot;tt&quot;&gt;lda.l&lt;/span&gt; for Everything',['../tutorial_sa1.html#autotoc_md297',1,'']]],
  ['l_20lda_20l_20for_20everything_2',['Use &lt;span class=&quot;tt&quot;&gt;sta.l&lt;/span&gt; / &lt;span class=&quot;tt&quot;&gt;lda.l&lt;/span&gt; for Everything',['../tutorial_sa1.html#autotoc_md297',1,'']]],
  ['l_20table_20x_3',['ROM Table Lookups with &lt;span class=&quot;tt&quot;&gt;lda.l table,x&lt;/span&gt;',['../tutorial_sa1.html#autotoc_md298',1,'']]],
  ['labels_4',['Labels',['../code_style.html#autotoc_md462',1,'']]],
  ['landing_5',['Snapping to Tile Grid (Platformer Landing)',['../tutorial_collision.html#autotoc_md126',1,'']]],
  ['large_20dma_6',['Force Blank for Large DMA',['../examples_graphics_sprites_object_size.html#autotoc_md1274',1,'']]],
  ['large_20or_20linker_20errors_20about_20size_7',['&quot;ROM too large&quot; or linker errors about size',['../troubleshooting.html#autotoc_md578',1,'']]],
  ['large_20soundbank_20music_8',['SNESMOD Large Soundbank Music',['../examples_audio_snesmod_music_large.html',1,'examples_audio']]],
  ['latency_9',['Input Latency',['../examples_input_two_players.html#autotoc_md1380',1,'']]],
  ['launch_20from_20c_10',['4. Launch from C',['../tutorial_superfx.html#autotoc_md361',1,'']]],
  ['layer_11',['Layer',['../examples_graphics_backgrounds_mode1.html#autotoc_md972',1,'Exercise 1: Add a Second Layer'],['../examples_graphics_effects_parallax_scrolling.html#autotoc_md1156',1,'Why This Works with One Layer']]],
  ['layer_12',['layer',['../tutorial_mode7.html#autotoc_md264',1,'🔴 Single BG layer'],['../tutorial_mode7.html#autotoc_md269',1,'🟡 Out-of-bounds with &lt;span class=&quot;tt&quot;&gt;MODE7_TRANSPARENT&lt;/span&gt; shows the backdrop, not a layer']]],
  ['layer_202bpp_20background_13',['Mode 0 — 4-Layer 2bpp Background',['../examples_graphics_backgrounds_mode0.html',1,'examples_graphics_backgrounds']]],
  ['layer_20only_14',['One Layer Only',['../examples_graphics_backgrounds_mode7.html#autotoc_md1031',1,'']]],
  ['layer_20over_20backgrounds_15',['Mode 1 BG3 High Priority -- HUD Layer Over Backgrounds',['../examples_graphics_backgrounds_mode1_bg3_priority.html',1,'examples_graphics_backgrounds']]],
  ['layers_16',['Layers',['../tutorial_scrolling.html#autotoc_md309',1,'Mixed Scroll (Static + Moving Layers)'],['../examples_graphics_effects_window.html#autotoc_md1208',1,'Switching Layers']]],
  ['layers_17',['1. Set up three background layers',['../examples_graphics_backgrounds_mode1_bg3_priority.html#autotoc_md987',1,'']]],
  ['layers_20two_20speeds_18',['1. Two Layers, Two Speeds',['../examples_graphics_backgrounds_continuous_scroll.html#autotoc_md912',1,'']]],
  ['layout_19',['Layout',['../examples_games_likemario.html#autotoc_md858',1,'2. The VRAM Layout'],['../examples_input_two_players.html#autotoc_md1381',1,'Button Layout'],['../examples_basics_collision_demo.html#autotoc_md788',1,'Collision Map Layout'],['../tutorial_superfx.html#autotoc_md370',1,'Column-Major Tile Layout'],['../examples_input.html#autotoc_md1324',1,'Joypad Bit Layout'],['../examples_audio_snesmod_music.html#autotoc_md730',1,'Memory Layout'],['../mode7_8h.html#autotoc_md46',1,'Mode 7 VRAM Layout'],['../examples_maps_dynamic_map.html#autotoc_md1387',1,'SC_64x64 Tilemap Layout'],['../tutorial_input.html#autotoc_md215',1,'SNES Controller Layout'],['../tutorial_animation.html#autotoc_md72',1,'Sprite Sheet Layout'],['../snes_graphics_guide.html#autotoc_md490',1,'VRAM Layout'],['../examples_graphics_backgrounds_mode1.html#autotoc_md962',1,'VRAM Layout'],['../examples_graphics_backgrounds_mode1_bg3_priority.html#autotoc_md994',1,'VRAM Layout'],['../examples_graphics_effects_window.html#autotoc_md1212',1,'VRAM Layout'],['../examples_graphics_sprites_object_size.html#autotoc_md1275',1,'VRAM Layout']]],
  ['layout_20',['1. Sprite sheet layout',['../examples_graphics_sprites_animated_sprite.html#autotoc_md1225',1,'']]],
  ['layout_20256_20colors_20×_202_20bytes_21',['CGRAM Layout (256 colors × 2 bytes)',['../snes_graphics_guide.html#autotoc_md495',1,'']]],
  ['layout_20and_20oam_20tile_20numbers_22',['VRAM Tile Layout and OAM Tile Numbers',['../examples_graphics_sprites_metasprite.html#autotoc_md1258',1,'']]],
  ['layout_20convention_23',['I-RAM Layout Convention',['../tutorial_sa1.html#autotoc_md295',1,'']]],
  ['layout_20for_20text_24',['VRAM Layout for Text',['../examples_text.html#autotoc_md1520',1,'']]],
  ['layout_20lorom_25',['Memory Layout (LoROM)',['../sram_8h.html#autotoc_md61',1,'']]],
  ['layout_20mode_201_26',['Recommended Layout (Mode 1)',['../snes_graphics_guide.html#autotoc_md491',1,'']]],
  ['layout_20planning_27',['VRAM Layout Planning',['../examples_graphics_backgrounds_mixed_scroll.html#autotoc_md932',1,'']]],
  ['lda_20l_20for_20everything_28',['Use &lt;span class=&quot;tt&quot;&gt;sta.l&lt;/span&gt; / &lt;span class=&quot;tt&quot;&gt;lda.l&lt;/span&gt; for Everything',['../tutorial_sa1.html#autotoc_md297',1,'']]],
  ['lda_20l_20table_20x_29',['ROM Table Lookups with &lt;span class=&quot;tt&quot;&gt;lda.l table,x&lt;/span&gt;',['../tutorial_sa1.html#autotoc_md298',1,'']]],
  ['learn_30',['Learn',['../examples_audio_snesmod_music_hirom.html#autotoc_md755',1,'What You&apos;ll Learn'],['../examples_audio_snesmod_music_large.html#autotoc_md759',1,'What You&apos;ll Learn'],['../examples_audio_snesmod_sfx.html#autotoc_md764',1,'What You&apos;ll Learn'],['../examples_basics_collision_demo.html#autotoc_md781',1,'What You&apos;ll Learn'],['../examples_basics_random.html#autotoc_md799',1,'What You&apos;ll Learn'],['../examples_basics_scene_stack.html#autotoc_md809',1,'What You&apos;ll Learn'],['../examples_basics_timer.html#autotoc_md817',1,'What You&apos;ll Learn'],['../examples_games_breakout.html#autotoc_md826',1,'What You&apos;ll Learn'],['../examples_games_likemario.html#autotoc_md854',1,'What You&apos;ll Learn'],['../examples_games_mapandobjects.html#autotoc_md878',1,'What You&apos;ll Learn'],['../examples_graphics_backgrounds_continuous_scroll.html#autotoc_md909',1,'What You&apos;ll Learn'],['../examples_graphics_backgrounds_mixed_scroll.html#autotoc_md929',1,'What You&apos;ll Learn'],['../examples_graphics_backgrounds_mode1_lz77.html#autotoc_md997',1,'What You&apos;ll Learn'],['../examples_graphics_effects_hdma_wave.html#autotoc_md1110',1,'What You&apos;ll Learn'],['../examples_graphics_effects_superfx_3d.html#autotoc_md1169',1,'What You&apos;ll Learn'],['../examples_graphics_effects_transparency.html#autotoc_md1175',1,'What You&apos;ll Learn'],['../examples_graphics_sprites_dynamic_metasprite.html#autotoc_md1236',1,'What You&apos;ll Learn'],['../examples_graphics_sprites_metasprite.html#autotoc_md1254',1,'What You&apos;ll Learn'],['../examples_input_controller.html#autotoc_md1300',1,'What You&apos;ll Learn'],['../examples_input_mouse.html#autotoc_md1308',1,'What You&apos;ll Learn'],['../examples_input_superscope.html#autotoc_md1330',1,'What You&apos;ll Learn'],['../examples_maps_dynamic_map.html#autotoc_md1384',1,'What You&apos;ll Learn'],['../examples_maps_mapscroll.html#autotoc_md1394',1,'What You&apos;ll Learn'],['../examples_maps_slopemario.html#autotoc_md1411',1,'What You&apos;ll Learn'],['../examples_maps_tiled.html#autotoc_md1421',1,'What You&apos;ll Learn'],['../examples_memory_sa1_hello.html#autotoc_md1452',1,'What You&apos;ll Learn'],['../examples_memory_sa1_starfield.html#autotoc_md1456',1,'What You&apos;ll Learn'],['../examples_memory_superfx_hello.html#autotoc_md1478',1,'What You&apos;ll Learn'],['../examples_text_hello_world.html#autotoc_md1494',1,'What You&apos;ll Learn'],['../examples_text_text_test.html#autotoc_md1523',1,'What You&apos;ll Learn']]],
  ['learn_20snes_20development_31',['Learn SNES Development',['../learning_path.html',1,'index']]],
  ['learning_20objectives_32',['Learning Objectives',['../examples_audio_snesmod_music.html#autotoc_md704',1,'Learning Objectives'],['../examples_graphics_backgrounds_mode1.html#autotoc_md947',1,'Learning Objectives'],['../examples_graphics_effects_fading.html#autotoc_md1056',1,'Learning Objectives'],['../examples_input_two_players.html#autotoc_md1342',1,'Learning Objectives']]],
  ['learning_20path_33',['Learning Path',['../examples.html#autotoc_md1482',1,'']]],
  ['left_20right_20is_20an_20empty_20window_34',['&lt;span class=&quot;tt&quot;&gt;left &amp;gt; right&lt;/span&gt; is an &quot;empty&quot; window',['../tutorial_window.html#autotoc_md378',1,'']]],
  ['legacy_20—_20read_20the_20warning_20above_20before_20using_35',['Quick Start (legacy — read the warning above before using)',['../audio_8h.html#autotoc_md11',1,'']]],
  ['letters_20in_20hex_36',['2. Drawing Letters in Hex',['../examples_text_hello_world.html#autotoc_md1498',1,'']]],
  ['level_37',['Making Your Own Level',['../examples_maps_tiled.html#autotoc_md1430',1,'']]],
  ['level_201_20ndash_20first_20steps_38',['Level 1 &amp;ndash; First Steps',['../examples.html#autotoc_md1483',1,'']]],
  ['level_201_3a_20first_20steps_39',['Level 1: First Steps',['../learning_path.html#autotoc_md419',1,'']]],
  ['level_202_20ndash_20graphics_20fundamentals_40',['Level 2 &amp;ndash; Graphics Fundamentals',['../examples.html#autotoc_md1484',1,'']]],
  ['level_202_3a_20graphics_20fundamentals_41',['Level 2: Graphics Fundamentals',['../learning_path.html#autotoc_md420',1,'']]],
  ['level_203_20ndash_20scrolling_20and_20effects_42',['Level 3 &amp;ndash; Scrolling and Effects',['../examples.html#autotoc_md1485',1,'']]],
  ['level_203_3a_20scrolling_20and_20effects_43',['Level 3: Scrolling and Effects',['../learning_path.html#autotoc_md421',1,'']]],
  ['level_204_20ndash_20advanced_20topics_44',['Level 4 &amp;ndash; Advanced Topics',['../examples.html#autotoc_md1486',1,'']]],
  ['level_204_3a_20advanced_20topics_45',['Level 4: Advanced Topics',['../learning_path.html#autotoc_md422',1,'']]],
  ['level_205_20ndash_20maps_20and_20complete_20projects_46',['Level 5 &amp;ndash; Maps and Complete Projects',['../examples.html#autotoc_md1487',1,'']]],
  ['level_205_3a_20maps_20and_20complete_20projects_47',['Level 5: Maps and Complete Projects',['../learning_path.html#autotoc_md423',1,'']]],
  ['level_206_3a_20enhancement_20chips_48',['Level 6: Enhancement Chips',['../learning_path.html#autotoc_md424',1,'']]],
  ['levels_49',['Levels',['../examples_graphics_effects_hdma_wave.html#autotoc_md1115',1,'3. Seven Amplitude Levels'],['../examples_games_breakout.html#autotoc_md836',1,'8. Color Cycling Between Levels']]],
  ['lib_20api_50',['lib API',['../tutorial_colormath.html#autotoc_md136',1,'The lib API'],['../tutorial_mosaic.html#autotoc_md275',1,'The lib API'],['../tutorial_sram.html#autotoc_md339',1,'The lib API'],['../tutorial_window.html#autotoc_md381',1,'The lib API']]],
  ['lib_20api_20tour_51',['Lib API tour',['../tutorial_dma.html#autotoc_md157',1,'']]],
  ['lib_20chantier_20b6_202026_2005_2009_52',['&lt;span class=&quot;tt&quot;&gt;atan2&lt;/span&gt; and &lt;span class=&quot;tt&quot;&gt;sqrt&lt;/span&gt; ship in the lib (chantier B6, 2026-05-09)',['../tutorial_math.html#autotoc_md249',1,'']]],
  ['lib_20helpers_20and_20what_20they_20do_53',['The lib helpers and what they do',['../tutorial_mode7.html#autotoc_md259',1,'']]],
  ['library_20not_20built_54',['Build fails with &quot;Library not built&quot;',['../getting_started.html#autotoc_md415',1,'']]],
  ['licence_55',['Licence',['../examples_games_shmup_1942.html#autotoc_md902',1,'']]],
  ['license_56',['License',['../index.html#autotoc_md10',1,'License'],['../examples_audio_snesmod_music.html#autotoc_md753',1,'License']]],
  ['lights_20off_20load_20everything_57',['1. Lights Off, Load Everything',['../examples_games_breakout.html#autotoc_md829',1,'']]],
  ['lights_20on_58',['7. Lights On',['../examples_text_hello_world.html#autotoc_md1503',1,'']]],
  ['likemario_59',['LikeMario',['../tutorial_animation.html#autotoc_md85',1,'Action-Based Animation (LikeMario)'],['../examples_games_likemario.html',1,'LikeMario']]],
  ['limitation_60',['Limitation',['../hdma_8h.html#autotoc_md32',1,'Bank Byte Limitation'],['../dma_8h.html#autotoc_md25',1,'Bank Limitation']]],
  ['limits_61',['SNES Sprite Limits',['../sprite_8h.html#autotoc_md57',1,'']]],
  ['limits_20critical_62',['Scanline Limits (Critical!)',['../snes_graphics_guide.html#autotoc_md483',1,'']]],
  ['lines_63',['5. Gravity in Two Lines',['../examples_games_likemario.html#autotoc_md861',1,'']]],
  ['linker_20errors_20about_20size_64',['&quot;ROM too large&quot; or linker errors about size',['../troubleshooting.html#autotoc_md578',1,'']]],
  ['links_65',['Links',['../index.html#autotoc_md9',1,'Links'],['../contributing.html#autotoc_md1566',1,'Links']]],
  ['lives_66',['Where the Data Lives',['../examples_graphics_effects_hdma_wave.html#autotoc_md1126',1,'']]],
  ['ll_20learn_67',['ll Learn',['../examples_audio_snesmod_music_hirom.html#autotoc_md755',1,'What You&apos;ll Learn'],['../examples_audio_snesmod_music_large.html#autotoc_md759',1,'What You&apos;ll Learn'],['../examples_audio_snesmod_sfx.html#autotoc_md764',1,'What You&apos;ll Learn'],['../examples_basics_collision_demo.html#autotoc_md781',1,'What You&apos;ll Learn'],['../examples_basics_random.html#autotoc_md799',1,'What You&apos;ll Learn'],['../examples_basics_scene_stack.html#autotoc_md809',1,'What You&apos;ll Learn'],['../examples_basics_timer.html#autotoc_md817',1,'What You&apos;ll Learn'],['../examples_games_breakout.html#autotoc_md826',1,'What You&apos;ll Learn'],['../examples_games_likemario.html#autotoc_md854',1,'What You&apos;ll Learn'],['../examples_games_mapandobjects.html#autotoc_md878',1,'What You&apos;ll Learn'],['../examples_graphics_backgrounds_continuous_scroll.html#autotoc_md909',1,'What You&apos;ll Learn'],['../examples_graphics_backgrounds_mixed_scroll.html#autotoc_md929',1,'What You&apos;ll Learn'],['../examples_graphics_backgrounds_mode1_lz77.html#autotoc_md997',1,'What You&apos;ll Learn'],['../examples_graphics_effects_hdma_wave.html#autotoc_md1110',1,'What You&apos;ll Learn'],['../examples_graphics_effects_superfx_3d.html#autotoc_md1169',1,'What You&apos;ll Learn'],['../examples_graphics_effects_transparency.html#autotoc_md1175',1,'What You&apos;ll Learn'],['../examples_graphics_sprites_dynamic_metasprite.html#autotoc_md1236',1,'What You&apos;ll Learn'],['../examples_graphics_sprites_metasprite.html#autotoc_md1254',1,'What You&apos;ll Learn'],['../examples_input_controller.html#autotoc_md1300',1,'What You&apos;ll Learn'],['../examples_input_mouse.html#autotoc_md1308',1,'What You&apos;ll Learn'],['../examples_input_superscope.html#autotoc_md1330',1,'What You&apos;ll Learn'],['../examples_maps_dynamic_map.html#autotoc_md1384',1,'What You&apos;ll Learn'],['../examples_maps_mapscroll.html#autotoc_md1394',1,'What You&apos;ll Learn'],['../examples_maps_slopemario.html#autotoc_md1411',1,'What You&apos;ll Learn'],['../examples_maps_tiled.html#autotoc_md1421',1,'What You&apos;ll Learn'],['../examples_memory_sa1_hello.html#autotoc_md1452',1,'What You&apos;ll Learn'],['../examples_memory_sa1_starfield.html#autotoc_md1456',1,'What You&apos;ll Learn'],['../examples_memory_superfx_hello.html#autotoc_md1478',1,'What You&apos;ll Learn'],['../examples_text_hello_world.html#autotoc_md1494',1,'What You&apos;ll Learn'],['../examples_text_text_test.html#autotoc_md1523',1,'What You&apos;ll Learn']]],
  ['load_20both_20tilesets_20and_20palettes_68',['1. Load Both Tilesets and Palettes',['../examples_graphics_backgrounds_mixed_scroll.html#autotoc_md937',1,'']]],
  ['load_20cursor_20sprite_69',['2. Load Cursor Sprite',['../examples_input_mouse.html#autotoc_md1316',1,'']]],
  ['load_20everything_70',['1. Lights Off, Load Everything',['../examples_games_breakout.html#autotoc_md829',1,'']]],
  ['load_20font_71',['3. Initialize Text and Load Font',['../examples_text_text_test.html#autotoc_md1532',1,'']]],
  ['load_20from_20sram_72',['3. Load from SRAM',['../examples_memory_save_game.html#autotoc_md1466',1,'']]],
  ['load_20objects_20from_20map_20data_73',['3. Load Objects from Map Data',['../examples_games_mapandobjects.html#autotoc_md887',1,'']]],
  ['load_20palette_20and_20tilemap_20uncompressed_74',['3. Load Palette and Tilemap (Uncompressed)',['../examples_graphics_backgrounds_mode1_lz77.html#autotoc_md1006',1,'']]],
  ['load_20sprite_20graphics_20into_20vram_75',['1. Load sprite graphics into VRAM',['../examples_graphics_sprites_simple_sprite.html#autotoc_md1289',1,'']]],
  ['load_20sprites_20with_20force_20blank_76',['2. Load sprites with force blank',['../examples_graphics_sprites_object_size.html#autotoc_md1268',1,'']]],
  ['load_20the_20sprite_20palette_77',['2. Load the sprite palette',['../examples_graphics_sprites_simple_sprite.html#autotoc_md1290',1,'']]],
  ['load_20tilemaps_20to_20vram_78',['2. Load Tilemaps to VRAM',['../examples_graphics_backgrounds_mixed_scroll.html#autotoc_md938',1,'']]],
  ['load_20tiles_20and_20palettes_79',['2. Load tiles and palettes',['../examples_graphics_backgrounds_mode1_bg3_priority.html#autotoc_md988',1,'']]],
  ['loader_80',['Assembly DMA Loader',['../examples_graphics_effects_transparency.html#autotoc_md1181',1,'']]],
  ['loader_2065816_20asm_81',['3. Create the GSU Loader (65816 ASM)',['../tutorial_superfx.html#autotoc_md360',1,'']]],
  ['loading_20and_20playing_20effects_82',['Loading and Playing Effects',['../examples_audio_snesmod_sfx.html#autotoc_md768',1,'']]],
  ['loading_20sprite_20tiles_83',['Loading Sprite Tiles',['../tutorial_sprites.html#autotoc_md325',1,'']]],
  ['loading_20tiles_20to_20vram_84',['Loading Tiles to VRAM',['../tutorial_graphics.html#autotoc_md186',1,'']]],
  ['loads_20but_20screen_20is_20black_85',['ROM loads but screen is black',['../troubleshooting.html#autotoc_md568',1,'']]],
  ['locations_86',['Sprite Palette Locations',['../examples_graphics.html#autotoc_md1218',1,'']]],
  ['log_87',['What&apos;s still missing: &lt;span class=&quot;tt&quot;&gt;pow&lt;/span&gt;, &lt;span class=&quot;tt&quot;&gt;exp&lt;/span&gt;, &lt;span class=&quot;tt&quot;&gt;log&lt;/span&gt;',['../tutorial_math.html#autotoc_md250',1,'']]],
  ['logic_88',['Window Logic',['../window_8h.html#autotoc_md66',1,'']]],
  ['logic_20op_20trap_89',['The window logic op trap',['../tutorial_window.html#autotoc_md380',1,'']]],
  ['long_20sizes_20are_20correct_20on_20this_20target_20since_20chantier_20a1_90',['🟢 &lt;span class=&quot;tt&quot;&gt;int&lt;/span&gt; and &lt;span class=&quot;tt&quot;&gt;long&lt;/span&gt; sizes are correct on this target (since chantier A1)',['../tutorial_math.html#autotoc_md242',1,'']]],
  ['long_20way_91',['Manual setup (the long way)',['../getting_started.html#autotoc_md401',1,'']]],
  ['lookup_20tables_92',['Trigonometry (sin/cos lookup tables)',['../tutorial_math.html#autotoc_md233',1,'']]],
  ['lookups_20with_20lda_20l_20table_20x_93',['ROM Table Lookups with &lt;span class=&quot;tt&quot;&gt;lda.l table,x&lt;/span&gt;',['../tutorial_sa1.html#autotoc_md298',1,'']]],
  ['loop_94',['Loop',['../examples_graphics_backgrounds_mode1_lz77.html#autotoc_md1008',1,'5. Idle Loop'],['../examples_text_text_test.html#autotoc_md1534',1,'5. Idle Loop'],['../examples_games_likemario.html#autotoc_md863',1,'7. The Main Loop'],['../examples_games_breakout.html#autotoc_md837',1,'9. The Game Loop'],['../examples_graphics_effects_parallax_scrolling.html#autotoc_md1152',1,'Animation Loop'],['../examples_graphics_effects_transparency.html#autotoc_md1185',1,'Main Loop'],['../tutorial_animation.html#autotoc_md84',1,'The Game Loop']]],
  ['loop_95',['Per-frame DMA in the main loop',['../tutorial_dma.html#autotoc_md156',1,'']]],
  ['loop_20critical_96',['Main Loop (CRITICAL!)',['../examples_audio_snesmod_music.html#autotoc_md716',1,'']]],
  ['loop_20over_20100_20bricks_97',['5. Grid Collision (Don&apos;t Loop Over 100 Bricks)',['../examples_games_breakout.html#autotoc_md833',1,'']]],
  ['loop_3a_20read_20mouse_20update_20cursor_98',['4. Main Loop: Read Mouse, Update Cursor',['../examples_input_mouse.html#autotoc_md1318',1,'']]],
  ['loop_3a_20update_20draw_20sync_99',['4. Main Loop: Update, Draw, Sync',['../examples_games_mapandobjects.html#autotoc_md888',1,'']]],
  ['loops_100',['Loops',['../tutorial_superfx.html#autotoc_md366',1,'3. RPIX After PLOT Loops'],['../tutorial_superfx.html#autotoc_md367',1,'4. CACHE Before Hot Loops']]],
  ['lorom_101',['LoROM',['../examples_memory_hirom_demo.html#autotoc_md1437',1,'2. The code is identical to LoROM'],['../sram_8h.html#autotoc_md61',1,'Memory Layout (LoROM)']]],
  ['lorom_20memory_20map_20default_102',['LoROM Memory Map (Default)',['../memory_map.html#autotoc_md595',1,'']]],
  ['lorom_20vs_20hirom_103',['LoROM vs HiROM',['../hardware_overview.html#autotoc_md638',1,'LoROM vs HiROM'],['../examples_memory_hirom_demo.html#autotoc_md1441',1,'LoROM vs HiROM'],['../examples_memory.html#autotoc_md1448',1,'LoROM vs HiROM']]],
  ['luts_20are_20unsigned_20angle_20signed_20result_104',['🟡 Sin/cos LUTs are unsigned-angle, signed-result',['../tutorial_math.html#autotoc_md248',1,'']]],
  ['lz77_105',['Mode 1 LZ77',['../examples_graphics_backgrounds_mode1_lz77.html',1,'examples_graphics_backgrounds']]],
  ['lz77_20format_106',['LZ77 Format',['../lzss_8h.html#autotoc_md38',1,'']]],
  ['lz77_20lzss_20compression_107',['LZ77 / LZSS Compression',['../examples_graphics_backgrounds_mode1_lz77.html#autotoc_md999',1,'']]],
  ['lzss_20compression_108',['LZ77 / LZSS Compression',['../examples_graphics_backgrounds_mode1_lz77.html#autotoc_md999',1,'']]]
];
