var searchData=
[
  ['t_20appear_0',['Sprites don&apos;t appear',['../troubleshooting.html#autotoc_md578',1,'']]],
  ['t_20configured_1',['🟡 Don&apos;t enable channels you haven&apos;t configured',['../tutorial_hdma.html#autotoc_md220',1,'']]],
  ['t_20do_2',['What SA-1 Can&apos;t Do',['../tutorial_sa1.html#autotoc_md311',1,'']]],
  ['t_20double_20up_3',['🟠 OAM DMA is automated, don&apos;t double-up',['../tutorial_dma.html#autotoc_md172',1,'']]],
  ['t_20enable_20channels_20you_20haven_20t_20configured_4',['🟡 Don&apos;t enable channels you haven&apos;t configured',['../tutorial_hdma.html#autotoc_md220',1,'']]],
  ['t_20have_20to_20think_20about_20it_5',['🟠 Endianness — but you don&apos;t have to think about it',['../tutorial_sram.html#autotoc_md358',1,'']]],
  ['t_20loop_20over_20100_20bricks_6',['5. Grid Collision (Don&apos;t Loop Over 100 Bricks)',['../examples_games_breakout.html#autotoc_md842',1,'']]],
  ['table_7',['Table',['../examples_graphics_effects_parallax_scrolling.html#autotoc_md1159',1,'HDMA Scroll Table'],['../examples_graphics_sprites_object_size.html#autotoc_md1282',1,'OAM High Table']]],
  ['table_8',['2. The gradient table',['../examples_graphics_effects_gradient_colors.html#autotoc_md1105',1,'']]],
  ['table_202_20bits_20per_20sprite_9',['Extended Table (2 bits per sprite)',['../oam.html#autotoc_md621',1,'']]],
  ['table_204_20bytes_20per_20sprite_10',['Main Table (4 bytes per sprite)',['../oam.html#autotoc_md619',1,'']]],
  ['table_20format_11',['Table Format',['../examples_graphics_effects_hdma_wave.html#autotoc_md1123',1,'2. The HDMA Table Format'],['../hdma_8h.html#autotoc_md30',1,'Table Format']]],
  ['table_20format_12',['Table format',['../tutorial_hdma.html#autotoc_md206',1,'']]],
  ['table_20generation_13',['HDMA gradient table generation',['../tutorial_math.html#autotoc_md248',1,'']]],
  ['table_20lookups_20with_20lda_20l_20table_20x_14',['ROM Table Lookups with &lt;span class=&quot;tt&quot;&gt;lda.l table,x&lt;/span&gt;',['../tutorial_sa1.html#autotoc_md306',1,'']]],
  ['table_20of_20contents_15',['Table of Contents',['../snes_graphics_guide.html#autotoc_md475',1,'Table of Contents'],['../snes_sound_guide.html#autotoc_md519',1,'Table of Contents'],['../registers.html#autotoc_md650',1,'Table of Contents']]],
  ['table_20x_16',['ROM Table Lookups with &lt;span class=&quot;tt&quot;&gt;lda.l table,x&lt;/span&gt;',['../tutorial_sa1.html#autotoc_md306',1,'']]],
  ['tables_17',['The Triangle Tables',['../examples_graphics_effects_window.html#autotoc_md1215',1,'']]],
  ['tables_18',['Trigonometry (sin/cos lookup tables)',['../tutorial_math.html#autotoc_md241',1,'']]],
  ['target_20branch_19',['Target branch',['../contributing.html#autotoc_md1564',1,'']]],
  ['target_20common_20mk_20',['&quot;OPENSNES not defined&quot; or &quot;No rule to make target &apos;common.mk&apos;&quot;',['../troubleshooting.html#autotoc_md569',1,'']]],
  ['target_20since_20chantier_20a1_21',['🟢 &lt;span class=&quot;tt&quot;&gt;int&lt;/span&gt; and &lt;span class=&quot;tt&quot;&gt;long&lt;/span&gt; sizes are correct on this target (since chantier A1)',['../tutorial_math.html#autotoc_md250',1,'']]],
  ['targets_20cgadd_20_242121_22',['1. HDMA targets CGADD ($2121)',['../examples_graphics_effects_gradient_colors.html#autotoc_md1104',1,'']]],
  ['technical_20notes_23',['Technical Notes',['../examples_audio_snesmod_music.html#autotoc_md754',1,'Technical Notes'],['../examples_graphics_backgrounds_mode1.html#autotoc_md986',1,'Technical Notes'],['../examples_graphics_effects_fading.html#autotoc_md1093',1,'Technical Notes'],['../examples_input_two_players.html#autotoc_md1386',1,'Technical Notes']]],
  ['technical_20reference_24',['Technical Reference',['../examples_games_breakout.html#autotoc_md858',1,'Technical Reference'],['../examples_games_likemario.html#autotoc_md884',1,'Technical Reference'],['../examples_graphics_backgrounds_continuous_scroll.html#autotoc_md935',1,'Technical Reference'],['../examples_graphics_effects_hdma_wave.html#autotoc_md1138',1,'Technical Reference'],['../examples_input_superscope.html#autotoc_md1349',1,'Technical Reference'],['../examples_text_hello_world.html#autotoc_md1523',1,'Technical Reference']]],
  ['technique_25',['Technique',['../examples_graphics_effects_parallax_scrolling.html#autotoc_md1158',1,'The Parallax Technique'],['../examples_graphics_effects_transparent_window.html#autotoc_md1201',1,'The Technique']]],
  ['temporal_20artefacts_20flicker_20page_20flip_20desync_26',['Recipe 6 — Temporal artefacts (flicker, page-flip desync)',['../tutorial_debugging.html#autotoc_md156',1,'']]],
  ['test_27',['Test',['../tutorial_collision.html#autotoc_md114',1,'Basic Overlap Test'],['../examples_text_text_test.html',1,'Text Module Test']]],
  ['testing_28',['Testing',['../contributing.html#autotoc_md1568',1,'']]],
  ['testing_20multiple_20enemies_29',['Testing Multiple Enemies',['../tutorial_collision.html#autotoc_md115',1,'']]],
  ['tests_30',['B3. Run Tests',['../getting_started.html#autotoc_md415',1,'']]],
  ['tetris_31',['Tetris',['../tutorial_game_states.html#autotoc_md188',1,'Restart Game Over (Tetris)'],['../examples_games_tetris.html',1,'Tetris']]],
  ['text_32',['Text',['../examples_by_category.html#autotoc_md436',1,'Text'],['../examples_text.html#autotoc_md1529',1,'VRAM Layout for Text']]],
  ['text_20and_20detect_20mouse_33',['1. Initialize Text and Detect Mouse',['../examples_input_mouse.html#autotoc_md1324',1,'']]],
  ['text_20and_20load_20font_34',['3. Initialize Text and Load Font',['../examples_text_text_test.html#autotoc_md1541',1,'']]],
  ['text_20display_35',['Text Display',['../examples_audio_snesmod_sfx.html#autotoc_md779',1,'']]],
  ['text_20display_36',['5. Text display',['../examples_memory_save_game.html#autotoc_md1477',1,'']]],
  ['text_20examples_37',['Text Examples',['../examples_text.html',1,'examples']]],
  ['text_20module_20test_38',['Text Module Test',['../examples_text_text_test.html',1,'examples_text']]],
  ['text_20on_20bg1_204bpp_20in_20mode_201_39',['1. Set up text on BG1 (4bpp in Mode 1)',['../examples_graphics_sprites_object_size.html#autotoc_md1276',1,'']]],
  ['text_20rendering_20on_20the_20snes_40',['Text Rendering on the SNES',['../examples_text_text_test.html#autotoc_md1534',1,'']]],
  ['text_20system_20bg1_41',['2. Text System (BG1)',['../examples_input_superscope.html#autotoc_md1342',1,'']]],
  ['text_20works_20on_20snes_42',['How Text Works on SNES',['../examples_text.html#autotoc_md1527',1,'']]],
  ['than_20the_20screen_43',['1. The World Is Bigger Than the Screen',['../examples_games_likemario.html#autotoc_md866',1,'']]],
  ['the_206_20size_20modes_44',['The 6 Size Modes',['../examples_graphics_sprites_object_size.html#autotoc_md1279',1,'']]],
  ['the_208_208_20fixed_20point_20format_45',['The 8.8 fixed-point format',['../tutorial_math.html#autotoc_md238',1,'']]],
  ['the_208_20transfer_20modes_46',['The 8 transfer modes',['../tutorial_dma.html#autotoc_md161',1,'']]],
  ['the_20backdrop_47',['🟡 Colour-math on the backdrop',['../tutorial_colormath.html#autotoc_md144',1,'']]],
  ['the_20backdrop_20not_20a_20layer_48',['🟡 Out-of-bounds with &lt;span class=&quot;tt&quot;&gt;MODE7_TRANSPARENT&lt;/span&gt; shows the backdrop, not a layer',['../tutorial_mode7.html#autotoc_md277',1,'']]],
  ['the_20bg2_20is_20sub_20screen_20only_20trap_49',['🔴 The &quot;BG2 is sub-screen-only&quot; trap',['../tutorial_colormath.html#autotoc_md141',1,'']]],
  ['the_20build_50',['The Build',['../examples_games_breakout.html#autotoc_md852',1,'Under the Hood: The Build'],['../examples_games_likemario.html#autotoc_md878',1,'Under the Hood: The Build'],['../examples_graphics_backgrounds_continuous_scroll.html#autotoc_md931',1,'Under the Hood: The Build'],['../examples_graphics_effects_hdma_wave.html#autotoc_md1133',1,'Under the Hood: The Build'],['../examples_input_superscope.html#autotoc_md1348',1,'Under the Hood: The Build'],['../examples_text_hello_world.html#autotoc_md1518',1,'Under the Hood: The Build']]],
  ['the_20checkerboard_20background_51',['6. The Checkerboard Background',['../examples_graphics_effects_hdma_wave.html#autotoc_md1127',1,'']]],
  ['the_20code_20is_20identical_20to_20lorom_52',['2. The code is identical to LoROM',['../examples_memory_hirom_demo.html#autotoc_md1446',1,'']]],
  ['the_20column_20pipeline_53',['3. Streaming: The Column Pipeline',['../examples_games_likemario.html#autotoc_md868',1,'']]],
  ['the_20conversion_20macros_54',['The conversion macros',['../tutorial_math.html#autotoc_md239',1,'']]],
  ['the_20data_20lives_55',['Where the Data Lives',['../examples_graphics_effects_hdma_wave.html#autotoc_md1135',1,'']]],
  ['the_20dma_20channels_56',['The DMA channels',['../tutorial_dma.html#autotoc_md160',1,'']]],
  ['the_20dynamic_20sprite_20engine_57',['The Dynamic Sprite Engine',['../tutorial_animation.html#autotoc_md80',1,'']]],
  ['the_20dynamic_20sprite_20engine_58',['1. Initialize the dynamic sprite engine',['../examples_graphics_sprites_dynamic_sprite.html#autotoc_md1253',1,'']]],
  ['the_20exclusive_20bus_59',['The Exclusive Bus',['../tutorial_superfx.html#autotoc_md370',1,'']]],
  ['the_20four_20channel_20registers_60',['The four channel registers',['../tutorial_hdma.html#autotoc_md204',1,'']]],
  ['the_20game_20loop_61',['The Game Loop',['../examples_games_breakout.html#autotoc_md846',1,'9. The Game Loop'],['../tutorial_animation.html#autotoc_md84',1,'The Game Loop']]],
  ['the_20game_20state_20struct_62',['5. The Game State Struct',['../examples_graphics_backgrounds_continuous_scroll.html#autotoc_md925',1,'']]],
  ['the_20gate_20to_20colour_20math_63',['🟠 &lt;span class=&quot;tt&quot;&gt;windowEnable(window, WINDOW_MATH)&lt;/span&gt; is the gate to colour math',['../tutorial_window.html#autotoc_md395',1,'']]],
  ['the_20gradient_20table_64',['2. The gradient table',['../examples_graphics_effects_gradient_colors.html#autotoc_md1105',1,'']]],
  ['the_20gsu_20loader_2065816_20asm_65',['3. Create the GSU Loader (65816 ASM)',['../tutorial_superfx.html#autotoc_md368',1,'']]],
  ['the_20hdma_20channel_66',['4. Setting Up the HDMA Channel',['../examples_graphics_effects_hdma_wave.html#autotoc_md1125',1,'']]],
  ['the_20hdma_20table_20format_67',['2. The HDMA Table Format',['../examples_graphics_effects_hdma_wave.html#autotoc_md1123',1,'']]],
  ['the_20hood_3a_20the_20build_68',['the Hood: The Build',['../examples_games_breakout.html#autotoc_md852',1,'Under the Hood: The Build'],['../examples_games_likemario.html#autotoc_md878',1,'Under the Hood: The Build'],['../examples_graphics_backgrounds_continuous_scroll.html#autotoc_md931',1,'Under the Hood: The Build'],['../examples_graphics_effects_hdma_wave.html#autotoc_md1133',1,'Under the Hood: The Build'],['../examples_input_superscope.html#autotoc_md1348',1,'Under the Hood: The Build'],['../examples_text_hello_world.html#autotoc_md1518',1,'Under the Hood: The Build']]],
  ['the_20interleaved_20vram_20format_69',['The interleaved VRAM format',['../tutorial_mode7.html#autotoc_md263',1,'']]],
  ['the_20lib_20api_70',['The lib API',['../tutorial_colormath.html#autotoc_md136',1,'The lib API'],['../tutorial_mosaic.html#autotoc_md283',1,'The lib API'],['../tutorial_sram.html#autotoc_md347',1,'The lib API'],['../tutorial_window.html#autotoc_md389',1,'The lib API']]],
  ['the_20lib_20chantier_20b6_202026_2005_2009_71',['&lt;span class=&quot;tt&quot;&gt;atan2&lt;/span&gt; and &lt;span class=&quot;tt&quot;&gt;sqrt&lt;/span&gt; ship in the lib (chantier B6, 2026-05-09)',['../tutorial_math.html#autotoc_md257',1,'']]],
  ['the_20lib_20helpers_20and_20what_20they_20do_72',['The lib helpers and what they do',['../tutorial_mode7.html#autotoc_md267',1,'']]],
  ['the_20long_20way_73',['Manual setup (the long way)',['../getting_started.html#autotoc_md409',1,'']]],
  ['the_20machine_20at_20a_20point_20in_20time_74',['Recipe 1 — Inspect the machine at a point in time',['../tutorial_debugging.html#autotoc_md151',1,'']]],
  ['the_20mailbox_75',['I-RAM — The Mailbox',['../tutorial_sa1.html#autotoc_md295',1,'']]],
  ['the_20main_20loop_76',['7. The Main Loop',['../examples_games_likemario.html#autotoc_md872',1,'']]],
  ['the_20main_20loop_77',['Per-frame DMA in the main loop',['../tutorial_dma.html#autotoc_md165',1,'']]],
  ['the_20makefile_78',['The Makefile',['../examples_games_breakout.html#autotoc_md853',1,'The Makefile'],['../examples_games_likemario.html#autotoc_md879',1,'The Makefile'],['../examples_graphics_backgrounds_continuous_scroll.html#autotoc_md932',1,'The Makefile'],['../examples_graphics_effects_hdma_wave.html#autotoc_md1134',1,'The Makefile'],['../examples_text_hello_world.html#autotoc_md1520',1,'The Makefile']]],
  ['the_20makefile_79',['the Makefile',['../examples_memory_hirom_demo.html#autotoc_md1445',1,'1. Enable HiROM in the Makefile'],['../examples_memory_save_game.html#autotoc_md1476',1,'4. Enable SRAM in the Makefile']]],
  ['the_20map_20and_20sprite_20system_80',['1. Initialize the Map and Sprite System',['../examples_games_mapandobjects.html#autotoc_md894',1,'']]],
  ['the_20map_20engine_81',['The Map Engine',['../examples_maps_slopemario.html#autotoc_md1422',1,'']]],
  ['the_20matrix_20and_20the_20registers_82',['The matrix and the registers',['../tutorial_mode7.html#autotoc_md262',1,'']]],
  ['the_20matrix_20every_20frame_83',['3. Update the matrix every frame',['../examples_graphics_backgrounds_mode7.html#autotoc_md1036',1,'']]],
  ['the_20message_84',['6. Spelling the Message',['../examples_text_hello_world.html#autotoc_md1511',1,'']]],
  ['the_20minimum_20viable_20colour_20math_85',['The minimum viable colour math',['../tutorial_colormath.html#autotoc_md133',1,'']]],
  ['the_20minimum_20viable_20mosaic_86',['The minimum viable mosaic',['../tutorial_mosaic.html#autotoc_md281',1,'']]],
  ['the_20minimum_20viable_20save_87',['The minimum viable save',['../tutorial_sram.html#autotoc_md348',1,'']]],
  ['the_20minimum_20viable_20window_88',['The minimum viable window',['../tutorial_window.html#autotoc_md383',1,'']]],
  ['the_20nmi_20handler_89',['🟡 HDMA fires before the user callback in the NMI handler',['../tutorial_hdma.html#autotoc_md219',1,'']]],
  ['the_20oambuffer_90',['2. Set up sprites via the oambuffer',['../examples_graphics_sprites_dynamic_sprite.html#autotoc_md1254',1,'']]],
  ['the_20parallax_20technique_91',['The Parallax Technique',['../examples_graphics_effects_parallax_scrolling.html#autotoc_md1158',1,'']]],
  ['the_20pipeline_92',['The Pipeline',['../examples_text_hello_world.html#autotoc_md1519',1,'']]],
  ['the_20pointer_93',['5. Animation = Just Move the Pointer',['../examples_graphics_effects_hdma_wave.html#autotoc_md1126',1,'']]],
  ['the_20ppu_94',['3. Setting Up the PPU',['../examples_text_hello_world.html#autotoc_md1508',1,'']]],
  ['the_20problem_95',['The Problem',['../oam.html#autotoc_md623',1,'']]],
  ['the_20ram_20buffer_20pattern_96',['3. ROM is Read-Only (The RAM Buffer Pattern)',['../examples_games_breakout.html#autotoc_md840',1,'']]],
  ['the_20rect_20type_97',['The Rect Type',['../tutorial_collision.html#autotoc_md112',1,'']]],
  ['the_20registers_98',['The matrix and the registers',['../tutorial_mode7.html#autotoc_md262',1,'']]],
  ['the_20scene_20struct_99',['The Scene struct',['../examples_basics_scene_stack.html#autotoc_md821',1,'']]],
  ['the_20screen_100',['1. The World Is Bigger Than the Screen',['../examples_games_likemario.html#autotoc_md866',1,'']]],
  ['the_20screen_20centre_101',['🟡 Centre default is the tilemap centre, not the screen centre',['../tutorial_mode7.html#autotoc_md276',1,'']]],
  ['the_20setup_20pattern_102',['The setup pattern',['../tutorial_dma.html#autotoc_md164',1,'']]],
  ['the_20shipped_20example_103',['the shipped example',['../tutorial_mosaic.html#autotoc_md284',1,'Worked pattern (the shipped example)'],['../tutorial_sram.html#autotoc_md351',1,'Worked pattern (the shipped example)']]],
  ['the_20six_20shipped_20examples_104',['Worked patterns (the six shipped examples)',['../tutorial_hdma.html#autotoc_md208',1,'']]],
  ['the_20snes_105',['the SNES',['../examples_input_controller.html#autotoc_md1312',1,'How Input Works on the SNES'],['../examples_text_text_test.html#autotoc_md1534',1,'Text Rendering on the SNES'],['../tutorial_math.html#autotoc_md237',1,'Why fixed-point on the SNES']]],
  ['the_20solution_106',['The Solution',['../oam.html#autotoc_md624',1,'']]],
  ['the_20soundbank_107',['The Soundbank',['../examples_audio_snesmod_sfx.html#autotoc_md778',1,'']]],
  ['the_20sprite_108',['4. Place the sprite',['../examples_graphics_sprites_simple_sprite.html#autotoc_md1301',1,'']]],
  ['the_20sprite_20palette_109',['2. Load the sprite palette',['../examples_graphics_sprites_simple_sprite.html#autotoc_md1299',1,'']]],
  ['the_20streaming_20pattern_110',['The Streaming Pattern',['../tutorial_scrolling.html#autotoc_md322',1,'']]],
  ['the_20technique_111',['The Technique',['../examples_graphics_effects_transparent_window.html#autotoc_md1201',1,'']]],
  ['the_20threshold_20scroll_20pattern_112',['2. The Threshold Scroll Pattern',['../examples_graphics_backgrounds_continuous_scroll.html#autotoc_md922',1,'']]],
  ['the_20tile_20number_113',['Calculating the Tile Number',['../tutorial_animation.html#autotoc_md78',1,'']]],
  ['the_20tiled_20workflow_114',['The Tiled Workflow',['../examples_maps_tiled.html#autotoc_md1431',1,'']]],
  ['the_20tilemap_20centre_20not_20the_20screen_20centre_115',['🟡 Centre default is the tilemap centre, not the screen centre',['../tutorial_mode7.html#autotoc_md276',1,'']]],
  ['the_20transformation_116',['2. Initialize the transformation',['../examples_graphics_backgrounds_mode7.html#autotoc_md1035',1,'']]],
  ['the_20triangle_20tables_117',['The Triangle Tables',['../examples_graphics_effects_window.html#autotoc_md1215',1,'']]],
  ['the_20two_20shipped_20examples_118',['the two shipped examples',['../tutorial_colormath.html#autotoc_md137',1,'Worked patterns (the two shipped examples)'],['../tutorial_mode7.html#autotoc_md268',1,'Worked patterns (the two shipped examples)'],['../tutorial_window.html#autotoc_md390',1,'Worked patterns (the two shipped examples)']]],
  ['the_20user_20callback_20in_20the_20nmi_20handler_119',['🟡 HDMA fires before the user callback in the NMI handler',['../tutorial_hdma.html#autotoc_md219',1,'']]],
  ['the_20vram_20layout_120',['2. The VRAM Layout',['../examples_games_likemario.html#autotoc_md867',1,'']]],
  ['the_20vram_20map_20—_20a_20deliberate_20overlap_121',['2. The VRAM Map — A Deliberate Overlap',['../examples_games_breakout.html#autotoc_md839',1,'']]],
  ['the_20warning_20above_20before_20using_122',['Quick Start (legacy — read the warning above before using)',['../audio_8h.html#autotoc_md11',1,'']]],
  ['the_20window_20gate_123',['The window gate',['../tutorial_colormath.html#autotoc_md135',1,'']]],
  ['the_20window_20logic_20op_20trap_124',['The window logic op trap',['../tutorial_window.html#autotoc_md388',1,'']]],
  ['the_20window_20register_20acts_20strange_125',['When the window register acts strange',['../tutorial_window.html#autotoc_md385',1,'']]],
  ['the_20world_20is_20bigger_20than_20the_20screen_126',['1. The World Is Bigger Than the Screen',['../examples_games_likemario.html#autotoc_md866',1,'']]],
  ['there_20is_20no_20printf_127',['1. There Is No printf',['../examples_text_hello_world.html#autotoc_md1506',1,'']]],
  ['these_20demonstrate_128',['What These Demonstrate',['../examples_games.html#autotoc_md902',1,'']]],
  ['these_20modules_129',['These Modules',['../examples_games_breakout.html#autotoc_md856',1,'Why These Modules?'],['../examples_graphics_backgrounds_continuous_scroll.html#autotoc_md933',1,'Why These Modules?'],['../examples_graphics_effects_hdma_wave.html#autotoc_md1136',1,'Why These Modules?'],['../examples_text_hello_world.html#autotoc_md1521',1,'Why These Modules?']]],
  ['they_20do_130',['The lib helpers and what they do',['../tutorial_mode7.html#autotoc_md267',1,'']]],
  ['think_20about_20it_131',['🟠 Endianness — but you don&apos;t have to think about it',['../tutorial_sram.html#autotoc_md358',1,'']]],
  ['third_20party_20components_132',['Third-Party Components',['../third_party.html',1,'index']]],
  ['this_20example_20demonstrates_133',['What this example demonstrates',['../basics_2fix32__orbit_2main_8c.html#autotoc_md801',1,'']]],
  ['this_20example_20does_134',['This Example Does',['../examples_audio_snesmod_music.html#autotoc_md716',1,'What This Example Does'],['../examples_graphics_backgrounds_mode1.html#autotoc_md959',1,'What This Example Does'],['../examples_graphics_effects_fading.html#autotoc_md1068',1,'What This Example Does'],['../examples_input_two_players.html#autotoc_md1354',1,'What This Example Does']]],
  ['this_20example_20shows_135',['This Example Shows',['../examples_graphics_backgrounds_mode1_bg3_priority.html#autotoc_md992',1,'What This Example Shows'],['../examples_graphics_backgrounds_mode7.html#autotoc_md1029',1,'What This Example Shows'],['../examples_graphics_backgrounds_mode7_perspective.html#autotoc_md1045',1,'What This Example Shows'],['../examples_graphics_effects_gradient_colors.html#autotoc_md1099',1,'What This Example Shows'],['../examples_graphics_effects_mosaic.html#autotoc_md1140',1,'What This Example Shows'],['../examples_graphics_effects_parallax_scrolling.html#autotoc_md1154',1,'What This Example Shows'],['../examples_graphics_sprites_animated_sprite.html#autotoc_md1229',1,'What This Example Shows'],['../examples_graphics_sprites_dynamic_sprite.html#autotoc_md1248',1,'What This Example Shows'],['../examples_graphics_sprites_object_size.html#autotoc_md1272',1,'What This Example Shows'],['../examples_graphics_sprites_simple_sprite.html#autotoc_md1293',1,'What This Example Shows'],['../examples_memory_hirom_demo.html#autotoc_md1440',1,'What This Example Shows'],['../examples_memory_save_game.html#autotoc_md1468',1,'What This Example Shows']]],
  ['this_20target_20since_20chantier_20a1_136',['🟢 &lt;span class=&quot;tt&quot;&gt;int&lt;/span&gt; and &lt;span class=&quot;tt&quot;&gt;long&lt;/span&gt; sizes are correct on this target (since chantier A1)',['../tutorial_math.html#autotoc_md250',1,'']]],
  ['this_20variable_137',['Recipe 2 — &quot;Who writes this variable?&quot;',['../tutorial_debugging.html#autotoc_md152',1,'']]],
  ['this_20works_20with_20one_20layer_138',['Why This Works with One Layer',['../examples_graphics_effects_parallax_scrolling.html#autotoc_md1165',1,'']]],
  ['three_20background_20layers_139',['1. Set up three background layers',['../examples_graphics_backgrounds_mode1_bg3_priority.html#autotoc_md996',1,'']]],
  ['threshold_20scroll_20pattern_140',['2. The Threshold Scroll Pattern',['../examples_graphics_backgrounds_continuous_scroll.html#autotoc_md922',1,'']]],
  ['through_20a_141',['No &lt;span class=&quot;tt&quot;&gt;stx.l&lt;/span&gt; — Save X Through A',['../tutorial_sa1.html#autotoc_md307',1,'']]],
  ['tile_20animation_142',['Background Tile Animation',['../tutorial_animation.html#autotoc_md87',1,'']]],
  ['tile_20based_20collision_143',['Tile Based Collision',['../examples_games_likemario.html#autotoc_md871',1,'6. Tile-Based Collision'],['../examples_maps.html#autotoc_md1417',1,'Tile-Based Collision']]],
  ['tile_20based_20wall_20collision_144',['Tile-Based Wall Collision',['../examples_basics_collision_demo.html#autotoc_md794',1,'']]],
  ['tile_20calculation_145',['4. Tile calculation',['../examples_graphics_sprites_animated_sprite.html#autotoc_md1237',1,'']]],
  ['tile_20collision_146',['Map Engine and Tile Collision',['../examples_games_mapandobjects.html#autotoc_md889',1,'']]],
  ['tile_20data_20address_147',['$210B-$210C - BG12NBA/BG34NBA (Tile Data Address)',['../registers.html#autotoc_md663',1,'']]],
  ['tile_20flip_148',['Exercise 3: Tile Flip',['../examples_graphics_backgrounds_mode1.html#autotoc_md983',1,'']]],
  ['tile_20format_149',['Tile Format',['../examples_text.html#autotoc_md1528',1,'2BPP Tile Format'],['../examples_graphics_backgrounds_mode1.html#autotoc_md974',1,'4bpp Tile Format']]],
  ['tile_20formats_150',['Tile Formats',['../snes_graphics_guide.html#autotoc_md486',1,'']]],
  ['tile_20graphics_151',['Approach 2: Overwrite Tile Graphics',['../tutorial_animation.html#autotoc_md89',1,'']]],
  ['tile_20grid_20platformer_20landing_152',['Snapping to Tile Grid (Platformer Landing)',['../tutorial_collision.html#autotoc_md126',1,'']]],
  ['tile_20layout_153',['Column-Major Tile Layout',['../tutorial_superfx.html#autotoc_md378',1,'']]],
  ['tile_20layout_20and_20oam_20tile_20numbers_154',['VRAM Tile Layout and OAM Tile Numbers',['../examples_graphics_sprites_metasprite.html#autotoc_md1267',1,'']]],
  ['tile_20number_155',['Calculating the Tile Number',['../tutorial_animation.html#autotoc_md78',1,'']]],
  ['tile_20numbering_156',['VRAM Tile Numbering',['../tutorial_animation.html#autotoc_md73',1,'']]],
  ['tile_20numbers_157',['VRAM Tile Layout and OAM Tile Numbers',['../examples_graphics_sprites_metasprite.html#autotoc_md1267',1,'']]],
  ['tile_20properties_158',['Tile Properties',['../examples_maps_tiled.html#autotoc_md1434',1,'']]],
  ['tile_20properties_20from_20a_20tilemap_20platformer_20pattern_159',['Tile Properties from a Tilemap (Platformer Pattern)',['../tutorial_collision.html#autotoc_md121',1,'']]],
  ['tile_20sizes_160',['Custom Tile Sizes',['../tutorial_collision.html#autotoc_md120',1,'']]],
  ['tiled_20map_20editor_20integration_161',['Tiled Map Editor Integration',['../examples_maps_tiled.html',1,'examples_maps']]],
  ['tiled_20workflow_162',['The Tiled Workflow',['../examples_maps_tiled.html#autotoc_md1431',1,'']]],
  ['tilemap_163',['Background Tilemap',['../registers.html#autotoc_md661',1,'']]],
  ['tilemap_20address_20size_164',['$2107-$210A - BG1SC-BG4SC (Tilemap Address/Size)',['../registers.html#autotoc_md662',1,'']]],
  ['tilemap_20centre_20not_20the_20screen_20centre_165',['🟡 Centre default is the tilemap centre, not the screen centre',['../tutorial_mode7.html#autotoc_md276',1,'']]],
  ['tilemap_20data_166',['Reading Tilemap Data',['../tutorial_collision.html#autotoc_md118',1,'']]],
  ['tilemap_20entries_167',['Approach 1: Swap Tilemap Entries',['../tutorial_animation.html#autotoc_md88',1,'']]],
  ['tilemap_20entry_202_20bytes_168',['Tilemap Entry (2 bytes)',['../examples_graphics_backgrounds.html#autotoc_md1062',1,'']]],
  ['tilemap_20for_20seamless_20wrapping_169',['64x32 Tilemap for Seamless Wrapping',['../examples_graphics_effects_parallax_scrolling.html#autotoc_md1164',1,'']]],
  ['tilemap_20format_170',['Tilemap Format',['../examples_graphics_backgrounds_mode1.html#autotoc_md972',1,'']]],
  ['tilemap_20layout_171',['SC_64x64 Tilemap Layout',['../examples_maps_dynamic_map.html#autotoc_md1396',1,'']]],
  ['tilemap_20palette_20bits_172',['Tilemap Palette Bits',['../examples_graphics_backgrounds_mode1_bg3_priority.html#autotoc_md1002',1,'']]],
  ['tilemap_20platformer_20pattern_173',['Tile Properties from a Tilemap (Platformer Pattern)',['../tutorial_collision.html#autotoc_md121',1,'']]],
  ['tilemap_20sizes_174',['Tilemap Sizes',['../snes_graphics_guide.html#autotoc_md485',1,'Tilemap Sizes'],['../examples_maps.html#autotoc_md1416',1,'Tilemap Sizes']]],
  ['tilemap_20structure_175',['Tilemap Structure',['../snes_graphics_guide.html#autotoc_md484',1,'']]],
  ['tilemap_20uncompressed_176',['3. Load Palette and Tilemap (Uncompressed)',['../examples_graphics_backgrounds_mode1_lz77.html#autotoc_md1015',1,'']]],
  ['tilemaps_177',['Tilemaps',['../examples_maps.html#autotoc_md1415',1,'Hardware Tilemaps'],['../tutorial_graphics.html#autotoc_md196',1,'Setting Up Tilemaps'],['../examples_graphics_backgrounds_mode1_lz77.html#autotoc_md1009',1,'Why Compress Tiles but Not Tilemaps?']]],
  ['tilemaps_20to_20vram_178',['2. Load Tilemaps to VRAM',['../examples_graphics_backgrounds_mixed_scroll.html#autotoc_md947',1,'']]],
  ['tiles_179',['Tiles',['../tutorial_sprites.html#autotoc_md333',1,'Loading Sprite Tiles'],['../examples_maps_dynamic_map.html#autotoc_md1395',1,'Mode 3 and 8bpp Tiles']]],
  ['tiles_20and_20palettes_180',['2. Load tiles and palettes',['../examples_graphics_backgrounds_mode1_bg3_priority.html#autotoc_md997',1,'']]],
  ['tiles_20and_20sprites_181',['Tiles and Sprites',['../hardware_overview.html#autotoc_md644',1,'']]],
  ['tiles_20appear_20corrupted_182',['Tiles appear corrupted',['../troubleshooting.html#autotoc_md583',1,'']]],
  ['tiles_20but_20not_20tilemaps_183',['Why Compress Tiles but Not Tilemaps?',['../examples_graphics_backgrounds_mode1_lz77.html#autotoc_md1009',1,'']]],
  ['tiles_20in_20oam_184',['16x16 Tiles in OAM',['../examples_graphics_sprites_animated_sprite.html#autotoc_md1241',1,'']]],
  ['tiles_20to_20vram_185',['Tiles to VRAM',['../examples_graphics_backgrounds_mode1_lz77.html#autotoc_md1014',1,'2. Decompress Tiles to VRAM'],['../examples_text_hello_world.html#autotoc_md1509',1,'4. Uploading Tiles to VRAM'],['../tutorial_graphics.html#autotoc_md195',1,'Loading Tiles to VRAM']]],
  ['tilesets_20and_20palettes_186',['1. Load Both Tilesets and Palettes',['../examples_graphics_backgrounds_mixed_scroll.html#autotoc_md946',1,'']]],
  ['time_187',['Recipe 1 — Inspect the machine at a point in time',['../tutorial_debugging.html#autotoc_md151',1,'']]],
  ['timer_188',['Timer',['../registers.html#autotoc_md680',1,'$4207-$420A - HTIMEx/VTIMEx (IRQ Timer)'],['../examples_basics_timer.html',1,'VBlank Timer']]],
  ['timeup_20irq_20status_189',['$4211 - TIMEUP (IRQ Status)',['../registers.html#autotoc_md682',1,'']]],
  ['timing_190',['Timing',['../tutorial_animation.html#autotoc_md69',1,'Frame Timing'],['../oam.html#autotoc_md633',1,'Timing'],['../tutorial_scrolling.html#autotoc_md324',1,'VBlank Timing']]],
  ['timing_191',['timing',['../tutorial_sram.html#autotoc_md356',1,'🟠 SRAM access requires no special timing'],['../tutorial_math.html#autotoc_md255',1,'🟡 Hardware multiplier read timing'],['../examples_graphics_sprites_animated_sprite.html#autotoc_md1236',1,'3. Animation timing']]],
  ['timing_20requirement_192',['VBlank Timing Requirement',['../dma_8h.html#autotoc_md24',1,'']]],
  ['timing_20values_193',['Timing Values',['../snes_sound_guide.html#autotoc_md541',1,'']]],
  ['timing_20with_20idle_20check_194',['Animation Timing with Idle Check',['../tutorial_animation.html#autotoc_md79',1,'']]],
  ['tip_195',['Performance Tip',['../examples_graphics_sprites.html#autotoc_md1291',1,'']]],
  ['tips_196',['Tips',['../tutorial_collision.html#autotoc_md128',1,'Performance Tips'],['../tutorial_sprites.html#autotoc_md340',1,'Performance Tips'],['../tutorial_sa1.html#autotoc_md304',1,'SA-1 Assembly Tips'],['../tutorial_scrolling.html#autotoc_md323',1,'Streaming Tips'],['../tutorial_audio.html#autotoc_md108',1,'Tips'],['../tutorial_input.html#autotoc_md234',1,'Tips'],['../examples.html#autotoc_md1499',1,'Tips']]],
  ['tips_20tricks_197',['Tips Tricks',['../examples_games_breakout.html#autotoc_md848',1,'Tips &amp;amp; Tricks'],['../examples_games_likemario.html#autotoc_md874',1,'Tips &amp;amp; Tricks'],['../examples_graphics_backgrounds_continuous_scroll.html#autotoc_md927',1,'Tips &amp;amp; Tricks'],['../examples_graphics_effects_hdma_wave.html#autotoc_md1129',1,'Tips &amp;amp; Tricks'],['../examples_input_superscope.html#autotoc_md1347',1,'Tips &amp;amp; Tricks'],['../examples_text_hello_world.html#autotoc_md1514',1,'Tips &amp;amp; Tricks']]],
  ['title_20flow_198',['Complete Title Flow',['../tutorial_game_states.html#autotoc_md183',1,'']]],
  ['title_20screen_20implementation_199',['Title Screen Implementation',['../tutorial_game_states.html#autotoc_md182',1,'']]],
  ['tm_20main_20screen_20enable_200',['$212C - TM (Main Screen Enable)',['../registers.html#autotoc_md674',1,'']]],
  ['to_20background_20collision_201',['Sprite-to-Background Collision',['../tutorial_collision.html#autotoc_md117',1,'']]],
  ['to_20black_202',['Fade Out (Full to Black)',['../examples_graphics_effects_fading.html#autotoc_md1076',1,'']]],
  ['to_20black_20fade_20to_20white_203',['Fade-to-black / fade-to-white',['../tutorial_colormath.html#autotoc_md134',1,'']]],
  ['to_20build_204',['to Build',['../examples_basics_aim_target.html#autotoc_md785',1,'How to Build'],['../examples_basics_fix32_orbit.html#autotoc_md805',1,'How to Build'],['../examples_basics_scene_stack.html#autotoc_md824',1,'How to Build']]],
  ['to_20colour_20math_205',['🟠 &lt;span class=&quot;tt&quot;&gt;windowEnable(window, WINDOW_MATH)&lt;/span&gt; is the gate to colour math',['../tutorial_window.html#autotoc_md395',1,'']]],
  ['to_20full_206',['Fade In (Black to Full)',['../examples_graphics_effects_fading.html#autotoc_md1075',1,'']]],
  ['to_20lorom_207',['2. The code is identical to LoROM',['../examples_memory_hirom_demo.html#autotoc_md1446',1,'']]],
  ['to_20make_20target_20common_20mk_208',['&quot;OPENSNES not defined&quot; or &quot;No rule to make target &apos;common.mk&apos;&quot;',['../troubleshooting.html#autotoc_md569',1,'']]],
  ['to_20observe_209',['to Observe',['../examples_basics_aim_target.html#autotoc_md784',1,'What to Observe'],['../examples_basics_fix32_orbit.html#autotoc_md804',1,'What to Observe'],['../examples_memory_sa1_starfield.html#autotoc_md1466',1,'What to Observe']]],
  ['to_20opensnes_210',['Contributing to OpenSNES',['../contributing.html',1,'index']]],
  ['to_20sprite_20collision_211',['Sprite-to-Sprite Collision',['../tutorial_collision.html#autotoc_md113',1,'']]],
  ['to_20sram_212',['2. Save to SRAM',['../examples_memory_save_game.html#autotoc_md1474',1,'']]],
  ['to_20think_20about_20it_213',['🟠 Endianness — but you don&apos;t have to think about it',['../tutorial_sram.html#autotoc_md358',1,'']]],
  ['to_20tile_20grid_20platformer_20landing_214',['Snapping to Tile Grid (Platformer Landing)',['../tutorial_collision.html#autotoc_md126',1,'']]],
  ['to_20use_20hirom_215',['When to Use HiROM',['../examples_memory_hirom_demo.html#autotoc_md1451',1,'']]],
  ['to_20vram_216',['to VRAM',['../examples_graphics_backgrounds_mode1_lz77.html#autotoc_md1014',1,'2. Decompress Tiles to VRAM'],['../examples_graphics_backgrounds_mixed_scroll.html#autotoc_md947',1,'2. Load Tilemaps to VRAM'],['../examples_text_hello_world.html#autotoc_md1509',1,'4. Uploading Tiles to VRAM'],['../tutorial_graphics.html#autotoc_md195',1,'Loading Tiles to VRAM']]],
  ['to_20vram_20transfer_217',['SRAM to VRAM Transfer',['../tutorial_superfx.html#autotoc_md379',1,'']]],
  ['to_20white_218',['Fade-to-black / fade-to-white',['../tutorial_colormath.html#autotoc_md134',1,'']]],
  ['today_219',['🔴 Interleaved VRAM, no &lt;span class=&quot;tt&quot;&gt;mode7LoadGraphics&lt;/span&gt; helper today',['../tutorial_mode7.html#autotoc_md273',1,'']]],
  ['toggle_20at_20runtime_220',['3. Toggle at runtime',['../examples_graphics_effects_gradient_colors.html#autotoc_md1106',1,'']]],
  ['too_20large_20or_20linker_20errors_20about_20size_221',['&quot;ROM too large&quot; or linker errors about size',['../troubleshooting.html#autotoc_md586',1,'']]],
  ['tool_222',['smconv Tool',['../tutorial_audio.html#autotoc_md103',1,'']]],
  ['tools_223',['Tools',['../snes_sound_guide.html#autotoc_md560',1,'Conversion Tools'],['../code_style.html#autotoc_md474',1,'Formatting Tools'],['../snes_graphics_guide.html#autotoc_md512',1,'Graphics Conversion Tools'],['../snes_sound_guide.html#autotoc_md559',1,'Sound Creation Tools']]],
  ['tools_20resources_224',['Tools Resources',['../snes_graphics_guide.html#autotoc_md511',1,'Tools &amp;amp; Resources'],['../snes_sound_guide.html#autotoc_md558',1,'Tools &amp;amp; Resources']]],
  ['topic_225',['By Topic',['../group__examples.html#autotoc_md1546',1,'']]],
  ['topic_20per_20pr_226',['One topic per PR',['../contributing.html#autotoc_md1565',1,'']]],
  ['topics_227',['Topics',['../examples.html#autotoc_md1495',1,'Level 4 &amp;ndash; Advanced Topics'],['../learning_path.html#autotoc_md430',1,'Level 4: Advanced Topics']]],
  ['total_228',['total',['../snes_sound_guide.html#autotoc_md555',1,'Memory Budget (64KB total)'],['../snes_graphics_guide.html#autotoc_md489',1,'OAM Structure (544 bytes total)']]],
  ['tour_229',['Lib API tour',['../tutorial_dma.html#autotoc_md166',1,'']]],
  ['tracker_20based_20music_230',['Why Tracker-Based Music?',['../examples_audio_snesmod_music.html#autotoc_md755',1,'']]],
  ['transfer_231',['SRAM to VRAM Transfer',['../tutorial_superfx.html#autotoc_md379',1,'']]],
  ['transfer_20modes_232',['Transfer modes',['../tutorial_hdma.html#autotoc_md205',1,'']]],
  ['transfer_20modes_233',['The 8 transfer modes',['../tutorial_dma.html#autotoc_md161',1,'']]],
  ['transfer_20size_234',['$43x5-$43x6 - DASxL/H (Transfer Size)',['../registers.html#autotoc_md696',1,'']]],
  ['transfers_235',['DMA Registers (for fast transfers)',['../snes_graphics_guide.html#autotoc_md518',1,'']]],
  ['transformation_236',['Affine Transformation',['../examples_graphics_backgrounds_mode7.html#autotoc_md1039',1,'']]],
  ['transformation_237',['2. Initialize the transformation',['../examples_graphics_backgrounds_mode7.html#autotoc_md1035',1,'']]],
  ['transition_20pattern_238',['Scene Transition Pattern',['../examples_graphics_effects_fading.html#autotoc_md1081',1,'']]],
  ['transitions_239',['State Transitions',['../tutorial_game_states.html#autotoc_md179',1,'']]],
  ['transitions_240',['transitions',['../examples_graphics_effects_mosaic.html#autotoc_md1147',1,'3. Combining both for transitions'],['../tutorial_mosaic.html#autotoc_md282',1,'Animated transitions']]],
  ['translation_241',['Address Translation',['../examples_memory_hirom_demo.html#autotoc_md1452',1,'']]],
  ['transparency_242',['Color Addition Transparency',['../examples_graphics_effects_transparency.html',1,'examples_graphics_effects']]],
  ['transparency_243',['Additive cloud overlay — &lt;span class=&quot;tt&quot;&gt;examples/graphics/effects/transparency&lt;/span&gt;',['../tutorial_colormath.html#autotoc_md138',1,'']]],
  ['transparent_20window_20color_20math_20hdma_244',['Transparent Window -- Color Math + HDMA',['../examples_graphics_effects_transparent_window.html',1,'examples_graphics_effects']]],
  ['transparent_5fwindow_245',['transparent_window',['../tutorial_window.html#autotoc_md392',1,'Window + colour math — &lt;span class=&quot;tt&quot;&gt;examples/graphics/effects/transparent_window&lt;/span&gt;'],['../tutorial_hdma.html#autotoc_md213',1,'Window animation — &lt;span class=&quot;tt&quot;&gt;examples/graphics/effects/transparent_window&lt;/span&gt;'],['../tutorial_colormath.html#autotoc_md139',1,'Window-gated spotlight blend — &lt;span class=&quot;tt&quot;&gt;examples/graphics/effects/transparent_window&lt;/span&gt;']]],
  ['trap_246',['trap',['../tutorial_dma.html#autotoc_md170',1,'🔴 &lt;span class=&quot;tt&quot;&gt;dmaCopyVram&lt;/span&gt; hardcodes source bank &lt;span class=&quot;tt&quot;&gt;$00&lt;/span&gt; — SUPERFREE spillover trap'],['../tutorial_colormath.html#autotoc_md141',1,'🔴 The &quot;BG2 is sub-screen-only&quot; trap'],['../tutorial_window.html#autotoc_md388',1,'The window logic op trap']]],
  ['trap_20on_20hdmasetup_247',['🔴 Bank byte trap on &lt;span class=&quot;tt&quot;&gt;hdmaSetup&lt;/span&gt;',['../tutorial_hdma.html#autotoc_md217',1,'']]],
  ['triangle_20masking_248',['Window -- HDMA Triangle Masking',['../examples_graphics_effects_window.html',1,'examples_graphics_effects']]],
  ['triangle_20reveal_20—_20examples_20graphics_20effects_20window_249',['Animated triangle reveal — &lt;span class=&quot;tt&quot;&gt;examples/graphics/effects/window&lt;/span&gt;',['../tutorial_window.html#autotoc_md391',1,'']]],
  ['triangle_20tables_250',['The Triangle Tables',['../examples_graphics_effects_window.html#autotoc_md1215',1,'']]],
  ['tricks_251',['Tricks',['../examples_games_breakout.html#autotoc_md848',1,'Tips &amp;amp; Tricks'],['../examples_games_likemario.html#autotoc_md874',1,'Tips &amp;amp; Tricks'],['../examples_graphics_backgrounds_continuous_scroll.html#autotoc_md927',1,'Tips &amp;amp; Tricks'],['../examples_graphics_effects_hdma_wave.html#autotoc_md1129',1,'Tips &amp;amp; Tricks'],['../examples_input_superscope.html#autotoc_md1347',1,'Tips &amp;amp; Tricks'],['../examples_text_hello_world.html#autotoc_md1514',1,'Tips &amp;amp; Tricks']]],
  ['trigonometry_20sin_20cos_20lookup_20tables_252',['Trigonometry (sin/cos lookup tables)',['../tutorial_math.html#autotoc_md241',1,'']]],
  ['troubleshooting_253',['Troubleshooting',['../getting_started.html#autotoc_md420',1,'']]],
  ['troubleshooting_20opensnes_254',['Troubleshooting OpenSNES',['../troubleshooting.html',1,'index']]],
  ['truncates_20fractional_20precision_255',['🔴 &lt;span class=&quot;tt&quot;&gt;fixMul&lt;/span&gt; truncates fractional precision',['../tutorial_math.html#autotoc_md252',1,'']]],
  ['ts_20sub_20screen_20enable_256',['$212D - TS (Sub Screen Enable)',['../registers.html#autotoc_md675',1,'']]],
  ['tutorial_257',['Tutorial',['../tutorial_animation.html',1,'Animation Tutorial'],['../tutorial_audio.html',1,'Audio &amp; Music Tutorial'],['../tutorial_collision.html',1,'Collision Detection Tutorial'],['../tutorial_colormath.html',1,'Colour Math Tutorial'],['../tutorial_input.html',1,'Controller Input Tutorial'],['../tutorial_dma.html',1,'DMA Tutorial'],['../tutorial_math.html',1,'Fixed-Point Math Tutorial'],['../tutorial_game_states.html',1,'Game States Tutorial'],['../tutorial_graphics.html',1,'Graphics &amp; Backgrounds Tutorial'],['../tutorial_hdma.html',1,'HDMA Tutorial'],['../tutorial_mode7.html',1,'Mode 7 Tutorial'],['../tutorial_mosaic.html',1,'Mosaic Tutorial'],['../tutorial_sa1.html',1,'SA-1 Enhancement Chip Tutorial'],['../tutorial_scrolling.html',1,'Scrolling &amp; Parallax Tutorial'],['../tutorial_sprites.html',1,'Sprites &amp; Animation Tutorial'],['../tutorial_sram.html',1,'SRAM Save Tutorial'],['../tutorial_superfx.html',1,'SuperFX (GSU) Tutorial'],['../tutorial_window.html',1,'Window Masking Tutorial']]],
  ['tutorials_258',['Tutorials',['../index.html#autotoc_md2',1,'Tutorials'],['../getting_started.html#autotoc_md419',1,'Tutorials']]],
  ['twice_20register_259',['BG1HOFS ($210D) &amp;ndash; Write-Twice Register',['../examples_graphics_effects_parallax_scrolling.html#autotoc_md1163',1,'']]],
  ['two_20camps_260',['Why two camps?',['../oam.html#autotoc_md632',1,'']]],
  ['two_20colors_20four_20bytes_261',['5. Two Colors, Four Bytes',['../examples_text_hello_world.html#autotoc_md1510',1,'']]],
  ['two_20controllers_262',['Reading Two Controllers',['../examples_input_two_players.html#autotoc_md1358',1,'']]],
  ['two_20layers_20two_20speeds_263',['1. Two Layers, Two Speeds',['../examples_graphics_backgrounds_continuous_scroll.html#autotoc_md921',1,'']]],
  ['two_20lines_264',['5. Gravity in Two Lines',['../examples_games_likemario.html#autotoc_md870',1,'']]],
  ['two_20phase_20update_265',['Map Engine Two-Phase Update',['../examples_maps_mapscroll.html#autotoc_md1406',1,'']]],
  ['two_20player_20example_266',['Two-Player Example',['../tutorial_input.html#autotoc_md230',1,'']]],
  ['two_20players_267',['Example: Two Players',['../tutorial_sprites.html#autotoc_md339',1,'']]],
  ['two_20players_20example_268',['Two Players Example',['../examples_input_two_players.html',1,'examples_input']]],
  ['two_20shipped_20examples_269',['two shipped examples',['../tutorial_colormath.html#autotoc_md137',1,'Worked patterns (the two shipped examples)'],['../tutorial_mode7.html#autotoc_md268',1,'Worked patterns (the two shipped examples)'],['../tutorial_window.html#autotoc_md390',1,'Worked patterns (the two shipped examples)']]],
  ['two_20speeds_270',['1. Two Layers, Two Speeds',['../examples_graphics_backgrounds_continuous_scroll.html#autotoc_md921',1,'']]],
  ['two_20sprites_20per_20mode_271',['3. Two sprites per mode',['../examples_graphics_sprites_object_size.html#autotoc_md1278',1,'']]],
  ['type_272',['Type',['../examples_audio_snesmod_music.html#autotoc_md718',1,'Code Type'],['../examples_graphics_backgrounds_mode1.html#autotoc_md961',1,'Code Type'],['../examples_graphics_effects_fading.html#autotoc_md1070',1,'Code Type'],['../examples_input_two_players.html#autotoc_md1356',1,'Code Type'],['../tutorial_collision.html#autotoc_md112',1,'The Rect Type']]],
  ['types_273',['Types',['../examples_input_two_players.html#autotoc_md1374',1,'Controller Types'],['../code_style.html#autotoc_md462',1,'Types']]],
  ['types_20in_20assembly_274',['2. Register Object Types in Assembly',['../examples_games_mapandobjects.html#autotoc_md895',1,'']]],
  ['typical_20sample_20sizes_275',['Typical Sample Sizes',['../snes_sound_guide.html#autotoc_md556',1,'']]]
];
