var searchData=
[
  ['s_0',['The two flags that decide everything: &lt;span class=&quot;tt&quot;&gt;-u&lt;/span&gt; and &lt;span class=&quot;tt&quot;&gt;-s&lt;/span&gt;',['../tools_gfx4snes.html#autotoc_md513',1,'']]],
  ['s_20map_1',['Controls (krom&apos;s map)',['../examples_mode7_perspective_rotate.html#autotoc_md1543',1,'']]],
  ['s_20must_20match_20the_20sprite_20size_2',['Converting a sheet: &lt;span class=&quot;tt&quot;&gt;-s&lt;/span&gt; must match the sprite size',['../tutorial_sprites.html#autotoc_md386',1,'']]],
  ['s_20next_3',['s Next',['../getting_started.html#autotoc_md566',1,'What&apos;s Next?'],['../examples_audio_snesmod_music.html#autotoc_md939',1,'What&apos;s Next?'],['../examples_audio_snesmod_sfx.html#autotoc_md959',1,'What&apos;s Next?'],['../examples_backgrounds_mode1.html#autotoc_md1007',1,'What&apos;s Next?'],['../examples_basics_collision_demo.html#autotoc_md1076',1,'What&apos;s Next?'],['../examples_color_transparency.html#autotoc_md1189',1,'What&apos;s Next?'],['../examples_input_two_players.html#autotoc_md1444',1,'What&apos;s Next?'],['../examples_transitions_fading.html#autotoc_md1767',1,'What&apos;s Next?']]],
  ['s_20spc_20dump_4',['Debugging audio: luna&apos;s spc-dump',['../tutorial_audio.html#autotoc_md116',1,'']]],
  ['s_20still_20missing_3a_20pow_20exp_20log_5',['What&apos;s still missing: &lt;span class=&quot;tt&quot;&gt;pow&lt;/span&gt;, &lt;span class=&quot;tt&quot;&gt;exp&lt;/span&gt;, &lt;span class=&quot;tt&quot;&gt;log&lt;/span&gt;',['../tutorial_math.html#autotoc_md297',1,'']]],
  ['s5_202_6',['Bullet despawn fix (S5.2)',['../examples_games_shmup_1942.html#autotoc_md1298',1,'']]],
  ['s6_20hud_20on_20bg3_7',['Open chantier — S6 HUD on BG3',['../examples_games_shmup_1942.html#autotoc_md1299',1,'']]],
  ['sa_201_8',['What Is SA-1?',['../tutorial_sa1.html#autotoc_md344',1,'']]],
  ['sa_201_20assembly_20tips_9',['SA-1 Assembly Tips',['../tutorial_sa1.html#autotoc_md355',1,'']]],
  ['sa_201_20boot_20code_10',['2. Write Your SA-1 Boot Code',['../tutorial_sa1.html#autotoc_md349',1,'']]],
  ['sa_201_20can_20t_20do_11',['What SA-1 Can&apos;t Do',['../tutorial_sa1.html#autotoc_md362',1,'']]],
  ['sa_201_20cartridge_12',['SA-1 Cartridge',['../memory_map.html#autotoc_md777',1,'']]],
  ['sa_201_20coprocessor_13',['SA-1 Coprocessor',['../examples_by_category.html#autotoc_md616',1,'']]],
  ['sa_201_20enhancement_20chip_20tutorial_14',['SA-1 Enhancement Chip Tutorial',['../tutorial_sa1.html',1,'index']]],
  ['sa_201_20hello_20world_15',['SA-1 Hello World',['../examples_chips_sa1_hello.html',1,'examples_chips']]],
  ['sa_201_20in_20your_20makefile_16',['1. Enable SA-1 in Your Makefile',['../tutorial_sa1.html#autotoc_md348',1,'']]],
  ['sa_201_20registers_20_242200_20_24230e_17',['SA-1 Registers ($2200-$230E)',['../registers.html#autotoc_md868',1,'']]],
  ['sa_201_20starfield_20murmuration_18',['SA-1 Starfield (Murmuration)',['../examples_chips_sa1_starfield.html',1,'examples_chips']]],
  ['safe_19',['safe',['../tutorial_dsp1.html#autotoc_md193',1,'🟡 Not NMI-callback-safe'],['../tutorial_dma.html#autotoc_md170',1,'When VRAM/CGRAM/OAM writes are safe']]],
  ['safe_20in_20nmi_20',['🟡 WRAM data port &lt;span class=&quot;tt&quot;&gt;$2180&lt;/span&gt;–&lt;span class=&quot;tt&quot;&gt;$2183&lt;/span&gt; is NOT safe in NMI',['../tutorial_dma.html#autotoc_md181',1,'']]],
  ['sample_21',['How the WAV becomes a sample',['../examples_audio_sfx_from_wav.html#autotoc_md891',1,'']]],
  ['sample_20directory_22',['Sample Directory',['../snes_sound_guide.html#autotoc_md698',1,'']]],
  ['sample_20format_23',['BRR Sample Format',['../snes_sound_guide.html#autotoc_md695',1,'']]],
  ['sample_20preparation_24',['Sample Preparation',['../snes_sound_guide.html#autotoc_md716',1,'']]],
  ['sample_20provenance_25',['Sample provenance',['../examples_audio_pitch_mod.html#autotoc_md882',1,'Sample provenance'],['../examples_audio_soundboard.html#autotoc_md961',1,'Sample provenance']]],
  ['sample_20sizes_26',['Typical Sample Sizes',['../snes_sound_guide.html#autotoc_md718',1,'']]],
  ['sample_20sources_27',['Sample Sources',['../snes_sound_guide.html#autotoc_md723',1,'']]],
  ['samples_28',['samples',['../examples_audio_play_noise.html',1,'play_noise — a drum kit with zero samples'],['../tools_wav2brr.html',1,'wav2brr — WAV to BRR sound samples']]],
  ['samples_20and_20effects_20from_20pure_20c_29',['The audio module (v2) — samples and effects from pure C',['../tutorial_audio.html#autotoc_md113',1,'']]],
  ['samples_20from_20wav_20wav2brr_30',['One-shot samples from WAV (wav2brr)',['../tutorial_audio.html#audio_wav2brr',1,'']]],
  ['saturation_20interact_31',['🟠 Half-mode and saturation interact',['../tutorial_colormath.html#autotoc_md150',1,'']]],
  ['save_32',['save',['../tutorial_sram.html#autotoc_md403',1,'&quot;Delete save&quot;'],['../tutorial_sram.html#autotoc_md401',1,'The minimum viable save']]],
  ['save_20game_20sram_20persistence_33',['Save Game -- SRAM Persistence',['../examples_memory_save_game.html',1,'examples_memory']]],
  ['save_20slots_34',['Save Slots',['../examples_memory_save_game.html#autotoc_md1517',1,'']]],
  ['save_20structure_35',['1. Define a save structure',['../examples_memory_save_game.html#autotoc_md1510',1,'']]],
  ['save_20to_20sram_36',['2. Save to SRAM',['../examples_memory_save_game.html#autotoc_md1511',1,'']]],
  ['save_20tutorial_37',['SRAM Save Tutorial',['../tutorial_sram.html',1,'index']]],
  ['save_20x_20through_20a_38',['No &lt;span class=&quot;tt&quot;&gt;stx.l&lt;/span&gt; — Save X Through A',['../tutorial_sa1.html#autotoc_md358',1,'']]],
  ['saves_39',['Multi-slot saves',['../tutorial_sram.html#autotoc_md402',1,'']]],
  ['says_20open_20snes_40',['speech_synth — the SNES says &quot;OPEN SNES&quot;',['../examples_audio_speech_synth.html',1,'examples_audio']]],
  ['sc_5f64x64_20tilemap_20layout_41',['SC_64x64 Tilemap Layout',['../examples_maps_dynamic_map.html#autotoc_md1448',1,'']]],
  ['scale_42',['8.8 Fixed-Point Scale',['../examples_mode7_rotate_scale.html#autotoc_md1565',1,'']]],
  ['scale_20before_20angle_43',['🟡 Set scale BEFORE angle',['../tutorial_mode7.html#autotoc_md316',1,'']]],
  ['scaling_44',['Scaling',['../examples_mode7_rotate_scale.html',1,'Mode 7 -- Rotation and Scaling'],['../examples_mode7_perspective.html#autotoc_md1539',1,'Per-Scanline Scaling']]],
  ['scaling_45',['Squash and stretch without scaling',['../craft_game_feel.html#autotoc_md481',1,'']]],
  ['scaling_20—_20examples_20mode7_20rotate_5fscale_46',['Basic rotation + scaling — &lt;span class=&quot;tt&quot;&gt;examples/mode7/rotate_scale&lt;/span&gt;',['../tutorial_mode7.html#autotoc_md308',1,'']]],
  ['scanline_47',['scanline',['../examples_mode7_perspective_rotate.html',1,'Mode 7 rotating perspective — the full matrix, per scanline'],['../examples_windows_window_multi_hdma.html',1,'Multi-window HDMA — both windows animated per scanline']]],
  ['scanline_20—_20examples_20windows_20window_5fmulti_5fhdma_48',['Both windows per scanline — &lt;span class=&quot;tt&quot;&gt;examples/windows/window_multi_hdma&lt;/span&gt;',['../tutorial_window.html#autotoc_md454',1,'']]],
  ['scanline_20limits_20critical_49',['Scanline Limits (Critical!)',['../snes_graphics_guide.html#autotoc_md653',1,'']]],
  ['scanline_20matrix_3a_20rotating_20perspective_50',['Per-scanline matrix: rotating perspective',['../tutorial_mode7.html#autotoc_md321',1,'']]],
  ['scanline_20quirk_51',['Sprite Y +1 Scanline Quirk',['../oam.html#autotoc_md792',1,'']]],
  ['scanline_20scaling_52',['Per-Scanline Scaling',['../examples_mode7_perspective.html#autotoc_md1539',1,'']]],
  ['scanline_20scroll_53',['HDMA Parallax (Per-Scanline Scroll)',['../tutorial_scrolling.html#autotoc_md371',1,'']]],
  ['scanline_20wave_20distortion_20—_20examples_20hdma_20hdma_5fwave_54',['Per-scanline wave distortion — &lt;span class=&quot;tt&quot;&gt;examples/hdma/hdma_wave&lt;/span&gt;',['../tutorial_hdma.html#autotoc_md231',1,'']]],
  ['scene_20at_20once_55',['shadow_tint — recolour a whole scene at once',['../examples_color_shadow_tint.html',1,'examples_color']]],
  ['scene_20changes_20—_20fades_20and_20dissolves_56',['Punctuate scene changes — fades and dissolves',['../craft_game_feel.html#autotoc_md479',1,'']]],
  ['scene_20module_57',['The scene stack (recommended) — &lt;span class=&quot;tt&quot;&gt;scene&lt;/span&gt; module',['../tutorial_game_states.html#autotoc_md198',1,'']]],
  ['scene_20stack_58',['Scene Stack',['../examples_basics_scene_stack.html',1,'examples_basics']]],
  ['scene_20stack_20recommended_20—_20scene_20module_59',['The scene stack (recommended) — &lt;span class=&quot;tt&quot;&gt;scene&lt;/span&gt; module',['../tutorial_game_states.html#autotoc_md198',1,'']]],
  ['scene_20struct_60',['The Scene struct',['../examples_basics_scene_stack.html#autotoc_md1109',1,'']]],
  ['scene_20transition_20pattern_61',['Scene Transition Pattern',['../examples_transitions_fading.html#autotoc_md1750',1,'']]],
  ['scenes_62',['🟡 Window state survives between scenes',['../tutorial_window.html#autotoc_md450',1,'']]],
  ['scope_63',['Scope',['../tools_aseprite2snes.html#autotoc_md506',1,'Scope'],['../examples_input_superscope.html',1,'Super Scope']]],
  ['scope_20a_20first_20game_20you_20can_20finish_64',['Scope a first game you can finish',['../craft_planning.html#autotoc_md490',1,'']]],
  ['screen_65',['Screen',['../examples_games_likemario.html#autotoc_md1249',1,'1. The World Is Bigger Than the Screen'],['../examples_color_transparency.html#autotoc_md1179',1,'Color Math: Main Screen + Sub Screen'],['../examples_input_two_players.html#autotoc_md1436',1,'Exercise 4: Split Screen'],['../colormath_8h.html#autotoc_md19',1,'Main Screen vs Sub Screen'],['../tutorial_game_states.html#autotoc_md205',1,'Pause Screen']]],
  ['screen_66',['screen',['../craft_planning.html#autotoc_md485',1,'1. VRAM — 64 KB, shared by everything on screen'],['../examples_sprites.html#autotoc_md1679',1,'Reference — OAM in one screen'],['../learning_path.html#autotoc_md577',1,'Stage 1 — &quot;Can I put something on screen?&quot;'],['../examples_audio.html#autotoc_md889',1,'The idea in one screen'],['../examples_backgrounds.html#autotoc_md1058',1,'The idea in one screen'],['../examples_color.html#autotoc_md1167',1,'The idea in one screen'],['../examples_hdma.html#autotoc_md1359',1,'The idea in one screen'],['../examples_input.html#autotoc_md1388',1,'The idea in one screen'],['../examples_maps.html#autotoc_md1464',1,'The idea in one screen'],['../examples_mode7.html#autotoc_md1551',1,'The idea in one screen'],['../examples_scrolling.html#autotoc_md1630',1,'The idea in one screen'],['../examples_transitions.html#autotoc_md1783',1,'The idea in one screen'],['../examples_windows.html#autotoc_md1785',1,'The idea in one screen'],['../examples_chips.html#autotoc_md1126',1,'The two chips, in one screen']]],
  ['screen_20centre_67',['🟡 Centre default is the tilemap centre, not the screen centre',['../tutorial_mode7.html#autotoc_md317',1,'']]],
  ['screen_20crash_68',['Runtime Issues (Black Screen / Crash)',['../troubleshooting.html#autotoc_md737',1,'']]],
  ['screen_20enable_69',['Screen Enable',['../registers.html#autotoc_md836',1,'$212C - TM (Main Screen Enable)'],['../registers.html#autotoc_md837',1,'$212D - TS (Sub Screen Enable)'],['../registers.html#autotoc_md835',1,'Screen Enable']]],
  ['screen_20implementation_70',['Title Screen Implementation',['../tutorial_game_states.html#autotoc_md203',1,'']]],
  ['screen_20is_20black_71',['ROM loads but screen is black',['../troubleshooting.html#autotoc_md738',1,'']]],
  ['screen_20only_20trap_72',['🔴 The &quot;BG2 is sub-screen-only&quot; trap',['../tutorial_colormath.html#autotoc_md148',1,'']]],
  ['screen_20shake_20—_20nudge_20the_20scroll_73',['Screen shake — nudge the scroll',['../craft_game_feel.html#autotoc_md476',1,'']]],
  ['screen_20sub_20screen_74',['Color Math: Main Screen + Sub Screen',['../examples_color_transparency.html#autotoc_md1179',1,'']]],
  ['screen_20vs_20sub_20screen_75',['Main Screen vs Sub Screen',['../colormath_8h.html#autotoc_md19',1,'']]],
  ['screen_20when_20running_20rom_76',['Black screen when running ROM',['../getting_started.html#autotoc_md572',1,'']]],
  ['screen_20with_20hdma_77',['1. Split-screen with HDMA',['../examples_mode7_perspective.html#autotoc_md1534',1,'']]],
  ['scroll_78',['Scroll',['../registers.html#autotoc_md826',1,'Background Scroll'],['../examples_scrolling_continuous_scroll.html',1,'Continuous Scroll'],['../tutorial_scrolling.html#autotoc_md371',1,'HDMA Parallax (Per-Scanline Scroll)'],['../examples_maps_map_scroll.html',1,'Map Scroll'],['../examples_scrolling_mixed_scroll.html',1,'Mixed Scroll']]],
  ['scroll_79',['Screen shake — nudge the scroll',['../craft_game_feel.html#autotoc_md476',1,'']]],
  ['scroll_20a_20message_80',['Scroll a message',['../examples_text_scroll_message.html',1,'examples_text']]],
  ['scroll_20and_20the_20mode_207_20registers_20share_20one_20write_20twice_20latch_81',['🟡 BG1 scroll and the Mode 7 registers share one write-twice latch',['../tutorial_mode7.html#autotoc_md312',1,'']]],
  ['scroll_20bg1_82',['4. Auto-Scroll BG1',['../examples_scrolling_mixed_scroll.html#autotoc_md1612',1,'']]],
  ['scroll_20can_20corrupt_20mode_207_20writes_20shared_20latch_83',['🟡 HDMA on BG1 scroll can corrupt Mode 7 writes (shared latch)',['../tutorial_hdma.html#autotoc_md246',1,'']]],
  ['scroll_20from_20bg3_84',['mode2 — offset-per-tile: per-column scroll from BG3',['../examples_backgrounds_mode2.html',1,'examples_backgrounds']]],
  ['scroll_20pattern_85',['2. The Threshold Scroll Pattern',['../examples_scrolling_continuous_scroll.html#autotoc_md1585',1,'']]],
  ['scroll_20registers_86',['$210D-$2114 - BGnHOFS/BGnVOFS (Scroll Registers)',['../registers.html#autotoc_md827',1,'']]],
  ['scroll_20registers_20require_20repeat_20mode_87',['IMPORTANT: Scroll Registers Require Repeat Mode',['../hdma_8h.html#autotoc_md35',1,'']]],
  ['scroll_20static_20moving_20layers_88',['Mixed Scroll (Static + Moving Layers)',['../tutorial_scrolling.html#autotoc_md368',1,'']]],
  ['scroll_20table_89',['HDMA Scroll Table',['../examples_scrolling_parallax_scroll.html#autotoc_md1620',1,'']]],
  ['scroll_20updates_20via_20bgsetscroll_20dirty_20flags_90',['3. Scroll Updates via bgSetScroll Dirty Flags',['../examples_scrolling_continuous_scroll.html#autotoc_md1586',1,'']]],
  ['scroll_20values_91',['The camera &lt;em&gt;is&lt;/em&gt; your scroll values',['../craft_camera.html#autotoc_md463',1,'']]],
  ['scroller_92',['The minimum viable scroller',['../tutorial_map.html#autotoc_md267',1,'']]],
  ['scrolling_93',['Scrolling',['../examples_mode7_perspective.html#autotoc_md1536',1,'3. Scrolling'],['../tutorial_graphics.html#autotoc_md219',1,'Background Scrolling'],['../tutorial_scrolling.html#autotoc_md366',1,'Basic BG Scrolling'],['../tutorial_scrolling.html#autotoc_md372',1,'Continuous / Infinite Scrolling'],['../tutorial_scrolling.html#autotoc_md367',1,'D-PAD Controlled Scrolling'],['../examples_scrolling_mixed_scroll.html#autotoc_md1606',1,'Independent Background Scrolling'],['../examples_scrolling_parallax_scroll.html',1,'Parallax Scrolling'],['../tutorial_graphics.html#autotoc_md220',1,'Parallax Scrolling'],['../tutorial_scrolling.html#autotoc_md369',1,'Parallax Scrolling'],['../examples_scrolling.html',1,'Scrolling'],['../examples_by_category.html#autotoc_md593',1,'Scrolling']]],
  ['scrolling_20—_20examples_20scrolling_20parallax_5fscroll_94',['Parallax scrolling — &lt;span class=&quot;tt&quot;&gt;examples/scrolling/parallax_scroll&lt;/span&gt;',['../tutorial_hdma.html#autotoc_md232',1,'']]],
  ['scrolling_20and_20effects_95',['Level 3 &amp;ndash; Scrolling and Effects',['../examples.html#autotoc_md1572',1,'']]],
  ['scrolling_20is_20jerky_96',['Scrolling is jerky',['../troubleshooting.html#autotoc_md746',1,'']]],
  ['scrolling_20maps_97',['Scrolling maps',['../tutorial_map.html',1,'index']]],
  ['scrolling_20parallax_20tutorial_98',['Scrolling &amp;amp; Parallax Tutorial',['../tutorial_scrolling.html',1,'index']]],
  ['scrolling_20parallax_5fscroll_99',['Parallax scrolling — &lt;span class=&quot;tt&quot;&gt;examples/scrolling/parallax_scroll&lt;/span&gt;',['../tutorial_hdma.html#autotoc_md232',1,'']]],
  ['scrolling_20works_100',['How BG Scrolling Works',['../tutorial_scrolling.html#autotoc_md364',1,'']]],
  ['sdk_101',['A3. Download OpenSNES SDK',['../getting_started.html#autotoc_md553',1,'']]],
  ['sdk_20bugs_20this_20port_20surfaced_102',['Two SDK bugs this port surfaced',['../examples_color_hicolor_1792.html#autotoc_md1156',1,'']]],
  ['sdk_20convention_103',['OpenSNES SDK convention',['../oam.html#autotoc_md793',1,'']]],
  ['sdk_20developer_104',['Path B: SDK Developer',['../getting_started.html#autotoc_md560',1,'']]],
  ['seamless_20wrapping_105',['64x32 Tilemap for Seamless Wrapping',['../examples_scrolling_parallax_scroll.html#autotoc_md1625',1,'']]],
  ['second_20layer_106',['Exercise 1: Add a Second Layer',['../examples_backgrounds_mode1.html#autotoc_md997',1,'']]],
  ['second_20layer_20options_107',['One-way and second-layer options',['../tutorial_map.html#autotoc_md269',1,'']]],
  ['seconds_108',['ROM runs but crashes after a few seconds',['../troubleshooting.html#autotoc_md739',1,'']]],
  ['see_109',['Understanding what you see',['../examples_backgrounds_mode5_hires.html#autotoc_md1052',1,'']]],
  ['see_20also_110',['See Also',['../oam.html#autotoc_md798',1,'See Also'],['../examples_sprites_aseprite_pipeline.html#autotoc_md1649',1,'See Also']]],
  ['see_20also_111',['See also',['../tutorial_colormath.html#autotoc_md155',1,'See also'],['../tutorial_dma.html#autotoc_md183',1,'See also'],['../tutorial_dsp1.html#autotoc_md196',1,'See also'],['../tutorial_hdma.html#autotoc_md250',1,'See also'],['../tutorial_map.html#autotoc_md275',1,'See also'],['../tutorial_math.html#autotoc_md299',1,'See also'],['../tutorial_mode7.html#autotoc_md320',1,'See also'],['../tutorial_mosaic.html#autotoc_md334',1,'See also'],['../tutorial_panel.html#autotoc_md343',1,'See also'],['../tutorial_sram.html#autotoc_md415',1,'See also'],['../tutorial_window.html#autotoc_md453',1,'See also'],['../examples_basics_aim_target.html#autotoc_md1063',1,'See also'],['../examples_basics_fix32_orbit.html#autotoc_md1083',1,'See also']]],
  ['see_20it_20in_20practice_112',['See it in practice',['../tools_gfx4snes.html#autotoc_md517',1,'See it in practice'],['../tools_palplan.html#autotoc_md528',1,'See it in practice'],['../tools_smconv.html#autotoc_md537',1,'See it in practice'],['../tools_tmx2snes.html#autotoc_md542',1,'See it in practice'],['../tools_wav2brr.html#autotoc_md547',1,'See it in practice']]],
  ['seed_20matters_113',['Why Seed Matters',['../examples_basics_random.html#autotoc_md1099',1,'']]],
  ['selecting_20the_20clip_20and_20ticking_114',['Selecting the Clip and Ticking',['../tutorial_animation.html#autotoc_md81',1,'']]],
  ['selection_115',['Palette Selection',['../snes_graphics_guide.html#autotoc_md667',1,'']]],
  ['self_20review_20checklist_116',['Self-review checklist',['../contributing.html#autotoc_md1839',1,'']]],
  ['semantics_117',['Push/pop semantics',['../examples_basics_scene_stack.html#autotoc_md1110',1,'']]],
  ['sensitivity_118',['Mouse Sensitivity',['../examples_input_mouse.html#autotoc_md1371',1,'']]],
  ['sep_119',['Explicit &lt;span class=&quot;tt&quot;&gt;.ACCU&lt;/span&gt; After Every &lt;span class=&quot;tt&quot;&gt;rep&lt;/span&gt;/&lt;span class=&quot;tt&quot;&gt;sep&lt;/span&gt;',['../tutorial_sa1.html#autotoc_md359',1,'']]],
  ['separate_20palettes_120',['Separate Palettes',['../examples_input_two_players.html#autotoc_md1421',1,'']]],
  ['sequencing_121',['🟠 Double-write register sequencing',['../tutorial_mode7.html#autotoc_md315',1,'']]],
  ['sequencing_20during_20hdma_122',['🟡 Boundary register sequencing during HDMA',['../tutorial_window.html#autotoc_md451',1,'']]],
  ['set_20scale_20before_20angle_123',['🟡 Set scale BEFORE angle',['../tutorial_mode7.html#autotoc_md316',1,'']]],
  ['set_20up_20background_124',['2. Set Up Background',['../examples_backgrounds_mode1.html#autotoc_md984',1,'']]],
  ['set_20up_20oam_20directly_125',['3. Set Up OAM Directly',['../examples_input_mouse.html#autotoc_md1377',1,'']]],
  ['set_20up_20sprites_20via_20the_20oambuffer_126',['2. Set up sprites via the oambuffer',['../examples_sprites_dynamic_sprite.html#autotoc_md1660',1,'']]],
  ['set_20up_20text_20on_20bg1_204bpp_20in_20mode_201_127',['1. Set up text on BG1 (4bpp in Mode 1)',['../examples_sprites_sprite_sizes.html#autotoc_md1700',1,'']]],
  ['set_20up_20three_20background_20layers_128',['1. Set up three background layers',['../examples_backgrounds_mode1_bg3_priority.html#autotoc_md1012',1,'']]],
  ['setbrightness_200_129',['🔴 &lt;span class=&quot;tt&quot;&gt;panelFlush&lt;/span&gt; uploads under forced blank — do not do it yourself with &lt;span class=&quot;tt&quot;&gt;setBrightness(0)&lt;/span&gt;',['../tutorial_panel.html#autotoc_md340',1,'']]],
  ['setini_130',['Hi-res and interlace (Modes 5/6, SETINI)',['../tutorial_graphics.html#autotoc_md223',1,'']]],
  ['setscreenon_131',['🔴 &lt;span class=&quot;tt&quot;&gt;mapLoad()&lt;/span&gt; must run before &lt;span class=&quot;tt&quot;&gt;setScreenOn()&lt;/span&gt;',['../tutorial_map.html#autotoc_md272',1,'']]],
  ['setting_20a_20sprite_132',['Setting a Sprite',['../tutorial_sprites.html#autotoc_md381',1,'']]],
  ['setting_20oam_20address_133',['Setting OAM Address',['../oam.html#autotoc_md789',1,'']]],
  ['setting_20palettes_134',['Setting Palettes',['../tutorial_graphics.html#autotoc_md218',1,'']]],
  ['setting_20up_20a_20dynamic_20sprite_135',['Setting Up a Dynamic Sprite',['../tutorial_animation.html#autotoc_md85',1,'']]],
  ['setting_20up_20graphics_136',['Setting Up Graphics',['../tutorial_graphics.html#autotoc_md214',1,'']]],
  ['setting_20up_20memory_137',['Example: Setting Up Memory',['../memory_map.html#autotoc_md775',1,'']]],
  ['setting_20up_20the_20hdma_20channel_138',['4. Setting Up the HDMA Channel',['../examples_hdma_hdma_wave.html#autotoc_md1339',1,'']]],
  ['setting_20up_20the_20ppu_139',['3. Setting Up the PPU',['../examples_fundamentals_text_glyphs.html#autotoc_md1199',1,'']]],
  ['setting_20up_20tilemaps_140',['Setting Up Tilemaps',['../tutorial_graphics.html#autotoc_md217',1,'']]],
  ['settings_141',['$2101 - OBJSEL (Sprite Settings)',['../registers.html#autotoc_md817',1,'']]],
  ['setup_142',['Setup',['../examples_input_superscope.html#autotoc_md1397',1,'5. Direct OAM Setup'],['../examples_backgrounds_mode1.html#autotoc_md982',1,'Basic Setup'],['../tutorial_graphics.html#autotoc_md222',1,'Example: Complete Background Setup'],['../examples_sprites_dynamic_sprite.html#autotoc_md1666',1,'Force Blank for Initial Setup'],['../examples_scrolling_parallax_scroll.html#autotoc_md1621',1,'HDMA Setup'],['../tutorial_audio.html#autotoc_md99',1,'Setup'],['../tutorial_debugging.html#autotoc_md156',1,'Setup'],['../tutorial_superfx.html#autotoc_md430',1,'Setup'],['../examples_color_transparency.html#autotoc_md1185',1,'Setup'],['../contributing.html#autotoc_md1831',1,'Setup'],['../examples_input_two_players.html#autotoc_md1422',1,'Sprite Setup']]],
  ['setup_143',['Build setup',['../tutorial_sram.html#autotoc_md397',1,'']]],
  ['setup_20even_20work_144',['Stage 0 — &quot;Does my setup even work?&quot;',['../learning_path.html#autotoc_md576',1,'']]],
  ['setup_20pattern_145',['Setup pattern',['../tutorial_hdma.html#autotoc_md229',1,'Setup pattern'],['../tutorial_mode7.html#autotoc_md303',1,'Setup pattern']]],
  ['setup_20pattern_146',['The setup pattern',['../tutorial_dma.html#autotoc_md171',1,'']]],
  ['setup_20recommended_147',['Mode 1 Setup (Recommended)',['../snes_graphics_guide.html#autotoc_md643',1,'']]],
  ['setup_20the_20long_20way_148',['Manual setup (the long way)',['../getting_started.html#autotoc_md556',1,'']]],
  ['seven_20amplitude_20levels_149',['3. Seven Amplitude Levels',['../examples_hdma_hdma_wave.html#autotoc_md1338',1,'']]],
  ['several_20panels_20one_20layer_20one_20upload_150',['Several panels, one layer, one upload',['../tutorial_panel.html#autotoc_md338',1,'']]],
  ['sfx_151',['Example: Music + SFX',['../tutorial_audio.html#autotoc_md108',1,'']]],
  ['sfx_20from_20wav_152',['SFX from WAV',['../examples_audio_sfx_from_wav.html',1,'examples_audio']]],
  ['shadow_20buffer_20vs_20hardware_153',['Recipe 4 — Sprite/OAM debugging (shadow buffer vs hardware)',['../tutorial_debugging.html#autotoc_md161',1,'']]],
  ['shadow_5ftint_20—_20recolour_20a_20whole_20scene_20at_20once_154',['shadow_tint — recolour a whole scene at once',['../examples_color_shadow_tint.html',1,'examples_color']]],
  ['shadows_20free_20depth_155',['7. Drop Shadows (Free Depth)',['../examples_games_breakout.html#autotoc_md1227',1,'']]],
  ['shake_20—_20nudge_20the_20scroll_156',['Screen shake — nudge the scroll',['../craft_game_feel.html#autotoc_md476',1,'']]],
  ['shape_20not_20by_20register_157',['🟡 Repeat vs non-repeat on &lt;span class=&quot;tt&quot;&gt;WH0&lt;/span&gt;/&lt;span class=&quot;tt&quot;&gt;WH1&lt;/span&gt; — pick by data shape, not by register',['../tutorial_window.html#autotoc_md447',1,'']]],
  ['shapes_158',['Static shapes vs animated shapes',['../tutorial_window.html#autotoc_md437',1,'']]],
  ['shapes_20in_20commercial_20games_159',['Window Shapes in Commercial Games',['../examples_windows_window.html#autotoc_md1808',1,'']]],
  ['shapes_20vs_20animated_20shapes_160',['Static shapes vs animated shapes',['../tutorial_window.html#autotoc_md437',1,'']]],
  ['shapes_20with_20hdma_161',['Making Non-Rectangular Shapes with HDMA',['../examples_windows_window.html#autotoc_md1802',1,'']]],
  ['share_20one_20write_20twice_20latch_162',['🟡 BG1 scroll and the Mode 7 registers share one write-twice latch',['../tutorial_mode7.html#autotoc_md312',1,'']]],
  ['shared_20by_20everything_20on_20screen_163',['1. VRAM — 64 KB, shared by everything on screen',['../craft_planning.html#autotoc_md485',1,'']]],
  ['shared_20latch_164',['🟡 HDMA on BG1 scroll can corrupt Mode 7 writes (shared latch)',['../tutorial_hdma.html#autotoc_md246',1,'']]],
  ['shared_20palette_20planner_165',['palplan — project shared-palette planner',['../tools_palplan.html',1,'tools']]],
  ['sheet_166',['Register Cheat Sheet',['../snes_graphics_guide.html#autotoc_md679',1,'']]],
  ['sheet_20layout_167',['Sprite Sheet Layout',['../tutorial_animation.html#autotoc_md75',1,'']]],
  ['sheet_20layout_168',['1. Sprite sheet layout',['../examples_sprites_animated_sprite.html#autotoc_md1636',1,'']]],
  ['sheet_20organization_169',['Sprite Sheet Organization',['../tutorial_animation.html#autotoc_md77',1,'']]],
  ['sheet_20was_20converted_170',['🟡 Match &lt;span class=&quot;tt&quot;&gt;base_tile&lt;/span&gt;/&lt;span class=&quot;tt&quot;&gt;stride&lt;/span&gt; to how the sheet was converted',['../tutorial_panel.html#autotoc_md342',1,'']]],
  ['sheet_3a_20s_20must_20match_20the_20sprite_20size_171',['Converting a sheet: &lt;span class=&quot;tt&quot;&gt;-s&lt;/span&gt; must match the sprite size',['../tutorial_sprites.html#autotoc_md386',1,'']]],
  ['sheets_172',['Animated Sprite -- Direction States and Sprite Sheets',['../examples_sprites_animated_sprite.html',1,'examples_sprites']]],
  ['sheets_20in_20vram_173',['Sprite Sheets in VRAM',['../examples_sprites_animated_sprite.html#autotoc_md1642',1,'']]],
  ['sheets_20with_20gfx4snes_174',['Converting Sprite Sheets with gfx4snes',['../tutorial_animation.html#autotoc_md78',1,'']]],
  ['shelf_175',['Go deeper — the curated shelf',['../craft.html#autotoc_md494',1,'']]],
  ['ship_176',['Stage 6 — &quot;Can I finish and ship?&quot;',['../learning_path.html#autotoc_md582',1,'']]],
  ['ship_20in_20the_20lib_20chantier_20b6_202026_2005_2009_177',['&lt;span class=&quot;tt&quot;&gt;atan2&lt;/span&gt; and &lt;span class=&quot;tt&quot;&gt;sqrt&lt;/span&gt; ship in the lib (chantier B6, 2026-05-09)',['../tutorial_math.html#autotoc_md296',1,'']]],
  ['shipped_20example_178',['shipped example',['../tutorial_mosaic.html#autotoc_md326',1,'Worked pattern (the shipped example)'],['../tutorial_sram.html#autotoc_md404',1,'Worked pattern (the shipped example)']]],
  ['shipped_20examples_179',['shipped examples',['../tutorial_hdma.html#autotoc_md230',1,'Worked patterns (the shipped examples)'],['../tutorial_map.html#autotoc_md270',1,'Worked patterns (the shipped examples)'],['../tutorial_mode7.html#autotoc_md307',1,'Worked patterns (the shipped examples)'],['../tutorial_window.html#autotoc_md443',1,'Worked patterns (the shipped examples)'],['../tutorial_colormath.html#autotoc_md144',1,'Worked patterns (the two shipped examples)']]],
  ['shmup_5f1942_180',['shmup_1942',['../examples_games_shmup_1942.html',1,'examples_games']]],
  ['shot_20samples_20from_20wav_20wav2brr_181',['One-shot samples from WAV (wav2brr)',['../tutorial_audio.html#audio_wav2brr',1,'']]],
  ['show_20inside_182',['Inversion: Show Inside',['../examples_windows_window.html#autotoc_md1804',1,'']]],
  ['showcase_20—_20examples_20hdma_20hdma_5fhelpers_183',['Helpers showcase — &lt;span class=&quot;tt&quot;&gt;examples/hdma/hdma_helpers&lt;/span&gt;',['../tutorial_hdma.html#autotoc_md234',1,'']]],
  ['shows_184',['Shows',['../examples_backgrounds_mode1_bg3_priority.html#autotoc_md1008',1,'What This Example Shows'],['../examples_hdma_gradient_colors.html#autotoc_md1309',1,'What This Example Shows'],['../examples_memory_hirom_demo.html#autotoc_md1485',1,'What This Example Shows'],['../examples_memory_save_game.html#autotoc_md1505',1,'What This Example Shows'],['../examples_mode7_perspective.html#autotoc_md1529',1,'What This Example Shows'],['../examples_mode7_rotate_scale.html#autotoc_md1552',1,'What This Example Shows'],['../examples_scrolling_parallax_scroll.html#autotoc_md1615',1,'What This Example Shows'],['../examples_sprites_animated_sprite.html#autotoc_md1631',1,'What This Example Shows'],['../examples_sprites_dynamic_sprite.html#autotoc_md1654',1,'What This Example Shows'],['../examples_sprites_simple_sprite.html#autotoc_md1680',1,'What This Example Shows'],['../examples_sprites_sprite_sizes.html#autotoc_md1696',1,'What This Example Shows'],['../examples_transitions_mosaic.html#autotoc_md1768',1,'What This Example Shows']]],
  ['shows_20the_20backdrop_20not_20a_20layer_185',['🟡 Out-of-bounds with &lt;span class=&quot;tt&quot;&gt;MODE7_TRANSPARENT&lt;/span&gt; shows the backdrop, not a layer',['../tutorial_mode7.html#autotoc_md318',1,'']]],
  ['side_3a_20tiles_20by_20mode_186',['The cost side: tiles by mode',['../craft_planning.html#autotoc_md489',1,'']]],
  ['sign_20convention_187',['Sign convention',['../fixed32_8h.html#autotoc_md30',1,'']]],
  ['signed_20result_188',['🟡 Sin/cos LUTs are unsigned-angle, signed-result',['../tutorial_math.html#autotoc_md295',1,'']]],
  ['silent_20corruption_189',['🔴 Battery dies → silent corruption',['../tutorial_sram.html#autotoc_md407',1,'']]],
  ['silently_20dropped_190',['🔴 VRAM/CGRAM/OAM writes outside VBlank or force blank are silently dropped',['../tutorial_dma.html#autotoc_md175',1,'']]],
  ['simple_20game_20over_20breakout_191',['Simple Game Over (Breakout)',['../tutorial_game_states.html#autotoc_md208',1,'']]],
  ['simple_20parallax_20multiple_20bgs_192',['Simple Parallax (Multiple BGs)',['../tutorial_scrolling.html#autotoc_md370',1,'']]],
  ['simple_20sprite_20your_20first_20oam_20sprite_193',['Simple Sprite -- Your First OAM Sprite',['../examples_sprites_simple_sprite.html',1,'examples_sprites']]],
  ['sin_20cos_20lookup_20tables_194',['Trigonometry (sin/cos lookup tables)',['../tutorial_math.html#autotoc_md280',1,'']]],
  ['sin_20cos_20luts_20are_20unsigned_20angle_20signed_20result_195',['🟡 Sin/cos LUTs are unsigned-angle, signed-result',['../tutorial_math.html#autotoc_md295',1,'']]],
  ['since_20chantier_20a1_196',['🟢 &lt;span class=&quot;tt&quot;&gt;int&lt;/span&gt; and &lt;span class=&quot;tt&quot;&gt;long&lt;/span&gt; sizes are correct on this target (since chantier A1)',['../tutorial_math.html#autotoc_md289',1,'']]],
  ['single_20bg_20layer_197',['🔴 Single BG layer',['../tutorial_mode7.html#autotoc_md313',1,'']]],
  ['size_198',['Size',['../registers.html#autotoc_md824',1,'$2107-$210A - BG1SC-BG4SC (Tilemap Address/Size)'],['../registers.html#autotoc_md858',1,'$43x5-$43x6 - DASxL/H (Transfer Size)'],['../tutorial_animation.html#autotoc_md88',1,'One Draw Function, Engine-Resolved Size']]],
  ['size_199',['size',['../troubleshooting.html#autotoc_md748',1,'&quot;ROM too large&quot; or linker errors about size'],['../examples_sprites_simple_sprite.html#autotoc_md1687',1,'3. Configure OBJ size'],['../tutorial_sprites.html#autotoc_md386',1,'Converting a sheet: &lt;span class=&quot;tt&quot;&gt;-s&lt;/span&gt; must match the sprite size']]],
  ['size_201_20pixels_200',['🟡 Mosaic block size is &quot;size + 1&quot; pixels',['../tutorial_mosaic.html#autotoc_md330',1,'']]],
  ['size_20all_206_20snes_20sprite_20size_20modes_201',['Object Size -- All 6 SNES Sprite Size Modes',['../examples_sprites_sprite_sizes.html',1,'examples_sprites']]],
  ['size_20is_20size_201_20pixels_202',['🟡 Mosaic block size is &quot;size + 1&quot; pixels',['../tutorial_mosaic.html#autotoc_md330',1,'']]],
  ['size_20modes_203',['Size Modes',['../examples_sprites_sprite_sizes.html',1,'Object Size -- All 6 SNES Sprite Size Modes'],['../examples_sprites_sprite_sizes.html#autotoc_md1703',1,'The 6 Size Modes']]],
  ['size_20modes_20register_20_242101_204',['OBJ Size Modes (Register $2101)',['../examples_sprites_metasprite.html#autotoc_md1671',1,'']]],
  ['sizes_205',['Sizes',['../tutorial_collision.html#autotoc_md126',1,'Custom Tile Sizes'],['../tutorial_sprites.html#autotoc_md391',1,'Sprite Sizes'],['../snes_graphics_guide.html#autotoc_md652',1,'Sprite Sizes'],['../oam.html#autotoc_md790',1,'Sprite Sizes'],['../snes_graphics_guide.html#autotoc_md647',1,'Tilemap Sizes'],['../snes_sound_guide.html#autotoc_md718',1,'Typical Sample Sizes']]],
  ['sizes_20are_20correct_20on_20this_20target_20since_20chantier_20a1_206',['🟢 &lt;span class=&quot;tt&quot;&gt;int&lt;/span&gt; and &lt;span class=&quot;tt&quot;&gt;long&lt;/span&gt; sizes are correct on this target (since chantier A1)',['../tutorial_math.html#autotoc_md289',1,'']]],
  ['slice_20panels_207',['9-slice panels',['../tutorial_panel.html',1,'index']]],
  ['slide_20along_20walls_208',['Stopping Movement (Slide Along Walls)',['../tutorial_collision.html#autotoc_md130',1,'']]],
  ['sliding_209',['Per-Axis Sliding',['../examples_basics_collision_demo.html#autotoc_md1071',1,'']]],
  ['slope_20collision_210',['Object Engine and Slope Collision',['../examples_maps_slope_collision.html#autotoc_md1468',1,'']]],
  ['slope_20mario_211',['Slope Mario',['../examples_maps_slope_collision.html',1,'examples_maps']]],
  ['slot_212',['1. NOP After Every Branch (Delay Slot)',['../tutorial_superfx.html#autotoc_md425',1,'']]],
  ['slot_20saves_213',['Multi-slot saves',['../tutorial_sram.html#autotoc_md402',1,'']]],
  ['slot_20types_214',['Fixed-point: three slot types',['../tutorial_dsp1.html#autotoc_md186',1,'']]],
  ['slots_215',['Slots',['../examples_scrolling_mixed_scroll.html#autotoc_md1605',1,'Palette Slots'],['../examples_memory_save_game.html#autotoc_md1517',1,'Save Slots']]],
  ['small_216',['Keep PRs small',['../contributing.html#autotoc_md1836',1,'']]],
  ['smallest_20complete_20game_217',['game_skeleton — the smallest complete game',['../examples_basics_game_skeleton.html',1,'examples_basics']]],
  ['smconv_218',['smconv',['../third_party.html#autotoc_md758',1,'']]],
  ['smconv_20—_20tracker_20modules_20to_20snesmod_20soundbanks_219',['smconv — tracker modules to SNESMOD soundbanks',['../tools_smconv.html',1,'tools']]],
  ['smconv_20error_220',['Build fails with smconv error',['../examples_audio_snesmod_music.html#autotoc_md932',1,'']]],
  ['smconv_20options_221',['smconv Options',['../examples_audio_snesmod_music.html#autotoc_md937',1,'']]],
  ['smconv_20tool_222',['smconv Tool',['../tutorial_audio.html#autotoc_md105',1,'']]],
  ['smooth_20fade_223',['Exercise 1: Smooth Fade',['../examples_transitions_fading.html#autotoc_md1757',1,'']]],
  ['smooth_20interpolation_224',['Smooth interpolation',['../tutorial_math.html#autotoc_md286',1,'']]],
  ['smooth_20sprite_20movement_225',['Smooth sprite movement',['../tutorial_math.html#autotoc_md284',1,'']]],
  ['snapping_20to_20tile_20grid_20platformer_20landing_226',['Snapping to Tile Grid (Platformer Landing)',['../tutorial_collision.html#autotoc_md133',1,'']]],
  ['snes_227',['SNES',['../examples_input_controller.html#autotoc_md1363',1,'How Input Works on the SNES'],['../examples_text.html#autotoc_md1724',1,'How Text Works on SNES'],['../examples_audio_speech_synth.html',1,'speech_synth — the SNES says &quot;OPEN SNES&quot;'],['../craft_tiles_to_levels.html#autotoc_md499',1,'The workflow: design in Tiled, convert for the SNES'],['../tutorial_math.html#autotoc_md276',1,'Why fixed-point on the SNES']]],
  ['snes_20audio_20architecture_228',['SNES Audio Architecture',['../tutorial_audio.html#autotoc_md96',1,'']]],
  ['snes_20compatibility_229',['For SNES Compatibility',['../snes_graphics_guide.html#autotoc_md670',1,'']]],
  ['snes_20concepts_230',['SNES Concepts',['../examples_audio_apu_switch.html#autotoc_md871',1,'SNES Concepts'],['../examples_audio_pitch_mod.html#autotoc_md881',1,'SNES Concepts'],['../examples_audio_play_noise.html#autotoc_md885',1,'SNES Concepts'],['../examples_audio_sfx_from_wav.html#autotoc_md890',1,'SNES Concepts'],['../examples_audio_snesmod_sfx.html#autotoc_md952',1,'SNES Concepts'],['../examples_audio_soundboard.html#autotoc_md960',1,'SNES Concepts'],['../examples_backgrounds_mode1_bg3_priority.html#autotoc_md1015',1,'SNES Concepts'],['../examples_backgrounds_mode1_lz77.html#autotoc_md1023',1,'SNES Concepts'],['../examples_backgrounds_mode5_hires.html#autotoc_md1051',1,'SNES Concepts'],['../examples_basics_aim_target.html#autotoc_md1059',1,'SNES Concepts'],['../examples_basics_collision_demo.html#autotoc_md1068',1,'SNES Concepts'],['../examples_basics_fix32_orbit.html#autotoc_md1079',1,'SNES Concepts'],['../examples_basics_random.html#autotoc_md1098',1,'SNES Concepts'],['../examples_basics_scene_stack.html#autotoc_md1108',1,'SNES Concepts'],['../examples_basics_timer.html#autotoc_md1116',1,'SNES Concepts'],['../examples_chips_dsp1_cube.html#autotoc_md1121',1,'SNES Concepts'],['../examples_color_direct_color.html#autotoc_md1146',1,'SNES Concepts'],['../examples_color_gradient_9bit.html#autotoc_md1149',1,'SNES Concepts'],['../examples_color_hicolor_1792.html#autotoc_md1153',1,'SNES Concepts'],['../examples_color_transparency.html#autotoc_md1178',1,'SNES Concepts'],['../examples_games_mapandobjects.html#autotoc_md1271',1,'SNES Concepts'],['../examples_games_mode7_flying.html#autotoc_md1284',1,'SNES Concepts'],['../examples_games_mode7_racing.html#autotoc_md1287',1,'SNES Concepts'],['../examples_games_rpg.html#autotoc_md1293',1,'SNES Concepts'],['../examples_hdma_gradient_colors.html#autotoc_md1317',1,'SNES Concepts'],['../examples_hdma_hdma_indirect_gradient.html#autotoc_md1328',1,'SNES Concepts'],['../examples_hdma_hdma_wave_table.html#autotoc_md1355',1,'SNES Concepts'],['../examples_input_controller.html#autotoc_md1362',1,'SNES Concepts'],['../examples_input_mouse.html#autotoc_md1369',1,'SNES Concepts'],['../examples_maps_dynamic_map.html#autotoc_md1446',1,'SNES Concepts'],['../examples_maps_map_scroll.html#autotoc_md1457',1,'SNES Concepts'],['../examples_maps_slope_collision.html#autotoc_md1466',1,'SNES Concepts'],['../examples_maps_tiled.html#autotoc_md1477',1,'SNES Concepts'],['../examples_memory_hirom_demo.html#autotoc_md1494',1,'SNES Concepts'],['../examples_memory_save_game.html#autotoc_md1515',1,'SNES Concepts'],['../examples_mode7_dsp1_ground.html#autotoc_md1524',1,'SNES Concepts'],['../examples_mode7_perspective.html#autotoc_md1537',1,'SNES Concepts'],['../examples_mode7_perspective_rotate.html#autotoc_md1544',1,'SNES Concepts'],['../examples_mode7_rotate_scale.html#autotoc_md1561',1,'SNES Concepts'],['../examples_scrolling_mixed_scroll.html#autotoc_md1602',1,'SNES Concepts'],['../examples_scrolling_parallax_scroll.html#autotoc_md1623',1,'SNES Concepts'],['../examples_sprites_animated_sprite.html#autotoc_md1640',1,'SNES Concepts'],['../examples_sprites_aseprite_pipeline.html#autotoc_md1646',1,'SNES Concepts'],['../examples_sprites_dynamic_sprite.html#autotoc_md1663',1,'SNES Concepts'],['../examples_sprites_metasprite.html#autotoc_md1670',1,'SNES Concepts'],['../examples_sprites_simple_sprite.html#autotoc_md1690',1,'SNES Concepts'],['../examples_sprites_sprite_sizes.html#autotoc_md1704',1,'SNES Concepts'],['../examples_transitions_mosaic.html#autotoc_md1776',1,'SNES Concepts'],['../examples_windows_transparent_window.html#autotoc_md1793',1,'SNES Concepts'],['../examples_windows_window.html#autotoc_md1806',1,'SNES Concepts'],['../examples_windows_window_multi_hdma.html#autotoc_md1812',1,'SNES Concepts']]],
  ['snes_20concepts_231',['SNES concepts',['../examples_audio_echo.html#autotoc_md876',1,'SNES concepts'],['../examples_input_move_sprite.html#autotoc_md1383',1,'SNES concepts'],['../examples_text_print_string.html#autotoc_md1718',1,'SNES concepts'],['../examples_text_scroll_message.html#autotoc_md1730',1,'SNES concepts']]],
  ['snes_20controller_20layout_232',['SNES Controller Layout',['../tutorial_input.html#autotoc_md251',1,'']]],
  ['snes_20development_233',['Learn SNES Development',['../learning_path.html',1,'index']]],
  ['snes_20game_234',['Planning your SNES game',['../craft_planning.html',1,'craft']]],
  ['snes_20graphics_20programming_20guide_235',['SNES Graphics Programming Guide',['../snes_graphics_guide.html',1,'index']]],
  ['snes_20hardware_20overview_236',['SNES Hardware Overview',['../hardware_overview.html',1,'index']]],
  ['snes_20hardware_20register_20reference_237',['SNES Hardware Register Reference',['../registers.html',1,'index']]],
  ['snes_20map_20data_238',['tmx2snes — Tiled levels to SNES map data',['../tools_tmx2snes.html',1,'tools']]],
  ['snes_20memory_20map_239',['SNES Memory Map',['../memory_map.html',1,'index']]],
  ['snes_20memory_20mapping_240',['HiROM Demo -- Understanding SNES Memory Mapping',['../examples_memory_hirom_demo.html',1,'examples_memory']]],
  ['snes_20mouse_241',['SNES Mouse',['../examples_input_mouse.html',1,'examples_input']]],
  ['snes_20mouse_20hardware_242',['SNES Mouse Hardware',['../examples_input_mouse.html#autotoc_md1370',1,'']]],
  ['snes_20oam_20object_20attribute_20memory_243',['SNES OAM (Object Attribute Memory)',['../oam.html',1,'index']]],
  ['snes_20says_20open_20snes_244',['speech_synth — the SNES says &quot;OPEN SNES&quot;',['../examples_audio_speech_synth.html',1,'examples_audio']]],
  ['snes_20sound_20programming_20guide_245',['SNES Sound Programming Guide',['../snes_sound_guide.html',1,'index']]],
  ['snes_20sprite_20basics_246',['SNES Sprite Basics',['../tutorial_sprites.html#autotoc_md377',1,'']]],
  ['snes_20sprite_20limits_247',['SNES Sprite Limits',['../sprite_8h.html#autotoc_md59',1,'']]],
  ['snes_20sprite_20size_20modes_248',['Object Size -- All 6 SNES Sprite Size Modes',['../examples_sprites_sprite_sizes.html',1,'examples_sprites']]],
  ['snes_20video_20modes_249',['SNES Video Modes',['../tutorial_graphics.html#autotoc_md213',1,'']]],
  ['snes_20window_20system_250',['SNES Window System',['../examples_windows_window.html#autotoc_md1801',1,'']]],
  ['snesmod_251',['The raw APU path (no snesmod)',['../tutorial_audio.html#autotoc_md114',1,'']]],
  ['snesmod_20api_252',['SNESMOD API',['../examples_audio_snesmod_music.html#autotoc_md904',1,'']]],
  ['snesmod_20initialization_253',['SNESMOD Initialization',['../examples_audio_snesmod_sfx.html#autotoc_md953',1,'']]],
  ['snesmod_20large_20soundbank_20music_254',['SNESMOD Large Soundbank Music',['../examples_audio_snesmod_music_large.html',1,'examples_audio']]],
  ['snesmod_20music_20example_255',['SNESMOD Music Example',['../examples_audio_snesmod_music.html',1,'examples_audio']]],
  ['snesmod_20overview_256',['SNESMOD Overview',['../examples_audio_snesmod_music.html#autotoc_md901',1,'']]],
  ['snesmod_20recommended_257',['SNESMOD (Recommended)',['../tutorial_audio.html#autotoc_md98',1,'']]],
  ['snesmod_20sound_20effects_258',['SNESMOD Sound Effects',['../examples_audio_snesmod_sfx.html',1,'examples_audio']]],
  ['snesmod_20soundbanks_259',['smconv — tracker modules to SNESMOD soundbanks',['../tools_smconv.html',1,'tools']]],
  ['snesmodprocess_260',['Important: Call snesmodProcess()!',['../tutorial_audio.html#autotoc_md107',1,'']]],
  ['so_20many_20modules_261',['Why So Many Modules?',['../examples_games_likemario.html#autotoc_md1264',1,'']]],
  ['so_20stream_20it_262',['The level is bigger than VRAM — so stream it',['../craft_tiles_to_levels.html#autotoc_md498',1,'']]],
  ['solution_263',['The Solution',['../oam.html#autotoc_md786',1,'']]],
  ['something_20on_20screen_264',['Stage 1 — &quot;Can I put something on screen?&quot;',['../learning_path.html#autotoc_md577',1,'']]],
  ['sound_20creation_20tools_265',['Sound Creation Tools',['../snes_sound_guide.html#autotoc_md721',1,'']]],
  ['sound_20effects_266',['Sound Effects',['../examples_audio_snesmod_music.html#autotoc_md925',1,'Exercise 1: Add Sound Effects'],['../examples_audio_snesmod_sfx.html',1,'SNESMOD Sound Effects'],['../tutorial_audio.html#autotoc_md102',1,'Sound Effects']]],
  ['sound_20programming_20guide_267',['SNES Sound Programming Guide',['../snes_sound_guide.html',1,'index']]],
  ['sound_20samples_268',['wav2brr — WAV to BRR sound samples',['../tools_wav2brr.html',1,'tools']]],
  ['soundbank_269',['The Soundbank',['../examples_audio_snesmod_sfx.html#autotoc_md955',1,'']]],
  ['soundbank_20creation_270',['Soundbank Creation',['../snesmod_8h.html#autotoc_md57',1,'']]],
  ['soundbank_20music_271',['SNESMOD Large Soundbank Music',['../examples_audio_snesmod_music_large.html',1,'examples_audio']]],
  ['soundbanks_272',['smconv — tracker modules to SNESMOD soundbanks',['../tools_smconv.html',1,'tools']]],
  ['soundboard_20—_20the_20audio_20v2_20engine_20driven_20entirely_20from_20c_273',['soundboard — the audio v2 engine, driven entirely from C',['../examples_audio_soundboard.html',1,'examples_audio']]],
  ['sounds_20wrong_274',['Music sounds wrong',['../examples_audio_snesmod_music.html#autotoc_md931',1,'']]],
  ['source_20address_275',['$43x2-$43x4 - A1TxL/H/B (Source Address)',['../registers.html#autotoc_md857',1,'']]],
  ['source_20addressing_276',['Direction and source addressing',['../tutorial_dma.html#autotoc_md169',1,'']]],
  ['source_20c_277',['Source (.c)',['../code_style.html#autotoc_md635',1,'']]],
  ['source_20code_278',['Source Code',['../example_sources.html',1,'Example Source Code'],['../index.html#autotoc_md6',1,'Examples (Annotated Source Code)']]],
  ['sources_279',['Sample Sources',['../snes_sound_guide.html#autotoc_md723',1,'']]],
  ['sources_20cc0_20public_20domain_280',['Free Asset Sources (CC0/Public Domain)',['../snes_graphics_guide.html#autotoc_md675',1,'']]],
  ['space_281',['SRAM Address Space',['../examples_memory_save_game.html#autotoc_md1516',1,'']]],
  ['space_20overview_282',['Address Space Overview',['../memory_map.html#autotoc_md765',1,'']]],
  ['spc_20dump_283',['Debugging audio: luna&apos;s spc-dump',['../tutorial_audio.html#autotoc_md116',1,'']]],
  ['spc_20ram_284',['SPC RAM',['../examples_audio_snesmod_music.html#autotoc_md922',1,'']]],
  ['spc700_20cpu_285',['SPC700 CPU',['../snes_sound_guide.html#autotoc_md686',1,'']]],
  ['special_20timing_286',['🟠 SRAM access requires no special timing',['../tutorial_sram.html#autotoc_md409',1,'']]],
  ['specifications_287',['Specifications',['../hardware_overview.html#autotoc_md801',1,'']]],
  ['specifics_288',['BG3 Specifics',['../examples_backgrounds_mode1.html#autotoc_md1004',1,'']]],
  ['speech_5fsynth_20—_20the_20snes_20says_20open_20snes_289',['speech_synth — the SNES says &quot;OPEN SNES&quot;',['../examples_audio_speech_synth.html',1,'examples_audio']]],
  ['speeds_290',['Speeds',['../examples_scrolling_continuous_scroll.html#autotoc_md1584',1,'1. Two Layers, Two Speeds'],['../examples_input_two_players.html#autotoc_md1434',1,'Exercise 2: Different Speeds'],['../examples_transitions_fading.html#autotoc_md1747',1,'Fade Speeds']]],
  ['spelling_20the_20message_291',['6. Spelling the Message',['../examples_fundamentals_text_glyphs.html#autotoc_md1202',1,'']]],
  ['split_292',['CGRAM Split',['../examples_sprites_simple_sprite.html#autotoc_md1692',1,'']]],
  ['split_20bg_20vs_20sprites_293',['2. CGRAM — 256 colours, split BG vs sprites',['../craft_planning.html#autotoc_md486',1,'']]],
  ['split_20blend_294',['&quot;3840 colors&quot; — RGB channel-split blend',['../examples_color_hicolor_blend.html',1,'examples_color']]],
  ['split_20screen_295',['Exercise 4: Split Screen',['../examples_input_two_players.html#autotoc_md1436',1,'']]],
  ['split_20screen_20with_20hdma_296',['1. Split-screen with HDMA',['../examples_mode7_perspective.html#autotoc_md1534',1,'']]],
  ['spotlight_20blend_20—_20examples_20windows_20transparent_5fwindow_297',['Window-gated spotlight blend — &lt;span class=&quot;tt&quot;&gt;examples/windows/transparent_window&lt;/span&gt;',['../tutorial_colormath.html#autotoc_md146',1,'']]],
  ['sprite_298',['Sprite',['../examples_input_mouse.html#autotoc_md1376',1,'2. Load Cursor Sprite'],['../tutorial_sprites.html#autotoc_md381',1,'Setting a Sprite'],['../tutorial_animation.html#autotoc_md85',1,'Setting Up a Dynamic Sprite'],['../examples_sprites_simple_sprite.html',1,'Simple Sprite -- Your First OAM Sprite']]],
  ['sprite_299',['sprite',['../examples_sprites_simple_sprite.html#autotoc_md1688',1,'4. Place the sprite'],['../oam.html#autotoc_md783',1,'Extended Table (2 bits per sprite)'],['../oam.html#autotoc_md781',1,'Main Table (4 bytes per sprite)']]],
  ['sprite_20basics_300',['SNES Sprite Basics',['../tutorial_sprites.html#autotoc_md377',1,'']]],
  ['sprite_20collision_301',['Sprite-to-Sprite Collision',['../tutorial_collision.html#autotoc_md119',1,'']]],
  ['sprite_20direction_20states_20and_20sprite_20sheets_302',['Animated Sprite -- Direction States and Sprite Sheets',['../examples_sprites_animated_sprite.html',1,'examples_sprites']]],
  ['sprite_20engine_303',['Sprite Engine',['../examples_maps_slope_collision.html#autotoc_md1469',1,'Dynamic Sprite Engine'],['../tutorial_animation.html#autotoc_md82',1,'The Dynamic Sprite Engine']]],
  ['sprite_20engine_304',['1. Initialize the dynamic sprite engine',['../examples_sprites_dynamic_sprite.html#autotoc_md1659',1,'']]],
  ['sprite_20functions_305',['Using OpenSNES Sprite Functions',['../tutorial_sprites.html#autotoc_md379',1,'']]],
  ['sprite_20graphics_20into_20vram_306',['1. Load sprite graphics into VRAM',['../examples_sprites_simple_sprite.html#autotoc_md1685',1,'']]],
  ['sprite_20is_20vs_20where_20it_20collides_307',['Where the sprite is vs where it collides',['../tutorial_collision.html#autotoc_md128',1,'']]],
  ['sprite_20limits_308',['SNES Sprite Limits',['../sprite_8h.html#autotoc_md59',1,'']]],
  ['sprite_20memory_309',['OAM (Sprite Memory)',['../registers.html#autotoc_md818',1,'']]],
  ['sprite_20movement_310',['Smooth sprite movement',['../tutorial_math.html#autotoc_md284',1,'']]],
  ['sprite_20oam_20debugging_20shadow_20buffer_20vs_20hardware_311',['Recipe 4 — Sprite/OAM debugging (shadow buffer vs hardware)',['../tutorial_debugging.html#autotoc_md161',1,'']]],
  ['sprite_20palette_312',['2. Load the sprite palette',['../examples_sprites_simple_sprite.html#autotoc_md1686',1,'']]],
  ['sprite_20palettes_313',['Sprite Palettes',['../tutorial_sprites.html#autotoc_md387',1,'']]],
  ['sprite_20per_20line_20budget_3a_2032_314',['The sprite-per-line budget: 32',['../craft_frame_budget.html#autotoc_md472',1,'']]],
  ['sprite_20positioning_315',['Camera-Relative Sprite Positioning',['../examples_maps_map_scroll.html#autotoc_md1459',1,'']]],
  ['sprite_20priority_316',['Sprite Priority',['../snes_graphics_guide.html#autotoc_md654',1,'']]],
  ['sprite_20settings_317',['$2101 - OBJSEL (Sprite Settings)',['../registers.html#autotoc_md817',1,'']]],
  ['sprite_20setup_318',['Sprite Setup',['../examples_input_two_players.html#autotoc_md1422',1,'']]],
  ['sprite_20sheet_20layout_319',['Sprite Sheet Layout',['../tutorial_animation.html#autotoc_md75',1,'']]],
  ['sprite_20sheet_20layout_320',['1. Sprite sheet layout',['../examples_sprites_animated_sprite.html#autotoc_md1636',1,'']]],
  ['sprite_20sheet_20organization_321',['Sprite Sheet Organization',['../tutorial_animation.html#autotoc_md77',1,'']]],
  ['sprite_20sheets_322',['Animated Sprite -- Direction States and Sprite Sheets',['../examples_sprites_animated_sprite.html',1,'examples_sprites']]],
  ['sprite_20sheets_20in_20vram_323',['Sprite Sheets in VRAM',['../examples_sprites_animated_sprite.html#autotoc_md1642',1,'']]],
  ['sprite_20sheets_20with_20gfx4snes_324',['Converting Sprite Sheets with gfx4snes',['../tutorial_animation.html#autotoc_md78',1,'']]],
  ['sprite_20size_325',['Converting a sheet: &lt;span class=&quot;tt&quot;&gt;-s&lt;/span&gt; must match the sprite size',['../tutorial_sprites.html#autotoc_md386',1,'']]],
  ['sprite_20size_20modes_326',['Object Size -- All 6 SNES Sprite Size Modes',['../examples_sprites_sprite_sizes.html',1,'examples_sprites']]],
  ['sprite_20sizes_327',['Sprite Sizes',['../tutorial_sprites.html#autotoc_md391',1,'Sprite Sizes'],['../snes_graphics_guide.html#autotoc_md652',1,'Sprite Sizes'],['../oam.html#autotoc_md790',1,'Sprite Sizes']]],
  ['sprite_20system_328',['1. Initialize the Map and Sprite System',['../examples_games_mapandobjects.html#autotoc_md1277',1,'']]],
  ['sprite_20tiles_329',['Loading Sprite Tiles',['../tutorial_sprites.html#autotoc_md385',1,'']]],
  ['sprite_20to_20background_20collision_330',['Sprite-to-Background Collision',['../tutorial_collision.html#autotoc_md123',1,'']]],
  ['sprite_20to_20sprite_20collision_331',['Sprite-to-Sprite Collision',['../tutorial_collision.html#autotoc_md119',1,'']]],
  ['sprite_20vram_20streaming_20for_20animated_20sprites_332',['Dynamic Sprite -- VRAM Streaming for Animated Sprites',['../examples_sprites_dynamic_sprite.html',1,'examples_sprites']]],
  ['sprite_20with_20the_20pad_333',['Drive a sprite with the pad',['../examples_input_move_sprite.html',1,'examples_input']]],
  ['sprite_20y_201_20scanline_20quirk_334',['Sprite Y +1 Scanline Quirk',['../oam.html#autotoc_md792',1,'']]],
  ['sprite_20your_20first_20oam_20sprite_335',['Simple Sprite -- Your First OAM Sprite',['../examples_sprites_simple_sprite.html',1,'examples_sprites']]],
  ['sprite_5fswarm_20—_20a_20bouncing_20swarm_20and_20the_20oam_20throughput_20ceiling_336',['sprite_swarm — a bouncing swarm, and the OAM throughput ceiling',['../examples_sprites_sprite_swarm.html',1,'examples_sprites']]],
  ['sprites_337',['Sprites',['../examples_games_breakout.html#autotoc_md1224',1,'4. Bricks Are Not Sprites'],['../examples_input_superscope.html#autotoc_md1396',1,'4. Sprites'],['../examples_sprites_dynamic_sprite.html',1,'Dynamic Sprite -- VRAM Streaming for Animated Sprites'],['../examples_games_mapandobjects.html#autotoc_md1274',1,'Dynamic Sprites'],['../tutorial_sprites.html#autotoc_md383',1,'Hiding Sprites'],['../oam.html#autotoc_md791',1,'Hiding Sprites'],['../examples_sprites.html',1,'Sprites'],['../examples_by_category.html#autotoc_md591',1,'Sprites'],['../snes_graphics_guide.html#autotoc_md650',1,'Sprites'],['../group__examples.html#autotoc_md1819',1,'Sprites'],['../examples_sprites_dynamic_sprite.html#autotoc_md1665',1,'Static vs Dynamic Sprites'],['../hardware_overview.html#autotoc_md806',1,'Tiles and Sprites']]],
  ['sprites_338',['sprites',['../tutorial_mosaic.html#autotoc_md328',1,'🟠 Mosaic does not affect OBJ (sprites)'],['../craft_planning.html#autotoc_md486',1,'2. CGRAM — 256 colours, split BG vs sprites']]],
  ['sprites_20animation_20tutorial_339',['Sprites &amp;amp; Animation Tutorial',['../tutorial_sprites.html',1,'index']]],
  ['sprites_20are_20unaffected_340',['Sprites Are Unaffected',['../examples_transitions_mosaic.html#autotoc_md1779',1,'']]],
  ['sprites_20as_20ui_20elements_341',['Sprites as UI Elements',['../examples_input_mouse.html#autotoc_md1372',1,'']]],
  ['sprites_20but_20far_20fewer_20per_20line_342',['3. OAM — 128 sprites, but far fewer per line',['../craft_planning.html#autotoc_md487',1,'']]],
  ['sprites_20don_20t_20appear_343',['Sprites don&apos;t appear',['../troubleshooting.html#autotoc_md740',1,'']]],
  ['sprites_20per_20mode_344',['3. Two sprites per mode',['../examples_sprites_sprite_sizes.html#autotoc_md1702',1,'']]],
  ['sprites_20via_20the_20oambuffer_345',['2. Set up sprites via the oambuffer',['../examples_sprites_dynamic_sprite.html#autotoc_md1660',1,'']]],
  ['sprites_20with_20force_20blank_346',['2. Load sprites with force blank',['../examples_sprites_sprite_sizes.html#autotoc_md1701',1,'']]],
  ['sqrt_20ship_20in_20the_20lib_20chantier_20b6_202026_2005_2009_347',['&lt;span class=&quot;tt&quot;&gt;atan2&lt;/span&gt; and &lt;span class=&quot;tt&quot;&gt;sqrt&lt;/span&gt; ship in the lib (chantier B6, 2026-05-09)',['../tutorial_math.html#autotoc_md296',1,'']]],
  ['squash_20and_20stretch_20without_20scaling_348',['Squash and stretch without scaling',['../craft_game_feel.html#autotoc_md481',1,'']]],
  ['sram_349',['SRAM',['../tutorial_sram.html#autotoc_md410',1,'🟠 Cannot store pointers in SRAM'],['../examples_memory_save_game.html#autotoc_md1511',1,'2. Save to SRAM'],['../examples_memory_save_game.html#autotoc_md1512',1,'3. Load from SRAM']]],
  ['sram_20access_20requires_20no_20special_20timing_350',['🟠 SRAM access requires no special timing',['../tutorial_sram.html#autotoc_md409',1,'']]],
  ['sram_20actually_20is_351',['What SRAM actually is',['../tutorial_sram.html#autotoc_md395',1,'']]],
  ['sram_20address_20space_352',['SRAM Address Space',['../examples_memory_save_game.html#autotoc_md1516',1,'']]],
  ['sram_20battery_20backup_353',['SRAM (Battery Backup)',['../examples_memory.html#autotoc_md1503',1,'']]],
  ['sram_20contents_20on_20first_20boot_20are_20undefined_354',['🔴 SRAM contents on first boot are undefined',['../tutorial_sram.html#autotoc_md406',1,'']]],
  ['sram_20in_20the_20makefile_355',['4. Enable SRAM in the Makefile',['../examples_memory_save_game.html#autotoc_md1513',1,'']]],
  ['sram_20overview_356',['SRAM Overview',['../sram_8h.html#autotoc_md62',1,'']]],
  ['sram_20persistence_357',['Save Game -- SRAM Persistence',['../examples_memory_save_game.html',1,'examples_memory']]],
  ['sram_20save_20tutorial_358',['SRAM Save Tutorial',['../tutorial_sram.html',1,'index']]],
  ['sram_20to_20vram_20transfer_359',['SRAM to VRAM Transfer',['../tutorial_superfx.html#autotoc_md432',1,'']]],
  ['sram_5fsize_20mismatch_20between_20makefile_20and_20code_360',['🔴 &lt;span class=&quot;tt&quot;&gt;SRAM_SIZE&lt;/span&gt; mismatch between Makefile and code',['../tutorial_sram.html#autotoc_md408',1,'']]],
  ['sramclear_20is_20a_20memset_20not_20a_20write_20protect_361',['🟡 &lt;span class=&quot;tt&quot;&gt;sramClear&lt;/span&gt; is a memset, not a write-protect',['../tutorial_sram.html#autotoc_md413',1,'']]],
  ['sta_20l_20lda_20l_20for_20everything_362',['Use &lt;span class=&quot;tt&quot;&gt;sta.l&lt;/span&gt; / &lt;span class=&quot;tt&quot;&gt;lda.l&lt;/span&gt; for Everything',['../tutorial_sa1.html#autotoc_md356',1,'']]],
  ['stack_363',['Scene Stack',['../examples_basics_scene_stack.html',1,'examples_basics']]],
  ['stack_20recommended_20—_20scene_20module_364',['The scene stack (recommended) — &lt;span class=&quot;tt&quot;&gt;scene&lt;/span&gt; module',['../tutorial_game_states.html#autotoc_md198',1,'']]],
  ['stage_200_20—_20does_20my_20setup_20even_20work_365',['Stage 0 — &quot;Does my setup even work?&quot;',['../learning_path.html#autotoc_md576',1,'']]],
  ['stage_201_20—_20can_20i_20put_20something_20on_20screen_366',['Stage 1 — &quot;Can I put something on screen?&quot;',['../learning_path.html#autotoc_md577',1,'']]],
  ['stage_202_20—_20can_20the_20player_20act_367',['Stage 2 — &quot;Can the player act?&quot;',['../learning_path.html#autotoc_md578',1,'']]],
  ['stage_203_20—_20can_20i_20build_20a_20world_368',['Stage 3 — &quot;Can I build a world?&quot;',['../learning_path.html#autotoc_md579',1,'']]],
  ['stage_204_20—_20can_20i_20make_20it_20feel_20good_369',['Stage 4 — &quot;Can I make it feel good?&quot;',['../learning_path.html#autotoc_md580',1,'']]],
  ['stage_205_20—_20can_20i_20hold_20it_20all_20together_370',['Stage 5 — &quot;Can I hold it all together?&quot;',['../learning_path.html#autotoc_md581',1,'']]],
  ['stage_206_20—_20can_20i_20finish_20and_20ship_371',['Stage 6 — &quot;Can I finish and ship?&quot;',['../learning_path.html#autotoc_md582',1,'']]],
  ['starfield_20murmuration_372',['SA-1 Starfield (Murmuration)',['../examples_chips_sa1_starfield.html',1,'examples_chips']]],
  ['start_373',['Start',['../audio_8h.html#autotoc_md13',1,'Quick Start'],['../profile_8h.html#autotoc_md51',1,'Quick Start'],['../snesmod_8h.html#autotoc_md56',1,'Quick Start']]],
  ['start_20here_374',['Start Here',['../index.html#autotoc_md0',1,'']]],
  ['started_375',['Started',['../tutorial_sa1.html#autotoc_md347',1,'Getting Started'],['../tutorial_superfx.html#autotoc_md418',1,'Getting Started'],['../group__examples.html#autotoc_md1817',1,'Getting Started']]],
  ['started_20with_20opensnes_376',['Getting Started with OpenSNES',['../getting_started.html',1,'index']]],
  ['state_377',['Player State',['../examples_input_two_players.html#autotoc_md1414',1,'']]],
  ['state_20changes_378',['Input and State Changes',['../tutorial_animation.html#autotoc_md80',1,'']]],
  ['state_20is_20not_20reset_20by_20consoleinit_379',['🟡 Mosaic state is not reset by &lt;span class=&quot;tt&quot;&gt;consoleInit&lt;/span&gt;',['../tutorial_mosaic.html#autotoc_md332',1,'']]],
  ['state_20machine_380',['State Machine',['../examples_input_superscope.html#autotoc_md1398',1,'6. State Machine'],['../snes_graphics_guide.html#autotoc_md658',1,'Animation State Machine']]],
  ['state_20machine_381',['2. State machine',['../examples_sprites_animated_sprite.html#autotoc_md1637',1,'']]],
  ['state_20machine_20summary_382',['State Machine Summary',['../tutorial_game_states.html#autotoc_md211',1,'']]],
  ['state_20machine_20under_20the_20hood_383',['The manual state machine (under the hood)',['../tutorial_game_states.html#autotoc_md199',1,'']]],
  ['state_20struct_384',['5. The Game State Struct',['../examples_scrolling_continuous_scroll.html#autotoc_md1588',1,'']]],
  ['state_20survives_20between_20scenes_385',['🟡 Window state survives between scenes',['../tutorial_window.html#autotoc_md450',1,'']]],
  ['state_20transitions_386',['State Transitions',['../tutorial_game_states.html#autotoc_md200',1,'']]],
  ['states_387',['States',['../tutorial_game_states.html#autotoc_md202',1,'VRAM Reload Between States'],['../tutorial_game_states.html#autotoc_md197',1,'What Are Game States?']]],
  ['states_20and_20sprite_20sheets_388',['Animated Sprite -- Direction States and Sprite Sheets',['../examples_sprites_animated_sprite.html',1,'examples_sprites']]],
  ['states_20tutorial_389',['Game States Tutorial',['../tutorial_game_states.html',1,'index']]],
  ['static_20colour_20gradient_20—_20examples_20hdma_20gradient_5fcolors_390',['Static colour gradient — &lt;span class=&quot;tt&quot;&gt;examples/hdma/gradient_colors&lt;/span&gt;',['../tutorial_hdma.html#autotoc_md233',1,'']]],
  ['static_20moving_20layers_391',['Mixed Scroll (Static + Moving Layers)',['../tutorial_scrolling.html#autotoc_md368',1,'']]],
  ['static_20shapes_20vs_20animated_20shapes_392',['Static shapes vs animated shapes',['../tutorial_window.html#autotoc_md437',1,'']]],
  ['static_20variables_20with_20initializers_393',['Static variables with initializers',['../troubleshooting.html#autotoc_md736',1,'']]],
  ['static_20vs_20dynamic_20sprites_394',['Static vs Dynamic Sprites',['../examples_sprites_dynamic_sprite.html#autotoc_md1665',1,'']]],
  ['stationary_20window_20—_20examples_20windows_20window_395',['Stationary window — &lt;span class=&quot;tt&quot;&gt;examples/windows/window&lt;/span&gt;',['../tutorial_hdma.html#autotoc_md236',1,'']]],
  ['status_396',['Status',['../registers.html#autotoc_md843',1,'$4210 - RDNMI (NMI Status)'],['../registers.html#autotoc_md844',1,'$4211 - TIMEUP (IRQ Status)'],['../registers.html#autotoc_md845',1,'$4212 - HVBJOY (Blank/Joypad Status)']]],
  ['status_397',['Roadmap status',['../examples_games_shmup_1942.html#autotoc_md1297',1,'']]],
  ['status_20codes_398',['Status Codes',['../examples_chips_sa1_hello.html#autotoc_md1129',1,'Status Codes'],['../examples_chips_superfx_hello.html#autotoc_md1144',1,'Status Codes']]],
  ['stay_20in_20force_20blank_399',['1. Initialize and Stay in Force Blank',['../examples_backgrounds_mode1_lz77.html#autotoc_md1029',1,'']]],
  ['steps_400',['Steps',['../examples.html#autotoc_md1570',1,'Level 1 &amp;ndash; First Steps'],['../tutorial_animation.html#autotoc_md95',1,'Next Steps'],['../tutorial_audio.html#autotoc_md112',1,'Next Steps'],['../tutorial_collision.html#autotoc_md137',1,'Next Steps'],['../tutorial_game_states.html#autotoc_md212',1,'Next Steps'],['../tutorial_graphics.html#autotoc_md224',1,'Next Steps'],['../tutorial_input.html#autotoc_md264',1,'Next Steps'],['../tutorial_scrolling.html#autotoc_md376',1,'Next Steps'],['../tutorial_sprites.html#autotoc_md394',1,'Next Steps']]],
  ['still_20for_401',['What Mesen2 is still for',['../tutorial_debugging.html#autotoc_md164',1,'']]],
  ['still_20missing_3a_20pow_20exp_20log_402',['What&apos;s still missing: &lt;span class=&quot;tt&quot;&gt;pow&lt;/span&gt;, &lt;span class=&quot;tt&quot;&gt;exp&lt;/span&gt;, &lt;span class=&quot;tt&quot;&gt;log&lt;/span&gt;',['../tutorial_math.html#autotoc_md297',1,'']]],
  ['stop_403',['2. NOP Padding Before STOP',['../tutorial_superfx.html#autotoc_md426',1,'']]],
  ['stopping_20movement_20slide_20along_20walls_404',['Stopping Movement (Slide Along Walls)',['../tutorial_collision.html#autotoc_md130',1,'']]],
  ['store_20pointers_20in_20sram_405',['🟠 Cannot store pointers in SRAM',['../tutorial_sram.html#autotoc_md410',1,'']]],
  ['story_406',['Why the envelope differs from the original (a true story)',['../examples_audio_pitch_mod.html#autotoc_md880',1,'']]],
  ['strange_407',['When the window register acts strange',['../tutorial_window.html#autotoc_md438',1,'']]],
  ['stream_20cannot_20be_20resynced_20—_20let_20the_20lib_20close_20it_408',['🟡 A Raster stream cannot be &quot;resynced&quot; — let the lib close it',['../tutorial_dsp1.html#autotoc_md194',1,'']]],
  ['stream_20it_409',['The level is bigger than VRAM — so stream it',['../craft_tiles_to_levels.html#autotoc_md498',1,'']]],
  ['streaming_410',['Map Engine Streaming',['../examples_maps_tiled.html#autotoc_md1478',1,'']]],
  ['streaming_411',['When HDMA isn&apos;t enough: H-timer IRQ streaming',['../tutorial_hdma.html#autotoc_md241',1,'']]],
  ['streaming_20for_20animated_20sprites_412',['Dynamic Sprite -- VRAM Streaming for Animated Sprites',['../examples_sprites_dynamic_sprite.html',1,'examples_sprites']]],
  ['streaming_20pattern_413',['The Streaming Pattern',['../tutorial_scrolling.html#autotoc_md373',1,'']]],
  ['streaming_20tips_414',['Streaming Tips',['../tutorial_scrolling.html#autotoc_md374',1,'']]],
  ['streaming_3a_20the_20column_20pipeline_415',['3. Streaming: The Column Pipeline',['../examples_games_likemario.html#autotoc_md1251',1,'']]],
  ['streams_20m16_20background_20wants_20q16_416',['🟡 &lt;span class=&quot;tt&quot;&gt;map&lt;/span&gt; streams &lt;span class=&quot;tt&quot;&gt;.m16&lt;/span&gt;; &lt;span class=&quot;tt&quot;&gt;background&lt;/span&gt; wants &lt;span class=&quot;tt&quot;&gt;.q16&lt;/span&gt;',['../tutorial_map.html#autotoc_md274',1,'']]],
  ['stretch_20without_20scaling_417',['Squash and stretch without scaling',['../craft_game_feel.html#autotoc_md481',1,'']]],
  ['stride_20to_20how_20the_20sheet_20was_20converted_418',['🟡 Match &lt;span class=&quot;tt&quot;&gt;base_tile&lt;/span&gt;/&lt;span class=&quot;tt&quot;&gt;stride&lt;/span&gt; to how the sheet was converted',['../tutorial_panel.html#autotoc_md342',1,'']]],
  ['string_419',['Print a string',['../examples_text_print_string.html',1,'examples_text']]],
  ['struct_420',['5. The Game State Struct',['../examples_scrolling_continuous_scroll.html#autotoc_md1588',1,'']]],
  ['struct_421',['The Scene struct',['../examples_basics_scene_stack.html#autotoc_md1109',1,'']]],
  ['struct_20—_20the_20tilemap_20is_20yours_422',['The &lt;span class=&quot;tt&quot;&gt;Panel&lt;/span&gt; struct — the tilemap is yours',['../tutorial_panel.html#autotoc_md336',1,'']]],
  ['struct_20pattern_20required_423',['Struct Pattern (Required)',['../examples_input_two_players.html#autotoc_md1415',1,'']]],
  ['structure_424',['Structure',['../examples_sprites_metasprite.html#autotoc_md1672',1,'MetaspriteItem Structure'],['../tutorial_sprites.html#autotoc_md378',1,'OAM Structure'],['../oam.html#autotoc_md780',1,'OAM Structure'],['../getting_started.html#autotoc_md557',1,'Project Structure'],['../examples_backgrounds_mode1_bg3_priority.html#autotoc_md1020',1,'Project Structure'],['../examples_backgrounds_mode1_lz77.html#autotoc_md1034',1,'Project Structure'],['../examples_games_mapandobjects.html#autotoc_md1282',1,'Project Structure'],['../examples_hdma_gradient_colors.html#autotoc_md1321',1,'Project Structure'],['../examples_input_mouse.html#autotoc_md1380',1,'Project Structure'],['../examples_maps_dynamic_map.html#autotoc_md1453',1,'Project Structure'],['../examples_maps_slope_collision.html#autotoc_md1473',1,'Project Structure'],['../examples_maps_tiled.html#autotoc_md1481',1,'Project Structure'],['../examples_memory_hirom_demo.html#autotoc_md1498',1,'Project Structure'],['../examples_memory_save_game.html#autotoc_md1520',1,'Project Structure'],['../examples_mode7_dsp1_ground.html#autotoc_md1527',1,'Project Structure'],['../examples_mode7_perspective.html#autotoc_md1541',1,'Project Structure'],['../examples_mode7_rotate_scale.html#autotoc_md1566',1,'Project Structure'],['../examples_scrolling_mixed_scroll.html#autotoc_md1613',1,'Project Structure'],['../examples_scrolling_parallax_scroll.html#autotoc_md1627',1,'Project Structure'],['../examples_sprites_animated_sprite.html#autotoc_md1644',1,'Project Structure'],['../examples_sprites_dynamic_sprite.html#autotoc_md1667',1,'Project Structure'],['../examples_sprites_metasprite.html#autotoc_md1676',1,'Project Structure'],['../examples_sprites_simple_sprite.html#autotoc_md1694',1,'Project Structure'],['../examples_sprites_sprite_sizes.html#autotoc_md1709',1,'Project Structure'],['../examples_transitions_mosaic.html#autotoc_md1780',1,'Project Structure'],['../examples_windows_transparent_window.html#autotoc_md1796',1,'Project Structure'],['../examples_windows_window.html#autotoc_md1810',1,'Project Structure'],['../snes_graphics_guide.html#autotoc_md646',1,'Tilemap Structure']]],
  ['structure_425',['1. Define a save structure',['../examples_memory_save_game.html#autotoc_md1510',1,'']]],
  ['structure_20544_20bytes_20total_426',['OAM Structure (544 bytes total)',['../snes_graphics_guide.html#autotoc_md651',1,'']]],
  ['structure_209_20bytes_427',['Block Structure (9 bytes)',['../snes_sound_guide.html#autotoc_md696',1,'']]],
  ['stx_20l_20—_20save_20x_20through_20a_428',['No &lt;span class=&quot;tt&quot;&gt;stx.l&lt;/span&gt; — Save X Through A',['../tutorial_sa1.html#autotoc_md358',1,'']]],
  ['style_20demo_429',['mode7_flying — a Pilotwings-style demo',['../examples_games_mode7_flying.html',1,'examples_games']]],
  ['style_20guide_430',['OpenSNES Code Style Guide',['../code_style.html',1,'index']]],
  ['style_20mini_20game_431',['mode7_racing — an F-Zero-style mini game',['../examples_games_mode7_racing.html',1,'examples_games']]],
  ['sub_20mean_20here_432',['What &quot;main&quot; and &quot;sub&quot; mean here',['../tutorial_colormath.html#autotoc_md139',1,'']]],
  ['sub_20screen_433',['Sub Screen',['../examples_color_transparency.html#autotoc_md1179',1,'Color Math: Main Screen + Sub Screen'],['../colormath_8h.html#autotoc_md19',1,'Main Screen vs Sub Screen']]],
  ['sub_20screen_20enable_434',['$212D - TS (Sub Screen Enable)',['../registers.html#autotoc_md837',1,'']]],
  ['sub_20screen_20only_20trap_435',['🔴 The &quot;BG2 is sub-screen-only&quot; trap',['../tutorial_colormath.html#autotoc_md148',1,'']]],
  ['submitting_20code_436',['Submitting Code',['../contributing.html#autotoc_md1830',1,'']]],
  ['suggesting_20features_437',['Suggesting Features',['../contributing.html#autotoc_md1829',1,'']]],
  ['summary_438',['State Machine Summary',['../tutorial_game_states.html#autotoc_md211',1,'']]],
  ['summary_439',['Cycle cost summary',['../tutorial_math.html#autotoc_md298',1,'']]],
  ['super_20mario_20kart_20floor_440',['DSP-1 Ground — the Super Mario Kart floor',['../examples_mode7_dsp1_ground.html',1,'examples_mode7']]],
  ['super_20mario_20kart_20floor_20via_20the_20dsp_201_20—_20examples_20mode7_20dsp1_5fground_441',['The Super Mario Kart floor via the DSP-1 — &lt;span class=&quot;tt&quot;&gt;examples/mode7/dsp1_ground&lt;/span&gt;',['../tutorial_mode7.html#autotoc_md310',1,'']]],
  ['super_20scope_442',['Super Scope',['../examples_input_superscope.html',1,'examples_input']]],
  ['superfree_20assets_20in_20any_20bank_20just_20work_443',['🟢 SUPERFREE assets in any bank just work',['../tutorial_dma.html#autotoc_md177',1,'']]],
  ['superfx_444',['What Is SuperFX?',['../tutorial_superfx.html#autotoc_md416',1,'']]],
  ['superfx_203d_20cube_445',['SuperFX 3D Cube',['../examples_chips_superfx_3d.html',1,'examples_chips']]],
  ['superfx_20assembly_20rules_446',['SuperFX Assembly Rules',['../tutorial_superfx.html#autotoc_md424',1,'']]],
  ['superfx_20cartridge_447',['SuperFX Cartridge',['../memory_map.html#autotoc_md778',1,'']]],
  ['superfx_20gsu_448',['SuperFX (GSU)',['../examples_by_category.html#autotoc_md617',1,'']]],
  ['superfx_20gsu_20registers_20_243000_20_24303f_449',['SuperFX / GSU Registers ($3000-$303F)',['../registers.html#autotoc_md870',1,'']]],
  ['superfx_20gsu_20tutorial_450',['SuperFX (GSU) Tutorial',['../tutorial_superfx.html',1,'index']]],
  ['superfx_20hello_451',['SuperFX Hello',['../examples_chips_superfx_hello.html',1,'examples_chips']]],
  ['superfx_20in_20your_20makefile_452',['1. Enable SuperFX in Your Makefile',['../tutorial_superfx.html#autotoc_md419',1,'']]],
  ['support_453',['Multitap Support',['../examples_input_two_players.html#autotoc_md1440',1,'']]],
  ['surfaced_454',['surfaced',['../examples_mode7_perspective_rotate.html#autotoc_md1547',1,'Two integration lessons this port surfaced'],['../examples_color_hicolor_1792.html#autotoc_md1156',1,'Two SDK bugs this port surfaced']]],
  ['survives_20a_20dialog_20box_455',['panel_hud — a HUD that survives a dialog box',['../examples_basics_panel_hud.html',1,'examples_basics']]],
  ['survives_20between_20scenes_456',['🟡 Window state survives between scenes',['../tutorial_window.html#autotoc_md450',1,'']]],
  ['swap_20tilemap_20entries_457',['Approach 1: Swap Tilemap Entries',['../tutorial_animation.html#autotoc_md90',1,'']]],
  ['swapping_20apu_20programs_458',['Hot-swapping APU programs',['../tutorial_audio.html#autotoc_md115',1,'']]],
  ['swapping_20apu_20programs_20at_20runtime_459',['apu_switch — hot-swapping APU programs at runtime',['../examples_audio_apu_switch.html',1,'examples_audio']]],
  ['swarm_20and_20the_20oam_20throughput_20ceiling_460',['sprite_swarm — a bouncing swarm, and the OAM throughput ceiling',['../examples_sprites_sprite_swarm.html',1,'examples_sprites']]],
  ['switch_461',['Why a framework instead of a switch',['../examples_basics_scene_stack.html#autotoc_md1111',1,'']]],
  ['switching_20layers_462',['Switching Layers',['../examples_windows_window.html#autotoc_md1805',1,'']]],
  ['switching_20mid_20frame_463',['Mode Switching Mid-Frame',['../examples_mode7_perspective.html#autotoc_md1538',1,'']]],
  ['symbols_464',['Working with symbols',['../tutorial_debugging.html#autotoc_md157',1,'']]],
  ['sync_465',['4. Main Loop: Update, Draw, Sync',['../examples_games_mapandobjects.html#autotoc_md1280',1,'']]],
  ['sync_20producer_20consumer_466',['Pattern 1: Flag Sync (Producer/Consumer)',['../tutorial_sa1.html#autotoc_md352',1,'']]],
  ['system_467',['System',['../examples_games_mapandobjects.html#autotoc_md1277',1,'1. Initialize the Map and Sprite System'],['../snes_sound_guide.html#autotoc_md706',1,'Echo System'],['../examples_backgrounds_mode1_bg3_priority.html#autotoc_md1016',1,'Mode 1 Priority System'],['../examples_windows_window.html#autotoc_md1801',1,'SNES Window System']]],
  ['system_468',['Coordinate system',['../tutorial_mode7.html#autotoc_md304',1,'']]],
  ['system_20bg1_469',['2. Text System (BG1)',['../examples_input_superscope.html#autotoc_md1394',1,'']]],
  ['systems_470',['Memory Systems',['../snes_graphics_guide.html#autotoc_md640',1,'']]]
];
