var searchData=
[
  ['y_201_20scanline_20quirk_0',['Sprite Y +1 Scanline Quirk',['../oam.html#autotoc_md646',1,'']]],
  ['you_20don_20t_20have_20to_20think_20about_20it_1',['🟠 Endianness — but you don&apos;t have to think about it',['../tutorial_sram.html#autotoc_md371',1,'']]],
  ['you_20haven_20t_20configured_2',['🟡 Don&apos;t enable channels you haven&apos;t configured',['../tutorial_hdma.html#autotoc_md231',1,'']]],
  ['you_20ll_20learn_3',['You ll Learn',['../examples_audio_snesmod_music_hirom.html#autotoc_md792',1,'What You&apos;ll Learn'],['../examples_audio_snesmod_music_large.html#autotoc_md796',1,'What You&apos;ll Learn'],['../examples_audio_snesmod_sfx.html#autotoc_md801',1,'What You&apos;ll Learn'],['../examples_basics_collision_demo.html#autotoc_md826',1,'What You&apos;ll Learn'],['../examples_basics_random.html#autotoc_md844',1,'What You&apos;ll Learn'],['../examples_basics_scene_stack.html#autotoc_md854',1,'What You&apos;ll Learn'],['../examples_basics_timer.html#autotoc_md862',1,'What You&apos;ll Learn'],['../examples_games_breakout.html#autotoc_md871',1,'What You&apos;ll Learn'],['../examples_games_likemario.html#autotoc_md899',1,'What You&apos;ll Learn'],['../examples_games_mapandobjects.html#autotoc_md923',1,'What You&apos;ll Learn'],['../examples_graphics_backgrounds_continuous_scroll.html#autotoc_md964',1,'What You&apos;ll Learn'],['../examples_graphics_backgrounds_mixed_scroll.html#autotoc_md984',1,'What You&apos;ll Learn'],['../examples_graphics_backgrounds_mode1_lz77.html#autotoc_md1052',1,'What You&apos;ll Learn'],['../examples_graphics_effects_hdma_wave.html#autotoc_md1176',1,'What You&apos;ll Learn'],['../examples_graphics_effects_superfx_3d.html#autotoc_md1261',1,'What You&apos;ll Learn'],['../examples_graphics_effects_transparency.html#autotoc_md1267',1,'What You&apos;ll Learn'],['../examples_graphics_sprites_dynamic_metasprite.html#autotoc_md1332',1,'What You&apos;ll Learn'],['../examples_graphics_sprites_metasprite.html#autotoc_md1350',1,'What You&apos;ll Learn'],['../examples_input_controller.html#autotoc_md1396',1,'What You&apos;ll Learn'],['../examples_input_mouse.html#autotoc_md1404',1,'What You&apos;ll Learn'],['../examples_input_superscope.html#autotoc_md1426',1,'What You&apos;ll Learn'],['../examples_maps_dynamic_map.html#autotoc_md1480',1,'What You&apos;ll Learn'],['../examples_maps_mapscroll.html#autotoc_md1490',1,'What You&apos;ll Learn'],['../examples_maps_slopemario.html#autotoc_md1507',1,'What You&apos;ll Learn'],['../examples_maps_tiled.html#autotoc_md1517',1,'What You&apos;ll Learn'],['../examples_memory_sa1_hello.html#autotoc_md1548',1,'What You&apos;ll Learn'],['../examples_memory_sa1_starfield.html#autotoc_md1552',1,'What You&apos;ll Learn'],['../examples_memory_superfx_hello.html#autotoc_md1574',1,'What You&apos;ll Learn'],['../examples_text_hello_world.html#autotoc_md1590',1,'What You&apos;ll Learn'],['../examples_text_text_test.html#autotoc_md1619',1,'What You&apos;ll Learn']]],
  ['you_20see_4',['Understanding what you see',['../examples_graphics_effects_hires_text.html#autotoc_md1211',1,'']]],
  ['your_20first_20oam_20sprite_5',['Simple Sprite -- Your First OAM Sprite',['../examples_graphics_sprites_simple_sprite.html',1,'examples_graphics_sprites']]],
  ['your_20first_20rom_6',['A4. Run Your First ROM',['../getting_started.html#autotoc_md421',1,'']]],
  ['your_20game_7',['Test Your Game',['../getting_started.html#autotoc_md425',1,'']]],
  ['your_20makefile_8',['Your Makefile',['../tutorial_sa1.html#autotoc_md309',1,'1. Enable SA-1 in Your Makefile'],['../tutorial_superfx.html#autotoc_md379',1,'1. Enable SuperFX in Your Makefile']]],
  ['your_20own_20level_9',['Making Your Own Level',['../examples_maps_tiled.html#autotoc_md1526',1,'']]],
  ['your_20own_20project_10',['A5. Create Your Own Project',['../getting_started.html#autotoc_md422',1,'']]],
  ['your_20path_11',['Choose Your Path',['../getting_started.html#autotoc_md415',1,'']]],
  ['your_20sa_201_20boot_20code_12',['2. Write Your SA-1 Boot Code',['../tutorial_sa1.html#autotoc_md310',1,'']]]
];
