var searchData=
[
  ['d_20pad_20controlled_20scrolling_0',['D-PAD Controlled Scrolling',['../tutorial_scrolling.html#d-pad-controlled-scrolling',1,'']]],
  ['dasxl_20h_20transfer_20size_1',['$43x5-$43x6 - DASxL/H (Transfer Size)',['../registers.html#autotoc_md43x5-43x6---dasxlh-transfer-size',1,'']]],
  ['data_2',['Data',['../examples_games_mapandobjects.html#autotoc_md3-load-objects-from-map-data',1,'3. Load Objects from Map Data'],['../tutorial_collision.html#reading-tilemap-data',1,'Reading Tilemap Data']]],
  ['data_3',['tmx2snes — Tiled levels to SNES map data',['../tools_tmx2snes.html',1,'tools']]],
  ['data_20address_4',['$210B-$210C - BG12NBA/BG34NBA (Tile Data Address)',['../registers.html#autotoc_md210b-210c---bg12nbabg34nba-tile-data-address',1,'']]],
  ['data_20around_5',['Moving data around',['../api_index.html#moving-data-around',1,'']]],
  ['data_20format_20example_6',['Data Format Example',['../snes_graphics_guide.html#data-format-example',1,'']]],
  ['data_20is_20far_20and_20casting_20const_20away_20breaks_20it_7',['Trap 5: const data is far, and casting &lt;span class=&quot;tt&quot;&gt;const&lt;/span&gt; away breaks it',['../migrating_pvsneslib.html#trap-5-const-data-is-far-and-casting-const-away-breaks-it',1,'']]],
  ['data_20lives_8',['Where the Data Lives',['../examples_hdma_hdma_wave.html#where-the-data-lives',1,'']]],
  ['data_20lives_20in_20the_20asset_20banks_20since_20127_203_9',['🟢 Bank $00 ROM: code only — C const data lives in the asset banks (since #127.3)',['../KNOWN_LIMITATIONS.html#autotoc_md-bank-00-rom-code-only--c-const-data-lives-in-the-asset-banks-since-1273',1,'']]],
  ['data_20placement_10',['Data Placement',['../examples_games_likemario.html#data-placement',1,'']]],
  ['data_20port_20–_20is_20not_20safe_20in_20nmi_11',['🟡 WRAM data port &lt;span class=&quot;tt&quot;&gt;$2180&lt;/span&gt;–&lt;span class=&quot;tt&quot;&gt;$2183&lt;/span&gt; is NOT safe in NMI',['../tutorial_dma.html#autotoc_md-wram-data-port-21802183-is-not-safe-in-nmi',1,'']]],
  ['data_20port_20race_20in_20nmi_20caught_20at_20build_20time_12',['🟢 WRAM data port &lt;span class=&quot;tt&quot;&gt;$2180–$2183&lt;/span&gt; race in NMI (caught at build time)',['../KNOWN_LIMITATIONS.html#autotoc_md-wram-data-port-21802183-race-in-nmi-caught-at-build-time',1,'']]],
  ['data_20shape_20not_20by_20register_13',['🟡 Repeat vs non-repeat on &lt;span class=&quot;tt&quot;&gt;WH0&lt;/span&gt;/&lt;span class=&quot;tt&quot;&gt;WH1&lt;/span&gt; — pick by data shape, not by register',['../tutorial_window.html#autotoc_md-repeat-vs-non-repeat-on-wh0wh1--pick-by-data-shape-not-by-register',1,'']]],
  ['data_20write_14',['Data Write',['../registers.html#autotoc_md2104---oamdata-oam-data-write',1,'$2104 - OAMDATA (OAM Data Write)'],['../registers.html#autotoc_md2118-2119---vmdatalh-vram-data-write',1,'$2118-$2119 - VMDATAL/H (VRAM Data Write)'],['../registers.html#autotoc_md2122---cgdata-cgram-data-write',1,'$2122 - CGDATA (CGRAM Data Write)']]],
  ['data_5finit_5fend_20o_20must_20be_20linked_20last_20enforced_15',['🟢 &lt;span class=&quot;tt&quot;&gt;data_init_end.o&lt;/span&gt; MUST be linked last (enforced)',['../KNOWN_LIMITATIONS.html#autotoc_md-data_init_endo-must-be-linked-last-enforced',1,'']]],
  ['deadzone_20it_16',['Don&apos;t glue the camera to the player — deadzone it',['../craft_camera.html#dont-glue-the-camera-to-the-player--deadzone-it',1,'']]],
  ['debug_20tooling_20that_20cracked_20it_17',['Debug tooling that cracked it',['../examples_audio_speech_synth.html#debug-tooling-that-cracked-it',1,'']]],
  ['debugger_20alternative_18',['Using Mesen Debugger (alternative)',['../troubleshooting.html#using-mesen-debugger-alternative',1,'']]],
  ['debugging_19',['Debugging',['../tutorial_far_ram.html#debugging',1,'']]],
  ['debugging_20archaeology_20all_20owner_20listening_20test_20driven_20',['The debugging archaeology (all owner-listening-test driven)',['../examples_audio_speech_synth.html#the-debugging-archaeology-all-owner-listening-test-driven',1,'']]],
  ['debugging_20audio_3a_20luna_20s_20spc_20dump_21',['Debugging audio: luna&apos;s spc-dump',['../tutorial_audio.html#debugging-audio-lunas-spc-dump',1,'']]],
  ['debugging_20in_20mesen2_22',['Debugging in Mesen2',['../tutorial_sa1.html#debugging-in-mesen2',1,'']]],
  ['debugging_20shadow_20buffer_20vs_20hardware_23',['Recipe 4 — Sprite/OAM debugging (shadow buffer vs hardware)',['../tutorial_debugging.html#recipe-4--spriteoam-debugging-shadow-buffer-vs-hardware',1,'']]],
  ['debugging_20with_20luna_24',['Interactive Debugging with luna',['../tutorial_debugging.html',1,'index']]],
  ['debugging_20with_20luna_25',['Interactive debugging with luna',['../troubleshooting.html#interactive-debugging-with-luna',1,'']]],
  ['decide_20everything_3a_20u_20and_20s_26',['The two flags that decide everything: &lt;span class=&quot;tt&quot;&gt;-u&lt;/span&gt; and &lt;span class=&quot;tt&quot;&gt;-s&lt;/span&gt;',['../tools_gfx4snes.html#the-two-flags-that-decide-everything--u-and--s',1,'']]],
  ['decompress_20tiles_20to_20vram_27',['2. Decompress Tiles to VRAM',['../examples_backgrounds_mode1_lz77.html#autotoc_md2-decompress-tiles-to-vram',1,'']]],
  ['deeper_20—_20the_20curated_20shelf_28',['Go deeper — the curated shelf',['../craft.html#go-deeper--the-curated-shelf',1,'']]],
  ['default_29',['LoROM Memory Map (Default)',['../memory_map.html#lorom-memory-map-default',1,'']]],
  ['default_20is_20the_20tilemap_20centre_20not_20the_20screen_20centre_30',['🟡 Centre default is the tilemap centre, not the screen centre',['../tutorial_mode7.html#autotoc_md-centre-default-is-the-tilemap-centre-not-the-screen-centre',1,'']]],
  ['define_20a_20save_20structure_31',['1. Define a save structure',['../examples_memory_save_game.html#autotoc_md1-define-a-save-structure',1,'']]],
  ['defined_20or_20no_20rule_20to_20make_20target_20common_20mk_32',['&quot;OPENSNES not defined&quot; or &quot;No rule to make target &apos;common.mk&apos;&quot;',['../troubleshooting.html#opensnes-not-defined-or-no-rule-to-make-target-commonmk',1,'']]],
  ['delay_20slot_33',['1. NOP After Every Branch (Delay Slot)',['../tutorial_superfx.html#autotoc_md1-nop-after-every-branch-delay-slot',1,'']]],
  ['delete_20save_34',['&quot;Delete save&quot;',['../tutorial_sram.html#delete-save',1,'']]],
  ['deliberate_20overlap_35',['2. The VRAM Map — A Deliberate Overlap',['../examples_games_breakout.html#autotoc_md2-the-vram-map--a-deliberate-overlap',1,'']]],
  ['demo_36',['Demo',['../examples_basics_collision_demo.html',1,'Collision Detection Demo'],['../examples_hdma_hdma_helpers.html',1,'HDMA Helpers Demo']]],
  ['demo_37',['mode7_flying — a Pilotwings-style demo',['../examples_games_mode7_flying.html',1,'examples_games']]],
  ['demo_20understanding_20snes_20memory_20mapping_38',['HiROM Demo -- Understanding SNES Memory Mapping',['../examples_memory_hirom_demo.html',1,'examples_memory']]],
  ['demonstrate_39',['What These Demonstrate',['../examples_games.html#what-these-demonstrate',1,'']]],
  ['demonstrates_40',['What this example demonstrates',['../basics_2fix32__orbit_2main_8c.html#what-this-example-demonstrates',1,'']]],
  ['depends_20on_20palette_41',['🟡 OBJ math depends on palette',['../tutorial_colormath.html#autotoc_md-obj-math-depends-on-palette',1,'']]],
  ['depth_42',['7. Drop Shadows (Free Depth)',['../examples_games_breakout.html#autotoc_md7-drop-shadows-free-depth',1,'']]],
  ['depth_20from_20motion_43',['Parallax — depth from motion',['../craft_backgrounds.html#parallax--depth-from-motion',1,'']]],
  ['depth_20is_20priority_20not_20layer_20order_44',['Depth is priority, not layer order',['../craft_backgrounds.html#depth-is-priority-not-layer-order',1,'']]],
  ['description_45',['Description',['../examples_backgrounds_mode0.html#description',1,'Description'],['../examples_backgrounds_mode3.html#description-1',1,'Description'],['../examples_backgrounds_mode5.html#description-2',1,'Description']]],
  ['design_20in_20tiled_20convert_20for_20the_20snes_46',['The workflow: design in Tiled, convert for the SNES',['../craft_tiles_to_levels.html#the-workflow-design-in-tiled-convert-for-the-snes',1,'']]],
  ['design_20rules_47',['Pause Design Rules',['../tutorial_game_states.html#pause-design-rules',1,'']]],
  ['designing_20the_20level_20not_20just_20building_20it_48',['Designing the level, not just building it',['../craft_tiles_to_levels.html#designing-the-level-not-just-building-it',1,'']]],
  ['despawn_20fix_20s5_202_49',['Bullet despawn fix (S5.2)',['../examples_games_shmup_1942.html#bullet-despawn-fix-s52',1,'']]],
  ['desync_50',['Recipe 6 — Temporal artefacts (flicker, page-flip desync)',['../tutorial_debugging.html#recipe-6--temporal-artefacts-flicker-page-flip-desync',1,'']]],
  ['detect_20mouse_51',['1. Initialize Text and Detect Mouse',['../examples_input_mouse.html#autotoc_md1-initialize-text-and-detect-mouse',1,'']]],
  ['detection_52',['Detection',['../examples_input_two_players.html#controller-detection',1,'Controller Detection'],['../tutorial_input.html#edge-detection',1,'Edge Detection']]],
  ['detection_20demo_53',['Collision Detection Demo',['../examples_basics_collision_demo.html',1,'examples_basics']]],
  ['detection_20tutorial_54',['Collision Detection Tutorial',['../tutorial_collision.html',1,'index']]],
  ['developer_55',['Developer',['../getting_started.html#path-a-game-developer',1,'Path A: Game Developer'],['../getting_started.html#path-b-sdk-developer',1,'Path B: SDK Developer']]],
  ['development_56',['Learn SNES Development',['../learning_path.html',1,'index']]],
  ['development_20workflow_57',['B4. Development Workflow',['../getting_started.html#b4-development-workflow',1,'']]],
  ['diagnostic_20commands_58',['Diagnostic Commands',['../troubleshooting.html#diagnostic-commands',1,'']]],
  ['dialog_20box_59',['dialog box',['../examples_basics_panel_hud.html',1,'panel_hud — a HUD that survives a dialog box'],['../tutorial_panel.html#the-minimum-viable-dialog-box',1,'The minimum viable dialog box']]],
  ['dies_20→_20silent_20corruption_60',['🔴 Battery dies → silent corruption',['../tutorial_sram.html#autotoc_md-battery-dies--silent-corruption',1,'']]],
  ['diff_61',['&lt;span class=&quot;tt&quot;&gt;luna diff&lt;/span&gt;',['../tools_luna.html#luna-diff',1,'']]],
  ['different_20in_20one_20table_62',['What is different, in one table',['../migrating_pvsneslib.html#what-is-different-in-one-table',1,'']]],
  ['different_20layer_20above_20the_20panel_63',['🟡 Text goes on a &lt;em&gt;different&lt;/em&gt; layer, above the panel',['../tutorial_panel.html#autotoc_md-text-goes-on-a-different-layer-above-the-panel',1,'']]],
  ['different_20rules_64',['Vertical wants different rules',['../craft_camera.html#vertical-wants-different-rules',1,'']]],
  ['different_20speeds_65',['Exercise 2: Different Speeds',['../examples_input_two_players.html#exercise-2-different-speeds',1,'']]],
  ['differentiation_66',['Player Differentiation',['../examples_input_two_players.html#player-differentiation',1,'']]],
  ['differs_20from_20the_20original_20a_20true_20story_67',['Why the envelope differs from the original (a true story)',['../examples_audio_pitch_mod.html#why-the-envelope-differs-from-the-original-a-true-story',1,'']]],
  ['direct_20oam_20setup_68',['5. Direct OAM Setup',['../examples_input_superscope.html#autotoc_md5-direct-oam-setup',1,'']]],
  ['direct_20oammemory_20writes_69',['Direct oamMemory[] Writes',['../examples_basics_collision_demo.html#direct-oammemory-writes',1,'']]],
  ['direct_20register_20access_20recommended_70',['Direct Register Access (Recommended)',['../tutorial_input.html#direct-register-access-recommended',1,'']]],
  ['direct_5fcolor_20—_20the_20pixel_20byte_20is_20the_20color_71',['direct_color — the pixel byte IS the color',['../examples_color_direct_color.html',1,'examples_color']]],
  ['direction_20and_20source_20addressing_72',['Direction and source addressing',['../tutorial_dma.html#direction-and-source-addressing',1,'']]],
  ['direction_20based_20animation_73',['Direction-Based Animation',['../tutorial_animation.html#direction-based-animation',1,'']]],
  ['direction_20states_20and_20sprite_20sheets_74',['Animated Sprite -- Direction States and Sprite Sheets',['../examples_sprites_animated_sprite.html',1,'examples_sprites']]],
  ['directional_20wipe_75',['Exercise 2: Directional Wipe',['../examples_transitions_fading.html#exercise-2-directional-wipe',1,'']]],
  ['directly_76',['3. Set Up OAM Directly',['../examples_input_mouse.html#autotoc_md3-set-up-oam-directly',1,'']]],
  ['directories_20or_20cc65816_20not_20found_77',['Empty &lt;span class=&quot;tt&quot;&gt;compiler/&lt;/span&gt; directories or &quot;cc65816 not found&quot;',['../troubleshooting.html#empty-compiler-directories-or-cc65816-not-found',1,'']]],
  ['directory_78',['Sample Directory',['../snes_sound_guide.html#sample-directory',1,'']]],
  ['dirty_20flags_79',['3. Scroll Updates via bgSetScroll Dirty Flags',['../examples_scrolling_continuous_scroll.html#autotoc_md3-scroll-updates-via-bgsetscroll-dirty-flags',1,'']]],
  ['disabled_80',['GAIN Modes (when ADSR disabled)',['../snes_sound_guide.html#gain-modes-when-adsr-disabled',1,'']]],
  ['discipline_20matters_81',['🟡 Repeat-mode discipline matters',['../tutorial_hdma.html#autotoc_md-repeat-mode-discipline-matters',1,'']]],
  ['disconnected_20controller_82',['Disconnected Controller',['../examples_input_two_players.html#disconnected-controller',1,'']]],
  ['display_83',['Display',['../examples_backgrounds_mode1.html#autotoc_md3-enable-display',1,'3. Enable Display'],['../examples_backgrounds_mode1_lz77.html#autotoc_md4-configure-bg1-and-enable-display',1,'4. Configure BG1 and Enable Display'],['../tutorial_graphics.html#initialize-display',1,'Initialize Display'],['../examples_audio_snesmod_sfx.html#text-display',1,'Text Display']]],
  ['display_84',['display',['../examples_sprites_simple_sprite.html#autotoc_md5-enable-display',1,'5. Enable display'],['../examples_memory_save_game.html#autotoc_md5-text-display',1,'5. Text display']]],
  ['display_20control_85',['Display Control',['../registers.html#autotoc_md2100---inidisp-display-control',1,'$2100 - INIDISP (Display Control)'],['../registers.html#display-control',1,'Display Control']]],
  ['dissolves_86',['Punctuate scene changes — fades and dissolves',['../craft_game_feel.html#punctuate-scene-changes--fades-and-dissolves',1,'']]],
  ['distance_20and_20range_3a_20the_20game_20logic_20commands_87',['Distance and Range: the game-logic commands',['../tutorial_dsp1.html#distance-and-range-the-game-logic-commands',1,'']]],
  ['distortion_20—_20examples_20hdma_20hdma_5fwave_88',['Per-scanline wave distortion — &lt;span class=&quot;tt&quot;&gt;examples/hdma/hdma_wave&lt;/span&gt;',['../tutorial_hdma.html#per-scanline-wave-distortion--exampleshdmahdma_wave',1,'']]],
  ['dithered_20backdrop_89',['&quot;9-bit&quot; gradient — brightness-dithered backdrop',['../examples_color_gradient_9bit.html',1,'examples_color']]],
  ['divide_90',['$4204-$4206 - WRDIV (Divide)',['../registers.html#autotoc_md4204-4206---wrdiv-divide',1,'']]],
  ['divide_20by_20zero_91',['🟠 &lt;span class=&quot;tt&quot;&gt;fixDiv&lt;/span&gt; returns 0 on divide-by-zero',['../tutorial_math.html#autotoc_md-fixdiv-returns-0-on-divide-by-zero',1,'']]],
  ['divider_92',['Hardware multiplier and divider',['../tutorial_math.html#hardware-multiplier-and-divider',1,'']]],
  ['dma_93',['DMA',['../tutorial_hdma.html#autotoc_md-channel-7-is-reserved-for-oam-dma',1,'🔴 Channel 7 is reserved for OAM DMA'],['../examples_sprites_sprite_sizes.html#force-blank-for-large-dma',1,'Force Blank for Large DMA']]],
  ['dma_20actually_20is_94',['What DMA actually is',['../tutorial_dma.html#what-dma-actually-is',1,'']]],
  ['dma_20budget_20is_204_20kb_20per_20frame_95',['DMA budget is 4 KB per frame',['../tutorial_dma.html#autotoc_md-vblank-dma-budget-is-4-kb-per-frame',1,'🔴 VBlank DMA budget is ~4 KB per frame'],['../KNOWN_LIMITATIONS.html#autotoc_md-vblank-dma-budget-is-4-kb-per-frame-1',1,'🔴 VBlank DMA budget is ~4 KB per frame']]],
  ['dma_20budget_3a_204_20kb_96',['The VBlank DMA budget: ~4 KB',['../craft_frame_budget.html#the-vblank-dma-budget-4-kb',1,'']]],
  ['dma_20channels_97',['The DMA channels',['../tutorial_dma.html#the-dma-channels',1,'']]],
  ['dma_20control_98',['DMA Control',['../registers.html#dma-control',1,'']]],
  ['dma_20enable_99',['$420B - MDMAEN (General DMA Enable)',['../registers.html#autotoc_md420b---mdmaen-general-dma-enable',1,'']]],
  ['dma_20example_100',['DMA Example',['../registers.html#dma-example',1,'']]],
  ['dma_20in_20the_20main_20loop_101',['Per-frame DMA in the main loop',['../tutorial_dma.html#per-frame-dma-in-the-main-loop',1,'']]],
  ['dma_20is_20automated_20don_20t_20double_20up_102',['🟠 OAM DMA is automated, don&apos;t double-up',['../tutorial_dma.html#autotoc_md-oam-dma-is-automated-dont-double-up',1,'']]],
  ['dma_20loader_103',['Assembly DMA Loader',['../examples_color_transparency.html#assembly-dma-loader',1,'']]],
  ['dma_20overview_104',['DMA Overview',['../dma_8h.html#dma-overview',1,'']]],
  ['dma_20parameters_105',['$43x0 - DMAPx (DMA Parameters)',['../registers.html#autotoc_md43x0---dmapx-dma-parameters',1,'']]],
  ['dma_20pattern_106',['1-Page-Per-VBlank DMA Pattern',['../examples_maps_dynamic_map.html#autotoc_md1-page-per-vblank-dma-pattern',1,'']]],
  ['dma_20registers_20_244300_20_24437f_107',['DMA Registers ($4300-$437F)',['../registers.html#dma-registers-4300-437f',1,'']]],
  ['dma_20registers_20_2443x0_20_2443xf_108',['DMA Registers ($43x0-$43xF)',['../memory_map.html#dma-registers-43x0-43xf',1,'']]],
  ['dma_20registers_20for_20fast_20transfers_109',['DMA Registers (for fast transfers)',['../snes_graphics_guide.html#dma-registers-for-fast-transfers',1,'']]],
  ['dma_20tutorial_110',['DMA Tutorial',['../tutorial_dma.html',1,'index']]],
  ['dma_20vs_20hdma_111',['DMA vs HDMA',['../tutorial_dma.html#dma-vs-hdma',1,'']]],
  ['dmacopyvram_112',['🟡 Mode 7 needs &lt;span class=&quot;tt&quot;&gt;dmaCopyVramMode7&lt;/span&gt;, not &lt;span class=&quot;tt&quot;&gt;dmaCopyVram&lt;/span&gt;',['../tutorial_dma.html#autotoc_md-mode-7-needs-dmacopyvrammode7-not-dmacopyvram',1,'']]],
  ['dmacopyvrammode7_20does_20the_20two_20passes_113',['🟢 Interleaved VRAM: &lt;span class=&quot;tt&quot;&gt;dmaCopyVramMode7&lt;/span&gt; does the two passes',['../tutorial_mode7.html#autotoc_md-interleaved-vram-dmacopyvrammode7-does-the-two-passes',1,'']]],
  ['dmacopyvrammode7_20not_20dmacopyvram_114',['🟡 Mode 7 needs &lt;span class=&quot;tt&quot;&gt;dmaCopyVramMode7&lt;/span&gt;, not &lt;span class=&quot;tt&quot;&gt;dmaCopyVram&lt;/span&gt;',['../tutorial_dma.html#autotoc_md-mode-7-needs-dmacopyvrammode7-not-dmacopyvram',1,'']]],
  ['dmapx_20dma_20parameters_115',['$43x0 - DMAPx (DMA Parameters)',['../registers.html#autotoc_md43x0---dmapx-dma-parameters',1,'']]],
  ['do_116',['What SA-1 Can&apos;t Do',['../tutorial_sa1.html#what-sa-1-cant-do',1,'']]],
  ['do_117',['do',['../api_index.html',1,'API index — by what you are trying to do'],['../tutorial_mode7.html#the-lib-helpers-and-what-they-do',1,'The lib helpers and what they do']]],
  ['do_20i_20need_118',['Which API do I need?',['../getting_started.html#which-api-do-i-need',1,'']]],
  ['do_20it_20yourself_20with_20setbrightness_200_119',['🔴 &lt;span class=&quot;tt&quot;&gt;panelFlush&lt;/span&gt; uploads under forced blank — do not do it yourself with &lt;span class=&quot;tt&quot;&gt;setBrightness(0)&lt;/span&gt;',['../tutorial_panel.html#autotoc_md-panelflush-uploads-under-forced-blank--do-not-do-it-yourself-with-setbrightness0',1,'']]],
  ['do_20not_20do_20it_20yourself_20with_20setbrightness_200_120',['🔴 &lt;span class=&quot;tt&quot;&gt;panelFlush&lt;/span&gt; uploads under forced blank — do not do it yourself with &lt;span class=&quot;tt&quot;&gt;setBrightness(0)&lt;/span&gt;',['../tutorial_panel.html#autotoc_md-panelflush-uploads-under-forced-blank--do-not-do-it-yourself-with-setbrightness0',1,'']]],
  ['docs_121',['Where they fit with the rest of the docs',['../tools.html#where-they-fit-with-the-rest-of-the-docs',1,'']]],
  ['documentation_122',['Documentation',['../snes_graphics_guide.html#documentation',1,'Documentation'],['../snes_sound_guide.html#documentation-1',1,'Documentation'],['../contributing.html#documentation-2',1,'Documentation'],['../code_style.html#function-documentation',1,'Function Documentation'],['../index.html',1,'OpenSNES Documentation'],['../code_style.html#register-documentation',1,'Register Documentation']]],
  ['does_123',['Does',['../examples_audio_snesmod_music.html#what-this-example-does',1,'What This Example Does'],['../examples_backgrounds_mode1.html#what-this-example-does-1',1,'What This Example Does'],['../examples_input_two_players.html#what-this-example-does-2',1,'What This Example Does'],['../examples_transitions_fading.html#what-this-example-does-3',1,'What This Example Does']]],
  ['does_124',['does',['../tutorial_dsp1.html#the-3d-pipeline-what-dsp1_cube-does',1,'The 3D pipeline (what dsp1_cube does)'],['../tutorial_dsp1.html#the-ground-what-dsp1_ground-does',1,'The ground (what dsp1_ground does)']]],
  ['does_20my_20setup_20even_20work_125',['Stage 0 — &quot;Does my setup even work?&quot;',['../learning_path.html#stage-0--does-my-setup-even-work',1,'']]],
  ['does_20not_126',['🟠 &lt;span class=&quot;tt&quot;&gt;mapVblank()&lt;/span&gt; belongs in VBlank, &lt;span class=&quot;tt&quot;&gt;mapUpdate()&lt;/span&gt; does not',['../tutorial_map.html#autotoc_md-mapvblank-belongs-in-vblank-mapupdate-does-not',1,'']]],
  ['does_20not_20affect_20obj_20sprites_127',['🟠 Mosaic does not affect OBJ (sprites)',['../tutorial_mosaic.html#autotoc_md-mosaic-does-not-affect-obj-sprites',1,'']]],
  ['does_20not_20propagate_20the_20high_20half_20through_20the_20call_128',['🟡 C function returning &lt;span class=&quot;tt&quot;&gt;long&lt;/span&gt; does not propagate the high half through the call',['../KNOWN_LIMITATIONS.html#autotoc_md-c-function-returning-long-does-not-propagate-the-high-half-through-the-call',1,'']]],
  ['does_20nothing_129',['When something silently does nothing',['../api_index.html#when-something-silently-does-nothing',1,'']]],
  ['does_20the_20two_20passes_130',['🟢 Interleaved VRAM: &lt;span class=&quot;tt&quot;&gt;dmaCopyVramMode7&lt;/span&gt; does the two passes',['../tutorial_mode7.html#autotoc_md-interleaved-vram-dmacopyvrammode7-does-the-two-passes',1,'']]],
  ['domain_131',['Free Asset Sources (CC0/Public Domain)',['../snes_graphics_guide.html#free-asset-sources-cc0public-domain',1,'']]],
  ['don_20t_20appear_132',['Sprites don&apos;t appear',['../troubleshooting.html#sprites-dont-appear',1,'']]],
  ['don_20t_20double_20up_133',['🟠 OAM DMA is automated, don&apos;t double-up',['../tutorial_dma.html#autotoc_md-oam-dma-is-automated-dont-double-up',1,'']]],
  ['don_20t_20enable_20channels_20you_20haven_20t_20configured_134',['🟡 Don&apos;t enable channels you haven&apos;t configured',['../tutorial_hdma.html#autotoc_md-dont-enable-channels-you-havent-configured',1,'']]],
  ['don_20t_20glue_20the_20camera_20to_20the_20player_20—_20deadzone_20it_135',['Don&apos;t glue the camera to the player — deadzone it',['../craft_camera.html#dont-glue-the-camera-to-the-player--deadzone-it',1,'']]],
  ['don_20t_20have_20to_20think_20about_20it_136',['🟠 Endianness — but you don&apos;t have to think about it',['../tutorial_sram.html#autotoc_md-endianness--but-you-dont-have-to-think-about-it',1,'']]],
  ['don_20t_20loop_20over_20100_20bricks_137',['5. Grid Collision (Don&apos;t Loop Over 100 Bricks)',['../examples_games_breakout.html#autotoc_md5-grid-collision-dont-loop-over-100-bricks',1,'']]],
  ['double_20up_138',['🟠 OAM DMA is automated, don&apos;t double-up',['../tutorial_dma.html#autotoc_md-oam-dma-is-automated-dont-double-up',1,'']]],
  ['double_20write_20register_20sequencing_139',['🟠 Double-write register sequencing',['../tutorial_mode7.html#autotoc_md-double-write-register-sequencing',1,'']]],
  ['download_20opensnes_20sdk_140',['A3. Download OpenSNES SDK',['../getting_started.html#a3-download-opensnes-sdk',1,'']]],
  ['draw_20and_20upload_20every_20frame_141',['3. Draw and upload every frame',['../examples_sprites_dynamic_sprite.html#autotoc_md3-draw-and-upload-every-frame',1,'']]],
  ['draw_20function_20engine_20resolved_20size_142',['One Draw Function, Engine-Resolved Size',['../tutorial_animation.html#one-draw-function-engine-resolved-size',1,'']]],
  ['draw_20sync_143',['4. Main Loop: Update, Draw, Sync',['../examples_games_mapandobjects.html#autotoc_md4-main-loop-update-draw-sync',1,'']]],
  ['drawing_20letters_20in_20hex_144',['2. Drawing Letters in Hex',['../examples_fundamentals_text_glyphs.html#autotoc_md2-drawing-letters-in-hex',1,'']]],
  ['drawn_145',['Fundamentals: how a glyph is drawn',['../examples_fundamentals_text_glyphs.html',1,'examples_fundamentals']]],
  ['drift_20caught_20by_20verify_20toolchain_146',['🟢 Compiler submodule drift (caught by verify-toolchain)',['../KNOWN_LIMITATIONS.html#autotoc_md-compiler-submodule-drift-caught-by-verify-toolchain',1,'']]],
  ['drive_20a_20sprite_20with_20the_20pad_147',['Drive a sprite with the pad',['../examples_input_move_sprite.html',1,'examples_input']]],
  ['driven_148',['The debugging archaeology (all owner-listening-test driven)',['../examples_audio_speech_synth.html#the-debugging-archaeology-all-owner-listening-test-driven',1,'']]],
  ['driven_20by_20a_20tiled_20map_149',['rpg — an RPG template driven by a Tiled map',['../examples_games_rpg.html',1,'examples_games']]],
  ['driven_20entirely_20from_20c_150',['soundboard — the audio v2 engine, driven entirely from C',['../examples_audio_soundboard.html',1,'examples_audio']]],
  ['drop_20shadows_20free_20depth_151',['7. Drop Shadows (Free Depth)',['../examples_games_breakout.html#autotoc_md7-drop-shadows-free-depth',1,'']]],
  ['dropped_152',['dropped',['../KNOWN_LIMITATIONS.html#autotoc_md-vram-writes-outside-vblank-are-silently-dropped',1,'🔴 VRAM writes outside VBlank are silently dropped'],['../tutorial_dma.html#autotoc_md-vramcgramoam-writes-outside-vblank-or-force-blank-are-silently-dropped',1,'🔴 VRAM/CGRAM/OAM writes outside VBlank or force blank are silently dropped']]],
  ['drum_20kit_20with_20zero_20samples_153',['play_noise — a drum kit with zero samples',['../examples_audio_play_noise.html',1,'examples_audio']]],
  ['dsp_201_20—_20examples_20mode7_20dsp1_5fground_154',['The Super Mario Kart floor via the DSP-1 — &lt;span class=&quot;tt&quot;&gt;examples/mode7/dsp1_ground&lt;/span&gt;',['../tutorial_mode7.html#the-super-mario-kart-floor-via-the-dsp-1--examplesmode7dsp1_ground',1,'']]],
  ['dsp_201_20coprocessor_155',['DSP-1 Coprocessor',['../examples_by_category.html#dsp-1-coprocessor',1,'']]],
  ['dsp_201_20coprocessor_156',['3D math on the DSP-1 coprocessor',['../api_index.html#autotoc_md3d-math-on-the-dsp-1-coprocessor',1,'']]],
  ['dsp_201_20coprocessor_20tutorial_157',['DSP-1 Coprocessor Tutorial',['../tutorial_dsp1.html',1,'']]],
  ['dsp_201_20cube_158',['DSP-1 Cube',['../examples_chips_dsp1_cube.html',1,'examples_chips']]],
  ['dsp_201_20ground_20—_20the_20super_20mario_20kart_20floor_159',['DSP-1 Ground — the Super Mario Kart floor',['../examples_mode7_dsp1_ground.html',1,'examples_mode7']]],
  ['dsp_20registers_160',['DSP Registers',['../snes_sound_guide.html#dsp-registers',1,'']]],
  ['dsp1_5fcube_20does_161',['The 3D pipeline (what dsp1_cube does)',['../tutorial_dsp1.html#the-3d-pipeline-what-dsp1_cube-does',1,'']]],
  ['dsp1_5fground_162',['The Super Mario Kart floor via the DSP-1 — &lt;span class=&quot;tt&quot;&gt;examples/mode7/dsp1_ground&lt;/span&gt;',['../tutorial_mode7.html#the-super-mario-kart-floor-via-the-dsp-1--examplesmode7dsp1_ground',1,'']]],
  ['dsp1_5fground_20does_163',['The ground (what dsp1_ground does)',['../tutorial_dsp1.html#the-ground-what-dsp1_ground-does',1,'']]],
  ['dump_164',['dump',['../tools_luna.html#luna-assets-dump',1,'&lt;span class=&quot;tt&quot;&gt;luna assets-dump&lt;/span&gt;'],['../tools_luna.html#luna-spc-dump',1,'&lt;span class=&quot;tt&quot;&gt;luna spc-dump&lt;/span&gt;'],['../tutorial_audio.html#debugging-audio-lunas-spc-dump',1,'Debugging audio: luna&apos;s spc-dump']]],
  ['during_20gameplay_165',['Fade During Gameplay',['../examples_transitions_fading.html#fade-during-gameplay',1,'']]],
  ['during_20hdma_166',['🟡 Boundary register sequencing during HDMA',['../tutorial_window.html#autotoc_md-boundary-register-sequencing-during-hdma',1,'']]],
  ['during_20the_20picture_20lands_20on_20the_20wrong_20entry_167',['🟡 A CGRAM write during the picture lands on the wrong entry',['../KNOWN_LIMITATIONS.html#autotoc_md-a-cgram-write-during-the-picture-lands-on-the-wrong-entry',1,'']]],
  ['during_20vblank_168',['VRAM Budget During VBlank',['../examples_sprites_dynamic_sprite.html#vram-budget-during-vblank',1,'']]],
  ['dx_169',['DX',['../code_style.html#assembly-65816---wla-dx',1,'Assembly (65816 - WLA-DX)'],['../third_party.html#wla-dx',1,'WLA-DX']]],
  ['dx_20loses_20accu_20index_20tracking_20after_20branch_20merges_20lint_20enforced_170',['🟢 WLA-DX loses &lt;span class=&quot;tt&quot;&gt;.ACCU&lt;/span&gt; / &lt;span class=&quot;tt&quot;&gt;.INDEX&lt;/span&gt; tracking after branch merges (lint-enforced)',['../KNOWN_LIMITATIONS.html#autotoc_md-wla-dx-loses-accu--index-tracking-after-branch-merges-lint-enforced',1,'']]],
  ['dynamic_20map_171',['Dynamic Map',['../examples_maps_dynamic_map.html',1,'examples_maps']]],
  ['dynamic_20metasprite_20engine_172',['Dynamic Metasprite Engine',['../examples_sprites_dynamic_metasprite.html',1,'examples_sprites']]],
  ['dynamic_20sprite_173',['Setting Up a Dynamic Sprite',['../tutorial_animation.html#setting-up-a-dynamic-sprite',1,'']]],
  ['dynamic_20sprite_20engine_174',['Dynamic Sprite Engine',['../examples_maps_slope_collision.html#dynamic-sprite-engine',1,'Dynamic Sprite Engine'],['../tutorial_animation.html#the-dynamic-sprite-engine',1,'The Dynamic Sprite Engine']]],
  ['dynamic_20sprite_20engine_175',['1. Initialize the dynamic sprite engine',['../examples_sprites_dynamic_sprite.html#autotoc_md1-initialize-the-dynamic-sprite-engine',1,'']]],
  ['dynamic_20sprite_20vram_20streaming_20for_20animated_20sprites_176',['Dynamic Sprite -- VRAM Streaming for Animated Sprites',['../examples_sprites_dynamic_sprite.html',1,'examples_sprites']]],
  ['dynamic_20sprites_177',['Dynamic Sprites',['../examples_games_mapandobjects.html#dynamic-sprites',1,'Dynamic Sprites'],['../examples_sprites_dynamic_sprite.html#static-vs-dynamic-sprites',1,'Static vs Dynamic Sprites']]]
];
