var searchData=
[
  ['gain_20modes_20when_20adsr_20disabled_0',['GAIN Modes (when ADSR disabled)',['../snes_sound_guide.html#autotoc_md688',1,'']]],
  ['game_1',['Game',['../getting_started.html#autotoc_md542',1,'Test Your Game'],['../examples_games_breakout.html#autotoc_md1221',1,'Why &lt;span class=&quot;tt&quot;&gt;ASMSRC&lt;/span&gt; for a Game?']]],
  ['game_2',['game',['../examples_basics_game_skeleton.html',1,'game_skeleton — the smallest complete game'],['../examples_games_mode7_racing.html',1,'mode7_racing — an F-Zero-style mini game'],['../craft_planning.html',1,'Planning your SNES game'],['../examples_backgrounds_mode2.html#autotoc_md1021',1,'Why it matters for your game'],['../examples_basics_game_skeleton.html#autotoc_md1068',1,'Why it matters for your game'],['../examples_basics_panel_hud.html#autotoc_md1074',1,'Why it matters for your game'],['../examples_color_palette_cycle.html#autotoc_md1144',1,'Why it matters for your game'],['../examples_color_shadow_tint.html#autotoc_md1152',1,'Why it matters for your game'],['../examples_sprites_sprite_swarm.html#autotoc_md1688',1,'Why it matters for your game']]],
  ['game_20craft_3',['Game-Craft',['../index.html#autotoc_md2',1,'']]],
  ['game_20craft_20guides_4',['Game-Craft Guides',['../craft.html',1,'index']]],
  ['game_20developer_5',['Path A: Game Developer',['../getting_started.html#autotoc_md534',1,'']]],
  ['game_20examples_6',['Complete Game Examples',['../examples_games.html',1,'examples']]],
  ['game_20feel_3a_20juice_20on_20real_20hardware_7',['Game feel: juice on real hardware',['../craft_game_feel.html',1,'craft']]],
  ['game_20loop_8',['Game Loop',['../examples_games_breakout.html#autotoc_md1213',1,'9. The Game Loop'],['../tutorial_animation.html#autotoc_md86',1,'The Game Loop']]],
  ['game_20math_20mechanics_9',['Game math &amp;amp; mechanics',['../examples_by_category.html#autotoc_md595',1,'']]],
  ['game_20over_10',['Game Over',['../tutorial_game_states.html#autotoc_md194',1,'']]],
  ['game_20over_20breakout_11',['Simple Game Over (Breakout)',['../tutorial_game_states.html#autotoc_md195',1,'']]],
  ['game_20over_20tetris_12',['Restart Game Over (Tetris)',['../tutorial_game_states.html#autotoc_md196',1,'']]],
  ['game_20over_20with_20fade_13',['Game Over with Fade',['../tutorial_game_states.html#autotoc_md197',1,'']]],
  ['game_20sram_20persistence_14',['Save Game -- SRAM Persistence',['../examples_memory_save_game.html',1,'examples_memory']]],
  ['game_20state_20struct_15',['5. The Game State Struct',['../examples_scrolling_continuous_scroll.html#autotoc_md1565',1,'']]],
  ['game_20states_16',['What Are Game States?',['../tutorial_game_states.html#autotoc_md184',1,'']]],
  ['game_20states_20tutorial_17',['Game States Tutorial',['../tutorial_game_states.html',1,'index']]],
  ['game_20you_20can_20finish_18',['Scope a first game you can finish',['../craft_planning.html#autotoc_md474',1,'']]],
  ['game_5fskeleton_20—_20the_20smallest_20complete_20game_19',['game_skeleton — the smallest complete game',['../examples_basics_game_skeleton.html',1,'examples_basics']]],
  ['gameplay_20',['Fade During Gameplay',['../examples_transitions_fading.html#autotoc_md1741',1,'']]],
  ['games_21',['Games',['../group__examples.html#autotoc_md1802',1,'Games'],['../examples_basics_random.html#autotoc_md1084',1,'Using rand() in Games'],['../examples_windows_window.html#autotoc_md1785',1,'Window Shapes in Commercial Games']]],
  ['games_20capstones_22',['Games (capstones)',['../examples_by_category.html#autotoc_md604',1,'']]],
  ['games_20using_20mode_201_23',['Games Using Mode 1',['../examples_backgrounds_mode1.html#autotoc_md964',1,'']]],
  ['garbled_20palette_24',['Wrong colors / garbled palette',['../troubleshooting.html#autotoc_md728',1,'']]],
  ['gate_25',['The window gate',['../tutorial_colormath.html#autotoc_md142',1,'']]],
  ['gate_20to_20colour_20math_26',['🟠 &lt;span class=&quot;tt&quot;&gt;windowEnable(window, WINDOW_MATH)&lt;/span&gt; is the gate to colour math',['../tutorial_window.html#autotoc_md432',1,'']]],
  ['gated_20spotlight_20blend_20—_20examples_20windows_20transparent_5fwindow_27',['Window-gated spotlight blend — &lt;span class=&quot;tt&quot;&gt;examples/windows/transparent_window&lt;/span&gt;',['../tutorial_colormath.html#autotoc_md146',1,'']]],
  ['general_28',['General',['../code_style.html#autotoc_md606',1,'General'],['../code_style.html#autotoc_md613',1,'General']]],
  ['general_20dma_20enable_29',['$420B - MDMAEN (General DMA Enable)',['../registers.html#autotoc_md834',1,'']]],
  ['generated_20files_30',['Generated Files',['../examples_audio_snesmod_music.html#autotoc_md898',1,'']]],
  ['generated_20header_31',['The generated header',['../tools_aseprite2snes.html#autotoc_md488',1,'']]],
  ['generating_20assets_32',['Re-generating assets',['../examples_games_shmup_1942.html#autotoc_md1286',1,'']]],
  ['generation_33',['HDMA gradient table generation',['../tutorial_math.html#autotoc_md273',1,'']]],
  ['generator_20ram_34',['CGRAM (Color Generator RAM)',['../examples_hdma_gradient_colors.html#autotoc_md1302',1,'']]],
  ['genre_35',['Choose a background mode from your genre',['../craft_planning.html#autotoc_md472',1,'']]],
  ['get_20an_20emulator_36',['A2. Get an Emulator',['../getting_started.html#autotoc_md536',1,'']]],
  ['getframecount_37',['Using getFrameCount()',['../tutorial_animation.html#autotoc_md74',1,'']]],
  ['getting_20help_38',['Getting Help',['../getting_started.html#autotoc_md558',1,'']]],
  ['getting_20more_20help_39',['Getting More Help',['../troubleshooting.html#autotoc_md734',1,'']]],
  ['getting_20started_40',['Getting Started',['../tutorial_sa1.html#autotoc_md331',1,'Getting Started'],['../tutorial_superfx.html#autotoc_md402',1,'Getting Started'],['../group__examples.html#autotoc_md1794',1,'Getting Started']]],
  ['getting_20started_20with_20opensnes_41',['Getting Started with OpenSNES',['../getting_started.html',1,'index']]],
  ['gfx4snes_42',['gfx4snes',['../examples_games_likemario.html#autotoc_md1247',1,'Asset Conversion with gfx4snes'],['../tutorial_animation.html#autotoc_md78',1,'Converting Sprite Sheets with gfx4snes'],['../third_party.html#autotoc_md740',1,'gfx4snes'],['../tutorial_graphics.html#autotoc_md208',1,'Using gfx4snes']]],
  ['gfx4snes_20—_20images_20to_20tiles_20palettes_20maps_43',['gfx4snes — images to tiles, palettes &amp;amp; maps',['../tools_gfx4snes.html',1,'tools']]],
  ['give_44',['When you need more than layers can give',['../craft_backgrounds.html#autotoc_md445',1,'']]],
  ['give_20every_20layer_20a_20job_45',['Give every layer a job',['../craft_backgrounds.html#autotoc_md439',1,'']]],
  ['glance_46',['The tools at a glance',['../tools.html#autotoc_md514',1,'']]],
  ['glitches_47',['Audio glitches',['../examples_audio_snesmod_music.html#autotoc_md917',1,'']]],
  ['global_20registers_48',['Global Registers',['../snes_sound_guide.html#autotoc_md677',1,'']]],
  ['glue_20the_20camera_20to_20the_20player_20—_20deadzone_20it_49',['Don&apos;t glue the camera to the player — deadzone it',['../craft_camera.html#autotoc_md448',1,'']]],
  ['glyph_20is_20drawn_50',['Fundamentals: how a glyph is drawn',['../examples_fundamentals_text_glyphs.html',1,'examples_fundamentals']]],
  ['go_20deeper_20—_20the_20curated_20shelf_51',['Go deeper — the curated shelf',['../craft.html#autotoc_md478',1,'']]],
  ['go_20further_52',['Go Further',['../examples_fundamentals_text_glyphs.html#autotoc_md1191',1,'Go Further'],['../examples_games_breakout.html#autotoc_md1217',1,'Go Further'],['../examples_games_likemario.html#autotoc_md1243',1,'Go Further'],['../examples_hdma_hdma_wave.html#autotoc_md1329',1,'Go Further'],['../examples_scrolling_continuous_scroll.html#autotoc_md1569',1,'Go Further']]],
  ['goes_53',['Where the time goes',['../craft_frame_budget.html#autotoc_md454',1,'']]],
  ['goes_20in_20what_20comes_20out_54',['goes in what comes out',['../tools_font2snes.html#autotoc_md491',1,'What goes in, what comes out'],['../tools_gfx4snes.html#autotoc_md496',1,'What goes in, what comes out'],['../tools_img2snes.html#autotoc_md502',1,'What goes in, what comes out'],['../tools_palplan.html#autotoc_md507',1,'What goes in, what comes out'],['../tools_smconv.html#autotoc_md517',1,'What goes in, what comes out'],['../tools_tmx2snes.html#autotoc_md522',1,'What goes in, what comes out'],['../tools_wav2brr.html#autotoc_md527',1,'What goes in, what comes out']]],
  ['goes_20on_20a_20different_20layer_20above_20the_20panel_55',['🟡 Text goes on a &lt;em&gt;different&lt;/em&gt; layer, above the panel',['../tutorial_panel.html#autotoc_md325',1,'']]],
  ['going_20further_56',['Going Further',['../examples_backgrounds_mode1_bg3_priority.html#autotoc_md1005',1,'Going Further'],['../examples_hdma_gradient_colors.html#autotoc_md1306',1,'Going Further'],['../examples_memory_hirom_demo.html#autotoc_md1483',1,'Going Further'],['../examples_memory_save_game.html#autotoc_md1505',1,'Going Further'],['../examples_mode7_perspective.html#autotoc_md1519',1,'Going Further'],['../examples_mode7_rotate_scale.html#autotoc_md1544',1,'Going Further'],['../examples_scrolling_parallax_scroll.html#autotoc_md1605',1,'Going Further'],['../examples_sprites_animated_sprite.html#autotoc_md1622',1,'Going Further'],['../examples_sprites_dynamic_sprite.html#autotoc_md1645',1,'Going Further'],['../examples_sprites_simple_sprite.html#autotoc_md1672',1,'Going Further'],['../examples_sprites_sprite_sizes.html#autotoc_md1687',1,'Going Further'],['../examples_transitions_mosaic.html#autotoc_md1758',1,'Going Further'],['../examples_windows_transparent_window.html#autotoc_md1774',1,'Going Further'],['../examples_windows_window.html#autotoc_md1788',1,'Going Further']]],
  ['good_57',['Stage 4 — &quot;Can I make it feel good?&quot;',['../learning_path.html#autotoc_md564',1,'']]],
  ['good_20first_20issues_58',['Good First Issues',['../contributing.html#autotoc_md1821',1,'']]],
  ['goomba_20example_59',['5. Enemy AI (Goomba Example)',['../examples_games_mapandobjects.html#autotoc_md1265',1,'']]],
  ['gotchas_60',['Gotchas',['../tutorial_colormath.html#autotoc_md147',1,'Gotchas'],['../tutorial_dma.html#autotoc_md174',1,'Gotchas'],['../tutorial_hdma.html#autotoc_md229',1,'Gotchas'],['../tutorial_map.html#autotoc_md257',1,'Gotchas'],['../tutorial_math.html#autotoc_md274',1,'Gotchas'],['../tutorial_mode7.html#autotoc_md296',1,'Gotchas'],['../tutorial_mosaic.html#autotoc_md311',1,'Gotchas'],['../tutorial_panel.html#autotoc_md323',1,'Gotchas'],['../tutorial_sram.html#autotoc_md389',1,'Gotchas'],['../tutorial_window.html#autotoc_md430',1,'Gotchas']]],
  ['gotchas_20worth_20knowing_20up_20front_61',['Gotchas worth knowing up front',['../tools_font2snes.html#autotoc_md494',1,'Gotchas worth knowing up front'],['../tools_gfx4snes.html#autotoc_md500',1,'Gotchas worth knowing up front'],['../tools_img2snes.html#autotoc_md505',1,'Gotchas worth knowing up front'],['../tools_palplan.html#autotoc_md511',1,'Gotchas worth knowing up front'],['../tools_smconv.html#autotoc_md520',1,'Gotchas worth knowing up front'],['../tools_tmx2snes.html#autotoc_md525',1,'Gotchas worth knowing up front'],['../tools_wav2brr.html#autotoc_md530',1,'Gotchas worth knowing up front']]],
  ['gradient_62',['HDMA Indirect Gradient',['../examples_hdma_hdma_indirect_gradient.html',1,'examples_hdma']]],
  ['gradient_20—_20brightness_20dithered_20backdrop_63',['&quot;9-bit&quot; gradient — brightness-dithered backdrop',['../examples_color_gradient_9bit.html',1,'examples_color']]],
  ['gradient_20—_20examples_20hdma_20gradient_5fcolors_64',['Static colour gradient — &lt;span class=&quot;tt&quot;&gt;examples/hdma/gradient_colors&lt;/span&gt;',['../tutorial_hdma.html#autotoc_md220',1,'']]],
  ['gradient_20colors_20hdma_20color_20gradients_65',['Gradient Colors -- HDMA Color Gradients',['../examples_hdma_gradient_colors.html',1,'examples_hdma']]],
  ['gradient_20table_66',['2. The gradient table',['../examples_hdma_gradient_colors.html#autotoc_md1299',1,'']]],
  ['gradient_20table_20generation_67',['HDMA gradient table generation',['../tutorial_math.html#autotoc_md273',1,'']]],
  ['gradient_5f9bit_68',['Two channels, one visual — &lt;span class=&quot;tt&quot;&gt;examples/color/gradient_9bit&lt;/span&gt;',['../tutorial_hdma.html#autotoc_md227',1,'']]],
  ['gradient_5fcolors_69',['Static colour gradient — &lt;span class=&quot;tt&quot;&gt;examples/hdma/gradient_colors&lt;/span&gt;',['../tutorial_hdma.html#autotoc_md220',1,'']]],
  ['gradients_70',['Gradient Colors -- HDMA Color Gradients',['../examples_hdma_gradient_colors.html',1,'examples_hdma']]],
  ['graphics_71',['Graphics',['../tutorial_animation.html#autotoc_md91',1,'Approach 2: Overwrite Tile Graphics'],['../tutorial_graphics.html#autotoc_md201',1,'Setting Up Graphics']]],
  ['graphics_20backgrounds_20tutorial_72',['Graphics &amp;amp; Backgrounds Tutorial',['../tutorial_graphics.html',1,'index']]],
  ['graphics_20conversion_20tools_73',['Graphics Conversion Tools',['../snes_graphics_guide.html#autotoc_md658',1,'']]],
  ['graphics_20fundamentals_74',['Level 2 &amp;ndash; Graphics Fundamentals',['../examples.html#autotoc_md1548',1,'']]],
  ['graphics_20into_20vram_75',['1. Load sprite graphics into VRAM',['../examples_sprites_simple_sprite.html#autotoc_md1662',1,'']]],
  ['graphics_20issues_76',['Graphics Issues',['../troubleshooting.html#autotoc_md727',1,'']]],
  ['graphics_20programming_20guide_77',['SNES Graphics Programming Guide',['../snes_graphics_guide.html',1,'index']]],
  ['gravity_20in_20two_20lines_78',['5. Gravity in Two Lines',['../examples_games_likemario.html#autotoc_md1237',1,'']]],
  ['grid_20based_20collision_20breakout_20bricks_79',['Grid-Based Collision (Breakout Bricks)',['../tutorial_collision.html#autotoc_md134',1,'']]],
  ['grid_20collision_20don_20t_20loop_20over_20100_20bricks_80',['5. Grid Collision (Don&apos;t Loop Over 100 Bricks)',['../examples_games_breakout.html#autotoc_md1209',1,'']]],
  ['grid_20platformer_20landing_81',['Snapping to Tile Grid (Platformer Landing)',['../tutorial_collision.html#autotoc_md133',1,'']]],
  ['ground_20effect_82',['Mode 7 Perspective -- Pseudo-3D Ground Effect',['../examples_mode7_perspective.html',1,'examples_mode7']]],
  ['gsu_83',['SuperFX (GSU)',['../examples_by_category.html#autotoc_md601',1,'']]],
  ['gsu_20assembly_20code_84',['2. Write GSU Assembly Code',['../tutorial_superfx.html#autotoc_md404',1,'']]],
  ['gsu_20loader_2065816_20asm_85',['3. Create the GSU Loader (65816 ASM)',['../tutorial_superfx.html#autotoc_md405',1,'']]],
  ['gsu_20registers_20_243000_20_24303f_86',['SuperFX / GSU Registers ($3000-$303F)',['../registers.html#autotoc_md854',1,'']]],
  ['gsu_20tutorial_87',['SuperFX (GSU) Tutorial',['../tutorial_superfx.html',1,'index']]],
  ['guide_88',['Guide',['../code_style.html',1,'OpenSNES Code Style Guide'],['../snes_graphics_guide.html',1,'SNES Graphics Programming Guide'],['../snes_sound_guide.html',1,'SNES Sound Programming Guide']]],
  ['guides_89',['Guides',['../craft.html',1,'Game-Craft Guides'],['../index.html#autotoc_md1',1,'Guides']]],
  ['guides_90',['The guides',['../craft.html#autotoc_md477',1,'']]]
];
