var searchData=
[
  ['i_20ram_20—_20the_20mailbox_0',['I-RAM — The Mailbox',['../tutorial_sa1.html#autotoc_md287',1,'']]],
  ['i_20ram_20layout_20convention_1',['I-RAM Layout Convention',['../tutorial_sa1.html#autotoc_md295',1,'']]],
  ['identical_20to_20lorom_2',['2. The code is identical to LoROM',['../examples_memory_hirom_demo.html#autotoc_md1431',1,'']]],
  ['idle_20check_3',['Animation Timing with Idle Check',['../tutorial_animation.html#autotoc_md79',1,'']]],
  ['idle_20loop_4',['Idle Loop',['../examples_graphics_backgrounds_mode1_lz77.html#autotoc_md1002',1,'5. Idle Loop'],['../examples_text_text_test.html#autotoc_md1528',1,'5. Idle Loop']]],
  ['ids_5',['4. Animate by changing frame IDs',['../examples_graphics_sprites_dynamic_sprite.html#autotoc_md1241',1,'']]],
  ['implementation_6',['Implementation',['../examples_graphics_effects_fading.html#autotoc_md1059',1,'Basic Fade Implementation'],['../tutorial_game_states.html#autotoc_md173',1,'Title Screen Implementation']]],
  ['important_3a_20call_20snesmodprocess_7',['Important: Call snesmodProcess()!',['../tutorial_audio.html#autotoc_md105',1,'']]],
  ['important_3a_20scroll_20registers_20require_20repeat_20mode_8',['IMPORTANT: Scroll Registers Require Repeat Mode',['../hdma_8h.html#autotoc_md33',1,'']]],
  ['in_9',['Fade Out / Fade In',['../tutorial_game_states.html#autotoc_md171',1,'']]],
  ['in_20assembly_10',['2. Register Object Types in Assembly',['../examples_games_mapandobjects.html#autotoc_md880',1,'']]],
  ['in_20black_20to_20full_11',['Fade In (Black to Full)',['../examples_graphics_effects_fading.html#autotoc_md1060',1,'']]],
  ['in_20claude_12',['Project knowledge in &lt;span class=&quot;tt&quot;&gt;.claude/&lt;/span&gt;',['../contributing.html#autotoc_md1557',1,'']]],
  ['in_20commercial_20games_13',['Window Shapes in Commercial Games',['../examples_graphics_effects_window.html#autotoc_md1205',1,'']]],
  ['in_20force_20blank_14',['1. Initialize and Stay in Force Blank',['../examples_graphics_backgrounds_mode1_lz77.html#autotoc_md998',1,'']]],
  ['in_20games_15',['Using rand() in Games',['../examples_basics_random.html#autotoc_md797',1,'']]],
  ['in_20hex_16',['2. Drawing Letters in Hex',['../examples_text_hello_world.html#autotoc_md1492',1,'']]],
  ['in_20mesen2_17',['Debugging in Mesen2',['../tutorial_sa1.html#autotoc_md301',1,'']]],
  ['in_20mode_201_18',['in Mode 1',['../examples_graphics_sprites_object_size.html#autotoc_md1261',1,'1. Set up text on BG1 (4bpp in Mode 1)'],['../examples_graphics_backgrounds_mode1_bg3_priority.html#autotoc_md986',1,'BG3 is 2bpp in Mode 1']]],
  ['in_20nmi_19',['🟡 WRAM data port &lt;span class=&quot;tt&quot;&gt;$2180&lt;/span&gt;–&lt;span class=&quot;tt&quot;&gt;$2183&lt;/span&gt; is NOT safe in NMI',['../tutorial_dma.html#autotoc_md165',1,'']]],
  ['in_20oam_20',['16x16 Tiles in OAM',['../examples_graphics_sprites_animated_sprite.html#autotoc_md1226',1,'']]],
  ['in_20opensnes_21',['Audio Options in OpenSNES',['../tutorial_audio.html#autotoc_md95',1,'']]],
  ['in_20sram_22',['🟠 Cannot store pointers in SRAM',['../tutorial_sram.html#autotoc_md349',1,'']]],
  ['in_20the_20lib_20chantier_20b6_202026_2005_2009_23',['&lt;span class=&quot;tt&quot;&gt;atan2&lt;/span&gt; and &lt;span class=&quot;tt&quot;&gt;sqrt&lt;/span&gt; ship in the lib (chantier B6, 2026-05-09)',['../tutorial_math.html#autotoc_md249',1,'']]],
  ['in_20the_20main_20loop_24',['Per-frame DMA in the main loop',['../tutorial_dma.html#autotoc_md156',1,'']]],
  ['in_20the_20makefile_25',['in the Makefile',['../examples_memory_hirom_demo.html#autotoc_md1430',1,'1. Enable HiROM in the Makefile'],['../examples_memory_save_game.html#autotoc_md1461',1,'4. Enable SRAM in the Makefile']]],
  ['in_20the_20nmi_20handler_26',['🟡 HDMA fires before the user callback in the NMI handler',['../tutorial_hdma.html#autotoc_md211',1,'']]],
  ['in_20two_20lines_27',['5. Gravity in Two Lines',['../examples_games_likemario.html#autotoc_md855',1,'']]],
  ['in_20vram_28',['Sprite Sheets in VRAM',['../examples_graphics_sprites_animated_sprite.html#autotoc_md1225',1,'']]],
  ['in_20your_20makefile_29',['in Your Makefile',['../tutorial_sa1.html#autotoc_md289',1,'1. Enable SA-1 in Your Makefile'],['../tutorial_superfx.html#autotoc_md358',1,'1. Enable SuperFX in Your Makefile']]],
  ['inclusive_20on_20both_20ends_30',['Boundaries are inclusive on both ends',['../tutorial_window.html#autotoc_md379',1,'']]],
  ['increment_31',['$2115 - VMAIN (VRAM Address Increment)',['../registers.html#autotoc_md657',1,'']]],
  ['independent_20background_20scrolling_32',['Independent Background Scrolling',['../examples_graphics_backgrounds_mixed_scroll.html#autotoc_md928',1,'']]],
  ['independent_20control_33',['Independent Control',['../examples_input_two_players.html#autotoc_md1351',1,'']]],
  ['infinite_20scrolling_34',['Continuous / Infinite Scrolling',['../tutorial_scrolling.html#autotoc_md313',1,'']]],
  ['inidisp_20_242100_35',['Screen Brightness (INIDISP $2100)',['../examples_graphics_effects.html#autotoc_md1155',1,'']]],
  ['inidisp_20display_20control_36',['$2100 - INIDISP (Display Control)',['../registers.html#autotoc_md644',1,'']]],
  ['inidisp_20register_37',['INIDISP Register',['../examples_graphics_effects_fading.html#autotoc_md1057',1,'']]],
  ['initial_20setup_38',['Force Blank for Initial Setup',['../examples_graphics_sprites_dynamic_sprite.html#autotoc_md1245',1,'']]],
  ['initialization_39',['Initialization',['../examples_input_superscope.html#autotoc_md1326',1,'1. Initialization'],['../tutorial_animation.html#autotoc_md82',1,'Initialization'],['../examples_audio_snesmod_music.html#autotoc_md714',1,'Initialization'],['../examples_audio_snesmod_sfx.html#autotoc_md766',1,'SNESMOD Initialization']]],
  ['initialize_20and_20stay_20in_20force_20blank_40',['1. Initialize and Stay in Force Blank',['../examples_graphics_backgrounds_mode1_lz77.html#autotoc_md998',1,'']]],
  ['initialize_20display_41',['Initialize Display',['../tutorial_graphics.html#autotoc_md185',1,'']]],
  ['initialize_20from_20c_42',['3. Initialize from C',['../tutorial_sa1.html#autotoc_md291',1,'']]],
  ['initialize_20oam_43',['Initialize OAM',['../tutorial_sprites.html#autotoc_md321',1,'']]],
  ['initialize_20text_20and_20detect_20mouse_44',['1. Initialize Text and Detect Mouse',['../examples_input_mouse.html#autotoc_md1309',1,'']]],
  ['initialize_20text_20and_20load_20font_45',['3. Initialize Text and Load Font',['../examples_text_text_test.html#autotoc_md1526',1,'']]],
  ['initialize_20the_20dynamic_20sprite_20engine_46',['1. Initialize the dynamic sprite engine',['../examples_graphics_sprites_dynamic_sprite.html#autotoc_md1238',1,'']]],
  ['initialize_20the_20map_20and_20sprite_20system_47',['1. Initialize the Map and Sprite System',['../examples_games_mapandobjects.html#autotoc_md879',1,'']]],
  ['initialize_20the_20transformation_48',['2. Initialize the transformation',['../examples_graphics_backgrounds_mode7.html#autotoc_md1020',1,'']]],
  ['initializers_49',['Static variables with initializers',['../troubleshooting.html#autotoc_md565',1,'']]],
  ['input_50',['Input',['../examples_input_controller.html',1,'Controller Input'],['../examples_by_category.html#autotoc_md435',1,'Input'],['../group__examples.html#autotoc_md1536',1,'Input']]],
  ['input_20and_20state_20changes_51',['Input and State Changes',['../tutorial_animation.html#autotoc_md77',1,'']]],
  ['input_20devices_52',['Input Devices',['../examples_input.html#autotoc_md1320',1,'']]],
  ['input_20examples_53',['Input Examples',['../examples_input.html',1,'examples']]],
  ['input_20latency_54',['Input Latency',['../examples_input_two_players.html#autotoc_md1374',1,'']]],
  ['input_20not_20working_55',['Controller input not working',['../troubleshooting.html#autotoc_md570',1,'']]],
  ['input_20reading_56',['4. Input Reading',['../examples_graphics_backgrounds_continuous_scroll.html#autotoc_md909',1,'']]],
  ['input_20tutorial_57',['Controller Input Tutorial',['../tutorial_input.html',1,'index']]],
  ['input_20works_20on_20the_20snes_58',['How Input Works on the SNES',['../examples_input_controller.html#autotoc_md1297',1,'']]],
  ['inputs_20interaction_59',['Inputs / interaction',['../basics_2fix32__orbit_2main_8c.html#autotoc_md792',1,'']]],
  ['ins_60',['Framework opt-ins',['../index.html#autotoc_md6',1,'']]],
  ['inside_61',['Inversion: Show Inside',['../examples_graphics_effects_window.html#autotoc_md1201',1,'']]],
  ['install_20prerequisites_62',['Install Prerequisites',['../getting_started.html#autotoc_md396',1,'A1. Install Prerequisites'],['../getting_started.html#autotoc_md404',1,'B1. Install Prerequisites']]],
  ['instead_20of_20a_20switch_63',['Why a framework instead of a switch',['../examples_basics_scene_stack.html#autotoc_md808',1,'']]],
  ['int_20and_20long_20sizes_20are_20correct_20on_20this_20target_20since_20chantier_20a1_64',['🟢 &lt;span class=&quot;tt&quot;&gt;int&lt;/span&gt; and &lt;span class=&quot;tt&quot;&gt;long&lt;/span&gt; sizes are correct on this target (since chantier A1)',['../tutorial_math.html#autotoc_md242',1,'']]],
  ['integration_65',['Tiled Map Editor Integration',['../examples_maps_tiled.html',1,'examples_maps']]],
  ['interact_66',['🟠 Half-mode and saturation interact',['../tutorial_colormath.html#autotoc_md143',1,'']]],
  ['interaction_67',['Inputs / interaction',['../basics_2fix32__orbit_2main_8c.html#autotoc_md792',1,'']]],
  ['interactive_20feedback_68',['4. Interactive feedback',['../examples_memory_hirom_demo.html#autotoc_md1433',1,'']]],
  ['interleaved_20vram_20format_69',['The interleaved VRAM format',['../tutorial_mode7.html#autotoc_md255',1,'']]],
  ['interleaved_20vram_20no_20mode7loadgraphics_20helper_20today_70',['🔴 Interleaved VRAM, no &lt;span class=&quot;tt&quot;&gt;mode7LoadGraphics&lt;/span&gt; helper today',['../tutorial_mode7.html#autotoc_md265',1,'']]],
  ['interpolation_71',['Smooth interpolation',['../tutorial_math.html#autotoc_md239',1,'']]],
  ['interrupt_20control_72',['Interrupt Control',['../registers.html#autotoc_md668',1,'']]],
  ['interrupt_20enable_73',['$4200 - NMITIMEN (Interrupt Enable)',['../registers.html#autotoc_md669',1,'']]],
  ['into_20vram_74',['1. Load sprite graphics into VRAM',['../examples_graphics_sprites_simple_sprite.html#autotoc_md1283',1,'']]],
  ['intuitive_75',['🟠 &lt;span class=&quot;tt&quot;&gt;colorMathSetSource&lt;/span&gt; polarity is opposite of intuitive',['../tutorial_colormath.html#autotoc_md142',1,'']]],
  ['inversion_3a_20show_20inside_76',['Inversion: Show Inside',['../examples_graphics_effects_window.html#autotoc_md1201',1,'']]],
  ['irq_20status_77',['$4211 - TIMEUP (IRQ Status)',['../registers.html#autotoc_md672',1,'']]],
  ['irq_20timer_78',['$4207-$420A - HTIMEx/VTIMEx (IRQ Timer)',['../registers.html#autotoc_md670',1,'']]],
  ['is_79',['is',['../tutorial_colormath.html#autotoc_md131',1,'What colour math actually is'],['../tutorial_dma.html#autotoc_md149',1,'What DMA actually is'],['../tutorial_hdma.html#autotoc_md194',1,'What HDMA actually is'],['../tutorial_mode7.html#autotoc_md253',1,'What Mode 7 actually is'],['../tutorial_mosaic.html#autotoc_md272',1,'What mosaic actually is'],['../tutorial_sram.html#autotoc_md334',1,'What SRAM actually is']]],
  ['is_202bpp_20in_20mode_201_80',['BG3 is 2bpp in Mode 1',['../examples_graphics_backgrounds_mode1_bg3_priority.html#autotoc_md986',1,'']]],
  ['is_204_20kb_20per_20frame_81',['🔴 VBlank DMA budget is ~4 KB per frame',['../tutorial_dma.html#autotoc_md160',1,'']]],
  ['is_20a_20memset_20not_20a_20write_20protect_82',['🟡 &lt;span class=&quot;tt&quot;&gt;sramClear&lt;/span&gt; is a memset, not a write-protect',['../tutorial_sram.html#autotoc_md352',1,'']]],
  ['is_20an_20empty_20window_83',['&lt;span class=&quot;tt&quot;&gt;left &amp;gt; right&lt;/span&gt; is an &quot;empty&quot; window',['../tutorial_window.html#autotoc_md378',1,'']]],
  ['is_20automated_20don_20t_20double_20up_84',['🟠 OAM DMA is automated, don&apos;t double-up',['../tutorial_dma.html#autotoc_md163',1,'']]],
  ['is_20bigger_20than_20the_20screen_85',['1. The World Is Bigger Than the Screen',['../examples_games_likemario.html#autotoc_md851',1,'']]],
  ['is_20black_86',['ROM loads but screen is black',['../troubleshooting.html#autotoc_md567',1,'']]],
  ['is_20hdma_87',['1. What Is HDMA?',['../examples_graphics_effects_hdma_wave.html#autotoc_md1107',1,'']]],
  ['is_20identical_20to_20lorom_88',['2. The code is identical to LoROM',['../examples_memory_hirom_demo.html#autotoc_md1431',1,'']]],
  ['is_20jerky_89',['Scrolling is jerky',['../troubleshooting.html#autotoc_md575',1,'']]],
  ['is_20no_20printf_90',['1. There Is No printf',['../examples_text_hello_world.html#autotoc_md1491',1,'']]],
  ['is_20not_20reset_20by_20consoleinit_91',['🟡 Mosaic state is not reset by &lt;span class=&quot;tt&quot;&gt;consoleInit&lt;/span&gt;',['../tutorial_mosaic.html#autotoc_md282',1,'']]],
  ['is_20not_20safe_20in_20nmi_92',['🟡 WRAM data port &lt;span class=&quot;tt&quot;&gt;$2180&lt;/span&gt;–&lt;span class=&quot;tt&quot;&gt;$2183&lt;/span&gt; is NOT safe in NMI',['../tutorial_dma.html#autotoc_md165',1,'']]],
  ['is_20opposite_20of_20intuitive_93',['🟠 &lt;span class=&quot;tt&quot;&gt;colorMathSetSource&lt;/span&gt; polarity is opposite of intuitive',['../tutorial_colormath.html#autotoc_md142',1,'']]],
  ['is_20read_20only_20the_20ram_20buffer_20pattern_94',['3. ROM is Read-Only (The RAM Buffer Pattern)',['../examples_games_breakout.html#autotoc_md825',1,'']]],
  ['is_20reserved_20for_20oam_20dma_95',['🔴 Channel 7 is reserved for OAM DMA',['../tutorial_hdma.html#autotoc_md208',1,'']]],
  ['is_20sa_201_96',['What Is SA-1?',['../tutorial_sa1.html#autotoc_md285',1,'']]],
  ['is_20size_201_20pixels_97',['🟡 Mosaic block size is &quot;size + 1&quot; pixels',['../tutorial_mosaic.html#autotoc_md280',1,'']]],
  ['is_20sub_20screen_20only_20trap_98',['🔴 The &quot;BG2 is sub-screen-only&quot; trap',['../tutorial_colormath.html#autotoc_md141',1,'']]],
  ['is_20superfx_99',['What Is SuperFX?',['../tutorial_superfx.html#autotoc_md355',1,'']]],
  ['is_20the_20gate_20to_20colour_20math_100',['🟠 &lt;span class=&quot;tt&quot;&gt;windowEnable(window, WINDOW_MATH)&lt;/span&gt; is the gate to colour math',['../tutorial_window.html#autotoc_md387',1,'']]],
  ['is_20the_20tilemap_20centre_20not_20the_20screen_20centre_101',['🟡 Centre default is the tilemap centre, not the screen centre',['../tutorial_mode7.html#autotoc_md268',1,'']]],
  ['isa_2010_2074_20mhz_102',['SA-1 Coprocessor (same ISA, 10.74 MHz)',['../learning_path.html#autotoc_md424',1,'']]],
  ['issues_103',['Issues',['../troubleshooting.html#autotoc_md559',1,'Build Issues'],['../examples_audio_snesmod_music.html#autotoc_md738',1,'Common Issues'],['../contributing.html#autotoc_md1559',1,'Good First Issues'],['../troubleshooting.html#autotoc_md572',1,'Graphics Issues'],['../troubleshooting.html#autotoc_md576',1,'Memory Issues']]],
  ['issues_20black_20screen_20crash_104',['Runtime Issues (Black Screen / Crash)',['../troubleshooting.html#autotoc_md566',1,'']]],
  ['it_105',['🟠 Endianness — but you don&apos;t have to think about it',['../tutorial_sram.html#autotoc_md350',1,'']]],
  ['it_20works_106',['It Works',['../tutorial_animation.html#autotoc_md81',1,'How It Works'],['../examples_games_mapandobjects.html#autotoc_md878',1,'How It Works'],['../examples_graphics_backgrounds_mixed_scroll.html#autotoc_md930',1,'How It Works'],['../examples_graphics_backgrounds_mode1_bg3_priority.html#autotoc_md980',1,'How It Works'],['../examples_graphics_backgrounds_mode1_lz77.html#autotoc_md997',1,'How It Works'],['../examples_graphics_backgrounds_mode7.html#autotoc_md1018',1,'How It Works'],['../examples_graphics_backgrounds_mode7_perspective.html#autotoc_md1034',1,'How It Works'],['../examples_graphics_effects_gradient_colors.html#autotoc_md1088',1,'How It Works'],['../examples_graphics_effects_mosaic.html#autotoc_md1129',1,'How It Works'],['../examples_graphics_effects_parallax_scrolling.html#autotoc_md1142',1,'How It Works'],['../examples_graphics_effects_transparent_window.html#autotoc_md1185',1,'How It Works'],['../examples_graphics_effects_window.html#autotoc_md1197',1,'How It Works'],['../examples_graphics_sprites_animated_sprite.html#autotoc_md1218',1,'How It Works'],['../examples_graphics_sprites_dynamic_sprite.html#autotoc_md1237',1,'How It Works'],['../examples_graphics_sprites_metasprite.html#autotoc_md1254',1,'How It Works'],['../examples_graphics_sprites_object_size.html#autotoc_md1260',1,'How It Works'],['../examples_graphics_sprites_simple_sprite.html#autotoc_md1282',1,'How It Works'],['../examples_input_mouse.html#autotoc_md1308',1,'How It Works'],['../examples_maps_dynamic_map.html#autotoc_md1385',1,'How It Works'],['../examples_maps_slopemario.html#autotoc_md1412',1,'How It Works'],['../examples_memory_hirom_demo.html#autotoc_md1429',1,'How It Works'],['../examples_memory_save_game.html#autotoc_md1457',1,'How It Works'],['../examples_text_text_test.html#autotoc_md1523',1,'How It Works']]]
];
