var searchData=
[
  ['y_201_20scanline_20quirk_0',['Sprite Y +1 Scanline Quirk',['../oam.html#autotoc_md631',1,'']]],
  ['you_20don_20t_20have_20to_20think_20about_20it_1',['🟠 Endianness — but you don&apos;t have to think about it',['../tutorial_sram.html#autotoc_md358',1,'']]],
  ['you_20haven_20t_20configured_2',['🟡 Don&apos;t enable channels you haven&apos;t configured',['../tutorial_hdma.html#autotoc_md220',1,'']]],
  ['you_20ll_20learn_3',['You ll Learn',['../examples_audio_snesmod_music_hirom.html#autotoc_md765',1,'What You&apos;ll Learn'],['../examples_audio_snesmod_music_large.html#autotoc_md769',1,'What You&apos;ll Learn'],['../examples_audio_snesmod_sfx.html#autotoc_md774',1,'What You&apos;ll Learn'],['../examples_basics_collision_demo.html#autotoc_md791',1,'What You&apos;ll Learn'],['../examples_basics_random.html#autotoc_md809',1,'What You&apos;ll Learn'],['../examples_basics_scene_stack.html#autotoc_md819',1,'What You&apos;ll Learn'],['../examples_basics_timer.html#autotoc_md827',1,'What You&apos;ll Learn'],['../examples_games_breakout.html#autotoc_md836',1,'What You&apos;ll Learn'],['../examples_games_likemario.html#autotoc_md864',1,'What You&apos;ll Learn'],['../examples_games_mapandobjects.html#autotoc_md888',1,'What You&apos;ll Learn'],['../examples_graphics_backgrounds_continuous_scroll.html#autotoc_md919',1,'What You&apos;ll Learn'],['../examples_graphics_backgrounds_mixed_scroll.html#autotoc_md939',1,'What You&apos;ll Learn'],['../examples_graphics_backgrounds_mode1_lz77.html#autotoc_md1007',1,'What You&apos;ll Learn'],['../examples_graphics_effects_hdma_wave.html#autotoc_md1120',1,'What You&apos;ll Learn'],['../examples_graphics_effects_superfx_3d.html#autotoc_md1179',1,'What You&apos;ll Learn'],['../examples_graphics_effects_transparency.html#autotoc_md1185',1,'What You&apos;ll Learn'],['../examples_graphics_sprites_dynamic_metasprite.html#autotoc_md1246',1,'What You&apos;ll Learn'],['../examples_graphics_sprites_metasprite.html#autotoc_md1264',1,'What You&apos;ll Learn'],['../examples_input_controller.html#autotoc_md1310',1,'What You&apos;ll Learn'],['../examples_input_mouse.html#autotoc_md1318',1,'What You&apos;ll Learn'],['../examples_input_superscope.html#autotoc_md1340',1,'What You&apos;ll Learn'],['../examples_maps_dynamic_map.html#autotoc_md1394',1,'What You&apos;ll Learn'],['../examples_maps_mapscroll.html#autotoc_md1404',1,'What You&apos;ll Learn'],['../examples_maps_slopemario.html#autotoc_md1421',1,'What You&apos;ll Learn'],['../examples_maps_tiled.html#autotoc_md1431',1,'What You&apos;ll Learn'],['../examples_memory_sa1_hello.html#autotoc_md1462',1,'What You&apos;ll Learn'],['../examples_memory_sa1_starfield.html#autotoc_md1466',1,'What You&apos;ll Learn'],['../examples_memory_superfx_hello.html#autotoc_md1488',1,'What You&apos;ll Learn'],['../examples_text_hello_world.html#autotoc_md1504',1,'What You&apos;ll Learn'],['../examples_text_text_test.html#autotoc_md1533',1,'What You&apos;ll Learn']]],
  ['your_20first_20oam_20sprite_4',['Simple Sprite -- Your First OAM Sprite',['../examples_graphics_sprites_simple_sprite.html',1,'examples_graphics_sprites']]],
  ['your_20first_20rom_5',['A4. Run Your First ROM',['../getting_started.html#autotoc_md407',1,'']]],
  ['your_20game_6',['Test Your Game',['../getting_started.html#autotoc_md411',1,'']]],
  ['your_20makefile_7',['Your Makefile',['../tutorial_sa1.html#autotoc_md297',1,'1. Enable SA-1 in Your Makefile'],['../tutorial_superfx.html#autotoc_md366',1,'1. Enable SuperFX in Your Makefile']]],
  ['your_20own_20level_8',['Making Your Own Level',['../examples_maps_tiled.html#autotoc_md1440',1,'']]],
  ['your_20own_20project_9',['A5. Create Your Own Project',['../getting_started.html#autotoc_md408',1,'']]],
  ['your_20path_10',['Choose Your Path',['../getting_started.html#autotoc_md401',1,'']]],
  ['your_20sa_201_20boot_20code_11',['2. Write Your SA-1 Boot Code',['../tutorial_sa1.html#autotoc_md298',1,'']]]
];
