var searchData=
[
  ['ram_0',['RAM',['../examples_graphics_effects_gradient_colors.html#autotoc_md1161',1,'CGRAM (Color Generator RAM)'],['../memory_map.html#autotoc_md625',1,'CGRAM (Color RAM)'],['../examples_audio_snesmod_music.html#autotoc_md769',1,'SPC RAM']]],
  ['ram_20—_20the_20mailbox_1',['I-RAM — The Mailbox',['../tutorial_sa1.html#autotoc_md307',1,'']]],
  ['ram_20_242116_20_242119_2',['Video RAM ($2116-$2119)',['../memory_map.html#autotoc_md623',1,'']]],
  ['ram_20_247e_3a0000_20_247f_3affff_3',['Work RAM ($7E:0000 - $7F:FFFF)',['../memory_map.html#autotoc_md622',1,'']]],
  ['ram_20buffer_20pattern_4',['3. ROM is Read-Only (The RAM Buffer Pattern)',['../examples_games_breakout.html#autotoc_md876',1,'']]],
  ['ram_20layout_20convention_5',['I-RAM Layout Convention',['../tutorial_sa1.html#autotoc_md315',1,'']]],
  ['rand_20in_20games_6',['Using rand() in Games',['../examples_basics_random.html#autotoc_md848',1,'']]],
  ['random_20numbers_7',['Random Numbers',['../examples_basics_random.html',1,'examples_basics']]],
  ['raw_20apu_20path_20no_20snesmod_8',['The raw APU path (no snesmod)',['../tutorial_audio.html#autotoc_md112',1,'']]],
  ['rdnmi_20nmi_20status_9',['$4210 - RDNMI (NMI Status)',['../registers.html#autotoc_md697',1,'']]],
  ['re_20generating_20assets_10',['Re-generating assets',['../examples_games_shmup_1942.html#autotoc_md955',1,'']]],
  ['read_11',['Auto-Joypad Read',['../examples_input_two_players.html#autotoc_md1474',1,'']]],
  ['read_20mouse_20update_20cursor_12',['4. Main Loop: Read Mouse, Update Cursor',['../examples_input_mouse.html#autotoc_md1414',1,'']]],
  ['read_20only_20the_20ram_20buffer_20pattern_13',['3. ROM is Read-Only (The RAM Buffer Pattern)',['../examples_games_breakout.html#autotoc_md876',1,'']]],
  ['read_20results_14',['$4218-$421F - JOY1-4 (Auto-Read Results)',['../registers.html#autotoc_md716',1,'']]],
  ['read_20timing_15',['🟡 Hardware multiplier read timing',['../tutorial_math.html#autotoc_md266',1,'']]],
  ['reading_16',['Reading',['../examples_graphics_backgrounds_continuous_scroll.html#autotoc_md970',1,'4. Input Reading'],['../tutorial_sa1.html#autotoc_md324',1,'Further Reading'],['../tutorial_superfx.html#autotoc_md394',1,'Further Reading'],['../memory_map.html#autotoc_md633',1,'Further Reading'],['../hardware_overview.html#autotoc_md664',1,'Further Reading'],['../registers.html#autotoc_md720',1,'Further Reading']]],
  ['reading_20both_20controllers_17',['Reading Both Controllers',['../examples_input_two_players.html#autotoc_md1447',1,'']]],
  ['reading_20controller_202_18',['Reading Controller 2',['../tutorial_input.html#autotoc_md238',1,'']]],
  ['reading_20controllers_19',['Reading Controllers',['../tutorial_input.html#autotoc_md236',1,'']]],
  ['reading_20tilemap_20data_20',['Reading Tilemap Data',['../tutorial_collision.html#autotoc_md122',1,'']]],
  ['reading_20two_20controllers_21',['Reading Two Controllers',['../examples_input_two_players.html#autotoc_md1445',1,'']]],
  ['recipe_201_20—_20inspect_20the_20machine_20at_20a_20point_20in_20time_22',['Recipe 1 — Inspect the machine at a point in time',['../tutorial_debugging.html#autotoc_md156',1,'']]],
  ['recipe_202_20—_20who_20writes_20this_20variable_23',['Recipe 2 — &quot;Who writes this variable?&quot;',['../tutorial_debugging.html#autotoc_md157',1,'']]],
  ['recipe_203_20—_20break_20at_20a_20function_24',['Recipe 3 — Break at a function',['../tutorial_debugging.html#autotoc_md158',1,'']]],
  ['recipe_204_20—_20sprite_20oam_20debugging_20shadow_20buffer_20vs_20hardware_25',['Recipe 4 — Sprite/OAM debugging (shadow buffer vs hardware)',['../tutorial_debugging.html#autotoc_md159',1,'']]],
  ['recipe_205_20—_20poke_20and_20observe_26',['Recipe 5 — Poke and observe',['../tutorial_debugging.html#autotoc_md160',1,'']]],
  ['recipe_206_20—_20temporal_20artefacts_20flicker_20page_20flip_20desync_27',['Recipe 6 — Temporal artefacts (flicker, page-flip desync)',['../tutorial_debugging.html#autotoc_md161',1,'']]],
  ['recommended_28',['Recommended',['../tutorial_input.html#autotoc_md237',1,'Direct Register Access (Recommended)'],['../tutorial_animation.html#autotoc_md71',1,'Manual Counter (Recommended)'],['../snes_graphics_guide.html#autotoc_md497',1,'Mode 1 Setup (Recommended)'],['../tutorial_audio.html#autotoc_md96',1,'SNESMOD (Recommended)'],['../tutorial_animation.html#autotoc_md68',1,'The anim Module (Recommended)'],['../examples_audio_snesmod_music.html#autotoc_md758',1,'Using OpenMPT (Recommended)']]],
  ['recommended_20layout_20mode_201_29',['Recommended Layout (Mode 1)',['../snes_graphics_guide.html#autotoc_md515',1,'']]],
  ['recommended_20workflow_30',['Recommended Workflow',['../snes_graphics_guide.html#autotoc_md525',1,'']]],
  ['rect_20pointers_31',['AABB Collision with Rect Pointers',['../examples_basics_collision_demo.html#autotoc_md829',1,'']]],
  ['rect_20type_32',['The Rect Type',['../tutorial_collision.html#autotoc_md116',1,'']]],
  ['rectangle_33',['Rectangle',['../examples_graphics_effects_transparent_window.html#autotoc_md1286',1,'HDMA Rectangle'],['../tutorial_collision.html#autotoc_md120',1,'Point-vs-Rectangle']]],
  ['rectangular_20shapes_20with_20hdma_34',['Making Non-Rectangular Shapes with HDMA',['../examples_graphics_effects_window.html#autotoc_md1297',1,'']]],
  ['reference_35',['Reference',['../index.html#autotoc_md5',1,'API Reference'],['../index.html#autotoc_md3',1,'Hardware Reference'],['../snes_graphics_guide.html#autotoc_md532',1,'Quick Reference'],['../snes_sound_guide.html#autotoc_md580',1,'Quick Reference'],['../hardware_overview.html#autotoc_md654',1,'Quick Reference'],['../examples_graphics.html#autotoc_md1312',1,'Quick Reference'],['../registers_8h.html#autotoc_md52',1,'Reference'],['../registers.html',1,'SNES Hardware Register Reference'],['../examples_games_breakout.html#autotoc_md894',1,'Technical Reference'],['../examples_games_likemario.html#autotoc_md920',1,'Technical Reference'],['../examples_graphics_backgrounds_continuous_scroll.html#autotoc_md981',1,'Technical Reference'],['../examples_graphics_effects_hdma_wave.html#autotoc_md1195',1,'Technical Reference'],['../examples_input_superscope.html#autotoc_md1436',1,'Technical Reference'],['../examples_text_hello_world.html#autotoc_md1610',1,'Technical Reference']]],
  ['references_36',['Example References',['../tutorial_animation.html#autotoc_md92',1,'']]],
  ['regions_37',['Key Memory Regions',['../memory_map.html#autotoc_md621',1,'']]],
  ['register_38',['Register',['../examples_graphics_effects_parallax_scrolling.html#autotoc_md1246',1,'BG1HOFS ($210D) &amp;ndash; Write-Twice Register'],['../examples_graphics_effects_fading.html#autotoc_md1121',1,'INIDISP Register']]],
  ['register_20_242101_39',['Register $2101',['../examples_graphics_sprites_metasprite.html#autotoc_md1352',1,'OBJ Size Modes (Register $2101)'],['../examples_graphics_sprites_object_size.html#autotoc_md1368',1,'OBJSEL Register ($2101)']]],
  ['register_20_242106_40',['Mosaic Register ($2106)',['../examples_graphics_effects_mosaic.html#autotoc_md1232',1,'']]],
  ['register_20_242123_41',['W12SEL Register ($2123)',['../examples_graphics_effects_window.html#autotoc_md1302',1,'']]],
  ['register_20access_20recommended_42',['Direct Register Access (Recommended)',['../tutorial_input.html#autotoc_md237',1,'']]],
  ['register_20acts_20strange_43',['When the window register acts strange',['../tutorial_window.html#autotoc_md398',1,'']]],
  ['register_20cheat_20sheet_44',['Register Cheat Sheet',['../snes_graphics_guide.html#autotoc_md533',1,'']]],
  ['register_20documentation_45',['Register Documentation',['../code_style.html#autotoc_md485',1,'']]],
  ['register_20fidelity_20vs_20the_20original_46',['Register fidelity vs the original',['../examples_audio_speech_synth.html#autotoc_md815',1,'Register fidelity vs the original'],['../examples_graphics_effects_gradient_9bit.html#autotoc_md1149',1,'Register fidelity vs the original'],['../examples_graphics_effects_hicolor_1792.html#autotoc_md1202',1,'Register fidelity vs the original'],['../examples_graphics_effects_hicolor_hires.html#autotoc_md1208',1,'Register fidelity vs the original'],['../examples_graphics_effects_hires_text.html#autotoc_md1212',1,'Register fidelity vs the original'],['../examples_graphics_effects_mode7_perspective_rotate.html#autotoc_md1218',1,'Register fidelity vs the original'],['../examples_graphics_effects_window_multi_hdma.html#autotoc_md1308',1,'Register fidelity vs the original']]],
  ['register_20macros_47',['OpenSNES Register Macros',['../registers.html#autotoc_md718',1,'']]],
  ['register_20object_20types_20in_20assembly_48',['2. Register Object Types in Assembly',['../examples_games_mapandobjects.html#autotoc_md931',1,'']]],
  ['register_20reference_49',['SNES Hardware Register Reference',['../registers.html',1,'index']]],
  ['register_20sequencing_50',['🟠 Double-write register sequencing',['../tutorial_mode7.html#autotoc_md285',1,'']]],
  ['register_20sequencing_20during_20hdma_51',['🟡 Boundary register sequencing during HDMA',['../tutorial_window.html#autotoc_md411',1,'']]],
  ['register_20x5_52',['ADSR1 Register (x5)',['../snes_sound_guide.html#autotoc_md555',1,'']]],
  ['register_20x6_53',['ADSR2 Register (x6)',['../snes_sound_guide.html#autotoc_md556',1,'']]],
  ['registers_54',['Registers',['../registers.html#autotoc_md681',1,'$210D-$2114 - BGnHOFS/BGnVOFS (Scroll Registers)'],['../examples_graphics_backgrounds.html#autotoc_md1107',1,'BG Scroll Registers'],['../examples_input_two_players.html#autotoc_md1446',1,'Controller Registers'],['../snes_sound_guide.html#autotoc_md545',1,'DSP Registers'],['../snes_sound_guide.html#autotoc_md547',1,'Global Registers'],['../tutorial_input.html#autotoc_md244',1,'Hardware Registers'],['../registers.html#autotoc_md715',1,'Joypad Registers'],['../oam.html#autotoc_md642',1,'OAM Registers'],['../snes_sound_guide.html#autotoc_md541',1,'Registers'],['../snes_graphics_guide.html#autotoc_md516',1,'VRAM Address Registers']]],
  ['registers_55',['registers',['../tutorial_hdma.html#autotoc_md210',1,'The four channel registers'],['../tutorial_mode7.html#autotoc_md273',1,'The matrix and the registers']]],
  ['registers_20_242100_20_24213f_56',['Registers $2100 $213F',['../memory_map.html#autotoc_md626',1,'PPU Registers ($2100-$213F)'],['../registers.html#autotoc_md668',1,'PPU Registers ($2100-$213F)']]],
  ['registers_20_242200_20_24230e_57',['SA-1 Registers ($2200-$230E)',['../registers.html#autotoc_md722',1,'']]],
  ['registers_20_243000_20_24303f_58',['SuperFX / GSU Registers ($3000-$303F)',['../registers.html#autotoc_md724',1,'']]],
  ['registers_20_244200_20_24421f_59',['CPU Registers ($4200-$421F)',['../registers.html#autotoc_md693',1,'']]],
  ['registers_20_244200_20_2444ff_60',['CPU Registers ($4200-$44FF)',['../memory_map.html#autotoc_md627',1,'']]],
  ['registers_20_244300_20_24437f_61',['DMA Registers ($4300-$437F)',['../registers.html#autotoc_md707',1,'']]],
  ['registers_20_2443x0_20_2443xf_62',['DMA Registers ($43x0-$43xF)',['../memory_map.html#autotoc_md628',1,'']]],
  ['registers_20for_20fast_20transfers_63',['DMA Registers (for fast transfers)',['../snes_graphics_guide.html#autotoc_md534',1,'']]],
  ['registers_20require_20repeat_20mode_64',['IMPORTANT: Scroll Registers Require Repeat Mode',['../hdma_8h.html#autotoc_md33',1,'']]],
  ['registers_20x_20voice_200_207_65',['Per-Voice Registers (x = voice 0-7)',['../snes_sound_guide.html#autotoc_md546',1,'']]],
  ['registration_66',['Assembly Bank Byte Registration',['../examples_maps_slopemario.html#autotoc_md1512',1,'']]],
  ['related_20examples_67',['Related examples',['../examples_graphics_effects_hdma_helpers.html#autotoc_md1169',1,'']]],
  ['relative_20sprite_20positioning_68',['Camera-Relative Sprite Positioning',['../examples_maps_mapscroll.html#autotoc_md1494',1,'']]],
  ['release_20policy_69',['Branching and release policy',['../contributing.html#autotoc_md1649',1,'']]],
  ['reload_20between_20states_70',['VRAM Reload Between States',['../tutorial_game_states.html#autotoc_md186',1,'']]],
  ['rendering_71',['PLOT Bitmap Rendering',['../tutorial_superfx.html#autotoc_md389',1,'']]],
  ['rendering_20on_20the_20snes_72',['Text Rendering on the SNES',['../examples_text_text_test.html#autotoc_md1621',1,'']]],
  ['rep_20sep_73',['Explicit &lt;span class=&quot;tt&quot;&gt;.ACCU&lt;/span&gt; After Every &lt;span class=&quot;tt&quot;&gt;rep&lt;/span&gt;/&lt;span class=&quot;tt&quot;&gt;sep&lt;/span&gt;',['../tutorial_sa1.html#autotoc_md320',1,'']]],
  ['repeat_20mode_74',['Repeat Mode',['../hdma_8h.html#autotoc_md33',1,'IMPORTANT: Scroll Registers Require Repeat Mode'],['../examples_graphics_effects_gradient_colors.html#autotoc_md1163',1,'Non-Repeat vs Repeat Mode']]],
  ['repeat_20mode_75',['🟠 HDMA on &lt;span class=&quot;tt&quot;&gt;WH0&lt;/span&gt;/&lt;span class=&quot;tt&quot;&gt;WH1&lt;/span&gt; requires repeat mode',['../tutorial_window.html#autotoc_md407',1,'']]],
  ['repeat_20mode_20discipline_20matters_76',['🟡 Repeat-mode discipline matters',['../tutorial_hdma.html#autotoc_md229',1,'']]],
  ['repeat_20vs_20repeat_20mode_77',['Non-Repeat vs Repeat Mode',['../examples_graphics_effects_gradient_colors.html#autotoc_md1163',1,'']]],
  ['repointing_20as_20animation_20—_20examples_20graphics_20effects_20hdma_5fwave_5ftable_78',['Table repointing as animation — &lt;span class=&quot;tt&quot;&gt;examples/graphics/effects/hdma_wave_table&lt;/span&gt;',['../tutorial_hdma.html#autotoc_md222',1,'']]],
  ['reporting_20bugs_79',['Reporting Bugs',['../troubleshooting.html#autotoc_md608',1,'Reporting Bugs'],['../contributing.html#autotoc_md1645',1,'Reporting Bugs']]],
  ['repository_20not_20found_20or_20empty_20compiler_20folder_80',['&quot;fatal: repository not found&quot; or empty compiler folder',['../getting_started.html#autotoc_md437',1,'']]],
  ['request_20rules_81',['Pull Request Rules',['../contributing.html#autotoc_md1650',1,'']]],
  ['require_20repeat_20mode_82',['IMPORTANT: Scroll Registers Require Repeat Mode',['../hdma_8h.html#autotoc_md33',1,'']]],
  ['required_83',['Struct Pattern (Required)',['../examples_input_two_players.html#autotoc_md1450',1,'']]],
  ['requirement_84',['Requirement',['../sram_8h.html#autotoc_md63',1,'ROM Header Requirement'],['../dma_8h.html#autotoc_md24',1,'VBlank Timing Requirement']]],
  ['requirements_85',['Requirements',['../snes_graphics_guide.html#autotoc_md523',1,'Asset Requirements'],['../snes_sound_guide.html#autotoc_md569',1,'Asset Requirements']]],
  ['requires_20no_20special_20timing_86',['🟠 SRAM access requires no special timing',['../tutorial_sram.html#autotoc_md369',1,'']]],
  ['requires_20repeat_20mode_87',['🟠 HDMA on &lt;span class=&quot;tt&quot;&gt;WH0&lt;/span&gt;/&lt;span class=&quot;tt&quot;&gt;WH1&lt;/span&gt; requires repeat mode',['../tutorial_window.html#autotoc_md407',1,'']]],
  ['res_20512×256_20background_88',['Mode 5 — Hi-Res 512×256 Background',['../examples_graphics_backgrounds_mode5.html',1,'examples_graphics_backgrounds']]],
  ['res_20and_20interlace_20modes_205_206_20setini_89',['Hi-res and interlace (Modes 5/6, SETINI)',['../tutorial_graphics.html#autotoc_md207',1,'']]],
  ['res_20text_20—_20bg_20mode_205_20interlace_20512_20×_20448_90',['Hi-res text — BG Mode 5 + interlace (512 × 448)',['../examples_graphics_effects_hires_text.html',1,'examples_graphics_effects']]],
  ['reserved_20for_20oam_20dma_91',['🔴 Channel 7 is reserved for OAM DMA',['../tutorial_hdma.html#autotoc_md227',1,'']]],
  ['reset_20by_20consoleinit_92',['🟡 Mosaic state is not reset by &lt;span class=&quot;tt&quot;&gt;consoleInit&lt;/span&gt;',['../tutorial_mosaic.html#autotoc_md302',1,'']]],
  ['resolution_93',['Resolution',['../hardware_overview.html#autotoc_md656',1,'']]],
  ['resolved_20size_94',['One Draw Function, Engine-Resolved Size',['../tutorial_animation.html#autotoc_md86',1,'']]],
  ['resources_95',['Resources',['../snes_graphics_guide.html#autotoc_md527',1,'Tools &amp;amp; Resources'],['../snes_sound_guide.html#autotoc_md574',1,'Tools &amp;amp; Resources']]],
  ['response_20patterns_96',['Collision Response Patterns',['../tutorial_collision.html#autotoc_md127',1,'']]],
  ['restart_20game_20over_20tetris_97',['Restart Game Over (Tetris)',['../tutorial_game_states.html#autotoc_md193',1,'']]],
  ['result_98',['🟡 Sin/cos LUTs are unsigned-angle, signed-result',['../tutorial_math.html#autotoc_md267',1,'']]],
  ['results_99',['$4218-$421F - JOY1-4 (Auto-Read Results)',['../registers.html#autotoc_md716',1,'']]],
  ['returns_200_20on_20divide_20by_20zero_100',['🟠 &lt;span class=&quot;tt&quot;&gt;fixDiv&lt;/span&gt; returns 0 on divide-by-zero',['../tutorial_math.html#autotoc_md264',1,'']]],
  ['reveal_20—_20examples_20graphics_20effects_20window_101',['Animated triangle reveal — &lt;span class=&quot;tt&quot;&gt;examples/graphics/effects/window&lt;/span&gt;',['../tutorial_window.html#autotoc_md404',1,'']]],
  ['review_102',['Code Review',['../contributing.html#autotoc_md1657',1,'']]],
  ['review_20checklist_103',['Self-review checklist',['../contributing.html#autotoc_md1656',1,'']]],
  ['rgb_20channel_20split_20blend_104',['&quot;3840 colors&quot; — RGB channel-split blend',['../examples_graphics_effects_hicolor_blend.html',1,'examples_graphics_effects']]],
  ['right_20is_20an_20empty_20window_105',['&lt;span class=&quot;tt&quot;&gt;left &amp;gt; right&lt;/span&gt; is an &quot;empty&quot; window',['../tutorial_window.html#autotoc_md399',1,'']]],
  ['risc_20bitmap_203d_106',['SuperFX / GSU (custom RISC, bitmap + 3D)',['../learning_path.html#autotoc_md450',1,'']]],
  ['roadmap_20status_107',['Roadmap status',['../examples_games_shmup_1942.html#autotoc_md950',1,'']]],
  ['rom_108',['ROM',['../getting_started.html#autotoc_md421',1,'A4. Run Your First ROM'],['../getting_started.html#autotoc_md439',1,'Black screen when running ROM'],['../examples_audio_snesmod_music.html#autotoc_md768',1,'ROM']]],
  ['rom_20header_109',['2. ROM header',['../tutorial_sram.html#autotoc_md359',1,'']]],
  ['rom_20header_20requirement_110',['ROM Header Requirement',['../sram_8h.html#autotoc_md63',1,'']]],
  ['rom_20is_20read_20only_20the_20ram_20buffer_20pattern_111',['3. ROM is Read-Only (The RAM Buffer Pattern)',['../examples_games_breakout.html#autotoc_md876',1,'']]],
  ['rom_20loads_20but_20screen_20is_20black_112',['ROM loads but screen is black',['../troubleshooting.html#autotoc_md592',1,'']]],
  ['rom_20runs_20but_20crashes_20after_20a_20few_20seconds_113',['ROM runs but crashes after a few seconds',['../troubleshooting.html#autotoc_md593',1,'']]],
  ['rom_20table_20lookups_20with_20lda_20l_20table_20x_114',['ROM Table Lookups with &lt;span class=&quot;tt&quot;&gt;lda.l table,x&lt;/span&gt;',['../tutorial_sa1.html#autotoc_md318',1,'']]],
  ['rom_20too_20large_20or_20linker_20errors_20about_20size_115',['&quot;ROM too large&quot; or linker errors about size',['../troubleshooting.html#autotoc_md602',1,'']]],
  ['rotating_20perspective_116',['Per-scanline matrix: rotating perspective',['../tutorial_mode7.html#autotoc_md291',1,'']]],
  ['rotating_20perspective_20—_20the_20full_20matrix_20per_20scanline_117',['Mode 7 rotating perspective — the full matrix, per scanline',['../examples_graphics_effects_mode7_perspective_rotate.html',1,'examples_graphics_effects']]],
  ['rotation_20and_20scaling_118',['Mode 7 -- Rotation and Scaling',['../examples_graphics_backgrounds_mode7.html',1,'examples_graphics_backgrounds']]],
  ['rotation_20around_20a_20point_119',['Rotation around a point',['../tutorial_math.html#autotoc_md257',1,'']]],
  ['rotation_20scaling_20—_20examples_20graphics_20backgrounds_20mode7_120',['Basic rotation + scaling — &lt;span class=&quot;tt&quot;&gt;examples/graphics/backgrounds/mode7&lt;/span&gt;',['../tutorial_mode7.html#autotoc_md280',1,'']]],
  ['rpg_20—_20an_20rpg_20template_20driven_20by_20a_20tiled_20map_121',['rpg — an RPG template driven by a Tiled map',['../examples_games_rpg.html',1,'examples_games']]],
  ['rpg_20template_20driven_20by_20a_20tiled_20map_122',['rpg — an RPG template driven by a Tiled map',['../examples_games_rpg.html',1,'examples_games']]],
  ['rpix_20after_20plot_20loops_123',['3. RPIX After PLOT Loops',['../tutorial_superfx.html#autotoc_md387',1,'']]],
  ['rule_20to_20make_20target_20common_20mk_124',['&quot;OPENSNES not defined&quot; or &quot;No rule to make target &apos;common.mk&apos;&quot;',['../troubleshooting.html#autotoc_md585',1,'']]],
  ['rules_125',['Rules',['../tutorial_game_states.html#autotoc_md190',1,'Pause Design Rules'],['../contributing.html#autotoc_md1650',1,'Pull Request Rules'],['../tutorial_superfx.html#autotoc_md384',1,'SuperFX Assembly Rules']]],
  ['run_126',['Run',['../examples_audio_snesmod_music.html#autotoc_md763',1,'Build &amp;amp; Run'],['../examples_audio_snesmod_music_hirom.html#autotoc_md791',1,'Build &amp;amp; Run'],['../examples_audio_snesmod_music_large.html#autotoc_md795',1,'Build &amp;amp; Run'],['../examples_audio_snesmod_sfx.html#autotoc_md799',1,'Build &amp;amp; Run'],['../examples_basics_collision_demo.html#autotoc_md824',1,'Build &amp;amp; Run'],['../examples_basics_random.html#autotoc_md850',1,'Build &amp;amp; Run'],['../examples_basics_timer.html#autotoc_md868',1,'Build &amp;amp; Run'],['../examples_games_breakout.html#autotoc_md870',1,'Build &amp;amp; Run'],['../examples_games_likemario.html#autotoc_md898',1,'Build &amp;amp; Run'],['../examples_games_mapandobjects.html#autotoc_md936',1,'Build &amp;amp; Run'],['../examples_graphics_backgrounds_continuous_scroll.html#autotoc_md963',1,'Build &amp;amp; Run'],['../examples_graphics_backgrounds_mixed_scroll.html#autotoc_md997',1,'Build &amp;amp; Run'],['../examples_graphics_backgrounds_mode1.html#autotoc_md1022',1,'Build &amp;amp; Run'],['../examples_graphics_backgrounds_mode1_bg3_priority.html#autotoc_md1040',1,'Build &amp;amp; Run'],['../examples_graphics_backgrounds_mode1_lz77.html#autotoc_md1065',1,'Build &amp;amp; Run'],['../examples_graphics_backgrounds_mode7.html#autotoc_md1078',1,'Build &amp;amp; Run'],['../examples_graphics_backgrounds_mode7_perspective.html#autotoc_md1094',1,'Build &amp;amp; Run'],['../examples_graphics_effects_fading.html#autotoc_md1132',1,'Build &amp;amp; Run'],['../examples_graphics_effects_gradient_colors.html#autotoc_md1155',1,'Build &amp;amp; Run'],['../examples_graphics_effects_hdma_wave.html#autotoc_md1175',1,'Build &amp;amp; Run'],['../examples_graphics_effects_mosaic.html#autotoc_md1226',1,'Build &amp;amp; Run'],['../examples_graphics_effects_parallax_scrolling.html#autotoc_md1239',1,'Build &amp;amp; Run'],['../examples_graphics_effects_superfx_3d.html#autotoc_md1260',1,'Build &amp;amp; Run'],['../examples_graphics_effects_transparency.html#autotoc_md1265',1,'Build &amp;amp; Run'],['../examples_graphics_effects_transparent_window.html#autotoc_md1282',1,'Build &amp;amp; Run'],['../examples_graphics_effects_window.html#autotoc_md1294',1,'Build &amp;amp; Run'],['../examples_graphics_sprites_animated_sprite.html#autotoc_md1319',1,'Build &amp;amp; Run'],['../examples_graphics_sprites_dynamic_metasprite.html#autotoc_md1331',1,'Build &amp;amp; Run'],['../examples_graphics_sprites_dynamic_sprite.html#autotoc_md1338',1,'Build &amp;amp; Run'],['../examples_graphics_sprites_metasprite.html#autotoc_md1358',1,'Build &amp;amp; Run'],['../examples_graphics_sprites_object_size.html#autotoc_md1361',1,'Build &amp;amp; Run'],['../examples_graphics_sprites_simple_sprite.html#autotoc_md1383',1,'Build &amp;amp; Run'],['../examples_input_controller.html#autotoc_md1403',1,'Build &amp;amp; Run'],['../examples_input_mouse.html#autotoc_md1417',1,'Build &amp;amp; Run'],['../examples_input_superscope.html#autotoc_md1425',1,'Build &amp;amp; Run'],['../examples_input_two_players.html#autotoc_md1463',1,'Build &amp;amp; Run'],['../examples_maps_dynamic_map.html#autotoc_md1489',1,'Build &amp;amp; Run'],['../examples_maps_mapscroll.html#autotoc_md1497',1,'Build &amp;amp; Run'],['../examples_maps_slopemario.html#autotoc_md1516',1,'Build &amp;amp; Run'],['../examples_maps_tiled.html#autotoc_md1525',1,'Build &amp;amp; Run'],['../examples_memory_hirom_demo.html#autotoc_md1530',1,'Build &amp;amp; Run'],['../examples_memory_sa1_hello.html#autotoc_md1547',1,'Build &amp;amp; Run'],['../examples_memory_sa1_starfield.html#autotoc_md1551',1,'Build &amp;amp; Run'],['../examples_memory_save_game.html#autotoc_md1558',1,'Build &amp;amp; Run'],['../examples_memory_superfx_hello.html#autotoc_md1573',1,'Build &amp;amp; Run'],['../examples_text_hello_world.html#autotoc_md1588',1,'Build &amp;amp; Run'],['../examples_text_text_test.html#autotoc_md1632',1,'Build &amp;amp; Run']]],
  ['run_20tests_127',['B3. Run Tests',['../getting_started.html#autotoc_md430',1,'']]],
  ['run_20your_20first_20rom_128',['A4. Run Your First ROM',['../getting_started.html#autotoc_md421',1,'']]],
  ['running_129',['Running',['../examples.html#autotoc_md1585',1,'']]],
  ['running_20counter_130',['Pattern 2: Free-Running Counter',['../tutorial_sa1.html#autotoc_md314',1,'']]],
  ['running_20rom_131',['Black screen when running ROM',['../getting_started.html#autotoc_md439',1,'']]],
  ['runs_20after_20windowing_132',['🟡 Colour math runs after windowing',['../tutorial_colormath.html#autotoc_md150',1,'']]],
  ['runs_20but_20crashes_20after_20a_20few_20seconds_133',['ROM runs but crashes after a few seconds',['../troubleshooting.html#autotoc_md593',1,'']]],
  ['runtime_134',['runtime',['../examples_graphics_effects_gradient_colors.html#autotoc_md1159',1,'3. Toggle at runtime'],['../examples_audio_apu_switch.html',1,'apu_switch — hot-swapping APU programs at runtime']]],
  ['runtime_20communication_135',['Runtime Communication',['../snes_sound_guide.html#autotoc_md567',1,'']]],
  ['runtime_20issues_20black_20screen_20crash_136',['Runtime Issues (Black Screen / Crash)',['../troubleshooting.html#autotoc_md591',1,'']]]
];
