var searchData=
[
  ['race_20in_20nmi_20caught_20at_20build_20time_0',['🟢 WRAM data port &lt;span class=&quot;tt&quot;&gt;$2180–$2183&lt;/span&gt; race in NMI (caught at build time)',['../KNOWN_LIMITATIONS.html#autotoc_md-wram-data-port-21802183-race-in-nmi-caught-at-build-time',1,'']]],
  ['ram_1',['RAM',['../examples_hdma_gradient_colors.html#cgram-color-generator-ram',1,'CGRAM (Color Generator RAM)'],['../memory_map.html#cgram-color-ram',1,'CGRAM (Color RAM)'],['../examples_audio_snesmod_music.html#spc-ram',1,'SPC RAM']]],
  ['ram_20—_20the_20mailbox_2',['I-RAM — The Mailbox',['../tutorial_sa1.html#i-ram--the-mailbox',1,'']]],
  ['ram_20_242116_20_242119_3',['Video RAM ($2116-$2119)',['../memory_map.html#video-ram-2116-2119',1,'']]],
  ['ram_20_247e_3a0000_20_247f_3affff_4',['Work RAM ($7E:0000 - $7F:FFFF)',['../memory_map.html#work-ram-7e0000---7fffff',1,'']]],
  ['ram_20bands_5',['The two RAM bands',['../tutorial_far_ram.html#the-two-ram-bands',1,'']]],
  ['ram_20buffer_20not_20on_20the_20screen_6',['Text lands in a RAM buffer, not on the screen',['../tutorial_text.html#text-lands-in-a-ram-buffer-not-on-the-screen',1,'']]],
  ['ram_20buffer_20pattern_7',['3. ROM is Read-Only (The RAM Buffer Pattern)',['../examples_games_breakout.html#autotoc_md3-rom-is-read-only-the-ram-buffer-pattern',1,'']]],
  ['ram_20carried_20a_20rom_20bank_20fixed_202026_2009_2020_8',['🟢 HiROM: every C pointer to RAM carried a ROM bank (fixed 2026-09-20)',['../KNOWN_LIMITATIONS.html#autotoc_md-hirom-every-c-pointer-to-ram-carried-a-rom-bank-fixed-2026-09-20',1,'']]],
  ['ram_20layout_20convention_9',['I-RAM Layout Convention',['../tutorial_sa1.html#i-ram-layout-convention',1,'']]],
  ['ram_20lives_20below_20_242000_20far_20is_20the_20way_20above_20it_10',['🟡 Plain C RAM lives below $2000; &lt;span class=&quot;tt&quot;&gt;FAR&lt;/span&gt; is the way above it',['../KNOWN_LIMITATIONS.html#autotoc_md-plain-c-ram-lives-below-2000-far-is-the-way-above-it',1,'']]],
  ['ram_20tutorial_20—_20far_20objects_20beyond_20the_208_20kb_20band_11',['Far RAM Tutorial — FAR objects beyond the 8 KB band',['../tutorial_far_ram.html',1,'index']]],
  ['ramp_20instead_20of_20zeros_20fixed_202026_2009_2015_12',['🟢 &lt;span class=&quot;tt&quot;&gt;sramClear()&lt;/span&gt; wrote a byte ramp instead of zeros (fixed 2026-09-15)',['../KNOWN_LIMITATIONS.html#autotoc_md-sramclear-wrote-a-byte-ramp-instead-of-zeros-fixed-2026-09-15',1,'']]],
  ['random_20numbers_13',['Random Numbers',['../examples_basics_random.html',1,'examples_basics']]],
  ['range_3a_20the_20game_20logic_20commands_14',['Distance and Range: the game-logic commands',['../tutorial_dsp1.html#distance-and-range-the-game-logic-commands',1,'']]],
  ['raster_15',['raster',['../examples_hdma.html',1,'HDMA &amp; raster'],['../examples_by_category.html#hdma--raster',1,'HDMA &amp;amp; raster']]],
  ['raster_20stream_20cannot_20be_20resynced_20—_20let_20the_20lib_20close_20it_16',['🟡 A Raster stream cannot be &quot;resynced&quot; — let the lib close it',['../tutorial_dsp1.html#autotoc_md-a-raster-stream-cannot-be-resynced--let-the-lib-close-it',1,'']]],
  ['raw_20apu_20path_20no_20snesmod_17',['The raw APU path (no snesmod)',['../tutorial_audio.html#the-raw-apu-path-no-snesmod',1,'']]],
  ['rdnmi_20nmi_20status_18',['$4210 - RDNMI (NMI Status)',['../registers.html#autotoc_md4210---rdnmi-nmi-status',1,'']]],
  ['re_20generating_20assets_19',['Re-generating assets',['../examples_games_shmup_1942.html#re-generating-assets',1,'']]],
  ['reaching_20an_20object_20you_20are_20not_20currently_20updating_20',['Reaching an object you are not currently updating',['../tutorial_object.html#reaching-an-object-you-are-not-currently-updating',1,'']]],
  ['read_21',['Auto-Joypad Read',['../examples_input_two_players.html#auto-joypad-read',1,'']]],
  ['read_20mouse_20update_20cursor_22',['4. Main Loop: Read Mouse, Update Cursor',['../examples_input_mouse.html#autotoc_md4-main-loop-read-mouse-update-cursor',1,'']]],
  ['read_20only_20the_20ram_20buffer_20pattern_23',['3. ROM is Read-Only (The RAM Buffer Pattern)',['../examples_games_breakout.html#autotoc_md3-rom-is-read-only-the-ram-buffer-pattern',1,'']]],
  ['read_20results_24',['$4218-$421F - JOY1-4 (Auto-Read Results)',['../registers.html#autotoc_md4218-421f---joy1-4-auto-read-results',1,'']]],
  ['read_20timing_25',['🟡 Hardware multiplier read timing',['../tutorial_math.html#autotoc_md-hardware-multiplier-read-timing',1,'']]],
  ['reading_26',['Reading',['../examples_scrolling_continuous_scroll.html#autotoc_md4-input-reading',1,'4. Input Reading'],['../tutorial_sa1.html#further-reading',1,'Further Reading'],['../tutorial_superfx.html#further-reading-1',1,'Further Reading'],['../memory_map.html#further-reading-2',1,'Further Reading'],['../hardware_overview.html#further-reading-3',1,'Further Reading'],['../registers.html#further-reading-4',1,'Further Reading']]],
  ['reading_20both_20controllers_27',['Reading Both Controllers',['../examples_input_two_players.html#reading-both-controllers',1,'']]],
  ['reading_20controller_202_28',['Reading Controller 2',['../tutorial_input.html#reading-controller-2',1,'']]],
  ['reading_20controllers_29',['Reading Controllers',['../tutorial_input.html#reading-controllers',1,'']]],
  ['reading_20tilemap_20data_30',['Reading Tilemap Data',['../tutorial_collision.html#reading-tilemap-data',1,'']]],
  ['reading_20two_20controllers_31',['Reading Two Controllers',['../examples_input_two_players.html#reading-two-controllers',1,'']]],
  ['reads_20what_32',['Collision: which routine reads what',['../tutorial_object.html#collision-which-routine-reads-what',1,'']]],
  ['real_20hardware_33',['Game feel: juice on real hardware',['../craft_game_feel.html',1,'craft']]],
  ['recipe_201_20—_20inspect_20the_20machine_20at_20a_20point_20in_20time_34',['Recipe 1 — Inspect the machine at a point in time',['../tutorial_debugging.html#recipe-1--inspect-the-machine-at-a-point-in-time',1,'']]],
  ['recipe_202_20—_20who_20writes_20this_20variable_35',['Recipe 2 — &quot;Who writes this variable?&quot;',['../tutorial_debugging.html#recipe-2--who-writes-this-variable',1,'']]],
  ['recipe_203_20—_20break_20at_20a_20function_36',['Recipe 3 — Break at a function',['../tutorial_debugging.html#recipe-3--break-at-a-function',1,'']]],
  ['recipe_204_20—_20sprite_20oam_20debugging_20shadow_20buffer_20vs_20hardware_37',['Recipe 4 — Sprite/OAM debugging (shadow buffer vs hardware)',['../tutorial_debugging.html#recipe-4--spriteoam-debugging-shadow-buffer-vs-hardware',1,'']]],
  ['recipe_205_20—_20poke_20and_20observe_38',['Recipe 5 — Poke and observe',['../tutorial_debugging.html#recipe-5--poke-and-observe',1,'']]],
  ['recipe_206_20—_20temporal_20artefacts_20flicker_20page_20flip_20desync_39',['Recipe 6 — Temporal artefacts (flicker, page-flip desync)',['../tutorial_debugging.html#recipe-6--temporal-artefacts-flicker-page-flip-desync',1,'']]],
  ['recipe_207_20—_20the_20rom_20tells_20you_20itself_40',['Recipe 7 — the ROM tells you itself',['../tutorial_debugging.html#recipe-7--the-rom-tells-you-itself',1,'']]],
  ['recolour_20a_20whole_20scene_20at_20once_41',['shadow_tint — recolour a whole scene at once',['../examples_color_shadow_tint.html',1,'examples_color']]],
  ['recommended_42',['Recommended',['../tutorial_input.html#direct-register-access-recommended',1,'Direct Register Access (Recommended)'],['../tutorial_animation.html#manual-counter-recommended',1,'Manual Counter (Recommended)'],['../snes_graphics_guide.html#mode-1-setup-recommended',1,'Mode 1 Setup (Recommended)'],['../tutorial_audio.html#snesmod-recommended',1,'SNESMOD (Recommended)'],['../tutorial_animation.html#the-anim-module-recommended',1,'The anim Module (Recommended)'],['../examples_audio_snesmod_music.html#using-openmpt-recommended',1,'Using OpenMPT (Recommended)']]],
  ['recommended_20—_20scene_20module_43',['The scene stack (recommended) — &lt;span class=&quot;tt&quot;&gt;scene&lt;/span&gt; module',['../tutorial_game_states.html#the-scene-stack-recommended--scene-module',1,'']]],
  ['recommended_20layout_20mode_201_44',['Recommended Layout (Mode 1)',['../snes_graphics_guide.html#recommended-layout-mode-1',1,'']]],
  ['recommended_20workflow_45',['Recommended Workflow',['../snes_graphics_guide.html#recommended-workflow',1,'']]],
  ['rect_20pointers_46',['AABB Collision with Rect Pointers',['../examples_basics_collision_demo.html#aabb-collision-with-rect-pointers',1,'']]],
  ['rect_20type_47',['The Rect Type',['../tutorial_collision.html#the-rect-type',1,'']]],
  ['rectangle_48',['Rectangle',['../examples_windows_transparent_window.html#hdma-rectangle',1,'HDMA Rectangle'],['../tutorial_collision.html#point-vs-rectangle',1,'Point-vs-Rectangle']]],
  ['rectangular_20shapes_20with_20hdma_49',['Making Non-Rectangular Shapes with HDMA',['../examples_windows_window.html#making-non-rectangular-shapes-with-hdma',1,'']]],
  ['reference_50',['Reference',['../index.html#api-reference',1,'API Reference'],['../index.html#hardware-reference',1,'Hardware Reference'],['../snes_graphics_guide.html#quick-reference',1,'Quick Reference'],['../snes_sound_guide.html#quick-reference-1',1,'Quick Reference'],['../hardware_overview.html#quick-reference-2',1,'Quick Reference'],['../registers_8h.html#reference',1,'Reference'],['../registers.html',1,'SNES Hardware Register Reference'],['../examples_fundamentals_text_glyphs.html#technical-reference',1,'Technical Reference'],['../examples_games_breakout.html#technical-reference-1',1,'Technical Reference'],['../examples_games_likemario.html#technical-reference-2',1,'Technical Reference'],['../examples_hdma_hdma_wave.html#technical-reference-3',1,'Technical Reference'],['../examples_input_superscope.html#technical-reference-4',1,'Technical Reference'],['../examples_scrolling_continuous_scroll.html#technical-reference-5',1,'Technical Reference']]],
  ['reference_20—_20oam_20in_20one_20screen_51',['Reference — OAM in one screen',['../examples_sprites.html#reference--oam-in-one-screen',1,'']]],
  ['reference_20pinned_20v1_2024_200_52',['luna — command reference (pinned v1.24.0)',['../tools_luna.html',1,'tools']]],
  ['references_53',['Example References',['../tutorial_animation.html#example-references',1,'']]],
  ['references_20we_20cite_54',['The hardware references we cite',['../craft.html#the-hardware-references-we-cite',1,'']]],
  ['refresh_55',['🟡 A screen-edge crossing forces a full sprite refresh',['../tutorial_object.html#autotoc_md-a-screen-edge-crossing-forces-a-full-sprite-refresh',1,'']]],
  ['refresh_20pass_56',['The sprite refresh pass',['../tutorial_object.html#the-sprite-refresh-pass',1,'']]],
  ['refused_57',['refused',['../KNOWN_LIMITATIONS.html#autotoc_md-inline-assembly-is-refused',1,'🟡 Inline assembly is refused'],['../KNOWN_LIMITATIONS.html#autotoc_md-struct-parameters-struct-returns-and-struct-assignment-by-value-are-refused',1,'🟡 Struct parameters, struct returns and struct assignment by value are refused'],['../KNOWN_LIMITATIONS.html#autotoc_md-variadic-functions-are-refused',1,'🟡 Variadic functions are refused']]],
  ['refused_20since_202026_2009_2021_58',['🟢 &lt;span class=&quot;tt&quot;&gt;SRAM_SIZE&lt;/span&gt; mismatch between Makefile and code — refused since 2026-09-21',['../tutorial_sram.html#autotoc_md-sram_size-mismatch-between-makefile-and-code--refused-since-2026-09-21',1,'']]],
  ['refuses_59',['Step 3 — constructs cc65816 refuses',['../migrating_pvsneslib.html#step-3--constructs-cc65816-refuses',1,'']]],
  ['regions_60',['Key Memory Regions',['../memory_map.html#key-memory-regions',1,'']]],
  ['register_61',['Register',['../examples_scrolling_parallax_scroll.html#bg1hofs-210d----write-twice-register',1,'BG1HOFS ($210D) &amp;ndash; Write-Twice Register'],['../examples_transitions_fading.html#inidisp-register',1,'INIDISP Register']]],
  ['register_62',['register',['../tutorial_window.html#autotoc_md-repeat-vs-non-repeat-on-wh0wh1--pick-by-data-shape-not-by-register',1,'🟡 Repeat vs non-repeat on &lt;span class=&quot;tt&quot;&gt;WH0&lt;/span&gt;/&lt;span class=&quot;tt&quot;&gt;WH1&lt;/span&gt; — pick by data shape, not by register'],['../hdma_8h.html#which-mode-for-which-register',1,'Which mode for which register']]],
  ['register_20_242101_63',['Register $2101',['../examples_sprites_metasprite.html#obj-size-modes-register-2101',1,'OBJ Size Modes (Register $2101)'],['../examples_sprites_sprite_sizes.html#objsel-register-2101',1,'OBJSEL Register ($2101)']]],
  ['register_20_242106_64',['Mosaic Register ($2106)',['../examples_transitions_mosaic.html#mosaic-register-2106',1,'']]],
  ['register_20_242123_65',['W12SEL Register ($2123)',['../examples_windows_window.html#w12sel-register-2123',1,'']]],
  ['register_20access_20recommended_66',['Direct Register Access (Recommended)',['../tutorial_input.html#direct-register-access-recommended',1,'']]],
  ['register_20acts_20strange_67',['When the window register acts strange',['../tutorial_window.html#when-the-window-register-acts-strange',1,'']]],
  ['register_20cheat_20sheet_68',['Register Cheat Sheet',['../snes_graphics_guide.html#register-cheat-sheet',1,'']]],
  ['register_20documentation_69',['Register Documentation',['../code_style.html#register-documentation',1,'']]],
  ['register_20fidelity_20vs_20the_20original_70',['Register fidelity vs the original',['../examples_audio_speech_synth.html#register-fidelity-vs-the-original',1,'Register fidelity vs the original'],['../examples_backgrounds_mode5_hires.html#register-fidelity-vs-the-original-1',1,'Register fidelity vs the original'],['../examples_color_gradient_9bit.html#register-fidelity-vs-the-original-2',1,'Register fidelity vs the original'],['../examples_color_hicolor_1792.html#register-fidelity-vs-the-original-3',1,'Register fidelity vs the original'],['../examples_mode7_perspective_rotate.html#register-fidelity-vs-the-original-4',1,'Register fidelity vs the original'],['../examples_windows_window_multi_hdma.html#register-fidelity-vs-the-original-5',1,'Register fidelity vs the original']]],
  ['register_20macros_71',['OpenSNES Register Macros',['../registers.html#opensnes-register-macros',1,'']]],
  ['register_20object_20types_20in_20assembly_72',['2. Register Object Types in Assembly',['../examples_games_mapandobjects.html#autotoc_md2-register-object-types-in-assembly',1,'']]],
  ['register_20reference_73',['SNES Hardware Register Reference',['../registers.html',1,'index']]],
  ['register_20sequencing_74',['🟠 Double-write register sequencing',['../tutorial_mode7.html#autotoc_md-double-write-register-sequencing',1,'']]],
  ['register_20sequencing_20during_20hdma_75',['🟡 Boundary register sequencing during HDMA',['../tutorial_window.html#autotoc_md-boundary-register-sequencing-during-hdma',1,'']]],
  ['register_20x5_76',['ADSR1 Register (x5)',['../snes_sound_guide.html#adsr1-register-x5',1,'']]],
  ['register_20x6_77',['ADSR2 Register (x6)',['../snes_sound_guide.html#adsr2-register-x6',1,'']]],
  ['registered_20callbacks_20jumped_20into_20nowhere_20—_20fixed_202026_2009_2019_78',['🟢 A type with no registered callbacks jumped into nowhere — fixed 2026-09-19',['../tutorial_object.html#autotoc_md-a-type-with-no-registered-callbacks-jumped-into-nowhere--fixed-2026-09-19',1,'']]],
  ['registering_20a_20type_79',['Registering a type',['../tutorial_object.html#registering-a-type',1,'']]],
  ['registers_80',['Registers',['../registers.html#autotoc_md210d-2114---bgnhofsbgnvofs-scroll-registers',1,'$210D-$2114 - BGnHOFS/BGnVOFS (Scroll Registers)'],['../examples_input_two_players.html#controller-registers',1,'Controller Registers'],['../snes_sound_guide.html#dsp-registers',1,'DSP Registers'],['../snes_sound_guide.html#global-registers',1,'Global Registers'],['../tutorial_input.html#hardware-registers',1,'Hardware Registers'],['../registers.html#joypad-registers',1,'Joypad Registers'],['../oam.html#oam-registers',1,'OAM Registers'],['../snes_graphics_guide.html#vram-address-registers',1,'VRAM Address Registers']]],
  ['registers_81',['registers',['../snes_sound_guide.html#spc700-registers',1,'SPC700 registers'],['../tutorial_hdma.html#the-four-channel-registers',1,'The four channel registers'],['../tutorial_mode7.html#the-matrix-and-the-registers',1,'The matrix and the registers']]],
  ['registers_20_242100_20_24213f_82',['Registers $2100 $213F',['../memory_map.html#ppu-registers-2100-213f',1,'PPU Registers ($2100-$213F)'],['../registers.html#ppu-registers-2100-213f-1',1,'PPU Registers ($2100-$213F)']]],
  ['registers_20_242200_20_24230e_83',['SA-1 Registers ($2200-$230E)',['../registers.html#sa-1-registers-2200-230e',1,'']]],
  ['registers_20_243000_20_24303f_84',['SuperFX / GSU Registers ($3000-$303F)',['../registers.html#superfx--gsu-registers-3000-303f',1,'']]],
  ['registers_20_244200_20_24421f_85',['CPU Registers ($4200-$421F)',['../registers.html#cpu-registers-4200-421f',1,'']]],
  ['registers_20_244200_20_2444ff_86',['CPU Registers ($4200-$44FF)',['../memory_map.html#cpu-registers-4200-44ff',1,'']]],
  ['registers_20_244300_20_24437f_87',['DMA Registers ($4300-$437F)',['../registers.html#dma-registers-4300-437f',1,'']]],
  ['registers_20_2443x0_20_2443xf_88',['DMA Registers ($43x0-$43xF)',['../memory_map.html#dma-registers-43x0-43xf',1,'']]],
  ['registers_20for_20fast_20transfers_89',['DMA Registers (for fast transfers)',['../snes_graphics_guide.html#dma-registers-for-fast-transfers',1,'']]],
  ['registers_20share_20one_20write_20twice_20latch_90',['🟡 BG1 scroll and the Mode 7 registers share one write-twice latch',['../tutorial_mode7.html#autotoc_md-bg1-scroll-and-the-mode-7-registers-share-one-write-twice-latch',1,'']]],
  ['registers_20x_20voice_200_207_91',['Per-Voice Registers (x = voice 0-7)',['../snes_sound_guide.html#per-voice-registers-x--voice-0-7',1,'']]],
  ['registration_92',['Assembly Bank Byte Registration',['../examples_maps_slope_collision.html#assembly-bank-byte-registration',1,'']]],
  ['related_20examples_93',['Related examples',['../examples_hdma_hdma_helpers.html#related-examples',1,'']]],
  ['relative_20sprite_20positioning_94',['Camera-Relative Sprite Positioning',['../examples_maps_map_scroll.html#camera-relative-sprite-positioning',1,'']]],
  ['release_20policy_95',['Branching and release policy',['../contributing.html#branching-and-release-policy',1,'']]],
  ['reload_20between_20states_96',['VRAM Reload Between States',['../tutorial_game_states.html#vram-reload-between-states',1,'']]],
  ['reloads_20the_20workspace_97',['What reloads the workspace',['../tutorial_object.html#what-reloads-the-workspace',1,'']]],
  ['removing_20objects_98',['Removing objects',['../tutorial_object.html#removing-objects',1,'']]],
  ['rendering_99',['PLOT Bitmap Rendering',['../tutorial_superfx.html#plot-bitmap-rendering',1,'']]],
  ['rep_20sep_100',['Explicit &lt;span class=&quot;tt&quot;&gt;.ACCU&lt;/span&gt; After Every &lt;span class=&quot;tt&quot;&gt;rep&lt;/span&gt;/&lt;span class=&quot;tt&quot;&gt;sep&lt;/span&gt;',['../tutorial_sa1.html#explicit-accu-after-every-repsep',1,'']]],
  ['repeat_20mode_101',['Non-Repeat vs Repeat Mode',['../examples_hdma_gradient_colors.html#non-repeat-vs-repeat-mode',1,'']]],
  ['repeat_20mode_20discipline_20matters_102',['🟡 Repeat-mode discipline matters',['../tutorial_hdma.html#autotoc_md-repeat-mode-discipline-matters',1,'']]],
  ['repeat_20on_20wh0_20wh1_20—_20pick_20by_20data_20shape_20not_20by_20register_103',['🟡 Repeat vs non-repeat on &lt;span class=&quot;tt&quot;&gt;WH0&lt;/span&gt;/&lt;span class=&quot;tt&quot;&gt;WH1&lt;/span&gt; — pick by data shape, not by register',['../tutorial_window.html#autotoc_md-repeat-vs-non-repeat-on-wh0wh1--pick-by-data-shape-not-by-register',1,'']]],
  ['repeat_20vs_20non_20repeat_20on_20wh0_20wh1_20—_20pick_20by_20data_20shape_20not_20by_20register_104',['🟡 Repeat vs non-repeat on &lt;span class=&quot;tt&quot;&gt;WH0&lt;/span&gt;/&lt;span class=&quot;tt&quot;&gt;WH1&lt;/span&gt; — pick by data shape, not by register',['../tutorial_window.html#autotoc_md-repeat-vs-non-repeat-on-wh0wh1--pick-by-data-shape-not-by-register',1,'']]],
  ['repeat_20vs_20repeat_20mode_105',['Non-Repeat vs Repeat Mode',['../examples_hdma_gradient_colors.html#non-repeat-vs-repeat-mode',1,'']]],
  ['replaces_106',['gameLoopRun — the boilerplate it replaces',['../tutorial_framework.html#gamelooprun--the-boilerplate-it-replaces',1,'']]],
  ['repointing_20as_20animation_20—_20examples_20hdma_20hdma_5fwave_5ftable_107',['Table repointing as animation — &lt;span class=&quot;tt&quot;&gt;examples/hdma/hdma_wave_table&lt;/span&gt;',['../tutorial_hdma.html#table-repointing-as-animation--exampleshdmahdma_wave_table',1,'']]],
  ['reporting_20bugs_108',['Reporting Bugs',['../troubleshooting.html#reporting-bugs',1,'Reporting Bugs'],['../contributing.html#reporting-bugs-1',1,'Reporting Bugs']]],
  ['repository_20not_20found_20or_20empty_20compiler_20folder_109',['&quot;fatal: repository not found&quot; or empty compiler folder',['../getting_started.html#fatal-repository-not-found-or-empty-compiler-folder',1,'']]],
  ['request_20rules_110',['Pull Request Rules',['../contributing.html#pull-request-rules',1,'']]],
  ['required_111',['Struct Pattern (Required)',['../examples_input_two_players.html#struct-pattern-required',1,'']]],
  ['requirement_112',['Requirement',['../sram_8h.html#rom-header-requirement',1,'ROM Header Requirement'],['../dma_8h.html#vblank-timing-requirement',1,'VBlank Timing Requirement']]],
  ['requirement_113',['Firmware requirement',['../examples_chips_dsp1_cube.html#firmware-requirement',1,'']]],
  ['requirements_114',['Requirements',['../snes_graphics_guide.html#asset-requirements',1,'Asset Requirements'],['../snes_sound_guide.html#asset-requirements-1',1,'Asset Requirements']]],
  ['requires_20no_20special_20timing_115',['🟠 SRAM access requires no special timing',['../tutorial_sram.html#autotoc_md-sram-access-requires-no-special-timing',1,'']]],
  ['res_20512×256_20background_116',['Mode 5 — Hi-Res 512×256 Background',['../examples_backgrounds_mode5.html',1,'examples_backgrounds']]],
  ['res_20and_20interlace_20modes_205_206_20setini_117',['Hi-res and interlace (Modes 5/6, SETINI)',['../tutorial_graphics.html#hi-res-and-interlace-modes-56-setini',1,'']]],
  ['res_20text_20—_20bg_20mode_205_20interlace_20512_20×_20448_118',['Hi-res text — BG Mode 5 + interlace (512 × 448)',['../examples_backgrounds_mode5_hires.html',1,'examples_backgrounds']]],
  ['reserved_20for_20oam_20dma_119',['🔴 Channel 7 is reserved for OAM DMA',['../tutorial_hdma.html#autotoc_md-channel-7-is-reserved-for-oam-dma',1,'']]],
  ['reset_20by_20consoleinit_120',['🟡 Mosaic state is not reset by &lt;span class=&quot;tt&quot;&gt;consoleInit&lt;/span&gt;',['../tutorial_mosaic.html#autotoc_md-mosaic-state-is-not-reset-by-consoleinit',1,'']]],
  ['resolution_121',['Resolution',['../hardware_overview.html#resolution',1,'']]],
  ['resolved_122',['🟢 Bank byte trap on &lt;span class=&quot;tt&quot;&gt;hdmaSetup&lt;/span&gt; (resolved)',['../tutorial_hdma.html#autotoc_md-bank-byte-trap-on-hdmasetup-resolved',1,'']]],
  ['resolved_20by_20the_20luna_20migration_123',['🟢 SuperFX / SA-1 chips: covered natively (resolved by the luna migration)',['../KNOWN_LIMITATIONS.html#autotoc_md-superfx--sa-1-chips-covered-natively-resolved-by-the-luna-migration',1,'']]],
  ['resolved_20size_124',['One Draw Function, Engine-Resolved Size',['../tutorial_animation.html#one-draw-function-engine-resolved-size',1,'']]],
  ['resolved_20via_20asm_20rewrite_202026_2003_2003_125',['🟢 &lt;span class=&quot;tt&quot;&gt;oamSet()&lt;/span&gt; framesize cliff — RESOLVED via ASM rewrite (2026-03-03)',['../KNOWN_LIMITATIONS.html#autotoc_md-oamset-framesize-cliff--resolved-via-asm-rewrite-2026-03-03',1,'']]],
  ['resolved_3a_20bit_201_20write_20enable_126',['🟢 SA-1 SIWP/CIWP write-protection polarity (resolved: bit=1 = write-enable)',['../KNOWN_LIMITATIONS.html#autotoc_md-sa-1-siwpciwp-write-protection-polarity-resolved-bit1--write-enable',1,'']]],
  ['resources_127',['Resources',['../snes_graphics_guide.html#tools--resources',1,'Tools &amp;amp; Resources'],['../snes_sound_guide.html#tools--resources-1',1,'Tools &amp;amp; Resources']]],
  ['response_20patterns_128',['Collision Response Patterns',['../tutorial_collision.html#collision-response-patterns',1,'']]],
  ['rest_20of_20the_20docs_129',['Where they fit with the rest of the docs',['../tools.html#where-they-fit-with-the-rest-of-the-docs',1,'']]],
  ['restart_20game_20over_20tetris_130',['Restart Game Over (Tetris)',['../tutorial_game_states.html#restart-game-over-tetris',1,'']]],
  ['result_131',['🟡 Sin/cos LUTs are unsigned-angle, signed-result',['../tutorial_math.html#autotoc_md-sincos-luts-are-unsigned-angle-signed-result',1,'']]],
  ['results_132',['$4218-$421F - JOY1-4 (Auto-Read Results)',['../registers.html#autotoc_md4218-421f---joy1-4-auto-read-results',1,'']]],
  ['results_20log_133',['Results log',['../hardware_verification.html#results-log',1,'']]],
  ['resynced_20—_20let_20the_20lib_20close_20it_134',['🟡 A Raster stream cannot be &quot;resynced&quot; — let the lib close it',['../tutorial_dsp1.html#autotoc_md-a-raster-stream-cannot-be-resynced--let-the-lib-close-it',1,'']]],
  ['returned_20garbage_20for_20no_20contact_20—_20fixed_202026_2009_2020_135',['🟢 &lt;span class=&quot;tt&quot;&gt;objCollidObj&lt;/span&gt; returned garbage for &quot;no contact&quot; — fixed 2026-09-20',['../tutorial_object.html#autotoc_md-objcollidobj-returned-garbage-for-no-contact--fixed-2026-09-20',1,'']]],
  ['returning_20long_20does_20not_20propagate_20the_20high_20half_20through_20the_20call_136',['🟡 C function returning &lt;span class=&quot;tt&quot;&gt;long&lt;/span&gt; does not propagate the high half through the call',['../KNOWN_LIMITATIONS.html#autotoc_md-c-function-returning-long-does-not-propagate-the-high-half-through-the-call',1,'']]],
  ['returns_200_20on_20divide_20by_20zero_137',['🟠 &lt;span class=&quot;tt&quot;&gt;fixDiv&lt;/span&gt; returns 0 on divide-by-zero',['../tutorial_math.html#autotoc_md-fixdiv-returns-0-on-divide-by-zero',1,'']]],
  ['returns_20and_20struct_20assignment_20by_20value_20are_20refused_138',['🟡 Struct parameters, struct returns and struct assignment by value are refused',['../KNOWN_LIMITATIONS.html#autotoc_md-struct-parameters-struct-returns-and-struct-assignment-by-value-are-refused',1,'']]],
  ['reuse_139',['Three compositions you will reuse',['../craft_backgrounds.html#three-compositions-you-will-reuse',1,'']]],
  ['reveal_20—_20examples_20windows_20window_140',['Animated triangle reveal — &lt;span class=&quot;tt&quot;&gt;examples/windows/window&lt;/span&gt;',['../tutorial_window.html#animated-triangle-reveal--exampleswindowswindow',1,'']]],
  ['reverb_141',['Echo / reverb',['../examples_audio_echo.html',1,'examples_audio']]],
  ['review_142',['Code Review',['../contributing.html#code-review',1,'']]],
  ['review_20checklist_143',['Self-review checklist',['../contributing.html#self-review-checklist',1,'']]],
  ['rewrite_202026_2003_2003_144',['🟢 &lt;span class=&quot;tt&quot;&gt;oamSet()&lt;/span&gt; framesize cliff — RESOLVED via ASM rewrite (2026-03-03)',['../KNOWN_LIMITATIONS.html#autotoc_md-oamset-framesize-cliff--resolved-via-asm-rewrite-2026-03-03',1,'']]],
  ['rgb_20artwork_20to_20indexed_20palettes_145',['img2snes — RGB artwork to indexed palettes',['../tools_img2snes.html',1,'tools']]],
  ['rgb_20channel_20split_20blend_146',['&quot;3840 colors&quot; — RGB channel-split blend',['../examples_color_hicolor_blend.html',1,'examples_color']]],
  ['right_147',['🟠 cc65816 pushes function args &lt;b&gt;LEFT-TO-RIGHT&lt;/b&gt;',['../KNOWN_LIMITATIONS.html#autotoc_md-cc65816-pushes-function-args-left-to-right',1,'']]],
  ['right_148',['Trap 1: arguments are pushed left to right',['../migrating_pvsneslib.html#trap-1-arguments-are-pushed-left-to-right',1,'']]],
  ['right_20after_20textmodeinit_149',['🟡 Sprites vanishing right after &lt;span class=&quot;tt&quot;&gt;textModeInit()&lt;/span&gt;',['../tutorial_text.html#autotoc_md-sprites-vanishing-right-after-textmodeinit',1,'']]],
  ['right_20is_20an_20empty_20window_150',['&lt;span class=&quot;tt&quot;&gt;left &amp;gt; right&lt;/span&gt; is an &quot;empty&quot; window',['../tutorial_window.html#left--right-is-an-empty-window',1,'']]],
  ['right_20moment_151',['Write it at the right moment',['../craft_camera.html#write-it-at-the-right-moment',1,'']]],
  ['rngnext_20in_20games_152',['Using rngNext() in Games',['../examples_basics_random.html#using-rngnext-in-games',1,'']]],
  ['roadmap_20status_153',['Roadmap status',['../examples_games_shmup_1942.html#roadmap-status',1,'']]],
  ['rom_154',['ROM',['../getting_started.html#a4-run-your-first-rom',1,'A4. Run Your First ROM'],['../getting_started.html#black-screen-when-running-rom',1,'Black screen when running ROM'],['../examples_audio_snesmod_music.html#rom',1,'ROM']]],
  ['rom_202026_2009_2013_155',['🟢 Five silent miscompilations found and fixed by the C-feature runtime ROM (2026-09-13)',['../KNOWN_LIMITATIONS.html#autotoc_md-five-silent-miscompilations-found-and-fixed-by-the-c-feature-runtime-rom-2026-09-13',1,'']]],
  ['rom_20bank_20fixed_202026_2009_2020_156',['🟢 HiROM: every C pointer to RAM carried a ROM bank (fixed 2026-09-20)',['../KNOWN_LIMITATIONS.html#autotoc_md-hirom-every-c-pointer-to-ram-carried-a-rom-bank-fixed-2026-09-20',1,'']]],
  ['rom_20header_157',['2. ROM header',['../tutorial_sram.html#autotoc_md2-rom-header',1,'']]],
  ['rom_20header_20requirement_158',['ROM Header Requirement',['../sram_8h.html#rom-header-requirement',1,'']]],
  ['rom_20is_20read_20only_20the_20ram_20buffer_20pattern_159',['3. ROM is Read-Only (The RAM Buffer Pattern)',['../examples_games_breakout.html#autotoc_md3-rom-is-read-only-the-ram-buffer-pattern',1,'']]],
  ['rom_20loads_20but_20screen_20is_20black_160',['ROM loads but screen is black',['../troubleshooting.html#rom-loads-but-screen-is-black',1,'']]],
  ['rom_20runs_20but_20crashes_20after_20a_20few_20seconds_161',['ROM runs but crashes after a few seconds',['../troubleshooting.html#rom-runs-but-crashes-after-a-few-seconds',1,'']]],
  ['rom_20table_20lookups_20with_20lda_20l_20table_20x_162',['ROM Table Lookups with &lt;span class=&quot;tt&quot;&gt;lda.l table,x&lt;/span&gt;',['../tutorial_sa1.html#rom-table-lookups-with-ldal-tablex',1,'']]],
  ['rom_20tells_20you_20itself_163',['Recipe 7 — the ROM tells you itself',['../tutorial_debugging.html#recipe-7--the-rom-tells-you-itself',1,'']]],
  ['rom_20too_20large_20or_20linker_20errors_20about_20size_164',['&quot;ROM too large&quot; or linker errors about size',['../troubleshooting.html#rom-too-large-or-linker-errors-about-size',1,'']]],
  ['rom_3a_20code_20only_20—_20c_20const_20data_20lives_20in_20the_20asset_20banks_20since_20127_203_165',['🟢 Bank $00 ROM: code only — C const data lives in the asset banks (since #127.3)',['../KNOWN_LIMITATIONS.html#autotoc_md-bank-00-rom-code-only--c-const-data-lives-in-the-asset-banks-since-1273',1,'']]],
  ['roms_166',['ROMs',['../tutorial_audio.html#example-roms',1,'Example ROMs'],['../tutorial_sa1.html#example-roms-1',1,'Example ROMs'],['../tutorial_superfx.html#example-roms-2',1,'Example ROMs'],['../examples_basics.html#example-roms-3',1,'Example ROMs'],['../examples_fundamentals.html#example-roms-4',1,'Example ROMs'],['../examples_games.html#example-roms-5',1,'Example ROMs'],['../examples_memory.html#example-roms-6',1,'Example ROMs'],['../examples_text.html#example-roms-7',1,'Example ROMs']]],
  ['room_167',['16.16 when 8.8 runs out of room',['../tutorial_math.html#autotoc_md1616-when-88-runs-out-of-room',1,'']]],
  ['room_20locking_168',['Clamp to the world — room-locking',['../craft_camera.html#clamp-to-the-world--room-locking',1,'']]],
  ['rotate_5fscale_169',['Basic rotation + scaling — &lt;span class=&quot;tt&quot;&gt;examples/mode7/rotate_scale&lt;/span&gt;',['../tutorial_mode7.html#basic-rotation--scaling--examplesmode7rotate_scale',1,'']]],
  ['rotating_20cgram_170',['palette_cycle — animate by rotating CGRAM',['../examples_color_palette_cycle.html',1,'examples_color']]],
  ['rotating_20perspective_171',['Per-scanline matrix: rotating perspective',['../tutorial_mode7.html#per-scanline-matrix-rotating-perspective',1,'']]],
  ['rotating_20perspective_20—_20the_20full_20matrix_20per_20scanline_172',['Mode 7 rotating perspective — the full matrix, per scanline',['../examples_mode7_perspective_rotate.html',1,'examples_mode7']]],
  ['rotation_20and_20scaling_173',['Mode 7 -- Rotation and Scaling',['../examples_mode7_rotate_scale.html',1,'examples_mode7']]],
  ['rotation_20around_20a_20point_174',['Rotation around a point',['../tutorial_math.html#rotation-around-a-point',1,'']]],
  ['rotation_20scaling_20—_20examples_20mode7_20rotate_5fscale_175',['Basic rotation + scaling — &lt;span class=&quot;tt&quot;&gt;examples/mode7/rotate_scale&lt;/span&gt;',['../tutorial_mode7.html#basic-rotation--scaling--examplesmode7rotate_scale',1,'']]],
  ['routine_176',['Choosing a routine',['../tutorial_object.html#choosing-a-routine',1,'']]],
  ['routine_20reads_20what_177',['Collision: which routine reads what',['../tutorial_object.html#collision-which-routine-reads-what',1,'']]],
  ['row_178',['How to run a row',['../hardware_verification.html#how-to-run-a-row',1,'']]],
  ['rows_179',['The rows',['../hardware_verification.html#the-rows',1,'']]],
  ['rpg_20—_20an_20rpg_20template_20driven_20by_20a_20tiled_20map_180',['rpg — an RPG template driven by a Tiled map',['../examples_games_rpg.html',1,'examples_games']]],
  ['rpg_20template_20driven_20by_20a_20tiled_20map_181',['rpg — an RPG template driven by a Tiled map',['../examples_games_rpg.html',1,'examples_games']]],
  ['rpix_20after_20plot_20loops_182',['3. RPIX After PLOT Loops',['../tutorial_superfx.html#autotoc_md3-rpix-after-plot-loops',1,'']]],
  ['rule_183',['rule',['../craft_backgrounds.html#the-one-rule',1,'The one rule'],['../craft_camera.html#the-one-rule-1',1,'The one rule'],['../craft_frame_budget.html#the-one-rule-2',1,'The one rule'],['../craft_game_feel.html#the-one-rule-3',1,'The one rule']]],
  ['rule_20to_20make_20target_20common_20mk_184',['&quot;OPENSNES not defined&quot; or &quot;No rule to make target &apos;common.mk&apos;&quot;',['../troubleshooting.html#opensnes-not-defined-or-no-rule-to-make-target-commonmk',1,'']]],
  ['rules_185',['Rules',['../tutorial_game_states.html#pause-design-rules',1,'Pause Design Rules'],['../contributing.html#pull-request-rules',1,'Pull Request Rules'],['../tutorial_superfx.html#superfx-assembly-rules',1,'SuperFX Assembly Rules']]],
  ['rules_186',['rules',['../tools_aseprite2snes.html#mapping-rules',1,'Mapping rules'],['../craft_camera.html#vertical-wants-different-rules',1,'Vertical wants different rules']]],
  ['rules_20the_20compiler_20enforces_187',['Rules the compiler enforces',['../tutorial_far_ram.html#rules-the-compiler-enforces',1,'']]],
  ['run_188',['Run',['../examples_audio_snesmod_music.html#build--run',1,'Build &amp;amp; Run'],['../examples_audio_snesmod_music_large.html#build--run-1',1,'Build &amp;amp; Run'],['../examples_audio_snesmod_sfx.html#build--run-2',1,'Build &amp;amp; Run'],['../examples_backgrounds_mode1.html#build--run-3',1,'Build &amp;amp; Run'],['../examples_backgrounds_mode1_bg3_priority.html#build--run-4',1,'Build &amp;amp; Run'],['../examples_backgrounds_mode1_lz77.html#build--run-5',1,'Build &amp;amp; Run'],['../examples_basics_collision_demo.html#build--run-7',1,'Build &amp;amp; Run'],['../examples_basics_random.html#build--run-10',1,'Build &amp;amp; Run'],['../examples_basics_timer.html#build--run-11',1,'Build &amp;amp; Run'],['../examples_chips_sa1_hello.html#build--run-12',1,'Build &amp;amp; Run'],['../examples_chips_sa1_starfield.html#build--run-13',1,'Build &amp;amp; Run'],['../examples_chips_superfx_3d.html#build--run-14',1,'Build &amp;amp; Run'],['../examples_chips_superfx_hello.html#build--run-15',1,'Build &amp;amp; Run'],['../examples_color_transparency.html#build--run-18',1,'Build &amp;amp; Run'],['../examples_fundamentals_text_glyphs.html#build--run-19',1,'Build &amp;amp; Run'],['../examples_games_breakout.html#build--run-20',1,'Build &amp;amp; Run'],['../examples_games_likemario.html#build--run-21',1,'Build &amp;amp; Run'],['../examples_games_mapandobjects.html#build--run-22',1,'Build &amp;amp; Run'],['../examples_hdma_gradient_colors.html#build--run-23',1,'Build &amp;amp; Run'],['../examples_hdma_hdma_wave.html#build--run-24',1,'Build &amp;amp; Run'],['../examples_input_controller.html#build--run-25',1,'Build &amp;amp; Run'],['../examples_input_mouse.html#build--run-26',1,'Build &amp;amp; Run'],['../examples_input_superscope.html#build--run-27',1,'Build &amp;amp; Run'],['../examples_input_two_players.html#build--run-28',1,'Build &amp;amp; Run'],['../examples_maps_dynamic_map.html#build--run-29',1,'Build &amp;amp; Run'],['../examples_maps_map_scroll.html#build--run-30',1,'Build &amp;amp; Run'],['../examples_maps_slope_collision.html#build--run-31',1,'Build &amp;amp; Run'],['../examples_maps_tiled.html#build--run-32',1,'Build &amp;amp; Run'],['../examples_memory_hirom_demo.html#build--run-33',1,'Build &amp;amp; Run'],['../examples_memory_save_game.html#build--run-34',1,'Build &amp;amp; Run'],['../examples_mode7_perspective.html#build--run-35',1,'Build &amp;amp; Run'],['../examples_mode7_rotate_scale.html#build--run-36',1,'Build &amp;amp; Run'],['../examples_scrolling_continuous_scroll.html#build--run-37',1,'Build &amp;amp; Run'],['../examples_scrolling_mixed_scroll.html#build--run-38',1,'Build &amp;amp; Run'],['../examples_scrolling_parallax_scroll.html#build--run-39',1,'Build &amp;amp; Run'],['../examples_sprites_animated_sprite.html#build--run-40',1,'Build &amp;amp; Run'],['../examples_sprites_dynamic_metasprite.html#build--run-41',1,'Build &amp;amp; Run'],['../examples_sprites_dynamic_sprite.html#build--run-42',1,'Build &amp;amp; Run'],['../examples_sprites_metasprite.html#build--run-43',1,'Build &amp;amp; Run'],['../examples_sprites_simple_sprite.html#build--run-44',1,'Build &amp;amp; Run'],['../examples_sprites_sprite_sizes.html#build--run-45',1,'Build &amp;amp; Run'],['../examples_transitions_fading.html#build--run-47',1,'Build &amp;amp; Run'],['../examples_transitions_mosaic.html#build--run-48',1,'Build &amp;amp; Run'],['../examples_windows_transparent_window.html#build--run-49',1,'Build &amp;amp; Run'],['../examples_windows_window.html#build--run-50',1,'Build &amp;amp; Run']]],
  ['run_189',['run',['../tools_luna.html#luna-run',1,'&lt;span class=&quot;tt&quot;&gt;luna run&lt;/span&gt;'],['../examples_backgrounds_mode2.html#build--run-6',1,'Build &amp;amp; run'],['../examples_basics_game_skeleton.html#build--run-8',1,'Build &amp;amp; run'],['../examples_basics_panel_hud.html#build--run-9',1,'Build &amp;amp; run'],['../examples_color_palette_cycle.html#build--run-16',1,'Build &amp;amp; run'],['../examples_color_shadow_tint.html#build--run-17',1,'Build &amp;amp; run'],['../examples_sprites_sprite_swarm.html#build--run-46',1,'Build &amp;amp; run']]],
  ['run_20a_20row_190',['How to run a row',['../hardware_verification.html#how-to-run-a-row',1,'']]],
  ['run_20before_20setscreenon_191',['🔴 &lt;span class=&quot;tt&quot;&gt;mapLoad()&lt;/span&gt; must run before &lt;span class=&quot;tt&quot;&gt;setScreenOn()&lt;/span&gt;',['../tutorial_map.html#autotoc_md-mapload-must-run-before-setscreenon',1,'']]],
  ['run_20tests_192',['B3. Run Tests',['../getting_started.html#b3-run-tests',1,'']]],
  ['run_20your_20first_20rom_193',['A4. Run Your First ROM',['../getting_started.html#a4-run-your-first-rom',1,'']]],
  ['rung_194',['Next rung',['../examples_text_print_string.html#next-rung',1,'']]],
  ['running_195',['Running',['../examples.html#running',1,'']]],
  ['running_20counter_196',['Pattern 2: Free-Running Counter',['../tutorial_sa1.html#pattern-2-free-running-counter',1,'']]],
  ['running_20rom_197',['Black screen when running ROM',['../getting_started.html#black-screen-when-running-rom',1,'']]],
  ['runs_20after_20windowing_198',['🟡 Colour math runs after windowing',['../tutorial_colormath.html#autotoc_md-colour-math-runs-after-windowing',1,'']]],
  ['runs_20but_20crashes_20after_20a_20few_20seconds_199',['ROM runs but crashes after a few seconds',['../troubleshooting.html#rom-runs-but-crashes-after-a-few-seconds',1,'']]],
  ['runs_20out_20of_20room_200',['16.16 when 8.8 runs out of room',['../tutorial_math.html#autotoc_md1616-when-88-runs-out-of-room',1,'']]],
  ['runtime_201',['runtime',['../examples_hdma_gradient_colors.html#autotoc_md3-toggle-at-runtime',1,'3. Toggle at runtime'],['../examples_audio_apu_switch.html',1,'apu_switch — hot-swapping APU programs at runtime']]],
  ['runtime_20communication_202',['Runtime Communication',['../snes_sound_guide.html#runtime-communication',1,'']]],
  ['runtime_20issues_20black_20screen_20crash_203',['Runtime Issues (Black Screen / Crash)',['../troubleshooting.html#runtime-issues-black-screen--crash',1,'']]],
  ['runtime_20rom_202026_2009_2013_204',['🟢 Five silent miscompilations found and fixed by the C-feature runtime ROM (2026-09-13)',['../KNOWN_LIMITATIONS.html#autotoc_md-five-silent-miscompilations-found-and-fixed-by-the-c-feature-runtime-rom-2026-09-13',1,'']]],
  ['runtime_20traps_205',['Runtime traps',['../KNOWN_LIMITATIONS.html#runtime-traps',1,'']]]
];
