var searchData=
[
  ['gain_20modes_20when_20adsr_20disabled_0',['GAIN Modes (when ADSR disabled)',['../snes_sound_guide.html#autotoc_md580',1,'']]],
  ['game_1',['Game',['../getting_started.html#autotoc_md447',1,'Test Your Game'],['../examples_games_breakout.html#autotoc_md912',1,'Why &lt;span class=&quot;tt&quot;&gt;ASMSRC&lt;/span&gt; for a Game?']]],
  ['game_2',['mode7_racing — an F-Zero-style mini game',['../examples_games_mode7_racing.html',1,'examples_games']]],
  ['game_20developer_3',['Path A: Game Developer',['../getting_started.html#autotoc_md439',1,'']]],
  ['game_20examples_4',['Complete Game Examples',['../examples_games.html',1,'examples']]],
  ['game_20loop_5',['Game Loop',['../examples_games_breakout.html#autotoc_md904',1,'9. The Game Loop'],['../tutorial_animation.html#autotoc_md84',1,'The Game Loop']]],
  ['game_20over_6',['Game Over',['../tutorial_game_states.html#autotoc_md192',1,'']]],
  ['game_20over_20breakout_7',['Simple Game Over (Breakout)',['../tutorial_game_states.html#autotoc_md193',1,'']]],
  ['game_20over_20tetris_8',['Restart Game Over (Tetris)',['../tutorial_game_states.html#autotoc_md194',1,'']]],
  ['game_20over_20with_20fade_9',['Game Over with Fade',['../tutorial_game_states.html#autotoc_md195',1,'']]],
  ['game_20sram_20persistence_10',['Save Game -- SRAM Persistence',['../examples_memory_save_game.html',1,'examples_memory']]],
  ['game_20state_20struct_11',['5. The Game State Struct',['../examples_graphics_backgrounds_continuous_scroll.html#autotoc_md993',1,'']]],
  ['game_20states_12',['What Are Game States?',['../tutorial_game_states.html#autotoc_md182',1,'']]],
  ['game_20states_20tutorial_13',['Game States Tutorial',['../tutorial_game_states.html',1,'index']]],
  ['gameplay_14',['Fade During Gameplay',['../examples_graphics_effects_fading.html#autotoc_md1166',1,'']]],
  ['games_15',['Games',['../examples_by_category.html#autotoc_md492',1,'Games'],['../group__examples.html#autotoc_md1664',1,'Games'],['../examples_basics_random.html#autotoc_md870',1,'Using rand() in Games'],['../examples_graphics_effects_window.html#autotoc_md1325',1,'Window Shapes in Commercial Games']]],
  ['games_20using_20mode_201_16',['Games Using Mode 1',['../examples_graphics_backgrounds_mode1.html#autotoc_md1032',1,'']]],
  ['garbled_20palette_17',['Wrong colors / garbled palette',['../troubleshooting.html#autotoc_md620',1,'']]],
  ['gate_18',['The window gate',['../tutorial_colormath.html#autotoc_md140',1,'']]],
  ['gate_20to_20colour_20math_19',['🟠 &lt;span class=&quot;tt&quot;&gt;windowEnable(window, WINDOW_MATH)&lt;/span&gt; is the gate to colour math',['../tutorial_window.html#autotoc_md430',1,'']]],
  ['gated_20spotlight_20blend_20—_20examples_20graphics_20effects_20transparent_5fwindow_20',['Window-gated spotlight blend — &lt;span class=&quot;tt&quot;&gt;examples/graphics/effects/transparent_window&lt;/span&gt;',['../tutorial_colormath.html#autotoc_md144',1,'']]],
  ['general_21',['General',['../code_style.html#autotoc_md498',1,'General'],['../code_style.html#autotoc_md505',1,'General']]],
  ['general_20dma_20enable_22',['$420B - MDMAEN (General DMA Enable)',['../registers.html#autotoc_md726',1,'']]],
  ['generated_20files_23',['Generated Files',['../examples_audio_snesmod_music.html#autotoc_md783',1,'']]],
  ['generating_20assets_24',['Re-generating assets',['../examples_games_shmup_1942.html#autotoc_md977',1,'']]],
  ['generation_25',['HDMA gradient table generation',['../tutorial_math.html#autotoc_md271',1,'']]],
  ['generator_20ram_26',['CGRAM (Color Generator RAM)',['../examples_graphics_effects_gradient_colors.html#autotoc_md1183',1,'']]],
  ['get_20an_20emulator_27',['A2. Get an Emulator',['../getting_started.html#autotoc_md441',1,'']]],
  ['getframecount_28',['Using getFrameCount()',['../tutorial_animation.html#autotoc_md72',1,'']]],
  ['getting_20help_29',['Getting Help',['../getting_started.html#autotoc_md463',1,'']]],
  ['getting_20more_20help_30',['Getting More Help',['../troubleshooting.html#autotoc_md626',1,'']]],
  ['getting_20started_31',['Getting Started',['../tutorial_sa1.html#autotoc_md329',1,'Getting Started'],['../tutorial_superfx.html#autotoc_md400',1,'Getting Started'],['../group__examples.html#autotoc_md1656',1,'Getting Started']]],
  ['getting_20started_20with_20opensnes_32',['Getting Started with OpenSNES',['../getting_started.html',1,'index']]],
  ['gfx4snes_33',['gfx4snes',['../examples_games_likemario.html#autotoc_md938',1,'Asset Conversion with gfx4snes'],['../tutorial_animation.html#autotoc_md76',1,'Converting Sprite Sheets with gfx4snes'],['../third_party.html#autotoc_md632',1,'gfx4snes'],['../tutorial_graphics.html#autotoc_md206',1,'Using gfx4snes']]],
  ['glitches_34',['Audio glitches',['../examples_audio_snesmod_music.html#autotoc_md802',1,'']]],
  ['global_20registers_35',['Global Registers',['../snes_sound_guide.html#autotoc_md569',1,'']]],
  ['go_20further_36',['Go Further',['../examples_games_breakout.html#autotoc_md908',1,'Go Further'],['../examples_games_likemario.html#autotoc_md934',1,'Go Further'],['../examples_graphics_backgrounds_continuous_scroll.html#autotoc_md997',1,'Go Further'],['../examples_graphics_effects_hdma_wave.html#autotoc_md1210',1,'Go Further'],['../examples_text_hello_world.html#autotoc_md1625',1,'Go Further']]],
  ['goes_20on_20a_20different_20layer_20above_20the_20panel_37',['🟡 Text goes on a &lt;em&gt;different&lt;/em&gt; layer, above the panel',['../tutorial_panel.html#autotoc_md323',1,'']]],
  ['going_20further_38',['Going Further',['../examples_graphics_backgrounds_mode1_bg3_priority.html#autotoc_md1073',1,'Going Further'],['../examples_graphics_backgrounds_mode7.html#autotoc_md1112',1,'Going Further'],['../examples_graphics_backgrounds_mode7_perspective.html#autotoc_md1126',1,'Going Further'],['../examples_graphics_effects_gradient_colors.html#autotoc_md1187',1,'Going Further'],['../examples_graphics_effects_mosaic.html#autotoc_md1258',1,'Going Further'],['../examples_graphics_effects_parallax_scrolling.html#autotoc_md1272',1,'Going Further'],['../examples_graphics_effects_transparent_window.html#autotoc_md1314',1,'Going Further'],['../examples_graphics_effects_window.html#autotoc_md1328',1,'Going Further'],['../examples_graphics_sprites_animated_sprite.html#autotoc_md1352',1,'Going Further'],['../examples_graphics_sprites_dynamic_sprite.html#autotoc_md1371',1,'Going Further'],['../examples_graphics_sprites_object_size.html#autotoc_md1395',1,'Going Further'],['../examples_graphics_sprites_simple_sprite.html#autotoc_md1417',1,'Going Further'],['../examples_memory_hirom_demo.html#autotoc_md1563',1,'Going Further'],['../examples_memory_save_game.html#autotoc_md1593',1,'Going Further']]],
  ['good_20first_20issues_39',['Good First Issues',['../contributing.html#autotoc_md1683',1,'']]],
  ['goomba_20example_40',['5. Enemy AI (Goomba Example)',['../examples_games_mapandobjects.html#autotoc_md956',1,'']]],
  ['gotchas_41',['Gotchas',['../tutorial_colormath.html#autotoc_md145',1,'Gotchas'],['../tutorial_dma.html#autotoc_md172',1,'Gotchas'],['../tutorial_hdma.html#autotoc_md227',1,'Gotchas'],['../tutorial_map.html#autotoc_md255',1,'Gotchas'],['../tutorial_math.html#autotoc_md272',1,'Gotchas'],['../tutorial_mode7.html#autotoc_md294',1,'Gotchas'],['../tutorial_mosaic.html#autotoc_md309',1,'Gotchas'],['../tutorial_panel.html#autotoc_md321',1,'Gotchas'],['../tutorial_sram.html#autotoc_md387',1,'Gotchas'],['../tutorial_window.html#autotoc_md428',1,'Gotchas']]],
  ['gradient_42',['HDMA Indirect Gradient',['../examples_graphics_effects_hdma_indirect_gradient.html',1,'examples_graphics_effects']]],
  ['gradient_20—_20brightness_20dithered_20backdrop_43',['&quot;9-bit&quot; gradient — brightness-dithered backdrop',['../examples_graphics_effects_gradient_9bit.html',1,'examples_graphics_effects']]],
  ['gradient_20—_20examples_20graphics_20effects_20gradient_5fcolors_44',['Static colour gradient — &lt;span class=&quot;tt&quot;&gt;examples/graphics/effects/gradient_colors&lt;/span&gt;',['../tutorial_hdma.html#autotoc_md218',1,'']]],
  ['gradient_20colors_20hdma_20color_20gradients_45',['Gradient Colors -- HDMA Color Gradients',['../examples_graphics_effects_gradient_colors.html',1,'examples_graphics_effects']]],
  ['gradient_20table_46',['2. The gradient table',['../examples_graphics_effects_gradient_colors.html#autotoc_md1180',1,'']]],
  ['gradient_20table_20generation_47',['HDMA gradient table generation',['../tutorial_math.html#autotoc_md271',1,'']]],
  ['gradient_5f9bit_48',['Two channels, one visual — &lt;span class=&quot;tt&quot;&gt;examples/graphics/effects/gradient_9bit&lt;/span&gt;',['../tutorial_hdma.html#autotoc_md225',1,'']]],
  ['gradient_5fcolors_49',['Static colour gradient — &lt;span class=&quot;tt&quot;&gt;examples/graphics/effects/gradient_colors&lt;/span&gt;',['../tutorial_hdma.html#autotoc_md218',1,'']]],
  ['gradients_50',['Gradient Colors -- HDMA Color Gradients',['../examples_graphics_effects_gradient_colors.html',1,'examples_graphics_effects']]],
  ['graphics_51',['Graphics',['../tutorial_animation.html#autotoc_md89',1,'Approach 2: Overwrite Tile Graphics'],['../tutorial_graphics.html#autotoc_md199',1,'Setting Up Graphics']]],
  ['graphics_20backgrounds_20mode7_52',['Basic rotation + scaling — &lt;span class=&quot;tt&quot;&gt;examples/graphics/backgrounds/mode7&lt;/span&gt;',['../tutorial_mode7.html#autotoc_md292',1,'']]],
  ['graphics_20backgrounds_20mode7_5fperspective_53',['F-Zero perspective via HDMA — &lt;span class=&quot;tt&quot;&gt;examples/graphics/backgrounds/mode7_perspective&lt;/span&gt;',['../tutorial_mode7.html#autotoc_md293',1,'']]],
  ['graphics_20backgrounds_20tutorial_54',['Graphics &amp;amp; Backgrounds Tutorial',['../tutorial_graphics.html',1,'index']]],
  ['graphics_20conversion_20tools_55',['Graphics Conversion Tools',['../snes_graphics_guide.html#autotoc_md550',1,'']]],
  ['graphics_20effects_20gradient_5f9bit_56',['Two channels, one visual — &lt;span class=&quot;tt&quot;&gt;examples/graphics/effects/gradient_9bit&lt;/span&gt;',['../tutorial_hdma.html#autotoc_md225',1,'']]],
  ['graphics_20effects_20gradient_5fcolors_57',['Static colour gradient — &lt;span class=&quot;tt&quot;&gt;examples/graphics/effects/gradient_colors&lt;/span&gt;',['../tutorial_hdma.html#autotoc_md218',1,'']]],
  ['graphics_20effects_20hdma_5fhelpers_58',['Helpers showcase — &lt;span class=&quot;tt&quot;&gt;examples/graphics/effects/hdma_helpers&lt;/span&gt;',['../tutorial_hdma.html#autotoc_md219',1,'']]],
  ['graphics_20effects_20hdma_5findirect_5fgradient_59',['Indirect HDMA — &lt;span class=&quot;tt&quot;&gt;examples/graphics/effects/hdma_indirect_gradient&lt;/span&gt;',['../tutorial_hdma.html#autotoc_md222',1,'']]],
  ['graphics_20effects_20hdma_5fwave_60',['Per-scanline wave distortion — &lt;span class=&quot;tt&quot;&gt;examples/graphics/effects/hdma_wave&lt;/span&gt;',['../tutorial_hdma.html#autotoc_md216',1,'']]],
  ['graphics_20effects_20hdma_5fwave_5ftable_61',['Table repointing as animation — &lt;span class=&quot;tt&quot;&gt;examples/graphics/effects/hdma_wave_table&lt;/span&gt;',['../tutorial_hdma.html#autotoc_md223',1,'']]],
  ['graphics_20effects_20mode7_5fperspective_5frotate_62',['Full Mode 7 matrix per line — &lt;span class=&quot;tt&quot;&gt;examples/graphics/effects/mode7_perspective_rotate&lt;/span&gt;',['../tutorial_hdma.html#autotoc_md224',1,'']]],
  ['graphics_20effects_20parallax_5fscrolling_63',['Parallax scrolling — &lt;span class=&quot;tt&quot;&gt;examples/graphics/effects/parallax_scrolling&lt;/span&gt;',['../tutorial_hdma.html#autotoc_md217',1,'']]],
  ['graphics_20effects_20transparency_64',['Additive cloud overlay — &lt;span class=&quot;tt&quot;&gt;examples/graphics/effects/transparency&lt;/span&gt;',['../tutorial_colormath.html#autotoc_md143',1,'']]],
  ['graphics_20effects_20transparent_5fwindow_65',['graphics effects transparent_window',['../tutorial_window.html#autotoc_md427',1,'Window + colour math — &lt;span class=&quot;tt&quot;&gt;examples/graphics/effects/transparent_window&lt;/span&gt;'],['../tutorial_hdma.html#autotoc_md220',1,'Window animation — &lt;span class=&quot;tt&quot;&gt;examples/graphics/effects/transparent_window&lt;/span&gt;'],['../tutorial_colormath.html#autotoc_md144',1,'Window-gated spotlight blend — &lt;span class=&quot;tt&quot;&gt;examples/graphics/effects/transparent_window&lt;/span&gt;']]],
  ['graphics_20effects_20window_66',['graphics effects window',['../tutorial_window.html#autotoc_md426',1,'Animated triangle reveal — &lt;span class=&quot;tt&quot;&gt;examples/graphics/effects/window&lt;/span&gt;'],['../tutorial_hdma.html#autotoc_md221',1,'Stationary window — &lt;span class=&quot;tt&quot;&gt;examples/graphics/effects/window&lt;/span&gt;']]],
  ['graphics_20effects_20window_5fmulti_5fhdma_67',['Both windows per scanline — &lt;span class=&quot;tt&quot;&gt;examples/graphics/effects/window_multi_hdma&lt;/span&gt;',['../tutorial_window.html#autotoc_md436',1,'']]],
  ['graphics_20examples_68',['Graphics Examples',['../examples_graphics.html',1,'examples']]],
  ['graphics_20fundamentals_69',['Graphics Fundamentals',['../examples.html#autotoc_md1602',1,'Level 2 &amp;ndash; Graphics Fundamentals'],['../learning_path.html#autotoc_md466',1,'Level 2: Graphics Fundamentals']]],
  ['graphics_20into_20vram_70',['1. Load sprite graphics into VRAM',['../examples_graphics_sprites_simple_sprite.html#autotoc_md1407',1,'']]],
  ['graphics_20issues_71',['Graphics Issues',['../troubleshooting.html#autotoc_md619',1,'']]],
  ['graphics_20programming_20guide_72',['SNES Graphics Programming Guide',['../snes_graphics_guide.html',1,'index']]],
  ['graphics_3a_20backgrounds_73',['Graphics: Backgrounds',['../examples_by_category.html#autotoc_md476',1,'']]],
  ['graphics_3a_20effects_74',['Graphics: Effects',['../examples_by_category.html#autotoc_md480',1,'']]],
  ['graphics_3a_20sprites_75',['Graphics: Sprites',['../examples_by_category.html#autotoc_md478',1,'']]],
  ['gravity_20in_20two_20lines_76',['5. Gravity in Two Lines',['../examples_games_likemario.html#autotoc_md928',1,'']]],
  ['grid_20based_20collision_20breakout_20bricks_77',['Grid-Based Collision (Breakout Bricks)',['../tutorial_collision.html#autotoc_md132',1,'']]],
  ['grid_20collision_20don_20t_20loop_20over_20100_20bricks_78',['5. Grid Collision (Don&apos;t Loop Over 100 Bricks)',['../examples_games_breakout.html#autotoc_md900',1,'']]],
  ['grid_20platformer_20landing_79',['Snapping to Tile Grid (Platformer Landing)',['../tutorial_collision.html#autotoc_md131',1,'']]],
  ['ground_20effect_80',['Mode 7 Perspective -- Pseudo-3D Ground Effect',['../examples_graphics_backgrounds_mode7_perspective.html',1,'examples_graphics_backgrounds']]],
  ['gsu_81',['SuperFX (GSU)',['../examples_by_category.html#autotoc_md496',1,'']]],
  ['gsu_20assembly_20code_82',['2. Write GSU Assembly Code',['../tutorial_superfx.html#autotoc_md402',1,'']]],
  ['gsu_20custom_20risc_20bitmap_203d_83',['SuperFX / GSU (custom RISC, bitmap + 3D)',['../learning_path.html#autotoc_md472',1,'']]],
  ['gsu_20loader_2065816_20asm_84',['3. Create the GSU Loader (65816 ASM)',['../tutorial_superfx.html#autotoc_md403',1,'']]],
  ['gsu_20registers_20_243000_20_24303f_85',['SuperFX / GSU Registers ($3000-$303F)',['../registers.html#autotoc_md746',1,'']]],
  ['gsu_20tutorial_86',['SuperFX (GSU) Tutorial',['../tutorial_superfx.html',1,'index']]],
  ['guide_87',['Guide',['../code_style.html',1,'OpenSNES Code Style Guide'],['../snes_graphics_guide.html',1,'SNES Graphics Programming Guide'],['../snes_sound_guide.html',1,'SNES Sound Programming Guide']]],
  ['guides_88',['Guides',['../index.html#autotoc_md1',1,'']]]
];
