var searchData=
[
  ['t_20appear_0',['Sprites don&apos;t appear',['../troubleshooting.html#autotoc_md587',1,'']]],
  ['t_20configured_1',['🟡 Don&apos;t enable channels you haven&apos;t configured',['../tutorial_hdma.html#autotoc_md226',1,'']]],
  ['t_20do_2',['What SA-1 Can&apos;t Do',['../tutorial_sa1.html#autotoc_md318',1,'']]],
  ['t_20double_20up_3',['🟠 OAM DMA is automated, don&apos;t double-up',['../tutorial_dma.html#autotoc_md172',1,'']]],
  ['t_20enable_20channels_20you_20haven_20t_20configured_4',['🟡 Don&apos;t enable channels you haven&apos;t configured',['../tutorial_hdma.html#autotoc_md226',1,'']]],
  ['t_20enough_3a_20h_20timer_20irq_20streaming_5',['When HDMA isn&apos;t enough: H-timer IRQ streaming',['../tutorial_hdma.html#autotoc_md220',1,'']]],
  ['t_20have_20to_20think_20about_20it_6',['🟠 Endianness — but you don&apos;t have to think about it',['../tutorial_sram.html#autotoc_md365',1,'']]],
  ['t_20loop_20over_20100_20bricks_7',['5. Grid Collision (Don&apos;t Loop Over 100 Bricks)',['../examples_games_breakout.html#autotoc_md851',1,'']]],
  ['table_8',['Table',['../examples_graphics_effects_parallax_scrolling.html#autotoc_md1199',1,'HDMA Scroll Table'],['../examples_graphics_effects_hdma_wave_table.html',1,'HDMA Wave Table'],['../examples_graphics_sprites_object_size.html#autotoc_md1326',1,'OAM High Table']]],
  ['table_9',['2. The gradient table',['../examples_graphics_effects_gradient_colors.html#autotoc_md1118',1,'']]],
  ['table_202_20bits_20per_20sprite_10',['Extended Table (2 bits per sprite)',['../oam.html#autotoc_md630',1,'']]],
  ['table_204_20bytes_20per_20sprite_11',['Main Table (4 bytes per sprite)',['../oam.html#autotoc_md628',1,'']]],
  ['table_20format_12',['Table Format',['../examples_graphics_effects_hdma_wave.html#autotoc_md1140',1,'2. The HDMA Table Format'],['../hdma_8h.html#autotoc_md30',1,'Table Format']]],
  ['table_20format_13',['Table format',['../tutorial_hdma.html#autotoc_md207',1,'']]],
  ['table_20generation_14',['HDMA gradient table generation',['../tutorial_math.html#autotoc_md254',1,'']]],
  ['table_20lookups_20with_20lda_20l_20table_20x_15',['ROM Table Lookups with &lt;span class=&quot;tt&quot;&gt;lda.l table,x&lt;/span&gt;',['../tutorial_sa1.html#autotoc_md313',1,'']]],
  ['table_20of_20contents_16',['Table of Contents',['../snes_graphics_guide.html#autotoc_md484',1,'Table of Contents'],['../snes_sound_guide.html#autotoc_md528',1,'Table of Contents'],['../registers.html#autotoc_md659',1,'Table of Contents']]],
  ['table_20repointing_20as_20animation_20—_20examples_20graphics_20effects_20hdma_5fwave_5ftable_17',['Table repointing as animation — &lt;span class=&quot;tt&quot;&gt;examples/graphics/effects/hdma_wave_table&lt;/span&gt;',['../tutorial_hdma.html#autotoc_md217',1,'']]],
  ['table_20x_18',['ROM Table Lookups with &lt;span class=&quot;tt&quot;&gt;lda.l table,x&lt;/span&gt;',['../tutorial_sa1.html#autotoc_md313',1,'']]],
  ['tables_19',['The Triangle Tables',['../examples_graphics_effects_window.html#autotoc_md1255',1,'']]],
  ['tables_20',['Trigonometry (sin/cos lookup tables)',['../tutorial_math.html#autotoc_md247',1,'']]],
  ['target_20branch_21',['Target branch',['../contributing.html#autotoc_md1608',1,'']]],
  ['target_20common_20mk_22',['&quot;OPENSNES not defined&quot; or &quot;No rule to make target &apos;common.mk&apos;&quot;',['../troubleshooting.html#autotoc_md578',1,'']]],
  ['target_20since_20chantier_20a1_23',['🟢 &lt;span class=&quot;tt&quot;&gt;int&lt;/span&gt; and &lt;span class=&quot;tt&quot;&gt;long&lt;/span&gt; sizes are correct on this target (since chantier A1)',['../tutorial_math.html#autotoc_md256',1,'']]],
  ['targets_20cgadd_20_242121_24',['1. HDMA targets CGADD ($2121)',['../examples_graphics_effects_gradient_colors.html#autotoc_md1117',1,'']]],
  ['technical_20notes_25',['Technical Notes',['../examples_audio_snesmod_music.html#autotoc_md763',1,'Technical Notes'],['../examples_graphics_backgrounds_mode1.html#autotoc_md995',1,'Technical Notes'],['../examples_graphics_effects_fading.html#autotoc_md1102',1,'Technical Notes'],['../examples_input_two_players.html#autotoc_md1430',1,'Technical Notes']]],
  ['technical_20reference_26',['Technical Reference',['../examples_games_breakout.html#autotoc_md867',1,'Technical Reference'],['../examples_games_likemario.html#autotoc_md893',1,'Technical Reference'],['../examples_graphics_backgrounds_continuous_scroll.html#autotoc_md944',1,'Technical Reference'],['../examples_graphics_effects_hdma_wave.html#autotoc_md1155',1,'Technical Reference'],['../examples_input_superscope.html#autotoc_md1393',1,'Technical Reference'],['../examples_text_hello_world.html#autotoc_md1567',1,'Technical Reference']]],
  ['technique_27',['Technique',['../examples_graphics_effects_parallax_scrolling.html#autotoc_md1198',1,'The Parallax Technique'],['../examples_graphics_effects_transparent_window.html#autotoc_md1241',1,'The Technique']]],
  ['temporal_20artefacts_20flicker_20page_20flip_20desync_28',['Recipe 6 — Temporal artefacts (flicker, page-flip desync)',['../tutorial_debugging.html#autotoc_md156',1,'']]],
  ['test_29',['Test',['../tutorial_collision.html#autotoc_md114',1,'Basic Overlap Test'],['../examples_text_text_test.html',1,'Text Module Test']]],
  ['test_20your_20game_30',['Test Your Game',['../getting_started.html#autotoc_md419',1,'']]],
  ['testing_31',['Testing',['../contributing.html#autotoc_md1612',1,'']]],
  ['testing_20multiple_20enemies_32',['Testing Multiple Enemies',['../tutorial_collision.html#autotoc_md115',1,'']]],
  ['tests_33',['B3. Run Tests',['../getting_started.html#autotoc_md424',1,'']]],
  ['tetris_34',['Tetris',['../tutorial_game_states.html#autotoc_md188',1,'Restart Game Over (Tetris)'],['../examples_games_tetris.html',1,'Tetris']]],
  ['text_35',['Text',['../examples_by_category.html#autotoc_md445',1,'Text'],['../examples_text.html#autotoc_md1573',1,'VRAM Layout for Text']]],
  ['text_20—_20bg_20mode_205_20interlace_20512_20×_20448_36',['Hi-res text — BG Mode 5 + interlace (512 × 448)',['../examples_graphics_effects_hires_text.html',1,'examples_graphics_effects']]],
  ['text_20and_20detect_20mouse_37',['1. Initialize Text and Detect Mouse',['../examples_input_mouse.html#autotoc_md1368',1,'']]],
  ['text_20and_20load_20font_38',['3. Initialize Text and Load Font',['../examples_text_text_test.html#autotoc_md1585',1,'']]],
  ['text_20display_39',['Text Display',['../examples_audio_snesmod_sfx.html#autotoc_md788',1,'']]],
  ['text_20display_40',['5. Text display',['../examples_memory_save_game.html#autotoc_md1521',1,'']]],
  ['text_20examples_41',['Text Examples',['../examples_text.html',1,'examples']]],
  ['text_20module_20test_42',['Text Module Test',['../examples_text_text_test.html',1,'examples_text']]],
  ['text_20on_20bg1_204bpp_20in_20mode_201_43',['1. Set up text on BG1 (4bpp in Mode 1)',['../examples_graphics_sprites_object_size.html#autotoc_md1320',1,'']]],
  ['text_20rendering_20on_20the_20snes_44',['Text Rendering on the SNES',['../examples_text_text_test.html#autotoc_md1578',1,'']]],
  ['text_20system_20bg1_45',['2. Text System (BG1)',['../examples_input_superscope.html#autotoc_md1386',1,'']]],
  ['text_20works_20on_20snes_46',['How Text Works on SNES',['../examples_text.html#autotoc_md1571',1,'']]],
  ['than_20the_20screen_47',['1. The World Is Bigger Than the Screen',['../examples_games_likemario.html#autotoc_md875',1,'']]],
  ['the_206_20size_20modes_48',['The 6 Size Modes',['../examples_graphics_sprites_object_size.html#autotoc_md1323',1,'']]],
  ['the_208_208_20fixed_20point_20format_49',['The 8.8 fixed-point format',['../tutorial_math.html#autotoc_md244',1,'']]],
  ['the_208_20transfer_20modes_50',['The 8 transfer modes',['../tutorial_dma.html#autotoc_md161',1,'']]],
  ['the_20anim_20module_20recommended_51',['The anim Module (Recommended)',['../tutorial_animation.html#autotoc_md68',1,'']]],
  ['the_20backdrop_52',['🟡 Colour-math on the backdrop',['../tutorial_colormath.html#autotoc_md144',1,'']]],
  ['the_20backdrop_20not_20a_20layer_53',['🟡 Out-of-bounds with &lt;span class=&quot;tt&quot;&gt;MODE7_TRANSPARENT&lt;/span&gt; shows the backdrop, not a layer',['../tutorial_mode7.html#autotoc_md283',1,'']]],
  ['the_20bg2_20is_20sub_20screen_20only_20trap_54',['🔴 The &quot;BG2 is sub-screen-only&quot; trap',['../tutorial_colormath.html#autotoc_md141',1,'']]],
  ['the_20build_55',['The Build',['../examples_games_breakout.html#autotoc_md861',1,'Under the Hood: The Build'],['../examples_games_likemario.html#autotoc_md887',1,'Under the Hood: The Build'],['../examples_graphics_backgrounds_continuous_scroll.html#autotoc_md940',1,'Under the Hood: The Build'],['../examples_graphics_effects_hdma_wave.html#autotoc_md1150',1,'Under the Hood: The Build'],['../examples_input_superscope.html#autotoc_md1392',1,'Under the Hood: The Build'],['../examples_text_hello_world.html#autotoc_md1562',1,'Under the Hood: The Build']]],
  ['the_20checkerboard_20background_56',['6. The Checkerboard Background',['../examples_graphics_effects_hdma_wave.html#autotoc_md1144',1,'']]],
  ['the_20clip_20and_20ticking_57',['Selecting the Clip and Ticking',['../tutorial_animation.html#autotoc_md79',1,'']]],
  ['the_20code_20is_20identical_20to_20lorom_58',['2. The code is identical to LoROM',['../examples_memory_hirom_demo.html#autotoc_md1490',1,'']]],
  ['the_20column_20pipeline_59',['3. Streaming: The Column Pipeline',['../examples_games_likemario.html#autotoc_md877',1,'']]],
  ['the_20conversion_20macros_60',['The conversion macros',['../tutorial_math.html#autotoc_md245',1,'']]],
  ['the_20data_20lives_61',['Where the Data Lives',['../examples_graphics_effects_hdma_wave.html#autotoc_md1152',1,'']]],
  ['the_20dma_20channels_62',['The DMA channels',['../tutorial_dma.html#autotoc_md160',1,'']]],
  ['the_20dynamic_20sprite_20engine_63',['The Dynamic Sprite Engine',['../tutorial_animation.html#autotoc_md80',1,'']]],
  ['the_20dynamic_20sprite_20engine_64',['1. Initialize the dynamic sprite engine',['../examples_graphics_sprites_dynamic_sprite.html#autotoc_md1297',1,'']]],
  ['the_20exclusive_20bus_65',['The Exclusive Bus',['../tutorial_superfx.html#autotoc_md377',1,'']]],
  ['the_20four_20channel_20registers_66',['The four channel registers',['../tutorial_hdma.html#autotoc_md205',1,'']]],
  ['the_20full_20matrix_20per_20scanline_67',['Mode 7 rotating perspective — the full matrix, per scanline',['../examples_graphics_effects_mode7_perspective_rotate.html',1,'examples_graphics_effects']]],
  ['the_20game_20loop_68',['The Game Loop',['../examples_games_breakout.html#autotoc_md855',1,'9. The Game Loop'],['../tutorial_animation.html#autotoc_md84',1,'The Game Loop']]],
  ['the_20game_20state_20struct_69',['5. The Game State Struct',['../examples_graphics_backgrounds_continuous_scroll.html#autotoc_md934',1,'']]],
  ['the_20gate_20to_20colour_20math_70',['🟠 &lt;span class=&quot;tt&quot;&gt;windowEnable(window, WINDOW_MATH)&lt;/span&gt; is the gate to colour math',['../tutorial_window.html#autotoc_md402',1,'']]],
  ['the_20gradient_20table_71',['2. The gradient table',['../examples_graphics_effects_gradient_colors.html#autotoc_md1118',1,'']]],
  ['the_20gsu_20loader_2065816_20asm_72',['3. Create the GSU Loader (65816 ASM)',['../tutorial_superfx.html#autotoc_md375',1,'']]],
  ['the_20hdma_20channel_73',['4. Setting Up the HDMA Channel',['../examples_graphics_effects_hdma_wave.html#autotoc_md1142',1,'']]],
  ['the_20hdma_20table_20format_74',['2. The HDMA Table Format',['../examples_graphics_effects_hdma_wave.html#autotoc_md1140',1,'']]],
  ['the_20hood_3a_20the_20build_75',['the Hood: The Build',['../examples_games_breakout.html#autotoc_md861',1,'Under the Hood: The Build'],['../examples_games_likemario.html#autotoc_md887',1,'Under the Hood: The Build'],['../examples_graphics_backgrounds_continuous_scroll.html#autotoc_md940',1,'Under the Hood: The Build'],['../examples_graphics_effects_hdma_wave.html#autotoc_md1150',1,'Under the Hood: The Build'],['../examples_input_superscope.html#autotoc_md1392',1,'Under the Hood: The Build'],['../examples_text_hello_world.html#autotoc_md1562',1,'Under the Hood: The Build']]],
  ['the_20interleaved_20vram_20format_76',['The interleaved VRAM format',['../tutorial_mode7.html#autotoc_md269',1,'']]],
  ['the_20lib_20api_77',['The lib API',['../tutorial_colormath.html#autotoc_md136',1,'The lib API'],['../tutorial_mosaic.html#autotoc_md290',1,'The lib API'],['../tutorial_sram.html#autotoc_md354',1,'The lib API'],['../tutorial_window.html#autotoc_md396',1,'The lib API']]],
  ['the_20lib_20chantier_20b6_202026_2005_2009_78',['&lt;span class=&quot;tt&quot;&gt;atan2&lt;/span&gt; and &lt;span class=&quot;tt&quot;&gt;sqrt&lt;/span&gt; ship in the lib (chantier B6, 2026-05-09)',['../tutorial_math.html#autotoc_md263',1,'']]],
  ['the_20lib_20helpers_20and_20what_20they_20do_79',['The lib helpers and what they do',['../tutorial_mode7.html#autotoc_md273',1,'']]],
  ['the_20long_20way_80',['Manual setup (the long way)',['../getting_started.html#autotoc_md417',1,'']]],
  ['the_20machine_20at_20a_20point_20in_20time_81',['Recipe 1 — Inspect the machine at a point in time',['../tutorial_debugging.html#autotoc_md151',1,'']]],
  ['the_20mailbox_82',['I-RAM — The Mailbox',['../tutorial_sa1.html#autotoc_md302',1,'']]],
  ['the_20main_20loop_83',['7. The Main Loop',['../examples_games_likemario.html#autotoc_md881',1,'']]],
  ['the_20main_20loop_84',['Per-frame DMA in the main loop',['../tutorial_dma.html#autotoc_md165',1,'']]],
  ['the_20makefile_85',['The Makefile',['../examples_games_breakout.html#autotoc_md862',1,'The Makefile'],['../examples_games_likemario.html#autotoc_md888',1,'The Makefile'],['../examples_graphics_backgrounds_continuous_scroll.html#autotoc_md941',1,'The Makefile'],['../examples_graphics_effects_hdma_wave.html#autotoc_md1151',1,'The Makefile'],['../examples_text_hello_world.html#autotoc_md1564',1,'The Makefile']]],
  ['the_20makefile_86',['the Makefile',['../examples_memory_hirom_demo.html#autotoc_md1489',1,'1. Enable HiROM in the Makefile'],['../examples_memory_save_game.html#autotoc_md1520',1,'4. Enable SRAM in the Makefile']]],
  ['the_20map_20and_20sprite_20system_87',['1. Initialize the Map and Sprite System',['../examples_games_mapandobjects.html#autotoc_md903',1,'']]],
  ['the_20map_20engine_88',['The Map Engine',['../examples_maps_slopemario.html#autotoc_md1466',1,'']]],
  ['the_20matrix_20and_20the_20registers_89',['The matrix and the registers',['../tutorial_mode7.html#autotoc_md268',1,'']]],
  ['the_20matrix_20every_20frame_90',['3. Update the matrix every frame',['../examples_graphics_backgrounds_mode7.html#autotoc_md1045',1,'']]],
  ['the_20message_91',['6. Spelling the Message',['../examples_text_hello_world.html#autotoc_md1555',1,'']]],
  ['the_20minimum_20viable_20colour_20math_92',['The minimum viable colour math',['../tutorial_colormath.html#autotoc_md133',1,'']]],
  ['the_20minimum_20viable_20mosaic_93',['The minimum viable mosaic',['../tutorial_mosaic.html#autotoc_md288',1,'']]],
  ['the_20minimum_20viable_20save_94',['The minimum viable save',['../tutorial_sram.html#autotoc_md355',1,'']]],
  ['the_20minimum_20viable_20window_95',['The minimum viable window',['../tutorial_window.html#autotoc_md390',1,'']]],
  ['the_20nmi_20handler_96',['🟡 HDMA fires before the user callback in the NMI handler',['../tutorial_hdma.html#autotoc_md225',1,'']]],
  ['the_20oambuffer_97',['2. Set up sprites via the oambuffer',['../examples_graphics_sprites_dynamic_sprite.html#autotoc_md1298',1,'']]],
  ['the_20original_98',['the original',['../examples_graphics_effects_gradient_9bit.html#autotoc_md1109',1,'Register fidelity vs the original'],['../examples_graphics_effects_hicolor_1792.html#autotoc_md1162',1,'Register fidelity vs the original'],['../examples_graphics_effects_hires_text.html#autotoc_md1169',1,'Register fidelity vs the original'],['../examples_graphics_effects_mode7_perspective_rotate.html#autotoc_md1175',1,'Register fidelity vs the original'],['../examples_graphics_effects_window_multi_hdma.html#autotoc_md1265',1,'Register fidelity vs the original']]],
  ['the_20original_20measured_20not_20assumed_99',['the original measured not assumed',['../examples_graphics_effects_hdma_indirect_gradient.html#autotoc_md1130',1,'Fidelity to the original (measured, not assumed)'],['../examples_graphics_effects_hdma_wave_table.html#autotoc_md1157',1,'Fidelity to the original (measured, not assumed)']]],
  ['the_20parallax_20technique_100',['The Parallax Technique',['../examples_graphics_effects_parallax_scrolling.html#autotoc_md1198',1,'']]],
  ['the_20pipeline_101',['The Pipeline',['../examples_text_hello_world.html#autotoc_md1563',1,'']]],
  ['the_20pointer_102',['5. Animation = Just Move the Pointer',['../examples_graphics_effects_hdma_wave.html#autotoc_md1143',1,'']]],
  ['the_20ppu_103',['3. Setting Up the PPU',['../examples_text_hello_world.html#autotoc_md1552',1,'']]],
  ['the_20problem_104',['The Problem',['../oam.html#autotoc_md632',1,'']]],
  ['the_20ram_20buffer_20pattern_105',['3. ROM is Read-Only (The RAM Buffer Pattern)',['../examples_games_breakout.html#autotoc_md849',1,'']]],
  ['the_20rect_20type_106',['The Rect Type',['../tutorial_collision.html#autotoc_md112',1,'']]],
  ['the_20registers_107',['The matrix and the registers',['../tutorial_mode7.html#autotoc_md268',1,'']]],
  ['the_20scene_20struct_108',['The Scene struct',['../examples_basics_scene_stack.html#autotoc_md830',1,'']]],
  ['the_20screen_109',['1. The World Is Bigger Than the Screen',['../examples_games_likemario.html#autotoc_md875',1,'']]],
  ['the_20screen_20centre_110',['🟡 Centre default is the tilemap centre, not the screen centre',['../tutorial_mode7.html#autotoc_md282',1,'']]],
  ['the_20setup_20pattern_111',['The setup pattern',['../tutorial_dma.html#autotoc_md164',1,'']]],
  ['the_20shipped_20example_112',['the shipped example',['../tutorial_mosaic.html#autotoc_md291',1,'Worked pattern (the shipped example)'],['../tutorial_sram.html#autotoc_md358',1,'Worked pattern (the shipped example)']]],
  ['the_20shipped_20examples_113',['the shipped examples',['../tutorial_hdma.html#autotoc_md209',1,'Worked patterns (the shipped examples)'],['../tutorial_window.html#autotoc_md397',1,'Worked patterns (the shipped examples)']]],
  ['the_20snes_114',['the SNES',['../examples_input_controller.html#autotoc_md1356',1,'How Input Works on the SNES'],['../examples_text_text_test.html#autotoc_md1578',1,'Text Rendering on the SNES'],['../tutorial_math.html#autotoc_md243',1,'Why fixed-point on the SNES']]],
  ['the_20solution_115',['The Solution',['../oam.html#autotoc_md633',1,'']]],
  ['the_20soundbank_116',['The Soundbank',['../examples_audio_snesmod_sfx.html#autotoc_md787',1,'']]],
  ['the_20sprite_117',['4. Place the sprite',['../examples_graphics_sprites_simple_sprite.html#autotoc_md1345',1,'']]],
  ['the_20sprite_20palette_118',['2. Load the sprite palette',['../examples_graphics_sprites_simple_sprite.html#autotoc_md1343',1,'']]],
  ['the_20streaming_20pattern_119',['The Streaming Pattern',['../tutorial_scrolling.html#autotoc_md329',1,'']]],
  ['the_20technique_120',['The Technique',['../examples_graphics_effects_transparent_window.html#autotoc_md1241',1,'']]],
  ['the_20threshold_20scroll_20pattern_121',['2. The Threshold Scroll Pattern',['../examples_graphics_backgrounds_continuous_scroll.html#autotoc_md931',1,'']]],
  ['the_20tiled_20workflow_122',['The Tiled Workflow',['../examples_maps_tiled.html#autotoc_md1475',1,'']]],
  ['the_20tilemap_20centre_20not_20the_20screen_20centre_123',['🟡 Centre default is the tilemap centre, not the screen centre',['../tutorial_mode7.html#autotoc_md282',1,'']]],
  ['the_20transformation_124',['2. Initialize the transformation',['../examples_graphics_backgrounds_mode7.html#autotoc_md1044',1,'']]],
  ['the_20triangle_20tables_125',['The Triangle Tables',['../examples_graphics_effects_window.html#autotoc_md1255',1,'']]],
  ['the_20two_20shipped_20examples_126',['the two shipped examples',['../tutorial_colormath.html#autotoc_md137',1,'Worked patterns (the two shipped examples)'],['../tutorial_mode7.html#autotoc_md274',1,'Worked patterns (the two shipped examples)']]],
  ['the_20user_20callback_20in_20the_20nmi_20handler_127',['🟡 HDMA fires before the user callback in the NMI handler',['../tutorial_hdma.html#autotoc_md225',1,'']]],
  ['the_20vram_20layout_128',['2. The VRAM Layout',['../examples_games_likemario.html#autotoc_md876',1,'']]],
  ['the_20vram_20map_20—_20a_20deliberate_20overlap_129',['2. The VRAM Map — A Deliberate Overlap',['../examples_games_breakout.html#autotoc_md848',1,'']]],
  ['the_20warning_20above_20before_20using_130',['Quick Start (legacy — read the warning above before using)',['../audio_8h.html#autotoc_md11',1,'']]],
  ['the_20window_20gate_131',['The window gate',['../tutorial_colormath.html#autotoc_md135',1,'']]],
  ['the_20window_20logic_20op_20trap_132',['The window logic op trap',['../tutorial_window.html#autotoc_md395',1,'']]],
  ['the_20window_20register_20acts_20strange_133',['When the window register acts strange',['../tutorial_window.html#autotoc_md392',1,'']]],
  ['the_20world_20is_20bigger_20than_20the_20screen_134',['1. The World Is Bigger Than the Screen',['../examples_games_likemario.html#autotoc_md875',1,'']]],
  ['there_20is_20no_20printf_135',['1. There Is No printf',['../examples_text_hello_world.html#autotoc_md1550',1,'']]],
  ['these_20demonstrate_136',['What These Demonstrate',['../examples_games.html#autotoc_md911',1,'']]],
  ['these_20modules_137',['These Modules',['../examples_games_breakout.html#autotoc_md865',1,'Why These Modules?'],['../examples_graphics_backgrounds_continuous_scroll.html#autotoc_md942',1,'Why These Modules?'],['../examples_graphics_effects_hdma_wave.html#autotoc_md1153',1,'Why These Modules?'],['../examples_text_hello_world.html#autotoc_md1565',1,'Why These Modules?']]],
  ['they_20do_138',['The lib helpers and what they do',['../tutorial_mode7.html#autotoc_md273',1,'']]],
  ['think_20about_20it_139',['🟠 Endianness — but you don&apos;t have to think about it',['../tutorial_sram.html#autotoc_md365',1,'']]],
  ['third_20party_20components_140',['Third-Party Components',['../third_party.html',1,'index']]],
  ['this_20example_20demonstrates_141',['What this example demonstrates',['../basics_2fix32__orbit_2main_8c.html#autotoc_md810',1,'']]],
  ['this_20example_20does_142',['This Example Does',['../examples_audio_snesmod_music.html#autotoc_md725',1,'What This Example Does'],['../examples_graphics_backgrounds_mode1.html#autotoc_md968',1,'What This Example Does'],['../examples_graphics_effects_fading.html#autotoc_md1077',1,'What This Example Does'],['../examples_input_two_players.html#autotoc_md1398',1,'What This Example Does']]],
  ['this_20example_20shows_143',['This Example Shows',['../examples_graphics_backgrounds_mode1_bg3_priority.html#autotoc_md1001',1,'What This Example Shows'],['../examples_graphics_backgrounds_mode7.html#autotoc_md1038',1,'What This Example Shows'],['../examples_graphics_backgrounds_mode7_perspective.html#autotoc_md1054',1,'What This Example Shows'],['../examples_graphics_effects_gradient_colors.html#autotoc_md1112',1,'What This Example Shows'],['../examples_graphics_effects_mosaic.html#autotoc_md1180',1,'What This Example Shows'],['../examples_graphics_effects_parallax_scrolling.html#autotoc_md1194',1,'What This Example Shows'],['../examples_graphics_sprites_animated_sprite.html#autotoc_md1273',1,'What This Example Shows'],['../examples_graphics_sprites_dynamic_sprite.html#autotoc_md1292',1,'What This Example Shows'],['../examples_graphics_sprites_object_size.html#autotoc_md1316',1,'What This Example Shows'],['../examples_graphics_sprites_simple_sprite.html#autotoc_md1337',1,'What This Example Shows'],['../examples_memory_hirom_demo.html#autotoc_md1484',1,'What This Example Shows'],['../examples_memory_save_game.html#autotoc_md1512',1,'What This Example Shows']]],
  ['this_20port_20surfaced_144',['this port surfaced',['../examples_graphics_effects_mode7_perspective_rotate.html#autotoc_md1177',1,'Two integration lessons this port surfaced'],['../examples_graphics_effects_hicolor_1792.html#autotoc_md1164',1,'Two SDK bugs this port surfaced']]],
  ['this_20target_20since_20chantier_20a1_145',['🟢 &lt;span class=&quot;tt&quot;&gt;int&lt;/span&gt; and &lt;span class=&quot;tt&quot;&gt;long&lt;/span&gt; sizes are correct on this target (since chantier A1)',['../tutorial_math.html#autotoc_md256',1,'']]],
  ['this_20variable_146',['Recipe 2 — &quot;Who writes this variable?&quot;',['../tutorial_debugging.html#autotoc_md152',1,'']]],
  ['this_20works_20with_20one_20layer_147',['Why This Works with One Layer',['../examples_graphics_effects_parallax_scrolling.html#autotoc_md1205',1,'']]],
  ['three_20background_20layers_148',['1. Set up three background layers',['../examples_graphics_backgrounds_mode1_bg3_priority.html#autotoc_md1005',1,'']]],
  ['threshold_20scroll_20pattern_149',['2. The Threshold Scroll Pattern',['../examples_graphics_backgrounds_continuous_scroll.html#autotoc_md931',1,'']]],
  ['through_20a_150',['No &lt;span class=&quot;tt&quot;&gt;stx.l&lt;/span&gt; — Save X Through A',['../tutorial_sa1.html#autotoc_md314',1,'']]],
  ['ticking_151',['Selecting the Clip and Ticking',['../tutorial_animation.html#autotoc_md79',1,'']]],
  ['tile_20animation_152',['Background Tile Animation',['../tutorial_animation.html#autotoc_md87',1,'']]],
  ['tile_20based_20collision_153',['Tile Based Collision',['../examples_games_likemario.html#autotoc_md880',1,'6. Tile-Based Collision'],['../examples_maps.html#autotoc_md1461',1,'Tile-Based Collision']]],
  ['tile_20based_20wall_20collision_154',['Tile-Based Wall Collision',['../examples_basics_collision_demo.html#autotoc_md803',1,'']]],
  ['tile_20calculation_155',['4. Tile calculation',['../examples_graphics_sprites_animated_sprite.html#autotoc_md1281',1,'']]],
  ['tile_20collision_156',['Map Engine and Tile Collision',['../examples_games_mapandobjects.html#autotoc_md898',1,'']]],
  ['tile_20data_20address_157',['$210B-$210C - BG12NBA/BG34NBA (Tile Data Address)',['../registers.html#autotoc_md672',1,'']]],
  ['tile_20flip_158',['Exercise 3: Tile Flip',['../examples_graphics_backgrounds_mode1.html#autotoc_md992',1,'']]],
  ['tile_20format_159',['Tile Format',['../examples_text.html#autotoc_md1572',1,'2BPP Tile Format'],['../examples_graphics_backgrounds_mode1.html#autotoc_md983',1,'4bpp Tile Format']]],
  ['tile_20formats_160',['Tile Formats',['../snes_graphics_guide.html#autotoc_md495',1,'']]],
  ['tile_20graphics_161',['Approach 2: Overwrite Tile Graphics',['../tutorial_animation.html#autotoc_md89',1,'']]],
  ['tile_20grid_20platformer_20landing_162',['Snapping to Tile Grid (Platformer Landing)',['../tutorial_collision.html#autotoc_md126',1,'']]],
  ['tile_20layout_163',['Column-Major Tile Layout',['../tutorial_superfx.html#autotoc_md385',1,'']]],
  ['tile_20layout_20and_20oam_20tile_20numbers_164',['VRAM Tile Layout and OAM Tile Numbers',['../examples_graphics_sprites_metasprite.html#autotoc_md1311',1,'']]],
  ['tile_20numbering_165',['VRAM Tile Numbering',['../tutorial_animation.html#autotoc_md74',1,'']]],
  ['tile_20numbers_166',['VRAM Tile Layout and OAM Tile Numbers',['../examples_graphics_sprites_metasprite.html#autotoc_md1311',1,'']]],
  ['tile_20properties_167',['Tile Properties',['../examples_maps_tiled.html#autotoc_md1478',1,'']]],
  ['tile_20properties_20from_20a_20tilemap_20platformer_20pattern_168',['Tile Properties from a Tilemap (Platformer Pattern)',['../tutorial_collision.html#autotoc_md121',1,'']]],
  ['tile_20sizes_169',['Custom Tile Sizes',['../tutorial_collision.html#autotoc_md120',1,'']]],
  ['tiled_20map_20editor_20integration_170',['Tiled Map Editor Integration',['../examples_maps_tiled.html',1,'examples_maps']]],
  ['tiled_20workflow_171',['The Tiled Workflow',['../examples_maps_tiled.html#autotoc_md1475',1,'']]],
  ['tilemap_172',['Background Tilemap',['../registers.html#autotoc_md670',1,'']]],
  ['tilemap_20address_20size_173',['$2107-$210A - BG1SC-BG4SC (Tilemap Address/Size)',['../registers.html#autotoc_md671',1,'']]],
  ['tilemap_20centre_20not_20the_20screen_20centre_174',['🟡 Centre default is the tilemap centre, not the screen centre',['../tutorial_mode7.html#autotoc_md282',1,'']]],
  ['tilemap_20data_175',['Reading Tilemap Data',['../tutorial_collision.html#autotoc_md118',1,'']]],
  ['tilemap_20entries_176',['Approach 1: Swap Tilemap Entries',['../tutorial_animation.html#autotoc_md88',1,'']]],
  ['tilemap_20entry_202_20bytes_177',['Tilemap Entry (2 bytes)',['../examples_graphics_backgrounds.html#autotoc_md1071',1,'']]],
  ['tilemap_20for_20seamless_20wrapping_178',['64x32 Tilemap for Seamless Wrapping',['../examples_graphics_effects_parallax_scrolling.html#autotoc_md1204',1,'']]],
  ['tilemap_20format_179',['Tilemap Format',['../examples_graphics_backgrounds_mode1.html#autotoc_md981',1,'']]],
  ['tilemap_20layout_180',['SC_64x64 Tilemap Layout',['../examples_maps_dynamic_map.html#autotoc_md1440',1,'']]],
  ['tilemap_20palette_20bits_181',['Tilemap Palette Bits',['../examples_graphics_backgrounds_mode1_bg3_priority.html#autotoc_md1011',1,'']]],
  ['tilemap_20platformer_20pattern_182',['Tile Properties from a Tilemap (Platformer Pattern)',['../tutorial_collision.html#autotoc_md121',1,'']]],
  ['tilemap_20sizes_183',['Tilemap Sizes',['../snes_graphics_guide.html#autotoc_md494',1,'Tilemap Sizes'],['../examples_maps.html#autotoc_md1460',1,'Tilemap Sizes']]],
  ['tilemap_20structure_184',['Tilemap Structure',['../snes_graphics_guide.html#autotoc_md493',1,'']]],
  ['tilemap_20uncompressed_185',['3. Load Palette and Tilemap (Uncompressed)',['../examples_graphics_backgrounds_mode1_lz77.html#autotoc_md1024',1,'']]],
  ['tilemaps_186',['Tilemaps',['../examples_maps.html#autotoc_md1459',1,'Hardware Tilemaps'],['../tutorial_graphics.html#autotoc_md196',1,'Setting Up Tilemaps'],['../examples_graphics_backgrounds_mode1_lz77.html#autotoc_md1018',1,'Why Compress Tiles but Not Tilemaps?']]],
  ['tilemaps_20to_20vram_187',['2. Load Tilemaps to VRAM',['../examples_graphics_backgrounds_mixed_scroll.html#autotoc_md956',1,'']]],
  ['tiles_188',['Tiles',['../tutorial_sprites.html#autotoc_md340',1,'Loading Sprite Tiles'],['../examples_maps_dynamic_map.html#autotoc_md1439',1,'Mode 3 and 8bpp Tiles']]],
  ['tiles_20and_20palettes_189',['2. Load tiles and palettes',['../examples_graphics_backgrounds_mode1_bg3_priority.html#autotoc_md1006',1,'']]],
  ['tiles_20and_20sprites_190',['Tiles and Sprites',['../hardware_overview.html#autotoc_md653',1,'']]],
  ['tiles_20appear_20corrupted_191',['Tiles appear corrupted',['../troubleshooting.html#autotoc_md592',1,'']]],
  ['tiles_20but_20not_20tilemaps_192',['Why Compress Tiles but Not Tilemaps?',['../examples_graphics_backgrounds_mode1_lz77.html#autotoc_md1018',1,'']]],
  ['tiles_20in_20oam_193',['16x16 Tiles in OAM',['../examples_graphics_sprites_animated_sprite.html#autotoc_md1285',1,'']]],
  ['tiles_20to_20vram_194',['Tiles to VRAM',['../examples_graphics_backgrounds_mode1_lz77.html#autotoc_md1023',1,'2. Decompress Tiles to VRAM'],['../examples_text_hello_world.html#autotoc_md1553',1,'4. Uploading Tiles to VRAM'],['../tutorial_graphics.html#autotoc_md195',1,'Loading Tiles to VRAM']]],
  ['tilesets_20and_20palettes_195',['1. Load Both Tilesets and Palettes',['../examples_graphics_backgrounds_mixed_scroll.html#autotoc_md955',1,'']]],
  ['time_196',['Recipe 1 — Inspect the machine at a point in time',['../tutorial_debugging.html#autotoc_md151',1,'']]],
  ['timer_197',['Timer',['../registers.html#autotoc_md689',1,'$4207-$420A - HTIMEx/VTIMEx (IRQ Timer)'],['../examples_basics_timer.html',1,'VBlank Timer']]],
  ['timer_20irq_20streaming_198',['When HDMA isn&apos;t enough: H-timer IRQ streaming',['../tutorial_hdma.html#autotoc_md220',1,'']]],
  ['timeup_20irq_20status_199',['$4211 - TIMEUP (IRQ Status)',['../registers.html#autotoc_md691',1,'']]],
  ['timing_200',['Timing',['../tutorial_animation.html#autotoc_md70',1,'Frame Timing'],['../oam.html#autotoc_md642',1,'Timing'],['../tutorial_scrolling.html#autotoc_md331',1,'VBlank Timing']]],
  ['timing_201',['timing',['../tutorial_sram.html#autotoc_md363',1,'🟠 SRAM access requires no special timing'],['../tutorial_math.html#autotoc_md261',1,'🟡 Hardware multiplier read timing'],['../examples_graphics_sprites_animated_sprite.html#autotoc_md1280',1,'3. Animation timing']]],
  ['timing_20requirement_202',['VBlank Timing Requirement',['../dma_8h.html#autotoc_md24',1,'']]],
  ['timing_20values_203',['Timing Values',['../snes_sound_guide.html#autotoc_md550',1,'']]],
  ['tip_204',['Performance Tip',['../examples_graphics_sprites.html#autotoc_md1335',1,'']]],
  ['tips_205',['Tips',['../tutorial_collision.html#autotoc_md128',1,'Performance Tips'],['../tutorial_sprites.html#autotoc_md347',1,'Performance Tips'],['../tutorial_sa1.html#autotoc_md311',1,'SA-1 Assembly Tips'],['../tutorial_scrolling.html#autotoc_md330',1,'Streaming Tips'],['../tutorial_audio.html#autotoc_md108',1,'Tips'],['../tutorial_input.html#autotoc_md240',1,'Tips'],['../examples.html#autotoc_md1543',1,'Tips']]],
  ['tips_20tricks_206',['Tips Tricks',['../examples_games_breakout.html#autotoc_md857',1,'Tips &amp;amp; Tricks'],['../examples_games_likemario.html#autotoc_md883',1,'Tips &amp;amp; Tricks'],['../examples_graphics_backgrounds_continuous_scroll.html#autotoc_md936',1,'Tips &amp;amp; Tricks'],['../examples_graphics_effects_hdma_wave.html#autotoc_md1146',1,'Tips &amp;amp; Tricks'],['../examples_input_superscope.html#autotoc_md1391',1,'Tips &amp;amp; Tricks'],['../examples_text_hello_world.html#autotoc_md1558',1,'Tips &amp;amp; Tricks']]],
  ['title_20flow_207',['Complete Title Flow',['../tutorial_game_states.html#autotoc_md183',1,'']]],
  ['title_20screen_20implementation_208',['Title Screen Implementation',['../tutorial_game_states.html#autotoc_md182',1,'']]],
  ['tm_20main_20screen_20enable_209',['$212C - TM (Main Screen Enable)',['../registers.html#autotoc_md683',1,'']]],
  ['to_20background_20collision_210',['Sprite-to-Background Collision',['../tutorial_collision.html#autotoc_md117',1,'']]],
  ['to_20black_211',['Fade Out (Full to Black)',['../examples_graphics_effects_fading.html#autotoc_md1085',1,'']]],
  ['to_20black_20fade_20to_20white_212',['Fade-to-black / fade-to-white',['../tutorial_colormath.html#autotoc_md134',1,'']]],
  ['to_20build_213',['to Build',['../examples_basics_aim_target.html#autotoc_md794',1,'How to Build'],['../examples_basics_fix32_orbit.html#autotoc_md814',1,'How to Build'],['../examples_basics_scene_stack.html#autotoc_md833',1,'How to Build'],['../examples_graphics_effects_gradient_9bit.html#autotoc_md1110',1,'How to Build'],['../examples_graphics_effects_hdma_indirect_gradient.html#autotoc_md1132',1,'How to Build'],['../examples_graphics_effects_hdma_wave_table.html#autotoc_md1159',1,'How to Build'],['../examples_graphics_effects_hicolor_1792.html#autotoc_md1165',1,'How to Build'],['../examples_graphics_effects_hires_text.html#autotoc_md1171',1,'How to Build'],['../examples_graphics_effects_mode7_perspective_rotate.html#autotoc_md1178',1,'How to Build'],['../examples_graphics_effects_window_multi_hdma.html#autotoc_md1266',1,'How to Build']]],
  ['to_20colour_20math_214',['🟠 &lt;span class=&quot;tt&quot;&gt;windowEnable(window, WINDOW_MATH)&lt;/span&gt; is the gate to colour math',['../tutorial_window.html#autotoc_md402',1,'']]],
  ['to_20full_215',['Fade In (Black to Full)',['../examples_graphics_effects_fading.html#autotoc_md1084',1,'']]],
  ['to_20lorom_216',['2. The code is identical to LoROM',['../examples_memory_hirom_demo.html#autotoc_md1490',1,'']]],
  ['to_20make_20target_20common_20mk_217',['&quot;OPENSNES not defined&quot; or &quot;No rule to make target &apos;common.mk&apos;&quot;',['../troubleshooting.html#autotoc_md578',1,'']]],
  ['to_20observe_218',['to Observe',['../examples_basics_aim_target.html#autotoc_md793',1,'What to Observe'],['../examples_basics_fix32_orbit.html#autotoc_md813',1,'What to Observe'],['../examples_memory_sa1_starfield.html#autotoc_md1510',1,'What to Observe']]],
  ['to_20opensnes_219',['Contributing to OpenSNES',['../contributing.html',1,'index']]],
  ['to_20sprite_20collision_220',['Sprite-to-Sprite Collision',['../tutorial_collision.html#autotoc_md113',1,'']]],
  ['to_20sram_221',['2. Save to SRAM',['../examples_memory_save_game.html#autotoc_md1518',1,'']]],
  ['to_20the_20original_20measured_20not_20assumed_222',['to the original measured not assumed',['../examples_graphics_effects_hdma_indirect_gradient.html#autotoc_md1130',1,'Fidelity to the original (measured, not assumed)'],['../examples_graphics_effects_hdma_wave_table.html#autotoc_md1157',1,'Fidelity to the original (measured, not assumed)']]],
  ['to_20think_20about_20it_223',['🟠 Endianness — but you don&apos;t have to think about it',['../tutorial_sram.html#autotoc_md365',1,'']]],
  ['to_20tile_20grid_20platformer_20landing_224',['Snapping to Tile Grid (Platformer Landing)',['../tutorial_collision.html#autotoc_md126',1,'']]],
  ['to_20use_20hirom_225',['When to Use HiROM',['../examples_memory_hirom_demo.html#autotoc_md1495',1,'']]],
  ['to_20vram_226',['to VRAM',['../examples_graphics_backgrounds_mode1_lz77.html#autotoc_md1023',1,'2. Decompress Tiles to VRAM'],['../examples_graphics_backgrounds_mixed_scroll.html#autotoc_md956',1,'2. Load Tilemaps to VRAM'],['../examples_text_hello_world.html#autotoc_md1553',1,'4. Uploading Tiles to VRAM'],['../tutorial_graphics.html#autotoc_md195',1,'Loading Tiles to VRAM']]],
  ['to_20vram_20transfer_227',['SRAM to VRAM Transfer',['../tutorial_superfx.html#autotoc_md386',1,'']]],
  ['to_20white_228',['Fade-to-black / fade-to-white',['../tutorial_colormath.html#autotoc_md134',1,'']]],
  ['today_229',['🔴 Interleaved VRAM, no &lt;span class=&quot;tt&quot;&gt;mode7LoadGraphics&lt;/span&gt; helper today',['../tutorial_mode7.html#autotoc_md279',1,'']]],
  ['toggle_20at_20runtime_230',['3. Toggle at runtime',['../examples_graphics_effects_gradient_colors.html#autotoc_md1119',1,'']]],
  ['too_20large_20or_20linker_20errors_20about_20size_231',['&quot;ROM too large&quot; or linker errors about size',['../troubleshooting.html#autotoc_md595',1,'']]],
  ['tool_232',['smconv Tool',['../tutorial_audio.html#autotoc_md103',1,'']]],
  ['tools_233',['Tools',['../snes_sound_guide.html#autotoc_md569',1,'Conversion Tools'],['../code_style.html#autotoc_md483',1,'Formatting Tools'],['../snes_graphics_guide.html#autotoc_md521',1,'Graphics Conversion Tools'],['../snes_sound_guide.html#autotoc_md568',1,'Sound Creation Tools']]],
  ['tools_20resources_234',['Tools Resources',['../snes_graphics_guide.html#autotoc_md520',1,'Tools &amp;amp; Resources'],['../snes_sound_guide.html#autotoc_md567',1,'Tools &amp;amp; Resources']]],
  ['topic_235',['By Topic',['../group__examples.html#autotoc_md1590',1,'']]],
  ['topic_20per_20pr_236',['One topic per PR',['../contributing.html#autotoc_md1609',1,'']]],
  ['topics_237',['Topics',['../examples.html#autotoc_md1539',1,'Level 4 &amp;ndash; Advanced Topics'],['../learning_path.html#autotoc_md439',1,'Level 4: Advanced Topics']]],
  ['total_238',['total',['../snes_sound_guide.html#autotoc_md564',1,'Memory Budget (64KB total)'],['../snes_graphics_guide.html#autotoc_md498',1,'OAM Structure (544 bytes total)']]],
  ['tour_239',['Lib API tour',['../tutorial_dma.html#autotoc_md166',1,'']]],
  ['tracker_20based_20music_240',['Why Tracker-Based Music?',['../examples_audio_snesmod_music.html#autotoc_md764',1,'']]],
  ['transfer_241',['SRAM to VRAM Transfer',['../tutorial_superfx.html#autotoc_md386',1,'']]],
  ['transfer_20modes_242',['Transfer modes',['../tutorial_hdma.html#autotoc_md206',1,'']]],
  ['transfer_20modes_243',['The 8 transfer modes',['../tutorial_dma.html#autotoc_md161',1,'']]],
  ['transfer_20size_244',['$43x5-$43x6 - DASxL/H (Transfer Size)',['../registers.html#autotoc_md705',1,'']]],
  ['transfers_245',['DMA Registers (for fast transfers)',['../snes_graphics_guide.html#autotoc_md527',1,'']]],
  ['transformation_246',['Affine Transformation',['../examples_graphics_backgrounds_mode7.html#autotoc_md1048',1,'']]],
  ['transformation_247',['2. Initialize the transformation',['../examples_graphics_backgrounds_mode7.html#autotoc_md1044',1,'']]],
  ['transition_20pattern_248',['Scene Transition Pattern',['../examples_graphics_effects_fading.html#autotoc_md1090',1,'']]],
  ['transitions_249',['State Transitions',['../tutorial_game_states.html#autotoc_md179',1,'']]],
  ['transitions_250',['transitions',['../examples_graphics_effects_mosaic.html#autotoc_md1187',1,'3. Combining both for transitions'],['../tutorial_mosaic.html#autotoc_md289',1,'Animated transitions']]],
  ['translation_251',['Address Translation',['../examples_memory_hirom_demo.html#autotoc_md1496',1,'']]],
  ['transparency_252',['Color Addition Transparency',['../examples_graphics_effects_transparency.html',1,'examples_graphics_effects']]],
  ['transparency_253',['Additive cloud overlay — &lt;span class=&quot;tt&quot;&gt;examples/graphics/effects/transparency&lt;/span&gt;',['../tutorial_colormath.html#autotoc_md138',1,'']]],
  ['transparent_20window_20color_20math_20hdma_254',['Transparent Window -- Color Math + HDMA',['../examples_graphics_effects_transparent_window.html',1,'examples_graphics_effects']]],
  ['transparent_5fwindow_255',['transparent_window',['../tutorial_window.html#autotoc_md399',1,'Window + colour math — &lt;span class=&quot;tt&quot;&gt;examples/graphics/effects/transparent_window&lt;/span&gt;'],['../tutorial_hdma.html#autotoc_md214',1,'Window animation — &lt;span class=&quot;tt&quot;&gt;examples/graphics/effects/transparent_window&lt;/span&gt;'],['../tutorial_colormath.html#autotoc_md139',1,'Window-gated spotlight blend — &lt;span class=&quot;tt&quot;&gt;examples/graphics/effects/transparent_window&lt;/span&gt;']]],
  ['trap_256',['trap',['../tutorial_dma.html#autotoc_md170',1,'🔴 &lt;span class=&quot;tt&quot;&gt;dmaCopyVram&lt;/span&gt; hardcodes source bank &lt;span class=&quot;tt&quot;&gt;$00&lt;/span&gt; — SUPERFREE spillover trap'],['../tutorial_colormath.html#autotoc_md141',1,'🔴 The &quot;BG2 is sub-screen-only&quot; trap'],['../tutorial_window.html#autotoc_md395',1,'The window logic op trap']]],
  ['trap_20on_20hdmasetup_257',['🔴 Bank byte trap on &lt;span class=&quot;tt&quot;&gt;hdmaSetup&lt;/span&gt;',['../tutorial_hdma.html#autotoc_md223',1,'']]],
  ['triangle_20masking_258',['Window -- HDMA Triangle Masking',['../examples_graphics_effects_window.html',1,'examples_graphics_effects']]],
  ['triangle_20reveal_20—_20examples_20graphics_20effects_20window_259',['Animated triangle reveal — &lt;span class=&quot;tt&quot;&gt;examples/graphics/effects/window&lt;/span&gt;',['../tutorial_window.html#autotoc_md398',1,'']]],
  ['triangle_20tables_260',['The Triangle Tables',['../examples_graphics_effects_window.html#autotoc_md1255',1,'']]],
  ['tricks_261',['Tricks',['../examples_games_breakout.html#autotoc_md857',1,'Tips &amp;amp; Tricks'],['../examples_games_likemario.html#autotoc_md883',1,'Tips &amp;amp; Tricks'],['../examples_graphics_backgrounds_continuous_scroll.html#autotoc_md936',1,'Tips &amp;amp; Tricks'],['../examples_graphics_effects_hdma_wave.html#autotoc_md1146',1,'Tips &amp;amp; Tricks'],['../examples_input_superscope.html#autotoc_md1391',1,'Tips &amp;amp; Tricks'],['../examples_text_hello_world.html#autotoc_md1558',1,'Tips &amp;amp; Tricks']]],
  ['trigonometry_20sin_20cos_20lookup_20tables_262',['Trigonometry (sin/cos lookup tables)',['../tutorial_math.html#autotoc_md247',1,'']]],
  ['troubleshooting_263',['Troubleshooting',['../getting_started.html#autotoc_md429',1,'']]],
  ['troubleshooting_20opensnes_264',['Troubleshooting OpenSNES',['../troubleshooting.html',1,'index']]],
  ['truncates_20fractional_20precision_265',['🔴 &lt;span class=&quot;tt&quot;&gt;fixMul&lt;/span&gt; truncates fractional precision',['../tutorial_math.html#autotoc_md258',1,'']]],
  ['ts_20sub_20screen_20enable_266',['$212D - TS (Sub Screen Enable)',['../registers.html#autotoc_md684',1,'']]],
  ['tutorial_267',['Tutorial',['../tutorial_animation.html',1,'Animation Tutorial'],['../tutorial_audio.html',1,'Audio &amp; Music Tutorial'],['../tutorial_collision.html',1,'Collision Detection Tutorial'],['../tutorial_colormath.html',1,'Colour Math Tutorial'],['../tutorial_input.html',1,'Controller Input Tutorial'],['../tutorial_dma.html',1,'DMA Tutorial'],['../tutorial_math.html',1,'Fixed-Point Math Tutorial'],['../tutorial_game_states.html',1,'Game States Tutorial'],['../tutorial_graphics.html',1,'Graphics &amp; Backgrounds Tutorial'],['../tutorial_hdma.html',1,'HDMA Tutorial'],['../tutorial_mode7.html',1,'Mode 7 Tutorial'],['../tutorial_mosaic.html',1,'Mosaic Tutorial'],['../tutorial_sa1.html',1,'SA-1 Enhancement Chip Tutorial'],['../tutorial_scrolling.html',1,'Scrolling &amp; Parallax Tutorial'],['../tutorial_sprites.html',1,'Sprites &amp; Animation Tutorial'],['../tutorial_sram.html',1,'SRAM Save Tutorial'],['../tutorial_superfx.html',1,'SuperFX (GSU) Tutorial'],['../tutorial_window.html',1,'Window Masking Tutorial']]],
  ['tutorials_268',['Tutorials',['../index.html#autotoc_md2',1,'Tutorials'],['../getting_started.html#autotoc_md428',1,'Tutorials']]],
  ['twice_20register_269',['BG1HOFS ($210D) &amp;ndash; Write-Twice Register',['../examples_graphics_effects_parallax_scrolling.html#autotoc_md1203',1,'']]],
  ['two_20camps_270',['Why two camps?',['../oam.html#autotoc_md641',1,'']]],
  ['two_20channels_20one_20visual_20—_20examples_20graphics_20effects_20gradient_5f9bit_271',['Two channels, one visual — &lt;span class=&quot;tt&quot;&gt;examples/graphics/effects/gradient_9bit&lt;/span&gt;',['../tutorial_hdma.html#autotoc_md219',1,'']]],
  ['two_20colors_20four_20bytes_272',['5. Two Colors, Four Bytes',['../examples_text_hello_world.html#autotoc_md1554',1,'']]],
  ['two_20controllers_273',['Reading Two Controllers',['../examples_input_two_players.html#autotoc_md1402',1,'']]],
  ['two_20integration_20lessons_20this_20port_20surfaced_274',['Two integration lessons this port surfaced',['../examples_graphics_effects_mode7_perspective_rotate.html#autotoc_md1177',1,'']]],
  ['two_20layers_20two_20speeds_275',['1. Two Layers, Two Speeds',['../examples_graphics_backgrounds_continuous_scroll.html#autotoc_md930',1,'']]],
  ['two_20lines_276',['5. Gravity in Two Lines',['../examples_games_likemario.html#autotoc_md879',1,'']]],
  ['two_20phase_20update_277',['Map Engine Two-Phase Update',['../examples_maps_mapscroll.html#autotoc_md1450',1,'']]],
  ['two_20player_20example_278',['Two-Player Example',['../tutorial_input.html#autotoc_md236',1,'']]],
  ['two_20players_279',['Example: Two Players',['../tutorial_sprites.html#autotoc_md346',1,'']]],
  ['two_20players_20example_280',['Two Players Example',['../examples_input_two_players.html',1,'examples_input']]],
  ['two_20sdk_20bugs_20this_20port_20surfaced_281',['Two SDK bugs this port surfaced',['../examples_graphics_effects_hicolor_1792.html#autotoc_md1164',1,'']]],
  ['two_20shipped_20examples_282',['two shipped examples',['../tutorial_colormath.html#autotoc_md137',1,'Worked patterns (the two shipped examples)'],['../tutorial_mode7.html#autotoc_md274',1,'Worked patterns (the two shipped examples)']]],
  ['two_20speeds_283',['1. Two Layers, Two Speeds',['../examples_graphics_backgrounds_continuous_scroll.html#autotoc_md930',1,'']]],
  ['two_20sprites_20per_20mode_284',['3. Two sprites per mode',['../examples_graphics_sprites_object_size.html#autotoc_md1322',1,'']]],
  ['type_285',['Type',['../examples_audio_snesmod_music.html#autotoc_md727',1,'Code Type'],['../examples_graphics_backgrounds_mode1.html#autotoc_md970',1,'Code Type'],['../examples_graphics_effects_fading.html#autotoc_md1079',1,'Code Type'],['../examples_input_two_players.html#autotoc_md1400',1,'Code Type'],['../tutorial_collision.html#autotoc_md112',1,'The Rect Type']]],
  ['types_286',['Types',['../examples_input_two_players.html#autotoc_md1418',1,'Controller Types'],['../code_style.html#autotoc_md471',1,'Types']]],
  ['types_20in_20assembly_287',['2. Register Object Types in Assembly',['../examples_games_mapandobjects.html#autotoc_md904',1,'']]],
  ['typical_20sample_20sizes_288',['Typical Sample Sizes',['../snes_sound_guide.html#autotoc_md565',1,'']]]
];
