var searchData=
[
  ['s_20map_0',['Controls (krom&apos;s map)',['../examples_mode7_perspective_rotate.html#autotoc_md1410',1,'']]],
  ['s_20must_20match_20the_20sprite_20size_1',['Converting a sheet: &lt;span class=&quot;tt&quot;&gt;-s&lt;/span&gt; must match the sprite size',['../tutorial_sprites.html#autotoc_md368',1,'']]],
  ['s_20next_2',['s Next',['../getting_started.html#autotoc_md455',1,'What&apos;s Next?'],['../examples_audio_snesmod_music.html#autotoc_md823',1,'What&apos;s Next?'],['../examples_audio_snesmod_sfx.html#autotoc_md843',1,'What&apos;s Next?'],['../examples_backgrounds_mode1.html#autotoc_md891',1,'What&apos;s Next?'],['../examples_basics_collision_demo.html#autotoc_md954',1,'What&apos;s Next?'],['../examples_color_transparency.html#autotoc_md1063',1,'What&apos;s Next?'],['../examples_input_two_players.html#autotoc_md1318',1,'What&apos;s Next?'],['../examples_transitions_fading.html#autotoc_md1630',1,'What&apos;s Next?']]],
  ['s_20spc_20dump_3',['Debugging audio: luna&apos;s spc-dump',['../tutorial_audio.html#autotoc_md114',1,'']]],
  ['s_20still_20missing_3a_20pow_20exp_20log_4',['What&apos;s still missing: &lt;span class=&quot;tt&quot;&gt;pow&lt;/span&gt;, &lt;span class=&quot;tt&quot;&gt;exp&lt;/span&gt;, &lt;span class=&quot;tt&quot;&gt;log&lt;/span&gt;',['../tutorial_math.html#autotoc_md281',1,'']]],
  ['s5_202_5',['Bullet despawn fix (S5.2)',['../examples_games_shmup_1942.html#autotoc_md1172',1,'']]],
  ['s6_20hud_20on_20bg3_6',['Open chantier — S6 HUD on BG3',['../examples_games_shmup_1942.html#autotoc_md1173',1,'']]],
  ['sa_201_7',['What Is SA-1?',['../tutorial_sa1.html#autotoc_md326',1,'']]],
  ['sa_201_20assembly_20tips_8',['SA-1 Assembly Tips',['../tutorial_sa1.html#autotoc_md337',1,'']]],
  ['sa_201_20boot_20code_9',['2. Write Your SA-1 Boot Code',['../tutorial_sa1.html#autotoc_md331',1,'']]],
  ['sa_201_20can_20t_20do_10',['What SA-1 Can&apos;t Do',['../tutorial_sa1.html#autotoc_md344',1,'']]],
  ['sa_201_20cartridge_11',['SA-1 Cartridge',['../memory_map.html#autotoc_md665',1,'']]],
  ['sa_201_20coprocessor_12',['SA-1 Coprocessor',['../examples_by_category.html#autotoc_md505',1,'']]],
  ['sa_201_20enhancement_20chip_20tutorial_13',['SA-1 Enhancement Chip Tutorial',['../tutorial_sa1.html',1,'index']]],
  ['sa_201_20hello_20world_14',['SA-1 Hello World',['../examples_chips_sa1_hello.html',1,'examples_chips']]],
  ['sa_201_20in_20your_20makefile_15',['1. Enable SA-1 in Your Makefile',['../tutorial_sa1.html#autotoc_md330',1,'']]],
  ['sa_201_20registers_20_242200_20_24230e_16',['SA-1 Registers ($2200-$230E)',['../registers.html#autotoc_md756',1,'']]],
  ['sa_201_20starfield_20murmuration_17',['SA-1 Starfield (Murmuration)',['../examples_chips_sa1_starfield.html',1,'examples_chips']]],
  ['safe_18',['When VRAM/CGRAM/OAM writes are safe',['../tutorial_dma.html#autotoc_md168',1,'']]],
  ['safe_20in_20nmi_19',['🟡 WRAM data port &lt;span class=&quot;tt&quot;&gt;$2180&lt;/span&gt;–&lt;span class=&quot;tt&quot;&gt;$2183&lt;/span&gt; is NOT safe in NMI',['../tutorial_dma.html#autotoc_md179',1,'']]],
  ['sample_20directory_20',['Sample Directory',['../snes_sound_guide.html#autotoc_md586',1,'']]],
  ['sample_20format_21',['BRR Sample Format',['../snes_sound_guide.html#autotoc_md583',1,'']]],
  ['sample_20preparation_22',['Sample Preparation',['../snes_sound_guide.html#autotoc_md604',1,'']]],
  ['sample_20provenance_23',['Sample provenance',['../examples_audio_pitch_mod.html#autotoc_md770',1,'Sample provenance'],['../examples_audio_soundboard.html#autotoc_md845',1,'Sample provenance']]],
  ['sample_20sizes_24',['Typical Sample Sizes',['../snes_sound_guide.html#autotoc_md606',1,'']]],
  ['sample_20sources_25',['Sample Sources',['../snes_sound_guide.html#autotoc_md611',1,'']]],
  ['samples_26',['play_noise — a drum kit with zero samples',['../examples_audio_play_noise.html',1,'examples_audio']]],
  ['samples_20and_20effects_20from_20pure_20c_27',['The audio module (v2) — samples and effects from pure C',['../tutorial_audio.html#autotoc_md111',1,'']]],
  ['saturation_20interact_28',['🟠 Half-mode and saturation interact',['../tutorial_colormath.html#autotoc_md148',1,'']]],
  ['save_29',['save',['../tutorial_sram.html#autotoc_md385',1,'&quot;Delete save&quot;'],['../tutorial_sram.html#autotoc_md383',1,'The minimum viable save']]],
  ['save_20game_20sram_20persistence_30',['Save Game -- SRAM Persistence',['../examples_memory_save_game.html',1,'examples_memory']]],
  ['save_20slots_31',['Save Slots',['../examples_memory_save_game.html#autotoc_md1391',1,'']]],
  ['save_20structure_32',['1. Define a save structure',['../examples_memory_save_game.html#autotoc_md1384',1,'']]],
  ['save_20to_20sram_33',['2. Save to SRAM',['../examples_memory_save_game.html#autotoc_md1385',1,'']]],
  ['save_20tutorial_34',['SRAM Save Tutorial',['../tutorial_sram.html',1,'index']]],
  ['save_20x_20through_20a_35',['No &lt;span class=&quot;tt&quot;&gt;stx.l&lt;/span&gt; — Save X Through A',['../tutorial_sa1.html#autotoc_md340',1,'']]],
  ['saves_36',['Multi-slot saves',['../tutorial_sram.html#autotoc_md384',1,'']]],
  ['says_20open_20snes_37',['speech_synth — the SNES says &quot;OPEN SNES&quot;',['../examples_audio_speech_synth.html',1,'examples_audio']]],
  ['sc_5f64x64_20tilemap_20layout_38',['SC_64x64 Tilemap Layout',['../examples_maps_dynamic_map.html#autotoc_md1322',1,'']]],
  ['scale_39',['8.8 Fixed-Point Scale',['../examples_mode7_rotate_scale.html#autotoc_md1432',1,'']]],
  ['scale_20before_20angle_40',['🟡 Set scale BEFORE angle',['../tutorial_mode7.html#autotoc_md298',1,'']]],
  ['scaling_41',['Scaling',['../examples_mode7_rotate_scale.html',1,'Mode 7 -- Rotation and Scaling'],['../examples_mode7_perspective.html#autotoc_md1406',1,'Per-Scanline Scaling']]],
  ['scaling_20—_20examples_20mode7_20rotate_5fscale_42',['Basic rotation + scaling — &lt;span class=&quot;tt&quot;&gt;examples/mode7/rotate_scale&lt;/span&gt;',['../tutorial_mode7.html#autotoc_md292',1,'']]],
  ['scanline_43',['scanline',['../examples_mode7_perspective_rotate.html',1,'Mode 7 rotating perspective — the full matrix, per scanline'],['../examples_windows_window_multi_hdma.html',1,'Multi-window HDMA — both windows animated per scanline']]],
  ['scanline_20—_20examples_20windows_20window_5fmulti_5fhdma_44',['Both windows per scanline — &lt;span class=&quot;tt&quot;&gt;examples/windows/window_multi_hdma&lt;/span&gt;',['../tutorial_window.html#autotoc_md436',1,'']]],
  ['scanline_20limits_20critical_45',['Scanline Limits (Critical!)',['../snes_graphics_guide.html#autotoc_md541',1,'']]],
  ['scanline_20matrix_3a_20rotating_20perspective_46',['Per-scanline matrix: rotating perspective',['../tutorial_mode7.html#autotoc_md303',1,'']]],
  ['scanline_20quirk_47',['Sprite Y +1 Scanline Quirk',['../oam.html#autotoc_md680',1,'']]],
  ['scanline_20scaling_48',['Per-Scanline Scaling',['../examples_mode7_perspective.html#autotoc_md1406',1,'']]],
  ['scanline_20scroll_49',['HDMA Parallax (Per-Scanline Scroll)',['../tutorial_scrolling.html#autotoc_md353',1,'']]],
  ['scanline_20wave_20distortion_20—_20examples_20hdma_20hdma_5fwave_50',['Per-scanline wave distortion — &lt;span class=&quot;tt&quot;&gt;examples/hdma/hdma_wave&lt;/span&gt;',['../tutorial_hdma.html#autotoc_md216',1,'']]],
  ['scene_20at_20once_51',['shadow_tint — recolour a whole scene at once',['../examples_color_shadow_tint.html',1,'examples_color']]],
  ['scene_20module_52',['The scene stack (recommended) — &lt;span class=&quot;tt&quot;&gt;scene&lt;/span&gt; module',['../tutorial_game_states.html#autotoc_md183',1,'']]],
  ['scene_20stack_53',['Scene Stack',['../examples_basics_scene_stack.html',1,'examples_basics']]],
  ['scene_20stack_20recommended_20—_20scene_20module_54',['The scene stack (recommended) — &lt;span class=&quot;tt&quot;&gt;scene&lt;/span&gt; module',['../tutorial_game_states.html#autotoc_md183',1,'']]],
  ['scene_20struct_55',['The Scene struct',['../examples_basics_scene_stack.html#autotoc_md987',1,'']]],
  ['scene_20transition_20pattern_56',['Scene Transition Pattern',['../examples_transitions_fading.html#autotoc_md1613',1,'']]],
  ['scenes_57',['🟡 Window state survives between scenes',['../tutorial_window.html#autotoc_md432',1,'']]],
  ['scope_58',['Super Scope',['../examples_input_superscope.html',1,'examples_input']]],
  ['screen_59',['Screen',['../examples_games_likemario.html#autotoc_md1123',1,'1. The World Is Bigger Than the Screen'],['../examples_color_transparency.html#autotoc_md1053',1,'Color Math: Main Screen + Sub Screen'],['../examples_input_two_players.html#autotoc_md1310',1,'Exercise 4: Split Screen'],['../colormath_8h.html#autotoc_md17',1,'Main Screen vs Sub Screen'],['../tutorial_game_states.html#autotoc_md190',1,'Pause Screen']]],
  ['screen_60',['screen',['../examples_sprites.html#autotoc_md1542',1,'Reference — OAM in one screen'],['../learning_path.html#autotoc_md466',1,'Stage 1 — &quot;Can I put something on screen?&quot;'],['../examples_audio.html#autotoc_md777',1,'The idea in one screen'],['../examples_backgrounds.html#autotoc_md936',1,'The idea in one screen'],['../examples_color.html#autotoc_md1041',1,'The idea in one screen'],['../examples_hdma.html#autotoc_md1233',1,'The idea in one screen'],['../examples_input.html#autotoc_md1262',1,'The idea in one screen'],['../examples_maps.html#autotoc_md1338',1,'The idea in one screen'],['../examples_mode7.html#autotoc_md1418',1,'The idea in one screen'],['../examples_scrolling.html#autotoc_md1497',1,'The idea in one screen'],['../examples_transitions.html#autotoc_md1646',1,'The idea in one screen'],['../examples_windows.html#autotoc_md1648',1,'The idea in one screen'],['../examples_chips.html#autotoc_md1000',1,'The two chips, in one screen']]],
  ['screen_20centre_61',['🟡 Centre default is the tilemap centre, not the screen centre',['../tutorial_mode7.html#autotoc_md299',1,'']]],
  ['screen_20crash_62',['Runtime Issues (Black Screen / Crash)',['../troubleshooting.html#autotoc_md625',1,'']]],
  ['screen_20enable_63',['Screen Enable',['../registers.html#autotoc_md724',1,'$212C - TM (Main Screen Enable)'],['../registers.html#autotoc_md725',1,'$212D - TS (Sub Screen Enable)'],['../registers.html#autotoc_md723',1,'Screen Enable']]],
  ['screen_20implementation_64',['Title Screen Implementation',['../tutorial_game_states.html#autotoc_md188',1,'']]],
  ['screen_20is_20black_65',['ROM loads but screen is black',['../troubleshooting.html#autotoc_md626',1,'']]],
  ['screen_20only_20trap_66',['🔴 The &quot;BG2 is sub-screen-only&quot; trap',['../tutorial_colormath.html#autotoc_md146',1,'']]],
  ['screen_20sub_20screen_67',['Color Math: Main Screen + Sub Screen',['../examples_color_transparency.html#autotoc_md1053',1,'']]],
  ['screen_20vs_20sub_20screen_68',['Main Screen vs Sub Screen',['../colormath_8h.html#autotoc_md17',1,'']]],
  ['screen_20when_20running_20rom_69',['Black screen when running ROM',['../getting_started.html#autotoc_md461',1,'']]],
  ['screen_20with_20hdma_70',['1. Split-screen with HDMA',['../examples_mode7_perspective.html#autotoc_md1401',1,'']]],
  ['scroll_71',['Scroll',['../registers.html#autotoc_md714',1,'Background Scroll'],['../examples_scrolling_continuous_scroll.html',1,'Continuous Scroll'],['../tutorial_scrolling.html#autotoc_md353',1,'HDMA Parallax (Per-Scanline Scroll)'],['../examples_maps_map_scroll.html',1,'Map Scroll'],['../examples_scrolling_mixed_scroll.html',1,'Mixed Scroll']]],
  ['scroll_20a_20message_72',['Scroll a message',['../examples_text_scroll_message.html',1,'examples_text']]],
  ['scroll_20bg1_73',['4. Auto-Scroll BG1',['../examples_scrolling_mixed_scroll.html#autotoc_md1479',1,'']]],
  ['scroll_20pattern_74',['2. The Threshold Scroll Pattern',['../examples_scrolling_continuous_scroll.html#autotoc_md1452',1,'']]],
  ['scroll_20registers_75',['$210D-$2114 - BGnHOFS/BGnVOFS (Scroll Registers)',['../registers.html#autotoc_md715',1,'']]],
  ['scroll_20registers_20require_20repeat_20mode_76',['IMPORTANT: Scroll Registers Require Repeat Mode',['../hdma_8h.html#autotoc_md33',1,'']]],
  ['scroll_20static_20moving_20layers_77',['Mixed Scroll (Static + Moving Layers)',['../tutorial_scrolling.html#autotoc_md350',1,'']]],
  ['scroll_20table_78',['HDMA Scroll Table',['../examples_scrolling_parallax_scroll.html#autotoc_md1487',1,'']]],
  ['scroll_20updates_20via_20bgsetscroll_20dirty_20flags_79',['3. Scroll Updates via bgSetScroll Dirty Flags',['../examples_scrolling_continuous_scroll.html#autotoc_md1453',1,'']]],
  ['scroller_80',['The minimum viable scroller',['../tutorial_map.html#autotoc_md251',1,'']]],
  ['scrolling_81',['Scrolling',['../examples_mode7_perspective.html#autotoc_md1403',1,'3. Scrolling'],['../tutorial_graphics.html#autotoc_md204',1,'Background Scrolling'],['../tutorial_scrolling.html#autotoc_md348',1,'Basic BG Scrolling'],['../tutorial_scrolling.html#autotoc_md354',1,'Continuous / Infinite Scrolling'],['../tutorial_scrolling.html#autotoc_md349',1,'D-PAD Controlled Scrolling'],['../examples_scrolling_mixed_scroll.html#autotoc_md1473',1,'Independent Background Scrolling'],['../examples_scrolling_parallax_scroll.html',1,'Parallax Scrolling'],['../tutorial_graphics.html#autotoc_md205',1,'Parallax Scrolling'],['../tutorial_scrolling.html#autotoc_md351',1,'Parallax Scrolling'],['../examples_scrolling.html',1,'Scrolling'],['../examples_by_category.html#autotoc_md482',1,'Scrolling']]],
  ['scrolling_20—_20examples_20scrolling_20parallax_5fscroll_82',['Parallax scrolling — &lt;span class=&quot;tt&quot;&gt;examples/scrolling/parallax_scroll&lt;/span&gt;',['../tutorial_hdma.html#autotoc_md217',1,'']]],
  ['scrolling_20and_20effects_83',['Level 3 &amp;ndash; Scrolling and Effects',['../examples.html#autotoc_md1439',1,'']]],
  ['scrolling_20is_20jerky_84',['Scrolling is jerky',['../troubleshooting.html#autotoc_md634',1,'']]],
  ['scrolling_20maps_85',['Scrolling maps',['../tutorial_map.html',1,'index']]],
  ['scrolling_20parallax_20tutorial_86',['Scrolling &amp;amp; Parallax Tutorial',['../tutorial_scrolling.html',1,'index']]],
  ['scrolling_20parallax_5fscroll_87',['Parallax scrolling — &lt;span class=&quot;tt&quot;&gt;examples/scrolling/parallax_scroll&lt;/span&gt;',['../tutorial_hdma.html#autotoc_md217',1,'']]],
  ['scrolling_20works_88',['How BG Scrolling Works',['../tutorial_scrolling.html#autotoc_md346',1,'']]],
  ['sdk_89',['A3. Download OpenSNES SDK',['../getting_started.html#autotoc_md442',1,'']]],
  ['sdk_20bugs_20this_20port_20surfaced_90',['Two SDK bugs this port surfaced',['../examples_color_hicolor_1792.html#autotoc_md1030',1,'']]],
  ['sdk_20convention_91',['OpenSNES SDK convention',['../oam.html#autotoc_md681',1,'']]],
  ['sdk_20developer_92',['Path B: SDK Developer',['../getting_started.html#autotoc_md449',1,'']]],
  ['seamless_20wrapping_93',['64x32 Tilemap for Seamless Wrapping',['../examples_scrolling_parallax_scroll.html#autotoc_md1492',1,'']]],
  ['second_20layer_94',['Exercise 1: Add a Second Layer',['../examples_backgrounds_mode1.html#autotoc_md881',1,'']]],
  ['second_20layer_20options_95',['One-way and second-layer options',['../tutorial_map.html#autotoc_md253',1,'']]],
  ['seconds_96',['ROM runs but crashes after a few seconds',['../troubleshooting.html#autotoc_md627',1,'']]],
  ['see_97',['Understanding what you see',['../examples_backgrounds_mode5_hires.html#autotoc_md930',1,'']]],
  ['see_20also_98',['See Also',['../oam.html#autotoc_md686',1,'']]],
  ['see_20also_99',['See also',['../tutorial_colormath.html#autotoc_md153',1,'See also'],['../tutorial_dma.html#autotoc_md181',1,'See also'],['../tutorial_hdma.html#autotoc_md234',1,'See also'],['../tutorial_map.html#autotoc_md259',1,'See also'],['../tutorial_math.html#autotoc_md283',1,'See also'],['../tutorial_mode7.html#autotoc_md302',1,'See also'],['../tutorial_mosaic.html#autotoc_md316',1,'See also'],['../tutorial_panel.html#autotoc_md325',1,'See also'],['../tutorial_sram.html#autotoc_md397',1,'See also'],['../tutorial_window.html#autotoc_md435',1,'See also'],['../examples_basics_aim_target.html#autotoc_md941',1,'See also'],['../examples_basics_fix32_orbit.html#autotoc_md961',1,'See also']]],
  ['seed_20matters_100',['Why Seed Matters',['../examples_basics_random.html#autotoc_md977',1,'']]],
  ['selecting_20the_20clip_20and_20ticking_101',['Selecting the Clip and Ticking',['../tutorial_animation.html#autotoc_md79',1,'']]],
  ['selection_102',['Palette Selection',['../snes_graphics_guide.html#autotoc_md555',1,'']]],
  ['self_20review_20checklist_103',['Self-review checklist',['../contributing.html#autotoc_md1702',1,'']]],
  ['semantics_104',['Push/pop semantics',['../examples_basics_scene_stack.html#autotoc_md988',1,'']]],
  ['sensitivity_105',['Mouse Sensitivity',['../examples_input_mouse.html#autotoc_md1245',1,'']]],
  ['sep_106',['Explicit &lt;span class=&quot;tt&quot;&gt;.ACCU&lt;/span&gt; After Every &lt;span class=&quot;tt&quot;&gt;rep&lt;/span&gt;/&lt;span class=&quot;tt&quot;&gt;sep&lt;/span&gt;',['../tutorial_sa1.html#autotoc_md341',1,'']]],
  ['separate_20palettes_107',['Separate Palettes',['../examples_input_two_players.html#autotoc_md1295',1,'']]],
  ['sequencing_108',['🟠 Double-write register sequencing',['../tutorial_mode7.html#autotoc_md297',1,'']]],
  ['sequencing_20during_20hdma_109',['🟡 Boundary register sequencing during HDMA',['../tutorial_window.html#autotoc_md433',1,'']]],
  ['set_20scale_20before_20angle_110',['🟡 Set scale BEFORE angle',['../tutorial_mode7.html#autotoc_md298',1,'']]],
  ['set_20up_20background_111',['2. Set Up Background',['../examples_backgrounds_mode1.html#autotoc_md868',1,'']]],
  ['set_20up_20oam_20directly_112',['3. Set Up OAM Directly',['../examples_input_mouse.html#autotoc_md1251',1,'']]],
  ['set_20up_20sprites_20via_20the_20oambuffer_113',['2. Set up sprites via the oambuffer',['../examples_sprites_dynamic_sprite.html#autotoc_md1523',1,'']]],
  ['set_20up_20text_20on_20bg1_204bpp_20in_20mode_201_114',['1. Set up text on BG1 (4bpp in Mode 1)',['../examples_sprites_sprite_sizes.html#autotoc_md1563',1,'']]],
  ['set_20up_20three_20background_20layers_115',['1. Set up three background layers',['../examples_backgrounds_mode1_bg3_priority.html#autotoc_md896',1,'']]],
  ['setbrightness_200_116',['🔴 &lt;span class=&quot;tt&quot;&gt;panelFlush&lt;/span&gt; uploads under forced blank — do not do it yourself with &lt;span class=&quot;tt&quot;&gt;setBrightness(0)&lt;/span&gt;',['../tutorial_panel.html#autotoc_md322',1,'']]],
  ['setini_117',['Hi-res and interlace (Modes 5/6, SETINI)',['../tutorial_graphics.html#autotoc_md208',1,'']]],
  ['setscreenon_118',['🔴 &lt;span class=&quot;tt&quot;&gt;mapLoad()&lt;/span&gt; must run before &lt;span class=&quot;tt&quot;&gt;setScreenOn()&lt;/span&gt;',['../tutorial_map.html#autotoc_md256',1,'']]],
  ['setting_20a_20sprite_119',['Setting a Sprite',['../tutorial_sprites.html#autotoc_md363',1,'']]],
  ['setting_20oam_20address_120',['Setting OAM Address',['../oam.html#autotoc_md677',1,'']]],
  ['setting_20palettes_121',['Setting Palettes',['../tutorial_graphics.html#autotoc_md203',1,'']]],
  ['setting_20up_20a_20dynamic_20sprite_122',['Setting Up a Dynamic Sprite',['../tutorial_animation.html#autotoc_md83',1,'']]],
  ['setting_20up_20graphics_123',['Setting Up Graphics',['../tutorial_graphics.html#autotoc_md199',1,'']]],
  ['setting_20up_20memory_124',['Example: Setting Up Memory',['../memory_map.html#autotoc_md663',1,'']]],
  ['setting_20up_20the_20hdma_20channel_125',['4. Setting Up the HDMA Channel',['../examples_hdma_hdma_wave.html#autotoc_md1213',1,'']]],
  ['setting_20up_20the_20ppu_126',['3. Setting Up the PPU',['../examples_fundamentals_text_glyphs.html#autotoc_md1073',1,'']]],
  ['setting_20up_20tilemaps_127',['Setting Up Tilemaps',['../tutorial_graphics.html#autotoc_md202',1,'']]],
  ['settings_128',['$2101 - OBJSEL (Sprite Settings)',['../registers.html#autotoc_md705',1,'']]],
  ['setup_129',['Setup',['../examples_input_superscope.html#autotoc_md1271',1,'5. Direct OAM Setup'],['../examples_backgrounds_mode1.html#autotoc_md866',1,'Basic Setup'],['../tutorial_graphics.html#autotoc_md207',1,'Example: Complete Background Setup'],['../examples_sprites_dynamic_sprite.html#autotoc_md1529',1,'Force Blank for Initial Setup'],['../examples_scrolling_parallax_scroll.html#autotoc_md1488',1,'HDMA Setup'],['../tutorial_audio.html#autotoc_md97',1,'Setup'],['../tutorial_debugging.html#autotoc_md154',1,'Setup'],['../tutorial_superfx.html#autotoc_md412',1,'Setup'],['../examples_color_transparency.html#autotoc_md1059',1,'Setup'],['../contributing.html#autotoc_md1694',1,'Setup'],['../examples_input_two_players.html#autotoc_md1296',1,'Sprite Setup']]],
  ['setup_130',['Build setup',['../tutorial_sram.html#autotoc_md379',1,'']]],
  ['setup_20even_20work_131',['Stage 0 — &quot;Does my setup even work?&quot;',['../learning_path.html#autotoc_md465',1,'']]],
  ['setup_20pattern_132',['Setup pattern',['../tutorial_hdma.html#autotoc_md214',1,'Setup pattern'],['../tutorial_mode7.html#autotoc_md287',1,'Setup pattern']]],
  ['setup_20pattern_133',['The setup pattern',['../tutorial_dma.html#autotoc_md169',1,'']]],
  ['setup_20recommended_134',['Mode 1 Setup (Recommended)',['../snes_graphics_guide.html#autotoc_md531',1,'']]],
  ['setup_20the_20long_20way_135',['Manual setup (the long way)',['../getting_started.html#autotoc_md445',1,'']]],
  ['seven_20amplitude_20levels_136',['3. Seven Amplitude Levels',['../examples_hdma_hdma_wave.html#autotoc_md1212',1,'']]],
  ['several_20panels_20one_20layer_20one_20upload_137',['Several panels, one layer, one upload',['../tutorial_panel.html#autotoc_md320',1,'']]],
  ['sfx_138',['Example: Music + SFX',['../tutorial_audio.html#autotoc_md106',1,'']]],
  ['shadow_20buffer_20vs_20hardware_139',['Recipe 4 — Sprite/OAM debugging (shadow buffer vs hardware)',['../tutorial_debugging.html#autotoc_md159',1,'']]],
  ['shadow_5ftint_20—_20recolour_20a_20whole_20scene_20at_20once_140',['shadow_tint — recolour a whole scene at once',['../examples_color_shadow_tint.html',1,'examples_color']]],
  ['shadows_20free_20depth_141',['7. Drop Shadows (Free Depth)',['../examples_games_breakout.html#autotoc_md1101',1,'']]],
  ['shapes_142',['Static shapes vs animated shapes',['../tutorial_window.html#autotoc_md419',1,'']]],
  ['shapes_20in_20commercial_20games_143',['Window Shapes in Commercial Games',['../examples_windows_window.html#autotoc_md1671',1,'']]],
  ['shapes_20vs_20animated_20shapes_144',['Static shapes vs animated shapes',['../tutorial_window.html#autotoc_md419',1,'']]],
  ['shapes_20with_20hdma_145',['Making Non-Rectangular Shapes with HDMA',['../examples_windows_window.html#autotoc_md1665',1,'']]],
  ['sheet_146',['Register Cheat Sheet',['../snes_graphics_guide.html#autotoc_md567',1,'']]],
  ['sheet_20layout_147',['Sprite Sheet Layout',['../tutorial_animation.html#autotoc_md73',1,'']]],
  ['sheet_20layout_148',['1. Sprite sheet layout',['../examples_sprites_animated_sprite.html#autotoc_md1503',1,'']]],
  ['sheet_20organization_149',['Sprite Sheet Organization',['../tutorial_animation.html#autotoc_md75',1,'']]],
  ['sheet_20was_20converted_150',['🟡 Match &lt;span class=&quot;tt&quot;&gt;base_tile&lt;/span&gt;/&lt;span class=&quot;tt&quot;&gt;stride&lt;/span&gt; to how the sheet was converted',['../tutorial_panel.html#autotoc_md324',1,'']]],
  ['sheet_3a_20s_20must_20match_20the_20sprite_20size_151',['Converting a sheet: &lt;span class=&quot;tt&quot;&gt;-s&lt;/span&gt; must match the sprite size',['../tutorial_sprites.html#autotoc_md368',1,'']]],
  ['sheets_152',['Animated Sprite -- Direction States and Sprite Sheets',['../examples_sprites_animated_sprite.html',1,'examples_sprites']]],
  ['sheets_20in_20vram_153',['Sprite Sheets in VRAM',['../examples_sprites_animated_sprite.html#autotoc_md1509',1,'']]],
  ['sheets_20with_20gfx4snes_154',['Converting Sprite Sheets with gfx4snes',['../tutorial_animation.html#autotoc_md76',1,'']]],
  ['ship_155',['Stage 6 — &quot;Can I finish and ship?&quot;',['../learning_path.html#autotoc_md471',1,'']]],
  ['ship_20in_20the_20lib_20chantier_20b6_202026_2005_2009_156',['&lt;span class=&quot;tt&quot;&gt;atan2&lt;/span&gt; and &lt;span class=&quot;tt&quot;&gt;sqrt&lt;/span&gt; ship in the lib (chantier B6, 2026-05-09)',['../tutorial_math.html#autotoc_md280',1,'']]],
  ['shipped_20example_157',['shipped example',['../tutorial_mosaic.html#autotoc_md308',1,'Worked pattern (the shipped example)'],['../tutorial_sram.html#autotoc_md386',1,'Worked pattern (the shipped example)']]],
  ['shipped_20examples_158',['shipped examples',['../tutorial_hdma.html#autotoc_md215',1,'Worked patterns (the shipped examples)'],['../tutorial_map.html#autotoc_md254',1,'Worked patterns (the shipped examples)'],['../tutorial_window.html#autotoc_md425',1,'Worked patterns (the shipped examples)'],['../tutorial_colormath.html#autotoc_md142',1,'Worked patterns (the two shipped examples)'],['../tutorial_mode7.html#autotoc_md291',1,'Worked patterns (the two shipped examples)']]],
  ['shmup_5f1942_159',['shmup_1942',['../examples_games_shmup_1942.html',1,'examples_games']]],
  ['show_20inside_160',['Inversion: Show Inside',['../examples_windows_window.html#autotoc_md1667',1,'']]],
  ['showcase_20—_20examples_20hdma_20hdma_5fhelpers_161',['Helpers showcase — &lt;span class=&quot;tt&quot;&gt;examples/hdma/hdma_helpers&lt;/span&gt;',['../tutorial_hdma.html#autotoc_md219',1,'']]],
  ['shows_162',['Shows',['../examples_backgrounds_mode1_bg3_priority.html#autotoc_md892',1,'What This Example Shows'],['../examples_hdma_gradient_colors.html#autotoc_md1183',1,'What This Example Shows'],['../examples_memory_hirom_demo.html#autotoc_md1359',1,'What This Example Shows'],['../examples_memory_save_game.html#autotoc_md1379',1,'What This Example Shows'],['../examples_mode7_perspective.html#autotoc_md1396',1,'What This Example Shows'],['../examples_mode7_rotate_scale.html#autotoc_md1419',1,'What This Example Shows'],['../examples_scrolling_parallax_scroll.html#autotoc_md1482',1,'What This Example Shows'],['../examples_sprites_animated_sprite.html#autotoc_md1498',1,'What This Example Shows'],['../examples_sprites_dynamic_sprite.html#autotoc_md1517',1,'What This Example Shows'],['../examples_sprites_simple_sprite.html#autotoc_md1543',1,'What This Example Shows'],['../examples_sprites_sprite_sizes.html#autotoc_md1559',1,'What This Example Shows'],['../examples_transitions_mosaic.html#autotoc_md1631',1,'What This Example Shows']]],
  ['shows_20the_20backdrop_20not_20a_20layer_163',['🟡 Out-of-bounds with &lt;span class=&quot;tt&quot;&gt;MODE7_TRANSPARENT&lt;/span&gt; shows the backdrop, not a layer',['../tutorial_mode7.html#autotoc_md300',1,'']]],
  ['sign_20convention_164',['Sign convention',['../fixed32_8h.html#autotoc_md28',1,'']]],
  ['signed_20result_165',['🟡 Sin/cos LUTs are unsigned-angle, signed-result',['../tutorial_math.html#autotoc_md279',1,'']]],
  ['silent_20corruption_166',['🔴 Battery dies → silent corruption',['../tutorial_sram.html#autotoc_md389',1,'']]],
  ['silently_20dropped_167',['🔴 VRAM/CGRAM/OAM writes outside VBlank or force blank are silently dropped',['../tutorial_dma.html#autotoc_md173',1,'']]],
  ['simple_20game_20over_20breakout_168',['Simple Game Over (Breakout)',['../tutorial_game_states.html#autotoc_md193',1,'']]],
  ['simple_20parallax_20multiple_20bgs_169',['Simple Parallax (Multiple BGs)',['../tutorial_scrolling.html#autotoc_md352',1,'']]],
  ['simple_20sprite_20your_20first_20oam_20sprite_170',['Simple Sprite -- Your First OAM Sprite',['../examples_sprites_simple_sprite.html',1,'examples_sprites']]],
  ['sin_20cos_20lookup_20tables_171',['Trigonometry (sin/cos lookup tables)',['../tutorial_math.html#autotoc_md264',1,'']]],
  ['sin_20cos_20luts_20are_20unsigned_20angle_20signed_20result_172',['🟡 Sin/cos LUTs are unsigned-angle, signed-result',['../tutorial_math.html#autotoc_md279',1,'']]],
  ['since_20chantier_20a1_173',['🟢 &lt;span class=&quot;tt&quot;&gt;int&lt;/span&gt; and &lt;span class=&quot;tt&quot;&gt;long&lt;/span&gt; sizes are correct on this target (since chantier A1)',['../tutorial_math.html#autotoc_md273',1,'']]],
  ['single_20bg_20layer_174',['🔴 Single BG layer',['../tutorial_mode7.html#autotoc_md295',1,'']]],
  ['size_175',['Size',['../registers.html#autotoc_md712',1,'$2107-$210A - BG1SC-BG4SC (Tilemap Address/Size)'],['../registers.html#autotoc_md746',1,'$43x5-$43x6 - DASxL/H (Transfer Size)'],['../tutorial_animation.html#autotoc_md86',1,'One Draw Function, Engine-Resolved Size']]],
  ['size_176',['size',['../troubleshooting.html#autotoc_md636',1,'&quot;ROM too large&quot; or linker errors about size'],['../examples_sprites_simple_sprite.html#autotoc_md1550',1,'3. Configure OBJ size'],['../tutorial_sprites.html#autotoc_md368',1,'Converting a sheet: &lt;span class=&quot;tt&quot;&gt;-s&lt;/span&gt; must match the sprite size']]],
  ['size_201_20pixels_177',['🟡 Mosaic block size is &quot;size + 1&quot; pixels',['../tutorial_mosaic.html#autotoc_md312',1,'']]],
  ['size_20all_206_20snes_20sprite_20size_20modes_178',['Object Size -- All 6 SNES Sprite Size Modes',['../examples_sprites_sprite_sizes.html',1,'examples_sprites']]],
  ['size_20is_20size_201_20pixels_179',['🟡 Mosaic block size is &quot;size + 1&quot; pixels',['../tutorial_mosaic.html#autotoc_md312',1,'']]],
  ['size_20modes_180',['Size Modes',['../examples_sprites_sprite_sizes.html',1,'Object Size -- All 6 SNES Sprite Size Modes'],['../examples_sprites_sprite_sizes.html#autotoc_md1566',1,'The 6 Size Modes']]],
  ['size_20modes_20register_20_242101_181',['OBJ Size Modes (Register $2101)',['../examples_sprites_metasprite.html#autotoc_md1534',1,'']]],
  ['sizes_182',['Sizes',['../tutorial_collision.html#autotoc_md124',1,'Custom Tile Sizes'],['../tutorial_sprites.html#autotoc_md373',1,'Sprite Sizes'],['../snes_graphics_guide.html#autotoc_md540',1,'Sprite Sizes'],['../oam.html#autotoc_md678',1,'Sprite Sizes'],['../snes_graphics_guide.html#autotoc_md535',1,'Tilemap Sizes'],['../snes_sound_guide.html#autotoc_md606',1,'Typical Sample Sizes']]],
  ['sizes_20are_20correct_20on_20this_20target_20since_20chantier_20a1_183',['🟢 &lt;span class=&quot;tt&quot;&gt;int&lt;/span&gt; and &lt;span class=&quot;tt&quot;&gt;long&lt;/span&gt; sizes are correct on this target (since chantier A1)',['../tutorial_math.html#autotoc_md273',1,'']]],
  ['slice_20panels_184',['9-slice panels',['../tutorial_panel.html',1,'index']]],
  ['slide_20along_20walls_185',['Stopping Movement (Slide Along Walls)',['../tutorial_collision.html#autotoc_md128',1,'']]],
  ['sliding_186',['Per-Axis Sliding',['../examples_basics_collision_demo.html#autotoc_md949',1,'']]],
  ['slope_20collision_187',['Object Engine and Slope Collision',['../examples_maps_slope_collision.html#autotoc_md1342',1,'']]],
  ['slope_20mario_188',['Slope Mario',['../examples_maps_slope_collision.html',1,'examples_maps']]],
  ['slot_189',['1. NOP After Every Branch (Delay Slot)',['../tutorial_superfx.html#autotoc_md407',1,'']]],
  ['slot_20saves_190',['Multi-slot saves',['../tutorial_sram.html#autotoc_md384',1,'']]],
  ['slots_191',['Slots',['../examples_scrolling_mixed_scroll.html#autotoc_md1472',1,'Palette Slots'],['../examples_memory_save_game.html#autotoc_md1391',1,'Save Slots']]],
  ['small_192',['Keep PRs small',['../contributing.html#autotoc_md1699',1,'']]],
  ['smallest_20complete_20game_193',['game_skeleton — the smallest complete game',['../examples_basics_game_skeleton.html',1,'examples_basics']]],
  ['smconv_194',['smconv',['../third_party.html#autotoc_md646',1,'']]],
  ['smconv_20error_195',['Build fails with smconv error',['../examples_audio_snesmod_music.html#autotoc_md816',1,'']]],
  ['smconv_20options_196',['smconv Options',['../examples_audio_snesmod_music.html#autotoc_md821',1,'']]],
  ['smconv_20tool_197',['smconv Tool',['../tutorial_audio.html#autotoc_md103',1,'']]],
  ['smooth_20fade_198',['Exercise 1: Smooth Fade',['../examples_transitions_fading.html#autotoc_md1620',1,'']]],
  ['smooth_20interpolation_199',['Smooth interpolation',['../tutorial_math.html#autotoc_md270',1,'']]],
  ['smooth_20sprite_20movement_200',['Smooth sprite movement',['../tutorial_math.html#autotoc_md268',1,'']]],
  ['snapping_20to_20tile_20grid_20platformer_20landing_201',['Snapping to Tile Grid (Platformer Landing)',['../tutorial_collision.html#autotoc_md131',1,'']]],
  ['snes_202',['SNES',['../examples_input_controller.html#autotoc_md1237',1,'How Input Works on the SNES'],['../examples_text.html#autotoc_md1587',1,'How Text Works on SNES'],['../examples_audio_speech_synth.html',1,'speech_synth — the SNES says &quot;OPEN SNES&quot;'],['../tutorial_math.html#autotoc_md260',1,'Why fixed-point on the SNES']]],
  ['snes_20audio_20architecture_203',['SNES Audio Architecture',['../tutorial_audio.html#autotoc_md94',1,'']]],
  ['snes_20compatibility_204',['For SNES Compatibility',['../snes_graphics_guide.html#autotoc_md558',1,'']]],
  ['snes_20concepts_205',['SNES Concepts',['../examples_audio_apu_switch.html#autotoc_md759',1,'SNES Concepts'],['../examples_audio_pitch_mod.html#autotoc_md769',1,'SNES Concepts'],['../examples_audio_play_noise.html#autotoc_md773',1,'SNES Concepts'],['../examples_audio_snesmod_sfx.html#autotoc_md836',1,'SNES Concepts'],['../examples_audio_soundboard.html#autotoc_md844',1,'SNES Concepts'],['../examples_backgrounds_mode1_bg3_priority.html#autotoc_md899',1,'SNES Concepts'],['../examples_backgrounds_mode1_lz77.html#autotoc_md907',1,'SNES Concepts'],['../examples_backgrounds_mode5_hires.html#autotoc_md929',1,'SNES Concepts'],['../examples_basics_aim_target.html#autotoc_md937',1,'SNES Concepts'],['../examples_basics_collision_demo.html#autotoc_md946',1,'SNES Concepts'],['../examples_basics_fix32_orbit.html#autotoc_md957',1,'SNES Concepts'],['../examples_basics_random.html#autotoc_md976',1,'SNES Concepts'],['../examples_basics_scene_stack.html#autotoc_md986',1,'SNES Concepts'],['../examples_basics_timer.html#autotoc_md994',1,'SNES Concepts'],['../examples_color_direct_color.html#autotoc_md1020',1,'SNES Concepts'],['../examples_color_gradient_9bit.html#autotoc_md1023',1,'SNES Concepts'],['../examples_color_hicolor_1792.html#autotoc_md1027',1,'SNES Concepts'],['../examples_color_transparency.html#autotoc_md1052',1,'SNES Concepts'],['../examples_games_mapandobjects.html#autotoc_md1145',1,'SNES Concepts'],['../examples_games_mode7_flying.html#autotoc_md1158',1,'SNES Concepts'],['../examples_games_mode7_racing.html#autotoc_md1161',1,'SNES Concepts'],['../examples_games_rpg.html#autotoc_md1167',1,'SNES Concepts'],['../examples_hdma_gradient_colors.html#autotoc_md1191',1,'SNES Concepts'],['../examples_hdma_hdma_indirect_gradient.html#autotoc_md1202',1,'SNES Concepts'],['../examples_hdma_hdma_wave_table.html#autotoc_md1229',1,'SNES Concepts'],['../examples_input_controller.html#autotoc_md1236',1,'SNES Concepts'],['../examples_input_mouse.html#autotoc_md1243',1,'SNES Concepts'],['../examples_maps_dynamic_map.html#autotoc_md1320',1,'SNES Concepts'],['../examples_maps_map_scroll.html#autotoc_md1331',1,'SNES Concepts'],['../examples_maps_slope_collision.html#autotoc_md1340',1,'SNES Concepts'],['../examples_maps_tiled.html#autotoc_md1351',1,'SNES Concepts'],['../examples_memory_hirom_demo.html#autotoc_md1368',1,'SNES Concepts'],['../examples_memory_save_game.html#autotoc_md1389',1,'SNES Concepts'],['../examples_mode7_perspective.html#autotoc_md1404',1,'SNES Concepts'],['../examples_mode7_perspective_rotate.html#autotoc_md1411',1,'SNES Concepts'],['../examples_mode7_rotate_scale.html#autotoc_md1428',1,'SNES Concepts'],['../examples_scrolling_mixed_scroll.html#autotoc_md1469',1,'SNES Concepts'],['../examples_scrolling_parallax_scroll.html#autotoc_md1490',1,'SNES Concepts'],['../examples_sprites_animated_sprite.html#autotoc_md1507',1,'SNES Concepts'],['../examples_sprites_dynamic_sprite.html#autotoc_md1526',1,'SNES Concepts'],['../examples_sprites_metasprite.html#autotoc_md1533',1,'SNES Concepts'],['../examples_sprites_simple_sprite.html#autotoc_md1553',1,'SNES Concepts'],['../examples_sprites_sprite_sizes.html#autotoc_md1567',1,'SNES Concepts'],['../examples_transitions_mosaic.html#autotoc_md1639',1,'SNES Concepts'],['../examples_windows_transparent_window.html#autotoc_md1656',1,'SNES Concepts'],['../examples_windows_window.html#autotoc_md1669',1,'SNES Concepts'],['../examples_windows_window_multi_hdma.html#autotoc_md1675',1,'SNES Concepts']]],
  ['snes_20concepts_206',['SNES concepts',['../examples_audio_echo.html#autotoc_md764',1,'SNES concepts'],['../examples_input_move_sprite.html#autotoc_md1257',1,'SNES concepts'],['../examples_text_print_string.html#autotoc_md1581',1,'SNES concepts'],['../examples_text_scroll_message.html#autotoc_md1593',1,'SNES concepts']]],
  ['snes_20controller_20layout_207',['SNES Controller Layout',['../tutorial_input.html#autotoc_md235',1,'']]],
  ['snes_20development_208',['Learn SNES Development',['../learning_path.html',1,'index']]],
  ['snes_20graphics_20programming_20guide_209',['SNES Graphics Programming Guide',['../snes_graphics_guide.html',1,'index']]],
  ['snes_20hardware_20overview_210',['SNES Hardware Overview',['../hardware_overview.html',1,'index']]],
  ['snes_20hardware_20register_20reference_211',['SNES Hardware Register Reference',['../registers.html',1,'index']]],
  ['snes_20memory_20map_212',['SNES Memory Map',['../memory_map.html',1,'index']]],
  ['snes_20memory_20mapping_213',['HiROM Demo -- Understanding SNES Memory Mapping',['../examples_memory_hirom_demo.html',1,'examples_memory']]],
  ['snes_20mouse_214',['SNES Mouse',['../examples_input_mouse.html',1,'examples_input']]],
  ['snes_20mouse_20hardware_215',['SNES Mouse Hardware',['../examples_input_mouse.html#autotoc_md1244',1,'']]],
  ['snes_20oam_20object_20attribute_20memory_216',['SNES OAM (Object Attribute Memory)',['../oam.html',1,'index']]],
  ['snes_20says_20open_20snes_217',['speech_synth — the SNES says &quot;OPEN SNES&quot;',['../examples_audio_speech_synth.html',1,'examples_audio']]],
  ['snes_20sound_20programming_20guide_218',['SNES Sound Programming Guide',['../snes_sound_guide.html',1,'index']]],
  ['snes_20sprite_20basics_219',['SNES Sprite Basics',['../tutorial_sprites.html#autotoc_md359',1,'']]],
  ['snes_20sprite_20limits_220',['SNES Sprite Limits',['../sprite_8h.html#autotoc_md57',1,'']]],
  ['snes_20sprite_20size_20modes_221',['Object Size -- All 6 SNES Sprite Size Modes',['../examples_sprites_sprite_sizes.html',1,'examples_sprites']]],
  ['snes_20video_20modes_222',['SNES Video Modes',['../tutorial_graphics.html#autotoc_md198',1,'']]],
  ['snes_20window_20system_223',['SNES Window System',['../examples_windows_window.html#autotoc_md1664',1,'']]],
  ['snesmod_224',['The raw APU path (no snesmod)',['../tutorial_audio.html#autotoc_md112',1,'']]],
  ['snesmod_20api_225',['SNESMOD API',['../examples_audio_snesmod_music.html#autotoc_md788',1,'']]],
  ['snesmod_20initialization_226',['SNESMOD Initialization',['../examples_audio_snesmod_sfx.html#autotoc_md837',1,'']]],
  ['snesmod_20large_20soundbank_20music_227',['SNESMOD Large Soundbank Music',['../examples_audio_snesmod_music_large.html',1,'examples_audio']]],
  ['snesmod_20music_20example_228',['SNESMOD Music Example',['../examples_audio_snesmod_music.html',1,'examples_audio']]],
  ['snesmod_20overview_229',['SNESMOD Overview',['../examples_audio_snesmod_music.html#autotoc_md785',1,'']]],
  ['snesmod_20recommended_230',['SNESMOD (Recommended)',['../tutorial_audio.html#autotoc_md96',1,'']]],
  ['snesmod_20sound_20effects_231',['SNESMOD Sound Effects',['../examples_audio_snesmod_sfx.html',1,'examples_audio']]],
  ['snesmodprocess_232',['Important: Call snesmodProcess()!',['../tutorial_audio.html#autotoc_md105',1,'']]],
  ['so_20many_20modules_233',['Why So Many Modules?',['../examples_games_likemario.html#autotoc_md1138',1,'']]],
  ['solution_234',['The Solution',['../oam.html#autotoc_md674',1,'']]],
  ['something_20on_20screen_235',['Stage 1 — &quot;Can I put something on screen?&quot;',['../learning_path.html#autotoc_md466',1,'']]],
  ['sound_20creation_20tools_236',['Sound Creation Tools',['../snes_sound_guide.html#autotoc_md609',1,'']]],
  ['sound_20effects_237',['Sound Effects',['../examples_audio_snesmod_music.html#autotoc_md809',1,'Exercise 1: Add Sound Effects'],['../examples_audio_snesmod_sfx.html',1,'SNESMOD Sound Effects'],['../tutorial_audio.html#autotoc_md100',1,'Sound Effects']]],
  ['sound_20programming_20guide_238',['SNES Sound Programming Guide',['../snes_sound_guide.html',1,'index']]],
  ['soundbank_239',['The Soundbank',['../examples_audio_snesmod_sfx.html#autotoc_md839',1,'']]],
  ['soundbank_20creation_240',['Soundbank Creation',['../snesmod_8h.html#autotoc_md55',1,'']]],
  ['soundbank_20music_241',['SNESMOD Large Soundbank Music',['../examples_audio_snesmod_music_large.html',1,'examples_audio']]],
  ['soundboard_20—_20the_20audio_20v2_20engine_20driven_20entirely_20from_20c_242',['soundboard — the audio v2 engine, driven entirely from C',['../examples_audio_soundboard.html',1,'examples_audio']]],
  ['sounds_20wrong_243',['Music sounds wrong',['../examples_audio_snesmod_music.html#autotoc_md815',1,'']]],
  ['source_20address_244',['$43x2-$43x4 - A1TxL/H/B (Source Address)',['../registers.html#autotoc_md745',1,'']]],
  ['source_20addressing_245',['Direction and source addressing',['../tutorial_dma.html#autotoc_md167',1,'']]],
  ['source_20c_246',['Source (.c)',['../code_style.html#autotoc_md523',1,'']]],
  ['source_20code_247',['Source Code',['../example_sources.html',1,'Example Source Code'],['../index.html#autotoc_md4',1,'Examples (Annotated Source Code)']]],
  ['sources_248',['Sample Sources',['../snes_sound_guide.html#autotoc_md611',1,'']]],
  ['sources_20cc0_20public_20domain_249',['Free Asset Sources (CC0/Public Domain)',['../snes_graphics_guide.html#autotoc_md563',1,'']]],
  ['space_250',['SRAM Address Space',['../examples_memory_save_game.html#autotoc_md1390',1,'']]],
  ['space_20overview_251',['Address Space Overview',['../memory_map.html#autotoc_md653',1,'']]],
  ['spc_20dump_252',['Debugging audio: luna&apos;s spc-dump',['../tutorial_audio.html#autotoc_md114',1,'']]],
  ['spc_20ram_253',['SPC RAM',['../examples_audio_snesmod_music.html#autotoc_md806',1,'']]],
  ['spc700_20cpu_254',['SPC700 CPU',['../snes_sound_guide.html#autotoc_md574',1,'']]],
  ['special_20timing_255',['🟠 SRAM access requires no special timing',['../tutorial_sram.html#autotoc_md391',1,'']]],
  ['specifications_256',['Specifications',['../hardware_overview.html#autotoc_md689',1,'']]],
  ['specifics_257',['BG3 Specifics',['../examples_backgrounds_mode1.html#autotoc_md888',1,'']]],
  ['speech_5fsynth_20—_20the_20snes_20says_20open_20snes_258',['speech_synth — the SNES says &quot;OPEN SNES&quot;',['../examples_audio_speech_synth.html',1,'examples_audio']]],
  ['speeds_259',['Speeds',['../examples_scrolling_continuous_scroll.html#autotoc_md1451',1,'1. Two Layers, Two Speeds'],['../examples_input_two_players.html#autotoc_md1308',1,'Exercise 2: Different Speeds'],['../examples_transitions_fading.html#autotoc_md1610',1,'Fade Speeds']]],
  ['spelling_20the_20message_260',['6. Spelling the Message',['../examples_fundamentals_text_glyphs.html#autotoc_md1076',1,'']]],
  ['split_261',['CGRAM Split',['../examples_sprites_simple_sprite.html#autotoc_md1555',1,'']]],
  ['split_20blend_262',['&quot;3840 colors&quot; — RGB channel-split blend',['../examples_color_hicolor_blend.html',1,'examples_color']]],
  ['split_20screen_263',['Exercise 4: Split Screen',['../examples_input_two_players.html#autotoc_md1310',1,'']]],
  ['split_20screen_20with_20hdma_264',['1. Split-screen with HDMA',['../examples_mode7_perspective.html#autotoc_md1401',1,'']]],
  ['spotlight_20blend_20—_20examples_20windows_20transparent_5fwindow_265',['Window-gated spotlight blend — &lt;span class=&quot;tt&quot;&gt;examples/windows/transparent_window&lt;/span&gt;',['../tutorial_colormath.html#autotoc_md144',1,'']]],
  ['sprite_266',['Sprite',['../examples_input_mouse.html#autotoc_md1250',1,'2. Load Cursor Sprite'],['../tutorial_sprites.html#autotoc_md363',1,'Setting a Sprite'],['../tutorial_animation.html#autotoc_md83',1,'Setting Up a Dynamic Sprite'],['../examples_sprites_simple_sprite.html',1,'Simple Sprite -- Your First OAM Sprite']]],
  ['sprite_267',['sprite',['../examples_sprites_simple_sprite.html#autotoc_md1551',1,'4. Place the sprite'],['../oam.html#autotoc_md671',1,'Extended Table (2 bits per sprite)'],['../oam.html#autotoc_md669',1,'Main Table (4 bytes per sprite)']]],
  ['sprite_20basics_268',['SNES Sprite Basics',['../tutorial_sprites.html#autotoc_md359',1,'']]],
  ['sprite_20collision_269',['Sprite-to-Sprite Collision',['../tutorial_collision.html#autotoc_md117',1,'']]],
  ['sprite_20direction_20states_20and_20sprite_20sheets_270',['Animated Sprite -- Direction States and Sprite Sheets',['../examples_sprites_animated_sprite.html',1,'examples_sprites']]],
  ['sprite_20engine_271',['Sprite Engine',['../examples_maps_slope_collision.html#autotoc_md1343',1,'Dynamic Sprite Engine'],['../tutorial_animation.html#autotoc_md80',1,'The Dynamic Sprite Engine']]],
  ['sprite_20engine_272',['1. Initialize the dynamic sprite engine',['../examples_sprites_dynamic_sprite.html#autotoc_md1522',1,'']]],
  ['sprite_20functions_273',['Using OpenSNES Sprite Functions',['../tutorial_sprites.html#autotoc_md361',1,'']]],
  ['sprite_20graphics_20into_20vram_274',['1. Load sprite graphics into VRAM',['../examples_sprites_simple_sprite.html#autotoc_md1548',1,'']]],
  ['sprite_20is_20vs_20where_20it_20collides_275',['Where the sprite is vs where it collides',['../tutorial_collision.html#autotoc_md126',1,'']]],
  ['sprite_20limits_276',['SNES Sprite Limits',['../sprite_8h.html#autotoc_md57',1,'']]],
  ['sprite_20memory_277',['OAM (Sprite Memory)',['../registers.html#autotoc_md706',1,'']]],
  ['sprite_20movement_278',['Smooth sprite movement',['../tutorial_math.html#autotoc_md268',1,'']]],
  ['sprite_20oam_20debugging_20shadow_20buffer_20vs_20hardware_279',['Recipe 4 — Sprite/OAM debugging (shadow buffer vs hardware)',['../tutorial_debugging.html#autotoc_md159',1,'']]],
  ['sprite_20palette_280',['2. Load the sprite palette',['../examples_sprites_simple_sprite.html#autotoc_md1549',1,'']]],
  ['sprite_20palettes_281',['Sprite Palettes',['../tutorial_sprites.html#autotoc_md369',1,'']]],
  ['sprite_20positioning_282',['Camera-Relative Sprite Positioning',['../examples_maps_map_scroll.html#autotoc_md1333',1,'']]],
  ['sprite_20priority_283',['Sprite Priority',['../snes_graphics_guide.html#autotoc_md542',1,'']]],
  ['sprite_20settings_284',['$2101 - OBJSEL (Sprite Settings)',['../registers.html#autotoc_md705',1,'']]],
  ['sprite_20setup_285',['Sprite Setup',['../examples_input_two_players.html#autotoc_md1296',1,'']]],
  ['sprite_20sheet_20layout_286',['Sprite Sheet Layout',['../tutorial_animation.html#autotoc_md73',1,'']]],
  ['sprite_20sheet_20layout_287',['1. Sprite sheet layout',['../examples_sprites_animated_sprite.html#autotoc_md1503',1,'']]],
  ['sprite_20sheet_20organization_288',['Sprite Sheet Organization',['../tutorial_animation.html#autotoc_md75',1,'']]],
  ['sprite_20sheets_289',['Animated Sprite -- Direction States and Sprite Sheets',['../examples_sprites_animated_sprite.html',1,'examples_sprites']]],
  ['sprite_20sheets_20in_20vram_290',['Sprite Sheets in VRAM',['../examples_sprites_animated_sprite.html#autotoc_md1509',1,'']]],
  ['sprite_20sheets_20with_20gfx4snes_291',['Converting Sprite Sheets with gfx4snes',['../tutorial_animation.html#autotoc_md76',1,'']]],
  ['sprite_20size_292',['Converting a sheet: &lt;span class=&quot;tt&quot;&gt;-s&lt;/span&gt; must match the sprite size',['../tutorial_sprites.html#autotoc_md368',1,'']]],
  ['sprite_20size_20modes_293',['Object Size -- All 6 SNES Sprite Size Modes',['../examples_sprites_sprite_sizes.html',1,'examples_sprites']]],
  ['sprite_20sizes_294',['Sprite Sizes',['../tutorial_sprites.html#autotoc_md373',1,'Sprite Sizes'],['../snes_graphics_guide.html#autotoc_md540',1,'Sprite Sizes'],['../oam.html#autotoc_md678',1,'Sprite Sizes']]],
  ['sprite_20system_295',['1. Initialize the Map and Sprite System',['../examples_games_mapandobjects.html#autotoc_md1151',1,'']]],
  ['sprite_20tiles_296',['Loading Sprite Tiles',['../tutorial_sprites.html#autotoc_md367',1,'']]],
  ['sprite_20to_20background_20collision_297',['Sprite-to-Background Collision',['../tutorial_collision.html#autotoc_md121',1,'']]],
  ['sprite_20to_20sprite_20collision_298',['Sprite-to-Sprite Collision',['../tutorial_collision.html#autotoc_md117',1,'']]],
  ['sprite_20vram_20streaming_20for_20animated_20sprites_299',['Dynamic Sprite -- VRAM Streaming for Animated Sprites',['../examples_sprites_dynamic_sprite.html',1,'examples_sprites']]],
  ['sprite_20with_20the_20pad_300',['Drive a sprite with the pad',['../examples_input_move_sprite.html',1,'examples_input']]],
  ['sprite_20y_201_20scanline_20quirk_301',['Sprite Y +1 Scanline Quirk',['../oam.html#autotoc_md680',1,'']]],
  ['sprite_20your_20first_20oam_20sprite_302',['Simple Sprite -- Your First OAM Sprite',['../examples_sprites_simple_sprite.html',1,'examples_sprites']]],
  ['sprite_5fswarm_20—_20a_20bouncing_20swarm_20and_20the_20oam_20throughput_20ceiling_303',['sprite_swarm — a bouncing swarm, and the OAM throughput ceiling',['../examples_sprites_sprite_swarm.html',1,'examples_sprites']]],
  ['sprites_304',['Sprites',['../examples_games_breakout.html#autotoc_md1098',1,'4. Bricks Are Not Sprites'],['../examples_input_superscope.html#autotoc_md1270',1,'4. Sprites'],['../examples_sprites_dynamic_sprite.html',1,'Dynamic Sprite -- VRAM Streaming for Animated Sprites'],['../examples_games_mapandobjects.html#autotoc_md1148',1,'Dynamic Sprites'],['../tutorial_sprites.html#autotoc_md365',1,'Hiding Sprites'],['../oam.html#autotoc_md679',1,'Hiding Sprites'],['../examples_sprites.html',1,'Sprites'],['../examples_by_category.html#autotoc_md480',1,'Sprites'],['../snes_graphics_guide.html#autotoc_md538',1,'Sprites'],['../group__examples.html#autotoc_md1682',1,'Sprites'],['../examples_sprites_dynamic_sprite.html#autotoc_md1528',1,'Static vs Dynamic Sprites'],['../hardware_overview.html#autotoc_md694',1,'Tiles and Sprites']]],
  ['sprites_305',['🟠 Mosaic does not affect OBJ (sprites)',['../tutorial_mosaic.html#autotoc_md310',1,'']]],
  ['sprites_20animation_20tutorial_306',['Sprites &amp;amp; Animation Tutorial',['../tutorial_sprites.html',1,'index']]],
  ['sprites_20are_20unaffected_307',['Sprites Are Unaffected',['../examples_transitions_mosaic.html#autotoc_md1642',1,'']]],
  ['sprites_20as_20ui_20elements_308',['Sprites as UI Elements',['../examples_input_mouse.html#autotoc_md1246',1,'']]],
  ['sprites_20don_20t_20appear_309',['Sprites don&apos;t appear',['../troubleshooting.html#autotoc_md628',1,'']]],
  ['sprites_20per_20mode_310',['3. Two sprites per mode',['../examples_sprites_sprite_sizes.html#autotoc_md1565',1,'']]],
  ['sprites_20via_20the_20oambuffer_311',['2. Set up sprites via the oambuffer',['../examples_sprites_dynamic_sprite.html#autotoc_md1523',1,'']]],
  ['sprites_20with_20force_20blank_312',['2. Load sprites with force blank',['../examples_sprites_sprite_sizes.html#autotoc_md1564',1,'']]],
  ['sqrt_20ship_20in_20the_20lib_20chantier_20b6_202026_2005_2009_313',['&lt;span class=&quot;tt&quot;&gt;atan2&lt;/span&gt; and &lt;span class=&quot;tt&quot;&gt;sqrt&lt;/span&gt; ship in the lib (chantier B6, 2026-05-09)',['../tutorial_math.html#autotoc_md280',1,'']]],
  ['sram_314',['SRAM',['../tutorial_sram.html#autotoc_md392',1,'🟠 Cannot store pointers in SRAM'],['../examples_memory_save_game.html#autotoc_md1385',1,'2. Save to SRAM'],['../examples_memory_save_game.html#autotoc_md1386',1,'3. Load from SRAM']]],
  ['sram_20access_20requires_20no_20special_20timing_315',['🟠 SRAM access requires no special timing',['../tutorial_sram.html#autotoc_md391',1,'']]],
  ['sram_20actually_20is_316',['What SRAM actually is',['../tutorial_sram.html#autotoc_md377',1,'']]],
  ['sram_20address_20space_317',['SRAM Address Space',['../examples_memory_save_game.html#autotoc_md1390',1,'']]],
  ['sram_20battery_20backup_318',['SRAM (Battery Backup)',['../examples_memory.html#autotoc_md1377',1,'']]],
  ['sram_20contents_20on_20first_20boot_20are_20undefined_319',['🔴 SRAM contents on first boot are undefined',['../tutorial_sram.html#autotoc_md388',1,'']]],
  ['sram_20in_20the_20makefile_320',['4. Enable SRAM in the Makefile',['../examples_memory_save_game.html#autotoc_md1387',1,'']]],
  ['sram_20overview_321',['SRAM Overview',['../sram_8h.html#autotoc_md60',1,'']]],
  ['sram_20persistence_322',['Save Game -- SRAM Persistence',['../examples_memory_save_game.html',1,'examples_memory']]],
  ['sram_20save_20tutorial_323',['SRAM Save Tutorial',['../tutorial_sram.html',1,'index']]],
  ['sram_20to_20vram_20transfer_324',['SRAM to VRAM Transfer',['../tutorial_superfx.html#autotoc_md414',1,'']]],
  ['sram_5fsize_20mismatch_20between_20makefile_20and_20code_325',['🔴 &lt;span class=&quot;tt&quot;&gt;SRAM_SIZE&lt;/span&gt; mismatch between Makefile and code',['../tutorial_sram.html#autotoc_md390',1,'']]],
  ['sramclear_20is_20a_20memset_20not_20a_20write_20protect_326',['🟡 &lt;span class=&quot;tt&quot;&gt;sramClear&lt;/span&gt; is a memset, not a write-protect',['../tutorial_sram.html#autotoc_md395',1,'']]],
  ['sta_20l_20lda_20l_20for_20everything_327',['Use &lt;span class=&quot;tt&quot;&gt;sta.l&lt;/span&gt; / &lt;span class=&quot;tt&quot;&gt;lda.l&lt;/span&gt; for Everything',['../tutorial_sa1.html#autotoc_md338',1,'']]],
  ['stack_328',['Scene Stack',['../examples_basics_scene_stack.html',1,'examples_basics']]],
  ['stack_20recommended_20—_20scene_20module_329',['The scene stack (recommended) — &lt;span class=&quot;tt&quot;&gt;scene&lt;/span&gt; module',['../tutorial_game_states.html#autotoc_md183',1,'']]],
  ['stage_200_20—_20does_20my_20setup_20even_20work_330',['Stage 0 — &quot;Does my setup even work?&quot;',['../learning_path.html#autotoc_md465',1,'']]],
  ['stage_201_20—_20can_20i_20put_20something_20on_20screen_331',['Stage 1 — &quot;Can I put something on screen?&quot;',['../learning_path.html#autotoc_md466',1,'']]],
  ['stage_202_20—_20can_20the_20player_20act_332',['Stage 2 — &quot;Can the player act?&quot;',['../learning_path.html#autotoc_md467',1,'']]],
  ['stage_203_20—_20can_20i_20build_20a_20world_333',['Stage 3 — &quot;Can I build a world?&quot;',['../learning_path.html#autotoc_md468',1,'']]],
  ['stage_204_20—_20can_20i_20make_20it_20feel_20good_334',['Stage 4 — &quot;Can I make it feel good?&quot;',['../learning_path.html#autotoc_md469',1,'']]],
  ['stage_205_20—_20can_20i_20hold_20it_20all_20together_335',['Stage 5 — &quot;Can I hold it all together?&quot;',['../learning_path.html#autotoc_md470',1,'']]],
  ['stage_206_20—_20can_20i_20finish_20and_20ship_336',['Stage 6 — &quot;Can I finish and ship?&quot;',['../learning_path.html#autotoc_md471',1,'']]],
  ['starfield_20murmuration_337',['SA-1 Starfield (Murmuration)',['../examples_chips_sa1_starfield.html',1,'examples_chips']]],
  ['start_338',['Start',['../audio_8h.html#autotoc_md11',1,'Quick Start'],['../profile_8h.html#autotoc_md49',1,'Quick Start'],['../snesmod_8h.html#autotoc_md54',1,'Quick Start']]],
  ['start_20here_339',['Start Here',['../index.html#autotoc_md0',1,'']]],
  ['started_340',['Started',['../tutorial_sa1.html#autotoc_md329',1,'Getting Started'],['../tutorial_superfx.html#autotoc_md400',1,'Getting Started'],['../group__examples.html#autotoc_md1680',1,'Getting Started']]],
  ['started_20with_20opensnes_341',['Getting Started with OpenSNES',['../getting_started.html',1,'index']]],
  ['state_342',['Player State',['../examples_input_two_players.html#autotoc_md1288',1,'']]],
  ['state_20changes_343',['Input and State Changes',['../tutorial_animation.html#autotoc_md78',1,'']]],
  ['state_20is_20not_20reset_20by_20consoleinit_344',['🟡 Mosaic state is not reset by &lt;span class=&quot;tt&quot;&gt;consoleInit&lt;/span&gt;',['../tutorial_mosaic.html#autotoc_md314',1,'']]],
  ['state_20machine_345',['State Machine',['../examples_input_superscope.html#autotoc_md1272',1,'6. State Machine'],['../snes_graphics_guide.html#autotoc_md546',1,'Animation State Machine']]],
  ['state_20machine_346',['2. State machine',['../examples_sprites_animated_sprite.html#autotoc_md1504',1,'']]],
  ['state_20machine_20summary_347',['State Machine Summary',['../tutorial_game_states.html#autotoc_md196',1,'']]],
  ['state_20machine_20under_20the_20hood_348',['The manual state machine (under the hood)',['../tutorial_game_states.html#autotoc_md184',1,'']]],
  ['state_20struct_349',['5. The Game State Struct',['../examples_scrolling_continuous_scroll.html#autotoc_md1455',1,'']]],
  ['state_20survives_20between_20scenes_350',['🟡 Window state survives between scenes',['../tutorial_window.html#autotoc_md432',1,'']]],
  ['state_20transitions_351',['State Transitions',['../tutorial_game_states.html#autotoc_md185',1,'']]],
  ['states_352',['States',['../tutorial_game_states.html#autotoc_md187',1,'VRAM Reload Between States'],['../tutorial_game_states.html#autotoc_md182',1,'What Are Game States?']]],
  ['states_20and_20sprite_20sheets_353',['Animated Sprite -- Direction States and Sprite Sheets',['../examples_sprites_animated_sprite.html',1,'examples_sprites']]],
  ['states_20tutorial_354',['Game States Tutorial',['../tutorial_game_states.html',1,'index']]],
  ['static_20colour_20gradient_20—_20examples_20hdma_20gradient_5fcolors_355',['Static colour gradient — &lt;span class=&quot;tt&quot;&gt;examples/hdma/gradient_colors&lt;/span&gt;',['../tutorial_hdma.html#autotoc_md218',1,'']]],
  ['static_20moving_20layers_356',['Mixed Scroll (Static + Moving Layers)',['../tutorial_scrolling.html#autotoc_md350',1,'']]],
  ['static_20shapes_20vs_20animated_20shapes_357',['Static shapes vs animated shapes',['../tutorial_window.html#autotoc_md419',1,'']]],
  ['static_20variables_20with_20initializers_358',['Static variables with initializers',['../troubleshooting.html#autotoc_md624',1,'']]],
  ['static_20vs_20dynamic_20sprites_359',['Static vs Dynamic Sprites',['../examples_sprites_dynamic_sprite.html#autotoc_md1528',1,'']]],
  ['stationary_20window_20—_20examples_20windows_20window_360',['Stationary window — &lt;span class=&quot;tt&quot;&gt;examples/windows/window&lt;/span&gt;',['../tutorial_hdma.html#autotoc_md221',1,'']]],
  ['status_361',['Status',['../registers.html#autotoc_md731',1,'$4210 - RDNMI (NMI Status)'],['../registers.html#autotoc_md732',1,'$4211 - TIMEUP (IRQ Status)'],['../registers.html#autotoc_md733',1,'$4212 - HVBJOY (Blank/Joypad Status)']]],
  ['status_362',['Roadmap status',['../examples_games_shmup_1942.html#autotoc_md1171',1,'']]],
  ['status_20codes_363',['Status Codes',['../examples_chips_sa1_hello.html#autotoc_md1003',1,'Status Codes'],['../examples_chips_superfx_hello.html#autotoc_md1018',1,'Status Codes']]],
  ['stay_20in_20force_20blank_364',['1. Initialize and Stay in Force Blank',['../examples_backgrounds_mode1_lz77.html#autotoc_md913',1,'']]],
  ['steps_365',['Steps',['../examples.html#autotoc_md1437',1,'Level 1 &amp;ndash; First Steps'],['../tutorial_animation.html#autotoc_md93',1,'Next Steps'],['../tutorial_audio.html#autotoc_md110',1,'Next Steps'],['../tutorial_collision.html#autotoc_md135',1,'Next Steps'],['../tutorial_game_states.html#autotoc_md197',1,'Next Steps'],['../tutorial_graphics.html#autotoc_md209',1,'Next Steps'],['../tutorial_input.html#autotoc_md248',1,'Next Steps'],['../tutorial_scrolling.html#autotoc_md358',1,'Next Steps'],['../tutorial_sprites.html#autotoc_md376',1,'Next Steps']]],
  ['still_20for_366',['What Mesen2 is still for',['../tutorial_debugging.html#autotoc_md162',1,'']]],
  ['still_20missing_3a_20pow_20exp_20log_367',['What&apos;s still missing: &lt;span class=&quot;tt&quot;&gt;pow&lt;/span&gt;, &lt;span class=&quot;tt&quot;&gt;exp&lt;/span&gt;, &lt;span class=&quot;tt&quot;&gt;log&lt;/span&gt;',['../tutorial_math.html#autotoc_md281',1,'']]],
  ['stop_368',['2. NOP Padding Before STOP',['../tutorial_superfx.html#autotoc_md408',1,'']]],
  ['stopping_20movement_20slide_20along_20walls_369',['Stopping Movement (Slide Along Walls)',['../tutorial_collision.html#autotoc_md128',1,'']]],
  ['store_20pointers_20in_20sram_370',['🟠 Cannot store pointers in SRAM',['../tutorial_sram.html#autotoc_md392',1,'']]],
  ['story_371',['Why the envelope differs from the original (a true story)',['../examples_audio_pitch_mod.html#autotoc_md768',1,'']]],
  ['strange_372',['When the window register acts strange',['../tutorial_window.html#autotoc_md420',1,'']]],
  ['streaming_373',['Map Engine Streaming',['../examples_maps_tiled.html#autotoc_md1352',1,'']]],
  ['streaming_374',['When HDMA isn&apos;t enough: H-timer IRQ streaming',['../tutorial_hdma.html#autotoc_md226',1,'']]],
  ['streaming_20for_20animated_20sprites_375',['Dynamic Sprite -- VRAM Streaming for Animated Sprites',['../examples_sprites_dynamic_sprite.html',1,'examples_sprites']]],
  ['streaming_20pattern_376',['The Streaming Pattern',['../tutorial_scrolling.html#autotoc_md355',1,'']]],
  ['streaming_20tips_377',['Streaming Tips',['../tutorial_scrolling.html#autotoc_md356',1,'']]],
  ['streaming_3a_20the_20column_20pipeline_378',['3. Streaming: The Column Pipeline',['../examples_games_likemario.html#autotoc_md1125',1,'']]],
  ['streams_20m16_20background_20wants_20q16_379',['🟡 &lt;span class=&quot;tt&quot;&gt;map&lt;/span&gt; streams &lt;span class=&quot;tt&quot;&gt;.m16&lt;/span&gt;; &lt;span class=&quot;tt&quot;&gt;background&lt;/span&gt; wants &lt;span class=&quot;tt&quot;&gt;.q16&lt;/span&gt;',['../tutorial_map.html#autotoc_md258',1,'']]],
  ['stride_20to_20how_20the_20sheet_20was_20converted_380',['🟡 Match &lt;span class=&quot;tt&quot;&gt;base_tile&lt;/span&gt;/&lt;span class=&quot;tt&quot;&gt;stride&lt;/span&gt; to how the sheet was converted',['../tutorial_panel.html#autotoc_md324',1,'']]],
  ['string_381',['Print a string',['../examples_text_print_string.html',1,'examples_text']]],
  ['struct_382',['5. The Game State Struct',['../examples_scrolling_continuous_scroll.html#autotoc_md1455',1,'']]],
  ['struct_383',['The Scene struct',['../examples_basics_scene_stack.html#autotoc_md987',1,'']]],
  ['struct_20—_20the_20tilemap_20is_20yours_384',['The &lt;span class=&quot;tt&quot;&gt;Panel&lt;/span&gt; struct — the tilemap is yours',['../tutorial_panel.html#autotoc_md318',1,'']]],
  ['struct_20pattern_20required_385',['Struct Pattern (Required)',['../examples_input_two_players.html#autotoc_md1289',1,'']]],
  ['structure_386',['Structure',['../examples_sprites_metasprite.html#autotoc_md1535',1,'MetaspriteItem Structure'],['../tutorial_sprites.html#autotoc_md360',1,'OAM Structure'],['../oam.html#autotoc_md668',1,'OAM Structure'],['../getting_started.html#autotoc_md446',1,'Project Structure'],['../examples_backgrounds_mode1_bg3_priority.html#autotoc_md904',1,'Project Structure'],['../examples_backgrounds_mode1_lz77.html#autotoc_md918',1,'Project Structure'],['../examples_games_mapandobjects.html#autotoc_md1156',1,'Project Structure'],['../examples_hdma_gradient_colors.html#autotoc_md1195',1,'Project Structure'],['../examples_input_mouse.html#autotoc_md1254',1,'Project Structure'],['../examples_maps_dynamic_map.html#autotoc_md1327',1,'Project Structure'],['../examples_maps_slope_collision.html#autotoc_md1347',1,'Project Structure'],['../examples_maps_tiled.html#autotoc_md1355',1,'Project Structure'],['../examples_memory_hirom_demo.html#autotoc_md1372',1,'Project Structure'],['../examples_memory_save_game.html#autotoc_md1394',1,'Project Structure'],['../examples_mode7_perspective.html#autotoc_md1408',1,'Project Structure'],['../examples_mode7_rotate_scale.html#autotoc_md1433',1,'Project Structure'],['../examples_scrolling_mixed_scroll.html#autotoc_md1480',1,'Project Structure'],['../examples_scrolling_parallax_scroll.html#autotoc_md1494',1,'Project Structure'],['../examples_sprites_animated_sprite.html#autotoc_md1511',1,'Project Structure'],['../examples_sprites_dynamic_sprite.html#autotoc_md1530',1,'Project Structure'],['../examples_sprites_metasprite.html#autotoc_md1539',1,'Project Structure'],['../examples_sprites_simple_sprite.html#autotoc_md1557',1,'Project Structure'],['../examples_sprites_sprite_sizes.html#autotoc_md1572',1,'Project Structure'],['../examples_transitions_mosaic.html#autotoc_md1643',1,'Project Structure'],['../examples_windows_transparent_window.html#autotoc_md1659',1,'Project Structure'],['../examples_windows_window.html#autotoc_md1673',1,'Project Structure'],['../snes_graphics_guide.html#autotoc_md534',1,'Tilemap Structure']]],
  ['structure_387',['1. Define a save structure',['../examples_memory_save_game.html#autotoc_md1384',1,'']]],
  ['structure_20544_20bytes_20total_388',['OAM Structure (544 bytes total)',['../snes_graphics_guide.html#autotoc_md539',1,'']]],
  ['structure_209_20bytes_389',['Block Structure (9 bytes)',['../snes_sound_guide.html#autotoc_md584',1,'']]],
  ['stx_20l_20—_20save_20x_20through_20a_390',['No &lt;span class=&quot;tt&quot;&gt;stx.l&lt;/span&gt; — Save X Through A',['../tutorial_sa1.html#autotoc_md340',1,'']]],
  ['style_20demo_391',['mode7_flying — a Pilotwings-style demo',['../examples_games_mode7_flying.html',1,'examples_games']]],
  ['style_20guide_392',['OpenSNES Code Style Guide',['../code_style.html',1,'index']]],
  ['style_20mini_20game_393',['mode7_racing — an F-Zero-style mini game',['../examples_games_mode7_racing.html',1,'examples_games']]],
  ['sub_20mean_20here_394',['What &quot;main&quot; and &quot;sub&quot; mean here',['../tutorial_colormath.html#autotoc_md137',1,'']]],
  ['sub_20screen_395',['Sub Screen',['../examples_color_transparency.html#autotoc_md1053',1,'Color Math: Main Screen + Sub Screen'],['../colormath_8h.html#autotoc_md17',1,'Main Screen vs Sub Screen']]],
  ['sub_20screen_20enable_396',['$212D - TS (Sub Screen Enable)',['../registers.html#autotoc_md725',1,'']]],
  ['sub_20screen_20only_20trap_397',['🔴 The &quot;BG2 is sub-screen-only&quot; trap',['../tutorial_colormath.html#autotoc_md146',1,'']]],
  ['submitting_20code_398',['Submitting Code',['../contributing.html#autotoc_md1693',1,'']]],
  ['suggesting_20features_399',['Suggesting Features',['../contributing.html#autotoc_md1692',1,'']]],
  ['summary_400',['State Machine Summary',['../tutorial_game_states.html#autotoc_md196',1,'']]],
  ['summary_401',['Cycle cost summary',['../tutorial_math.html#autotoc_md282',1,'']]],
  ['super_20scope_402',['Super Scope',['../examples_input_superscope.html',1,'examples_input']]],
  ['superfree_20assets_20in_20any_20bank_20just_20work_403',['🟢 SUPERFREE assets in any bank just work',['../tutorial_dma.html#autotoc_md175',1,'']]],
  ['superfx_404',['What Is SuperFX?',['../tutorial_superfx.html#autotoc_md398',1,'']]],
  ['superfx_203d_20cube_405',['SuperFX 3D Cube',['../examples_chips_superfx_3d.html',1,'examples_chips']]],
  ['superfx_20assembly_20rules_406',['SuperFX Assembly Rules',['../tutorial_superfx.html#autotoc_md406',1,'']]],
  ['superfx_20cartridge_407',['SuperFX Cartridge',['../memory_map.html#autotoc_md666',1,'']]],
  ['superfx_20gsu_408',['SuperFX (GSU)',['../examples_by_category.html#autotoc_md506',1,'']]],
  ['superfx_20gsu_20registers_20_243000_20_24303f_409',['SuperFX / GSU Registers ($3000-$303F)',['../registers.html#autotoc_md758',1,'']]],
  ['superfx_20gsu_20tutorial_410',['SuperFX (GSU) Tutorial',['../tutorial_superfx.html',1,'index']]],
  ['superfx_20hello_411',['SuperFX Hello',['../examples_chips_superfx_hello.html',1,'examples_chips']]],
  ['superfx_20in_20your_20makefile_412',['1. Enable SuperFX in Your Makefile',['../tutorial_superfx.html#autotoc_md401',1,'']]],
  ['support_413',['Multitap Support',['../examples_input_two_players.html#autotoc_md1314',1,'']]],
  ['surfaced_414',['surfaced',['../examples_mode7_perspective_rotate.html#autotoc_md1414',1,'Two integration lessons this port surfaced'],['../examples_color_hicolor_1792.html#autotoc_md1030',1,'Two SDK bugs this port surfaced']]],
  ['survives_20a_20dialog_20box_415',['panel_hud — a HUD that survives a dialog box',['../examples_basics_panel_hud.html',1,'examples_basics']]],
  ['survives_20between_20scenes_416',['🟡 Window state survives between scenes',['../tutorial_window.html#autotoc_md432',1,'']]],
  ['swap_20tilemap_20entries_417',['Approach 1: Swap Tilemap Entries',['../tutorial_animation.html#autotoc_md88',1,'']]],
  ['swapping_20apu_20programs_418',['Hot-swapping APU programs',['../tutorial_audio.html#autotoc_md113',1,'']]],
  ['swapping_20apu_20programs_20at_20runtime_419',['apu_switch — hot-swapping APU programs at runtime',['../examples_audio_apu_switch.html',1,'examples_audio']]],
  ['swarm_20and_20the_20oam_20throughput_20ceiling_420',['sprite_swarm — a bouncing swarm, and the OAM throughput ceiling',['../examples_sprites_sprite_swarm.html',1,'examples_sprites']]],
  ['switch_421',['Why a framework instead of a switch',['../examples_basics_scene_stack.html#autotoc_md989',1,'']]],
  ['switching_20layers_422',['Switching Layers',['../examples_windows_window.html#autotoc_md1668',1,'']]],
  ['switching_20mid_20frame_423',['Mode Switching Mid-Frame',['../examples_mode7_perspective.html#autotoc_md1405',1,'']]],
  ['symbols_424',['Working with symbols',['../tutorial_debugging.html#autotoc_md155',1,'']]],
  ['sync_425',['4. Main Loop: Update, Draw, Sync',['../examples_games_mapandobjects.html#autotoc_md1154',1,'']]],
  ['sync_20producer_20consumer_426',['Pattern 1: Flag Sync (Producer/Consumer)',['../tutorial_sa1.html#autotoc_md334',1,'']]],
  ['system_427',['System',['../examples_games_mapandobjects.html#autotoc_md1151',1,'1. Initialize the Map and Sprite System'],['../snes_sound_guide.html#autotoc_md594',1,'Echo System'],['../examples_backgrounds_mode1_bg3_priority.html#autotoc_md900',1,'Mode 1 Priority System'],['../examples_windows_window.html#autotoc_md1664',1,'SNES Window System']]],
  ['system_428',['Coordinate system',['../tutorial_mode7.html#autotoc_md288',1,'']]],
  ['system_20bg1_429',['2. Text System (BG1)',['../examples_input_superscope.html#autotoc_md1268',1,'']]],
  ['systems_430',['Memory Systems',['../snes_graphics_guide.html#autotoc_md528',1,'']]]
];
