var searchData=
[
  ['t_20appear_0',['Sprites don&apos;t appear',['../troubleshooting.html#autotoc_md616',1,'']]],
  ['t_20configured_1',['🟡 Don&apos;t enable channels you haven&apos;t configured',['../tutorial_hdma.html#autotoc_md232',1,'']]],
  ['t_20do_2',['What SA-1 Can&apos;t Do',['../tutorial_sa1.html#autotoc_md344',1,'']]],
  ['t_20double_20up_3',['🟠 OAM DMA is automated, don&apos;t double-up',['../tutorial_dma.html#autotoc_md177',1,'']]],
  ['t_20enable_20channels_20you_20haven_20t_20configured_4',['🟡 Don&apos;t enable channels you haven&apos;t configured',['../tutorial_hdma.html#autotoc_md232',1,'']]],
  ['t_20enough_3a_20h_20timer_20irq_20streaming_5',['When HDMA isn&apos;t enough: H-timer IRQ streaming',['../tutorial_hdma.html#autotoc_md226',1,'']]],
  ['t_20have_20to_20think_20about_20it_6',['🟠 Endianness — but you don&apos;t have to think about it',['../tutorial_sram.html#autotoc_md393',1,'']]],
  ['t_20loop_20over_20100_20bricks_7',['5. Grid Collision (Don&apos;t Loop Over 100 Bricks)',['../examples_games_breakout.html#autotoc_md900',1,'']]],
  ['table_8',['Table',['../examples_graphics_effects_parallax_scrolling.html#autotoc_md1264',1,'HDMA Scroll Table'],['../examples_graphics_effects_hdma_wave_table.html',1,'HDMA Wave Table'],['../examples_graphics_sprites_object_size.html#autotoc_md1391',1,'OAM High Table']]],
  ['table_9',['2. The gradient table',['../examples_graphics_effects_gradient_colors.html#autotoc_md1180',1,'']]],
  ['table_202_20bits_20per_20sprite_10',['Extended Table (2 bits per sprite)',['../oam.html#autotoc_md659',1,'']]],
  ['table_204_20bytes_20per_20sprite_11',['Main Table (4 bytes per sprite)',['../oam.html#autotoc_md657',1,'']]],
  ['table_20format_12',['Table Format',['../examples_graphics_effects_hdma_wave.html#autotoc_md1202',1,'2. The HDMA Table Format'],['../hdma_8h.html#autotoc_md30',1,'Table Format']]],
  ['table_20format_13',['Table format',['../tutorial_hdma.html#autotoc_md213',1,'']]],
  ['table_20generation_14',['HDMA gradient table generation',['../tutorial_math.html#autotoc_md271',1,'']]],
  ['table_20lookups_20with_20lda_20l_20table_20x_15',['ROM Table Lookups with &lt;span class=&quot;tt&quot;&gt;lda.l table,x&lt;/span&gt;',['../tutorial_sa1.html#autotoc_md339',1,'']]],
  ['table_20of_20contents_16',['Table of Contents',['../snes_graphics_guide.html#autotoc_md513',1,'Table of Contents'],['../snes_sound_guide.html#autotoc_md557',1,'Table of Contents'],['../registers.html#autotoc_md688',1,'Table of Contents']]],
  ['table_20repointing_20as_20animation_20—_20examples_20graphics_20effects_20hdma_5fwave_5ftable_17',['Table repointing as animation — &lt;span class=&quot;tt&quot;&gt;examples/graphics/effects/hdma_wave_table&lt;/span&gt;',['../tutorial_hdma.html#autotoc_md223',1,'']]],
  ['table_20x_18',['ROM Table Lookups with &lt;span class=&quot;tt&quot;&gt;lda.l table,x&lt;/span&gt;',['../tutorial_sa1.html#autotoc_md339',1,'']]],
  ['tables_19',['The Triangle Tables',['../examples_graphics_effects_window.html#autotoc_md1320',1,'']]],
  ['tables_20',['Trigonometry (sin/cos lookup tables)',['../tutorial_math.html#autotoc_md264',1,'']]],
  ['target_20branch_21',['Target branch',['../contributing.html#autotoc_md1673',1,'']]],
  ['target_20common_20mk_22',['&quot;OPENSNES not defined&quot; or &quot;No rule to make target &apos;common.mk&apos;&quot;',['../troubleshooting.html#autotoc_md607',1,'']]],
  ['target_20since_20chantier_20a1_23',['🟢 &lt;span class=&quot;tt&quot;&gt;int&lt;/span&gt; and &lt;span class=&quot;tt&quot;&gt;long&lt;/span&gt; sizes are correct on this target (since chantier A1)',['../tutorial_math.html#autotoc_md273',1,'']]],
  ['targets_20cgadd_20_242121_24',['1. HDMA targets CGADD ($2121)',['../examples_graphics_effects_gradient_colors.html#autotoc_md1179',1,'']]],
  ['technical_20notes_25',['Technical Notes',['../examples_audio_snesmod_music.html#autotoc_md804',1,'Technical Notes'],['../examples_graphics_backgrounds_mode1.html#autotoc_md1054',1,'Technical Notes'],['../examples_graphics_effects_fading.html#autotoc_md1164',1,'Technical Notes'],['../examples_input_two_players.html#autotoc_md1495',1,'Technical Notes']]],
  ['technical_20reference_26',['Technical Reference',['../examples_games_breakout.html#autotoc_md916',1,'Technical Reference'],['../examples_games_likemario.html#autotoc_md942',1,'Technical Reference'],['../examples_graphics_backgrounds_continuous_scroll.html#autotoc_md1003',1,'Technical Reference'],['../examples_graphics_effects_hdma_wave.html#autotoc_md1217',1,'Technical Reference'],['../examples_input_superscope.html#autotoc_md1458',1,'Technical Reference'],['../examples_text_hello_world.html#autotoc_md1632',1,'Technical Reference']]],
  ['technique_27',['Technique',['../examples_graphics_effects_parallax_scrolling.html#autotoc_md1263',1,'The Parallax Technique'],['../examples_graphics_effects_transparent_window.html#autotoc_md1306',1,'The Technique']]],
  ['template_20driven_20by_20a_20tiled_20map_28',['rpg — an RPG template driven by a Tiled map',['../examples_games_rpg.html',1,'examples_games']]],
  ['temporal_20artefacts_20flicker_20page_20flip_20desync_29',['Recipe 6 — Temporal artefacts (flicker, page-flip desync)',['../tutorial_debugging.html#autotoc_md161',1,'']]],
  ['test_30',['Test',['../tutorial_collision.html#autotoc_md118',1,'Basic Overlap Test'],['../examples_text_text_test.html',1,'Text Module Test']]],
  ['test_20driven_31',['The debugging archaeology (all owner-listening-test driven)',['../examples_audio_speech_synth.html#autotoc_md838',1,'']]],
  ['test_20your_20game_32',['Test Your Game',['../getting_started.html#autotoc_md447',1,'']]],
  ['testing_33',['Testing',['../contributing.html#autotoc_md1677',1,'']]],
  ['testing_20multiple_20enemies_34',['Testing Multiple Enemies',['../tutorial_collision.html#autotoc_md119',1,'']]],
  ['tests_35',['B3. Run Tests',['../getting_started.html#autotoc_md452',1,'']]],
  ['tetris_36',['Tetris',['../tutorial_game_states.html#autotoc_md194',1,'Restart Game Over (Tetris)'],['../examples_games_tetris.html',1,'Tetris']]],
  ['text_37',['Text',['../examples_by_category.html#autotoc_md474',1,'Text'],['../examples_text.html#autotoc_md1638',1,'VRAM Layout for Text']]],
  ['text_20—_20bg_20mode_205_20interlace_20512_20×_20448_38',['Hi-res text — BG Mode 5 + interlace (512 × 448)',['../examples_graphics_effects_hires_text.html',1,'examples_graphics_effects']]],
  ['text_20and_20detect_20mouse_39',['1. Initialize Text and Detect Mouse',['../examples_input_mouse.html#autotoc_md1433',1,'']]],
  ['text_20and_20load_20font_40',['3. Initialize Text and Load Font',['../examples_text_text_test.html#autotoc_md1650',1,'']]],
  ['text_20display_41',['Text Display',['../examples_audio_snesmod_sfx.html#autotoc_md829',1,'']]],
  ['text_20display_42',['5. Text display',['../examples_memory_save_game.html#autotoc_md1586',1,'']]],
  ['text_20examples_43',['Text Examples',['../examples_text.html',1,'examples']]],
  ['text_20goes_20on_20a_20different_20layer_20above_20the_20panel_44',['🟡 Text goes on a &lt;em&gt;different&lt;/em&gt; layer, above the panel',['../tutorial_panel.html#autotoc_md323',1,'']]],
  ['text_20module_20test_45',['Text Module Test',['../examples_text_text_test.html',1,'examples_text']]],
  ['text_20on_20bg1_204bpp_20in_20mode_201_46',['1. Set up text on BG1 (4bpp in Mode 1)',['../examples_graphics_sprites_object_size.html#autotoc_md1385',1,'']]],
  ['text_20rendering_20on_20the_20snes_47',['Text Rendering on the SNES',['../examples_text_text_test.html#autotoc_md1643',1,'']]],
  ['text_20system_20bg1_48',['2. Text System (BG1)',['../examples_input_superscope.html#autotoc_md1451',1,'']]],
  ['text_20works_20on_20snes_49',['How Text Works on SNES',['../examples_text.html#autotoc_md1636',1,'']]],
  ['than_20the_20screen_50',['1. The World Is Bigger Than the Screen',['../examples_games_likemario.html#autotoc_md924',1,'']]],
  ['that_20cracked_20it_51',['Debug tooling that cracked it',['../examples_audio_speech_synth.html#autotoc_md839',1,'']]],
  ['the_206_20size_20modes_52',['The 6 Size Modes',['../examples_graphics_sprites_object_size.html#autotoc_md1388',1,'']]],
  ['the_208_208_20fixed_20point_20format_53',['The 8.8 fixed-point format',['../tutorial_math.html#autotoc_md261',1,'']]],
  ['the_208_20transfer_20modes_54',['The 8 transfer modes',['../tutorial_dma.html#autotoc_md166',1,'']]],
  ['the_20anim_20module_20recommended_55',['The anim Module (Recommended)',['../tutorial_animation.html#autotoc_md68',1,'']]],
  ['the_20audio_20module_20v2_20—_20samples_20and_20effects_20from_20pure_20c_56',['The audio module (v2) — samples and effects from pure C',['../tutorial_audio.html#autotoc_md111',1,'']]],
  ['the_20audio_20v2_20engine_20driven_20entirely_20from_20c_57',['soundboard — the audio v2 engine, driven entirely from C',['../examples_audio_soundboard.html',1,'examples_audio']]],
  ['the_20backdrop_58',['🟡 Colour-math on the backdrop',['../tutorial_colormath.html#autotoc_md149',1,'']]],
  ['the_20backdrop_20not_20a_20layer_59',['🟡 Out-of-bounds with &lt;span class=&quot;tt&quot;&gt;MODE7_TRANSPARENT&lt;/span&gt; shows the backdrop, not a layer',['../tutorial_mode7.html#autotoc_md300',1,'']]],
  ['the_20bg2_20is_20sub_20screen_20only_20trap_60',['🔴 The &quot;BG2 is sub-screen-only&quot; trap',['../tutorial_colormath.html#autotoc_md146',1,'']]],
  ['the_20build_61',['The Build',['../examples_games_breakout.html#autotoc_md910',1,'Under the Hood: The Build'],['../examples_games_likemario.html#autotoc_md936',1,'Under the Hood: The Build'],['../examples_graphics_backgrounds_continuous_scroll.html#autotoc_md999',1,'Under the Hood: The Build'],['../examples_graphics_effects_hdma_wave.html#autotoc_md1212',1,'Under the Hood: The Build'],['../examples_input_superscope.html#autotoc_md1457',1,'Under the Hood: The Build'],['../examples_text_hello_world.html#autotoc_md1627',1,'Under the Hood: The Build']]],
  ['the_20checkerboard_20background_62',['6. The Checkerboard Background',['../examples_graphics_effects_hdma_wave.html#autotoc_md1206',1,'']]],
  ['the_20clip_20and_20ticking_63',['Selecting the Clip and Ticking',['../tutorial_animation.html#autotoc_md79',1,'']]],
  ['the_20code_20is_20identical_20to_20lorom_64',['2. The code is identical to LoROM',['../examples_memory_hirom_demo.html#autotoc_md1555',1,'']]],
  ['the_20color_65',['direct_color — the pixel byte IS the color',['../examples_graphics_effects_direct_color.html',1,'examples_graphics_effects']]],
  ['the_20column_20pipeline_66',['3. Streaming: The Column Pipeline',['../examples_games_likemario.html#autotoc_md926',1,'']]],
  ['the_20conversion_20macros_67',['The conversion macros',['../tutorial_math.html#autotoc_md262',1,'']]],
  ['the_20data_20lives_68',['Where the Data Lives',['../examples_graphics_effects_hdma_wave.html#autotoc_md1214',1,'']]],
  ['the_20debugging_20archaeology_20all_20owner_20listening_20test_20driven_69',['The debugging archaeology (all owner-listening-test driven)',['../examples_audio_speech_synth.html#autotoc_md838',1,'']]],
  ['the_20dma_20channels_70',['The DMA channels',['../tutorial_dma.html#autotoc_md165',1,'']]],
  ['the_20dynamic_20sprite_20engine_71',['The Dynamic Sprite Engine',['../tutorial_animation.html#autotoc_md80',1,'']]],
  ['the_20dynamic_20sprite_20engine_72',['1. Initialize the dynamic sprite engine',['../examples_graphics_sprites_dynamic_sprite.html#autotoc_md1362',1,'']]],
  ['the_20envelope_20differs_20from_20the_20original_20a_20true_20story_73',['Why the envelope differs from the original (a true story)',['../examples_audio_pitch_mod.html#autotoc_md751',1,'']]],
  ['the_20exclusive_20bus_74',['The Exclusive Bus',['../tutorial_superfx.html#autotoc_md405',1,'']]],
  ['the_20four_20channel_20registers_75',['The four channel registers',['../tutorial_hdma.html#autotoc_md211',1,'']]],
  ['the_20full_20matrix_20per_20scanline_76',['Mode 7 rotating perspective — the full matrix, per scanline',['../examples_graphics_effects_mode7_perspective_rotate.html',1,'examples_graphics_effects']]],
  ['the_20game_20loop_77',['The Game Loop',['../examples_games_breakout.html#autotoc_md904',1,'9. The Game Loop'],['../tutorial_animation.html#autotoc_md84',1,'The Game Loop']]],
  ['the_20game_20state_20struct_78',['5. The Game State Struct',['../examples_graphics_backgrounds_continuous_scroll.html#autotoc_md993',1,'']]],
  ['the_20gate_20to_20colour_20math_79',['🟠 &lt;span class=&quot;tt&quot;&gt;windowEnable(window, WINDOW_MATH)&lt;/span&gt; is the gate to colour math',['../tutorial_window.html#autotoc_md430',1,'']]],
  ['the_20gradient_20table_80',['2. The gradient table',['../examples_graphics_effects_gradient_colors.html#autotoc_md1180',1,'']]],
  ['the_20gsu_20loader_2065816_20asm_81',['3. Create the GSU Loader (65816 ASM)',['../tutorial_superfx.html#autotoc_md403',1,'']]],
  ['the_20hdma_20channel_82',['4. Setting Up the HDMA Channel',['../examples_graphics_effects_hdma_wave.html#autotoc_md1204',1,'']]],
  ['the_20hdma_20table_20format_83',['2. The HDMA Table Format',['../examples_graphics_effects_hdma_wave.html#autotoc_md1202',1,'']]],
  ['the_20hood_84',['The manual state machine (under the hood)',['../tutorial_game_states.html#autotoc_md184',1,'']]],
  ['the_20hood_3a_20the_20build_85',['the Hood: The Build',['../examples_games_breakout.html#autotoc_md910',1,'Under the Hood: The Build'],['../examples_games_likemario.html#autotoc_md936',1,'Under the Hood: The Build'],['../examples_graphics_backgrounds_continuous_scroll.html#autotoc_md999',1,'Under the Hood: The Build'],['../examples_graphics_effects_hdma_wave.html#autotoc_md1212',1,'Under the Hood: The Build'],['../examples_input_superscope.html#autotoc_md1457',1,'Under the Hood: The Build'],['../examples_text_hello_world.html#autotoc_md1627',1,'Under the Hood: The Build']]],
  ['the_20interleaved_20vram_20format_86',['The interleaved VRAM format',['../tutorial_mode7.html#autotoc_md286',1,'']]],
  ['the_20lib_20api_87',['The lib API',['../tutorial_colormath.html#autotoc_md141',1,'The lib API'],['../tutorial_mosaic.html#autotoc_md307',1,'The lib API'],['../tutorial_sram.html#autotoc_md382',1,'The lib API'],['../tutorial_window.html#autotoc_md424',1,'The lib API']]],
  ['the_20lib_20chantier_20b6_202026_2005_2009_88',['&lt;span class=&quot;tt&quot;&gt;atan2&lt;/span&gt; and &lt;span class=&quot;tt&quot;&gt;sqrt&lt;/span&gt; ship in the lib (chantier B6, 2026-05-09)',['../tutorial_math.html#autotoc_md280',1,'']]],
  ['the_20lib_20helpers_20and_20what_20they_20do_89',['The lib helpers and what they do',['../tutorial_mode7.html#autotoc_md290',1,'']]],
  ['the_20long_20way_90',['Manual setup (the long way)',['../getting_started.html#autotoc_md445',1,'']]],
  ['the_20machine_20at_20a_20point_20in_20time_91',['Recipe 1 — Inspect the machine at a point in time',['../tutorial_debugging.html#autotoc_md156',1,'']]],
  ['the_20mailbox_92',['I-RAM — The Mailbox',['../tutorial_sa1.html#autotoc_md328',1,'']]],
  ['the_20main_20loop_93',['7. The Main Loop',['../examples_games_likemario.html#autotoc_md930',1,'']]],
  ['the_20main_20loop_94',['Per-frame DMA in the main loop',['../tutorial_dma.html#autotoc_md170',1,'']]],
  ['the_20makefile_95',['The Makefile',['../examples_games_breakout.html#autotoc_md911',1,'The Makefile'],['../examples_games_likemario.html#autotoc_md937',1,'The Makefile'],['../examples_graphics_backgrounds_continuous_scroll.html#autotoc_md1000',1,'The Makefile'],['../examples_graphics_effects_hdma_wave.html#autotoc_md1213',1,'The Makefile'],['../examples_text_hello_world.html#autotoc_md1629',1,'The Makefile']]],
  ['the_20makefile_96',['the Makefile',['../examples_memory_hirom_demo.html#autotoc_md1554',1,'1. Enable HiROM in the Makefile'],['../examples_memory_save_game.html#autotoc_md1585',1,'4. Enable SRAM in the Makefile']]],
  ['the_20manual_20state_20machine_20under_20the_20hood_97',['The manual state machine (under the hood)',['../tutorial_game_states.html#autotoc_md184',1,'']]],
  ['the_20map_98',['the map',['../tutorial_map.html#autotoc_md252',1,'Collision against the map'],['../examples_games_rpg.html#autotoc_md969',1,'Editing the map']]],
  ['the_20map_20and_20sprite_20system_99',['1. Initialize the Map and Sprite System',['../examples_games_mapandobjects.html#autotoc_md952',1,'']]],
  ['the_20map_20engine_100',['The Map Engine',['../examples_maps_slopemario.html#autotoc_md1531',1,'']]],
  ['the_20map_20module_20is_101',['What the map module is',['../tutorial_map.html#autotoc_md249',1,'']]],
  ['the_20matrix_20and_20the_20registers_102',['The matrix and the registers',['../tutorial_mode7.html#autotoc_md285',1,'']]],
  ['the_20matrix_20every_20frame_103',['3. Update the matrix every frame',['../examples_graphics_backgrounds_mode7.html#autotoc_md1104',1,'']]],
  ['the_20message_104',['6. Spelling the Message',['../examples_text_hello_world.html#autotoc_md1620',1,'']]],
  ['the_20minimum_20viable_20colour_20math_105',['The minimum viable colour math',['../tutorial_colormath.html#autotoc_md138',1,'']]],
  ['the_20minimum_20viable_20dialog_20box_106',['The minimum viable dialog box',['../tutorial_panel.html#autotoc_md319',1,'']]],
  ['the_20minimum_20viable_20mosaic_107',['The minimum viable mosaic',['../tutorial_mosaic.html#autotoc_md305',1,'']]],
  ['the_20minimum_20viable_20save_108',['The minimum viable save',['../tutorial_sram.html#autotoc_md383',1,'']]],
  ['the_20minimum_20viable_20scroller_109',['The minimum viable scroller',['../tutorial_map.html#autotoc_md251',1,'']]],
  ['the_20minimum_20viable_20window_110',['The minimum viable window',['../tutorial_window.html#autotoc_md418',1,'']]],
  ['the_20name_5fbase_20argument_20is_20a_20page_20number_20not_20a_20vram_20address_111',['The &lt;span class=&quot;tt&quot;&gt;name_base&lt;/span&gt; argument is a page number, not a VRAM address',['../tutorial_sprites.html#autotoc_md366',1,'']]],
  ['the_20nmi_20handler_112',['🟡 HDMA fires before the user callback in the NMI handler',['../tutorial_hdma.html#autotoc_md231',1,'']]],
  ['the_20oambuffer_113',['2. Set up sprites via the oambuffer',['../examples_graphics_sprites_dynamic_sprite.html#autotoc_md1363',1,'']]],
  ['the_20original_114',['the original',['../examples_audio_speech_synth.html#autotoc_md837',1,'Register fidelity vs the original'],['../examples_graphics_effects_gradient_9bit.html#autotoc_md1171',1,'Register fidelity vs the original'],['../examples_graphics_effects_hicolor_1792.html#autotoc_md1224',1,'Register fidelity vs the original'],['../examples_graphics_effects_hicolor_hires.html#autotoc_md1230',1,'Register fidelity vs the original'],['../examples_graphics_effects_hires_text.html#autotoc_md1234',1,'Register fidelity vs the original'],['../examples_graphics_effects_mode7_perspective_rotate.html#autotoc_md1240',1,'Register fidelity vs the original'],['../examples_graphics_effects_window_multi_hdma.html#autotoc_md1330',1,'Register fidelity vs the original']]],
  ['the_20original_20a_20true_20story_115',['Why the envelope differs from the original (a true story)',['../examples_audio_pitch_mod.html#autotoc_md751',1,'']]],
  ['the_20original_20measured_20not_20assumed_116',['the original measured not assumed',['../examples_graphics_effects_hdma_indirect_gradient.html#autotoc_md1192',1,'Fidelity to the original (measured, not assumed)'],['../examples_graphics_effects_hdma_wave_table.html#autotoc_md1219',1,'Fidelity to the original (measured, not assumed)']]],
  ['the_20panel_117',['🟡 Text goes on a &lt;em&gt;different&lt;/em&gt; layer, above the panel',['../tutorial_panel.html#autotoc_md323',1,'']]],
  ['the_20panel_20struct_20—_20the_20tilemap_20is_20yours_118',['The &lt;span class=&quot;tt&quot;&gt;Panel&lt;/span&gt; struct — the tilemap is yours',['../tutorial_panel.html#autotoc_md318',1,'']]],
  ['the_20parallax_20technique_119',['The Parallax Technique',['../examples_graphics_effects_parallax_scrolling.html#autotoc_md1263',1,'']]],
  ['the_20pipeline_120',['The Pipeline',['../examples_text_hello_world.html#autotoc_md1628',1,'']]],
  ['the_20pixel_20byte_20is_20the_20color_121',['direct_color — the pixel byte IS the color',['../examples_graphics_effects_direct_color.html',1,'examples_graphics_effects']]],
  ['the_20pointer_122',['5. Animation = Just Move the Pointer',['../examples_graphics_effects_hdma_wave.html#autotoc_md1205',1,'']]],
  ['the_20ppu_123',['3. Setting Up the PPU',['../examples_text_hello_world.html#autotoc_md1617',1,'']]],
  ['the_20problem_124',['The Problem',['../oam.html#autotoc_md661',1,'']]],
  ['the_20ram_20buffer_20pattern_125',['3. ROM is Read-Only (The RAM Buffer Pattern)',['../examples_games_breakout.html#autotoc_md898',1,'']]],
  ['the_20raw_20apu_20path_20no_20snesmod_126',['The raw APU path (no snesmod)',['../tutorial_audio.html#autotoc_md112',1,'']]],
  ['the_20rect_20type_127',['The Rect Type',['../tutorial_collision.html#autotoc_md116',1,'']]],
  ['the_20registers_128',['The matrix and the registers',['../tutorial_mode7.html#autotoc_md285',1,'']]],
  ['the_20scene_20stack_20recommended_20—_20scene_20module_129',['The scene stack (recommended) — &lt;span class=&quot;tt&quot;&gt;scene&lt;/span&gt; module',['../tutorial_game_states.html#autotoc_md183',1,'']]],
  ['the_20scene_20struct_130',['The Scene struct',['../examples_basics_scene_stack.html#autotoc_md879',1,'']]],
  ['the_20screen_131',['1. The World Is Bigger Than the Screen',['../examples_games_likemario.html#autotoc_md924',1,'']]],
  ['the_20screen_20centre_132',['🟡 Centre default is the tilemap centre, not the screen centre',['../tutorial_mode7.html#autotoc_md299',1,'']]],
  ['the_20setup_20pattern_133',['The setup pattern',['../tutorial_dma.html#autotoc_md169',1,'']]],
  ['the_20sheet_20was_20converted_134',['🟡 Match &lt;span class=&quot;tt&quot;&gt;base_tile&lt;/span&gt;/&lt;span class=&quot;tt&quot;&gt;stride&lt;/span&gt; to how the sheet was converted',['../tutorial_panel.html#autotoc_md324',1,'']]],
  ['the_20shipped_20example_135',['the shipped example',['../tutorial_mosaic.html#autotoc_md308',1,'Worked pattern (the shipped example)'],['../tutorial_sram.html#autotoc_md386',1,'Worked pattern (the shipped example)']]],
  ['the_20shipped_20examples_136',['the shipped examples',['../tutorial_hdma.html#autotoc_md215',1,'Worked patterns (the shipped examples)'],['../tutorial_map.html#autotoc_md254',1,'Worked patterns (the shipped examples)'],['../tutorial_window.html#autotoc_md425',1,'Worked patterns (the shipped examples)']]],
  ['the_20snes_137',['the SNES',['../examples_input_controller.html#autotoc_md1421',1,'How Input Works on the SNES'],['../examples_text_text_test.html#autotoc_md1643',1,'Text Rendering on the SNES'],['../tutorial_math.html#autotoc_md260',1,'Why fixed-point on the SNES']]],
  ['the_20snes_20says_20open_20snes_138',['speech_synth — the SNES says &quot;OPEN SNES&quot;',['../examples_audio_speech_synth.html',1,'examples_audio']]],
  ['the_20solution_139',['The Solution',['../oam.html#autotoc_md662',1,'']]],
  ['the_20soundbank_140',['The Soundbank',['../examples_audio_snesmod_sfx.html#autotoc_md828',1,'']]],
  ['the_20sprite_141',['4. Place the sprite',['../examples_graphics_sprites_simple_sprite.html#autotoc_md1410',1,'']]],
  ['the_20sprite_20is_20vs_20where_20it_20collides_142',['Where the sprite is vs where it collides',['../tutorial_collision.html#autotoc_md126',1,'']]],
  ['the_20sprite_20palette_143',['2. Load the sprite palette',['../examples_graphics_sprites_simple_sprite.html#autotoc_md1408',1,'']]],
  ['the_20sprite_20size_144',['Converting a sheet: &lt;span class=&quot;tt&quot;&gt;-s&lt;/span&gt; must match the sprite size',['../tutorial_sprites.html#autotoc_md368',1,'']]],
  ['the_20streaming_20pattern_145',['The Streaming Pattern',['../tutorial_scrolling.html#autotoc_md355',1,'']]],
  ['the_20technique_146',['The Technique',['../examples_graphics_effects_transparent_window.html#autotoc_md1306',1,'']]],
  ['the_20threshold_20scroll_20pattern_147',['2. The Threshold Scroll Pattern',['../examples_graphics_backgrounds_continuous_scroll.html#autotoc_md990',1,'']]],
  ['the_20tiled_20pipeline_148',['The Tiled pipeline',['../tutorial_map.html#autotoc_md250',1,'']]],
  ['the_20tiled_20workflow_149',['The Tiled Workflow',['../examples_maps_tiled.html#autotoc_md1540',1,'']]],
  ['the_20tilemap_20centre_20not_20the_20screen_20centre_150',['🟡 Centre default is the tilemap centre, not the screen centre',['../tutorial_mode7.html#autotoc_md299',1,'']]],
  ['the_20tilemap_20is_20yours_151',['The &lt;span class=&quot;tt&quot;&gt;Panel&lt;/span&gt; struct — the tilemap is yours',['../tutorial_panel.html#autotoc_md318',1,'']]],
  ['the_20transformation_152',['2. Initialize the transformation',['../examples_graphics_backgrounds_mode7.html#autotoc_md1103',1,'']]],
  ['the_20triangle_20tables_153',['The Triangle Tables',['../examples_graphics_effects_window.html#autotoc_md1320',1,'']]],
  ['the_20two_20shipped_20examples_154',['the two shipped examples',['../tutorial_colormath.html#autotoc_md142',1,'Worked patterns (the two shipped examples)'],['../tutorial_mode7.html#autotoc_md291',1,'Worked patterns (the two shipped examples)']]],
  ['the_20user_20callback_20in_20the_20nmi_20handler_155',['🟡 HDMA fires before the user callback in the NMI handler',['../tutorial_hdma.html#autotoc_md231',1,'']]],
  ['the_20vram_20layout_156',['2. The VRAM Layout',['../examples_games_likemario.html#autotoc_md925',1,'']]],
  ['the_20vram_20map_20—_20a_20deliberate_20overlap_157',['2. The VRAM Map — A Deliberate Overlap',['../examples_games_breakout.html#autotoc_md897',1,'']]],
  ['the_20window_20gate_158',['The window gate',['../tutorial_colormath.html#autotoc_md140',1,'']]],
  ['the_20window_20logic_20op_20trap_159',['The window logic op trap',['../tutorial_window.html#autotoc_md423',1,'']]],
  ['the_20window_20register_20acts_20strange_160',['When the window register acts strange',['../tutorial_window.html#autotoc_md420',1,'']]],
  ['the_20world_20is_20bigger_20than_20the_20screen_161',['1. The World Is Bigger Than the Screen',['../examples_games_likemario.html#autotoc_md924',1,'']]],
  ['there_20is_20no_20printf_162',['1. There Is No printf',['../examples_text_hello_world.html#autotoc_md1615',1,'']]],
  ['these_20demonstrate_163',['What These Demonstrate',['../examples_games.html#autotoc_md966',1,'']]],
  ['these_20modules_164',['These Modules',['../examples_games_breakout.html#autotoc_md914',1,'Why These Modules?'],['../examples_graphics_backgrounds_continuous_scroll.html#autotoc_md1001',1,'Why These Modules?'],['../examples_graphics_effects_hdma_wave.html#autotoc_md1215',1,'Why These Modules?'],['../examples_text_hello_world.html#autotoc_md1630',1,'Why These Modules?']]],
  ['they_20do_165',['The lib helpers and what they do',['../tutorial_mode7.html#autotoc_md290',1,'']]],
  ['think_20about_20it_166',['🟠 Endianness — but you don&apos;t have to think about it',['../tutorial_sram.html#autotoc_md393',1,'']]],
  ['third_20party_20components_167',['Third-Party Components',['../third_party.html',1,'index']]],
  ['this_20example_20demonstrates_168',['What this example demonstrates',['../basics_2fix32__orbit_2main_8c.html#autotoc_md859',1,'']]],
  ['this_20example_20does_169',['This Example Does',['../examples_audio_snesmod_music.html#autotoc_md766',1,'What This Example Does'],['../examples_graphics_backgrounds_mode1.html#autotoc_md1027',1,'What This Example Does'],['../examples_graphics_effects_fading.html#autotoc_md1139',1,'What This Example Does'],['../examples_input_two_players.html#autotoc_md1463',1,'What This Example Does']]],
  ['this_20example_20shows_170',['This Example Shows',['../examples_graphics_backgrounds_mode1_bg3_priority.html#autotoc_md1060',1,'What This Example Shows'],['../examples_graphics_backgrounds_mode7.html#autotoc_md1097',1,'What This Example Shows'],['../examples_graphics_backgrounds_mode7_perspective.html#autotoc_md1113',1,'What This Example Shows'],['../examples_graphics_effects_gradient_colors.html#autotoc_md1174',1,'What This Example Shows'],['../examples_graphics_effects_mosaic.html#autotoc_md1245',1,'What This Example Shows'],['../examples_graphics_effects_parallax_scrolling.html#autotoc_md1259',1,'What This Example Shows'],['../examples_graphics_sprites_animated_sprite.html#autotoc_md1338',1,'What This Example Shows'],['../examples_graphics_sprites_dynamic_sprite.html#autotoc_md1357',1,'What This Example Shows'],['../examples_graphics_sprites_object_size.html#autotoc_md1381',1,'What This Example Shows'],['../examples_graphics_sprites_simple_sprite.html#autotoc_md1402',1,'What This Example Shows'],['../examples_memory_hirom_demo.html#autotoc_md1549',1,'What This Example Shows'],['../examples_memory_save_game.html#autotoc_md1577',1,'What This Example Shows']]],
  ['this_20port_20surfaced_171',['this port surfaced',['../examples_graphics_effects_mode7_perspective_rotate.html#autotoc_md1242',1,'Two integration lessons this port surfaced'],['../examples_graphics_effects_hicolor_1792.html#autotoc_md1226',1,'Two SDK bugs this port surfaced']]],
  ['this_20target_20since_20chantier_20a1_172',['🟢 &lt;span class=&quot;tt&quot;&gt;int&lt;/span&gt; and &lt;span class=&quot;tt&quot;&gt;long&lt;/span&gt; sizes are correct on this target (since chantier A1)',['../tutorial_math.html#autotoc_md273',1,'']]],
  ['this_20variable_173',['Recipe 2 — &quot;Who writes this variable?&quot;',['../tutorial_debugging.html#autotoc_md157',1,'']]],
  ['this_20works_20with_20one_20layer_174',['Why This Works with One Layer',['../examples_graphics_effects_parallax_scrolling.html#autotoc_md1270',1,'']]],
  ['three_20background_20layers_175',['1. Set up three background layers',['../examples_graphics_backgrounds_mode1_bg3_priority.html#autotoc_md1064',1,'']]],
  ['threshold_20scroll_20pattern_176',['2. The Threshold Scroll Pattern',['../examples_graphics_backgrounds_continuous_scroll.html#autotoc_md990',1,'']]],
  ['through_20a_177',['No &lt;span class=&quot;tt&quot;&gt;stx.l&lt;/span&gt; — Save X Through A',['../tutorial_sa1.html#autotoc_md340',1,'']]],
  ['ticking_178',['Selecting the Clip and Ticking',['../tutorial_animation.html#autotoc_md79',1,'']]],
  ['tile_20animation_179',['Background Tile Animation',['../tutorial_animation.html#autotoc_md87',1,'']]],
  ['tile_20based_20collision_180',['Tile Based Collision',['../examples_games_likemario.html#autotoc_md929',1,'6. Tile-Based Collision'],['../examples_maps.html#autotoc_md1526',1,'Tile-Based Collision']]],
  ['tile_20based_20wall_20collision_181',['Tile-Based Wall Collision',['../examples_basics_collision_demo.html#autotoc_md852',1,'']]],
  ['tile_20calculation_182',['4. Tile calculation',['../examples_graphics_sprites_animated_sprite.html#autotoc_md1346',1,'']]],
  ['tile_20collision_183',['Map Engine and Tile Collision',['../examples_games_mapandobjects.html#autotoc_md947',1,'']]],
  ['tile_20data_20address_184',['$210B-$210C - BG12NBA/BG34NBA (Tile Data Address)',['../registers.html#autotoc_md701',1,'']]],
  ['tile_20flip_185',['Exercise 3: Tile Flip',['../examples_graphics_backgrounds_mode1.html#autotoc_md1051',1,'']]],
  ['tile_20format_186',['Tile Format',['../examples_text.html#autotoc_md1637',1,'2BPP Tile Format'],['../examples_graphics_backgrounds_mode1.html#autotoc_md1042',1,'4bpp Tile Format']]],
  ['tile_20formats_187',['Tile Formats',['../snes_graphics_guide.html#autotoc_md524',1,'']]],
  ['tile_20graphics_188',['Approach 2: Overwrite Tile Graphics',['../tutorial_animation.html#autotoc_md89',1,'']]],
  ['tile_20grid_20platformer_20landing_189',['Snapping to Tile Grid (Platformer Landing)',['../tutorial_collision.html#autotoc_md131',1,'']]],
  ['tile_20layout_190',['Column-Major Tile Layout',['../tutorial_superfx.html#autotoc_md413',1,'']]],
  ['tile_20layout_20and_20oam_20tile_20numbers_191',['VRAM Tile Layout and OAM Tile Numbers',['../examples_graphics_sprites_metasprite.html#autotoc_md1376',1,'']]],
  ['tile_20numbering_192',['VRAM Tile Numbering',['../tutorial_animation.html#autotoc_md74',1,'']]],
  ['tile_20numbers_193',['VRAM Tile Layout and OAM Tile Numbers',['../examples_graphics_sprites_metasprite.html#autotoc_md1376',1,'']]],
  ['tile_20properties_194',['Tile Properties',['../examples_maps_tiled.html#autotoc_md1543',1,'']]],
  ['tile_20properties_20from_20a_20tilemap_20platformer_20pattern_195',['Tile Properties from a Tilemap (Platformer Pattern)',['../tutorial_collision.html#autotoc_md125',1,'']]],
  ['tile_20sizes_196',['Custom Tile Sizes',['../tutorial_collision.html#autotoc_md124',1,'']]],
  ['tiled_20map_197',['rpg — an RPG template driven by a Tiled map',['../examples_games_rpg.html',1,'examples_games']]],
  ['tiled_20map_20editor_20integration_198',['Tiled Map Editor Integration',['../examples_maps_tiled.html',1,'examples_maps']]],
  ['tiled_20pipeline_199',['The Tiled pipeline',['../tutorial_map.html#autotoc_md250',1,'']]],
  ['tiled_20workflow_200',['The Tiled Workflow',['../examples_maps_tiled.html#autotoc_md1540',1,'']]],
  ['tilemap_201',['Background Tilemap',['../registers.html#autotoc_md699',1,'']]],
  ['tilemap_20address_20size_202',['$2107-$210A - BG1SC-BG4SC (Tilemap Address/Size)',['../registers.html#autotoc_md700',1,'']]],
  ['tilemap_20centre_20not_20the_20screen_20centre_203',['🟡 Centre default is the tilemap centre, not the screen centre',['../tutorial_mode7.html#autotoc_md299',1,'']]],
  ['tilemap_20data_204',['Reading Tilemap Data',['../tutorial_collision.html#autotoc_md122',1,'']]],
  ['tilemap_20entries_205',['Approach 1: Swap Tilemap Entries',['../tutorial_animation.html#autotoc_md88',1,'']]],
  ['tilemap_20entry_202_20bytes_206',['Tilemap Entry (2 bytes)',['../examples_graphics_backgrounds.html#autotoc_md1130',1,'']]],
  ['tilemap_20for_20seamless_20wrapping_207',['64x32 Tilemap for Seamless Wrapping',['../examples_graphics_effects_parallax_scrolling.html#autotoc_md1269',1,'']]],
  ['tilemap_20format_208',['Tilemap Format',['../examples_graphics_backgrounds_mode1.html#autotoc_md1040',1,'']]],
  ['tilemap_20is_20yours_209',['The &lt;span class=&quot;tt&quot;&gt;Panel&lt;/span&gt; struct — the tilemap is yours',['../tutorial_panel.html#autotoc_md318',1,'']]],
  ['tilemap_20layout_210',['SC_64x64 Tilemap Layout',['../examples_maps_dynamic_map.html#autotoc_md1505',1,'']]],
  ['tilemap_20palette_20bits_211',['Tilemap Palette Bits',['../examples_graphics_backgrounds_mode1_bg3_priority.html#autotoc_md1070',1,'']]],
  ['tilemap_20platformer_20pattern_212',['Tile Properties from a Tilemap (Platformer Pattern)',['../tutorial_collision.html#autotoc_md125',1,'']]],
  ['tilemap_20sizes_213',['Tilemap Sizes',['../snes_graphics_guide.html#autotoc_md523',1,'Tilemap Sizes'],['../examples_maps.html#autotoc_md1525',1,'Tilemap Sizes']]],
  ['tilemap_20structure_214',['Tilemap Structure',['../snes_graphics_guide.html#autotoc_md522',1,'']]],
  ['tilemap_20uncompressed_215',['3. Load Palette and Tilemap (Uncompressed)',['../examples_graphics_backgrounds_mode1_lz77.html#autotoc_md1083',1,'']]],
  ['tilemaps_216',['Tilemaps',['../examples_maps.html#autotoc_md1524',1,'Hardware Tilemaps'],['../tutorial_graphics.html#autotoc_md202',1,'Setting Up Tilemaps'],['../examples_graphics_backgrounds_mode1_lz77.html#autotoc_md1077',1,'Why Compress Tiles but Not Tilemaps?']]],
  ['tilemaps_20to_20vram_217',['2. Load Tilemaps to VRAM',['../examples_graphics_backgrounds_mixed_scroll.html#autotoc_md1015',1,'']]],
  ['tiles_218',['Tiles',['../tutorial_sprites.html#autotoc_md367',1,'Loading Sprite Tiles'],['../examples_maps_dynamic_map.html#autotoc_md1504',1,'Mode 3 and 8bpp Tiles']]],
  ['tiles_20and_20palettes_219',['2. Load tiles and palettes',['../examples_graphics_backgrounds_mode1_bg3_priority.html#autotoc_md1065',1,'']]],
  ['tiles_20and_20sprites_220',['Tiles and Sprites',['../hardware_overview.html#autotoc_md682',1,'']]],
  ['tiles_20appear_20corrupted_221',['Tiles appear corrupted',['../troubleshooting.html#autotoc_md621',1,'']]],
  ['tiles_20but_20not_20tilemaps_222',['Why Compress Tiles but Not Tilemaps?',['../examples_graphics_backgrounds_mode1_lz77.html#autotoc_md1077',1,'']]],
  ['tiles_20in_20oam_223',['16x16 Tiles in OAM',['../examples_graphics_sprites_animated_sprite.html#autotoc_md1350',1,'']]],
  ['tiles_20to_20vram_224',['Tiles to VRAM',['../examples_graphics_backgrounds_mode1_lz77.html#autotoc_md1082',1,'2. Decompress Tiles to VRAM'],['../examples_text_hello_world.html#autotoc_md1618',1,'4. Uploading Tiles to VRAM'],['../tutorial_graphics.html#autotoc_md201',1,'Loading Tiles to VRAM']]],
  ['tilesets_20and_20palettes_225',['1. Load Both Tilesets and Palettes',['../examples_graphics_backgrounds_mixed_scroll.html#autotoc_md1014',1,'']]],
  ['time_226',['Recipe 1 — Inspect the machine at a point in time',['../tutorial_debugging.html#autotoc_md156',1,'']]],
  ['timer_227',['Timer',['../registers.html#autotoc_md718',1,'$4207-$420A - HTIMEx/VTIMEx (IRQ Timer)'],['../examples_basics_timer.html',1,'VBlank Timer']]],
  ['timer_20irq_20streaming_228',['When HDMA isn&apos;t enough: H-timer IRQ streaming',['../tutorial_hdma.html#autotoc_md226',1,'']]],
  ['timeup_20irq_20status_229',['$4211 - TIMEUP (IRQ Status)',['../registers.html#autotoc_md720',1,'']]],
  ['timing_230',['Timing',['../tutorial_animation.html#autotoc_md70',1,'Frame Timing'],['../oam.html#autotoc_md671',1,'Timing'],['../tutorial_scrolling.html#autotoc_md357',1,'VBlank Timing']]],
  ['timing_231',['timing',['../tutorial_sram.html#autotoc_md391',1,'🟠 SRAM access requires no special timing'],['../tutorial_math.html#autotoc_md278',1,'🟡 Hardware multiplier read timing'],['../examples_graphics_sprites_animated_sprite.html#autotoc_md1345',1,'3. Animation timing']]],
  ['timing_20requirement_232',['VBlank Timing Requirement',['../dma_8h.html#autotoc_md24',1,'']]],
  ['timing_20values_233',['Timing Values',['../snes_sound_guide.html#autotoc_md579',1,'']]],
  ['tip_234',['Performance Tip',['../examples_graphics_sprites.html#autotoc_md1400',1,'']]],
  ['tips_235',['Tips',['../tutorial_collision.html#autotoc_md133',1,'Performance Tips'],['../tutorial_sprites.html#autotoc_md375',1,'Performance Tips'],['../tutorial_sa1.html#autotoc_md337',1,'SA-1 Assembly Tips'],['../tutorial_scrolling.html#autotoc_md356',1,'Streaming Tips'],['../tutorial_audio.html#autotoc_md108',1,'Tips'],['../tutorial_input.html#autotoc_md246',1,'Tips'],['../examples.html#autotoc_md1608',1,'Tips']]],
  ['tips_20tricks_236',['Tips Tricks',['../examples_games_breakout.html#autotoc_md906',1,'Tips &amp;amp; Tricks'],['../examples_games_likemario.html#autotoc_md932',1,'Tips &amp;amp; Tricks'],['../examples_graphics_backgrounds_continuous_scroll.html#autotoc_md995',1,'Tips &amp;amp; Tricks'],['../examples_graphics_effects_hdma_wave.html#autotoc_md1208',1,'Tips &amp;amp; Tricks'],['../examples_input_superscope.html#autotoc_md1456',1,'Tips &amp;amp; Tricks'],['../examples_text_hello_world.html#autotoc_md1623',1,'Tips &amp;amp; Tricks']]],
  ['title_20flow_237',['Complete Title Flow',['../tutorial_game_states.html#autotoc_md189',1,'']]],
  ['title_20screen_20implementation_238',['Title Screen Implementation',['../tutorial_game_states.html#autotoc_md188',1,'']]],
  ['tm_20main_20screen_20enable_239',['$212C - TM (Main Screen Enable)',['../registers.html#autotoc_md712',1,'']]],
  ['to_20background_20collision_240',['Sprite-to-Background Collision',['../tutorial_collision.html#autotoc_md121',1,'']]],
  ['to_20black_241',['Fade Out (Full to Black)',['../examples_graphics_effects_fading.html#autotoc_md1147',1,'']]],
  ['to_20black_20fade_20to_20white_242',['Fade-to-black / fade-to-white',['../tutorial_colormath.html#autotoc_md139',1,'']]],
  ['to_20build_243',['to Build',['../examples_audio_apu_switch.html#autotoc_md749',1,'How to Build'],['../examples_audio_pitch_mod.html#autotoc_md754',1,'How to Build'],['../examples_audio_play_noise.html#autotoc_md757',1,'How to Build'],['../examples_audio_soundboard.html#autotoc_md835',1,'How to Build'],['../examples_basics_aim_target.html#autotoc_md843',1,'How to Build'],['../examples_basics_fix32_orbit.html#autotoc_md863',1,'How to Build'],['../examples_basics_scene_stack.html#autotoc_md882',1,'How to Build'],['../examples_games_mode7_flying.html#autotoc_md960',1,'How to Build'],['../examples_games_mode7_racing.html#autotoc_md963',1,'How to Build'],['../examples_games_rpg.html#autotoc_md970',1,'How to Build'],['../examples_graphics_effects_direct_color.html#autotoc_md1134',1,'How to Build'],['../examples_graphics_effects_gradient_9bit.html#autotoc_md1172',1,'How to Build'],['../examples_graphics_effects_hdma_indirect_gradient.html#autotoc_md1194',1,'How to Build'],['../examples_graphics_effects_hdma_wave_table.html#autotoc_md1221',1,'How to Build'],['../examples_graphics_effects_hicolor_1792.html#autotoc_md1227',1,'How to Build'],['../examples_graphics_effects_hires_text.html#autotoc_md1236',1,'How to Build'],['../examples_graphics_effects_mode7_perspective_rotate.html#autotoc_md1243',1,'How to Build'],['../examples_graphics_effects_window_multi_hdma.html#autotoc_md1331',1,'How to Build']]],
  ['to_20colour_20math_244',['🟠 &lt;span class=&quot;tt&quot;&gt;windowEnable(window, WINDOW_MATH)&lt;/span&gt; is the gate to colour math',['../tutorial_window.html#autotoc_md430',1,'']]],
  ['to_20full_245',['Fade In (Black to Full)',['../examples_graphics_effects_fading.html#autotoc_md1146',1,'']]],
  ['to_20how_20the_20sheet_20was_20converted_246',['🟡 Match &lt;span class=&quot;tt&quot;&gt;base_tile&lt;/span&gt;/&lt;span class=&quot;tt&quot;&gt;stride&lt;/span&gt; to how the sheet was converted',['../tutorial_panel.html#autotoc_md324',1,'']]],
  ['to_20lorom_247',['2. The code is identical to LoROM',['../examples_memory_hirom_demo.html#autotoc_md1555',1,'']]],
  ['to_20make_20target_20common_20mk_248',['&quot;OPENSNES not defined&quot; or &quot;No rule to make target &apos;common.mk&apos;&quot;',['../troubleshooting.html#autotoc_md607',1,'']]],
  ['to_20observe_249',['to Observe',['../examples_basics_aim_target.html#autotoc_md842',1,'What to Observe'],['../examples_basics_fix32_orbit.html#autotoc_md862',1,'What to Observe'],['../examples_memory_sa1_starfield.html#autotoc_md1575',1,'What to Observe']]],
  ['to_20opensnes_250',['Contributing to OpenSNES',['../contributing.html',1,'index']]],
  ['to_20sprite_20collision_251',['Sprite-to-Sprite Collision',['../tutorial_collision.html#autotoc_md117',1,'']]],
  ['to_20sram_252',['2. Save to SRAM',['../examples_memory_save_game.html#autotoc_md1583',1,'']]],
  ['to_20the_20original_20measured_20not_20assumed_253',['to the original measured not assumed',['../examples_graphics_effects_hdma_indirect_gradient.html#autotoc_md1192',1,'Fidelity to the original (measured, not assumed)'],['../examples_graphics_effects_hdma_wave_table.html#autotoc_md1219',1,'Fidelity to the original (measured, not assumed)']]],
  ['to_20think_20about_20it_254',['🟠 Endianness — but you don&apos;t have to think about it',['../tutorial_sram.html#autotoc_md393',1,'']]],
  ['to_20tile_20grid_20platformer_20landing_255',['Snapping to Tile Grid (Platformer Landing)',['../tutorial_collision.html#autotoc_md131',1,'']]],
  ['to_20use_20hirom_256',['When to Use HiROM',['../examples_memory_hirom_demo.html#autotoc_md1560',1,'']]],
  ['to_20vram_257',['to VRAM',['../examples_graphics_backgrounds_mode1_lz77.html#autotoc_md1082',1,'2. Decompress Tiles to VRAM'],['../examples_graphics_backgrounds_mixed_scroll.html#autotoc_md1015',1,'2. Load Tilemaps to VRAM'],['../examples_text_hello_world.html#autotoc_md1618',1,'4. Uploading Tiles to VRAM'],['../tutorial_graphics.html#autotoc_md201',1,'Loading Tiles to VRAM']]],
  ['to_20vram_20transfer_258',['SRAM to VRAM Transfer',['../tutorial_superfx.html#autotoc_md414',1,'']]],
  ['to_20white_259',['Fade-to-black / fade-to-white',['../tutorial_colormath.html#autotoc_md139',1,'']]],
  ['today_260',['🔴 Interleaved VRAM, no &lt;span class=&quot;tt&quot;&gt;mode7LoadGraphics&lt;/span&gt; helper today',['../tutorial_mode7.html#autotoc_md296',1,'']]],
  ['toggle_20at_20runtime_261',['3. Toggle at runtime',['../examples_graphics_effects_gradient_colors.html#autotoc_md1181',1,'']]],
  ['too_20large_20or_20linker_20errors_20about_20size_262',['&quot;ROM too large&quot; or linker errors about size',['../troubleshooting.html#autotoc_md624',1,'']]],
  ['tool_263',['smconv Tool',['../tutorial_audio.html#autotoc_md103',1,'']]],
  ['tooling_20that_20cracked_20it_264',['Debug tooling that cracked it',['../examples_audio_speech_synth.html#autotoc_md839',1,'']]],
  ['tools_265',['Tools',['../snes_sound_guide.html#autotoc_md598',1,'Conversion Tools'],['../code_style.html#autotoc_md512',1,'Formatting Tools'],['../snes_graphics_guide.html#autotoc_md550',1,'Graphics Conversion Tools'],['../snes_sound_guide.html#autotoc_md597',1,'Sound Creation Tools']]],
  ['tools_20resources_266',['Tools Resources',['../snes_graphics_guide.html#autotoc_md549',1,'Tools &amp;amp; Resources'],['../snes_sound_guide.html#autotoc_md596',1,'Tools &amp;amp; Resources']]],
  ['topic_267',['By Topic',['../group__examples.html#autotoc_md1655',1,'']]],
  ['topic_20per_20pr_268',['One topic per PR',['../contributing.html#autotoc_md1674',1,'']]],
  ['topics_269',['Topics',['../examples.html#autotoc_md1604',1,'Level 4 &amp;ndash; Advanced Topics'],['../learning_path.html#autotoc_md468',1,'Level 4: Advanced Topics']]],
  ['total_270',['total',['../snes_sound_guide.html#autotoc_md593',1,'Memory Budget (64KB total)'],['../snes_graphics_guide.html#autotoc_md527',1,'OAM Structure (544 bytes total)']]],
  ['tour_271',['Lib API tour',['../tutorial_dma.html#autotoc_md171',1,'']]],
  ['tracker_20based_20music_272',['Why Tracker-Based Music?',['../examples_audio_snesmod_music.html#autotoc_md805',1,'']]],
  ['transfer_273',['SRAM to VRAM Transfer',['../tutorial_superfx.html#autotoc_md414',1,'']]],
  ['transfer_20modes_274',['Transfer modes',['../tutorial_hdma.html#autotoc_md212',1,'']]],
  ['transfer_20modes_275',['The 8 transfer modes',['../tutorial_dma.html#autotoc_md166',1,'']]],
  ['transfer_20size_276',['$43x5-$43x6 - DASxL/H (Transfer Size)',['../registers.html#autotoc_md734',1,'']]],
  ['transfers_277',['DMA Registers (for fast transfers)',['../snes_graphics_guide.html#autotoc_md556',1,'']]],
  ['transformation_278',['Affine Transformation',['../examples_graphics_backgrounds_mode7.html#autotoc_md1107',1,'']]],
  ['transformation_279',['2. Initialize the transformation',['../examples_graphics_backgrounds_mode7.html#autotoc_md1103',1,'']]],
  ['transition_20pattern_280',['Scene Transition Pattern',['../examples_graphics_effects_fading.html#autotoc_md1152',1,'']]],
  ['transitions_281',['State Transitions',['../tutorial_game_states.html#autotoc_md185',1,'']]],
  ['transitions_282',['transitions',['../examples_graphics_effects_mosaic.html#autotoc_md1252',1,'3. Combining both for transitions'],['../tutorial_mosaic.html#autotoc_md306',1,'Animated transitions']]],
  ['translation_283',['Address Translation',['../examples_memory_hirom_demo.html#autotoc_md1561',1,'']]],
  ['transparency_284',['Color Addition Transparency',['../examples_graphics_effects_transparency.html',1,'examples_graphics_effects']]],
  ['transparency_285',['Additive cloud overlay — &lt;span class=&quot;tt&quot;&gt;examples/graphics/effects/transparency&lt;/span&gt;',['../tutorial_colormath.html#autotoc_md143',1,'']]],
  ['transparent_20window_20color_20math_20hdma_286',['Transparent Window -- Color Math + HDMA',['../examples_graphics_effects_transparent_window.html',1,'examples_graphics_effects']]],
  ['transparent_5fwindow_287',['transparent_window',['../tutorial_window.html#autotoc_md427',1,'Window + colour math — &lt;span class=&quot;tt&quot;&gt;examples/graphics/effects/transparent_window&lt;/span&gt;'],['../tutorial_hdma.html#autotoc_md220',1,'Window animation — &lt;span class=&quot;tt&quot;&gt;examples/graphics/effects/transparent_window&lt;/span&gt;'],['../tutorial_colormath.html#autotoc_md144',1,'Window-gated spotlight blend — &lt;span class=&quot;tt&quot;&gt;examples/graphics/effects/transparent_window&lt;/span&gt;']]],
  ['trap_288',['trap',['../tutorial_colormath.html#autotoc_md146',1,'🔴 The &quot;BG2 is sub-screen-only&quot; trap'],['../tutorial_window.html#autotoc_md423',1,'The window logic op trap']]],
  ['trap_20on_20hdmasetup_289',['🔴 Bank byte trap on &lt;span class=&quot;tt&quot;&gt;hdmaSetup&lt;/span&gt;',['../tutorial_hdma.html#autotoc_md229',1,'']]],
  ['triangle_20masking_290',['Window -- HDMA Triangle Masking',['../examples_graphics_effects_window.html',1,'examples_graphics_effects']]],
  ['triangle_20reveal_20—_20examples_20graphics_20effects_20window_291',['Animated triangle reveal — &lt;span class=&quot;tt&quot;&gt;examples/graphics/effects/window&lt;/span&gt;',['../tutorial_window.html#autotoc_md426',1,'']]],
  ['triangle_20tables_292',['The Triangle Tables',['../examples_graphics_effects_window.html#autotoc_md1320',1,'']]],
  ['tricks_293',['Tricks',['../examples_games_breakout.html#autotoc_md906',1,'Tips &amp;amp; Tricks'],['../examples_games_likemario.html#autotoc_md932',1,'Tips &amp;amp; Tricks'],['../examples_graphics_backgrounds_continuous_scroll.html#autotoc_md995',1,'Tips &amp;amp; Tricks'],['../examples_graphics_effects_hdma_wave.html#autotoc_md1208',1,'Tips &amp;amp; Tricks'],['../examples_input_superscope.html#autotoc_md1456',1,'Tips &amp;amp; Tricks'],['../examples_text_hello_world.html#autotoc_md1623',1,'Tips &amp;amp; Tricks']]],
  ['trigonometry_20sin_20cos_20lookup_20tables_294',['Trigonometry (sin/cos lookup tables)',['../tutorial_math.html#autotoc_md264',1,'']]],
  ['troubleshooting_295',['Troubleshooting',['../getting_started.html#autotoc_md457',1,'']]],
  ['troubleshooting_20opensnes_296',['Troubleshooting OpenSNES',['../troubleshooting.html',1,'index']]],
  ['true_20story_297',['Why the envelope differs from the original (a true story)',['../examples_audio_pitch_mod.html#autotoc_md751',1,'']]],
  ['truncates_20fractional_20precision_298',['🔴 &lt;span class=&quot;tt&quot;&gt;fixMul&lt;/span&gt; truncates fractional precision',['../tutorial_math.html#autotoc_md275',1,'']]],
  ['ts_20sub_20screen_20enable_299',['$212D - TS (Sub Screen Enable)',['../registers.html#autotoc_md713',1,'']]],
  ['tutorial_300',['Tutorial',['../tutorial_animation.html',1,'Animation Tutorial'],['../tutorial_audio.html',1,'Audio &amp; Music Tutorial'],['../tutorial_collision.html',1,'Collision Detection Tutorial'],['../tutorial_colormath.html',1,'Colour Math Tutorial'],['../tutorial_input.html',1,'Controller Input Tutorial'],['../tutorial_dma.html',1,'DMA Tutorial'],['../tutorial_math.html',1,'Fixed-Point Math Tutorial'],['../tutorial_game_states.html',1,'Game States Tutorial'],['../tutorial_graphics.html',1,'Graphics &amp; Backgrounds Tutorial'],['../tutorial_hdma.html',1,'HDMA Tutorial'],['../tutorial_mode7.html',1,'Mode 7 Tutorial'],['../tutorial_mosaic.html',1,'Mosaic Tutorial'],['../tutorial_sa1.html',1,'SA-1 Enhancement Chip Tutorial'],['../tutorial_scrolling.html',1,'Scrolling &amp; Parallax Tutorial'],['../tutorial_sprites.html',1,'Sprites &amp; Animation Tutorial'],['../tutorial_sram.html',1,'SRAM Save Tutorial'],['../tutorial_superfx.html',1,'SuperFX (GSU) Tutorial'],['../tutorial_window.html',1,'Window Masking Tutorial']]],
  ['tutorials_301',['Tutorials',['../index.html#autotoc_md2',1,'Tutorials'],['../getting_started.html#autotoc_md456',1,'Tutorials']]],
  ['twice_20register_302',['BG1HOFS ($210D) &amp;ndash; Write-Twice Register',['../examples_graphics_effects_parallax_scrolling.html#autotoc_md1268',1,'']]],
  ['two_20camps_303',['Why two camps?',['../oam.html#autotoc_md670',1,'']]],
  ['two_20channels_20one_20visual_20—_20examples_20graphics_20effects_20gradient_5f9bit_304',['Two channels, one visual — &lt;span class=&quot;tt&quot;&gt;examples/graphics/effects/gradient_9bit&lt;/span&gt;',['../tutorial_hdma.html#autotoc_md225',1,'']]],
  ['two_20colors_20four_20bytes_305',['5. Two Colors, Four Bytes',['../examples_text_hello_world.html#autotoc_md1619',1,'']]],
  ['two_20controllers_306',['Reading Two Controllers',['../examples_input_two_players.html#autotoc_md1467',1,'']]],
  ['two_20integration_20lessons_20this_20port_20surfaced_307',['Two integration lessons this port surfaced',['../examples_graphics_effects_mode7_perspective_rotate.html#autotoc_md1242',1,'']]],
  ['two_20layers_20two_20speeds_308',['1. Two Layers, Two Speeds',['../examples_graphics_backgrounds_continuous_scroll.html#autotoc_md989',1,'']]],
  ['two_20lines_309',['5. Gravity in Two Lines',['../examples_games_likemario.html#autotoc_md928',1,'']]],
  ['two_20phase_20update_310',['Map Engine Two-Phase Update',['../examples_maps_mapscroll.html#autotoc_md1515',1,'']]],
  ['two_20player_20example_311',['Two-Player Example',['../tutorial_input.html#autotoc_md242',1,'']]],
  ['two_20players_312',['Example: Two Players',['../tutorial_sprites.html#autotoc_md374',1,'']]],
  ['two_20players_20example_313',['Two Players Example',['../examples_input_two_players.html',1,'examples_input']]],
  ['two_20sdk_20bugs_20this_20port_20surfaced_314',['Two SDK bugs this port surfaced',['../examples_graphics_effects_hicolor_1792.html#autotoc_md1226',1,'']]],
  ['two_20shipped_20examples_315',['two shipped examples',['../tutorial_colormath.html#autotoc_md142',1,'Worked patterns (the two shipped examples)'],['../tutorial_mode7.html#autotoc_md291',1,'Worked patterns (the two shipped examples)']]],
  ['two_20speeds_316',['1. Two Layers, Two Speeds',['../examples_graphics_backgrounds_continuous_scroll.html#autotoc_md989',1,'']]],
  ['two_20sprites_20per_20mode_317',['3. Two sprites per mode',['../examples_graphics_sprites_object_size.html#autotoc_md1387',1,'']]],
  ['type_318',['Type',['../examples_audio_snesmod_music.html#autotoc_md768',1,'Code Type'],['../examples_graphics_backgrounds_mode1.html#autotoc_md1029',1,'Code Type'],['../examples_graphics_effects_fading.html#autotoc_md1141',1,'Code Type'],['../examples_input_two_players.html#autotoc_md1465',1,'Code Type'],['../tutorial_collision.html#autotoc_md116',1,'The Rect Type']]],
  ['types_319',['Types',['../examples_input_two_players.html#autotoc_md1483',1,'Controller Types'],['../code_style.html#autotoc_md500',1,'Types']]],
  ['types_20in_20assembly_320',['2. Register Object Types in Assembly',['../examples_games_mapandobjects.html#autotoc_md953',1,'']]],
  ['typical_20sample_20sizes_321',['Typical Sample Sizes',['../snes_sound_guide.html#autotoc_md594',1,'']]]
];
