var searchData=
[
  ['b_20bus_20address_0',['$43x1 - BBADx (B-Bus Address)',['../registers.html#autotoc_md829',1,'']]],
  ['b_20multiply_1',['$4202-$4203 - WRMPYA/B (Multiply)',['../registers.html#autotoc_md820',1,'']]],
  ['b_20source_20address_2',['$43x2-$43x4 - A1TxL/H/B (Source Address)',['../registers.html#autotoc_md830',1,'']]],
  ['b1_20install_20prerequisites_3',['B1. Install Prerequisites',['../getting_started.html#autotoc_md534',1,'']]],
  ['b2_20clone_20and_20build_4',['B2. Clone and Build',['../getting_started.html#autotoc_md535',1,'']]],
  ['b3_20run_20tests_5',['B3. Run Tests',['../getting_started.html#autotoc_md536',1,'']]],
  ['b4_20development_20workflow_6',['B4. Development Workflow',['../getting_started.html#autotoc_md537',1,'']]],
  ['b6_202026_2005_2009_7',['&lt;span class=&quot;tt&quot;&gt;atan2&lt;/span&gt; and &lt;span class=&quot;tt&quot;&gt;sqrt&lt;/span&gt; ship in the lib (chantier B6, 2026-05-09)',['../tutorial_math.html#autotoc_md282',1,'']]],
  ['b_3a_20sdk_20developer_8',['Path B: SDK Developer',['../getting_started.html#autotoc_md533',1,'']]],
  ['backdrop_9',['backdrop',['../tutorial_colormath.html#autotoc_md151',1,'🟡 Colour-math on the backdrop'],['../examples_color_gradient_9bit.html',1,'&quot;9-bit&quot; gradient — brightness-dithered backdrop']]],
  ['backdrop_20not_20a_20layer_10',['🟡 Out-of-bounds with &lt;span class=&quot;tt&quot;&gt;MODE7_TRANSPARENT&lt;/span&gt; shows the backdrop, not a layer',['../tutorial_mode7.html#autotoc_md302',1,'']]],
  ['backend_11',['QBE (w65816 backend)',['../third_party.html#autotoc_md737',1,'']]],
  ['background_12',['Background',['../examples_backgrounds_mode1.html#autotoc_md957',1,'2. Set Up Background'],['../examples_hdma_hdma_wave.html#autotoc_md1314',1,'6. The Checkerboard Background'],['../examples_backgrounds_mode0.html',1,'Mode 0 — 4-Layer 2bpp Background'],['../examples_backgrounds_mode3.html',1,'Mode 3 — 256-Color Background'],['../examples_backgrounds_mode5.html',1,'Mode 5 — Hi-Res 512×256 Background']]],
  ['background_13',['HiColor — 1792 colors from a 4bpp background',['../examples_color_hicolor_1792.html',1,'examples_color']]],
  ['background_20bg2_14',['3. Calibration Background (BG2)',['../examples_input_superscope.html#autotoc_md1368',1,'']]],
  ['background_20collision_15',['Sprite-to-Background Collision',['../tutorial_collision.html#autotoc_md123',1,'']]],
  ['background_20layers_16',['1. Set up three background layers',['../examples_backgrounds_mode1_bg3_priority.html#autotoc_md985',1,'']]],
  ['background_20mode_17',['Background Mode',['../registers.html#autotoc_md795',1,'$2105 - BGMODE (Background Mode)'],['../registers.html#autotoc_md794',1,'Background Mode']]],
  ['background_20mode_20from_20your_20genre_18',['Choose a background mode from your genre',['../craft_planning.html#autotoc_md472',1,'']]],
  ['background_20modes_19',['Background Modes',['../hardware_overview.html#autotoc_md780',1,'']]],
  ['background_20scroll_20',['Background Scroll',['../registers.html#autotoc_md799',1,'']]],
  ['background_20scrolling_21',['Background Scrolling',['../tutorial_graphics.html#autotoc_md206',1,'Background Scrolling'],['../examples_scrolling_mixed_scroll.html#autotoc_md1572',1,'Independent Background Scrolling']]],
  ['background_20setup_22',['Example: Complete Background Setup',['../tutorial_graphics.html#autotoc_md209',1,'']]],
  ['background_20tile_20animation_23',['Background Tile Animation',['../tutorial_animation.html#autotoc_md89',1,'']]],
  ['background_20tilemap_24',['Background Tilemap',['../registers.html#autotoc_md796',1,'']]],
  ['background_20wants_20q16_25',['🟡 &lt;span class=&quot;tt&quot;&gt;map&lt;/span&gt; streams &lt;span class=&quot;tt&quot;&gt;.m16&lt;/span&gt;; &lt;span class=&quot;tt&quot;&gt;background&lt;/span&gt; wants &lt;span class=&quot;tt&quot;&gt;.q16&lt;/span&gt;',['../tutorial_map.html#autotoc_md260',1,'']]],
  ['backgrounds_26',['Backgrounds',['../examples_backgrounds.html',1,'Backgrounds'],['../examples_by_category.html#autotoc_md562',1,'Backgrounds'],['../snes_graphics_guide.html#autotoc_md618',1,'Backgrounds'],['../group__examples.html#autotoc_md1780',1,'Backgrounds'],['../examples_backgrounds_mode1_bg3_priority.html',1,'Mode 1 BG3 High Priority -- HUD Layer Over Backgrounds'],['../examples_scrolling_mixed_scroll.html#autotoc_md1569',1,'Mode 1 with Multiple Backgrounds']]],
  ['backgrounds_20layers_27',['Composing with backgrounds &amp;amp; layers',['../craft_backgrounds.html',1,'craft']]],
  ['backgrounds_20tutorial_28',['Graphics &amp;amp; Backgrounds Tutorial',['../tutorial_graphics.html',1,'index']]],
  ['backup_29',['SRAM (Battery Backup)',['../examples_memory.html#autotoc_md1476',1,'']]],
  ['bank_20byte_20limitation_30',['Bank Byte Limitation',['../hdma_8h.html#autotoc_md34',1,'']]],
  ['bank_20byte_20registration_31',['Assembly Bank Byte Registration',['../examples_maps_slope_collision.html#autotoc_md1443',1,'']]],
  ['bank_20byte_20trap_20on_20hdmasetup_32',['🔴 Bank byte trap on &lt;span class=&quot;tt&quot;&gt;hdmaSetup&lt;/span&gt;',['../tutorial_hdma.html#autotoc_md231',1,'']]],
  ['bank_20just_20work_33',['🟢 SUPERFREE assets in any bank just work',['../tutorial_dma.html#autotoc_md177',1,'']]],
  ['banks_34',['Banks',['../dma_8h.html#autotoc_md27',1,'']]],
  ['banks_20and_20addressing_35',['Banks and Addressing',['../hardware_overview.html#autotoc_md781',1,'']]],
  ['base_36',['Name Base',['../examples_sprites_simple_sprite.html#autotoc_md1655',1,'']]],
  ['base_5ftile_20stride_20to_20how_20the_20sheet_20was_20converted_37',['🟡 Match &lt;span class=&quot;tt&quot;&gt;base_tile&lt;/span&gt;/&lt;span class=&quot;tt&quot;&gt;stride&lt;/span&gt; to how the sheet was converted',['../tutorial_panel.html#autotoc_md326',1,'']]],
  ['based_20animation_38',['Based Animation',['../tutorial_animation.html#autotoc_md79',1,'Direction-Based Animation'],['../tutorial_animation.html#autotoc_md71',1,'Frame-Based Animation']]],
  ['based_20animation_39',['Frame-based Animation',['../tutorial_sprites.html#autotoc_md373',1,'']]],
  ['based_20animation_20likemario_40',['Action-Based Animation (LikeMario)',['../tutorial_animation.html#autotoc_md87',1,'']]],
  ['based_20collision_41',['6. Tile-Based Collision',['../examples_games_likemario.html#autotoc_md1227',1,'']]],
  ['based_20collision_20breakout_20bricks_42',['Grid-Based Collision (Breakout Bricks)',['../tutorial_collision.html#autotoc_md134',1,'']]],
  ['based_20music_43',['Why Tracker-Based Music?',['../examples_audio_snesmod_music.html#autotoc_md909',1,'']]],
  ['based_20wall_20collision_44',['Tile-Based Wall Collision',['../examples_basics_collision_demo.html#autotoc_md1043',1,'']]],
  ['basic_20bg_20scrolling_45',['Basic BG Scrolling',['../tutorial_scrolling.html#autotoc_md350',1,'']]],
  ['basic_20fade_20implementation_46',['Basic Fade Implementation',['../examples_transitions_fading.html#autotoc_md1705',1,'']]],
  ['basic_20music_20playback_47',['Basic Music Playback',['../tutorial_audio.html#autotoc_md101',1,'']]],
  ['basic_20overlap_20test_48',['Basic Overlap Test',['../tutorial_collision.html#autotoc_md120',1,'']]],
  ['basic_20rotation_20scaling_20—_20examples_20mode7_20rotate_5fscale_49',['Basic rotation + scaling — &lt;span class=&quot;tt&quot;&gt;examples/mode7/rotate_scale&lt;/span&gt;',['../tutorial_mode7.html#autotoc_md294',1,'']]],
  ['basic_20setup_50',['Basic Setup',['../examples_backgrounds_mode1.html#autotoc_md955',1,'']]],
  ['basic_20usage_51',['Basic Usage',['../console_8h.html#autotoc_md21',1,'']]],
  ['basics_52',['Basics',['../group__examples.html#autotoc_md1788',1,'Basics'],['../tutorial_sprites.html#autotoc_md361',1,'SNES Sprite Basics']]],
  ['basics_20examples_53',['Basics Examples',['../examples_basics.html',1,'examples']]],
  ['battery_20backup_54',['SRAM (Battery Backup)',['../examples_memory.html#autotoc_md1476',1,'']]],
  ['battery_20dies_20→_20silent_20corruption_55',['🔴 Battery dies → silent corruption',['../tutorial_sram.html#autotoc_md391',1,'']]],
  ['battery_20persistence_56',['Battery Persistence',['../examples_memory_save_game.html#autotoc_md1492',1,'']]],
  ['bbadx_20b_20bus_20address_57',['$43x1 - BBADx (B-Bus Address)',['../registers.html#autotoc_md829',1,'']]],
  ['becomes_20a_20sample_58',['How the WAV becomes a sample',['../examples_audio_sfx_from_wav.html#autotoc_md864',1,'']]],
  ['before_20angle_59',['🟡 Set scale BEFORE angle',['../tutorial_mode7.html#autotoc_md300',1,'']]],
  ['before_20hot_20loops_60',['4. CACHE Before Hot Loops',['../tutorial_superfx.html#autotoc_md412',1,'']]],
  ['before_20setscreenon_61',['🔴 &lt;span class=&quot;tt&quot;&gt;mapLoad()&lt;/span&gt; must run before &lt;span class=&quot;tt&quot;&gt;setScreenOn()&lt;/span&gt;',['../tutorial_map.html#autotoc_md258',1,'']]],
  ['before_20stop_62',['2. NOP Padding Before STOP',['../tutorial_superfx.html#autotoc_md410',1,'']]],
  ['before_20the_20user_20callback_20in_20the_20nmi_20handler_63',['🟡 HDMA fires before the user callback in the NMI handler',['../tutorial_hdma.html#autotoc_md233',1,'']]],
  ['before_20you_20write_20code_64',['Checklist before you write code',['../craft_planning.html#autotoc_md475',1,'']]],
  ['behavior_65',['Wrap Behavior',['../tutorial_scrolling.html#autotoc_md349',1,'']]],
  ['behaviour_66',['Out-of-bounds behaviour',['../tutorial_mode7.html#autotoc_md291',1,'']]],
  ['behind_20the_20makefile_67',['The flags behind the Makefile',['../tools_smconv.html#autotoc_md508',1,'']]],
  ['behind_20things_68',['Foreground occlusion — walking behind things',['../craft_backgrounds.html#autotoc_md444',1,'']]],
  ['belongs_20in_20vblank_20mapupdate_20does_20not_69',['🟠 &lt;span class=&quot;tt&quot;&gt;mapVblank()&lt;/span&gt; belongs in VBlank, &lt;span class=&quot;tt&quot;&gt;mapUpdate()&lt;/span&gt; does not',['../tutorial_map.html#autotoc_md259',1,'']]],
  ['between_20levels_70',['8. Color Cycling Between Levels',['../examples_games_breakout.html#autotoc_md1201',1,'']]],
  ['between_20makefile_20and_20code_71',['🔴 &lt;span class=&quot;tt&quot;&gt;SRAM_SIZE&lt;/span&gt; mismatch between Makefile and code',['../tutorial_sram.html#autotoc_md392',1,'']]],
  ['between_20scenes_72',['🟡 Window state survives between scenes',['../tutorial_window.html#autotoc_md434',1,'']]],
  ['between_20states_73',['VRAM Reload Between States',['../tutorial_game_states.html#autotoc_md189',1,'']]],
  ['bg_20layer_74',['🔴 Single BG layer',['../tutorial_mode7.html#autotoc_md297',1,'']]],
  ['bg_20masking_75',['Window for Color Math (Not for BG Masking)',['../examples_windows_transparent_window.html#autotoc_md1752',1,'']]],
  ['bg_20mode_205_20interlace_20512_20×_20448_76',['Hi-res text — BG Mode 5 + interlace (512 × 448)',['../examples_backgrounds_mode5_hires.html',1,'examples_backgrounds']]],
  ['bg_20scrolling_77',['Basic BG Scrolling',['../tutorial_scrolling.html#autotoc_md350',1,'']]],
  ['bg_20scrolling_20works_78',['How BG Scrolling Works',['../tutorial_scrolling.html#autotoc_md348',1,'']]],
  ['bg_20vs_20sprites_79',['2. CGRAM — 256 colours, split BG vs sprites',['../craft_planning.html#autotoc_md470',1,'']]],
  ['bg_20window_80',['Color Math Window vs BG Window',['../examples_windows_transparent_window.html#autotoc_md1756',1,'']]],
  ['bg1_81',['BG1',['../examples_input_superscope.html#autotoc_md1367',1,'2. Text System (BG1)'],['../examples_scrolling_mixed_scroll.html#autotoc_md1578',1,'4. Auto-Scroll BG1']]],
  ['bg1_204bpp_20in_20mode_201_82',['1. Set up text on BG1 (4bpp in Mode 1)',['../examples_sprites_sprite_sizes.html#autotoc_md1662',1,'']]],
  ['bg1_20and_20enable_20display_83',['4. Configure BG1 and Enable Display',['../examples_backgrounds_mode1_lz77.html#autotoc_md1005',1,'']]],
  ['bg1_20bg2_84',['3. Enable Mode 1 with BG1 + BG2',['../examples_scrolling_mixed_scroll.html#autotoc_md1577',1,'']]],
  ['bg12nba_20bg34nba_20tile_20data_20address_85',['$210B-$210C - BG12NBA/BG34NBA (Tile Data Address)',['../registers.html#autotoc_md798',1,'']]],
  ['bg1hofs_20_24210d_20ndash_20write_20twice_20register_86',['BG1HOFS ($210D) &amp;ndash; Write-Twice Register',['../examples_scrolling_parallax_scroll.html#autotoc_md1590',1,'']]],
  ['bg1sc_20bg4sc_20tilemap_20address_20size_87',['$2107-$210A - BG1SC-BG4SC (Tilemap Address/Size)',['../registers.html#autotoc_md797',1,'']]],
  ['bg2_88',['BG2',['../examples_input_superscope.html#autotoc_md1368',1,'3. Calibration Background (BG2)'],['../examples_scrolling_mixed_scroll.html#autotoc_md1577',1,'3. Enable Mode 1 with BG1 + BG2']]],
  ['bg2_20is_20sub_20screen_20only_20trap_89',['🔴 The &quot;BG2 is sub-screen-only&quot; trap',['../tutorial_colormath.html#autotoc_md148',1,'']]],
  ['bg3_90',['BG3',['../examples_backgrounds_mode2.html',1,'mode2 — offset-per-tile: per-column scroll from BG3'],['../examples_games_shmup_1942.html#autotoc_md1272',1,'Open chantier — S6 HUD on BG3']]],
  ['bg3_20high_20priority_91',['3. Enable BG3 high priority',['../examples_backgrounds_mode1_bg3_priority.html#autotoc_md987',1,'']]],
  ['bg3_20high_20priority_20hud_20layer_20over_20backgrounds_92',['Mode 1 BG3 High Priority -- HUD Layer Over Backgrounds',['../examples_backgrounds_mode1_bg3_priority.html',1,'examples_backgrounds']]],
  ['bg3_20is_202bpp_20in_20mode_201_93',['BG3 is 2bpp in Mode 1',['../examples_backgrounds_mode1_bg3_priority.html#autotoc_md990',1,'']]],
  ['bg3_20priority_20high_94',['Mode 1 with BG3 Priority High',['../examples_color_transparency.html#autotoc_md1153',1,'']]],
  ['bg3_20specifics_95',['BG3 Specifics',['../examples_backgrounds_mode1.html#autotoc_md977',1,'']]],
  ['bg34nba_20tile_20data_20address_96',['$210B-$210C - BG12NBA/BG34NBA (Tile Data Address)',['../registers.html#autotoc_md798',1,'']]],
  ['bg4sc_20tilemap_20address_20size_97',['$2107-$210A - BG1SC-BG4SC (Tilemap Address/Size)',['../registers.html#autotoc_md797',1,'']]],
  ['bgmode_20background_20mode_98',['$2105 - BGMODE (Background Mode)',['../registers.html#autotoc_md795',1,'']]],
  ['bgnhofs_20bgnvofs_20scroll_20registers_99',['$210D-$2114 - BGnHOFS/BGnVOFS (Scroll Registers)',['../registers.html#autotoc_md800',1,'']]],
  ['bgnvofs_20scroll_20registers_100',['$210D-$2114 - BGnHOFS/BGnVOFS (Scroll Registers)',['../registers.html#autotoc_md800',1,'']]],
  ['bgr_101',['Color Format (15-bit BGR)',['../snes_graphics_guide.html#autotoc_md639',1,'']]],
  ['bgs_102',['Simple Parallax (Multiple BGs)',['../tutorial_scrolling.html#autotoc_md354',1,'']]],
  ['bgsetscroll_20dirty_20flags_103',['3. Scroll Updates via bgSetScroll Dirty Flags',['../examples_scrolling_continuous_scroll.html#autotoc_md1552',1,'']]],
  ['bigger_20than_20the_20screen_104',['1. The World Is Bigger Than the Screen',['../examples_games_likemario.html#autotoc_md1222',1,'']]],
  ['bigger_20than_20vram_20—_20so_20stream_20it_105',['The level is bigger than VRAM — so stream it',['../craft_tiles_to_levels.html#autotoc_md482',1,'']]],
  ['bit_20bgr_106',['Color Format (15-bit BGR)',['../snes_graphics_guide.html#autotoc_md639',1,'']]],
  ['bit_20gradient_20—_20brightness_20dithered_20backdrop_107',['&quot;9-bit&quot; gradient — brightness-dithered backdrop',['../examples_color_gradient_9bit.html',1,'examples_color']]],
  ['bitmap_20rendering_108',['PLOT Bitmap Rendering',['../tutorial_superfx.html#autotoc_md413',1,'']]],
  ['bitmask_109',['Button Bitmask',['../examples_input_controller.html#autotoc_md1338',1,'']]],
  ['bits_110',['Tilemap Palette Bits',['../examples_backgrounds_mode1_bg3_priority.html#autotoc_md991',1,'']]],
  ['bits_20per_20sprite_111',['Extended Table (2 bits per sprite)',['../oam.html#autotoc_md756',1,'']]],
  ['black_112',['Fade Out (Full to Black)',['../examples_transitions_fading.html#autotoc_md1707',1,'']]],
  ['black_113',['ROM loads but screen is black',['../troubleshooting.html#autotoc_md711',1,'']]],
  ['black_20fade_20to_20white_114',['Fade-to-black / fade-to-white',['../tutorial_colormath.html#autotoc_md141',1,'']]],
  ['black_20screen_20crash_115',['Runtime Issues (Black Screen / Crash)',['../troubleshooting.html#autotoc_md710',1,'']]],
  ['black_20screen_20when_20running_20rom_116',['Black screen when running ROM',['../getting_started.html#autotoc_md545',1,'']]],
  ['black_20to_20full_117',['Fade In (Black to Full)',['../examples_transitions_fading.html#autotoc_md1706',1,'']]],
  ['blank_118',['1. Initialize and Stay in Force Blank',['../examples_backgrounds_mode1_lz77.html#autotoc_md1002',1,'']]],
  ['blank_119',['2. Load sprites with force blank',['../examples_sprites_sprite_sizes.html#autotoc_md1663',1,'']]],
  ['blank_20—_20do_20not_20do_20it_20yourself_20with_20setbrightness_200_120',['🔴 &lt;span class=&quot;tt&quot;&gt;panelFlush&lt;/span&gt; uploads under forced blank — do not do it yourself with &lt;span class=&quot;tt&quot;&gt;setBrightness(0)&lt;/span&gt;',['../tutorial_panel.html#autotoc_md324',1,'']]],
  ['blank_20are_20silently_20dropped_121',['🔴 VRAM/CGRAM/OAM writes outside VBlank or force blank are silently dropped',['../tutorial_dma.html#autotoc_md175',1,'']]],
  ['blank_20for_20initial_20setup_122',['Force Blank for Initial Setup',['../examples_sprites_dynamic_sprite.html#autotoc_md1628',1,'']]],
  ['blank_20for_20large_20dma_123',['Force Blank for Large DMA',['../examples_sprites_sprite_sizes.html#autotoc_md1669',1,'']]],
  ['blank_20for_20vram_20access_124',['Force Blank for VRAM Access',['../examples_backgrounds_mode1_lz77.html#autotoc_md999',1,'']]],
  ['blank_20joypad_20status_125',['$4212 - HVBJOY (Blank/Joypad Status)',['../registers.html#autotoc_md818',1,'']]],
  ['blank_20vblank_126',['Vertical Blank (VBlank)',['../hardware_overview.html#autotoc_md778',1,'']]],
  ['blank_20vs_20brightness_200_127',['Force Blank vs Brightness 0',['../examples_transitions_fading.html#autotoc_md1725',1,'']]],
  ['blend_128',['&quot;3840 colors&quot; — RGB channel-split blend',['../examples_color_hicolor_blend.html',1,'examples_color']]],
  ['blend_20—_20examples_20windows_20transparent_5fwindow_129',['Window-gated spotlight blend — &lt;span class=&quot;tt&quot;&gt;examples/windows/transparent_window&lt;/span&gt;',['../tutorial_colormath.html#autotoc_md146',1,'']]],
  ['block_20effect_130',['Mosaic -- PPU Pixel Block Effect',['../examples_transitions_mosaic.html',1,'examples_transitions']]],
  ['block_20size_20is_20size_201_20pixels_131',['🟡 Mosaic block size is &quot;size + 1&quot; pixels',['../tutorial_mosaic.html#autotoc_md314',1,'']]],
  ['block_20structure_209_20bytes_132',['Block Structure (9 bytes)',['../snes_sound_guide.html#autotoc_md669',1,'']]],
  ['blocking_133',['🟡 &lt;span class=&quot;tt&quot;&gt;mosaicFadeIn&lt;/span&gt; / &lt;span class=&quot;tt&quot;&gt;mosaicFadeOut&lt;/span&gt; are blocking',['../tutorial_mosaic.html#autotoc_md315',1,'']]],
  ['blow_20the_20budget_134',['When you blow the budget',['../craft_frame_budget.html#autotoc_md458',1,'']]],
  ['blur_135',['Not a Blur',['../examples_transitions_mosaic.html#autotoc_md1740',1,'']]],
  ['boot_136',['Upload Protocol (Boot)',['../snes_sound_guide.html#autotoc_md685',1,'']]],
  ['boot_20are_20undefined_137',['🔴 SRAM contents on first boot are undefined',['../tutorial_sram.html#autotoc_md390',1,'']]],
  ['boot_20code_138',['2. Write Your SA-1 Boot Code',['../tutorial_sa1.html#autotoc_md333',1,'']]],
  ['both_20controllers_139',['Reading Both Controllers',['../examples_input_two_players.html#autotoc_md1385',1,'']]],
  ['both_20ends_140',['Boundaries are inclusive on both ends',['../tutorial_window.html#autotoc_md424',1,'']]],
  ['both_20for_20transitions_141',['3. Combining both for transitions',['../examples_transitions_mosaic.html#autotoc_md1737',1,'']]],
  ['both_20tilesets_20and_20palettes_142',['1. Load Both Tilesets and Palettes',['../examples_scrolling_mixed_scroll.html#autotoc_md1575',1,'']]],
  ['both_20windows_20animated_20per_20scanline_143',['Multi-window HDMA — both windows animated per scanline',['../examples_windows_window_multi_hdma.html',1,'examples_windows']]],
  ['both_20windows_20per_20scanline_20—_20examples_20windows_20window_5fmulti_5fhdma_144',['Both windows per scanline — &lt;span class=&quot;tt&quot;&gt;examples/windows/window_multi_hdma&lt;/span&gt;',['../tutorial_window.html#autotoc_md438',1,'']]],
  ['bounce_20physics_145',['6. Paddle Bounce Physics',['../examples_games_breakout.html#autotoc_md1199',1,'']]],
  ['bouncing_20breakout_20pattern_146',['Bouncing (Breakout Pattern)',['../tutorial_collision.html#autotoc_md132',1,'']]],
  ['bouncing_20swarm_20and_20the_20oam_20throughput_20ceiling_147',['sprite_swarm — a bouncing swarm, and the OAM throughput ceiling',['../examples_sprites_sprite_swarm.html',1,'examples_sprites']]],
  ['boundaries_20are_20inclusive_20on_20both_20ends_148',['Boundaries are inclusive on both ends',['../tutorial_window.html#autotoc_md424',1,'']]],
  ['boundary_20register_20sequencing_20during_20hdma_149',['🟡 Boundary register sequencing during HDMA',['../tutorial_window.html#autotoc_md435',1,'']]],
  ['bounds_20behaviour_150',['Out-of-bounds behaviour',['../tutorial_mode7.html#autotoc_md291',1,'']]],
  ['bounds_20with_20mode7_5ftransparent_20shows_20the_20backdrop_20not_20a_20layer_151',['🟡 Out-of-bounds with &lt;span class=&quot;tt&quot;&gt;MODE7_TRANSPARENT&lt;/span&gt; shows the backdrop, not a layer',['../tutorial_mode7.html#autotoc_md302',1,'']]],
  ['box_152',['box',['../examples_basics_panel_hud.html',1,'panel_hud — a HUD that survives a dialog box'],['../tutorial_panel.html#autotoc_md321',1,'The minimum viable dialog box']]],
  ['branch_153',['Target branch',['../contributing.html#autotoc_md1796',1,'']]],
  ['branch_20delay_20slot_154',['1. NOP After Every Branch (Delay Slot)',['../tutorial_superfx.html#autotoc_md409',1,'']]],
  ['branching_20and_20release_20policy_155',['Branching and release policy',['../contributing.html#autotoc_md1794',1,'']]],
  ['break_20at_20a_20function_156',['Recipe 3 — Break at a function',['../tutorial_debugging.html#autotoc_md160',1,'']]],
  ['breakout_157',['Breakout',['../examples_games_breakout.html',1,'Breakout'],['../tutorial_game_states.html#autotoc_md195',1,'Simple Game Over (Breakout)']]],
  ['breakout_20bricks_158',['Grid-Based Collision (Breakout Bricks)',['../tutorial_collision.html#autotoc_md134',1,'']]],
  ['breakout_20pattern_159',['Bouncing (Breakout Pattern)',['../tutorial_collision.html#autotoc_md132',1,'']]],
  ['breaks_160',['breaks',['../examples_backgrounds_mode2.html#autotoc_md1012',1,'What to observe / if it breaks'],['../examples_basics_game_skeleton.html#autotoc_md1059',1,'What to observe / if it breaks'],['../examples_basics_panel_hud.html#autotoc_md1065',1,'What to observe / if it breaks'],['../examples_color_palette_cycle.html#autotoc_md1135',1,'What to observe / if it breaks'],['../examples_color_shadow_tint.html#autotoc_md1143',1,'What to observe / if it breaks'],['../examples_sprites_sprite_swarm.html#autotoc_md1675',1,'What to observe / if it breaks']]],
  ['bricks_161',['Bricks',['../examples_games_breakout.html#autotoc_md1198',1,'5. Grid Collision (Don&apos;t Loop Over 100 Bricks)'],['../tutorial_collision.html#autotoc_md134',1,'Grid-Based Collision (Breakout Bricks)']]],
  ['bricks_20are_20not_20sprites_162',['4. Bricks Are Not Sprites',['../examples_games_breakout.html#autotoc_md1197',1,'']]],
  ['brightness_163',['1. Fade effect (brightness)',['../examples_transitions_mosaic.html#autotoc_md1735',1,'']]],
  ['brightness_200_164',['Force Blank vs Brightness 0',['../examples_transitions_fading.html#autotoc_md1725',1,'']]],
  ['brightness_20dithered_20backdrop_165',['&quot;9-bit&quot; gradient — brightness-dithered backdrop',['../examples_color_gradient_9bit.html',1,'examples_color']]],
  ['browse_20examples_20by_20category_166',['Browse Examples by Category',['../examples_by_category.html',1,'index']]],
  ['brr_20sample_20format_167',['BRR Sample Format',['../snes_sound_guide.html#autotoc_md668',1,'']]],
  ['brr_20sound_20samples_168',['wav2brr — WAV to BRR sound samples',['../tools_wav2brr.html',1,'tools']]],
  ['budget_169',['Budget',['../examples_mode7_perspective.html#autotoc_md1506',1,'HDMA Budget'],['../tutorial_animation.html#autotoc_md92',1,'VBlank Budget']]],
  ['budget_170',['budget',['../craft_frame_budget.html',1,'The frame budget'],['../craft_frame_budget.html#autotoc_md458',1,'When you blow the budget']]],
  ['budget_2064kb_20total_171',['Memory Budget (64KB total)',['../snes_sound_guide.html#autotoc_md690',1,'']]],
  ['budget_20during_20vblank_172',['VRAM Budget During VBlank',['../examples_sprites_dynamic_sprite.html#autotoc_md1626',1,'']]],
  ['budget_20is_204_20kb_20per_20frame_173',['🔴 VBlank DMA budget is ~4 KB per frame',['../tutorial_dma.html#autotoc_md176',1,'']]],
  ['budget_3a_203_2058_20mhz_174',['The CPU budget: ~3.58 MHz',['../craft_frame_budget.html#autotoc_md457',1,'']]],
  ['budget_3a_2032_175',['The sprite-per-line budget: 32',['../craft_frame_budget.html#autotoc_md456',1,'']]],
  ['budget_3a_204_20kb_176',['The VBlank DMA budget: ~4 KB',['../craft_frame_budget.html#autotoc_md455',1,'']]],
  ['budgets_177',['The three budgets',['../craft_planning.html#autotoc_md468',1,'']]],
  ['buffer_178',['Critical: OAM Write Buffer',['../oam.html#autotoc_md757',1,'']]],
  ['buffer_20pattern_179',['3. ROM is Read-Only (The RAM Buffer Pattern)',['../examples_games_breakout.html#autotoc_md1196',1,'']]],
  ['buffer_20vs_20hardware_180',['Recipe 4 — Sprite/OAM debugging (shadow buffer vs hardware)',['../tutorial_debugging.html#autotoc_md161',1,'']]],
  ['bugs_181',['Bugs',['../troubleshooting.html#autotoc_md727',1,'Reporting Bugs'],['../contributing.html#autotoc_md1790',1,'Reporting Bugs']]],
  ['bugs_20this_20port_20surfaced_182',['Two SDK bugs this port surfaced',['../examples_color_hicolor_1792.html#autotoc_md1129',1,'']]],
  ['build_183',['Build',['../getting_started.html#autotoc_md535',1,'B2. Clone and Build'],['../debug_8h.html#autotoc_md24',1,'Build'],['../profile_8h.html#autotoc_md52',1,'Build'],['../examples_games_shmup_1942.html#autotoc_md1274',1,'Build'],['../examples_audio_apu_switch.html#autotoc_md846',1,'How to Build'],['../examples_audio_pitch_mod.html#autotoc_md856',1,'How to Build'],['../examples_audio_play_noise.html#autotoc_md859',1,'How to Build'],['../examples_audio_sfx_from_wav.html#autotoc_md865',1,'How to Build'],['../examples_audio_soundboard.html#autotoc_md935',1,'How to Build'],['../examples_backgrounds_mode5_hires.html#autotoc_md1028',1,'How to Build'],['../examples_basics_aim_target.html#autotoc_md1034',1,'How to Build'],['../examples_basics_fix32_orbit.html#autotoc_md1054',1,'How to Build'],['../examples_basics_scene_stack.html#autotoc_md1085',1,'How to Build'],['../examples_chips_dsp1_cube.html#autotoc_md1096',1,'How to Build'],['../examples_color_direct_color.html#autotoc_md1120',1,'How to Build'],['../examples_color_gradient_9bit.html#autotoc_md1124',1,'How to Build'],['../examples_color_hicolor_1792.html#autotoc_md1130',1,'How to Build'],['../examples_games_mode7_flying.html#autotoc_md1258',1,'How to Build'],['../examples_games_mode7_racing.html#autotoc_md1261',1,'How to Build'],['../examples_games_rpg.html#autotoc_md1268',1,'How to Build'],['../examples_hdma_hdma_indirect_gradient.html#autotoc_md1302',1,'How to Build'],['../examples_hdma_hdma_wave_table.html#autotoc_md1329',1,'How to Build'],['../examples_mode7_perspective_rotate.html#autotoc_md1514',1,'How to Build'],['../examples_windows_window_multi_hdma.html#autotoc_md1776',1,'How to Build'],['../examples_fundamentals_text_glyphs.html#autotoc_md1182',1,'Under the Hood: The Build'],['../examples_games_breakout.html#autotoc_md1208',1,'Under the Hood: The Build'],['../examples_games_likemario.html#autotoc_md1234',1,'Under the Hood: The Build'],['../examples_hdma_hdma_wave.html#autotoc_md1320',1,'Under the Hood: The Build'],['../examples_input_superscope.html#autotoc_md1373',1,'Under the Hood: The Build'],['../examples_scrolling_continuous_scroll.html#autotoc_md1560',1,'Under the Hood: The Build']]],
  ['build_184',['build',['../examples_audio_echo.html#autotoc_md850',1,'How to build'],['../examples_input_move_sprite.html#autotoc_md1357',1,'How to build'],['../examples_text_print_string.html#autotoc_md1681',1,'How to build'],['../examples_text_scroll_message.html#autotoc_md1693',1,'How to build']]],
  ['build_20a_20world_185',['Stage 3 — &quot;Can I build a world?&quot;',['../learning_path.html#autotoc_md552',1,'']]],
  ['build_20fails_20with_20library_20not_20built_186',['Build fails with &quot;Library not built&quot;',['../getting_started.html#autotoc_md544',1,'']]],
  ['build_20fails_20with_20smconv_20error_187',['Build fails with smconv error',['../examples_audio_snesmod_music.html#autotoc_md905',1,'']]],
  ['build_20fails_20with_20unhandled_20op_20or_20assembly_20errors_188',['Build fails with &quot;unhandled op&quot; or assembly errors',['../getting_started.html#autotoc_md546',1,'']]],
  ['build_20fails_20with_20unhandled_20op_3a_20xxx_189',['Build fails with &quot;unhandled op: XXX&quot;',['../troubleshooting.html#autotoc_md708',1,'']]],
  ['build_20issues_190',['Build Issues',['../troubleshooting.html#autotoc_md703',1,'']]],
  ['build_20process_191',['Build Process',['../examples_audio_snesmod_music.html#autotoc_md885',1,'']]],
  ['build_20run_192',['Build Run',['../examples_audio_snesmod_music.html#autotoc_md889',1,'Build &amp;amp; Run'],['../examples_audio_snesmod_music_large.html#autotoc_md917',1,'Build &amp;amp; Run'],['../examples_audio_snesmod_sfx.html#autotoc_md921',1,'Build &amp;amp; Run'],['../examples_backgrounds_mode1.html#autotoc_md965',1,'Build &amp;amp; Run'],['../examples_backgrounds_mode1_bg3_priority.html#autotoc_md983',1,'Build &amp;amp; Run'],['../examples_backgrounds_mode1_lz77.html#autotoc_md1008',1,'Build &amp;amp; Run'],['../examples_basics_collision_demo.html#autotoc_md1037',1,'Build &amp;amp; Run'],['../examples_basics_random.html#autotoc_md1075',1,'Build &amp;amp; Run'],['../examples_basics_timer.html#autotoc_md1093',1,'Build &amp;amp; Run'],['../examples_chips_sa1_hello.html#autotoc_md1100',1,'Build &amp;amp; Run'],['../examples_chips_sa1_starfield.html#autotoc_md1104',1,'Build &amp;amp; Run'],['../examples_chips_superfx_3d.html#autotoc_md1109',1,'Build &amp;amp; Run'],['../examples_chips_superfx_hello.html#autotoc_md1115',1,'Build &amp;amp; Run'],['../examples_color_transparency.html#autotoc_md1147',1,'Build &amp;amp; Run'],['../examples_fundamentals_text_glyphs.html#autotoc_md1165',1,'Build &amp;amp; Run'],['../examples_games_breakout.html#autotoc_md1190',1,'Build &amp;amp; Run'],['../examples_games_likemario.html#autotoc_md1218',1,'Build &amp;amp; Run'],['../examples_games_mapandobjects.html#autotoc_md1256',1,'Build &amp;amp; Run'],['../examples_hdma_gradient_colors.html#autotoc_md1285',1,'Build &amp;amp; Run'],['../examples_hdma_hdma_wave.html#autotoc_md1305',1,'Build &amp;amp; Run'],['../examples_input_controller.html#autotoc_md1340',1,'Build &amp;amp; Run'],['../examples_input_mouse.html#autotoc_md1354',1,'Build &amp;amp; Run'],['../examples_input_superscope.html#autotoc_md1363',1,'Build &amp;amp; Run'],['../examples_input_two_players.html#autotoc_md1401',1,'Build &amp;amp; Run'],['../examples_maps_dynamic_map.html#autotoc_md1427',1,'Build &amp;amp; Run'],['../examples_maps_map_scroll.html#autotoc_md1435',1,'Build &amp;amp; Run'],['../examples_maps_slope_collision.html#autotoc_md1447',1,'Build &amp;amp; Run'],['../examples_maps_tiled.html#autotoc_md1456',1,'Build &amp;amp; Run'],['../examples_memory_hirom_demo.html#autotoc_md1461',1,'Build &amp;amp; Run'],['../examples_memory_save_game.html#autotoc_md1481',1,'Build &amp;amp; Run'],['../examples_mode7_perspective.html#autotoc_md1498',1,'Build &amp;amp; Run'],['../examples_mode7_rotate_scale.html#autotoc_md1521',1,'Build &amp;amp; Run'],['../examples_scrolling_continuous_scroll.html#autotoc_md1546',1,'Build &amp;amp; Run'],['../examples_scrolling_mixed_scroll.html#autotoc_md1580',1,'Build &amp;amp; Run'],['../examples_scrolling_parallax_scroll.html#autotoc_md1583',1,'Build &amp;amp; Run'],['../examples_sprites_animated_sprite.html#autotoc_md1600',1,'Build &amp;amp; Run'],['../examples_sprites_dynamic_metasprite.html#autotoc_md1612',1,'Build &amp;amp; Run'],['../examples_sprites_dynamic_sprite.html#autotoc_md1619',1,'Build &amp;amp; Run'],['../examples_sprites_metasprite.html#autotoc_md1639',1,'Build &amp;amp; Run'],['../examples_sprites_simple_sprite.html#autotoc_md1645',1,'Build &amp;amp; Run'],['../examples_sprites_sprite_sizes.html#autotoc_md1660',1,'Build &amp;amp; Run'],['../examples_transitions_fading.html#autotoc_md1714',1,'Build &amp;amp; Run'],['../examples_transitions_mosaic.html#autotoc_md1733',1,'Build &amp;amp; Run'],['../examples_windows_transparent_window.html#autotoc_md1749',1,'Build &amp;amp; Run'],['../examples_windows_window.html#autotoc_md1761',1,'Build &amp;amp; Run']]],
  ['build_20run_193',['Build run',['../examples_backgrounds_mode2.html#autotoc_md1013',1,'Build &amp;amp; run'],['../examples_basics_game_skeleton.html#autotoc_md1060',1,'Build &amp;amp; run'],['../examples_basics_panel_hud.html#autotoc_md1066',1,'Build &amp;amp; run'],['../examples_color_palette_cycle.html#autotoc_md1136',1,'Build &amp;amp; run'],['../examples_color_shadow_tint.html#autotoc_md1144',1,'Build &amp;amp; run'],['../examples_sprites_sprite_swarm.html#autotoc_md1676',1,'Build &amp;amp; run']]],
  ['build_20setup_194',['Build setup',['../tutorial_sram.html#autotoc_md381',1,'']]],
  ['building_195',['Building',['../examples.html#autotoc_md1541',1,'']]],
  ['building_20it_196',['Designing the level, not just building it',['../craft_tiles_to_levels.html#autotoc_md485',1,'']]],
  ['built_197',['Build fails with &quot;Library not built&quot;',['../getting_started.html#autotoc_md544',1,'']]],
  ['bullet_20despawn_20fix_20s5_202_198',['Bullet despawn fix (S5.2)',['../examples_games_shmup_1942.html#autotoc_md1271',1,'']]],
  ['bus_199',['The Exclusive Bus',['../tutorial_superfx.html#autotoc_md407',1,'']]],
  ['bus_20address_200',['$43x1 - BBADx (B-Bus Address)',['../registers.html#autotoc_md829',1,'']]],
  ['but_20crashes_20after_20a_20few_20seconds_201',['ROM runs but crashes after a few seconds',['../troubleshooting.html#autotoc_md712',1,'']]],
  ['but_20far_20fewer_20per_20line_202',['3. OAM — 128 sprites, but far fewer per line',['../craft_planning.html#autotoc_md471',1,'']]],
  ['but_20not_20tilemaps_203',['Why Compress Tiles but Not Tilemaps?',['../examples_backgrounds_mode1_lz77.html#autotoc_md998',1,'']]],
  ['but_20screen_20is_20black_204',['ROM loads but screen is black',['../troubleshooting.html#autotoc_md711',1,'']]],
  ['but_20you_20don_20t_20have_20to_20think_20about_20it_205',['🟠 Endianness — but you don&apos;t have to think about it',['../tutorial_sram.html#autotoc_md395',1,'']]],
  ['button_20actions_206',['Exercise 3: Button Actions',['../examples_input_two_players.html#autotoc_md1408',1,'']]],
  ['button_20bitmask_207',['Button Bitmask',['../examples_input_controller.html#autotoc_md1338',1,'']]],
  ['button_20combinations_208',['Button Combinations',['../tutorial_input.html#autotoc_md245',1,'']]],
  ['button_20constants_209',['Button Constants',['../input_8h.html#autotoc_md36',1,'Button Constants'],['../tutorial_input.html#autotoc_md238',1,'Button Constants']]],
  ['button_20handling_210',['5. Button Handling',['../examples_input_mouse.html#autotoc_md1352',1,'']]],
  ['button_20layout_211',['Button Layout',['../examples_input_two_players.html#autotoc_md1415',1,'']]],
  ['by_20a_20tiled_20map_212',['rpg — an RPG template driven by a Tiled map',['../examples_games_rpg.html',1,'examples_games']]],
  ['by_20category_213',['Browse Examples by Category',['../examples_by_category.html',1,'index']]],
  ['by_20changing_20frame_20ids_214',['4. Animate by changing frame IDs',['../examples_sprites_dynamic_sprite.html#autotoc_md1624',1,'']]],
  ['by_20consoleinit_215',['🟡 Mosaic state is not reset by &lt;span class=&quot;tt&quot;&gt;consoleInit&lt;/span&gt;',['../tutorial_mosaic.html#autotoc_md316',1,'']]],
  ['by_20everything_20on_20screen_216',['1. VRAM — 64 KB, shared by everything on screen',['../craft_planning.html#autotoc_md469',1,'']]],
  ['by_20mode_217',['The cost side: tiles by mode',['../craft_planning.html#autotoc_md473',1,'']]],
  ['by_20rotating_20cgram_218',['palette_cycle — animate by rotating CGRAM',['../examples_color_palette_cycle.html',1,'examples_color']]],
  ['by_20topic_219',['By Topic',['../group__examples.html#autotoc_md1778',1,'']]],
  ['by_20zero_220',['🟠 &lt;span class=&quot;tt&quot;&gt;fixDiv&lt;/span&gt; returns 0 on divide-by-zero',['../tutorial_math.html#autotoc_md278',1,'']]],
  ['byte_203_221',['Attribute Byte (Byte 3)',['../oam.html#autotoc_md755',1,'']]],
  ['byte_20byte_203_222',['Attribute Byte (Byte 3)',['../oam.html#autotoc_md755',1,'']]],
  ['byte_20is_20the_20color_223',['direct_color — the pixel byte IS the color',['../examples_color_direct_color.html',1,'examples_color']]],
  ['byte_20limitation_224',['Bank Byte Limitation',['../hdma_8h.html#autotoc_md34',1,'']]],
  ['byte_20registration_225',['Assembly Bank Byte Registration',['../examples_maps_slope_collision.html#autotoc_md1443',1,'']]],
  ['byte_20trap_20on_20hdmasetup_226',['🔴 Bank byte trap on &lt;span class=&quot;tt&quot;&gt;hdmaSetup&lt;/span&gt;',['../tutorial_hdma.html#autotoc_md231',1,'']]],
  ['bytes_227',['5. Two Colors, Four Bytes',['../examples_fundamentals_text_glyphs.html#autotoc_md1174',1,'']]],
  ['bytes_228',['bytes',['../snes_sound_guide.html#autotoc_md669',1,'Block Structure (9 bytes)'],['../snes_graphics_guide.html#autotoc_md638',1,'CGRAM Layout (256 colors × 2 bytes)']]],
  ['bytes_20per_20sprite_229',['Main Table (4 bytes per sprite)',['../oam.html#autotoc_md754',1,'']]],
  ['bytes_20total_230',['OAM Structure (544 bytes total)',['../snes_graphics_guide.html#autotoc_md624',1,'']]]
];
