var searchData=
[
  ['l_20—_20save_20x_20through_20a_0',['No &lt;span class=&quot;tt&quot;&gt;stx.l&lt;/span&gt; — Save X Through A',['../tutorial_sa1.html#autotoc_md358',1,'']]],
  ['l_20for_20everything_1',['Use &lt;span class=&quot;tt&quot;&gt;sta.l&lt;/span&gt; / &lt;span class=&quot;tt&quot;&gt;lda.l&lt;/span&gt; for Everything',['../tutorial_sa1.html#autotoc_md356',1,'']]],
  ['l_20lda_20l_20for_20everything_2',['Use &lt;span class=&quot;tt&quot;&gt;sta.l&lt;/span&gt; / &lt;span class=&quot;tt&quot;&gt;lda.l&lt;/span&gt; for Everything',['../tutorial_sa1.html#autotoc_md356',1,'']]],
  ['l_20table_20x_3',['ROM Table Lookups with &lt;span class=&quot;tt&quot;&gt;lda.l table,x&lt;/span&gt;',['../tutorial_sa1.html#autotoc_md357',1,'']]],
  ['labels_4',['Labels',['../code_style.html#autotoc_md632',1,'']]],
  ['ladder_5',['Ladder',['../examples_audio_echo.html#autotoc_md879',1,'Ladder'],['../examples_input_move_sprite.html#autotoc_md1386',1,'Ladder'],['../examples_text_scroll_message.html#autotoc_md1733',1,'Ladder']]],
  ['ladder_6',['ladder',['../examples_audio.html#autotoc_md888',1,'The ladder'],['../examples_backgrounds.html#autotoc_md1057',1,'The ladder'],['../examples_chips.html#autotoc_md1125',1,'The ladder'],['../examples_color.html#autotoc_md1166',1,'The ladder'],['../examples_hdma.html#autotoc_md1358',1,'The ladder'],['../examples_input.html#autotoc_md1387',1,'The ladder'],['../examples_maps.html#autotoc_md1463',1,'The ladder'],['../examples_mode7.html#autotoc_md1550',1,'The ladder'],['../examples_scrolling.html#autotoc_md1629',1,'The ladder'],['../examples_sprites.html#autotoc_md1678',1,'The ladder'],['../examples_transitions.html#autotoc_md1782',1,'The ladder'],['../examples_windows.html#autotoc_md1784',1,'The ladder']]],
  ['landing_7',['Snapping to Tile Grid (Platformer Landing)',['../tutorial_collision.html#autotoc_md133',1,'']]],
  ['large_20dma_8',['Force Blank for Large DMA',['../examples_sprites_sprite_sizes.html#autotoc_md1707',1,'']]],
  ['large_20or_20linker_20errors_20about_20size_9',['&quot;ROM too large&quot; or linker errors about size',['../troubleshooting.html#autotoc_md748',1,'']]],
  ['large_20soundbank_20music_10',['SNESMOD Large Soundbank Music',['../examples_audio_snesmod_music_large.html',1,'examples_audio']]],
  ['latch_11',['latch',['../tutorial_mode7.html#autotoc_md312',1,'🟡 BG1 scroll and the Mode 7 registers share one write-twice latch'],['../tutorial_hdma.html#autotoc_md246',1,'🟡 HDMA on BG1 scroll can corrupt Mode 7 writes (shared latch)']]],
  ['latency_12',['Input Latency',['../examples_input_two_players.html#autotoc_md1441',1,'']]],
  ['launch_20from_20c_13',['4. Launch from C',['../tutorial_superfx.html#autotoc_md422',1,'']]],
  ['layer_14',['Layer',['../examples_backgrounds_mode1.html#autotoc_md997',1,'Exercise 1: Add a Second Layer'],['../examples_scrolling_parallax_scroll.html#autotoc_md1626',1,'Why This Works with One Layer']]],
  ['layer_15',['layer',['../tutorial_mode7.html#autotoc_md313',1,'🔴 Single BG layer'],['../tutorial_mode7.html#autotoc_md318',1,'🟡 Out-of-bounds with &lt;span class=&quot;tt&quot;&gt;MODE7_TRANSPARENT&lt;/span&gt; shows the backdrop, not a layer']]],
  ['layer_202bpp_20background_16',['Mode 0 — 4-Layer 2bpp Background',['../examples_backgrounds_mode0.html',1,'examples_backgrounds']]],
  ['layer_20a_20job_17',['Give every layer a job',['../craft_backgrounds.html#autotoc_md455',1,'']]],
  ['layer_20above_20the_20panel_18',['🟡 Text goes on a &lt;em&gt;different&lt;/em&gt; layer, above the panel',['../tutorial_panel.html#autotoc_md341',1,'']]],
  ['layer_20one_20upload_19',['Several panels, one layer, one upload',['../tutorial_panel.html#autotoc_md338',1,'']]],
  ['layer_20only_20',['One Layer Only',['../examples_mode7_rotate_scale.html#autotoc_md1563',1,'']]],
  ['layer_20options_21',['One-way and second-layer options',['../tutorial_map.html#autotoc_md269',1,'']]],
  ['layer_20order_22',['Depth is priority, not layer order',['../craft_backgrounds.html#autotoc_md456',1,'']]],
  ['layer_20over_20backgrounds_23',['Mode 1 BG3 High Priority -- HUD Layer Over Backgrounds',['../examples_backgrounds_mode1_bg3_priority.html',1,'examples_backgrounds']]],
  ['layer_20the_20little_20things_24',['Layer the little things',['../craft_game_feel.html#autotoc_md482',1,'']]],
  ['layers_25',['Layers',['../tutorial_scrolling.html#autotoc_md368',1,'Mixed Scroll (Static + Moving Layers)'],['../examples_windows_window.html#autotoc_md1805',1,'Switching Layers']]],
  ['layers_26',['layers',['../examples_backgrounds_mode1_bg3_priority.html#autotoc_md1012',1,'1. Set up three background layers'],['../craft_backgrounds.html',1,'Composing with backgrounds &amp; layers']]],
  ['layers_20can_20give_27',['When you need more than layers can give',['../craft_backgrounds.html#autotoc_md461',1,'']]],
  ['layers_20two_20speeds_28',['1. Two Layers, Two Speeds',['../examples_scrolling_continuous_scroll.html#autotoc_md1584',1,'']]],
  ['layout_29',['Layout',['../examples_games_likemario.html#autotoc_md1250',1,'2. The VRAM Layout'],['../examples_input_two_players.html#autotoc_md1442',1,'Button Layout'],['../examples_basics_collision_demo.html#autotoc_md1073',1,'Collision Map Layout'],['../tutorial_superfx.html#autotoc_md431',1,'Column-Major Tile Layout'],['../examples_audio_snesmod_music.html#autotoc_md920',1,'Memory Layout'],['../mode7_8h.html#autotoc_md48',1,'Mode 7 VRAM Layout'],['../examples_maps_dynamic_map.html#autotoc_md1448',1,'SC_64x64 Tilemap Layout'],['../tutorial_input.html#autotoc_md251',1,'SNES Controller Layout'],['../tutorial_animation.html#autotoc_md75',1,'Sprite Sheet Layout'],['../snes_graphics_guide.html#autotoc_md660',1,'VRAM Layout'],['../examples_backgrounds_mode1.html#autotoc_md987',1,'VRAM Layout'],['../examples_backgrounds_mode1_bg3_priority.html#autotoc_md1019',1,'VRAM Layout'],['../examples_sprites_sprite_sizes.html#autotoc_md1708',1,'VRAM Layout'],['../examples_windows_window.html#autotoc_md1809',1,'VRAM Layout']]],
  ['layout_30',['1. Sprite sheet layout',['../examples_sprites_animated_sprite.html#autotoc_md1636',1,'']]],
  ['layout_20256_20colors_20×_202_20bytes_31',['CGRAM Layout (256 colors × 2 bytes)',['../snes_graphics_guide.html#autotoc_md665',1,'']]],
  ['layout_20and_20oam_20tile_20numbers_32',['VRAM Tile Layout and OAM Tile Numbers',['../examples_sprites_metasprite.html#autotoc_md1673',1,'']]],
  ['layout_20convention_33',['I-RAM Layout Convention',['../tutorial_sa1.html#autotoc_md354',1,'']]],
  ['layout_20for_20text_34',['VRAM Layout for Text',['../examples_text.html#autotoc_md1726',1,'']]],
  ['layout_20lorom_35',['Memory Layout (LoROM)',['../sram_8h.html#autotoc_md63',1,'']]],
  ['layout_20mode_201_36',['Recommended Layout (Mode 1)',['../snes_graphics_guide.html#autotoc_md661',1,'']]],
  ['layout_20planning_37',['VRAM Layout Planning',['../examples_scrolling_mixed_scroll.html#autotoc_md1604',1,'']]],
  ['lda_20l_20for_20everything_38',['Use &lt;span class=&quot;tt&quot;&gt;sta.l&lt;/span&gt; / &lt;span class=&quot;tt&quot;&gt;lda.l&lt;/span&gt; for Everything',['../tutorial_sa1.html#autotoc_md356',1,'']]],
  ['lda_20l_20table_20x_39',['ROM Table Lookups with &lt;span class=&quot;tt&quot;&gt;lda.l table,x&lt;/span&gt;',['../tutorial_sa1.html#autotoc_md357',1,'']]],
  ['lead_20the_20action_20—_20look_20ahead_40',['Lead the action — look-ahead',['../craft_camera.html#autotoc_md465',1,'']]],
  ['learn_41',['Learn',['../examples_audio_snesmod_music_large.html#autotoc_md945',1,'What You&apos;ll Learn'],['../examples_audio_snesmod_sfx.html#autotoc_md950',1,'What You&apos;ll Learn'],['../examples_backgrounds_mode1_lz77.html#autotoc_md1022',1,'What You&apos;ll Learn'],['../examples_basics_collision_demo.html#autotoc_md1066',1,'What You&apos;ll Learn'],['../examples_basics_random.html#autotoc_md1096',1,'What You&apos;ll Learn'],['../examples_basics_scene_stack.html#autotoc_md1106',1,'What You&apos;ll Learn'],['../examples_basics_timer.html#autotoc_md1114',1,'What You&apos;ll Learn'],['../examples_chips_sa1_hello.html#autotoc_md1128',1,'What You&apos;ll Learn'],['../examples_chips_sa1_starfield.html#autotoc_md1132',1,'What You&apos;ll Learn'],['../examples_chips_superfx_3d.html#autotoc_md1137',1,'What You&apos;ll Learn'],['../examples_chips_superfx_hello.html#autotoc_md1143',1,'What You&apos;ll Learn'],['../examples_color_transparency.html#autotoc_md1176',1,'What You&apos;ll Learn'],['../examples_fundamentals_text_glyphs.html#autotoc_md1194',1,'What You&apos;ll Learn'],['../examples_games_breakout.html#autotoc_md1218',1,'What You&apos;ll Learn'],['../examples_games_likemario.html#autotoc_md1246',1,'What You&apos;ll Learn'],['../examples_games_mapandobjects.html#autotoc_md1270',1,'What You&apos;ll Learn'],['../examples_hdma_hdma_wave.html#autotoc_md1333',1,'What You&apos;ll Learn'],['../examples_input_controller.html#autotoc_md1360',1,'What You&apos;ll Learn'],['../examples_input_mouse.html#autotoc_md1368',1,'What You&apos;ll Learn'],['../examples_input_superscope.html#autotoc_md1391',1,'What You&apos;ll Learn'],['../examples_maps_dynamic_map.html#autotoc_md1445',1,'What You&apos;ll Learn'],['../examples_maps_map_scroll.html#autotoc_md1455',1,'What You&apos;ll Learn'],['../examples_maps_slope_collision.html#autotoc_md1465',1,'What You&apos;ll Learn'],['../examples_maps_tiled.html#autotoc_md1475',1,'What You&apos;ll Learn'],['../examples_scrolling_continuous_scroll.html#autotoc_md1581',1,'What You&apos;ll Learn'],['../examples_scrolling_mixed_scroll.html#autotoc_md1601',1,'What You&apos;ll Learn'],['../examples_sprites_dynamic_metasprite.html#autotoc_md1651',1,'What You&apos;ll Learn'],['../examples_sprites_metasprite.html#autotoc_md1669',1,'What You&apos;ll Learn']]],
  ['learn_42',['learn',['../examples_audio_echo.html#autotoc_md875',1,'What you&apos;ll learn'],['../examples_backgrounds_mode2.html#autotoc_md1038',1,'What you&apos;ll learn'],['../examples_basics_game_skeleton.html#autotoc_md1085',1,'What you&apos;ll learn'],['../examples_basics_panel_hud.html#autotoc_md1091',1,'What you&apos;ll learn'],['../examples_color_palette_cycle.html#autotoc_md1161',1,'What you&apos;ll learn'],['../examples_color_shadow_tint.html#autotoc_md1169',1,'What you&apos;ll learn'],['../examples_input_move_sprite.html#autotoc_md1382',1,'What you&apos;ll learn'],['../examples_sprites_sprite_swarm.html#autotoc_md1712',1,'What you&apos;ll learn'],['../examples_text_print_string.html#autotoc_md1717',1,'What you&apos;ll learn'],['../examples_text_scroll_message.html#autotoc_md1729',1,'What you&apos;ll learn']]],
  ['learn_20snes_20development_43',['Learn SNES Development',['../learning_path.html',1,'index']]],
  ['learning_20objectives_44',['Learning Objectives',['../examples_audio_snesmod_music.html#autotoc_md894',1,'Learning Objectives'],['../examples_backgrounds_mode1.html#autotoc_md972',1,'Learning Objectives'],['../examples_input_two_players.html#autotoc_md1403',1,'Learning Objectives'],['../examples_transitions_fading.html#autotoc_md1734',1,'Learning Objectives']]],
  ['learning_20path_45',['Learning Path',['../examples.html#autotoc_md1569',1,'']]],
  ['left_20right_20is_20an_20empty_20window_46',['&lt;span class=&quot;tt&quot;&gt;left &amp;gt; right&lt;/span&gt; is an &quot;empty&quot; window',['../tutorial_window.html#autotoc_md439',1,'']]],
  ['lessons_20this_20port_20surfaced_47',['Two integration lessons this port surfaced',['../examples_mode7_perspective_rotate.html#autotoc_md1547',1,'']]],
  ['let_20the_20lib_20close_20it_48',['🟡 A Raster stream cannot be &quot;resynced&quot; — let the lib close it',['../tutorial_dsp1.html#autotoc_md194',1,'']]],
  ['letters_20in_20hex_49',['2. Drawing Letters in Hex',['../examples_fundamentals_text_glyphs.html#autotoc_md1198',1,'']]],
  ['level_50',['Making Your Own Level',['../examples_maps_tiled.html#autotoc_md1484',1,'']]],
  ['level_51',['Two ways to hold a level',['../craft_tiles_to_levels.html#autotoc_md500',1,'']]],
  ['level_201_20ndash_20first_20steps_52',['Level 1 &amp;ndash; First Steps',['../examples.html#autotoc_md1570',1,'']]],
  ['level_202_20ndash_20graphics_20fundamentals_53',['Level 2 &amp;ndash; Graphics Fundamentals',['../examples.html#autotoc_md1571',1,'']]],
  ['level_203_20ndash_20scrolling_20and_20effects_54',['Level 3 &amp;ndash; Scrolling and Effects',['../examples.html#autotoc_md1572',1,'']]],
  ['level_204_20ndash_20advanced_20topics_55',['Level 4 &amp;ndash; Advanced Topics',['../examples.html#autotoc_md1573',1,'']]],
  ['level_205_20ndash_20maps_20and_20complete_20projects_56',['Level 5 &amp;ndash; Maps and Complete Projects',['../examples.html#autotoc_md1574',1,'']]],
  ['level_20emulators_57',['🟡 Firmware needed by low-level emulators',['../tutorial_dsp1.html#autotoc_md192',1,'']]],
  ['level_20in_20tiled_58',['Authoring the level in Tiled',['../tools_tmx2snes.html#autotoc_md540',1,'']]],
  ['level_20is_20bigger_20than_20vram_20—_20so_20stream_20it_59',['The level is bigger than VRAM — so stream it',['../craft_tiles_to_levels.html#autotoc_md498',1,'']]],
  ['level_20not_20just_20building_20it_60',['Designing the level, not just building it',['../craft_tiles_to_levels.html#autotoc_md501',1,'']]],
  ['levels_61',['Levels',['../examples_hdma_hdma_wave.html#autotoc_md1338',1,'3. Seven Amplitude Levels'],['../examples_games_breakout.html#autotoc_md1228',1,'8. Color Cycling Between Levels']]],
  ['levels_62',['From tiles to levels',['../craft_tiles_to_levels.html',1,'craft']]],
  ['levels_20of_20wiring_63',['Three levels of wiring',['../tools.html#autotoc_md531',1,'']]],
  ['levels_20to_20snes_20map_20data_64',['tmx2snes — Tiled levels to SNES map data',['../tools_tmx2snes.html',1,'tools']]],
  ['lib_20api_65',['lib API',['../tutorial_colormath.html#autotoc_md143',1,'The lib API'],['../tutorial_mosaic.html#autotoc_md325',1,'The lib API'],['../tutorial_sram.html#autotoc_md400',1,'The lib API'],['../tutorial_window.html#autotoc_md442',1,'The lib API']]],
  ['lib_20api_20tour_66',['Lib API tour',['../tutorial_dma.html#autotoc_md173',1,'']]],
  ['lib_20chantier_20b6_202026_2005_2009_67',['&lt;span class=&quot;tt&quot;&gt;atan2&lt;/span&gt; and &lt;span class=&quot;tt&quot;&gt;sqrt&lt;/span&gt; ship in the lib (chantier B6, 2026-05-09)',['../tutorial_math.html#autotoc_md296',1,'']]],
  ['lib_20close_20it_68',['🟡 A Raster stream cannot be &quot;resynced&quot; — let the lib close it',['../tutorial_dsp1.html#autotoc_md194',1,'']]],
  ['lib_20helpers_20and_20what_20they_20do_69',['The lib helpers and what they do',['../tutorial_mode7.html#autotoc_md306',1,'']]],
  ['library_20not_20built_70',['Build fails with &quot;Library not built&quot;',['../getting_started.html#autotoc_md571',1,'']]],
  ['licence_71',['Licence',['../examples_games_shmup_1942.html#autotoc_md1304',1,'']]],
  ['license_72',['License',['../index.html#autotoc_md12',1,'License'],['../examples_audio_snesmod_music.html#autotoc_md943',1,'License']]],
  ['life_20—_20palette_20cycling_73',['Ambient life — palette cycling',['../craft_game_feel.html#autotoc_md480',1,'']]],
  ['lights_20off_20load_20everything_74',['1. Lights Off, Load Everything',['../examples_games_breakout.html#autotoc_md1221',1,'']]],
  ['lights_20on_75',['7. Lights On',['../examples_fundamentals_text_glyphs.html#autotoc_md1203',1,'']]],
  ['likemario_76',['LikeMario',['../tutorial_animation.html#autotoc_md87',1,'Action-Based Animation (LikeMario)'],['../examples_games_likemario.html',1,'LikeMario']]],
  ['limitation_77',['Bank Byte Limitation',['../hdma_8h.html#autotoc_md34',1,'']]],
  ['limits_78',['SNES Sprite Limits',['../sprite_8h.html#autotoc_md59',1,'']]],
  ['limits_20critical_79',['Scanline Limits (Critical!)',['../snes_graphics_guide.html#autotoc_md653',1,'']]],
  ['line_80',['3. OAM — 128 sprites, but far fewer per line',['../craft_planning.html#autotoc_md487',1,'']]],
  ['line_20—_20examples_20mode7_20perspective_5frotate_81',['Full Mode 7 matrix per line — &lt;span class=&quot;tt&quot;&gt;examples/mode7/perspective_rotate&lt;/span&gt;',['../tutorial_hdma.html#autotoc_md239',1,'']]],
  ['line_20budget_3a_2032_82',['The sprite-per-line budget: 32',['../craft_frame_budget.html#autotoc_md472',1,'']]],
  ['lines_83',['5. Gravity in Two Lines',['../examples_games_likemario.html#autotoc_md1253',1,'']]],
  ['linker_20errors_20about_20size_84',['&quot;ROM too large&quot; or linker errors about size',['../troubleshooting.html#autotoc_md748',1,'']]],
  ['links_85',['Links',['../index.html#autotoc_md11',1,'Links'],['../contributing.html#autotoc_md1845',1,'Links']]],
  ['listening_20test_20driven_86',['The debugging archaeology (all owner-listening-test driven)',['../examples_audio_speech_synth.html#autotoc_md965',1,'']]],
  ['little_20things_87',['Layer the little things',['../craft_game_feel.html#autotoc_md482',1,'']]],
  ['lives_88',['Where the Data Lives',['../examples_hdma_hdma_wave.html#autotoc_md1349',1,'']]],
  ['ll_20learn_89',['ll Learn',['../examples_audio_snesmod_music_large.html#autotoc_md945',1,'What You&apos;ll Learn'],['../examples_audio_snesmod_sfx.html#autotoc_md950',1,'What You&apos;ll Learn'],['../examples_backgrounds_mode1_lz77.html#autotoc_md1022',1,'What You&apos;ll Learn'],['../examples_basics_collision_demo.html#autotoc_md1066',1,'What You&apos;ll Learn'],['../examples_basics_random.html#autotoc_md1096',1,'What You&apos;ll Learn'],['../examples_basics_scene_stack.html#autotoc_md1106',1,'What You&apos;ll Learn'],['../examples_basics_timer.html#autotoc_md1114',1,'What You&apos;ll Learn'],['../examples_chips_sa1_hello.html#autotoc_md1128',1,'What You&apos;ll Learn'],['../examples_chips_sa1_starfield.html#autotoc_md1132',1,'What You&apos;ll Learn'],['../examples_chips_superfx_3d.html#autotoc_md1137',1,'What You&apos;ll Learn'],['../examples_chips_superfx_hello.html#autotoc_md1143',1,'What You&apos;ll Learn'],['../examples_color_transparency.html#autotoc_md1176',1,'What You&apos;ll Learn'],['../examples_fundamentals_text_glyphs.html#autotoc_md1194',1,'What You&apos;ll Learn'],['../examples_games_breakout.html#autotoc_md1218',1,'What You&apos;ll Learn'],['../examples_games_likemario.html#autotoc_md1246',1,'What You&apos;ll Learn'],['../examples_games_mapandobjects.html#autotoc_md1270',1,'What You&apos;ll Learn'],['../examples_hdma_hdma_wave.html#autotoc_md1333',1,'What You&apos;ll Learn'],['../examples_input_controller.html#autotoc_md1360',1,'What You&apos;ll Learn'],['../examples_input_mouse.html#autotoc_md1368',1,'What You&apos;ll Learn'],['../examples_input_superscope.html#autotoc_md1391',1,'What You&apos;ll Learn'],['../examples_maps_dynamic_map.html#autotoc_md1445',1,'What You&apos;ll Learn'],['../examples_maps_map_scroll.html#autotoc_md1455',1,'What You&apos;ll Learn'],['../examples_maps_slope_collision.html#autotoc_md1465',1,'What You&apos;ll Learn'],['../examples_maps_tiled.html#autotoc_md1475',1,'What You&apos;ll Learn'],['../examples_scrolling_continuous_scroll.html#autotoc_md1581',1,'What You&apos;ll Learn'],['../examples_scrolling_mixed_scroll.html#autotoc_md1601',1,'What You&apos;ll Learn'],['../examples_sprites_dynamic_metasprite.html#autotoc_md1651',1,'What You&apos;ll Learn'],['../examples_sprites_metasprite.html#autotoc_md1669',1,'What You&apos;ll Learn']]],
  ['ll_20learn_90',['ll learn',['../examples_audio_echo.html#autotoc_md875',1,'What you&apos;ll learn'],['../examples_backgrounds_mode2.html#autotoc_md1038',1,'What you&apos;ll learn'],['../examples_basics_game_skeleton.html#autotoc_md1085',1,'What you&apos;ll learn'],['../examples_basics_panel_hud.html#autotoc_md1091',1,'What you&apos;ll learn'],['../examples_color_palette_cycle.html#autotoc_md1161',1,'What you&apos;ll learn'],['../examples_color_shadow_tint.html#autotoc_md1169',1,'What you&apos;ll learn'],['../examples_input_move_sprite.html#autotoc_md1382',1,'What you&apos;ll learn'],['../examples_sprites_sprite_swarm.html#autotoc_md1712',1,'What you&apos;ll learn'],['../examples_text_print_string.html#autotoc_md1717',1,'What you&apos;ll learn'],['../examples_text_scroll_message.html#autotoc_md1729',1,'What you&apos;ll learn']]],
  ['load_20both_20tilesets_20and_20palettes_91',['1. Load Both Tilesets and Palettes',['../examples_scrolling_mixed_scroll.html#autotoc_md1609',1,'']]],
  ['load_20cursor_20sprite_92',['2. Load Cursor Sprite',['../examples_input_mouse.html#autotoc_md1376',1,'']]],
  ['load_20everything_93',['1. Lights Off, Load Everything',['../examples_games_breakout.html#autotoc_md1221',1,'']]],
  ['load_20from_20sram_94',['3. Load from SRAM',['../examples_memory_save_game.html#autotoc_md1512',1,'']]],
  ['load_20objects_20from_20map_20data_95',['3. Load Objects from Map Data',['../examples_games_mapandobjects.html#autotoc_md1279',1,'']]],
  ['load_20palette_20and_20tilemap_20uncompressed_96',['3. Load Palette and Tilemap (Uncompressed)',['../examples_backgrounds_mode1_lz77.html#autotoc_md1031',1,'']]],
  ['load_20sprite_20graphics_20into_20vram_97',['1. Load sprite graphics into VRAM',['../examples_sprites_simple_sprite.html#autotoc_md1685',1,'']]],
  ['load_20sprites_20with_20force_20blank_98',['2. Load sprites with force blank',['../examples_sprites_sprite_sizes.html#autotoc_md1701',1,'']]],
  ['load_20the_20sprite_20palette_99',['2. Load the sprite palette',['../examples_sprites_simple_sprite.html#autotoc_md1686',1,'']]],
  ['load_20tilemaps_20to_20vram_100',['2. Load Tilemaps to VRAM',['../examples_scrolling_mixed_scroll.html#autotoc_md1610',1,'']]],
  ['load_20tiles_20and_20palettes_101',['2. Load tiles and palettes',['../examples_backgrounds_mode1_bg3_priority.html#autotoc_md1013',1,'']]],
  ['loader_102',['Assembly DMA Loader',['../examples_color_transparency.html#autotoc_md1182',1,'']]],
  ['loader_2065816_20asm_103',['3. Create the GSU Loader (65816 ASM)',['../tutorial_superfx.html#autotoc_md421',1,'']]],
  ['loading_20and_20playing_20effects_104',['Loading and Playing Effects',['../examples_audio_snesmod_sfx.html#autotoc_md954',1,'']]],
  ['loading_20sprite_20tiles_105',['Loading Sprite Tiles',['../tutorial_sprites.html#autotoc_md385',1,'']]],
  ['loading_20tiles_20to_20vram_106',['Loading Tiles to VRAM',['../tutorial_graphics.html#autotoc_md216',1,'']]],
  ['loads_20but_20screen_20is_20black_107',['ROM loads but screen is black',['../troubleshooting.html#autotoc_md738',1,'']]],
  ['locking_108',['Clamp to the world — room-locking',['../craft_camera.html#autotoc_md467',1,'']]],
  ['log_109',['What&apos;s still missing: &lt;span class=&quot;tt&quot;&gt;pow&lt;/span&gt;, &lt;span class=&quot;tt&quot;&gt;exp&lt;/span&gt;, &lt;span class=&quot;tt&quot;&gt;log&lt;/span&gt;',['../tutorial_math.html#autotoc_md297',1,'']]],
  ['logic_110',['Window Logic',['../window_8h.html#autotoc_md68',1,'']]],
  ['logic_20commands_111',['Distance and Range: the game-logic commands',['../tutorial_dsp1.html#autotoc_md190',1,'']]],
  ['logic_20op_20trap_112',['The window logic op trap',['../tutorial_window.html#autotoc_md441',1,'']]],
  ['long_20sizes_20are_20correct_20on_20this_20target_20since_20chantier_20a1_113',['🟢 &lt;span class=&quot;tt&quot;&gt;int&lt;/span&gt; and &lt;span class=&quot;tt&quot;&gt;long&lt;/span&gt; sizes are correct on this target (since chantier A1)',['../tutorial_math.html#autotoc_md289',1,'']]],
  ['long_20way_114',['Manual setup (the long way)',['../getting_started.html#autotoc_md556',1,'']]],
  ['look_20ahead_115',['Lead the action — look-ahead',['../craft_camera.html#autotoc_md465',1,'']]],
  ['lookup_20tables_116',['Trigonometry (sin/cos lookup tables)',['../tutorial_math.html#autotoc_md280',1,'']]],
  ['lookups_20with_20lda_20l_20table_20x_117',['ROM Table Lookups with &lt;span class=&quot;tt&quot;&gt;lda.l table,x&lt;/span&gt;',['../tutorial_sa1.html#autotoc_md357',1,'']]],
  ['loop_118',['Loop',['../examples_backgrounds_mode1_lz77.html#autotoc_md1033',1,'5. Idle Loop'],['../examples_games_likemario.html#autotoc_md1255',1,'7. The Main Loop'],['../examples_games_breakout.html#autotoc_md1229',1,'9. The Game Loop'],['../examples_scrolling_parallax_scroll.html#autotoc_md1622',1,'Animation Loop'],['../examples_color_transparency.html#autotoc_md1186',1,'Main Loop'],['../tutorial_animation.html#autotoc_md86',1,'The Game Loop']]],
  ['loop_119',['Per-frame DMA in the main loop',['../tutorial_dma.html#autotoc_md172',1,'']]],
  ['loop_20critical_120',['Main Loop (CRITICAL!)',['../examples_audio_snesmod_music.html#autotoc_md906',1,'']]],
  ['loop_20over_20100_20bricks_121',['5. Grid Collision (Don&apos;t Loop Over 100 Bricks)',['../examples_games_breakout.html#autotoc_md1225',1,'']]],
  ['loop_3a_20read_20mouse_20update_20cursor_122',['4. Main Loop: Read Mouse, Update Cursor',['../examples_input_mouse.html#autotoc_md1378',1,'']]],
  ['loop_3a_20update_20draw_20sync_123',['4. Main Loop: Update, Draw, Sync',['../examples_games_mapandobjects.html#autotoc_md1280',1,'']]],
  ['loops_124',['Loops',['../tutorial_superfx.html#autotoc_md427',1,'3. RPIX After PLOT Loops'],['../tutorial_superfx.html#autotoc_md428',1,'4. CACHE Before Hot Loops']]],
  ['lorom_125',['LoROM',['../examples_memory_hirom_demo.html#autotoc_md1491',1,'2. The code is identical to LoROM'],['../sram_8h.html#autotoc_md63',1,'Memory Layout (LoROM)']]],
  ['lorom_20memory_20map_20default_126',['LoROM Memory Map (Default)',['../memory_map.html#autotoc_md766',1,'']]],
  ['lorom_20vs_20hirom_127',['LoROM vs HiROM',['../hardware_overview.html#autotoc_md809',1,'LoROM vs HiROM'],['../examples_memory_hirom_demo.html#autotoc_md1495',1,'LoROM vs HiROM'],['../examples_memory.html#autotoc_md1502',1,'LoROM vs HiROM']]],
  ['low_20level_20emulators_128',['🟡 Firmware needed by low-level emulators',['../tutorial_dsp1.html#autotoc_md192',1,'']]],
  ['luna_129',['luna',['../tutorial_debugging.html',1,'Interactive Debugging with luna'],['../troubleshooting.html#autotoc_md752',1,'Interactive debugging with luna']]],
  ['luna_20s_20spc_20dump_130',['Debugging audio: luna&apos;s spc-dump',['../tutorial_audio.html#autotoc_md116',1,'']]],
  ['luna_20v1_209_200_131',['luna v1 9 0',['../examples_mode7_perspective_rotate.html#autotoc_md1546',1,'Measured parity (luna v1.9.0)'],['../examples_backgrounds_mode5_hires.html#autotoc_md1054',1,'Validation notes (luna v1.9.0)']]],
  ['luna_20v1_209_200_20mesen2_20cross_20check_132',['Measured parity (luna v1.9.0 + Mesen2 cross-check)',['../examples_color_hicolor_1792.html#autotoc_md1155',1,'']]],
  ['luts_20are_20unsigned_20angle_20signed_20result_133',['🟡 Sin/cos LUTs are unsigned-angle, signed-result',['../tutorial_math.html#autotoc_md295',1,'']]],
  ['lz77_134',['Mode 1 LZ77',['../examples_backgrounds_mode1_lz77.html',1,'examples_backgrounds']]],
  ['lz77_20format_135',['LZ77 Format',['../lzss_8h.html#autotoc_md40',1,'']]],
  ['lz77_20lzss_20compression_136',['LZ77 / LZSS Compression',['../examples_backgrounds_mode1_lz77.html#autotoc_md1024',1,'']]],
  ['lzss_20compression_137',['LZ77 / LZSS Compression',['../examples_backgrounds_mode1_lz77.html#autotoc_md1024',1,'']]]
];
