var searchData=
[
  ['c_0',['C',['../tutorial_sa1.html#autotoc_md334',1,'3. Initialize from C'],['../tutorial_superfx.html#autotoc_md406',1,'4. Launch from C'],['../examples_audio_soundboard.html',1,'soundboard — the audio v2 engine, driven entirely from C'],['../tutorial_audio.html#autotoc_md113',1,'The audio module (v2) — samples and effects from pure C']]],
  ['c_1',['Source (.c)',['../code_style.html#autotoc_md619',1,'']]],
  ['c_20code_2',['C Code',['../code_style.html#autotoc_md605',1,'']]],
  ['cache_20before_20hot_20loops_3',['4. CACHE Before Hot Loops',['../tutorial_superfx.html#autotoc_md412',1,'']]],
  ['calculation_4',['Pitch Calculation',['../snes_sound_guide.html#autotoc_md711',1,'']]],
  ['calculation_5',['4. Tile calculation',['../examples_sprites_animated_sprite.html#autotoc_md1616',1,'']]],
  ['calibration_20background_20bg2_6',['3. Calibration Background (BG2)',['../examples_input_superscope.html#autotoc_md1379',1,'']]],
  ['call_20snesmodprocess_7',['Important: Call snesmodProcess()!',['../tutorial_audio.html#autotoc_md107',1,'']]],
  ['callback_20in_20the_20nmi_20handler_8',['🟡 HDMA fires before the user callback in the NMI handler',['../tutorial_hdma.html#autotoc_md233',1,'']]],
  ['camera_9',['Following the player: the camera',['../craft_camera.html',1,'craft']]],
  ['camera_20is_20your_20scroll_20values_10',['The camera &lt;em&gt;is&lt;/em&gt; your scroll values',['../craft_camera.html#autotoc_md447',1,'']]],
  ['camera_20relative_20sprite_20positioning_11',['Camera-Relative Sprite Positioning',['../examples_maps_map_scroll.html#autotoc_md1443',1,'']]],
  ['camera_20to_20the_20player_20—_20deadzone_20it_12',['Don&apos;t glue the camera to the player — deadzone it',['../craft_camera.html#autotoc_md448',1,'']]],
  ['camps_13',['Why two camps?',['../oam.html#autotoc_md778',1,'']]],
  ['can_20finish_14',['Scope a first game you can finish',['../craft_planning.html#autotoc_md474',1,'']]],
  ['can_20give_15',['When you need more than layers can give',['../craft_backgrounds.html#autotoc_md445',1,'']]],
  ['can_20i_20build_20a_20world_16',['Stage 3 — &quot;Can I build a world?&quot;',['../learning_path.html#autotoc_md563',1,'']]],
  ['can_20i_20finish_20and_20ship_17',['Stage 6 — &quot;Can I finish and ship?&quot;',['../learning_path.html#autotoc_md566',1,'']]],
  ['can_20i_20hold_20it_20all_20together_18',['Stage 5 — &quot;Can I hold it all together?&quot;',['../learning_path.html#autotoc_md565',1,'']]],
  ['can_20i_20make_20it_20feel_20good_19',['Stage 4 — &quot;Can I make it feel good?&quot;',['../learning_path.html#autotoc_md564',1,'']]],
  ['can_20i_20put_20something_20on_20screen_20',['Stage 1 — &quot;Can I put something on screen?&quot;',['../learning_path.html#autotoc_md561',1,'']]],
  ['can_20t_20do_21',['What SA-1 Can&apos;t Do',['../tutorial_sa1.html#autotoc_md346',1,'']]],
  ['can_20the_20player_20act_22',['Stage 2 — &quot;Can the player act?&quot;',['../learning_path.html#autotoc_md562',1,'']]],
  ['cannot_20store_20pointers_20in_20sram_23',['🟠 Cannot store pointers in SRAM',['../tutorial_sram.html#autotoc_md394',1,'']]],
  ['capabilities_24',['Key Capabilities',['../snes_sound_guide.html#autotoc_md668',1,'']]],
  ['capstones_25',['Games (capstones)',['../examples_by_category.html#autotoc_md604',1,'']]],
  ['carries_20meaning_20not_20just_20pixels_26',['A tile carries meaning, not just pixels',['../craft_tiles_to_levels.html#autotoc_md481',1,'']]],
  ['cartridge_27',['Cartridge',['../memory_map.html#autotoc_md761',1,'SA-1 Cartridge'],['../memory_map.html#autotoc_md762',1,'SuperFX Cartridge']]],
  ['cartridge_20coprocessors_28',['More horsepower — the cartridge coprocessors',['../learning_path.html#autotoc_md567',1,'']]],
  ['categories_29',['Categories',['../examples.html#autotoc_md1545',1,'']]],
  ['category_30',['Browse Examples by Category',['../examples_by_category.html',1,'index']]],
  ['cc0_20public_20domain_31',['Free Asset Sources (CC0/Public Domain)',['../snes_graphics_guide.html#autotoc_md659',1,'']]],
  ['cc65816_20not_20found_32',['Empty &lt;span class=&quot;tt&quot;&gt;compiler/&lt;/span&gt; directories or &quot;cc65816 not found&quot;',['../troubleshooting.html#autotoc_md716',1,'']]],
  ['cc_3a_20command_20not_20found_33',['&quot;clang: command not found&quot; or &quot;cc: command not found&quot;',['../troubleshooting.html#autotoc_md718',1,'']]],
  ['ceiling_34',['sprite_swarm — a bouncing swarm, and the OAM throughput ceiling',['../examples_sprites_sprite_swarm.html',1,'examples_sprites']]],
  ['centre_35',['🟡 Centre default is the tilemap centre, not the screen centre',['../tutorial_mode7.html#autotoc_md301',1,'']]],
  ['centre_20default_20is_20the_20tilemap_20centre_20not_20the_20screen_20centre_36',['🟡 Centre default is the tilemap centre, not the screen centre',['../tutorial_mode7.html#autotoc_md301',1,'']]],
  ['centre_20not_20the_20screen_20centre_37',['🟡 Centre default is the tilemap centre, not the screen centre',['../tutorial_mode7.html#autotoc_md301',1,'']]],
  ['cgadd_20_242121_38',['1. HDMA targets CGADD ($2121)',['../examples_hdma_gradient_colors.html#autotoc_md1298',1,'']]],
  ['cgadd_20cgram_20address_39',['$2121 - CGADD (CGRAM Address)',['../registers.html#autotoc_md817',1,'']]],
  ['cgdata_20cgram_20data_20write_40',['$2122 - CGDATA (CGRAM Data Write)',['../registers.html#autotoc_md818',1,'']]],
  ['cgram_41',['CGRAM',['../registers.html#autotoc_md816',1,'Color (CGRAM)'],['../examples_color_palette_cycle.html',1,'palette_cycle — animate by rotating CGRAM']]],
  ['cgram_20—_20256_20colours_20split_20bg_20vs_20sprites_42',['2. CGRAM — 256 colours, split BG vs sprites',['../craft_planning.html#autotoc_md470',1,'']]],
  ['cgram_20address_43',['$2121 - CGADD (CGRAM Address)',['../registers.html#autotoc_md817',1,'']]],
  ['cgram_20color_20generator_20ram_44',['CGRAM (Color Generator RAM)',['../examples_hdma_gradient_colors.html#autotoc_md1302',1,'']]],
  ['cgram_20color_20ram_45',['CGRAM (Color RAM)',['../memory_map.html#autotoc_md755',1,'']]],
  ['cgram_20data_20write_46',['$2122 - CGDATA (CGRAM Data Write)',['../registers.html#autotoc_md818',1,'']]],
  ['cgram_20layout_20256_20colors_20×_202_20bytes_47',['CGRAM Layout (256 colors × 2 bytes)',['../snes_graphics_guide.html#autotoc_md649',1,'']]],
  ['cgram_20oam_20writes_20are_20safe_48',['When VRAM/CGRAM/OAM writes are safe',['../tutorial_dma.html#autotoc_md170',1,'']]],
  ['cgram_20oam_20writes_20outside_20vblank_20or_20force_20blank_20are_20silently_20dropped_49',['🔴 VRAM/CGRAM/OAM writes outside VBlank or force blank are silently dropped',['../tutorial_dma.html#autotoc_md175',1,'']]],
  ['cgram_20split_50',['CGRAM Split',['../examples_sprites_simple_sprite.html#autotoc_md1669',1,'']]],
  ['change_20palette_51',['Exercise 2: Change Palette',['../examples_backgrounds_mode1.html#autotoc_md982',1,'']]],
  ['changes_52',['Input and State Changes',['../tutorial_animation.html#autotoc_md80',1,'']]],
  ['changes_20—_20fades_20and_20dissolves_53',['Punctuate scene changes — fades and dissolves',['../craft_game_feel.html#autotoc_md463',1,'']]],
  ['changing_20frame_20ids_54',['4. Animate by changing frame IDs',['../examples_sprites_dynamic_sprite.html#autotoc_md1639',1,'']]],
  ['channel_55',['4. Setting Up the HDMA Channel',['../examples_hdma_hdma_wave.html#autotoc_md1323',1,'']]],
  ['channel_200_56',['🟠 Channel 0 vs HDMA on channel 0',['../tutorial_dma.html#autotoc_md178',1,'']]],
  ['channel_200_20vs_20hdma_20on_20channel_200_57',['🟠 Channel 0 vs HDMA on channel 0',['../tutorial_dma.html#autotoc_md178',1,'']]],
  ['channel_207_20is_20reserved_20for_20oam_20dma_58',['🔴 Channel 7 is reserved for OAM DMA',['../tutorial_hdma.html#autotoc_md230',1,'']]],
  ['channel_20configuration_59',['Channel Configuration',['../registers.html#autotoc_md838',1,'']]],
  ['channel_20registers_60',['The four channel registers',['../tutorial_hdma.html#autotoc_md213',1,'']]],
  ['channel_20split_20blend_61',['&quot;3840 colors&quot; — RGB channel-split blend',['../examples_color_hicolor_blend.html',1,'examples_color']]],
  ['channels_62',['The DMA channels',['../tutorial_dma.html#autotoc_md167',1,'']]],
  ['channels_20one_20visual_20—_20examples_20color_20gradient_5f9bit_63',['Two channels, one visual — &lt;span class=&quot;tt&quot;&gt;examples/color/gradient_9bit&lt;/span&gt;',['../tutorial_hdma.html#autotoc_md227',1,'']]],
  ['channels_20you_20haven_20t_20configured_64',['🟡 Don&apos;t enable channels you haven&apos;t configured',['../tutorial_hdma.html#autotoc_md234',1,'']]],
  ['chantier_20—_20s6_20hud_20on_20bg3_65',['Open chantier — S6 HUD on BG3',['../examples_games_shmup_1942.html#autotoc_md1283',1,'']]],
  ['chantier_20a1_66',['🟢 &lt;span class=&quot;tt&quot;&gt;int&lt;/span&gt; and &lt;span class=&quot;tt&quot;&gt;long&lt;/span&gt; sizes are correct on this target (since chantier A1)',['../tutorial_math.html#autotoc_md275',1,'']]],
  ['chantier_20b6_202026_2005_2009_67',['&lt;span class=&quot;tt&quot;&gt;atan2&lt;/span&gt; and &lt;span class=&quot;tt&quot;&gt;sqrt&lt;/span&gt; ship in the lib (chantier B6, 2026-05-09)',['../tutorial_math.html#autotoc_md282',1,'']]],
  ['cheaply_68',['The HUD — always on top, cheaply',['../craft_backgrounds.html#autotoc_md443',1,'']]],
  ['cheat_20sheet_69',['Register Cheat Sheet',['../snes_graphics_guide.html#autotoc_md663',1,'']]],
  ['check_70',['Measured parity (luna v1.9.0 + Mesen2 cross-check)',['../examples_color_hicolor_1792.html#autotoc_md1139',1,'']]],
  ['checkerboard_20background_71',['6. The Checkerboard Background',['../examples_hdma_hdma_wave.html#autotoc_md1325',1,'']]],
  ['checking_20all_20four_20corners_72',['Checking All Four Corners',['../tutorial_collision.html#autotoc_md125',1,'']]],
  ['checklist_73',['Self-review checklist',['../contributing.html#autotoc_md1816',1,'']]],
  ['checklist_20before_20you_20write_20code_74',['Checklist before you write code',['../craft_planning.html#autotoc_md475',1,'']]],
  ['checksum_20validation_75',['Checksum Validation',['../examples_memory_save_game.html#autotoc_md1502',1,'']]],
  ['chip_20memory_76',['Enhancement Chip Memory',['../memory_map.html#autotoc_md760',1,'']]],
  ['chip_20tutorial_77',['SA-1 Enhancement Chip Tutorial',['../tutorial_sa1.html',1,'index']]],
  ['chips_78',['chips',['../examples_chips.html',1,'Enhancement chips'],['../examples_by_category.html#autotoc_md599',1,'Enhancement chips']]],
  ['chips_20in_20one_20screen_79',['The two chips, in one screen',['../examples_chips.html#autotoc_md1110',1,'']]],
  ['choose_20a_20background_20mode_20from_20your_20genre_80',['Choose a background mode from your genre',['../craft_planning.html#autotoc_md472',1,'']]],
  ['choose_20your_20path_81',['Choose Your Path',['../getting_started.html#autotoc_md532',1,'']]],
  ['cite_82',['The hardware references we cite',['../craft.html#autotoc_md479',1,'']]],
  ['clamp_20to_20the_20world_20—_20room_20locking_83',['Clamp to the world — room-locking',['../craft_camera.html#autotoc_md451',1,'']]],
  ['clang_3a_20command_20not_20found_20or_20cc_3a_20command_20not_20found_84',['&quot;clang: command not found&quot; or &quot;cc: command not found&quot;',['../troubleshooting.html#autotoc_md718',1,'']]],
  ['claude_85',['Project knowledge in &lt;span class=&quot;tt&quot;&gt;.claude/&lt;/span&gt;',['../contributing.html#autotoc_md1819',1,'']]],
  ['clip_20and_20ticking_86',['Selecting the Clip and Ticking',['../tutorial_animation.html#autotoc_md81',1,'']]],
  ['clone_20and_20build_87',['B2. Clone and Build',['../getting_started.html#autotoc_md546',1,'']]],
  ['cloud_20overlay_20—_20examples_20color_20transparency_88',['Additive cloud overlay — &lt;span class=&quot;tt&quot;&gt;examples/color/transparency&lt;/span&gt;',['../tutorial_colormath.html#autotoc_md145',1,'']]],
  ['code_89',['Code',['../tutorial_superfx.html#autotoc_md404',1,'2. Write GSU Assembly Code'],['../tutorial_sa1.html#autotoc_md333',1,'2. Write Your SA-1 Boot Code'],['../code_style.html#autotoc_md605',1,'C Code'],['../example_sources.html',1,'Example Source Code'],['../index.html#autotoc_md6',1,'Examples (Annotated Source Code)'],['../contributing.html#autotoc_md1807',1,'Submitting Code']]],
  ['code_90',['code',['../tutorial_sram.html#autotoc_md392',1,'🔴 &lt;span class=&quot;tt&quot;&gt;SRAM_SIZE&lt;/span&gt; mismatch between Makefile and code'],['../craft_planning.html#autotoc_md475',1,'Checklist before you write code']]],
  ['code_20is_20identical_20to_20lorom_91',['2. The code is identical to LoROM',['../examples_memory_hirom_demo.html#autotoc_md1475',1,'']]],
  ['code_20of_20conduct_92',['Code of Conduct',['../contributing.html#autotoc_md1804',1,'']]],
  ['code_20review_93',['Code Review',['../contributing.html#autotoc_md1817',1,'']]],
  ['code_20style_20guide_94',['OpenSNES Code Style Guide',['../code_style.html',1,'index']]],
  ['code_20type_95',['Code Type',['../examples_audio_snesmod_music.html#autotoc_md883',1,'Code Type'],['../examples_backgrounds_mode1.html#autotoc_md961',1,'Code Type'],['../examples_input_two_players.html#autotoc_md1392',1,'Code Type'],['../examples_transitions_fading.html#autotoc_md1716',1,'Code Type']]],
  ['codes_96',['Codes',['../examples_chips_sa1_hello.html#autotoc_md1113',1,'Status Codes'],['../examples_chips_superfx_hello.html#autotoc_md1128',1,'Status Codes']]],
  ['coef_200f_207f_97',['FIR Filter Coefficients (COEF 0F-7F)',['../snes_sound_guide.html#autotoc_md693',1,'']]],
  ['coefficients_20coef_200f_207f_98',['FIR Filter Coefficients (COEF 0F-7F)',['../snes_sound_guide.html#autotoc_md693',1,'']]],
  ['collides_99',['Where the sprite is vs where it collides',['../tutorial_collision.html#autotoc_md128',1,'']]],
  ['collision_100',['Collision',['../examples_games_likemario.html#autotoc_md1238',1,'6. Tile-Based Collision'],['../examples_input_two_players.html#autotoc_md1417',1,'Exercise 1: Player Collision'],['../examples_games_mapandobjects.html#autotoc_md1256',1,'Map Engine and Tile Collision'],['../examples_maps_slope_collision.html#autotoc_md1452',1,'Object Engine and Slope Collision'],['../tutorial_collision.html#autotoc_md123',1,'Sprite-to-Background Collision'],['../tutorial_collision.html#autotoc_md119',1,'Sprite-to-Sprite Collision'],['../examples_basics_collision_demo.html#autotoc_md1054',1,'Tile-Based Wall Collision']]],
  ['collision_20against_20the_20map_101',['Collision against the map',['../tutorial_map.html#autotoc_md254',1,'']]],
  ['collision_20breakout_20bricks_102',['Grid-Based Collision (Breakout Bricks)',['../tutorial_collision.html#autotoc_md134',1,'']]],
  ['collision_20detection_20demo_103',['Collision Detection Demo',['../examples_basics_collision_demo.html',1,'examples_basics']]],
  ['collision_20detection_20tutorial_104',['Collision Detection Tutorial',['../tutorial_collision.html',1,'index']]],
  ['collision_20don_20t_20loop_20over_20100_20bricks_105',['5. Grid Collision (Don&apos;t Loop Over 100 Bricks)',['../examples_games_breakout.html#autotoc_md1209',1,'']]],
  ['collision_20map_20layout_106',['Collision Map Layout',['../examples_basics_collision_demo.html#autotoc_md1057',1,'']]],
  ['collision_20response_20patterns_107',['Collision Response Patterns',['../tutorial_collision.html#autotoc_md129',1,'']]],
  ['collision_20with_20rect_20pointers_108',['AABB Collision with Rect Pointers',['../examples_basics_collision_demo.html#autotoc_md1053',1,'']]],
  ['color_109',['direct_color — the pixel byte IS the color',['../examples_color_direct_color.html',1,'examples_color']]],
  ['color_20addition_20transparency_110',['Color Addition Transparency',['../examples_color_transparency.html',1,'examples_color']]],
  ['color_20background_111',['Mode 3 — 256-Color Background',['../examples_backgrounds_mode3.html',1,'examples_backgrounds']]],
  ['color_20cgram_112',['Color (CGRAM)',['../registers.html#autotoc_md816',1,'']]],
  ['color_20cycling_20between_20levels_113',['8. Color Cycling Between Levels',['../examples_games_breakout.html#autotoc_md1212',1,'']]],
  ['color_20fade_114',['Exercise 3: Color Fade',['../examples_transitions_fading.html#autotoc_md1736',1,'']]],
  ['color_20format_2015_20bit_20bgr_115',['Color Format (15-bit BGR)',['../snes_graphics_guide.html#autotoc_md650',1,'']]],
  ['color_20generator_20ram_116',['CGRAM (Color Generator RAM)',['../examples_hdma_gradient_colors.html#autotoc_md1302',1,'']]],
  ['color_20gradient_5f9bit_117',['Two channels, one visual — &lt;span class=&quot;tt&quot;&gt;examples/color/gradient_9bit&lt;/span&gt;',['../tutorial_hdma.html#autotoc_md227',1,'']]],
  ['color_20gradients_118',['Gradient Colors -- HDMA Color Gradients',['../examples_hdma_gradient_colors.html',1,'examples_hdma']]],
  ['color_20math_20configuration_119',['Color Math Configuration',['../examples_color_transparency.html#autotoc_md1165',1,'Color Math Configuration'],['../examples_windows_transparent_window.html#autotoc_md1769',1,'Color Math Configuration']]],
  ['color_20math_20hdma_120',['Transparent Window -- Color Math + HDMA',['../examples_windows_transparent_window.html',1,'examples_windows']]],
  ['color_20math_20not_20for_20bg_20masking_121',['Window for Color Math (Not for BG Masking)',['../examples_windows_transparent_window.html#autotoc_md1767',1,'']]],
  ['color_20math_20not_20palette_20edits_122',['Hit flash — color math, not palette edits',['../craft_game_feel.html#autotoc_md461',1,'']]],
  ['color_20math_20window_20vs_20bg_20window_123',['Color Math Window vs BG Window',['../examples_windows_transparent_window.html#autotoc_md1771',1,'']]],
  ['color_20math_20works_124',['How Color Math Works',['../colormath_8h.html#autotoc_md18',1,'']]],
  ['color_20math_3a_20main_20screen_20sub_20screen_125',['Color Math: Main Screen + Sub Screen',['../examples_color_transparency.html#autotoc_md1163',1,'']]],
  ['color_20palette_126',['Color Palette',['../examples_mode7_rotate_scale.html#autotoc_md1541',1,'256-Color Palette'],['../examples_backgrounds_mode1.html#autotoc_md989',1,'Color Palette']]],
  ['color_20ram_127',['CGRAM (Color RAM)',['../memory_map.html#autotoc_md755',1,'']]],
  ['color_20transparency_128',['Additive cloud overlay — &lt;span class=&quot;tt&quot;&gt;examples/color/transparency&lt;/span&gt;',['../tutorial_colormath.html#autotoc_md145',1,'']]],
  ['colormathsetsource_20polarity_20is_20opposite_20of_20intuitive_129',['🟠 &lt;span class=&quot;tt&quot;&gt;colorMathSetSource&lt;/span&gt; polarity is opposite of intuitive',['../tutorial_colormath.html#autotoc_md149',1,'']]],
  ['colors_130',['Colors',['../hardware_overview.html#autotoc_md787',1,'']]],
  ['colors_20×_202_20bytes_131',['CGRAM Layout (256 colors × 2 bytes)',['../snes_graphics_guide.html#autotoc_md649',1,'']]],
  ['colors_20—_20rgb_20channel_20split_20blend_132',['&quot;3840 colors&quot; — RGB channel-split blend',['../examples_color_hicolor_blend.html',1,'examples_color']]],
  ['colors_20four_20bytes_133',['5. Two Colors, Four Bytes',['../examples_fundamentals_text_glyphs.html#autotoc_md1185',1,'']]],
  ['colors_20from_20a_204bpp_20background_134',['HiColor — 1792 colors from a 4bpp background',['../examples_color_hicolor_1792.html',1,'examples_color']]],
  ['colors_20garbled_20palette_135',['Wrong colors / garbled palette',['../troubleshooting.html#autotoc_md728',1,'']]],
  ['colors_20hdma_20color_20gradients_136',['Gradient Colors -- HDMA Color Gradients',['../examples_hdma_gradient_colors.html',1,'examples_hdma']]],
  ['colour_137',['Colour',['../examples_color.html',1,'Colour'],['../examples_by_category.html#autotoc_md583',1,'Colour']]],
  ['colour_20gradient_20—_20examples_20hdma_20gradient_5fcolors_138',['Static colour gradient — &lt;span class=&quot;tt&quot;&gt;examples/hdma/gradient_colors&lt;/span&gt;',['../tutorial_hdma.html#autotoc_md220',1,'']]],
  ['colour_20math_139',['colour math',['../tutorial_window.html#autotoc_md432',1,'🟠 &lt;span class=&quot;tt&quot;&gt;windowEnable(window, WINDOW_MATH)&lt;/span&gt; is the gate to colour math'],['../tutorial_colormath.html#autotoc_md140',1,'The minimum viable colour math']]],
  ['colour_20math_20—_20examples_20windows_20transparent_5fwindow_140',['Window + colour math — &lt;span class=&quot;tt&quot;&gt;examples/windows/transparent_window&lt;/span&gt;',['../tutorial_window.html#autotoc_md429',1,'']]],
  ['colour_20math_20actually_20is_141',['What colour math actually is',['../tutorial_colormath.html#autotoc_md138',1,'']]],
  ['colour_20math_20on_20the_20backdrop_142',['🟡 Colour-math on the backdrop',['../tutorial_colormath.html#autotoc_md151',1,'']]],
  ['colour_20math_20runs_20after_20windowing_143',['🟡 Colour math runs after windowing',['../tutorial_colormath.html#autotoc_md152',1,'']]],
  ['colour_20math_20tutorial_144',['Colour Math Tutorial',['../tutorial_colormath.html',1,'index']]],
  ['colours_20split_20bg_20vs_20sprites_145',['2. CGRAM — 256 colours, split BG vs sprites',['../craft_planning.html#autotoc_md470',1,'']]],
  ['column_20major_20tile_20layout_146',['Column-Major Tile Layout',['../tutorial_superfx.html#autotoc_md415',1,'']]],
  ['column_20pipeline_147',['3. Streaming: The Column Pipeline',['../examples_games_likemario.html#autotoc_md1235',1,'']]],
  ['column_20scroll_20from_20bg3_148',['mode2 — offset-per-tile: per-column scroll from BG3',['../examples_backgrounds_mode2.html',1,'examples_backgrounds']]],
  ['combinations_149',['Button Combinations',['../tutorial_input.html#autotoc_md245',1,'']]],
  ['combining_20both_20for_20transitions_150',['3. Combining both for transitions',['../examples_transitions_mosaic.html#autotoc_md1752',1,'']]],
  ['comes_20out_151',['comes out',['../tools_font2snes.html#autotoc_md491',1,'What goes in, what comes out'],['../tools_gfx4snes.html#autotoc_md496',1,'What goes in, what comes out'],['../tools_img2snes.html#autotoc_md502',1,'What goes in, what comes out'],['../tools_palplan.html#autotoc_md507',1,'What goes in, what comes out'],['../tools_smconv.html#autotoc_md517',1,'What goes in, what comes out'],['../tools_tmx2snes.html#autotoc_md522',1,'What goes in, what comes out'],['../tools_wav2brr.html#autotoc_md527',1,'What goes in, what comes out']]],
  ['command_20not_20found_152',['command not found',['../troubleshooting.html#autotoc_md718',1,'&quot;clang: command not found&quot; or &quot;cc: command not found&quot;'],['../troubleshooting.html#autotoc_md717',1,'&quot;wla-65816: command not found&quot;']]],
  ['command_20not_20found_20or_20cc_3a_20command_20not_20found_153',['&quot;clang: command not found&quot; or &quot;cc: command not found&quot;',['../troubleshooting.html#autotoc_md718',1,'']]],
  ['command_20not_20found_3a_20make_154',['&quot;command not found: make&quot;',['../getting_started.html#autotoc_md553',1,'']]],
  ['commands_155',['Diagnostic Commands',['../troubleshooting.html#autotoc_md735',1,'']]],
  ['commercial_20games_156',['Window Shapes in Commercial Games',['../examples_windows_window.html#autotoc_md1785',1,'']]],
  ['commit_20messages_157',['Commit messages',['../contributing.html#autotoc_md1814',1,'']]],
  ['common_20issues_158',['Common Issues',['../examples_audio_snesmod_music.html#autotoc_md913',1,'']]],
  ['common_20mk_159',['&quot;OPENSNES not defined&quot; or &quot;No rule to make target &apos;common.mk&apos;&quot;',['../troubleshooting.html#autotoc_md715',1,'']]],
  ['common_20operations_160',['Common Operations',['../snes_sound_guide.html#autotoc_md712',1,'']]],
  ['common_20pitfalls_161',['Common Pitfalls',['../oam.html#autotoc_md781',1,'']]],
  ['communication_162',['Runtime Communication',['../snes_sound_guide.html#autotoc_md697',1,'']]],
  ['communication_20patterns_163',['Communication Patterns',['../tutorial_sa1.html#autotoc_md335',1,'']]],
  ['communication_20ports_164',['Communication Ports',['../snes_sound_guide.html#autotoc_md673',1,'']]],
  ['communication_20protocol_165',['Communication Protocol',['../snes_sound_guide.html#autotoc_md695',1,'']]],
  ['compatibility_166',['Compatibility',['../tutorial_superfx.html#autotoc_md401',1,'Emulator Compatibility'],['../examples_chips_superfx_3d.html#autotoc_md1119',1,'Emulator Compatibility'],['../examples_chips_superfx_hello.html#autotoc_md1125',1,'Emulator Compatibility'],['../snes_graphics_guide.html#autotoc_md654',1,'For SNES Compatibility']]],
  ['compiler_20directories_20or_20cc65816_20not_20found_167',['Empty &lt;span class=&quot;tt&quot;&gt;compiler/&lt;/span&gt; directories or &quot;cc65816 not found&quot;',['../troubleshooting.html#autotoc_md716',1,'']]],
  ['compiler_20folder_168',['&quot;fatal: repository not found&quot; or empty compiler folder',['../getting_started.html#autotoc_md554',1,'']]],
  ['compiler_20vs_20mul16_169',['🟠 Compiler &lt;span class=&quot;tt&quot;&gt;*&lt;/span&gt; vs &lt;span class=&quot;tt&quot;&gt;mul16&lt;/span&gt;',['../tutorial_math.html#autotoc_md279',1,'']]],
  ['complete_20background_20setup_170',['Example: Complete Background Setup',['../tutorial_graphics.html#autotoc_md209',1,'']]],
  ['complete_20example_171',['Complete Example',['../oam.html#autotoc_md780',1,'']]],
  ['complete_20examples_172',['Complete Examples',['../tutorial_collision.html#autotoc_md136',1,'']]],
  ['complete_20game_173',['game_skeleton — the smallest complete game',['../examples_basics_game_skeleton.html',1,'examples_basics']]],
  ['complete_20game_20examples_174',['Complete Game Examples',['../examples_games.html',1,'examples']]],
  ['complete_20projects_175',['Level 5 &amp;ndash; Maps and Complete Projects',['../examples.html#autotoc_md1551',1,'']]],
  ['complete_20title_20flow_176',['Complete Title Flow',['../tutorial_game_states.html#autotoc_md191',1,'']]],
  ['components_177',['Third-Party Components',['../third_party.html',1,'index']]],
  ['composing_20with_20backgrounds_20layers_178',['Composing with backgrounds &amp;amp; layers',['../craft_backgrounds.html',1,'craft']]],
  ['compositions_20you_20will_20reuse_179',['Three compositions you will reuse',['../craft_backgrounds.html#autotoc_md441',1,'']]],
  ['compress_20tiles_20but_20not_20tilemaps_180',['Why Compress Tiles but Not Tilemaps?',['../examples_backgrounds_mode1_lz77.html#autotoc_md1009',1,'']]],
  ['compression_181',['LZ77 / LZSS Compression',['../examples_backgrounds_mode1_lz77.html#autotoc_md1008',1,'']]],
  ['concepts_182',['Concepts',['../hardware_overview.html#autotoc_md788',1,'Key Concepts'],['../examples_basics.html#autotoc_md1088',1,'Key Concepts'],['../examples_memory.html#autotoc_md1485',1,'Key Concepts'],['../examples_text.html#autotoc_md1700',1,'Key Concepts'],['../examples_audio_apu_switch.html#autotoc_md855',1,'SNES Concepts'],['../examples_audio_pitch_mod.html#autotoc_md865',1,'SNES Concepts'],['../examples_audio_play_noise.html#autotoc_md869',1,'SNES Concepts'],['../examples_audio_sfx_from_wav.html#autotoc_md874',1,'SNES Concepts'],['../examples_audio_snesmod_sfx.html#autotoc_md936',1,'SNES Concepts'],['../examples_audio_soundboard.html#autotoc_md944',1,'SNES Concepts'],['../examples_backgrounds_mode1_bg3_priority.html#autotoc_md999',1,'SNES Concepts'],['../examples_backgrounds_mode1_lz77.html#autotoc_md1007',1,'SNES Concepts'],['../examples_backgrounds_mode5_hires.html#autotoc_md1035',1,'SNES Concepts'],['../examples_basics_aim_target.html#autotoc_md1043',1,'SNES Concepts'],['../examples_basics_collision_demo.html#autotoc_md1052',1,'SNES Concepts'],['../examples_basics_fix32_orbit.html#autotoc_md1063',1,'SNES Concepts'],['../examples_basics_random.html#autotoc_md1082',1,'SNES Concepts'],['../examples_basics_scene_stack.html#autotoc_md1092',1,'SNES Concepts'],['../examples_basics_timer.html#autotoc_md1100',1,'SNES Concepts'],['../examples_chips_dsp1_cube.html#autotoc_md1105',1,'SNES Concepts'],['../examples_color_direct_color.html#autotoc_md1130',1,'SNES Concepts'],['../examples_color_gradient_9bit.html#autotoc_md1133',1,'SNES Concepts'],['../examples_color_hicolor_1792.html#autotoc_md1137',1,'SNES Concepts'],['../examples_color_transparency.html#autotoc_md1162',1,'SNES Concepts'],['../examples_games_mapandobjects.html#autotoc_md1255',1,'SNES Concepts'],['../examples_games_mode7_flying.html#autotoc_md1268',1,'SNES Concepts'],['../examples_games_mode7_racing.html#autotoc_md1271',1,'SNES Concepts'],['../examples_games_rpg.html#autotoc_md1277',1,'SNES Concepts'],['../examples_hdma_gradient_colors.html#autotoc_md1301',1,'SNES Concepts'],['../examples_hdma_hdma_indirect_gradient.html#autotoc_md1312',1,'SNES Concepts'],['../examples_hdma_hdma_wave_table.html#autotoc_md1339',1,'SNES Concepts'],['../examples_input_controller.html#autotoc_md1346',1,'SNES Concepts'],['../examples_input_mouse.html#autotoc_md1353',1,'SNES Concepts'],['../examples_maps_dynamic_map.html#autotoc_md1430',1,'SNES Concepts'],['../examples_maps_map_scroll.html#autotoc_md1441',1,'SNES Concepts'],['../examples_maps_slope_collision.html#autotoc_md1450',1,'SNES Concepts'],['../examples_maps_tiled.html#autotoc_md1461',1,'SNES Concepts'],['../examples_memory_hirom_demo.html#autotoc_md1478',1,'SNES Concepts'],['../examples_memory_save_game.html#autotoc_md1499',1,'SNES Concepts'],['../examples_mode7_perspective.html#autotoc_md1514',1,'SNES Concepts'],['../examples_mode7_perspective_rotate.html#autotoc_md1521',1,'SNES Concepts'],['../examples_mode7_rotate_scale.html#autotoc_md1538',1,'SNES Concepts'],['../examples_scrolling_mixed_scroll.html#autotoc_md1579',1,'SNES Concepts'],['../examples_scrolling_parallax_scroll.html#autotoc_md1600',1,'SNES Concepts'],['../examples_sprites_animated_sprite.html#autotoc_md1617',1,'SNES Concepts'],['../examples_sprites_aseprite_pipeline.html#autotoc_md1623',1,'SNES Concepts'],['../examples_sprites_dynamic_sprite.html#autotoc_md1640',1,'SNES Concepts'],['../examples_sprites_metasprite.html#autotoc_md1647',1,'SNES Concepts'],['../examples_sprites_simple_sprite.html#autotoc_md1667',1,'SNES Concepts'],['../examples_sprites_sprite_sizes.html#autotoc_md1681',1,'SNES Concepts'],['../examples_transitions_mosaic.html#autotoc_md1753',1,'SNES Concepts'],['../examples_windows_transparent_window.html#autotoc_md1770',1,'SNES Concepts'],['../examples_windows_window.html#autotoc_md1783',1,'SNES Concepts'],['../examples_windows_window_multi_hdma.html#autotoc_md1789',1,'SNES Concepts']]],
  ['concepts_183',['concepts',['../examples_audio_echo.html#autotoc_md860',1,'SNES concepts'],['../examples_input_move_sprite.html#autotoc_md1367',1,'SNES concepts'],['../examples_text_print_string.html#autotoc_md1695',1,'SNES concepts'],['../examples_text_scroll_message.html#autotoc_md1707',1,'SNES concepts']]],
  ['conduct_184',['Code of Conduct',['../contributing.html#autotoc_md1804',1,'']]],
  ['configuration_185',['Configuration',['../registers.html#autotoc_md838',1,'Channel Configuration'],['../examples_color_transparency.html#autotoc_md1165',1,'Color Math Configuration'],['../examples_windows_transparent_window.html#autotoc_md1769',1,'Color Math Configuration'],['../snes_sound_guide.html#autotoc_md691',1,'Configuration'],['../tutorial_audio.html#autotoc_md100',1,'Makefile Configuration']]],
  ['configure_20bg1_20and_20enable_20display_186',['4. Configure BG1 and Enable Display',['../examples_backgrounds_mode1_lz77.html#autotoc_md1016',1,'']]],
  ['configure_20obj_20size_187',['3. Configure OBJ size',['../examples_sprites_simple_sprite.html#autotoc_md1664',1,'']]],
  ['configure_20video_20mode_188',['1. Configure Video Mode',['../examples_backgrounds_mode1.html#autotoc_md967',1,'']]],
  ['configured_189',['🟡 Don&apos;t enable channels you haven&apos;t configured',['../tutorial_hdma.html#autotoc_md234',1,'']]],
  ['considerations_190',['Performance Considerations',['../tutorial_animation.html#autotoc_md93',1,'']]],
  ['consoleinit_191',['🟡 Mosaic state is not reset by &lt;span class=&quot;tt&quot;&gt;consoleInit&lt;/span&gt;',['../tutorial_mosaic.html#autotoc_md316',1,'']]],
  ['constants_192',['Constants',['../input_8h.html#autotoc_md36',1,'Button Constants'],['../tutorial_input.html#autotoc_md238',1,'Button Constants'],['../tutorial_audio.html#autotoc_md106',1,'Pitch Constants']]],
  ['consumer_193',['Pattern 1: Flag Sync (Producer/Consumer)',['../tutorial_sa1.html#autotoc_md336',1,'']]],
  ['contents_194',['Contents',['../hardware_overview.html#autotoc_md783',1,'Contents'],['../snes_graphics_guide.html#autotoc_md621',1,'Table of Contents'],['../snes_sound_guide.html#autotoc_md665',1,'Table of Contents'],['../registers.html#autotoc_md796',1,'Table of Contents']]],
  ['contents_20on_20first_20boot_20are_20undefined_195',['🔴 SRAM contents on first boot are undefined',['../tutorial_sram.html#autotoc_md390',1,'']]],
  ['continuous_20infinite_20scrolling_196',['Continuous / Infinite Scrolling',['../tutorial_scrolling.html#autotoc_md356',1,'']]],
  ['continuous_20scroll_197',['Continuous Scroll',['../examples_scrolling_continuous_scroll.html',1,'examples_scrolling']]],
  ['contributing_198',['Contributing',['../index.html#autotoc_md9',1,'']]],
  ['contributing_20to_20opensnes_199',['Contributing to OpenSNES',['../contributing.html',1,'index']]],
  ['contributions_200',['AI-Assisted Contributions',['../contributing.html#autotoc_md1818',1,'']]],
  ['control_201',['Control',['../registers.html#autotoc_md800',1,'$2100 - INIDISP (Display Control)'],['../registers.html#autotoc_md799',1,'Display Control'],['../registers.html#autotoc_md833',1,'DMA Control'],['../examples_input_two_players.html#autotoc_md1402',1,'Independent Control'],['../registers.html#autotoc_md824',1,'Interrupt Control'],['../examples_audio_snesmod_music.html#autotoc_md891',1,'Playback Control'],['../tutorial_audio.html#autotoc_md103',1,'Volume Control'],['../examples_audio_snesmod_music.html#autotoc_md892',1,'Volume Control']]],
  ['control_202',['4. Zoom control',['../examples_mode7_rotate_scale.html#autotoc_md1537',1,'']]],
  ['controlled_20scrolling_203',['D-PAD Controlled Scrolling',['../tutorial_scrolling.html#autotoc_md351',1,'']]],
  ['controller_204',['Disconnected Controller',['../examples_input_two_players.html#autotoc_md1409',1,'']]],
  ['controller_202_205',['Reading Controller 2',['../tutorial_input.html#autotoc_md241',1,'']]],
  ['controller_20detection_206',['Controller Detection',['../examples_input_two_players.html#autotoc_md1408',1,'']]],
  ['controller_20input_207',['Controller Input',['../examples_input_controller.html',1,'examples_input']]],
  ['controller_20input_20not_20working_208',['Controller input not working',['../troubleshooting.html#autotoc_md725',1,'']]],
  ['controller_20input_20tutorial_209',['Controller Input Tutorial',['../tutorial_input.html',1,'index']]],
  ['controller_20layout_210',['SNES Controller Layout',['../tutorial_input.html#autotoc_md237',1,'']]],
  ['controller_20registers_211',['Controller Registers',['../examples_input_two_players.html#autotoc_md1395',1,'']]],
  ['controller_20types_212',['Controller Types',['../examples_input_two_players.html#autotoc_md1410',1,'']]],
  ['controllers_213',['Controllers',['../examples_input_two_players.html#autotoc_md1396',1,'Reading Both Controllers'],['../tutorial_input.html#autotoc_md239',1,'Reading Controllers'],['../examples_input_two_players.html#autotoc_md1394',1,'Reading Two Controllers']]],
  ['controls_214',['Controls',['../examples_audio_snesmod_music_large.html#autotoc_md930',1,'Controls'],['../examples_audio_snesmod_sfx.html#autotoc_md933',1,'Controls'],['../examples_backgrounds_mode1_bg3_priority.html#autotoc_md993',1,'Controls'],['../examples_backgrounds_mode1_lz77.html#autotoc_md1011',1,'Controls'],['../examples_basics_collision_demo.html#autotoc_md1049',1,'Controls'],['../examples_basics_random.html#autotoc_md1081',1,'Controls'],['../examples_basics_scene_stack.html#autotoc_md1091',1,'Controls'],['../examples_basics_timer.html#autotoc_md1099',1,'Controls'],['../examples_color_transparency.html#autotoc_md1159',1,'Controls'],['../examples_fundamentals_text_glyphs.html#autotoc_md1177',1,'Controls'],['../examples_games_breakout.html#autotoc_md1200',1,'Controls'],['../examples_games_likemario.html#autotoc_md1228',1,'Controls'],['../examples_games_mapandobjects.html#autotoc_md1259',1,'Controls'],['../examples_games_tetris.html#autotoc_md1290',1,'Controls'],['../examples_hdma_gradient_colors.html#autotoc_md1295',1,'Controls'],['../examples_hdma_hdma_wave.html#autotoc_md1315',1,'Controls'],['../examples_input_controller.html#autotoc_md1345',1,'Controls'],['../examples_input_mouse.html#autotoc_md1357',1,'Controls'],['../examples_input_superscope.html#autotoc_md1373',1,'Controls'],['../examples_maps_dynamic_map.html#autotoc_md1435',1,'Controls'],['../examples_maps_map_scroll.html#autotoc_md1440',1,'Controls'],['../examples_maps_slope_collision.html#autotoc_md1455',1,'Controls'],['../examples_maps_tiled.html#autotoc_md1464',1,'Controls'],['../examples_memory_hirom_demo.html#autotoc_md1471',1,'Controls'],['../examples_memory_save_game.html#autotoc_md1491',1,'Controls'],['../examples_mode7_perspective.html#autotoc_md1508',1,'Controls'],['../examples_mode7_rotate_scale.html#autotoc_md1531',1,'Controls'],['../examples_scrolling_continuous_scroll.html#autotoc_md1556',1,'Controls'],['../examples_scrolling_mixed_scroll.html#autotoc_md1584',1,'Controls'],['../examples_scrolling_parallax_scroll.html#autotoc_md1593',1,'Controls'],['../examples_sprites_animated_sprite.html#autotoc_md1610',1,'Controls'],['../examples_sprites_dynamic_metasprite.html#autotoc_md1629',1,'Controls'],['../examples_sprites_dynamic_sprite.html#autotoc_md1633',1,'Controls'],['../examples_sprites_metasprite.html#autotoc_md1651',1,'Controls'],['../examples_sprites_simple_sprite.html#autotoc_md1659',1,'Controls'],['../examples_sprites_sprite_sizes.html#autotoc_md1674',1,'Controls'],['../examples_transitions_mosaic.html#autotoc_md1747',1,'Controls'],['../examples_windows_transparent_window.html#autotoc_md1763',1,'Controls'],['../examples_windows_window.html#autotoc_md1775',1,'Controls']]],
  ['controls_20krom_20s_20map_215',['Controls (krom&apos;s map)',['../examples_mode7_perspective_rotate.html#autotoc_md1520',1,'']]],
  ['convention_216',['I-RAM Layout Convention',['../tutorial_sa1.html#autotoc_md338',1,'']]],
  ['convention_217',['convention',['../oam.html#autotoc_md777',1,'OpenSNES SDK convention'],['../fixed32_8h.html#autotoc_md30',1,'Sign convention']]],
  ['conventions_218',['Naming Conventions',['../code_style.html#autotoc_md607',1,'']]],
  ['conversion_20macros_219',['The conversion macros',['../tutorial_math.html#autotoc_md264',1,'']]],
  ['conversion_20tools_220',['Conversion Tools',['../snes_sound_guide.html#autotoc_md706',1,'Conversion Tools'],['../snes_graphics_guide.html#autotoc_md658',1,'Graphics Conversion Tools']]],
  ['conversion_20with_20gfx4snes_221',['Asset Conversion with gfx4snes',['../examples_games_likemario.html#autotoc_md1247',1,'']]],
  ['convert_20for_20the_20snes_222',['The workflow: design in Tiled, convert for the SNES',['../craft_tiles_to_levels.html#autotoc_md483',1,'']]],
  ['converted_223',['🟡 Match &lt;span class=&quot;tt&quot;&gt;base_tile&lt;/span&gt;/&lt;span class=&quot;tt&quot;&gt;stride&lt;/span&gt; to how the sheet was converted',['../tutorial_panel.html#autotoc_md326',1,'']]],
  ['converted_20assets_224',['Pre-Converted Assets',['../examples_games_breakout.html#autotoc_md1222',1,'']]],
  ['converting_20a_20sheet_3a_20s_20must_20match_20the_20sprite_20size_225',['Converting a sheet: &lt;span class=&quot;tt&quot;&gt;-s&lt;/span&gt; must match the sprite size',['../tutorial_sprites.html#autotoc_md370',1,'']]],
  ['converting_20sprite_20sheets_20with_20gfx4snes_226',['Converting Sprite Sheets with gfx4snes',['../tutorial_animation.html#autotoc_md78',1,'']]],
  ['coordinate_20system_227',['Coordinate system',['../tutorial_mode7.html#autotoc_md290',1,'']]],
  ['coprocessor_228',['Coprocessor',['../examples_by_category.html#autotoc_md602',1,'DSP-1 Coprocessor'],['../examples_by_category.html#autotoc_md600',1,'SA-1 Coprocessor']]],
  ['coprocessors_229',['More horsepower — the cartridge coprocessors',['../learning_path.html#autotoc_md567',1,'']]],
  ['corners_230',['Checking All Four Corners',['../tutorial_collision.html#autotoc_md125',1,'']]],
  ['correct_20on_20this_20target_20since_20chantier_20a1_231',['🟢 &lt;span class=&quot;tt&quot;&gt;int&lt;/span&gt; and &lt;span class=&quot;tt&quot;&gt;long&lt;/span&gt; sizes are correct on this target (since chantier A1)',['../tutorial_math.html#autotoc_md275',1,'']]],
  ['corrupted_232',['Tiles appear corrupted',['../troubleshooting.html#autotoc_md729',1,'']]],
  ['corruption_233',['🔴 Battery dies → silent corruption',['../tutorial_sram.html#autotoc_md391',1,'']]],
  ['cos_20lookup_20tables_234',['Trigonometry (sin/cos lookup tables)',['../tutorial_math.html#autotoc_md266',1,'']]],
  ['cos_20luts_20are_20unsigned_20angle_20signed_20result_235',['🟡 Sin/cos LUTs are unsigned-angle, signed-result',['../tutorial_math.html#autotoc_md281',1,'']]],
  ['cost_236',['cost',['../tutorial_colormath.html#autotoc_md154',1,'Cycle cost'],['../tutorial_dma.html#autotoc_md182',1,'Cycle cost'],['../tutorial_hdma.html#autotoc_md235',1,'Cycle cost'],['../tutorial_mode7.html#autotoc_md303',1,'Cycle cost'],['../tutorial_mosaic.html#autotoc_md317',1,'Cycle cost'],['../tutorial_sram.html#autotoc_md398',1,'Cycle cost'],['../tutorial_window.html#autotoc_md436',1,'Cycle cost']]],
  ['cost_20side_3a_20tiles_20by_20mode_237',['The cost side: tiles by mode',['../craft_planning.html#autotoc_md473',1,'']]],
  ['cost_20summary_238',['Cycle cost summary',['../tutorial_math.html#autotoc_md284',1,'']]],
  ['counter_239',['Pattern 2: Free-Running Counter',['../tutorial_sa1.html#autotoc_md337',1,'']]],
  ['counter_20recommended_240',['Manual Counter (Recommended)',['../tutorial_animation.html#autotoc_md73',1,'']]],
  ['cproc_241',['cproc',['../third_party.html#autotoc_md746',1,'']]],
  ['cpu_242',['SPC700 CPU',['../snes_sound_guide.html#autotoc_md670',1,'']]],
  ['cpu_20budget_3a_203_2058_20mhz_243',['The CPU budget: ~3.58 MHz',['../craft_frame_budget.html#autotoc_md457',1,'']]],
  ['cpu_20registers_20_244200_20_24421f_244',['CPU Registers ($4200-$421F)',['../registers.html#autotoc_md823',1,'']]],
  ['cpu_20registers_20_244200_20_2444ff_245',['CPU Registers ($4200-$44FF)',['../memory_map.html#autotoc_md757',1,'']]],
  ['cracked_20it_246',['Debug tooling that cracked it',['../examples_audio_speech_synth.html#autotoc_md950',1,'']]],
  ['craft_247',['Game-Craft',['../index.html#autotoc_md2',1,'']]],
  ['craft_20guides_248',['Game-Craft Guides',['../craft.html',1,'index']]],
  ['crash_249',['Runtime Issues (Black Screen / Crash)',['../troubleshooting.html#autotoc_md721',1,'']]],
  ['crashes_20after_20a_20few_20seconds_250',['ROM runs but crashes after a few seconds',['../troubleshooting.html#autotoc_md723',1,'']]],
  ['create_20the_20gsu_20loader_2065816_20asm_251',['3. Create the GSU Loader (65816 ASM)',['../tutorial_superfx.html#autotoc_md405',1,'']]],
  ['create_20your_20own_20project_252',['A5. Create Your Own Project',['../getting_started.html#autotoc_md539',1,'']]],
  ['creating_20music_253',['Creating Music',['../examples_audio_snesmod_music.html#autotoc_md894',1,'']]],
  ['creating_20music_20with_20openmpt_254',['Creating Music with OpenMPT',['../tutorial_audio.html#autotoc_md104',1,'']]],
  ['creation_255',['Soundbank Creation',['../snesmod_8h.html#autotoc_md57',1,'']]],
  ['creation_20tools_256',['Sound Creation Tools',['../snes_sound_guide.html#autotoc_md705',1,'']]],
  ['credits_257',['Credits',['../examples_audio_snesmod_music.html#autotoc_md925',1,'Credits'],['../examples_games_breakout.html#autotoc_md1227',1,'Credits'],['../examples_games_likemario.html#autotoc_md1253',1,'Credits'],['../examples_scrolling_continuous_scroll.html#autotoc_md1577',1,'Credits']]],
  ['critical_258',['Main Loop (CRITICAL!)',['../examples_audio_snesmod_music.html#autotoc_md890',1,'']]],
  ['critical_259',['Scanline Limits (Critical!)',['../snes_graphics_guide.html#autotoc_md637',1,'']]],
  ['critical_3a_20oam_20write_20buffer_260',['Critical: OAM Write Buffer',['../oam.html#autotoc_md768',1,'']]],
  ['cross_20check_261',['Measured parity (luna v1.9.0 + Mesen2 cross-check)',['../examples_color_hicolor_1792.html#autotoc_md1139',1,'']]],
  ['cube_262',['Cube',['../examples_chips_dsp1_cube.html',1,'DSP-1 Cube'],['../examples_chips_superfx_3d.html',1,'SuperFX 3D Cube']]],
  ['curated_20shelf_263',['Go deeper — the curated shelf',['../craft.html#autotoc_md478',1,'']]],
  ['current_264',['Architecture (current)',['../examples_games_shmup_1942.html#autotoc_md1284',1,'']]],
  ['cursor_265',['4. Main Loop: Read Mouse, Update Cursor',['../examples_input_mouse.html#autotoc_md1362',1,'']]],
  ['cursor_20sprite_266',['2. Load Cursor Sprite',['../examples_input_mouse.html#autotoc_md1360',1,'']]],
  ['custom_20tile_20sizes_267',['Custom Tile Sizes',['../tutorial_collision.html#autotoc_md126',1,'']]],
  ['cycle_20cost_268',['Cycle cost',['../tutorial_colormath.html#autotoc_md154',1,'Cycle cost'],['../tutorial_dma.html#autotoc_md182',1,'Cycle cost'],['../tutorial_hdma.html#autotoc_md235',1,'Cycle cost'],['../tutorial_mode7.html#autotoc_md303',1,'Cycle cost'],['../tutorial_mosaic.html#autotoc_md317',1,'Cycle cost'],['../tutorial_sram.html#autotoc_md398',1,'Cycle cost'],['../tutorial_window.html#autotoc_md436',1,'Cycle cost']]],
  ['cycle_20cost_20summary_269',['Cycle cost summary',['../tutorial_math.html#autotoc_md284',1,'']]],
  ['cycling_270',['Ambient life — palette cycling',['../craft_game_feel.html#autotoc_md464',1,'']]],
  ['cycling_20between_20levels_271',['8. Color Cycling Between Levels',['../examples_games_breakout.html#autotoc_md1212',1,'']]]
];
