var searchData=
[
  ['oam_0',['OAM',['../examples_graphics_sprites_animated_sprite.html#autotoc_md1226',1,'16x16 Tiles in OAM'],['../tutorial_sprites.html#autotoc_md321',1,'Initialize OAM'],['../tutorial_sprites.html#autotoc_md323',1,'Updating OAM']]],
  ['oam_20address_1',['OAM Address',['../registers.html#autotoc_md647',1,'$2102-$2103 - OAMADDL/H (OAM Address)'],['../oam.html#autotoc_md617',1,'Setting OAM Address']]],
  ['oam_20data_20write_2',['$2104 - OAMDATA (OAM Data Write)',['../registers.html#autotoc_md648',1,'']]],
  ['oam_20directly_3',['3. Set Up OAM Directly',['../examples_input_mouse.html#autotoc_md1311',1,'']]],
  ['oam_20dma_4',['🔴 Channel 7 is reserved for OAM DMA',['../tutorial_hdma.html#autotoc_md208',1,'']]],
  ['oam_20dma_20is_20automated_20don_20t_20double_20up_5',['🟠 OAM DMA is automated, don&apos;t double-up',['../tutorial_dma.html#autotoc_md163',1,'']]],
  ['oam_20high_20table_6',['OAM High Table',['../examples_graphics_sprites_object_size.html#autotoc_md1267',1,'']]],
  ['oam_20object_20attribute_20memory_7',['OAM Object Attribute Memory',['../memory_map.html#autotoc_md598',1,'OAM (Object Attribute Memory)'],['../examples_graphics_sprites_simple_sprite.html#autotoc_md1289',1,'OAM (Object Attribute Memory)'],['../oam.html',1,'SNES OAM (Object Attribute Memory)']]],
  ['oam_20registers_8',['OAM Registers',['../oam.html#autotoc_md616',1,'']]],
  ['oam_20setup_9',['5. Direct OAM Setup',['../examples_input_superscope.html#autotoc_md1330',1,'']]],
  ['oam_20sprite_10',['Simple Sprite -- Your First OAM Sprite',['../examples_graphics_sprites_simple_sprite.html',1,'examples_graphics_sprites']]],
  ['oam_20sprite_20memory_11',['OAM (Sprite Memory)',['../registers.html#autotoc_md646',1,'']]],
  ['oam_20structure_12',['OAM Structure',['../tutorial_sprites.html#autotoc_md319',1,'OAM Structure'],['../oam.html#autotoc_md608',1,'OAM Structure'],['../examples_graphics_sprites.html#autotoc_md1274',1,'OAM Structure']]],
  ['oam_20structure_20544_20bytes_20total_13',['OAM Structure (544 bytes total)',['../snes_graphics_guide.html#autotoc_md480',1,'']]],
  ['oam_20tile_20numbers_14',['VRAM Tile Layout and OAM Tile Numbers',['../examples_graphics_sprites_metasprite.html#autotoc_md1252',1,'']]],
  ['oam_20write_20buffer_15',['Critical: OAM Write Buffer',['../oam.html#autotoc_md612',1,'']]],
  ['oam_20writes_20are_20safe_16',['When VRAM/CGRAM/OAM writes are safe',['../tutorial_dma.html#autotoc_md154',1,'']]],
  ['oam_20writes_20outside_20vblank_20or_20force_20blank_20are_20silently_20dropped_17',['🔴 VRAM/CGRAM/OAM writes outside VBlank or force blank are silently dropped',['../tutorial_dma.html#autotoc_md159',1,'']]],
  ['oamaddl_20h_20oam_20address_18',['$2102-$2103 - OAMADDL/H (OAM Address)',['../registers.html#autotoc_md647',1,'']]],
  ['oambuffer_19',['2. Set up sprites via the oambuffer',['../examples_graphics_sprites_dynamic_sprite.html#autotoc_md1239',1,'']]],
  ['oamdata_20oam_20data_20write_20',['$2104 - OAMDATA (OAM Data Write)',['../registers.html#autotoc_md648',1,'']]],
  ['oammemory_20writes_21',['Direct oamMemory[] Writes',['../examples_basics_collision_demo.html#autotoc_md786',1,'']]],
  ['obj_20math_20depends_20on_20palette_22',['🟡 OBJ math depends on palette',['../tutorial_colormath.html#autotoc_md146',1,'']]],
  ['obj_20size_23',['3. Configure OBJ size',['../examples_graphics_sprites_simple_sprite.html#autotoc_md1285',1,'']]],
  ['obj_20size_20modes_20register_20_242101_24',['OBJ Size Modes (Register $2101)',['../examples_graphics_sprites_metasprite.html#autotoc_md1250',1,'']]],
  ['obj_20sprites_25',['🟠 Mosaic does not affect OBJ (sprites)',['../tutorial_mosaic.html#autotoc_md278',1,'']]],
  ['obj_5fflipx_20ndash_20hardware_20horizontal_20mirror_26',['OBJ_FLIPX &amp;ndash; Hardware Horizontal Mirror',['../examples_graphics_sprites_animated_sprite.html#autotoc_md1224',1,'']]],
  ['object_20attribute_20memory_27',['Object Attribute Memory',['../memory_map.html#autotoc_md598',1,'OAM (Object Attribute Memory)'],['../examples_graphics_sprites_simple_sprite.html#autotoc_md1289',1,'OAM (Object Attribute Memory)'],['../oam.html',1,'SNES OAM (Object Attribute Memory)']]],
  ['object_20engine_28',['Object Engine',['../examples_games_mapandobjects.html#autotoc_md875',1,'']]],
  ['object_20engine_20and_20slope_20collision_29',['Object Engine and Slope Collision',['../examples_maps_slopemario.html#autotoc_md1408',1,'']]],
  ['object_20size_20all_206_20snes_20sprite_20size_20modes_30',['Object Size -- All 6 SNES Sprite Size Modes',['../examples_graphics_sprites_object_size.html',1,'examples_graphics_sprites']]],
  ['object_20types_20in_20assembly_31',['2. Register Object Types in Assembly',['../examples_games_mapandobjects.html#autotoc_md880',1,'']]],
  ['objectives_32',['Objectives',['../examples_audio_snesmod_music.html#autotoc_md703',1,'Learning Objectives'],['../examples_graphics_backgrounds_mode1.html#autotoc_md941',1,'Learning Objectives'],['../examples_graphics_effects_fading.html#autotoc_md1050',1,'Learning Objectives'],['../examples_input_two_players.html#autotoc_md1336',1,'Learning Objectives']]],
  ['objects_33',['Map and Objects',['../examples_games_mapandobjects.html',1,'examples_games']]],
  ['objects_20from_20map_20data_34',['3. Load Objects from Map Data',['../examples_games_mapandobjects.html#autotoc_md881',1,'']]],
  ['objsel_20_242101_35',['Sprite Sizes (OBJSEL $2101)',['../examples_graphics_sprites.html#autotoc_md1275',1,'']]],
  ['objsel_20register_20_242101_36',['OBJSEL Register ($2101)',['../examples_graphics_sprites_object_size.html#autotoc_md1266',1,'']]],
  ['objsel_20sprite_20settings_37',['$2101 - OBJSEL (Sprite Settings)',['../registers.html#autotoc_md645',1,'']]],
  ['observe_38',['Observe',['../examples_basics_aim_target.html#autotoc_md774',1,'What to Observe'],['../examples_memory_sa1_starfield.html#autotoc_md1451',1,'What to Observe']]],
  ['of_20a_20switch_39',['Why a framework instead of a switch',['../examples_basics_scene_stack.html#autotoc_md808',1,'']]],
  ['of_20bounds_20behaviour_40',['Out-of-bounds behaviour',['../tutorial_mode7.html#autotoc_md258',1,'']]],
  ['of_20bounds_20with_20mode7_5ftransparent_20shows_20the_20backdrop_20not_20a_20layer_41',['🟡 Out-of-bounds with &lt;span class=&quot;tt&quot;&gt;MODE7_TRANSPARENT&lt;/span&gt; shows the backdrop, not a layer',['../tutorial_mode7.html#autotoc_md269',1,'']]],
  ['of_20conduct_42',['Code of Conduct',['../contributing.html#autotoc_md1542',1,'']]],
  ['of_20contents_43',['of Contents',['../snes_graphics_guide.html#autotoc_md466',1,'Table of Contents'],['../snes_sound_guide.html#autotoc_md510',1,'Table of Contents'],['../registers.html#autotoc_md640',1,'Table of Contents']]],
  ['of_20intuitive_44',['🟠 &lt;span class=&quot;tt&quot;&gt;colorMathSetSource&lt;/span&gt; polarity is opposite of intuitive',['../tutorial_colormath.html#autotoc_md142',1,'']]],
  ['of_20overlap_45',['Pushing Out of Overlap',['../tutorial_collision.html#autotoc_md124',1,'']]],
  ['off_20load_20everything_46',['1. Lights Off, Load Everything',['../examples_games_breakout.html#autotoc_md823',1,'']]],
  ['on_47',['7. Lights On',['../examples_text_hello_world.html#autotoc_md1497',1,'']]],
  ['on_20bg1_204bpp_20in_20mode_201_48',['1. Set up text on BG1 (4bpp in Mode 1)',['../examples_graphics_sprites_object_size.html#autotoc_md1261',1,'']]],
  ['on_20bg3_49',['Open chantier — S6 HUD on BG3',['../examples_games_shmup_1942.html#autotoc_md891',1,'']]],
  ['on_20both_20ends_50',['Boundaries are inclusive on both ends',['../tutorial_window.html#autotoc_md379',1,'']]],
  ['on_20channel_200_51',['🟠 Channel 0 vs HDMA on channel 0',['../tutorial_dma.html#autotoc_md162',1,'']]],
  ['on_20divide_20by_20zero_52',['🟠 &lt;span class=&quot;tt&quot;&gt;fixDiv&lt;/span&gt; returns 0 on divide-by-zero',['../tutorial_math.html#autotoc_md245',1,'']]],
  ['on_20first_20boot_20are_20undefined_53',['🔴 SRAM contents on first boot are undefined',['../tutorial_sram.html#autotoc_md345',1,'']]],
  ['on_20hdmasetup_54',['🔴 Bank byte trap on &lt;span class=&quot;tt&quot;&gt;hdmaSetup&lt;/span&gt;',['../tutorial_hdma.html#autotoc_md209',1,'']]],
  ['on_20palette_55',['🟡 OBJ math depends on palette',['../tutorial_colormath.html#autotoc_md146',1,'']]],
  ['on_20snes_56',['How Text Works on SNES',['../examples_text.html#autotoc_md1512',1,'']]],
  ['on_20the_20backdrop_57',['🟡 Colour-math on the backdrop',['../tutorial_colormath.html#autotoc_md144',1,'']]],
  ['on_20the_20snes_58',['on the SNES',['../examples_input_controller.html#autotoc_md1297',1,'How Input Works on the SNES'],['../examples_text_text_test.html#autotoc_md1519',1,'Text Rendering on the SNES'],['../tutorial_math.html#autotoc_md229',1,'Why fixed-point on the SNES']]],
  ['on_20this_20target_20since_20chantier_20a1_59',['🟢 &lt;span class=&quot;tt&quot;&gt;int&lt;/span&gt; and &lt;span class=&quot;tt&quot;&gt;long&lt;/span&gt; sizes are correct on this target (since chantier A1)',['../tutorial_math.html#autotoc_md242',1,'']]],
  ['on_20wh0_20wh1_20requires_20repeat_20mode_60',['🟠 HDMA on &lt;span class=&quot;tt&quot;&gt;WH0&lt;/span&gt;/&lt;span class=&quot;tt&quot;&gt;WH1&lt;/span&gt; requires repeat mode',['../tutorial_window.html#autotoc_md386',1,'']]],
  ['one_20draw_20function_20engine_20resolved_20size_61',['One Draw Function, Engine-Resolved Size',['../tutorial_animation.html#autotoc_md86',1,'']]],
  ['one_20layer_62',['Why This Works with One Layer',['../examples_graphics_effects_parallax_scrolling.html#autotoc_md1150',1,'']]],
  ['one_20layer_20only_63',['One Layer Only',['../examples_graphics_backgrounds_mode7.html#autotoc_md1025',1,'']]],
  ['one_20topic_20per_20pr_64',['One topic per PR',['../contributing.html#autotoc_md1550',1,'']]],
  ['only_65',['One Layer Only',['../examples_graphics_backgrounds_mode7.html#autotoc_md1025',1,'']]],
  ['only_20the_20ram_20buffer_20pattern_66',['3. ROM is Read-Only (The RAM Buffer Pattern)',['../examples_games_breakout.html#autotoc_md825',1,'']]],
  ['only_20trap_67',['🔴 The &quot;BG2 is sub-screen-only&quot; trap',['../tutorial_colormath.html#autotoc_md141',1,'']]],
  ['op_20or_20assembly_20errors_68',['Build fails with &quot;unhandled op&quot; or assembly errors',['../getting_started.html#autotoc_md416',1,'']]],
  ['op_20trap_69',['The window logic op trap',['../tutorial_window.html#autotoc_md380',1,'']]],
  ['op_3a_20xxx_70',['Build fails with &quot;unhandled op: XXX&quot;',['../troubleshooting.html#autotoc_md564',1,'']]],
  ['open_20chantier_20—_20s6_20hud_20on_20bg3_71',['Open chantier — S6 HUD on BG3',['../examples_games_shmup_1942.html#autotoc_md891',1,'']]],
  ['openmpt_72',['Creating Music with OpenMPT',['../tutorial_audio.html#autotoc_md102',1,'']]],
  ['openmpt_20recommended_73',['Using OpenMPT (Recommended)',['../examples_audio_snesmod_music.html#autotoc_md720',1,'']]],
  ['opensnes_74',['OpenSNES',['../tutorial_audio.html#autotoc_md95',1,'Audio Options in OpenSNES'],['../contributing.html',1,'Contributing to OpenSNES'],['../getting_started.html',1,'Getting Started with OpenSNES'],['../troubleshooting.html',1,'Troubleshooting OpenSNES']]],
  ['opensnes_20code_20style_20guide_75',['OpenSNES Code Style Guide',['../code_style.html',1,'index']]],
  ['opensnes_20documentation_76',['OpenSNES Documentation',['../index.html',1,'']]],
  ['opensnes_20examples_77',['OpenSNES Examples',['../examples.html',1,'index']]],
  ['opensnes_20not_20defined_20or_20no_20rule_20to_20make_20target_20common_20mk_78',['&quot;OPENSNES not defined&quot; or &quot;No rule to make target &apos;common.mk&apos;&quot;',['../troubleshooting.html#autotoc_md560',1,'']]],
  ['opensnes_20register_20macros_79',['OpenSNES Register Macros',['../registers.html#autotoc_md692',1,'']]],
  ['opensnes_20sdk_80',['A3. Download OpenSNES SDK',['../getting_started.html#autotoc_md398',1,'']]],
  ['opensnes_20sdk_20convention_81',['OpenSNES SDK convention',['../oam.html#autotoc_md621',1,'']]],
  ['opensnes_20sprite_20functions_82',['Using OpenSNES Sprite Functions',['../tutorial_sprites.html#autotoc_md320',1,'']]],
  ['operations_83',['Common Operations',['../snes_sound_guide.html#autotoc_md557',1,'']]],
  ['operations_20available_84',['Operations available',['../fixed32_8h.html#autotoc_md27',1,'']]],
  ['opposite_20of_20intuitive_85',['🟠 &lt;span class=&quot;tt&quot;&gt;colorMathSetSource&lt;/span&gt; polarity is opposite of intuitive',['../tutorial_colormath.html#autotoc_md142',1,'']]],
  ['opt_20ins_86',['Framework opt-ins',['../index.html#autotoc_md6',1,'']]],
  ['options_87',['smconv Options',['../examples_audio_snesmod_music.html#autotoc_md746',1,'']]],
  ['options_20in_20opensnes_88',['Audio Options in OpenSNES',['../tutorial_audio.html#autotoc_md95',1,'']]],
  ['or_20assembly_20errors_89',['Build fails with &quot;unhandled op&quot; or assembly errors',['../getting_started.html#autotoc_md416',1,'']]],
  ['or_20cc65816_20not_20found_90',['Empty &lt;span class=&quot;tt&quot;&gt;compiler/&lt;/span&gt; directories or &quot;cc65816 not found&quot;',['../troubleshooting.html#autotoc_md561',1,'']]],
  ['or_20cc_3a_20command_20not_20found_91',['&quot;clang: command not found&quot; or &quot;cc: command not found&quot;',['../troubleshooting.html#autotoc_md563',1,'']]],
  ['or_20empty_20compiler_20folder_92',['&quot;fatal: repository not found&quot; or empty compiler folder',['../getting_started.html#autotoc_md413',1,'']]],
  ['or_20force_20blank_20are_20silently_20dropped_93',['🔴 VRAM/CGRAM/OAM writes outside VBlank or force blank are silently dropped',['../tutorial_dma.html#autotoc_md159',1,'']]],
  ['or_20linker_20errors_20about_20size_94',['&quot;ROM too large&quot; or linker errors about size',['../troubleshooting.html#autotoc_md577',1,'']]],
  ['or_20no_20rule_20to_20make_20target_20common_20mk_95',['&quot;OPENSNES not defined&quot; or &quot;No rule to make target &apos;common.mk&apos;&quot;',['../troubleshooting.html#autotoc_md560',1,'']]],
  ['organization_96',['Organization',['../code_style.html#autotoc_md462',1,'File Organization'],['../tutorial_animation.html#autotoc_md74',1,'Sprite Sheet Organization']]],
  ['out_20fade_20in_97',['Fade Out / Fade In',['../tutorial_game_states.html#autotoc_md171',1,'']]],
  ['out_20full_20to_20black_98',['Fade Out (Full to Black)',['../examples_graphics_effects_fading.html#autotoc_md1061',1,'']]],
  ['out_20of_20bounds_20behaviour_99',['Out-of-bounds behaviour',['../tutorial_mode7.html#autotoc_md258',1,'']]],
  ['out_20of_20bounds_20with_20mode7_5ftransparent_20shows_20the_20backdrop_20not_20a_20layer_100',['🟡 Out-of-bounds with &lt;span class=&quot;tt&quot;&gt;MODE7_TRANSPARENT&lt;/span&gt; shows the backdrop, not a layer',['../tutorial_mode7.html#autotoc_md269',1,'']]],
  ['out_20of_20overlap_101',['Pushing Out of Overlap',['../tutorial_collision.html#autotoc_md124',1,'']]],
  ['output_102',['No audio output',['../examples_audio_snesmod_music.html#autotoc_md739',1,'']]],
  ['outside_20vblank_20or_20force_20blank_20are_20silently_20dropped_103',['🔴 VRAM/CGRAM/OAM writes outside VBlank or force blank are silently dropped',['../tutorial_dma.html#autotoc_md159',1,'']]],
  ['over_104',['Game Over',['../tutorial_game_states.html#autotoc_md177',1,'']]],
  ['over_20100_20bricks_105',['5. Grid Collision (Don&apos;t Loop Over 100 Bricks)',['../examples_games_breakout.html#autotoc_md827',1,'']]],
  ['over_20backgrounds_106',['Mode 1 BG3 High Priority -- HUD Layer Over Backgrounds',['../examples_graphics_backgrounds_mode1_bg3_priority.html',1,'examples_graphics_backgrounds']]],
  ['over_20breakout_107',['Simple Game Over (Breakout)',['../tutorial_game_states.html#autotoc_md178',1,'']]],
  ['over_20tetris_108',['Restart Game Over (Tetris)',['../tutorial_game_states.html#autotoc_md179',1,'']]],
  ['over_20with_20fade_109',['Game Over with Fade',['../tutorial_game_states.html#autotoc_md180',1,'']]],
  ['overflows_20for_20x_20≥_20128_110',['🔴 &lt;span class=&quot;tt&quot;&gt;FIX(x)&lt;/span&gt; overflows for &lt;span class=&quot;tt&quot;&gt;|x| ≥ 128&lt;/span&gt;',['../tutorial_math.html#autotoc_md243',1,'']]],
  ['overlap_111',['Overlap',['../examples_games_breakout.html#autotoc_md824',1,'2. The VRAM Map — A Deliberate Overlap'],['../tutorial_collision.html#autotoc_md124',1,'Pushing Out of Overlap']]],
  ['overlap_20test_112',['Basic Overlap Test',['../tutorial_collision.html#autotoc_md114',1,'']]],
  ['overlay_20—_20examples_20graphics_20effects_20transparency_113',['Additive cloud overlay — &lt;span class=&quot;tt&quot;&gt;examples/graphics/effects/transparency&lt;/span&gt;',['../tutorial_colormath.html#autotoc_md138',1,'']]],
  ['overview_114',['Overview',['../memory_map.html#autotoc_md593',1,'Address Space Overview'],['../snes_sound_guide.html#autotoc_md512',1,'Architecture Overview'],['../dma_8h.html#autotoc_md23',1,'DMA Overview'],['../examples_graphics_backgrounds_mode1.html#autotoc_md948',1,'Mode 1 Overview'],['../background_8h.html#autotoc_md13',1,'Overview'],['../collision_8h.html#autotoc_md14',1,'Overview'],['../fixed32_8h.html#autotoc_md26',1,'Overview'],['../math_8h.html#autotoc_md42',1,'Overview'],['../hardware_overview.html',1,'SNES Hardware Overview'],['../examples_audio_snesmod_music.html#autotoc_md710',1,'SNESMOD Overview'],['../sram_8h.html#autotoc_md60',1,'SRAM Overview']]],
  ['overwrite_20tile_20graphics_115',['Approach 2: Overwrite Tile Graphics',['../tutorial_animation.html#autotoc_md89',1,'']]],
  ['own_20level_116',['Making Your Own Level',['../examples_maps_tiled.html#autotoc_md1424',1,'']]],
  ['own_20project_117',['A5. Create Your Own Project',['../getting_started.html#autotoc_md400',1,'']]]
];
