var searchData=
[
  ['m16_20background_20wants_20q16_0',['🟡 &lt;span class=&quot;tt&quot;&gt;map&lt;/span&gt; streams &lt;span class=&quot;tt&quot;&gt;.m16&lt;/span&gt;; &lt;span class=&quot;tt&quot;&gt;background&lt;/span&gt; wants &lt;span class=&quot;tt&quot;&gt;.q16&lt;/span&gt;',['../tutorial_map.html#autotoc_md261',1,'']]],
  ['machine_1',['Machine',['../examples_input_superscope.html#autotoc_md1384',1,'6. State Machine'],['../snes_graphics_guide.html#autotoc_md644',1,'Animation State Machine']]],
  ['machine_2',['2. State machine',['../examples_sprites_animated_sprite.html#autotoc_md1616',1,'']]],
  ['machine_20at_20a_20point_20in_20time_3',['Recipe 1 — Inspect the machine at a point in time',['../tutorial_debugging.html#autotoc_md158',1,'']]],
  ['machine_20summary_4',['State Machine Summary',['../tutorial_game_states.html#autotoc_md198',1,'']]],
  ['machine_20under_20the_20hood_5',['The manual state machine (under the hood)',['../tutorial_game_states.html#autotoc_md186',1,'']]],
  ['macros_6',['OpenSNES Register Macros',['../registers.html#autotoc_md850',1,'']]],
  ['macros_7',['The conversion macros',['../tutorial_math.html#autotoc_md265',1,'']]],
  ['mailbox_8',['I-RAM — The Mailbox',['../tutorial_sa1.html#autotoc_md332',1,'']]],
  ['main_20and_20sub_20mean_20here_9',['What &quot;main&quot; and &quot;sub&quot; mean here',['../tutorial_colormath.html#autotoc_md139',1,'']]],
  ['main_20loop_10',['Main Loop',['../examples_games_likemario.html#autotoc_md1241',1,'7. The Main Loop'],['../examples_color_transparency.html#autotoc_md1172',1,'Main Loop']]],
  ['main_20loop_11',['Per-frame DMA in the main loop',['../tutorial_dma.html#autotoc_md172',1,'']]],
  ['main_20loop_20critical_12',['Main Loop (CRITICAL!)',['../examples_audio_snesmod_music.html#autotoc_md892',1,'']]],
  ['main_20loop_3a_20read_20mouse_20update_20cursor_13',['4. Main Loop: Read Mouse, Update Cursor',['../examples_input_mouse.html#autotoc_md1364',1,'']]],
  ['main_20loop_3a_20update_20draw_20sync_14',['4. Main Loop: Update, Draw, Sync',['../examples_games_mapandobjects.html#autotoc_md1266',1,'']]],
  ['main_20screen_20enable_15',['$212C - TM (Main Screen Enable)',['../registers.html#autotoc_md822',1,'']]],
  ['main_20screen_20sub_20screen_16',['Color Math: Main Screen + Sub Screen',['../examples_color_transparency.html#autotoc_md1165',1,'']]],
  ['main_20screen_20vs_20sub_20screen_17',['Main Screen vs Sub Screen',['../colormath_8h.html#autotoc_md19',1,'']]],
  ['main_20table_204_20bytes_20per_20sprite_18',['Main Table (4 bytes per sprite)',['../oam.html#autotoc_md767',1,'']]],
  ['major_20tile_20layout_19',['Column-Major Tile Layout',['../tutorial_superfx.html#autotoc_md417',1,'']]],
  ['make_20',['&quot;command not found: make&quot;',['../getting_started.html#autotoc_md555',1,'']]],
  ['make_20it_20feel_20good_21',['Stage 4 — &quot;Can I make it feel good?&quot;',['../learning_path.html#autotoc_md566',1,'']]],
  ['make_20target_20common_20mk_22',['&quot;OPENSNES not defined&quot; or &quot;No rule to make target &apos;common.mk&apos;&quot;',['../troubleshooting.html#autotoc_md717',1,'']]],
  ['makefile_23',['Makefile',['../examples_memory_hirom_demo.html#autotoc_md1476',1,'1. Enable HiROM in the Makefile'],['../tutorial_sa1.html#autotoc_md334',1,'1. Enable SA-1 in Your Makefile'],['../tutorial_superfx.html#autotoc_md405',1,'1. Enable SuperFX in Your Makefile'],['../tutorial_sram.html#autotoc_md384',1,'1. Makefile'],['../examples_memory_save_game.html#autotoc_md1499',1,'4. Enable SRAM in the Makefile'],['../tools_smconv.html#autotoc_md521',1,'The flags behind the Makefile'],['../examples_fundamentals_text_glyphs.html#autotoc_md1197',1,'The Makefile'],['../examples_games_breakout.html#autotoc_md1222',1,'The Makefile'],['../examples_games_likemario.html#autotoc_md1248',1,'The Makefile'],['../examples_hdma_hdma_wave.html#autotoc_md1334',1,'The Makefile'],['../examples_scrolling_continuous_scroll.html#autotoc_md1574',1,'The Makefile']]],
  ['makefile_20and_20code_24',['🔴 &lt;span class=&quot;tt&quot;&gt;SRAM_SIZE&lt;/span&gt; mismatch between Makefile and code',['../tutorial_sram.html#autotoc_md394',1,'']]],
  ['makefile_20configuration_25',['Makefile Configuration',['../tutorial_audio.html#autotoc_md100',1,'']]],
  ['making_20non_20rectangular_20shapes_20with_20hdma_26',['Making Non-Rectangular Shapes with HDMA',['../examples_windows_window.html#autotoc_md1781',1,'']]],
  ['making_20your_20own_20level_27',['Making Your Own Level',['../examples_maps_tiled.html#autotoc_md1470',1,'']]],
  ['manifest_28',['The manifest',['../tools_palplan.html#autotoc_md510',1,'']]],
  ['manual_20counter_20recommended_29',['Manual Counter (Recommended)',['../tutorial_animation.html#autotoc_md73',1,'']]],
  ['manual_20setup_20the_20long_20way_30',['Manual setup (the long way)',['../getting_started.html#autotoc_md542',1,'']]],
  ['manual_20state_20machine_20under_20the_20hood_31',['The manual state machine (under the hood)',['../tutorial_game_states.html#autotoc_md186',1,'']]],
  ['many_20modules_32',['Why So Many Modules?',['../examples_games_likemario.html#autotoc_md1250',1,'']]],
  ['map_33',['Map',['../examples_maps_dynamic_map.html',1,'Dynamic Map'],['../snes_sound_guide.html#autotoc_md674',1,'Memory Map'],['../memory_map.html',1,'SNES Memory Map']]],
  ['map_34',['map',['../tutorial_map.html#autotoc_md255',1,'Collision against the map'],['../examples_mode7_perspective_rotate.html#autotoc_md1522',1,'Controls (krom&apos;s map)'],['../examples_games_rpg.html#autotoc_md1280',1,'Editing the map'],['../tutorial_sram.html#autotoc_md382',1,'Memory map'],['../examples_games_rpg.html',1,'rpg — an RPG template driven by a Tiled map']]],
  ['map_20—_20a_20deliberate_20overlap_35',['2. The VRAM Map — A Deliberate Overlap',['../examples_games_breakout.html#autotoc_md1208',1,'']]],
  ['map_20and_20objects_36',['Map and Objects',['../examples_games_mapandobjects.html',1,'examples_games']]],
  ['map_20and_20sprite_20system_37',['1. Initialize the Map and Sprite System',['../examples_games_mapandobjects.html#autotoc_md1263',1,'']]],
  ['map_20data_38',['3. Load Objects from Map Data',['../examples_games_mapandobjects.html#autotoc_md1265',1,'']]],
  ['map_20data_39',['tmx2snes — Tiled levels to SNES map data',['../tools_tmx2snes.html',1,'tools']]],
  ['map_20default_40',['LoROM Memory Map (Default)',['../memory_map.html#autotoc_md752',1,'']]],
  ['map_20editor_20integration_41',['Tiled Map Editor Integration',['../examples_maps_tiled.html',1,'examples_maps']]],
  ['map_20engine_42',['The Map Engine',['../examples_maps_slope_collision.html#autotoc_md1453',1,'']]],
  ['map_20engine_20and_20tile_20collision_43',['Map Engine and Tile Collision',['../examples_games_mapandobjects.html#autotoc_md1258',1,'']]],
  ['map_20engine_20streaming_44',['Map Engine Streaming',['../examples_maps_tiled.html#autotoc_md1464',1,'']]],
  ['map_20engine_20two_20phase_20update_45',['Map Engine Two-Phase Update',['../examples_maps_map_scroll.html#autotoc_md1444',1,'']]],
  ['map_20layout_46',['Collision Map Layout',['../examples_basics_collision_demo.html#autotoc_md1059',1,'']]],
  ['map_20module_20is_47',['What the map module is',['../tutorial_map.html#autotoc_md252',1,'']]],
  ['map_20scroll_48',['Map Scroll',['../examples_maps_map_scroll.html',1,'examples_maps']]],
  ['map_20streams_20m16_20background_20wants_20q16_49',['🟡 &lt;span class=&quot;tt&quot;&gt;map&lt;/span&gt; streams &lt;span class=&quot;tt&quot;&gt;.m16&lt;/span&gt;; &lt;span class=&quot;tt&quot;&gt;background&lt;/span&gt; wants &lt;span class=&quot;tt&quot;&gt;.q16&lt;/span&gt;',['../tutorial_map.html#autotoc_md261',1,'']]],
  ['mapload_20must_20run_20before_20setscreenon_50',['🔴 &lt;span class=&quot;tt&quot;&gt;mapLoad()&lt;/span&gt; must run before &lt;span class=&quot;tt&quot;&gt;setScreenOn()&lt;/span&gt;',['../tutorial_map.html#autotoc_md259',1,'']]],
  ['mappers_51',['Memory &amp;amp; mappers',['../examples_by_category.html#autotoc_md599',1,'']]],
  ['mapping_52',['HiROM Demo -- Understanding SNES Memory Mapping',['../examples_memory_hirom_demo.html',1,'examples_memory']]],
  ['mapping_20rules_53',['Mapping rules',['../tools_aseprite2snes.html#autotoc_md491',1,'']]],
  ['maps_54',['Maps',['../examples_maps.html',1,'Maps'],['../examples_by_category.html#autotoc_md595',1,'Maps'],['../group__examples.html#autotoc_md1802',1,'Maps']]],
  ['maps_55',['maps',['../tools_gfx4snes.html',1,'gfx4snes — images to tiles, palettes &amp; maps'],['../tutorial_map.html',1,'Scrolling maps']]],
  ['maps_20and_20complete_20projects_56',['Level 5 &amp;ndash; Maps and Complete Projects',['../examples.html#autotoc_md1553',1,'']]],
  ['mapupdate_20does_20not_57',['🟠 &lt;span class=&quot;tt&quot;&gt;mapVblank()&lt;/span&gt; belongs in VBlank, &lt;span class=&quot;tt&quot;&gt;mapUpdate()&lt;/span&gt; does not',['../tutorial_map.html#autotoc_md260',1,'']]],
  ['mapvblank_20belongs_20in_20vblank_20mapupdate_20does_20not_58',['🟠 &lt;span class=&quot;tt&quot;&gt;mapVblank()&lt;/span&gt; belongs in VBlank, &lt;span class=&quot;tt&quot;&gt;mapUpdate()&lt;/span&gt; does not',['../tutorial_map.html#autotoc_md260',1,'']]],
  ['mario_59',['Slope Mario',['../examples_maps_slope_collision.html',1,'examples_maps']]],
  ['masking_60',['Masking',['../examples_windows_window.html',1,'Window -- HDMA Triangle Masking'],['../examples_windows_transparent_window.html#autotoc_md1769',1,'Window for Color Math (Not for BG Masking)']]],
  ['masking_20tutorial_61',['Window Masking Tutorial',['../tutorial_window.html',1,'index']]],
  ['match_20base_5ftile_20stride_20to_20how_20the_20sheet_20was_20converted_62',['🟡 Match &lt;span class=&quot;tt&quot;&gt;base_tile&lt;/span&gt;/&lt;span class=&quot;tt&quot;&gt;stride&lt;/span&gt; to how the sheet was converted',['../tutorial_panel.html#autotoc_md328',1,'']]],
  ['match_20the_20sprite_20size_63',['Converting a sheet: &lt;span class=&quot;tt&quot;&gt;-s&lt;/span&gt; must match the sprite size',['../tutorial_sprites.html#autotoc_md372',1,'']]],
  ['math_64',['math',['../tutorial_window.html#autotoc_md434',1,'🟠 &lt;span class=&quot;tt&quot;&gt;windowEnable(window, WINDOW_MATH)&lt;/span&gt; is the gate to colour math'],['../examples_mode7_perspective.html#autotoc_md1514',1,'2. Perspective math'],['../tutorial_colormath.html#autotoc_md140',1,'The minimum viable colour math']]],
  ['math_20—_20examples_20windows_20transparent_5fwindow_65',['Window + colour math — &lt;span class=&quot;tt&quot;&gt;examples/windows/transparent_window&lt;/span&gt;',['../tutorial_window.html#autotoc_md431',1,'']]],
  ['math_20actually_20is_66',['What colour math actually is',['../tutorial_colormath.html#autotoc_md138',1,'']]],
  ['math_20configuration_67',['Math Configuration',['../examples_color_transparency.html#autotoc_md1167',1,'Color Math Configuration'],['../examples_windows_transparent_window.html#autotoc_md1771',1,'Color Math Configuration']]],
  ['math_20depends_20on_20palette_68',['🟡 OBJ math depends on palette',['../tutorial_colormath.html#autotoc_md153',1,'']]],
  ['math_20hardware_69',['Math Hardware',['../registers.html#autotoc_md832',1,'']]],
  ['math_20hdma_70',['Transparent Window -- Color Math + HDMA',['../examples_windows_transparent_window.html',1,'examples_windows']]],
  ['math_20mechanics_71',['Game math &amp;amp; mechanics',['../examples_by_category.html#autotoc_md597',1,'']]],
  ['math_20not_20for_20bg_20masking_72',['Window for Color Math (Not for BG Masking)',['../examples_windows_transparent_window.html#autotoc_md1769',1,'']]],
  ['math_20not_20palette_20edits_73',['Hit flash — color math, not palette edits',['../craft_game_feel.html#autotoc_md463',1,'']]],
  ['math_20on_20the_20backdrop_74',['🟡 Colour-math on the backdrop',['../tutorial_colormath.html#autotoc_md151',1,'']]],
  ['math_20runs_20after_20windowing_75',['🟡 Colour math runs after windowing',['../tutorial_colormath.html#autotoc_md152',1,'']]],
  ['math_20tutorial_76',['Math Tutorial',['../tutorial_colormath.html',1,'Colour Math Tutorial'],['../tutorial_math.html',1,'Fixed-Point Math Tutorial']]],
  ['math_20window_20vs_20bg_20window_77',['Color Math Window vs BG Window',['../examples_windows_transparent_window.html#autotoc_md1773',1,'']]],
  ['math_20works_78',['How Color Math Works',['../colormath_8h.html#autotoc_md18',1,'']]],
  ['math_3a_20main_20screen_20sub_20screen_79',['Color Math: Main Screen + Sub Screen',['../examples_color_transparency.html#autotoc_md1165',1,'']]],
  ['matrix_20and_20the_20registers_80',['The matrix and the registers',['../tutorial_mode7.html#autotoc_md288',1,'']]],
  ['matrix_20every_20frame_81',['3. Update the matrix every frame',['../examples_mode7_rotate_scale.html#autotoc_md1538',1,'']]],
  ['matrix_20per_20line_20—_20examples_20mode7_20perspective_5frotate_82',['Full Mode 7 matrix per line — &lt;span class=&quot;tt&quot;&gt;examples/mode7/perspective_rotate&lt;/span&gt;',['../tutorial_hdma.html#autotoc_md226',1,'']]],
  ['matrix_20per_20scanline_83',['Mode 7 rotating perspective — the full matrix, per scanline',['../examples_mode7_perspective_rotate.html',1,'examples_mode7']]],
  ['matrix_3a_20rotating_20perspective_84',['Per-scanline matrix: rotating perspective',['../tutorial_mode7.html#autotoc_md307',1,'']]],
  ['matters_85',['Why Seed Matters',['../examples_basics_random.html#autotoc_md1085',1,'']]],
  ['matters_86',['🟡 Repeat-mode discipline matters',['../tutorial_hdma.html#autotoc_md232',1,'']]],
  ['matters_20for_20your_20game_87',['matters for your game',['../examples_backgrounds_mode2.html#autotoc_md1023',1,'Why it matters for your game'],['../examples_basics_game_skeleton.html#autotoc_md1070',1,'Why it matters for your game'],['../examples_basics_panel_hud.html#autotoc_md1076',1,'Why it matters for your game'],['../examples_color_palette_cycle.html#autotoc_md1146',1,'Why it matters for your game'],['../examples_color_shadow_tint.html#autotoc_md1154',1,'Why it matters for your game'],['../examples_sprites_sprite_swarm.html#autotoc_md1690',1,'Why it matters for your game']]],
  ['mdmaen_20general_20dma_20enable_88',['$420B - MDMAEN (General DMA Enable)',['../registers.html#autotoc_md836',1,'']]],
  ['mean_20here_89',['What &quot;main&quot; and &quot;sub&quot; mean here',['../tutorial_colormath.html#autotoc_md139',1,'']]],
  ['meaning_20not_20just_20pixels_90',['A tile carries meaning, not just pixels',['../craft_tiles_to_levels.html#autotoc_md483',1,'']]],
  ['measured_20not_20assumed_91',['measured not assumed',['../examples_hdma_hdma_indirect_gradient.html#autotoc_md1313',1,'Fidelity to the original (measured, not assumed)'],['../examples_hdma_hdma_wave_table.html#autotoc_md1340',1,'Fidelity to the original (measured, not assumed)']]],
  ['measured_20parity_20luna_20v1_209_200_92',['Measured parity (luna v1.9.0)',['../examples_mode7_perspective_rotate.html#autotoc_md1525',1,'']]],
  ['measured_20parity_20luna_20v1_209_200_20mesen2_20cross_20check_93',['Measured parity (luna v1.9.0 + Mesen2 cross-check)',['../examples_color_hicolor_1792.html#autotoc_md1141',1,'']]],
  ['mechanics_94',['Game math &amp;amp; mechanics',['../examples_by_category.html#autotoc_md597',1,'']]],
  ['memory_95',['Memory',['../memory_map.html#autotoc_md762',1,'Enhancement Chip Memory'],['../memory_map.html#autotoc_md761',1,'Example: Setting Up Memory'],['../code_style.html#autotoc_md613',1,'Memory'],['../group__examples.html#autotoc_md1803',1,'Memory'],['../memory_map.html#autotoc_md756',1,'OAM (Object Attribute Memory)'],['../examples_sprites_simple_sprite.html#autotoc_md1670',1,'OAM (Object Attribute Memory)'],['../registers.html#autotoc_md804',1,'OAM (Sprite Memory)'],['../oam.html',1,'SNES OAM (Object Attribute Memory)']]],
  ['memory_20architecture_96',['Memory Architecture',['../tutorial_sa1.html#autotoc_md331',1,'']]],
  ['memory_20budget_2064kb_20total_97',['Memory Budget (64KB total)',['../snes_sound_guide.html#autotoc_md703',1,'']]],
  ['memory_20examples_98',['Memory Examples',['../examples_memory.html',1,'examples']]],
  ['memory_20issues_99',['Memory Issues',['../troubleshooting.html#autotoc_md733',1,'']]],
  ['memory_20layout_100',['Memory Layout',['../examples_audio_snesmod_music.html#autotoc_md906',1,'']]],
  ['memory_20layout_20lorom_101',['Memory Layout (LoROM)',['../sram_8h.html#autotoc_md63',1,'']]],
  ['memory_20map_102',['Memory Map',['../snes_sound_guide.html#autotoc_md674',1,'Memory Map'],['../memory_map.html',1,'SNES Memory Map']]],
  ['memory_20map_103',['Memory map',['../tutorial_sram.html#autotoc_md382',1,'']]],
  ['memory_20map_20default_104',['LoROM Memory Map (Default)',['../memory_map.html#autotoc_md752',1,'']]],
  ['memory_20mappers_105',['Memory &amp;amp; mappers',['../examples_by_category.html#autotoc_md599',1,'']]],
  ['memory_20mapping_106',['HiROM Demo -- Understanding SNES Memory Mapping',['../examples_memory_hirom_demo.html',1,'examples_memory']]],
  ['memory_20regions_107',['Key Memory Regions',['../memory_map.html#autotoc_md753',1,'']]],
  ['memory_20systems_108',['Memory Systems',['../snes_graphics_guide.html#autotoc_md626',1,'']]],
  ['memory_20usage_109',['Memory Usage',['../snesmod_8h.html#autotoc_md58',1,'Memory Usage'],['../tutorial_audio.html#autotoc_md109',1,'Memory Usage'],['../snes_sound_guide.html#autotoc_md694',1,'Memory Usage']]],
  ['memset_20not_20a_20write_20protect_110',['🟡 &lt;span class=&quot;tt&quot;&gt;sramClear&lt;/span&gt; is a memset, not a write-protect',['../tutorial_sram.html#autotoc_md399',1,'']]],
  ['menu_20navigation_111',['Menu Navigation',['../tutorial_input.html#autotoc_md247',1,'']]],
  ['mesen_20debugger_20alternative_112',['Using Mesen Debugger (alternative)',['../troubleshooting.html#autotoc_md739',1,'']]],
  ['mesen2_113',['Debugging in Mesen2',['../tutorial_sa1.html#autotoc_md346',1,'']]],
  ['mesen2_20cross_20check_114',['Measured parity (luna v1.9.0 + Mesen2 cross-check)',['../examples_color_hicolor_1792.html#autotoc_md1141',1,'']]],
  ['mesen2_20is_20still_20for_115',['What Mesen2 is still for',['../tutorial_debugging.html#autotoc_md164',1,'']]],
  ['message_116',['6. Spelling the Message',['../examples_fundamentals_text_glyphs.html#autotoc_md1188',1,'']]],
  ['message_117',['Scroll a message',['../examples_text_scroll_message.html',1,'examples_text']]],
  ['messages_118',['Commit messages',['../contributing.html#autotoc_md1816',1,'']]],
  ['metasprite_119',['Metasprite',['../examples_sprites_metasprite.html',1,'examples_sprites']]],
  ['metasprite_20engine_120',['Dynamic Metasprite Engine',['../examples_sprites_dynamic_metasprite.html',1,'examples_sprites']]],
  ['metaspriteitem_20structure_121',['MetaspriteItem Structure',['../examples_sprites_metasprite.html#autotoc_md1651',1,'']]],
  ['metasprites_122',['Metasprites',['../snes_graphics_guide.html#autotoc_md642',1,'']]],
  ['metatile_20is_20the_20word_123',['The tile is the atom; the metatile is the word',['../craft_tiles_to_levels.html#autotoc_md482',1,'']]],
  ['mhz_124',['The CPU budget: ~3.58 MHz',['../craft_frame_budget.html#autotoc_md459',1,'']]],
  ['mid_20frame_125',['Mode Switching Mid-Frame',['../examples_mode7_perspective.html#autotoc_md1517',1,'']]],
  ['mini_20game_126',['mode7_racing — an F-Zero-style mini game',['../examples_games_mode7_racing.html',1,'examples_games']]],
  ['minimum_20viable_20colour_20math_127',['The minimum viable colour math',['../tutorial_colormath.html#autotoc_md140',1,'']]],
  ['minimum_20viable_20dialog_20box_128',['The minimum viable dialog box',['../tutorial_panel.html#autotoc_md323',1,'']]],
  ['minimum_20viable_20mosaic_129',['The minimum viable mosaic',['../tutorial_mosaic.html#autotoc_md309',1,'']]],
  ['minimum_20viable_20save_130',['The minimum viable save',['../tutorial_sram.html#autotoc_md387',1,'']]],
  ['minimum_20viable_20scroller_131',['The minimum viable scroller',['../tutorial_map.html#autotoc_md254',1,'']]],
  ['minimum_20viable_20window_132',['The minimum viable window',['../tutorial_window.html#autotoc_md422',1,'']]],
  ['mirror_133',['OBJ_FLIPX &amp;ndash; Hardware Horizontal Mirror',['../examples_sprites_animated_sprite.html#autotoc_md1620',1,'']]],
  ['mismatch_20between_20makefile_20and_20code_134',['🔴 &lt;span class=&quot;tt&quot;&gt;SRAM_SIZE&lt;/span&gt; mismatch between Makefile and code',['../tutorial_sram.html#autotoc_md394',1,'']]],
  ['missing_3a_20pow_20exp_20log_135',['What&apos;s still missing: &lt;span class=&quot;tt&quot;&gt;pow&lt;/span&gt;, &lt;span class=&quot;tt&quot;&gt;exp&lt;/span&gt;, &lt;span class=&quot;tt&quot;&gt;log&lt;/span&gt;',['../tutorial_math.html#autotoc_md284',1,'']]],
  ['mixed_20scroll_136',['Mixed Scroll',['../examples_scrolling_mixed_scroll.html',1,'examples_scrolling']]],
  ['mixed_20scroll_20static_20moving_20layers_137',['Mixed Scroll (Static + Moving Layers)',['../tutorial_scrolling.html#autotoc_md354',1,'']]],
  ['mk_138',['&quot;OPENSNES not defined&quot; or &quot;No rule to make target &apos;common.mk&apos;&quot;',['../troubleshooting.html#autotoc_md717',1,'']]],
  ['mode_139',['Mode',['../registers.html#autotoc_md808',1,'$2105 - BGMODE (Background Mode)'],['../examples_backgrounds_mode1.html#autotoc_md969',1,'1. Configure Video Mode'],['../registers.html#autotoc_md807',1,'Background Mode'],['../hdma_8h.html#autotoc_md35',1,'IMPORTANT: Scroll Registers Require Repeat Mode'],['../examples_hdma_gradient_colors.html#autotoc_md1306',1,'Non-Repeat vs Repeat Mode']]],
  ['mode_140',['mode',['../examples_sprites_sprite_sizes.html#autotoc_md1681',1,'3. Two sprites per mode'],['../craft_planning.html#autotoc_md475',1,'The cost side: tiles by mode']]],
  ['mode_200_20—_204_20layer_202bpp_20background_141',['Mode 0 — 4-Layer 2bpp Background',['../examples_backgrounds_mode0.html',1,'examples_backgrounds']]],
  ['mode_200_20palette_142',['Mode 0 Palette',['../examples_text.html#autotoc_md1706',1,'']]],
  ['mode_201_143',['Mode 1',['../examples_sprites_sprite_sizes.html#autotoc_md1679',1,'1. Set up text on BG1 (4bpp in Mode 1)'],['../examples_backgrounds_mode1_bg3_priority.html#autotoc_md1003',1,'BG3 is 2bpp in Mode 1'],['../examples_backgrounds_mode1.html#autotoc_md966',1,'Games Using Mode 1'],['../snes_graphics_guide.html#autotoc_md647',1,'Recommended Layout (Mode 1)']]],
  ['mode_201_20bg3_20high_20priority_20hud_20layer_20over_20backgrounds_144',['Mode 1 BG3 High Priority -- HUD Layer Over Backgrounds',['../examples_backgrounds_mode1_bg3_priority.html',1,'examples_backgrounds']]],
  ['mode_201_20example_145',['Mode 1 Example',['../examples_backgrounds_mode1.html',1,'examples_backgrounds']]],
  ['mode_201_20lz77_146',['Mode 1 LZ77',['../examples_backgrounds_mode1_lz77.html',1,'examples_backgrounds']]],
  ['mode_201_20overview_147',['Mode 1 Overview',['../examples_backgrounds_mode1.html#autotoc_md965',1,'']]],
  ['mode_201_20priorities_148',['Mode 1 Priorities',['../examples_backgrounds_mode1.html#autotoc_md989',1,'']]],
  ['mode_201_20priority_20system_149',['Mode 1 Priority System',['../examples_backgrounds_mode1_bg3_priority.html#autotoc_md1002',1,'']]],
  ['mode_201_20setup_20recommended_150',['Mode 1 Setup (Recommended)',['../snes_graphics_guide.html#autotoc_md629',1,'']]],
  ['mode_201_20with_20bg1_20bg2_151',['3. Enable Mode 1 with BG1 + BG2',['../examples_scrolling_mixed_scroll.html#autotoc_md1590',1,'']]],
  ['mode_201_20with_20bg3_20priority_20high_152',['Mode 1 with BG3 Priority High',['../examples_color_transparency.html#autotoc_md1166',1,'']]],
  ['mode_201_20with_20multiple_20backgrounds_153',['Mode 1 with Multiple Backgrounds',['../examples_scrolling_mixed_scroll.html#autotoc_md1582',1,'']]],
  ['mode_203_20—_20256_20color_20background_154',['Mode 3 — 256-Color Background',['../examples_backgrounds_mode3.html',1,'examples_backgrounds']]],
  ['mode_203_202reg_5f2x_155',['HDMA Mode 3 (2REG_2X)',['../examples_hdma_gradient_colors.html#autotoc_md1305',1,'']]],
  ['mode_203_20and_208bpp_20tiles_156',['Mode 3 and 8bpp Tiles',['../examples_maps_dynamic_map.html#autotoc_md1433',1,'']]],
  ['mode_205_20—_20hi_20res_20512×256_20background_157',['Mode 5 — Hi-Res 512×256 Background',['../examples_backgrounds_mode5.html',1,'examples_backgrounds']]],
  ['mode_205_20interlace_20512_20×_20448_158',['Hi-res text — BG Mode 5 + interlace (512 × 448)',['../examples_backgrounds_mode5_hires.html',1,'examples_backgrounds']]],
  ['mode_207_159',['Mode 7',['../examples_mode7.html',1,'Mode 7'],['../examples_by_category.html#autotoc_md581',1,'Mode 7']]],
  ['mode_207_20actually_20is_160',['What Mode 7 actually is',['../tutorial_mode7.html#autotoc_md287',1,'']]],
  ['mode_207_20matrix_20per_20line_20—_20examples_20mode7_20perspective_5frotate_161',['Full Mode 7 matrix per line — &lt;span class=&quot;tt&quot;&gt;examples/mode7/perspective_rotate&lt;/span&gt;',['../tutorial_hdma.html#autotoc_md226',1,'']]],
  ['mode_207_20needs_20dmacopyvrammode7_20not_20dmacopyvram_162',['🟡 Mode 7 needs &lt;span class=&quot;tt&quot;&gt;dmaCopyVramMode7&lt;/span&gt;, not &lt;span class=&quot;tt&quot;&gt;dmaCopyVram&lt;/span&gt;',['../tutorial_dma.html#autotoc_md180',1,'']]],
  ['mode_207_20perspective_20pseudo_203d_20ground_20effect_163',['Mode 7 Perspective -- Pseudo-3D Ground Effect',['../examples_mode7_perspective.html',1,'examples_mode7']]],
  ['mode_207_20registers_20share_20one_20write_20twice_20latch_164',['🟡 BG1 scroll and the Mode 7 registers share one write-twice latch',['../tutorial_mode7.html#autotoc_md298',1,'']]],
  ['mode_207_20rotating_20perspective_20—_20the_20full_20matrix_20per_20scanline_165',['Mode 7 rotating perspective — the full matrix, per scanline',['../examples_mode7_perspective_rotate.html',1,'examples_mode7']]],
  ['mode_207_20rotation_20and_20scaling_166',['Mode 7 -- Rotation and Scaling',['../examples_mode7_rotate_scale.html',1,'examples_mode7']]],
  ['mode_207_20tutorial_167',['Mode 7 Tutorial',['../tutorial_mode7.html',1,'index']]],
  ['mode_207_20unusual_168',['🟠 Mosaic + Mode 7 = unusual',['../tutorial_mosaic.html#autotoc_md315',1,'']]],
  ['mode_207_20vram_20format_169',['1. Mode 7 VRAM format',['../examples_mode7_rotate_scale.html#autotoc_md1536',1,'']]],
  ['mode_207_20vram_20layout_170',['Mode 7 VRAM Layout',['../mode7_8h.html#autotoc_md48',1,'']]],
  ['mode_207_20writes_20shared_20latch_171',['🟡 HDMA on BG1 scroll can corrupt Mode 7 writes (shared latch)',['../tutorial_hdma.html#autotoc_md233',1,'']]],
  ['mode_20and_20saturation_20interact_172',['🟠 Half-mode and saturation interact',['../tutorial_colormath.html#autotoc_md150',1,'']]],
  ['mode_20discipline_20matters_173',['🟡 Repeat-mode discipline matters',['../tutorial_hdma.html#autotoc_md232',1,'']]],
  ['mode_20from_20your_20genre_174',['Choose a background mode from your genre',['../craft_planning.html#autotoc_md474',1,'']]],
  ['mode_20switching_20mid_20frame_175',['Mode Switching Mid-Frame',['../examples_mode7_perspective.html#autotoc_md1517',1,'']]],
  ['mode2_20—_20offset_20per_20tile_3a_20per_20column_20scroll_20from_20bg3_176',['mode2 — offset-per-tile: per-column scroll from BG3',['../examples_backgrounds_mode2.html',1,'examples_backgrounds']]],
  ['mode7_20perspective_177',['F-Zero perspective via HDMA — &lt;span class=&quot;tt&quot;&gt;examples/mode7/perspective&lt;/span&gt;',['../tutorial_mode7.html#autotoc_md296',1,'']]],
  ['mode7_20perspective_5frotate_178',['Full Mode 7 matrix per line — &lt;span class=&quot;tt&quot;&gt;examples/mode7/perspective_rotate&lt;/span&gt;',['../tutorial_hdma.html#autotoc_md226',1,'']]],
  ['mode7_20rotate_5fscale_179',['Basic rotation + scaling — &lt;span class=&quot;tt&quot;&gt;examples/mode7/rotate_scale&lt;/span&gt;',['../tutorial_mode7.html#autotoc_md295',1,'']]],
  ['mode7_5fflying_20—_20a_20pilotwings_20style_20demo_180',['mode7_flying — a Pilotwings-style demo',['../examples_games_mode7_flying.html',1,'examples_games']]],
  ['mode7_5fracing_20—_20an_20f_20zero_20style_20mini_20game_181',['mode7_racing — an F-Zero-style mini game',['../examples_games_mode7_racing.html',1,'examples_games']]],
  ['mode7_5ftransparent_20shows_20the_20backdrop_20not_20a_20layer_182',['🟡 Out-of-bounds with &lt;span class=&quot;tt&quot;&gt;MODE7_TRANSPARENT&lt;/span&gt; shows the backdrop, not a layer',['../tutorial_mode7.html#autotoc_md304',1,'']]],
  ['mode7loadgraphics_20helper_20today_183',['🔴 Interleaved VRAM, no &lt;span class=&quot;tt&quot;&gt;mode7LoadGraphics&lt;/span&gt; helper today',['../tutorial_mode7.html#autotoc_md300',1,'']]],
  ['modes_184',['Modes',['../hardware_overview.html#autotoc_md793',1,'Background Modes'],['../examples_sprites_sprite_sizes.html',1,'Object Size -- All 6 SNES Sprite Size Modes'],['../tutorial_graphics.html#autotoc_md200',1,'SNES Video Modes'],['../examples_sprites_sprite_sizes.html#autotoc_md1682',1,'The 6 Size Modes'],['../snes_graphics_guide.html#autotoc_md628',1,'Video Modes']]],
  ['modes_185',['modes',['../tutorial_dma.html#autotoc_md168',1,'The 8 transfer modes'],['../tutorial_hdma.html#autotoc_md214',1,'Transfer modes']]],
  ['modes_205_206_20setini_186',['Hi-res and interlace (Modes 5/6, SETINI)',['../tutorial_graphics.html#autotoc_md210',1,'']]],
  ['modes_20register_20_242101_187',['OBJ Size Modes (Register $2101)',['../examples_sprites_metasprite.html#autotoc_md1650',1,'']]],
  ['modes_20when_20adsr_20disabled_188',['GAIN Modes (when ADSR disabled)',['../snes_sound_guide.html#autotoc_md690',1,'']]],
  ['modulation_189',['pitch_mod — hardware vibrato via pitch modulation',['../examples_audio_pitch_mod.html',1,'examples_audio']]],
  ['module_190',['The scene stack (recommended) — &lt;span class=&quot;tt&quot;&gt;scene&lt;/span&gt; module',['../tutorial_game_states.html#autotoc_md185',1,'']]],
  ['module_20is_191',['What the map module is',['../tutorial_map.html#autotoc_md252',1,'']]],
  ['module_20recommended_192',['The anim Module (Recommended)',['../tutorial_animation.html#autotoc_md70',1,'']]],
  ['module_20v2_20—_20samples_20and_20effects_20from_20pure_20c_193',['The audio module (v2) — samples and effects from pure C',['../tutorial_audio.html#autotoc_md113',1,'']]],
  ['modules_194',['Modules',['../examples_audio_snesmod_music.html#autotoc_md912',1,'Exercise 2: Multiple Modules'],['../examples_backgrounds_mode0.html#autotoc_md957',1,'Modules'],['../examples_backgrounds_mode1_lz77.html#autotoc_md1022',1,'Modules'],['../examples_backgrounds_mode3.html#autotoc_md1032',1,'Modules'],['../examples_backgrounds_mode5.html#autotoc_md1036',1,'Modules'],['../examples_games_tetris.html#autotoc_md1294',1,'Modules'],['../examples_hdma_hdma_helpers.html#autotoc_md1311',1,'Modules'],['../examples_games_likemario.html#autotoc_md1250',1,'Why So Many Modules?'],['../examples_fundamentals_text_glyphs.html#autotoc_md1198',1,'Why These Modules?'],['../examples_games_breakout.html#autotoc_md1225',1,'Why These Modules?'],['../examples_hdma_hdma_wave.html#autotoc_md1336',1,'Why These Modules?'],['../examples_scrolling_continuous_scroll.html#autotoc_md1575',1,'Why These Modules?']]],
  ['modules_20to_20snesmod_20soundbanks_195',['smconv — tracker modules to SNESMOD soundbanks',['../tools_smconv.html',1,'tools']]],
  ['modules_20used_196',['Modules Used',['../examples_audio_apu_switch.html#autotoc_md860',1,'Modules Used'],['../examples_audio_pitch_mod.html#autotoc_md870',1,'Modules Used'],['../examples_audio_play_noise.html#autotoc_md873',1,'Modules Used'],['../examples_audio_sfx_from_wav.html#autotoc_md879',1,'Modules Used'],['../examples_audio_snesmod_music_large.html#autotoc_md933',1,'Modules Used'],['../examples_audio_soundboard.html#autotoc_md949',1,'Modules Used'],['../examples_audio_speech_synth.html#autotoc_md953',1,'Modules Used'],['../examples_backgrounds_mode5_hires.html#autotoc_md1042',1,'Modules Used'],['../examples_basics_aim_target.html#autotoc_md1048',1,'Modules Used'],['../examples_basics_fix32_orbit.html#autotoc_md1068',1,'Modules Used'],['../examples_basics_random.html#autotoc_md1087',1,'Modules Used'],['../examples_basics_scene_stack.html#autotoc_md1099',1,'Modules Used'],['../examples_basics_timer.html#autotoc_md1105',1,'Modules Used'],['../examples_chips_dsp1_cube.html#autotoc_md1110',1,'Modules Used'],['../examples_chips_sa1_hello.html#autotoc_md1116',1,'Modules Used'],['../examples_chips_sa1_starfield.html#autotoc_md1120',1,'Modules Used'],['../examples_chips_superfx_3d.html#autotoc_md1126',1,'Modules Used'],['../examples_chips_superfx_hello.html#autotoc_md1131',1,'Modules Used'],['../examples_color_direct_color.html#autotoc_md1134',1,'Modules Used'],['../examples_color_gradient_9bit.html#autotoc_md1138',1,'Modules Used'],['../examples_color_hicolor_1792.html#autotoc_md1144',1,'Modules Used'],['../examples_color_hicolor_blend.html#autotoc_md1145',1,'Modules Used'],['../examples_games_mode7_flying.html#autotoc_md1272',1,'Modules Used'],['../examples_games_mode7_racing.html#autotoc_md1275',1,'Modules Used'],['../examples_games_rpg.html#autotoc_md1282',1,'Modules Used'],['../examples_games_shmup_1942.html#autotoc_md1289',1,'Modules Used'],['../examples_hdma_hdma_indirect_gradient.html#autotoc_md1316',1,'Modules Used'],['../examples_hdma_hdma_wave_table.html#autotoc_md1343',1,'Modules Used'],['../examples_input_controller.html#autotoc_md1352',1,'Modules Used'],['../examples_maps_map_scroll.html#autotoc_md1447',1,'Modules Used'],['../examples_maps_tiled.html#autotoc_md1468',1,'Modules Used'],['../examples_mode7_perspective_rotate.html#autotoc_md1528',1,'Modules Used'],['../examples_sprites_aseprite_pipeline.html#autotoc_md1627',1,'Modules Used'],['../examples_sprites_dynamic_metasprite.html#autotoc_md1632',1,'Modules Used'],['../examples_windows_window_multi_hdma.html#autotoc_md1794',1,'Modules Used']]],
  ['modules_20used_197',['Modules used',['../examples_audio_echo.html#autotoc_md864',1,'Modules used'],['../examples_backgrounds_mode2.html#autotoc_md1027',1,'Modules used'],['../examples_basics_game_skeleton.html#autotoc_md1074',1,'Modules used'],['../examples_basics_panel_hud.html#autotoc_md1080',1,'Modules used'],['../examples_color_palette_cycle.html#autotoc_md1150',1,'Modules used'],['../examples_color_shadow_tint.html#autotoc_md1158',1,'Modules used'],['../examples_input_move_sprite.html#autotoc_md1371',1,'Modules used'],['../examples_sprites_sprite_swarm.html#autotoc_md1694',1,'Modules used'],['../examples_text_print_string.html#autotoc_md1699',1,'Modules used'],['../examples_text_scroll_message.html#autotoc_md1711',1,'Modules used']]],
  ['moment_198',['Write it at the right moment',['../craft_camera.html#autotoc_md454',1,'']]],
  ['more_20help_199',['Getting More Help',['../troubleshooting.html#autotoc_md736',1,'']]],
  ['more_20horsepower_20—_20the_20cartridge_20coprocessors_200',['More horsepower — the cartridge coprocessors',['../learning_path.html#autotoc_md569',1,'']]],
  ['more_20than_20layers_20can_20give_201',['When you need more than layers can give',['../craft_backgrounds.html#autotoc_md447',1,'']]],
  ['mosaic_202',['The minimum viable mosaic',['../tutorial_mosaic.html#autotoc_md309',1,'']]],
  ['mosaic_20actually_20is_203',['What mosaic actually is',['../tutorial_mosaic.html#autotoc_md308',1,'']]],
  ['mosaic_20block_20size_20is_20size_201_20pixels_204',['🟡 Mosaic block size is &quot;size + 1&quot; pixels',['../tutorial_mosaic.html#autotoc_md316',1,'']]],
  ['mosaic_20does_20not_20affect_20obj_20sprites_205',['🟠 Mosaic does not affect OBJ (sprites)',['../tutorial_mosaic.html#autotoc_md314',1,'']]],
  ['mosaic_20effect_20pixelation_206',['2. Mosaic effect (pixelation)',['../examples_transitions_mosaic.html#autotoc_md1753',1,'']]],
  ['mosaic_20mode_207_20unusual_207',['🟠 Mosaic + Mode 7 = unusual',['../tutorial_mosaic.html#autotoc_md315',1,'']]],
  ['mosaic_20ppu_20pixel_20block_20effect_208',['Mosaic -- PPU Pixel Block Effect',['../examples_transitions_mosaic.html',1,'examples_transitions']]],
  ['mosaic_20register_20_242106_209',['Mosaic Register ($2106)',['../examples_transitions_mosaic.html#autotoc_md1756',1,'']]],
  ['mosaic_20state_20is_20not_20reset_20by_20consoleinit_210',['🟡 Mosaic state is not reset by &lt;span class=&quot;tt&quot;&gt;consoleInit&lt;/span&gt;',['../tutorial_mosaic.html#autotoc_md318',1,'']]],
  ['mosaic_20tutorial_211',['Mosaic Tutorial',['../tutorial_mosaic.html',1,'index']]],
  ['mosaicfadein_20mosaicfadeout_20are_20blocking_212',['🟡 &lt;span class=&quot;tt&quot;&gt;mosaicFadeIn&lt;/span&gt; / &lt;span class=&quot;tt&quot;&gt;mosaicFadeOut&lt;/span&gt; are blocking',['../tutorial_mosaic.html#autotoc_md317',1,'']]],
  ['mosaicfadeout_20are_20blocking_213',['🟡 &lt;span class=&quot;tt&quot;&gt;mosaicFadeIn&lt;/span&gt; / &lt;span class=&quot;tt&quot;&gt;mosaicFadeOut&lt;/span&gt; are blocking',['../tutorial_mosaic.html#autotoc_md317',1,'']]],
  ['motion_214',['Parallax — depth from motion',['../craft_backgrounds.html#autotoc_md444',1,'']]],
  ['mouse_215',['Mouse',['../examples_input_mouse.html#autotoc_md1361',1,'1. Initialize Text and Detect Mouse'],['../examples_input_mouse.html',1,'SNES Mouse']]],
  ['mouse_20hardware_216',['SNES Mouse Hardware',['../examples_input_mouse.html#autotoc_md1356',1,'']]],
  ['mouse_20sensitivity_217',['Mouse Sensitivity',['../examples_input_mouse.html#autotoc_md1357',1,'']]],
  ['mouse_20update_20cursor_218',['4. Main Loop: Read Mouse, Update Cursor',['../examples_input_mouse.html#autotoc_md1364',1,'']]],
  ['move_20the_20pointer_219',['5. Animation = Just Move the Pointer',['../examples_hdma_hdma_wave.html#autotoc_md1326',1,'']]],
  ['movement_220',['Player Movement',['../examples_input_two_players.html#autotoc_md1403',1,'']]],
  ['movement_221',['Smooth sprite movement',['../tutorial_math.html#autotoc_md271',1,'']]],
  ['movement_20example_222',['Movement Example',['../tutorial_input.html#autotoc_md244',1,'']]],
  ['movement_20slide_20along_20walls_223',['Stopping Movement (Slide Along Walls)',['../tutorial_collision.html#autotoc_md130',1,'']]],
  ['movement_20with_20animation_224',['Movement with Animation',['../tutorial_sprites.html#autotoc_md376',1,'']]],
  ['moving_20layers_225',['Mixed Scroll (Static + Moving Layers)',['../tutorial_scrolling.html#autotoc_md354',1,'']]],
  ['mul16_226',['🟠 Compiler &lt;span class=&quot;tt&quot;&gt;*&lt;/span&gt; vs &lt;span class=&quot;tt&quot;&gt;mul16&lt;/span&gt;',['../tutorial_math.html#autotoc_md280',1,'']]],
  ['multi_20slot_20saves_227',['Multi-slot saves',['../tutorial_sram.html#autotoc_md388',1,'']]],
  ['multi_20window_20hdma_20—_20both_20windows_20animated_20per_20scanline_228',['Multi-window HDMA — both windows animated per scanline',['../examples_windows_window_multi_hdma.html',1,'examples_windows']]],
  ['multiple_20backgrounds_229',['Mode 1 with Multiple Backgrounds',['../examples_scrolling_mixed_scroll.html#autotoc_md1582',1,'']]],
  ['multiple_20bgs_230',['Simple Parallax (Multiple BGs)',['../tutorial_scrolling.html#autotoc_md356',1,'']]],
  ['multiple_20enemies_231',['Testing Multiple Enemies',['../tutorial_collision.html#autotoc_md121',1,'']]],
  ['multiple_20modules_232',['Exercise 2: Multiple Modules',['../examples_audio_snesmod_music.html#autotoc_md912',1,'']]],
  ['multiplier_20and_20divider_233',['Hardware multiplier and divider',['../tutorial_math.html#autotoc_md268',1,'']]],
  ['multiplier_20read_20timing_234',['🟡 Hardware multiplier read timing',['../tutorial_math.html#autotoc_md281',1,'']]],
  ['multiply_235',['$4202-$4203 - WRMPYA/B (Multiply)',['../registers.html#autotoc_md833',1,'']]],
  ['multitap_20support_236',['Multitap Support',['../examples_input_two_players.html#autotoc_md1426',1,'']]],
  ['murmuration_237',['SA-1 Starfield (Murmuration)',['../examples_chips_sa1_starfield.html',1,'examples_chips']]],
  ['music_238',['Music',['../examples_audio_snesmod_music.html#autotoc_md896',1,'Creating Music'],['../examples_audio_snesmod_music_large.html',1,'SNESMOD Large Soundbank Music'],['../examples_audio_snesmod_music.html#autotoc_md922',1,'Why Tracker-Based Music?']]],
  ['music_20example_239',['SNESMOD Music Example',['../examples_audio_snesmod_music.html',1,'examples_audio']]],
  ['music_20playback_240',['Basic Music Playback',['../tutorial_audio.html#autotoc_md101',1,'']]],
  ['music_20sfx_241',['Example: Music + SFX',['../tutorial_audio.html#autotoc_md108',1,'']]],
  ['music_20sounds_20wrong_242',['Music sounds wrong',['../examples_audio_snesmod_music.html#autotoc_md917',1,'']]],
  ['music_20tutorial_243',['Audio &amp;amp; Music Tutorial',['../tutorial_audio.html',1,'index']]],
  ['music_20with_20openmpt_244',['Creating Music with OpenMPT',['../tutorial_audio.html#autotoc_md104',1,'']]],
  ['must_20match_20the_20sprite_20size_245',['Converting a sheet: &lt;span class=&quot;tt&quot;&gt;-s&lt;/span&gt; must match the sprite size',['../tutorial_sprites.html#autotoc_md372',1,'']]],
  ['must_20run_20before_20setscreenon_246',['🔴 &lt;span class=&quot;tt&quot;&gt;mapLoad()&lt;/span&gt; must run before &lt;span class=&quot;tt&quot;&gt;setScreenOn()&lt;/span&gt;',['../tutorial_map.html#autotoc_md259',1,'']]],
  ['my_20setup_20even_20work_247',['Stage 0 — &quot;Does my setup even work?&quot;',['../learning_path.html#autotoc_md562',1,'']]]
];
