var searchData=
[
  ['c_0',['C',['../tutorial_sa1.html#autotoc_md347',1,'3. Initialize from C'],['../tutorial_superfx.html#autotoc_md419',1,'4. Launch from C'],['../examples_audio_soundboard.html',1,'soundboard — the audio v2 engine, driven entirely from C'],['../tutorial_audio.html#autotoc_md113',1,'The audio module (v2) — samples and effects from pure C']]],
  ['c_1',['Source (.c)',['../code_style.html#autotoc_md632',1,'']]],
  ['c_20code_2',['C Code',['../code_style.html#autotoc_md618',1,'']]],
  ['cache_20before_20hot_20loops_3',['4. CACHE Before Hot Loops',['../tutorial_superfx.html#autotoc_md425',1,'']]],
  ['calculation_4',['Pitch Calculation',['../snes_sound_guide.html#autotoc_md724',1,'']]],
  ['calculation_5',['4. Tile calculation',['../examples_sprites_animated_sprite.html#autotoc_md1629',1,'']]],
  ['calibration_20background_20bg2_6',['3. Calibration Background (BG2)',['../examples_input_superscope.html#autotoc_md1392',1,'']]],
  ['call_20snesmodprocess_7',['Important: Call snesmodProcess()!',['../tutorial_audio.html#autotoc_md107',1,'']]],
  ['callback_20in_20the_20nmi_20handler_8',['🟡 HDMA fires before the user callback in the NMI handler',['../tutorial_hdma.html#autotoc_md245',1,'']]],
  ['callback_20safe_9',['🟡 Not NMI-callback-safe',['../tutorial_dsp1.html#autotoc_md192',1,'']]],
  ['camera_10',['Following the player: the camera',['../craft_camera.html',1,'craft']]],
  ['camera_20is_20your_20scroll_20values_11',['The camera &lt;em&gt;is&lt;/em&gt; your scroll values',['../craft_camera.html#autotoc_md460',1,'']]],
  ['camera_20relative_20sprite_20positioning_12',['Camera-Relative Sprite Positioning',['../examples_maps_map_scroll.html#autotoc_md1456',1,'']]],
  ['camera_20to_20the_20player_20—_20deadzone_20it_13',['Don&apos;t glue the camera to the player — deadzone it',['../craft_camera.html#autotoc_md461',1,'']]],
  ['camps_14',['Why two camps?',['../oam.html#autotoc_md791',1,'']]],
  ['can_20corrupt_20mode_207_20writes_20shared_20latch_15',['🟡 HDMA on BG1 scroll can corrupt Mode 7 writes (shared latch)',['../tutorial_hdma.html#autotoc_md244',1,'']]],
  ['can_20finish_16',['Scope a first game you can finish',['../craft_planning.html#autotoc_md487',1,'']]],
  ['can_20give_17',['When you need more than layers can give',['../craft_backgrounds.html#autotoc_md458',1,'']]],
  ['can_20i_20build_20a_20world_18',['Stage 3 — &quot;Can I build a world?&quot;',['../learning_path.html#autotoc_md576',1,'']]],
  ['can_20i_20finish_20and_20ship_19',['Stage 6 — &quot;Can I finish and ship?&quot;',['../learning_path.html#autotoc_md579',1,'']]],
  ['can_20i_20hold_20it_20all_20together_20',['Stage 5 — &quot;Can I hold it all together?&quot;',['../learning_path.html#autotoc_md578',1,'']]],
  ['can_20i_20make_20it_20feel_20good_21',['Stage 4 — &quot;Can I make it feel good?&quot;',['../learning_path.html#autotoc_md577',1,'']]],
  ['can_20i_20put_20something_20on_20screen_22',['Stage 1 — &quot;Can I put something on screen?&quot;',['../learning_path.html#autotoc_md574',1,'']]],
  ['can_20t_20do_23',['What SA-1 Can&apos;t Do',['../tutorial_sa1.html#autotoc_md359',1,'']]],
  ['can_20the_20player_20act_24',['Stage 2 — &quot;Can the player act?&quot;',['../learning_path.html#autotoc_md575',1,'']]],
  ['cannot_20store_20pointers_20in_20sram_25',['🟠 Cannot store pointers in SRAM',['../tutorial_sram.html#autotoc_md407',1,'']]],
  ['capabilities_26',['Key Capabilities',['../snes_sound_guide.html#autotoc_md681',1,'']]],
  ['capstones_27',['Games (capstones)',['../examples_by_category.html#autotoc_md617',1,'']]],
  ['carries_20meaning_20not_20just_20pixels_28',['A tile carries meaning, not just pixels',['../craft_tiles_to_levels.html#autotoc_md494',1,'']]],
  ['cartridge_29',['Cartridge',['../memory_map.html#autotoc_md774',1,'SA-1 Cartridge'],['../memory_map.html#autotoc_md775',1,'SuperFX Cartridge']]],
  ['cartridge_20coprocessors_30',['More horsepower — the cartridge coprocessors',['../learning_path.html#autotoc_md580',1,'']]],
  ['categories_31',['Categories',['../examples.html#autotoc_md1558',1,'']]],
  ['category_32',['Browse Examples by Category',['../examples_by_category.html',1,'index']]],
  ['cc0_20public_20domain_33',['Free Asset Sources (CC0/Public Domain)',['../snes_graphics_guide.html#autotoc_md672',1,'']]],
  ['cc65816_20not_20found_34',['Empty &lt;span class=&quot;tt&quot;&gt;compiler/&lt;/span&gt; directories or &quot;cc65816 not found&quot;',['../troubleshooting.html#autotoc_md729',1,'']]],
  ['cc_3a_20command_20not_20found_35',['&quot;clang: command not found&quot; or &quot;cc: command not found&quot;',['../troubleshooting.html#autotoc_md731',1,'']]],
  ['ceiling_36',['sprite_swarm — a bouncing swarm, and the OAM throughput ceiling',['../examples_sprites_sprite_swarm.html',1,'examples_sprites']]],
  ['centre_37',['🟡 Centre default is the tilemap centre, not the screen centre',['../tutorial_mode7.html#autotoc_md314',1,'']]],
  ['centre_20default_20is_20the_20tilemap_20centre_20not_20the_20screen_20centre_38',['🟡 Centre default is the tilemap centre, not the screen centre',['../tutorial_mode7.html#autotoc_md314',1,'']]],
  ['centre_20not_20the_20screen_20centre_39',['🟡 Centre default is the tilemap centre, not the screen centre',['../tutorial_mode7.html#autotoc_md314',1,'']]],
  ['cgadd_20_242121_40',['1. HDMA targets CGADD ($2121)',['../examples_hdma_gradient_colors.html#autotoc_md1311',1,'']]],
  ['cgadd_20cgram_20address_41',['$2121 - CGADD (CGRAM Address)',['../registers.html#autotoc_md830',1,'']]],
  ['cgdata_20cgram_20data_20write_42',['$2122 - CGDATA (CGRAM Data Write)',['../registers.html#autotoc_md831',1,'']]],
  ['cgram_43',['CGRAM',['../registers.html#autotoc_md829',1,'Color (CGRAM)'],['../examples_color_palette_cycle.html',1,'palette_cycle — animate by rotating CGRAM']]],
  ['cgram_20—_20256_20colours_20split_20bg_20vs_20sprites_44',['2. CGRAM — 256 colours, split BG vs sprites',['../craft_planning.html#autotoc_md483',1,'']]],
  ['cgram_20address_45',['$2121 - CGADD (CGRAM Address)',['../registers.html#autotoc_md830',1,'']]],
  ['cgram_20color_20generator_20ram_46',['CGRAM (Color Generator RAM)',['../examples_hdma_gradient_colors.html#autotoc_md1315',1,'']]],
  ['cgram_20color_20ram_47',['CGRAM (Color RAM)',['../memory_map.html#autotoc_md768',1,'']]],
  ['cgram_20data_20write_48',['$2122 - CGDATA (CGRAM Data Write)',['../registers.html#autotoc_md831',1,'']]],
  ['cgram_20layout_20256_20colors_20×_202_20bytes_49',['CGRAM Layout (256 colors × 2 bytes)',['../snes_graphics_guide.html#autotoc_md662',1,'']]],
  ['cgram_20oam_20writes_20are_20safe_50',['When VRAM/CGRAM/OAM writes are safe',['../tutorial_dma.html#autotoc_md170',1,'']]],
  ['cgram_20oam_20writes_20outside_20vblank_20or_20force_20blank_20are_20silently_20dropped_51',['🔴 VRAM/CGRAM/OAM writes outside VBlank or force blank are silently dropped',['../tutorial_dma.html#autotoc_md175',1,'']]],
  ['cgram_20split_52',['CGRAM Split',['../examples_sprites_simple_sprite.html#autotoc_md1682',1,'']]],
  ['change_20palette_53',['Exercise 2: Change Palette',['../examples_backgrounds_mode1.html#autotoc_md995',1,'']]],
  ['changes_54',['Input and State Changes',['../tutorial_animation.html#autotoc_md80',1,'']]],
  ['changes_20—_20fades_20and_20dissolves_55',['Punctuate scene changes — fades and dissolves',['../craft_game_feel.html#autotoc_md476',1,'']]],
  ['changing_20frame_20ids_56',['4. Animate by changing frame IDs',['../examples_sprites_dynamic_sprite.html#autotoc_md1652',1,'']]],
  ['channel_57',['4. Setting Up the HDMA Channel',['../examples_hdma_hdma_wave.html#autotoc_md1336',1,'']]],
  ['channel_200_58',['🟠 Channel 0 vs HDMA on channel 0',['../tutorial_dma.html#autotoc_md178',1,'']]],
  ['channel_200_20vs_20hdma_20on_20channel_200_59',['🟠 Channel 0 vs HDMA on channel 0',['../tutorial_dma.html#autotoc_md178',1,'']]],
  ['channel_207_20is_20reserved_20for_20oam_20dma_60',['🔴 Channel 7 is reserved for OAM DMA',['../tutorial_hdma.html#autotoc_md241',1,'']]],
  ['channel_20configuration_61',['Channel Configuration',['../registers.html#autotoc_md851',1,'']]],
  ['channel_20registers_62',['The four channel registers',['../tutorial_hdma.html#autotoc_md224',1,'']]],
  ['channel_20split_20blend_63',['&quot;3840 colors&quot; — RGB channel-split blend',['../examples_color_hicolor_blend.html',1,'examples_color']]],
  ['channels_64',['The DMA channels',['../tutorial_dma.html#autotoc_md167',1,'']]],
  ['channels_20one_20visual_20—_20examples_20color_20gradient_5f9bit_65',['Two channels, one visual — &lt;span class=&quot;tt&quot;&gt;examples/color/gradient_9bit&lt;/span&gt;',['../tutorial_hdma.html#autotoc_md238',1,'']]],
  ['channels_20you_20haven_20t_20configured_66',['🟡 Don&apos;t enable channels you haven&apos;t configured',['../tutorial_hdma.html#autotoc_md246',1,'']]],
  ['chantier_20—_20s6_20hud_20on_20bg3_67',['Open chantier — S6 HUD on BG3',['../examples_games_shmup_1942.html#autotoc_md1296',1,'']]],
  ['chantier_20a1_68',['🟢 &lt;span class=&quot;tt&quot;&gt;int&lt;/span&gt; and &lt;span class=&quot;tt&quot;&gt;long&lt;/span&gt; sizes are correct on this target (since chantier A1)',['../tutorial_math.html#autotoc_md287',1,'']]],
  ['chantier_20b6_202026_2005_2009_69',['&lt;span class=&quot;tt&quot;&gt;atan2&lt;/span&gt; and &lt;span class=&quot;tt&quot;&gt;sqrt&lt;/span&gt; ship in the lib (chantier B6, 2026-05-09)',['../tutorial_math.html#autotoc_md294',1,'']]],
  ['cheaply_70',['The HUD — always on top, cheaply',['../craft_backgrounds.html#autotoc_md456',1,'']]],
  ['cheat_20sheet_71',['Register Cheat Sheet',['../snes_graphics_guide.html#autotoc_md676',1,'']]],
  ['check_72',['Measured parity (luna v1.9.0 + Mesen2 cross-check)',['../examples_color_hicolor_1792.html#autotoc_md1152',1,'']]],
  ['checkerboard_20background_73',['6. The Checkerboard Background',['../examples_hdma_hdma_wave.html#autotoc_md1338',1,'']]],
  ['checking_20all_20four_20corners_74',['Checking All Four Corners',['../tutorial_collision.html#autotoc_md125',1,'']]],
  ['checklist_75',['Self-review checklist',['../contributing.html#autotoc_md1829',1,'']]],
  ['checklist_20before_20you_20write_20code_76',['Checklist before you write code',['../craft_planning.html#autotoc_md488',1,'']]],
  ['checksum_20validation_77',['Checksum Validation',['../examples_memory_save_game.html#autotoc_md1515',1,'']]],
  ['chip_20actually_20is_78',['What the chip actually is',['../tutorial_dsp1.html#autotoc_md184',1,'']]],
  ['chip_20memory_79',['Enhancement Chip Memory',['../memory_map.html#autotoc_md773',1,'']]],
  ['chip_20tutorial_80',['SA-1 Enhancement Chip Tutorial',['../tutorial_sa1.html',1,'index']]],
  ['chips_81',['chips',['../examples_chips.html',1,'Enhancement chips'],['../examples_by_category.html#autotoc_md612',1,'Enhancement chips']]],
  ['chips_20in_20one_20screen_82',['The two chips, in one screen',['../examples_chips.html#autotoc_md1123',1,'']]],
  ['choose_20a_20background_20mode_20from_20your_20genre_83',['Choose a background mode from your genre',['../craft_planning.html#autotoc_md485',1,'']]],
  ['choose_20your_20path_84',['Choose Your Path',['../getting_started.html#autotoc_md545',1,'']]],
  ['cite_85',['The hardware references we cite',['../craft.html#autotoc_md492',1,'']]],
  ['clamp_20to_20the_20world_20—_20room_20locking_86',['Clamp to the world — room-locking',['../craft_camera.html#autotoc_md464',1,'']]],
  ['clang_3a_20command_20not_20found_20or_20cc_3a_20command_20not_20found_87',['&quot;clang: command not found&quot; or &quot;cc: command not found&quot;',['../troubleshooting.html#autotoc_md731',1,'']]],
  ['claude_88',['Project knowledge in &lt;span class=&quot;tt&quot;&gt;.claude/&lt;/span&gt;',['../contributing.html#autotoc_md1832',1,'']]],
  ['clip_20and_20ticking_89',['Selecting the Clip and Ticking',['../tutorial_animation.html#autotoc_md81',1,'']]],
  ['clone_20and_20build_90',['B2. Clone and Build',['../getting_started.html#autotoc_md559',1,'']]],
  ['cloud_20overlay_20—_20examples_20color_20transparency_91',['Additive cloud overlay — &lt;span class=&quot;tt&quot;&gt;examples/color/transparency&lt;/span&gt;',['../tutorial_colormath.html#autotoc_md145',1,'']]],
  ['code_92',['Code',['../tutorial_superfx.html#autotoc_md417',1,'2. Write GSU Assembly Code'],['../tutorial_sa1.html#autotoc_md346',1,'2. Write Your SA-1 Boot Code'],['../code_style.html#autotoc_md618',1,'C Code'],['../example_sources.html',1,'Example Source Code'],['../index.html#autotoc_md6',1,'Examples (Annotated Source Code)'],['../contributing.html#autotoc_md1820',1,'Submitting Code']]],
  ['code_93',['code',['../tutorial_sram.html#autotoc_md405',1,'🔴 &lt;span class=&quot;tt&quot;&gt;SRAM_SIZE&lt;/span&gt; mismatch between Makefile and code'],['../craft_planning.html#autotoc_md488',1,'Checklist before you write code']]],
  ['code_20is_20identical_20to_20lorom_94',['2. The code is identical to LoROM',['../examples_memory_hirom_demo.html#autotoc_md1488',1,'']]],
  ['code_20of_20conduct_95',['Code of Conduct',['../contributing.html#autotoc_md1817',1,'']]],
  ['code_20review_96',['Code Review',['../contributing.html#autotoc_md1830',1,'']]],
  ['code_20style_20guide_97',['OpenSNES Code Style Guide',['../code_style.html',1,'index']]],
  ['code_20type_98',['Code Type',['../examples_audio_snesmod_music.html#autotoc_md896',1,'Code Type'],['../examples_backgrounds_mode1.html#autotoc_md974',1,'Code Type'],['../examples_input_two_players.html#autotoc_md1405',1,'Code Type'],['../examples_transitions_fading.html#autotoc_md1729',1,'Code Type']]],
  ['codes_99',['Codes',['../examples_chips_sa1_hello.html#autotoc_md1126',1,'Status Codes'],['../examples_chips_superfx_hello.html#autotoc_md1141',1,'Status Codes']]],
  ['coef_200f_207f_100',['FIR Filter Coefficients (COEF 0F-7F)',['../snes_sound_guide.html#autotoc_md706',1,'']]],
  ['coefficients_20coef_200f_207f_101',['FIR Filter Coefficients (COEF 0F-7F)',['../snes_sound_guide.html#autotoc_md706',1,'']]],
  ['collides_102',['Where the sprite is vs where it collides',['../tutorial_collision.html#autotoc_md128',1,'']]],
  ['collision_103',['Collision',['../examples_games_likemario.html#autotoc_md1251',1,'6. Tile-Based Collision'],['../examples_input_two_players.html#autotoc_md1430',1,'Exercise 1: Player Collision'],['../examples_games_mapandobjects.html#autotoc_md1269',1,'Map Engine and Tile Collision'],['../examples_maps_slope_collision.html#autotoc_md1465',1,'Object Engine and Slope Collision'],['../tutorial_collision.html#autotoc_md123',1,'Sprite-to-Background Collision'],['../tutorial_collision.html#autotoc_md119',1,'Sprite-to-Sprite Collision'],['../examples_basics_collision_demo.html#autotoc_md1067',1,'Tile-Based Wall Collision']]],
  ['collision_20against_20the_20map_104',['Collision against the map',['../tutorial_map.html#autotoc_md266',1,'']]],
  ['collision_20breakout_20bricks_105',['Grid-Based Collision (Breakout Bricks)',['../tutorial_collision.html#autotoc_md134',1,'']]],
  ['collision_20detection_20demo_106',['Collision Detection Demo',['../examples_basics_collision_demo.html',1,'examples_basics']]],
  ['collision_20detection_20tutorial_107',['Collision Detection Tutorial',['../tutorial_collision.html',1,'index']]],
  ['collision_20don_20t_20loop_20over_20100_20bricks_108',['5. Grid Collision (Don&apos;t Loop Over 100 Bricks)',['../examples_games_breakout.html#autotoc_md1222',1,'']]],
  ['collision_20map_20layout_109',['Collision Map Layout',['../examples_basics_collision_demo.html#autotoc_md1070',1,'']]],
  ['collision_20response_20patterns_110',['Collision Response Patterns',['../tutorial_collision.html#autotoc_md129',1,'']]],
  ['collision_20with_20rect_20pointers_111',['AABB Collision with Rect Pointers',['../examples_basics_collision_demo.html#autotoc_md1066',1,'']]],
  ['color_112',['direct_color — the pixel byte IS the color',['../examples_color_direct_color.html',1,'examples_color']]],
  ['color_20addition_20transparency_113',['Color Addition Transparency',['../examples_color_transparency.html',1,'examples_color']]],
  ['color_20background_114',['Mode 3 — 256-Color Background',['../examples_backgrounds_mode3.html',1,'examples_backgrounds']]],
  ['color_20cgram_115',['Color (CGRAM)',['../registers.html#autotoc_md829',1,'']]],
  ['color_20cycling_20between_20levels_116',['8. Color Cycling Between Levels',['../examples_games_breakout.html#autotoc_md1225',1,'']]],
  ['color_20fade_117',['Exercise 3: Color Fade',['../examples_transitions_fading.html#autotoc_md1749',1,'']]],
  ['color_20format_2015_20bit_20bgr_118',['Color Format (15-bit BGR)',['../snes_graphics_guide.html#autotoc_md663',1,'']]],
  ['color_20generator_20ram_119',['CGRAM (Color Generator RAM)',['../examples_hdma_gradient_colors.html#autotoc_md1315',1,'']]],
  ['color_20gradient_5f9bit_120',['Two channels, one visual — &lt;span class=&quot;tt&quot;&gt;examples/color/gradient_9bit&lt;/span&gt;',['../tutorial_hdma.html#autotoc_md238',1,'']]],
  ['color_20gradients_121',['Gradient Colors -- HDMA Color Gradients',['../examples_hdma_gradient_colors.html',1,'examples_hdma']]],
  ['color_20math_20configuration_122',['Color Math Configuration',['../examples_color_transparency.html#autotoc_md1178',1,'Color Math Configuration'],['../examples_windows_transparent_window.html#autotoc_md1782',1,'Color Math Configuration']]],
  ['color_20math_20hdma_123',['Transparent Window -- Color Math + HDMA',['../examples_windows_transparent_window.html',1,'examples_windows']]],
  ['color_20math_20not_20for_20bg_20masking_124',['Window for Color Math (Not for BG Masking)',['../examples_windows_transparent_window.html#autotoc_md1780',1,'']]],
  ['color_20math_20not_20palette_20edits_125',['Hit flash — color math, not palette edits',['../craft_game_feel.html#autotoc_md474',1,'']]],
  ['color_20math_20window_20vs_20bg_20window_126',['Color Math Window vs BG Window',['../examples_windows_transparent_window.html#autotoc_md1784',1,'']]],
  ['color_20math_20works_127',['How Color Math Works',['../colormath_8h.html#autotoc_md18',1,'']]],
  ['color_20math_3a_20main_20screen_20sub_20screen_128',['Color Math: Main Screen + Sub Screen',['../examples_color_transparency.html#autotoc_md1176',1,'']]],
  ['color_20palette_129',['Color Palette',['../examples_mode7_rotate_scale.html#autotoc_md1554',1,'256-Color Palette'],['../examples_backgrounds_mode1.html#autotoc_md1002',1,'Color Palette']]],
  ['color_20ram_130',['CGRAM (Color RAM)',['../memory_map.html#autotoc_md768',1,'']]],
  ['color_20transparency_131',['Additive cloud overlay — &lt;span class=&quot;tt&quot;&gt;examples/color/transparency&lt;/span&gt;',['../tutorial_colormath.html#autotoc_md145',1,'']]],
  ['colormathsetsource_20polarity_20is_20opposite_20of_20intuitive_132',['🟠 &lt;span class=&quot;tt&quot;&gt;colorMathSetSource&lt;/span&gt; polarity is opposite of intuitive',['../tutorial_colormath.html#autotoc_md149',1,'']]],
  ['colors_133',['Colors',['../hardware_overview.html#autotoc_md800',1,'']]],
  ['colors_20×_202_20bytes_134',['CGRAM Layout (256 colors × 2 bytes)',['../snes_graphics_guide.html#autotoc_md662',1,'']]],
  ['colors_20—_20rgb_20channel_20split_20blend_135',['&quot;3840 colors&quot; — RGB channel-split blend',['../examples_color_hicolor_blend.html',1,'examples_color']]],
  ['colors_20four_20bytes_136',['5. Two Colors, Four Bytes',['../examples_fundamentals_text_glyphs.html#autotoc_md1198',1,'']]],
  ['colors_20from_20a_204bpp_20background_137',['HiColor — 1792 colors from a 4bpp background',['../examples_color_hicolor_1792.html',1,'examples_color']]],
  ['colors_20garbled_20palette_138',['Wrong colors / garbled palette',['../troubleshooting.html#autotoc_md741',1,'']]],
  ['colors_20hdma_20color_20gradients_139',['Gradient Colors -- HDMA Color Gradients',['../examples_hdma_gradient_colors.html',1,'examples_hdma']]],
  ['colour_140',['Colour',['../examples_color.html',1,'Colour'],['../examples_by_category.html#autotoc_md596',1,'Colour']]],
  ['colour_20gradient_20—_20examples_20hdma_20gradient_5fcolors_141',['Static colour gradient — &lt;span class=&quot;tt&quot;&gt;examples/hdma/gradient_colors&lt;/span&gt;',['../tutorial_hdma.html#autotoc_md231',1,'']]],
  ['colour_20math_142',['colour math',['../tutorial_window.html#autotoc_md445',1,'🟠 &lt;span class=&quot;tt&quot;&gt;windowEnable(window, WINDOW_MATH)&lt;/span&gt; is the gate to colour math'],['../tutorial_colormath.html#autotoc_md140',1,'The minimum viable colour math']]],
  ['colour_20math_20—_20examples_20windows_20transparent_5fwindow_143',['Window + colour math — &lt;span class=&quot;tt&quot;&gt;examples/windows/transparent_window&lt;/span&gt;',['../tutorial_window.html#autotoc_md442',1,'']]],
  ['colour_20math_20actually_20is_144',['What colour math actually is',['../tutorial_colormath.html#autotoc_md138',1,'']]],
  ['colour_20math_20on_20the_20backdrop_145',['🟡 Colour-math on the backdrop',['../tutorial_colormath.html#autotoc_md151',1,'']]],
  ['colour_20math_20runs_20after_20windowing_146',['🟡 Colour math runs after windowing',['../tutorial_colormath.html#autotoc_md152',1,'']]],
  ['colour_20math_20tutorial_147',['Colour Math Tutorial',['../tutorial_colormath.html',1,'index']]],
  ['colours_20split_20bg_20vs_20sprites_148',['2. CGRAM — 256 colours, split BG vs sprites',['../craft_planning.html#autotoc_md483',1,'']]],
  ['column_20major_20tile_20layout_149',['Column-Major Tile Layout',['../tutorial_superfx.html#autotoc_md428',1,'']]],
  ['column_20pipeline_150',['3. Streaming: The Column Pipeline',['../examples_games_likemario.html#autotoc_md1248',1,'']]],
  ['column_20scroll_20from_20bg3_151',['mode2 — offset-per-tile: per-column scroll from BG3',['../examples_backgrounds_mode2.html',1,'examples_backgrounds']]],
  ['combinations_152',['Button Combinations',['../tutorial_input.html#autotoc_md257',1,'']]],
  ['combining_20both_20for_20transitions_153',['3. Combining both for transitions',['../examples_transitions_mosaic.html#autotoc_md1765',1,'']]],
  ['comes_20out_154',['comes out',['../tools_font2snes.html#autotoc_md504',1,'What goes in, what comes out'],['../tools_gfx4snes.html#autotoc_md509',1,'What goes in, what comes out'],['../tools_img2snes.html#autotoc_md515',1,'What goes in, what comes out'],['../tools_palplan.html#autotoc_md520',1,'What goes in, what comes out'],['../tools_smconv.html#autotoc_md530',1,'What goes in, what comes out'],['../tools_tmx2snes.html#autotoc_md535',1,'What goes in, what comes out'],['../tools_wav2brr.html#autotoc_md540',1,'What goes in, what comes out']]],
  ['command_20not_20found_155',['command not found',['../troubleshooting.html#autotoc_md731',1,'&quot;clang: command not found&quot; or &quot;cc: command not found&quot;'],['../troubleshooting.html#autotoc_md730',1,'&quot;wla-65816: command not found&quot;']]],
  ['command_20not_20found_20or_20cc_3a_20command_20not_20found_156',['&quot;clang: command not found&quot; or &quot;cc: command not found&quot;',['../troubleshooting.html#autotoc_md731',1,'']]],
  ['command_20not_20found_3a_20make_157',['&quot;command not found: make&quot;',['../getting_started.html#autotoc_md566',1,'']]],
  ['commands_158',['Diagnostic Commands',['../troubleshooting.html#autotoc_md748',1,'']]],
  ['commands_159',['Distance and Range: the game-logic commands',['../tutorial_dsp1.html#autotoc_md189',1,'']]],
  ['commercial_20games_160',['Window Shapes in Commercial Games',['../examples_windows_window.html#autotoc_md1798',1,'']]],
  ['commit_20messages_161',['Commit messages',['../contributing.html#autotoc_md1827',1,'']]],
  ['common_20issues_162',['Common Issues',['../examples_audio_snesmod_music.html#autotoc_md926',1,'']]],
  ['common_20mk_163',['&quot;OPENSNES not defined&quot; or &quot;No rule to make target &apos;common.mk&apos;&quot;',['../troubleshooting.html#autotoc_md728',1,'']]],
  ['common_20operations_164',['Common Operations',['../snes_sound_guide.html#autotoc_md725',1,'']]],
  ['common_20pitfalls_165',['Common Pitfalls',['../oam.html#autotoc_md794',1,'']]],
  ['communication_166',['Runtime Communication',['../snes_sound_guide.html#autotoc_md710',1,'']]],
  ['communication_20patterns_167',['Communication Patterns',['../tutorial_sa1.html#autotoc_md348',1,'']]],
  ['communication_20ports_168',['Communication Ports',['../snes_sound_guide.html#autotoc_md686',1,'']]],
  ['communication_20protocol_169',['Communication Protocol',['../snes_sound_guide.html#autotoc_md708',1,'']]],
  ['compatibility_170',['Compatibility',['../tutorial_superfx.html#autotoc_md414',1,'Emulator Compatibility'],['../examples_chips_superfx_3d.html#autotoc_md1132',1,'Emulator Compatibility'],['../examples_chips_superfx_hello.html#autotoc_md1138',1,'Emulator Compatibility'],['../snes_graphics_guide.html#autotoc_md667',1,'For SNES Compatibility']]],
  ['compiler_20directories_20or_20cc65816_20not_20found_171',['Empty &lt;span class=&quot;tt&quot;&gt;compiler/&lt;/span&gt; directories or &quot;cc65816 not found&quot;',['../troubleshooting.html#autotoc_md729',1,'']]],
  ['compiler_20folder_172',['&quot;fatal: repository not found&quot; or empty compiler folder',['../getting_started.html#autotoc_md567',1,'']]],
  ['compiler_20vs_20mul16_173',['🟠 Compiler &lt;span class=&quot;tt&quot;&gt;*&lt;/span&gt; vs &lt;span class=&quot;tt&quot;&gt;mul16&lt;/span&gt;',['../tutorial_math.html#autotoc_md291',1,'']]],
  ['complete_20background_20setup_174',['Example: Complete Background Setup',['../tutorial_graphics.html#autotoc_md220',1,'']]],
  ['complete_20example_175',['Complete Example',['../oam.html#autotoc_md793',1,'']]],
  ['complete_20examples_176',['Complete Examples',['../tutorial_collision.html#autotoc_md136',1,'']]],
  ['complete_20game_177',['game_skeleton — the smallest complete game',['../examples_basics_game_skeleton.html',1,'examples_basics']]],
  ['complete_20game_20examples_178',['Complete Game Examples',['../examples_games.html',1,'examples']]],
  ['complete_20projects_179',['Level 5 &amp;ndash; Maps and Complete Projects',['../examples.html#autotoc_md1564',1,'']]],
  ['complete_20title_20flow_180',['Complete Title Flow',['../tutorial_game_states.html#autotoc_md202',1,'']]],
  ['components_181',['Third-Party Components',['../third_party.html',1,'index']]],
  ['composing_20with_20backgrounds_20layers_182',['Composing with backgrounds &amp;amp; layers',['../craft_backgrounds.html',1,'craft']]],
  ['compositions_20you_20will_20reuse_183',['Three compositions you will reuse',['../craft_backgrounds.html#autotoc_md454',1,'']]],
  ['compress_20tiles_20but_20not_20tilemaps_184',['Why Compress Tiles but Not Tilemaps?',['../examples_backgrounds_mode1_lz77.html#autotoc_md1022',1,'']]],
  ['compression_185',['LZ77 / LZSS Compression',['../examples_backgrounds_mode1_lz77.html#autotoc_md1021',1,'']]],
  ['concepts_186',['Concepts',['../hardware_overview.html#autotoc_md801',1,'Key Concepts'],['../examples_basics.html#autotoc_md1101',1,'Key Concepts'],['../examples_memory.html#autotoc_md1498',1,'Key Concepts'],['../examples_text.html#autotoc_md1713',1,'Key Concepts'],['../examples_audio_apu_switch.html#autotoc_md868',1,'SNES Concepts'],['../examples_audio_pitch_mod.html#autotoc_md878',1,'SNES Concepts'],['../examples_audio_play_noise.html#autotoc_md882',1,'SNES Concepts'],['../examples_audio_sfx_from_wav.html#autotoc_md887',1,'SNES Concepts'],['../examples_audio_snesmod_sfx.html#autotoc_md949',1,'SNES Concepts'],['../examples_audio_soundboard.html#autotoc_md957',1,'SNES Concepts'],['../examples_backgrounds_mode1_bg3_priority.html#autotoc_md1012',1,'SNES Concepts'],['../examples_backgrounds_mode1_lz77.html#autotoc_md1020',1,'SNES Concepts'],['../examples_backgrounds_mode5_hires.html#autotoc_md1048',1,'SNES Concepts'],['../examples_basics_aim_target.html#autotoc_md1056',1,'SNES Concepts'],['../examples_basics_collision_demo.html#autotoc_md1065',1,'SNES Concepts'],['../examples_basics_fix32_orbit.html#autotoc_md1076',1,'SNES Concepts'],['../examples_basics_random.html#autotoc_md1095',1,'SNES Concepts'],['../examples_basics_scene_stack.html#autotoc_md1105',1,'SNES Concepts'],['../examples_basics_timer.html#autotoc_md1113',1,'SNES Concepts'],['../examples_chips_dsp1_cube.html#autotoc_md1118',1,'SNES Concepts'],['../examples_color_direct_color.html#autotoc_md1143',1,'SNES Concepts'],['../examples_color_gradient_9bit.html#autotoc_md1146',1,'SNES Concepts'],['../examples_color_hicolor_1792.html#autotoc_md1150',1,'SNES Concepts'],['../examples_color_transparency.html#autotoc_md1175',1,'SNES Concepts'],['../examples_games_mapandobjects.html#autotoc_md1268',1,'SNES Concepts'],['../examples_games_mode7_flying.html#autotoc_md1281',1,'SNES Concepts'],['../examples_games_mode7_racing.html#autotoc_md1284',1,'SNES Concepts'],['../examples_games_rpg.html#autotoc_md1290',1,'SNES Concepts'],['../examples_hdma_gradient_colors.html#autotoc_md1314',1,'SNES Concepts'],['../examples_hdma_hdma_indirect_gradient.html#autotoc_md1325',1,'SNES Concepts'],['../examples_hdma_hdma_wave_table.html#autotoc_md1352',1,'SNES Concepts'],['../examples_input_controller.html#autotoc_md1359',1,'SNES Concepts'],['../examples_input_mouse.html#autotoc_md1366',1,'SNES Concepts'],['../examples_maps_dynamic_map.html#autotoc_md1443',1,'SNES Concepts'],['../examples_maps_map_scroll.html#autotoc_md1454',1,'SNES Concepts'],['../examples_maps_slope_collision.html#autotoc_md1463',1,'SNES Concepts'],['../examples_maps_tiled.html#autotoc_md1474',1,'SNES Concepts'],['../examples_memory_hirom_demo.html#autotoc_md1491',1,'SNES Concepts'],['../examples_memory_save_game.html#autotoc_md1512',1,'SNES Concepts'],['../examples_mode7_perspective.html#autotoc_md1527',1,'SNES Concepts'],['../examples_mode7_perspective_rotate.html#autotoc_md1534',1,'SNES Concepts'],['../examples_mode7_rotate_scale.html#autotoc_md1551',1,'SNES Concepts'],['../examples_scrolling_mixed_scroll.html#autotoc_md1592',1,'SNES Concepts'],['../examples_scrolling_parallax_scroll.html#autotoc_md1613',1,'SNES Concepts'],['../examples_sprites_animated_sprite.html#autotoc_md1630',1,'SNES Concepts'],['../examples_sprites_aseprite_pipeline.html#autotoc_md1636',1,'SNES Concepts'],['../examples_sprites_dynamic_sprite.html#autotoc_md1653',1,'SNES Concepts'],['../examples_sprites_metasprite.html#autotoc_md1660',1,'SNES Concepts'],['../examples_sprites_simple_sprite.html#autotoc_md1680',1,'SNES Concepts'],['../examples_sprites_sprite_sizes.html#autotoc_md1694',1,'SNES Concepts'],['../examples_transitions_mosaic.html#autotoc_md1766',1,'SNES Concepts'],['../examples_windows_transparent_window.html#autotoc_md1783',1,'SNES Concepts'],['../examples_windows_window.html#autotoc_md1796',1,'SNES Concepts'],['../examples_windows_window_multi_hdma.html#autotoc_md1802',1,'SNES Concepts']]],
  ['concepts_187',['concepts',['../examples_audio_echo.html#autotoc_md873',1,'SNES concepts'],['../examples_input_move_sprite.html#autotoc_md1380',1,'SNES concepts'],['../examples_text_print_string.html#autotoc_md1708',1,'SNES concepts'],['../examples_text_scroll_message.html#autotoc_md1720',1,'SNES concepts']]],
  ['conduct_188',['Code of Conduct',['../contributing.html#autotoc_md1817',1,'']]],
  ['configuration_189',['Configuration',['../registers.html#autotoc_md851',1,'Channel Configuration'],['../examples_color_transparency.html#autotoc_md1178',1,'Color Math Configuration'],['../examples_windows_transparent_window.html#autotoc_md1782',1,'Color Math Configuration'],['../snes_sound_guide.html#autotoc_md704',1,'Configuration'],['../tutorial_audio.html#autotoc_md100',1,'Makefile Configuration']]],
  ['configure_20bg1_20and_20enable_20display_190',['4. Configure BG1 and Enable Display',['../examples_backgrounds_mode1_lz77.html#autotoc_md1029',1,'']]],
  ['configure_20obj_20size_191',['3. Configure OBJ size',['../examples_sprites_simple_sprite.html#autotoc_md1677',1,'']]],
  ['configure_20video_20mode_192',['1. Configure Video Mode',['../examples_backgrounds_mode1.html#autotoc_md980',1,'']]],
  ['configured_193',['🟡 Don&apos;t enable channels you haven&apos;t configured',['../tutorial_hdma.html#autotoc_md246',1,'']]],
  ['considerations_194',['Performance Considerations',['../tutorial_animation.html#autotoc_md93',1,'']]],
  ['consoleinit_195',['🟡 Mosaic state is not reset by &lt;span class=&quot;tt&quot;&gt;consoleInit&lt;/span&gt;',['../tutorial_mosaic.html#autotoc_md329',1,'']]],
  ['constants_196',['Constants',['../input_8h.html#autotoc_md36',1,'Button Constants'],['../tutorial_input.html#autotoc_md250',1,'Button Constants'],['../tutorial_audio.html#autotoc_md106',1,'Pitch Constants']]],
  ['consumer_197',['Pattern 1: Flag Sync (Producer/Consumer)',['../tutorial_sa1.html#autotoc_md349',1,'']]],
  ['contents_198',['Contents',['../hardware_overview.html#autotoc_md796',1,'Contents'],['../snes_graphics_guide.html#autotoc_md634',1,'Table of Contents'],['../snes_sound_guide.html#autotoc_md678',1,'Table of Contents'],['../registers.html#autotoc_md809',1,'Table of Contents']]],
  ['contents_20on_20first_20boot_20are_20undefined_199',['🔴 SRAM contents on first boot are undefined',['../tutorial_sram.html#autotoc_md403',1,'']]],
  ['continuous_20infinite_20scrolling_200',['Continuous / Infinite Scrolling',['../tutorial_scrolling.html#autotoc_md369',1,'']]],
  ['continuous_20scroll_201',['Continuous Scroll',['../examples_scrolling_continuous_scroll.html',1,'examples_scrolling']]],
  ['contributing_202',['Contributing',['../index.html#autotoc_md9',1,'']]],
  ['contributing_20to_20opensnes_203',['Contributing to OpenSNES',['../contributing.html',1,'index']]],
  ['contributions_204',['AI-Assisted Contributions',['../contributing.html#autotoc_md1831',1,'']]],
  ['control_205',['Control',['../registers.html#autotoc_md813',1,'$2100 - INIDISP (Display Control)'],['../registers.html#autotoc_md812',1,'Display Control'],['../registers.html#autotoc_md846',1,'DMA Control'],['../examples_input_two_players.html#autotoc_md1415',1,'Independent Control'],['../registers.html#autotoc_md837',1,'Interrupt Control'],['../examples_audio_snesmod_music.html#autotoc_md904',1,'Playback Control'],['../tutorial_audio.html#autotoc_md103',1,'Volume Control'],['../examples_audio_snesmod_music.html#autotoc_md905',1,'Volume Control']]],
  ['control_206',['4. Zoom control',['../examples_mode7_rotate_scale.html#autotoc_md1550',1,'']]],
  ['controlled_20scrolling_207',['D-PAD Controlled Scrolling',['../tutorial_scrolling.html#autotoc_md364',1,'']]],
  ['controller_208',['Disconnected Controller',['../examples_input_two_players.html#autotoc_md1422',1,'']]],
  ['controller_202_209',['Reading Controller 2',['../tutorial_input.html#autotoc_md253',1,'']]],
  ['controller_20detection_210',['Controller Detection',['../examples_input_two_players.html#autotoc_md1421',1,'']]],
  ['controller_20input_211',['Controller Input',['../examples_input_controller.html',1,'examples_input']]],
  ['controller_20input_20not_20working_212',['Controller input not working',['../troubleshooting.html#autotoc_md738',1,'']]],
  ['controller_20input_20tutorial_213',['Controller Input Tutorial',['../tutorial_input.html',1,'index']]],
  ['controller_20layout_214',['SNES Controller Layout',['../tutorial_input.html#autotoc_md249',1,'']]],
  ['controller_20registers_215',['Controller Registers',['../examples_input_two_players.html#autotoc_md1408',1,'']]],
  ['controller_20types_216',['Controller Types',['../examples_input_two_players.html#autotoc_md1423',1,'']]],
  ['controllers_217',['Controllers',['../examples_input_two_players.html#autotoc_md1409',1,'Reading Both Controllers'],['../tutorial_input.html#autotoc_md251',1,'Reading Controllers'],['../examples_input_two_players.html#autotoc_md1407',1,'Reading Two Controllers']]],
  ['controls_218',['Controls',['../examples_audio_snesmod_music_large.html#autotoc_md943',1,'Controls'],['../examples_audio_snesmod_sfx.html#autotoc_md946',1,'Controls'],['../examples_backgrounds_mode1_bg3_priority.html#autotoc_md1006',1,'Controls'],['../examples_backgrounds_mode1_lz77.html#autotoc_md1024',1,'Controls'],['../examples_basics_collision_demo.html#autotoc_md1062',1,'Controls'],['../examples_basics_random.html#autotoc_md1094',1,'Controls'],['../examples_basics_scene_stack.html#autotoc_md1104',1,'Controls'],['../examples_basics_timer.html#autotoc_md1112',1,'Controls'],['../examples_color_transparency.html#autotoc_md1172',1,'Controls'],['../examples_fundamentals_text_glyphs.html#autotoc_md1190',1,'Controls'],['../examples_games_breakout.html#autotoc_md1213',1,'Controls'],['../examples_games_likemario.html#autotoc_md1241',1,'Controls'],['../examples_games_mapandobjects.html#autotoc_md1272',1,'Controls'],['../examples_games_tetris.html#autotoc_md1303',1,'Controls'],['../examples_hdma_gradient_colors.html#autotoc_md1308',1,'Controls'],['../examples_hdma_hdma_wave.html#autotoc_md1328',1,'Controls'],['../examples_input_controller.html#autotoc_md1358',1,'Controls'],['../examples_input_mouse.html#autotoc_md1370',1,'Controls'],['../examples_input_superscope.html#autotoc_md1386',1,'Controls'],['../examples_maps_dynamic_map.html#autotoc_md1448',1,'Controls'],['../examples_maps_map_scroll.html#autotoc_md1453',1,'Controls'],['../examples_maps_slope_collision.html#autotoc_md1468',1,'Controls'],['../examples_maps_tiled.html#autotoc_md1477',1,'Controls'],['../examples_memory_hirom_demo.html#autotoc_md1484',1,'Controls'],['../examples_memory_save_game.html#autotoc_md1504',1,'Controls'],['../examples_mode7_perspective.html#autotoc_md1521',1,'Controls'],['../examples_mode7_rotate_scale.html#autotoc_md1544',1,'Controls'],['../examples_scrolling_continuous_scroll.html#autotoc_md1569',1,'Controls'],['../examples_scrolling_mixed_scroll.html#autotoc_md1597',1,'Controls'],['../examples_scrolling_parallax_scroll.html#autotoc_md1606',1,'Controls'],['../examples_sprites_animated_sprite.html#autotoc_md1623',1,'Controls'],['../examples_sprites_dynamic_metasprite.html#autotoc_md1642',1,'Controls'],['../examples_sprites_dynamic_sprite.html#autotoc_md1646',1,'Controls'],['../examples_sprites_metasprite.html#autotoc_md1664',1,'Controls'],['../examples_sprites_simple_sprite.html#autotoc_md1672',1,'Controls'],['../examples_sprites_sprite_sizes.html#autotoc_md1687',1,'Controls'],['../examples_transitions_mosaic.html#autotoc_md1760',1,'Controls'],['../examples_windows_transparent_window.html#autotoc_md1776',1,'Controls'],['../examples_windows_window.html#autotoc_md1788',1,'Controls']]],
  ['controls_20krom_20s_20map_219',['Controls (krom&apos;s map)',['../examples_mode7_perspective_rotate.html#autotoc_md1533',1,'']]],
  ['convention_220',['I-RAM Layout Convention',['../tutorial_sa1.html#autotoc_md351',1,'']]],
  ['convention_221',['convention',['../oam.html#autotoc_md790',1,'OpenSNES SDK convention'],['../fixed32_8h.html#autotoc_md30',1,'Sign convention']]],
  ['conventions_222',['Naming Conventions',['../code_style.html#autotoc_md620',1,'']]],
  ['conversion_20macros_223',['The conversion macros',['../tutorial_math.html#autotoc_md276',1,'']]],
  ['conversion_20tools_224',['Conversion Tools',['../snes_sound_guide.html#autotoc_md719',1,'Conversion Tools'],['../snes_graphics_guide.html#autotoc_md671',1,'Graphics Conversion Tools']]],
  ['conversion_20with_20gfx4snes_225',['Asset Conversion with gfx4snes',['../examples_games_likemario.html#autotoc_md1260',1,'']]],
  ['convert_20for_20the_20snes_226',['The workflow: design in Tiled, convert for the SNES',['../craft_tiles_to_levels.html#autotoc_md496',1,'']]],
  ['converted_227',['🟡 Match &lt;span class=&quot;tt&quot;&gt;base_tile&lt;/span&gt;/&lt;span class=&quot;tt&quot;&gt;stride&lt;/span&gt; to how the sheet was converted',['../tutorial_panel.html#autotoc_md339',1,'']]],
  ['converted_20assets_228',['Pre-Converted Assets',['../examples_games_breakout.html#autotoc_md1235',1,'']]],
  ['converting_20a_20sheet_3a_20s_20must_20match_20the_20sprite_20size_229',['Converting a sheet: &lt;span class=&quot;tt&quot;&gt;-s&lt;/span&gt; must match the sprite size',['../tutorial_sprites.html#autotoc_md383',1,'']]],
  ['converting_20sprite_20sheets_20with_20gfx4snes_230',['Converting Sprite Sheets with gfx4snes',['../tutorial_animation.html#autotoc_md78',1,'']]],
  ['coordinate_20system_231',['Coordinate system',['../tutorial_mode7.html#autotoc_md302',1,'']]],
  ['coprocessor_232',['Coprocessor',['../examples_by_category.html#autotoc_md615',1,'DSP-1 Coprocessor'],['../examples_by_category.html#autotoc_md613',1,'SA-1 Coprocessor']]],
  ['coprocessor_20tutorial_233',['DSP-1 Coprocessor Tutorial',['../tutorial_dsp1.html',1,'']]],
  ['coprocessors_234',['More horsepower — the cartridge coprocessors',['../learning_path.html#autotoc_md580',1,'']]],
  ['corners_235',['Checking All Four Corners',['../tutorial_collision.html#autotoc_md125',1,'']]],
  ['correct_20on_20this_20target_20since_20chantier_20a1_236',['🟢 &lt;span class=&quot;tt&quot;&gt;int&lt;/span&gt; and &lt;span class=&quot;tt&quot;&gt;long&lt;/span&gt; sizes are correct on this target (since chantier A1)',['../tutorial_math.html#autotoc_md287',1,'']]],
  ['corrupt_20mode_207_20writes_20shared_20latch_237',['🟡 HDMA on BG1 scroll can corrupt Mode 7 writes (shared latch)',['../tutorial_hdma.html#autotoc_md244',1,'']]],
  ['corrupted_238',['Tiles appear corrupted',['../troubleshooting.html#autotoc_md742',1,'']]],
  ['corruption_239',['🔴 Battery dies → silent corruption',['../tutorial_sram.html#autotoc_md404',1,'']]],
  ['cos_20lookup_20tables_240',['Trigonometry (sin/cos lookup tables)',['../tutorial_math.html#autotoc_md278',1,'']]],
  ['cos_20luts_20are_20unsigned_20angle_20signed_20result_241',['🟡 Sin/cos LUTs are unsigned-angle, signed-result',['../tutorial_math.html#autotoc_md293',1,'']]],
  ['cost_242',['cost',['../tutorial_colormath.html#autotoc_md154',1,'Cycle cost'],['../tutorial_dma.html#autotoc_md182',1,'Cycle cost'],['../tutorial_hdma.html#autotoc_md247',1,'Cycle cost'],['../tutorial_mode7.html#autotoc_md316',1,'Cycle cost'],['../tutorial_mosaic.html#autotoc_md330',1,'Cycle cost'],['../tutorial_sram.html#autotoc_md411',1,'Cycle cost'],['../tutorial_window.html#autotoc_md449',1,'Cycle cost']]],
  ['cost_20side_3a_20tiles_20by_20mode_243',['The cost side: tiles by mode',['../craft_planning.html#autotoc_md486',1,'']]],
  ['cost_20summary_244',['Cycle cost summary',['../tutorial_math.html#autotoc_md296',1,'']]],
  ['counter_245',['Pattern 2: Free-Running Counter',['../tutorial_sa1.html#autotoc_md350',1,'']]],
  ['counter_20recommended_246',['Manual Counter (Recommended)',['../tutorial_animation.html#autotoc_md73',1,'']]],
  ['cproc_247',['cproc',['../third_party.html#autotoc_md759',1,'']]],
  ['cpu_248',['SPC700 CPU',['../snes_sound_guide.html#autotoc_md683',1,'']]],
  ['cpu_20budget_3a_203_2058_20mhz_249',['The CPU budget: ~3.58 MHz',['../craft_frame_budget.html#autotoc_md470',1,'']]],
  ['cpu_20registers_20_244200_20_24421f_250',['CPU Registers ($4200-$421F)',['../registers.html#autotoc_md836',1,'']]],
  ['cpu_20registers_20_244200_20_2444ff_251',['CPU Registers ($4200-$44FF)',['../memory_map.html#autotoc_md770',1,'']]],
  ['cracked_20it_252',['Debug tooling that cracked it',['../examples_audio_speech_synth.html#autotoc_md963',1,'']]],
  ['craft_253',['Game-Craft',['../index.html#autotoc_md2',1,'']]],
  ['craft_20guides_254',['Game-Craft Guides',['../craft.html',1,'index']]],
  ['crash_255',['Runtime Issues (Black Screen / Crash)',['../troubleshooting.html#autotoc_md734',1,'']]],
  ['crashes_20after_20a_20few_20seconds_256',['ROM runs but crashes after a few seconds',['../troubleshooting.html#autotoc_md736',1,'']]],
  ['create_20the_20gsu_20loader_2065816_20asm_257',['3. Create the GSU Loader (65816 ASM)',['../tutorial_superfx.html#autotoc_md418',1,'']]],
  ['create_20your_20own_20project_258',['A5. Create Your Own Project',['../getting_started.html#autotoc_md552',1,'']]],
  ['creating_20music_259',['Creating Music',['../examples_audio_snesmod_music.html#autotoc_md907',1,'']]],
  ['creating_20music_20with_20openmpt_260',['Creating Music with OpenMPT',['../tutorial_audio.html#autotoc_md104',1,'']]],
  ['creation_261',['Soundbank Creation',['../snesmod_8h.html#autotoc_md57',1,'']]],
  ['creation_20tools_262',['Sound Creation Tools',['../snes_sound_guide.html#autotoc_md718',1,'']]],
  ['credits_263',['Credits',['../examples_audio_snesmod_music.html#autotoc_md938',1,'Credits'],['../examples_games_breakout.html#autotoc_md1240',1,'Credits'],['../examples_games_likemario.html#autotoc_md1266',1,'Credits'],['../examples_scrolling_continuous_scroll.html#autotoc_md1590',1,'Credits']]],
  ['critical_264',['Main Loop (CRITICAL!)',['../examples_audio_snesmod_music.html#autotoc_md903',1,'']]],
  ['critical_265',['Scanline Limits (Critical!)',['../snes_graphics_guide.html#autotoc_md650',1,'']]],
  ['critical_3a_20oam_20write_20buffer_266',['Critical: OAM Write Buffer',['../oam.html#autotoc_md781',1,'']]],
  ['cross_20check_267',['Measured parity (luna v1.9.0 + Mesen2 cross-check)',['../examples_color_hicolor_1792.html#autotoc_md1152',1,'']]],
  ['cube_268',['Cube',['../examples_chips_dsp1_cube.html',1,'DSP-1 Cube'],['../examples_chips_superfx_3d.html',1,'SuperFX 3D Cube']]],
  ['curated_20shelf_269',['Go deeper — the curated shelf',['../craft.html#autotoc_md491',1,'']]],
  ['current_270',['Architecture (current)',['../examples_games_shmup_1942.html#autotoc_md1297',1,'']]],
  ['cursor_271',['4. Main Loop: Read Mouse, Update Cursor',['../examples_input_mouse.html#autotoc_md1375',1,'']]],
  ['cursor_20sprite_272',['2. Load Cursor Sprite',['../examples_input_mouse.html#autotoc_md1373',1,'']]],
  ['custom_20tile_20sizes_273',['Custom Tile Sizes',['../tutorial_collision.html#autotoc_md126',1,'']]],
  ['cycle_20cost_274',['Cycle cost',['../tutorial_colormath.html#autotoc_md154',1,'Cycle cost'],['../tutorial_dma.html#autotoc_md182',1,'Cycle cost'],['../tutorial_hdma.html#autotoc_md247',1,'Cycle cost'],['../tutorial_mode7.html#autotoc_md316',1,'Cycle cost'],['../tutorial_mosaic.html#autotoc_md330',1,'Cycle cost'],['../tutorial_sram.html#autotoc_md411',1,'Cycle cost'],['../tutorial_window.html#autotoc_md449',1,'Cycle cost']]],
  ['cycle_20cost_20summary_275',['Cycle cost summary',['../tutorial_math.html#autotoc_md296',1,'']]],
  ['cycling_276',['Ambient life — palette cycling',['../craft_game_feel.html#autotoc_md477',1,'']]],
  ['cycling_20between_20levels_277',['8. Color Cycling Between Levels',['../examples_games_breakout.html#autotoc_md1225',1,'']]]
];
