OPENSNES := $(shell cd ../../.. && pwd)

TARGET   := pseudo_hires.sfc
ROM_NAME := PSEUDO HIRES BLEND

USE_LIB  := 1
LIB_MODULES := console dma background input tile

CSRC := main.c

include $(OPENSNES)/make/common.mk
