#==============================================================================
# Calculator Example - Makefile
#==============================================================================

OPENSNES := $(shell cd ../../.. && pwd)

TARGET   := calculator.sfc
ROM_NAME := SNES CALCULATOR

CSRC     := main.c
ASMSRC   := calc_loop.asm

include $(OPENSNES)/make/common.mk
