; font_data.as — generated by opensnes-text 1.0.0; one ASSET_SECTION per blob, .include it from assets_gen.asm (the build does)

ASSET_SECTION "font_tiles"
font_tiles:
.incbin "font.pic"
font_tiles_end:
.ENDS

ASSET_SECTION "font_pal"
font_pal:
.incbin "font.pal"
font_pal_end:
.ENDS

