; project_data.as — generated by opensnes-palette 1.0.0; one ASSET_SECTION per blob, .include it from assets_gen.asm (the build does)

ASSET_SECTION "project_cgram"
project_cgram:
.incbin "project.pal"
project_cgram_end:
.ENDS

