# Object Size Example
# Interactive demo of all 6 SNES sprite size modes

OPENSNES := $(shell cd ../../.. && pwd)

TARGET     := sprite_sizes.sfc
ROM_NAME   := OBJECT SIZE

USE_LIB    := 1
LIB_MODULES := console sprite dma text text4bpp input background

CSRC       := main.c

include $(OPENSNES)/make/common.mk
