/* GENERATED by devtools/vram_layout/vram_layout.py --emit — DO NOT EDIT.
 * Source: vram.spec. Regenerate after editing the spec.
 * Validated at build by `make lint-vram` (alignment + no overlap + fit). */
#ifndef VRAM_MAP_H
#define VRAM_MAP_H

#define VRAM_OBJ_TILES   0x0000  /* obj, 32 words */
#define VRAM_BG_TILEMAP  0x0400  /* bg_map, 1024 words */
#define VRAM_BG_TILES    0x1000  /* bg_char, 16 words */

#endif /* VRAM_MAP_H */
