OPENSNES := $(shell cd ../../.. && pwd)

TARGET     := fix32_orbit.sfc
ROM_NAME   := FIX32 ORBIT DEMO

USE_LIB    := 1
LIB_MODULES := console sprite dma background fixed32 math

CSRC       := main.c

include $(OPENSNES)/make/common.mk
