OPENSNES := $(shell cd ../../.. && pwd)

TARGET     := mode3.sfc
ROM_NAME   := MODE 3 256COLOR DEMO

USE_LIB    := 1
LIB_MODULES := console dma background

CSRC       := main.c

include $(OPENSNES)/make/common.mk
