# Entity Unit Test Makefile

OPENSNES := $(shell cd ../../.. && pwd)
TARGET   := test_entity.sfc
ROM_NAME := ENTITY TESTS

CSRC     := test_entity.c
USE_LIB  := 1
LIB_MODULES := console entity collision sprite dma text

include $(OPENSNES)/make/common.mk
