# Mode 0 Background Example
# 4 backgrounds with parallax scrolling

OPENSNES := $(shell cd ../../../.. && pwd)

TARGET     := mode0.sfc
ROM_NAME   := MODE0 4BG PARALLAX

USE_LIB    := 1
LIB_MODULES := console sprite dma

CSRC       := main.c
ASMSRC     := data.asm

include $(OPENSNES)/make/common.mk
