OPENSNES := $(shell cd ../../.. && pwd)

TARGET   := perspective_rotate.sfc
ROM_NAME := M7 PERSPECT ROTATE

USE_LIB  := 1
LIB_MODULES := console dma background hdma input mode7

CSRC   := main.c
ASMSRC := data.asm

include $(OPENSNES)/make/common.mk
