;==============================================================================
; Mode1LZ77 - Graphics Data
; Ported from PVSnesLib to OpenSNES
;
; LZ77-compressed 4bpp tiles (Mode 1, 16 colors).
; The .pic file was generated by PVSnesLib's gfx4snes with -z (LZ77).
; Uncompressed: 12544 bytes, compressed: 8696 bytes (31% savings).
;==============================================================================

; LZ77-compressed tile data
.section ".rodata_tiles" superfree

patterns:
.incbin "res/pvsneslib.pic"
patterns_end:

.ends

; Tilemap and palette (uncompressed)
.section ".rodata_map" superfree

map:
.incbin "res/pvsneslib.map"
map_end:

palette:
.incbin "res/pvsneslib.pal"
palette_end:

.ends
