const t_metasprite grid_metasprite0[] = {
	METASPR_ITEM(0, 0, 0, OBJ_PAL(0) | OBJ_PRIO(0)),
	METASPR_TERM
};

const t_metasprite grid_metasprite1[] = {
	METASPR_ITEM(0, 0, 4, OBJ_PAL(0) | OBJ_PRIO(0)),
	METASPR_TERM
};

const t_metasprite grid_metasprite2[] = {
	METASPR_ITEM(0, 0, 8, OBJ_PAL(0) | OBJ_PRIO(0)),
	METASPR_TERM
};

const t_metasprite grid_metasprite3[] = {
	METASPR_ITEM(0, 0, 12, OBJ_PAL(0) | OBJ_PRIO(0)),
	METASPR_TERM
};

const t_metasprite grid_metasprite4[] = {
	METASPR_ITEM(0, 0, 64, OBJ_PAL(0) | OBJ_PRIO(0)),
	METASPR_TERM
};

const t_metasprite grid_metasprite5[] = {
	METASPR_ITEM(0, 0, 68, OBJ_PAL(0) | OBJ_PRIO(0)),
	METASPR_TERM
};

const t_metasprite grid_metasprite6[] = {
	METASPR_ITEM(0, 0, 72, OBJ_PAL(0) | OBJ_PRIO(0)),
	METASPR_TERM
};

const t_metasprite grid_metasprite7[] = {
	METASPR_ITEM(0, 0, 76, OBJ_PAL(0) | OBJ_PRIO(0)),
	METASPR_TERM
};

const t_metasprite* grid_metasprites[8] = {
	grid_metasprite0, grid_metasprite1, grid_metasprite2, grid_metasprite3, grid_metasprite4, grid_metasprite5, grid_metasprite6, grid_metasprite7
};
