const t_metasprite grid_metasprite0[] = {
	METASPR_ITEM(0, 0, 0, OBJ_PAL(0) | OBJ_PRIO(0)),
	METASPR_ITEM(16, 0, 2, OBJ_PAL(0) | OBJ_PRIO(0)),
	METASPR_ITEM(0, 16, 32, OBJ_PAL(0) | OBJ_PRIO(0)),
	METASPR_ITEM(16, 16, 34, OBJ_PAL(0) | OBJ_PRIO(0)),
	METASPR_TERM
};

const t_metasprite grid_metasprite1[] = {
	METASPR_ITEM(0, 0, 4, OBJ_PAL(0) | OBJ_PRIO(0)),
	METASPR_ITEM(16, 0, 6, OBJ_PAL(0) | OBJ_PRIO(0)),
	METASPR_ITEM(0, 16, 36, OBJ_PAL(0) | OBJ_PRIO(0)),
	METASPR_ITEM(16, 16, 38, OBJ_PAL(0) | OBJ_PRIO(0)),
	METASPR_TERM
};

const t_metasprite grid_metasprite2[] = {
	METASPR_ITEM(0, 0, 8, OBJ_PAL(0) | OBJ_PRIO(0)),
	METASPR_ITEM(16, 0, 10, OBJ_PAL(0) | OBJ_PRIO(0)),
	METASPR_ITEM(0, 16, 40, OBJ_PAL(0) | OBJ_PRIO(0)),
	METASPR_ITEM(16, 16, 42, OBJ_PAL(0) | OBJ_PRIO(0)),
	METASPR_TERM
};

const t_metasprite grid_metasprite3[] = {
	METASPR_ITEM(0, 0, 12, OBJ_PAL(0) | OBJ_PRIO(0)),
	METASPR_ITEM(16, 0, 14, OBJ_PAL(0) | OBJ_PRIO(0)),
	METASPR_ITEM(0, 16, 44, OBJ_PAL(0) | OBJ_PRIO(0)),
	METASPR_ITEM(16, 16, 46, OBJ_PAL(0) | OBJ_PRIO(0)),
	METASPR_TERM
};

const t_metasprite grid_metasprite4[] = {
	METASPR_ITEM(0, 0, 64, OBJ_PAL(0) | OBJ_PRIO(0)),
	METASPR_ITEM(16, 0, 66, OBJ_PAL(0) | OBJ_PRIO(0)),
	METASPR_ITEM(0, 16, 96, OBJ_PAL(0) | OBJ_PRIO(0)),
	METASPR_ITEM(16, 16, 98, OBJ_PAL(0) | OBJ_PRIO(0)),
	METASPR_TERM
};

const t_metasprite grid_metasprite5[] = {
	METASPR_ITEM(0, 0, 68, OBJ_PAL(0) | OBJ_PRIO(0)),
	METASPR_ITEM(16, 0, 70, OBJ_PAL(0) | OBJ_PRIO(0)),
	METASPR_ITEM(0, 16, 100, OBJ_PAL(0) | OBJ_PRIO(0)),
	METASPR_ITEM(16, 16, 102, OBJ_PAL(0) | OBJ_PRIO(0)),
	METASPR_TERM
};

const t_metasprite grid_metasprite6[] = {
	METASPR_ITEM(0, 0, 72, OBJ_PAL(0) | OBJ_PRIO(0)),
	METASPR_ITEM(16, 0, 74, OBJ_PAL(0) | OBJ_PRIO(0)),
	METASPR_ITEM(0, 16, 104, OBJ_PAL(0) | OBJ_PRIO(0)),
	METASPR_ITEM(16, 16, 106, OBJ_PAL(0) | OBJ_PRIO(0)),
	METASPR_TERM
};

const t_metasprite grid_metasprite7[] = {
	METASPR_ITEM(0, 0, 76, OBJ_PAL(0) | OBJ_PRIO(0)),
	METASPR_ITEM(16, 0, 78, OBJ_PAL(0) | OBJ_PRIO(0)),
	METASPR_ITEM(0, 16, 108, OBJ_PAL(0) | OBJ_PRIO(0)),
	METASPR_ITEM(16, 16, 110, OBJ_PAL(0) | OBJ_PRIO(0)),
	METASPR_TERM
};

const t_metasprite* grid_metasprites[8] = {
	grid_metasprite0, grid_metasprite1, grid_metasprite2, grid_metasprite3, grid_metasprite4, grid_metasprite5, grid_metasprite6, grid_metasprite7
};
