; spr_data.as — generated by opensnes-sprite 1.0.0; one ASSET_SECTION per blob, .include it from assets_gen.asm (the build does)

ASSET_SECTION "spr_tiles"
spr_tiles:
.incbin "spr.pic"
spr_tiles_end:
.ENDS

ASSET_SECTION "spr_pal"
spr_pal:
.incbin "spr.pal"
spr_pal_end:
.ENDS

