; town_data.as — generated by opensnes-level 1.0.0; one ASSET_SECTION per blob, .include it from assets_gen.asm (the build does)

ASSET_SECTION "town_BG1_map"
town_BG1_map:
.incbin "BG1.m16"
town_BG1_map_end:
.ENDS

ASSET_SECTION "town_BG1_quad"
town_BG1_quad:
.incbin "BG1.q16"
town_BG1_quad_end:
.ENDS

ASSET_SECTION "town_BG1_cells"
town_BG1_cells:
.incbin "BG1.c16"
town_BG1_cells_end:
.ENDS

ASSET_SECTION "town_tileattr"
town_tileattr:
.incbin "town.b16"
town_tileattr_end:
.ENDS

ASSET_SECTION "town_tiledef"
town_tiledef:
.incbin "town.t16"
town_tiledef_end:
.ENDS

ASSET_SECTION "town_objects"
town_objects:
.incbin "town.o16"
town_objects_end:
.ENDS

