OPENSNES := $(shell cd ../../../.. && pwd)

TARGET   := b2_far_ram.sfc
ROM_NAME := B2 FAR RAM TEST

USE_LIB  := 1
LIB_MODULES := console sprite dma background

CSRC   := main.c


include $(OPENSNES)/make/common.mk
