#!/usr/bin/env python3
"""Generate docs/tools/luna.md from the pinned luna binary's own --help.

Gaps review D3 (2026-09-14): the repository had no luna reference of its
own, and the versions its docs cited disagreed with each other. This
script writes ONE page from `luna --help` and `luna <cmd> --help` of the
binary `scripts/install-luna.sh` installs, stamped with the pinned
version, so the reference cannot drift from the pin: `make tests` runs
`--check`, which fails when the page differs from the installed pin's
--help (the lint job has no luna and skips it).

Run:  python3 devtools/gen_luna_doc.py          # regenerate the page
      python3 devtools/gen_luna_doc.py --check  # exit 1 if the page is stale
"""
from __future__ import annotations

import argparse
import re
import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
LUNA = ROOT / "tools" / "luna-test" / "bin" / "luna"
VERSION_FILE = ROOT / "tools" / "luna-test" / "luna.version"
OUT = ROOT / "docs" / "tools" / "luna.md"

HEADER = """# luna — command reference (pinned {version}) {{#tools_luna}}

<!-- GENERATED by devtools/gen_luna_doc.py from `luna --help`; do not edit.
     Regenerate after a pin bump: python3 devtools/gen_luna_doc.py -->

luna is the cycle-accurate emulator every OpenSNES test runs on
(`.claude/rules/testing.md`). The SDK pins one release in
`tools/luna-test/luna.version`; `scripts/install-luna.sh` fetches it and
`make tests` uses nothing else. This page is that release's own `--help`,
one section per subcommand, so what you read here is what the pinned
binary accepts — not a newer or older luna.

How the SDK uses it: `luna run` for corpus liveness and visual hashes,
`luna state --assert` for the runtime ROMs and probes, `luna test` for
the `tools/luna-test/manifests/*.toml`, `luna diff` for the Class A A/B,
`luna profile` for measured coverage and the cycle budget, `luna
wram-trace` behind the WRAM oracle. The MCP server (`luna mcp`) is the
interactive debugger (`docs/tutorials/debugging.md`).

"""


def help_of(*args: str) -> str:
    proc = subprocess.run([str(LUNA), *args, "--help"], capture_output=True, text=True, timeout=60)
    return (proc.stdout or proc.stderr).rstrip()


def subcommands(top: str) -> list[str]:
    out: list[str] = []
    in_cmds = False
    for line in top.splitlines():
        if line.startswith("Commands:"):
            in_cmds = True
            continue
        if in_cmds:
            if not line.strip() or not line.startswith(" "):
                break
            name = line.split()[0]
            if name != "help":
                out.append(name)
    return out


def render(version: str) -> str:
    top = help_of()
    parts = [HEADER.format(version=version)]
    parts.append("## `luna --help`\n\n```text\n" + top + "\n```\n")
    for cmd in subcommands(top):
        parts.append(f"\n## `luna {cmd}`\n\n```text\n" + help_of(cmd) + "\n```\n")
    return "\n".join(parts)


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    ap.add_argument("--check", action="store_true", help="exit 1 if docs/tools/luna.md is stale")
    args = ap.parse_args()
    if not LUNA.is_file():
        if args.check:
            # The lint job has no luna; the staleness check belongs to `make
            # tests`, which installs the pin. Say so rather than fail.
            print("luna doc: no pinned luna binary here, check skipped (make tests runs it)")
            return 0
        sys.exit("gen_luna_doc: no pinned luna binary (scripts/install-luna.sh first)")
    version = VERSION_FILE.read_text().strip()
    got = help_of()
    m = re.search(r"luna (\d+\.\d+\.\d+)", subprocess.run([str(LUNA), "--version"], capture_output=True, text=True).stdout)
    if m and f"v{m.group(1)}" != version:
        sys.exit(f"gen_luna_doc: installed luna is {m.group(1)} but the pin is {version} — run scripts/install-luna.sh")
    page = render(version)
    if args.check:
        if not OUT.is_file() or OUT.read_text() != page:
            print(f"STALE: {OUT.relative_to(ROOT)} does not match the pinned luna's --help; run devtools/gen_luna_doc.py")
            return 1
        print(f"luna doc: up to date ({version})")
        return 0
    OUT.write_text(page)
    print(f"wrote {OUT.relative_to(ROOT)} ({version}, {len(subcommands(got))} subcommands)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
