# Parallax Scrolling Example
# Two backgrounds with auto-scrolling

OPENSNES := $(shell cd ../../.. && pwd)

TARGET     := parallax.sfc
ROM_NAME   := PARALLAX SCROLL

USE_LIB    := 1
LIB_MODULES := console sprite dma

CSRC       := main.c
ASMSRC     := data.asm

include $(OPENSNES)/make/common.mk
