OPENSNES := $(shell cd ../../.. && pwd)

TARGET   := window_multi_hdma.sfc
ROM_NAME := WINDOW MULTI HDMA

USE_LIB  := 1
LIB_MODULES := console dma background hdma window input

CSRC   := main.c

include $(OPENSNES)/make/common.mk
