# Continuous Scroll Example
# Multi-layer parallax with sprite

OPENSNES := $(shell cd ../../.. && pwd)

TARGET     := continuous_scroll.sfc
ROM_NAME   := CONTINUOUS SCROLL

USE_LIB    := 1
LIB_MODULES := console sprite input background dma

CSRC       := main.c
ASMSRC     := data.asm

include $(OPENSNES)/make/common.mk
