# SSA Phi-Node Runtime Test

OPENSNES := $(shell cd ../.. && pwd)
TARGET   := test_phi.sfc
ROM_NAME := PHI-NODE TEST

CSRC     := main.c
USE_LIB  := 1
LIB_MODULES := console dma sprite input text

include $(OPENSNES)/make/common.mk
