# Mode 7 - Demonstrates Mode 7 rotation and scaling with joypad input

OPENSNES := $(shell cd ../../.. && pwd)

TARGET   := rotate_scale.sfc
ROM_NAME := OPENSNES MODE7

USE_LIB     := 1
LIB_MODULES := console dma background sprite input mode7

CSRC   := main.c
include $(OPENSNES)/make/common.mk
