# Super Scope Unit Test Makefile

OPENSNES := $(shell cd ../../.. && pwd)
TARGET   := test_superscope.sfc
ROM_NAME := SCOPE TESTS

CSRC     := test_superscope.c
USE_LIB  := 1
LIB_MODULES := console input text sprite dma

include $(OPENSNES)/make/common.mk
