/* Generated by palplan v1.0.0 — do not edit by hand.
 * Source manifest: project.txt
 *
 * Each palette gets its CGRAM colour index (pass as `startColor` to
 * dmaCopyCGram) and its slot number (the palette bank for gfx4snes -e
 * or OBJ_CGRAM_PAL()). Palettes with identical colours share a slot.
 */
#ifndef PALPLAN_H
#define PALPLAN_H

/* bg1 (bg, 16 colours) — bg slot 0 */
#define PAL_BG1_CGRAM  0
#define PAL_BG1_SLOT   0
#define PAL_BG1_COLORS 16

/* bg2 (bg, 16 colours) — bg slot 1 */
#define PAL_BG2_CGRAM  16
#define PAL_BG2_SLOT   1
#define PAL_BG2_COLORS 16

/* hud (bg, 4 colours) — bg slot 2 */
#define PAL_HUD_CGRAM  32
#define PAL_HUD_SLOT   2
#define PAL_HUD_COLORS 4

/* hero (sprite, 16 colours) — sprite slot 0 */
#define PAL_HERO_CGRAM  128
#define PAL_HERO_SLOT   0
#define PAL_HERO_COLORS 16

/* enemy (sprite, 16 colours) — sprite slot 1 */
#define PAL_ENEMY_CGRAM  144
#define PAL_ENEMY_SLOT   1
#define PAL_ENEMY_COLORS 16

/* boss (sprite, 16 colours) — sprite slot 0 (shared) */
#define PAL_BOSS_CGRAM  128
#define PAL_BOSS_SLOT   0
#define PAL_BOSS_COLORS 16

/* ghost (sprite, 16 colours) — sprite slot 2 */
#define PAL_GHOST_CGRAM  160
#define PAL_GHOST_SLOT   2
#define PAL_GHOST_COLORS 16

#endif /* PALPLAN_H */
