/* Generated by aseprite2snes v1.0.0 — do not edit by hand.
 * Source export: hero.json
 *
 * One AnimClip per Aseprite tag, for the OpenSNES anim.h player.
 * Frame values are metasprite-table indices (frame index x stride=1);
 * pair with a gfx4snes -P pointer table, or index OAM tiles directly.
 * Durations are Aseprite per-frame milliseconds converted at 60 fps.
 * Include this AFTER <snes.h> (needs AnimClip, ANIM_LOOP, ANIM_ONCE).
 */
#ifndef HERO_ANIM_H
#define HERO_ANIM_H

/* tag "walk" — forward, frames 0..3 */
static const u16 hero_walk_frames[] = { 0, 1, 2, 3 };
static const u8  hero_walk_durations[] = { 6, 6, 9, 6 };
static const AnimClip hero_walk = { hero_walk_frames, hero_walk_durations, 4, 0, ANIM_LOOP, 0 };

/* tag "idle" — forward, frames 4..5 */
static const u16 hero_idle_frames[] = { 4, 5 };
static const AnimClip hero_idle = { hero_idle_frames, 0, 2, 8, ANIM_LOOP, 0 };

/* tag "hurt" — pingpong, frames 6..7 */
static const u16 hero_hurt_frames[] = { 6, 7 };
static const AnimClip hero_hurt = { hero_hurt_frames, 0, 2, 3, ANIM_ONCE, 0 };

enum {
    HERO_ANIM_WALK = 0,
    HERO_ANIM_IDLE = 1,
    HERO_ANIM_HURT = 2,
    HERO_ANIM_COUNT = 3
};

static const AnimClip *const hero_anims[HERO_ANIM_COUNT] = {
    &hero_walk,
    &hero_idle,
    &hero_hurt,
};

#endif /* HERO_ANIM_H */
