OPENSNES := $(shell cd ../../../.. && pwd)

TARGET   := a7_32bit.sfc
ROM_NAME := A7 32BIT TEST

USE_LIB  := 1
LIB_MODULES := console sprite dma background

CSRC := main.c

include $(OPENSNES)/make/common.mk
