OPENSNES := $(shell cd ../../.. && pwd)

TARGET   := extbg.sfc
ROM_NAME := MODE7 EXTBG

USE_LIB  := 1
LIB_MODULES := console dma sprite input mode7 tile

CSRC := main.c

include $(OPENSNES)/make/common.mk
