; perspective_data.as — generated by opensnes-image 1.0.0; one ASSET_SECTION per blob, .include it from assets_gen.asm (the build does)

ASSET_SECTION "perspective_cos"
perspective_cos:
.incbin "perspective_cos.hdma"
perspective_cos_end:
.ENDS

ASSET_SECTION "perspective_sin"
perspective_sin:
.incbin "perspective_sin.hdma"
perspective_sin_end:
.ENDS

ASSET_SECTION "perspective_nsin"
perspective_nsin:
.incbin "perspective_nsin.hdma"
perspective_nsin_end:
.ENDS

