; scene_data.as — generated by opensnes-image 1.0.0; one ASSET_SECTION per blob, .include it from assets_gen.asm (the build does)

ASSET_SECTION "scene_tiles"
scene_tiles:
.incbin "scene.pic"
scene_tiles_end:
.ENDS

ASSET_SECTION "scene_pal"
scene_pal:
.incbin "scene.pal"
scene_pal_end:
.ENDS

