# Parallax Scrolling - HDMA-based multi-speed horizontal scroll (from PVSnesLib)

OPENSNES := $(shell cd ../../.. && pwd)

TARGET   := parallax_scroll.sfc
ROM_NAME := OPENSNES PARALLAX

USE_LIB     := 1
LIB_MODULES := console dma background sprite hdma input

CSRC   := main.c

include $(OPENSNES)/make/common.mk
