# PAL/NTSC Detection - PVSnesLib example ported to OpenSNES
# Tests isPAL() function

OPENSNES := $(shell cd ../.. && pwd)

TARGET   := typeconsole.sfc
ROM_NAME := OPENSNES  PAL  NTSC

USE_LIB  := 1
LIB_MODULES := console dma text background sprite

CSRC     := main.c

include $(OPENSNES)/make/common.mk
