OPENSNES := $(shell cd ../../.. && pwd)

TARGET     := timer.sfc
ROM_NAME   := VBLANK TIMER DEMO

USE_LIB    := 1
LIB_MODULES := console sprite dma background text input gameloop

CSRC       := main.c

include $(OPENSNES)/make/common.mk
