#!/usr/bin/env python3
"""
symmap - WLA-DX Symbol Map Analyzer for SNES Development

Parses .sym files generated by wlalink and provides:
- Memory layout visualization
- WRAM mirroring overlap detection
- Symbol search
- JSON/HTML export

Usage:
    symmap game.sym                           # Show memory layout
    symmap --check-overlap game.sym           # Check for WRAM mirror overlaps
    symmap --check-bank0-overflow game.sym    # Check for bank $00 ROM overflow
    symmap --find monster_x game.sym          # Find a symbol
    symmap --export-json game.sym             # Export to JSON
"""

import argparse
import json
import re
import sys
from dataclasses import dataclass, field
from pathlib import Path
from typing import Optional


# ANSI colors for terminal output
class Colors:
    RED = '\033[91m'
    GREEN = '\033[92m'
    YELLOW = '\033[93m'
    BLUE = '\033[94m'
    CYAN = '\033[96m'
    BOLD = '\033[1m'
    RESET = '\033[0m'

    @classmethod
    def disable(cls):
        cls.RED = cls.GREEN = cls.YELLOW = cls.BLUE = cls.CYAN = cls.BOLD = cls.RESET = ''


@dataclass
class Symbol:
    """Represents a symbol from the .sym file"""
    name: str
    bank: int
    address: int  # 16-bit address within bank
    full_address: int  # Full 24-bit address

    @property
    def is_in_wram_mirror(self) -> bool:
        """Check if this symbol is in the WRAM mirror range ($00:0000-$1FFF)"""
        return self.bank == 0x00 and self.address < 0x2000

    @property
    def is_in_wram(self) -> bool:
        """Check if this symbol is in Bank $7E WRAM"""
        return self.bank == 0x7E

    @property
    def mirror_address(self) -> Optional[int]:
        """If in WRAM or mirror, return the corresponding address in the other bank"""
        if self.is_in_wram_mirror:
            return 0x7E0000 + self.address
        elif self.is_in_wram and self.address < 0x2000:
            return self.address
        return None


@dataclass
class MemoryRegion:
    """A contiguous region of memory containing symbols"""
    bank: int
    start_address: int
    end_address: int
    symbols: list = field(default_factory=list)

    @property
    def size(self) -> int:
        return self.end_address - self.start_address + 1


@dataclass
class SectionRec:
    """A linker section from the .sym [sections] block"""
    name: str
    bank: int
    address: int  # CPU-visible address ($8000+ for LoROM)
    size: int


@dataclass
class Overlap:
    """Represents a memory overlap between two symbols"""
    bank0_symbol: Symbol
    bank7e_symbol: Symbol
    overlap_start: int
    overlap_end: int

    @property
    def overlap_size(self) -> int:
        return self.overlap_end - self.overlap_start + 1


class SymbolTable:
    """Parser and analyzer for WLA-DX .sym files"""

    # Bank descriptions for SNES LoROM
    BANK_DESCRIPTIONS = {
        0x00: "LoROM Bank 0 (WRAM Mirror $0000-$1FFF)",
        0x7E: "Work RAM (64KB)",
        0x7F: "Extended RAM (64KB)",
    }

    def __init__(self):
        self.symbols: dict[str, Symbol] = {}  # name -> Symbol
        self.banks: dict[int, list[Symbol]] = {}  # bank -> list of symbols
        self.sections: list[SectionRec] = []  # from the [sections] block
        self.ramsections: list[SectionRec] = []  # from the [ramsections] block

    def parse(self, sym_path: Path) -> None:
        """Parse a WLA-DX .sym file"""
        block = None
        with open(sym_path, 'r') as f:
            for line in f:
                line = line.strip()

                # Skip comments and empty lines
                if not line or line.startswith(';'):
                    continue

                if line.startswith('['):
                    block = line
                    continue

                # [sections] rows: "ROMOFF8 BB:AAAA CPUA SIZE8 name"
                # e.g. "00011167 02:1167 9167 0000000c .rodata.2"
                if block == '[sections]':
                    m = re.match(
                        r'^[0-9a-fA-F]{8}\s+([0-9a-fA-F]{2}):[0-9a-fA-F]{4}'
                        r'\s+([0-9a-fA-F]{4})\s+([0-9a-fA-F]{8})\s+(\S+)$', line)
                    if m:
                        self.sections.append(SectionRec(
                            name=m.group(4),
                            bank=int(m.group(1), 16),
                            address=int(m.group(2), 16),
                            size=int(m.group(3), 16)))
                    continue

                # [ramsections] rows: "BB:AAAA BBBB SIZE8 name" — the
                # first address is SLOT-relative, the second absolute
                # (they differ for SLOT 2 far sections: "7e:0000 2000").
                # e.g. "00:0700 0700 00000800 .dynamic_sprite_buffer"
                if block == '[ramsections]':
                    m = re.match(
                        r'^([0-9a-fA-F]{2}):([0-9a-fA-F]{4})\s+([0-9a-fA-F]{4})'
                        r'\s+([0-9a-fA-F]{8})\s+(\S+)$', line)
                    if m:
                        self.ramsections.append(SectionRec(
                            name=m.group(5),
                            bank=int(m.group(1), 16),
                            address=int(m.group(3), 16),
                            size=int(m.group(4), 16)))
                    continue

                # Try colon format first: "BB:AAAA symbol_name"
                # Example: "00:81b9 EmptyHandler"
                match = re.match(r'^([0-9a-fA-F]{2}):([0-9a-fA-F]{4})\s+(\S+)$', line)
                if match:
                    bank_str, addr_str, name = match.groups()
                    bank = int(bank_str, 16)
                    address = int(addr_str, 16)
                    full_addr = (bank << 16) | address
                else:
                    # Try legacy 8-char format: "00BBAAAA symbol_name"
                    match = re.match(r'^([0-9a-fA-F]{8})\s+(\S+)$', line)
                    if not match:
                        continue
                    full_addr_str, name = match.groups()
                    full_addr = int(full_addr_str, 16)
                    bank = (full_addr >> 16) & 0xFF
                    address = full_addr & 0xFFFF

                symbol = Symbol(
                    name=name,
                    bank=bank,
                    address=address,
                    full_address=full_addr
                )

                self.symbols[name] = symbol

                if bank not in self.banks:
                    self.banks[bank] = []
                self.banks[bank].append(symbol)

        # Sort symbols in each bank by address
        for bank in self.banks:
            self.banks[bank].sort(key=lambda s: s.address)

    def find_symbol(self, name: str, fuzzy: bool = False) -> list[Symbol]:
        """Find symbol(s) by name"""
        if not fuzzy:
            if name in self.symbols:
                return [self.symbols[name]]
            return []

        # Fuzzy match: find all symbols containing the search string
        results = []
        name_lower = name.lower()
        for sym_name, symbol in self.symbols.items():
            if name_lower in sym_name.lower():
                results.append(symbol)
        return sorted(results, key=lambda s: s.name)

    @staticmethod
    def _is_real_variable(sym: Symbol) -> bool:
        """
        Check if a symbol represents a real variable vs WLA-DX metadata or
        compiler infrastructure.

        Filtered out:
        - _sizeof_* : WLA-DX size calculation symbols
        - RAM_USAGE_* : RAM usage tracking markers
        - Labels with @, . suffixes: Compiler-generated internal labels
        - tcc__* : Compiler imaginary registers (intentionally in direct page)
        - __* : Other compiler internal symbols
        """
        name = sym.name

        # Skip WLA-DX size symbols
        if name.startswith('_sizeof_'):
            return False

        # Skip RAM usage markers
        if name.startswith('RAM_USAGE_'):
            return False

        # Skip compiler-generated internal labels (contain @ or end with .number)
        if '@' in name:
            return False

        # Skip section info labels
        if name.endswith('_START') or name.endswith('_END'):
            return False

        # Skip compiler imaginary registers (tcc__r0, tcc__r0h, tcc__r1, etc.)
        # These are intentionally in direct page ($00:0000-$00FF) and don't
        # actually conflict with WRAM bank $7E
        if name.startswith('tcc__'):
            return False

        # Skip other compiler internal symbols
        if name.startswith('__'):
            return False

        return True

    def check_wram_overlap(self) -> list[Overlap]:
        """
        Check for WRAM mirroring overlaps.

        CRITICAL: Bank $00:$0000-$1FFF mirrors Bank $7E:$0000-$1FFF.
        If both banks have symbols in the same address range, they will
        collide and overwrite each other!
        """
        overlaps = []

        # Get real variable symbols in the mirror ranges (filter out WLA-DX metadata)
        bank0_mirror = [s for s in self.banks.get(0x00, [])
                        if s.address < 0x2000 and self._is_real_variable(s)]
        bank7e_mirror = [s for s in self.banks.get(0x7E, [])
                         if s.address < 0x2000 and self._is_real_variable(s)]

        if not bank0_mirror or not bank7e_mirror:
            return []

        # Check each pair for overlap
        for s0 in bank0_mirror:
            for s7e in bank7e_mirror:
                # Check if ranges overlap
                # For now, assume each symbol is at least 1 byte
                # We can't know exact sizes without section info
                if s0.address == s7e.address:
                    overlaps.append(Overlap(
                        bank0_symbol=s0,
                        bank7e_symbol=s7e,
                        overlap_start=s0.address,
                        overlap_end=s0.address
                    ))

        # Also check for range overlaps by finding the extents
        if bank0_mirror and bank7e_mirror:
            bank0_min = min(s.address for s in bank0_mirror)
            bank0_max = max(s.address for s in bank0_mirror)
            bank7e_min = min(s.address for s in bank7e_mirror)
            bank7e_max = max(s.address for s in bank7e_mirror)

            # Check if ranges overlap at all
            if not (bank0_max < bank7e_min or bank7e_max < bank0_min):
                overlap_start = max(bank0_min, bank7e_min)
                overlap_end = min(bank0_max, bank7e_max)

                # Find which symbols are in the overlap range
                overlap_bank0 = [s for s in bank0_mirror
                                 if overlap_start <= s.address <= overlap_end]
                overlap_bank7e = [s for s in bank7e_mirror
                                  if overlap_start <= s.address <= overlap_end]

                if overlap_bank0 and overlap_bank7e:
                    # Create a single comprehensive overlap entry
                    overlaps.append(Overlap(
                        bank0_symbol=overlap_bank0[0],
                        bank7e_symbol=overlap_bank7e[0],
                        overlap_start=overlap_start,
                        overlap_end=overlap_end
                    ))

        return overlaps

    @staticmethod
    def _is_c_generated_data(sym: Symbol) -> bool:
        """Check if a symbol is C-generated const data that uses 16-bit addressing.

        The compiler (cproc/QBE) generates 16-bit addresses for:
        - String literals: string.N (or <tu>_string.N — per-TU-namespaced since
          the anonymous-label uniquing fix)
        - Static local const data: varname.N (e.g., size_mask.13)

        These are accessed via `pea.w` / `lda.l $0000,x` which always read bank $00.
        If they spill to bank $01+, the code silently reads garbage.

        NOT at risk (use 24-bit jsl/jml addressing):
        - Functions (code in .text sections, called via jsl)
        - Assembly-defined data (font tiles, soundbank — use explicit banks)
        """
        name = sym.name

        # String literals from C code (most common victim). Since the
        # anonymous-label uniquing fix these carry a per-TU prefix (<tu>_string.N).
        if re.match(r'^(?:\w+_)?string\.\d+$', name):
            return True

        # Static local const data: C identifier followed by .N
        # Examples: size_mask.13, ball_speeds.5
        # This pattern is generated by cproc/QBE for static locals
        if re.match(r'^[a-zA-Z_][a-zA-Z0-9_]*\.\d+$', name):
            return True

        return False

    def check_bank0_rom_overflow(self) -> tuple[list[Symbol], list[Symbol], int]:
        """Check for C-generated data that spilled from bank $00 to bank $01+.

        The C compiler generates 16-bit addresses (always bank $00) for string
        literals and const data. When bank $00 ROM fills up ($8000-$FFFF = 32KB),
        WLA-DX places new SUPERFREE sections in bank $01+ — but the code still
        reads bank $00, silently returning garbage data.

        Returns:
            (critical_spills, warning_spills, bank0_free_bytes)
            - critical_spills: string.N symbols in bank $01+ (always a bug —
              string literals are always accessed by the code that defines them)
            - warning_spills: other C data (varname.N) in bank $01+ (might be
              dead code from linked-but-uncalled library functions)
            - bank0_free_bytes: free space remaining in bank $00 ROM area
        """
        critical = []
        warnings = []

        # Check all banks > $00 for C-generated DATA symbols
        for bank, symbols in self.banks.items():
            if bank == 0x00:
                continue
            for sym in symbols:
                if sym.address < 0x8000:
                    continue
                if re.match(r'^(?:\w+_)?string\.\d+$', sym.name):
                    critical.append(sym)
                elif self._is_c_generated_data(sym):
                    warnings.append(sym)

        # QBE emits every C const datum into a ".rodata.N" SUPERFREE section.
        # Any such section landing in bank $01+ is read as garbage by the
        # 16-bit C deref — UNLESS it only holds __opensnes_force_emit_*
        # anchors, which exist for the linker and are never read.
        # Caught 2026-07-07: likemario's anim clips (named top-level statics,
        # no `.N` suffix, so invisible to the symbol heuristics above)
        # spilled to bank $02 and shipped a silently dead animation.
        already = {(s.bank, s.address) for s in critical}
        for sec in self.sections:
            if sec.bank == 0x00 or not re.match(r'^\.rodata\.\d+$', sec.name):
                continue
            contained = [s for s in self.banks.get(sec.bank, [])
                         if sec.address <= s.address < sec.address + sec.size
                         and not s.name.startswith('_sizeof_')]
            live = [s for s in contained
                    if not s.name.startswith('__opensnes_force_emit_')]
            for sym in live:
                if (sym.bank, sym.address) not in already:
                    critical.append(sym)
                    already.add((sym.bank, sym.address))

        # Calculate bank $00 ROM free space
        bank0_syms = self.banks.get(0x00, [])
        bank0_rom = [s for s in bank0_syms if s.address >= 0x8000]
        if bank0_rom:
            highest = max(s.address for s in bank0_rom)
            # Check _sizeof_ for the highest symbol to get its actual end
            highest_sym = [s for s in bank0_rom if s.address == highest][0]
            sizeof_name = f'_sizeof_{highest_sym.name}'
            if sizeof_name in self.symbols:
                # _sizeof_ values are stored as full_address (the raw parsed value)
                size = self.symbols[sizeof_name].full_address
                bank0_free = 0x10000 - (highest + size)
            else:
                # Assume at least 1 byte for the symbol
                bank0_free = 0x10000 - (highest + 1)
        else:
            bank0_free = 0x8000  # Empty bank $00 ROM = 32KB free

        return critical, warnings, bank0_free

    def get_memory_map(self) -> dict:
        """Generate a memory map summary"""
        result = {}

        for bank, symbols in sorted(self.banks.items()):
            bank_info = {
                'description': self.BANK_DESCRIPTIONS.get(bank, f"Bank ${bank:02X}"),
                'symbol_count': len(symbols),
                'symbols': []
            }

            for sym in symbols:
                bank_info['symbols'].append({
                    'name': sym.name,
                    'address': f"${sym.address:04X}",
                    'full_address': f"${sym.full_address:06X}",
                    'in_wram_mirror': sym.is_in_wram_mirror,
                })

            result[f"${bank:02X}"] = bank_info

        return result


def print_memory_layout(table: SymbolTable, verbose: bool = False):
    """Print a formatted memory layout"""
    print(f"{Colors.BOLD}=== Memory Layout ==={Colors.RESET}\n")

    for bank in sorted(table.banks.keys()):
        symbols = table.banks[bank]
        desc = table.BANK_DESCRIPTIONS.get(bank, "")

        print(f"{Colors.CYAN}BANK ${bank:02X}{Colors.RESET}", end="")
        if desc:
            print(f" ({desc})")
        else:
            print()

        if verbose:
            for sym in symbols:
                warning = ""
                if sym.is_in_wram_mirror:
                    warning = f" {Colors.YELLOW}[WRAM Mirror]{Colors.RESET}"
                print(f"  ${sym.address:04X}  {sym.name}{warning}")
        else:
            # Show summary
            if symbols:
                print(f"  ${symbols[0].address:04X}-${symbols[-1].address:04X}  "
                      f"({len(symbols)} symbols)")

        print()


def print_overlap_check(table: SymbolTable) -> int:
    """Check and print WRAM mirror overlaps. Returns exit code."""
    overlaps = table.check_wram_overlap()

    # Get REAL variable symbols in each mirror range (filter out WLA-DX metadata)
    bank0_mirror = [s for s in table.banks.get(0x00, [])
                    if s.address < 0x2000 and table._is_real_variable(s)]
    bank7e_mirror = [s for s in table.banks.get(0x7E, [])
                     if s.address < 0x2000 and table._is_real_variable(s)]

    if not bank0_mirror and not bank7e_mirror:
        print(f"{Colors.GREEN}OK: No symbols in WRAM mirror range{Colors.RESET}")
        return 0

    if not bank0_mirror or not bank7e_mirror:
        print(f"{Colors.GREEN}OK: Only one bank uses WRAM mirror range{Colors.RESET}")
        print(f"  Bank $00: {len(bank0_mirror)} real variables in $0000-$1FFF")
        print(f"  Bank $7E: {len(bank7e_mirror)} real variables in $0000-$1FFF")
        return 0

    # Both banks have symbols - check for EXACT address collisions
    # We only flag an error if the SAME address is used in BOTH banks

    # Filter out reserved placeholder symbols (intentional space reservations)
    # These symbols start with '_reserved' and exist to prevent linker placement
    bank0_real = [s for s in bank0_mirror if not s.name.startswith('_reserved')]

    if not bank0_real:
        print(f"{Colors.GREEN}OK: Bank $00 only has reserved placeholder symbols{Colors.RESET}")
        return 0

    bank0_max = max(s.address for s in bank0_real)
    bank7e_min = min(s.address for s in bank7e_mirror)
    bank7e_max = max(s.address for s in bank7e_mirror)

    # Build address sets for precise collision detection
    bank0_addresses = set(s.address for s in bank0_real)
    bank7e_addresses = set(s.address for s in bank7e_mirror)

    # Check for oamMemory buffer range (544 bytes starting at its address)
    OAM_BUFFER_SIZE = 544  # 512 main + 32 high table
    for s in bank7e_mirror:
        if s.name == 'oamMemory':
            # Add all addresses in the oamMemory buffer to the collision set
            for i in range(OAM_BUFFER_SIZE):
                bank7e_addresses.add(s.address + i)
            break

    # Find actual collisions - addresses used in BOTH banks
    collisions = bank0_addresses & bank7e_addresses

    if not collisions:
        print(f"{Colors.GREEN}OK: No address collisions detected{Colors.RESET}")
        print(f"  Bank $00: $0000-${bank0_max:04X} ({len(bank0_mirror)} symbols)")
        print(f"  Bank $7E: ${bank7e_min:04X}-${bank7e_max:04X} ({len(bank7e_mirror)} symbols)")
        return 0

    # Get the actual colliding symbols
    bank0_colliding = [s for s in bank0_mirror if s.address in collisions]
    bank7e_colliding = [s for s in bank7e_mirror if s.address in collisions]

    # COLLISION DETECTED!
    print(f"{Colors.RED}{Colors.BOLD}ERROR: WRAM Mirror Collision Detected!{Colors.RESET}\n")

    print(f"{Colors.YELLOW}Bank $00 symbols at collision addresses:{Colors.RESET}")
    for s in bank0_colliding[:10]:
        print(f"  ${s.address:04X}  {s.name}")
    if len(bank0_colliding) > 10:
        print(f"  ... and {len(bank0_colliding) - 10} more")

    print()
    print(f"{Colors.YELLOW}Bank $7E symbols at collision addresses:{Colors.RESET}")
    for s in bank7e_colliding[:10]:
        print(f"  ${s.address:04X}  {s.name}")
    if len(bank7e_colliding) > 10:
        print(f"  ... and {len(bank7e_colliding) - 10} more")

    print()
    print(f"{Colors.RED}COLLISION:{Colors.RESET} {len(collisions)} address(es) used in BOTH Bank $00 and Bank $7E!")
    collision_list = sorted(collisions)[:5]
    print(f"  Colliding addresses: {', '.join(f'${a:04X}' for a in collision_list)}")
    print()
    print(f"{Colors.CYAN}FIX:{Colors.RESET} Use ORGA to place Bank $7E buffers above ${bank0_max + 1:04X}")
    print(f"     Example: .RAMSECTION \"buffer\" BANK $7E SLOT 1 ORGA ${bank0_max + 0x100:04X} FORCE")

    return 1


# What counts as bulk read-only payload. Matched EXACTLY, not guessed:
# `.rodata*` is what QBE emits for C const data, and `asset.*` is what
# templates/assets.inc's ASSET_SECTION macro produces. An earlier version
# classified by name hints and flagged `.text.bgSetMapPtr` (it contains
# "map") and `.nmi` — a report you cannot trust is worse than none.
# Hand-written sections that opt out of the macro are simply not counted.
_ASSET_PREFIXES = (".rodata", "asset.", ".asset.")


def _is_asset_payload(name: str) -> bool:
    low = name.lower()
    return any(low.startswith(p) for p in _ASSET_PREFIXES)


def report_bank0_asset_payload(table: SymbolTable, min_report: int = 1024) -> None:
    """Print how much bulk read-only data ended up in bank $00.

    Bank $00 is the code bank. Assets do not need to be there — anything
    handed to a lib DMA function travels as a far pointer, and anything C
    reads through a `const` pointer is a far read since #121. But
    SUPERFREE picks the first bank that fits, which IS bank $00, so they
    land there by default and quietly spend the budget that code needs.

    This is the instrument for that: a number, printed at every link, so
    "my bank $00 is mysteriously full" becomes "12 KB of maps are sitting
    in it". See templates/assets.inc and issue #127.
    """
    payload = [sec for sec in table.sections
               if sec.bank == 0 and _is_asset_payload(sec.name)]
    total = sum(sec.size for sec in payload)
    if total < min_report:
        return
    print(f"{Colors.YELLOW}NOTE: {total} bytes of asset data are in bank $00 "
          f"(the code bank).{Colors.RESET}")
    for sec in sorted(payload, key=lambda x: -x.size)[:5]:
        print(f"  {sec.size:6d}  {sec.name}")
    if len(payload) > 5:
        print(f"  … and {len(payload) - 5} more")
    print("  Assets travel as far pointers (DMA) or const far reads (#121),")
    print("  so they can live in any bank. See templates/assets.inc.")


def print_bank0_overflow_check(table: SymbolTable, warn_threshold: int = 2048,
                                fail_threshold: int = 0) -> int:
    """Check and print bank $00 ROM overflow status. Returns exit code.

    Exit code 1 (hard fail): string literals spilled to bank $01+, OR free
        space below ``fail_threshold`` (when fail_threshold > 0). The latter
        catches "imminent overflow" — one new const literal away from a 🔴
        silent corruption — before it ships.
    Exit code 2: bank $00 free space below warn_threshold (soft warning).
    Exit code 0: no critical spills and free space above thresholds.

    fail_threshold of 0 (default) preserves the historical behaviour of
    failing only on actual spill. CI-tightening is a deliberate ratchet —
    see ``.claude/rules/bank0_budget.md`` for the policy.
    """
    critical, warnings, free_bytes = table.check_bank0_rom_overflow()

    if critical:
        # Post-#121 (const-load `cst` marker): C reads of const-qualified
        # data use FAR addressing, so a spilled const section is read
        # CORRECTLY from any bank by C code. The per-TU pattern guard
        # (devtools/check_bank_reads.py, hardened 2026-07-20) hard-fails
        # any remaining bank-blind read of these symbols, and the lib's
        # hand-written ASM was audited: all its C-const reads use `.l`
        # long addressing. Placement alone is therefore a WARNING now —
        # the read-pattern guard owns the verdict.
        print(f"{Colors.YELLOW}NOTE: C const data spilled to bank $01+ "
              f"(safe post-#121: C const reads are far;{Colors.RESET}")
        print(f"{Colors.YELLOW}check_bank_reads enforces the patterns):{Colors.RESET}")
        for sym in critical:
            print(f"  ${sym.bank:02X}:{sym.address:04X}  {sym.name}")
        if warnings:
            for sym in warnings:
                print(f"  ${sym.bank:02X}:{sym.address:04X}  {sym.name} (maybe unused)")
        print(f"  Bank $00 ROM free: {free_bytes} bytes")

    if warnings:
        print(f"{Colors.YELLOW}WARNING: C const data spilled to bank $01+ "
              f"(may be unused):{Colors.RESET}")
        for sym in warnings:
            print(f"  ${sym.bank:02X}:{sym.address:04X}  {sym.name}")
        print(f"  Bank $00 ROM free: {free_bytes} bytes")
        if free_bytes < warn_threshold:
            print(f"{Colors.YELLOW}WARNING: Bank $00 ROM nearly full "
                  f"({free_bytes} bytes free, threshold: {warn_threshold}){Colors.RESET}")
            report_bank0_asset_payload(table)
            return 2
        report_bank0_asset_payload(table)
        return 0

    # Hard-fail ratchet: free space below fail_threshold is treated as imminent
    # overflow. Default 0 (disabled) preserves historical behaviour; the build
    # system can opt in via BANK0_FAIL_THRESHOLD.
    if fail_threshold > 0 and free_bytes < fail_threshold:
        print(f"{Colors.RED}{Colors.BOLD}FAIL: Bank $00 ROM imminent overflow "
              f"({free_bytes} bytes free, fail-threshold: {fail_threshold}){Colors.RESET}")
        print("  One more const literal here will spill to bank $01+ and read")
        print("  as garbage at runtime (see KNOWN_LIMITATIONS.md, severity 🔴).")
        print(f"  See .claude/rules/bank0_budget.md for the refactor playbook.")
        return 1

    # No spills — check for low free space warning
    if free_bytes < warn_threshold:
        print(f"{Colors.YELLOW}WARNING: Bank $00 ROM nearly full "
              f"({free_bytes} bytes free, threshold: {warn_threshold}){Colors.RESET}")
        print("  Adding more const data or string literals may cause overflow.")
        report_bank0_asset_payload(table)
        return 2

    print(f"{Colors.GREEN}OK: No C-generated data in bank $01+ "
          f"(bank $00 ROM free: {free_bytes} bytes){Colors.RESET}")
    report_bank0_asset_payload(table)
    return 0


def print_ram_budget_check(table: SymbolTable, warn_threshold: int = 1024,
                           fail_threshold: int = 0) -> int:
    """Check and print C RAM band ($00:0000-$1FFF) budget status.

    The compiler's RAM addressing is bank-$00-implicit (`sta.l $0000,x`)
    for plain objects, so C RAM lives in the 8 KB WRAM mirror below $2000
    (KNOWN_LIMITATIONS.md); `__far` objects (chantier B2) are the escape
    hatch into $7E:2000-$FFFF, reported separately. This is the RAM twin of
    the bank $00 ROM ratchet: it turns "are we near the 8 KB ceiling?"
    into a number printed at every link, instead of a silent-corruption
    surprise when the ceiling is hit.

    Exit code 1 (hard fail): a bank-$00 RAM section crosses or sits past
        $2000 (its C accesses are silently wrong / collide with hardware
        registers), OR free space below ``fail_threshold`` (> 0).
    Exit code 2: free space below ``warn_threshold`` (soft warning, with
        the largest sections listed as refactor candidates).
    Exit code 0: within budget.
    """
    BAND_END = 0x2000

    band = [s for s in table.ramsections
            if s.bank == 0x00 and s.address < BAND_END]
    out_of_band = [s for s in table.ramsections
                   if s.bank == 0x00 and BAND_END <= s.address < 0x8000]
    crossers = [s for s in band if s.address + s.size > BAND_END]

    if not band and not out_of_band:
        # Older .sym without a [ramsections] block: fall back to wlalink's
        # high-water marker if present.
        end = table.symbols.get('RAM_USAGE_SLOT_1_BANK_0_END')
        if end is None:
            print(f"{Colors.YELLOW}NOTE: no [ramsections] block and no "
                  f"RAM_USAGE marker — C RAM budget not measurable{Colors.RESET}")
            return 0
        used_top = end.address + 1
        free_bytes = BAND_END - used_top
        total = used_top  # no per-section detail available
        nsections = 0
    else:
        used_top = max(s.address + s.size for s in band) if band else 0
        free_bytes = BAND_END - used_top
        total = sum(s.size for s in band)
        nsections = len(band)

    if crossers or out_of_band:
        print(f"{Colors.RED}{Colors.BOLD}FAIL: C RAM outside the $0000-$1FFF "
              f"band!{Colors.RESET}\n")
        print("The compiler's RAM addressing is bank-$00-implicit, so RAM")
        print("past $1FFF is silently wrong-banked (or collides with the")
        print("hardware registers at $2100+). These sections are affected:\n")
        for s in crossers:
            print(f"  {Colors.RED}$00:{s.address:04X}+{s.size:04X}{Colors.RESET}"
                  f"  {s.name}  (crosses $2000)")
        for s in out_of_band:
            print(f"  {Colors.RED}$00:{s.address:04X}+{s.size:04X}{Colors.RESET}"
                  f"  {s.name}  (entirely past $2000)")
        print("\nFIX: shrink RAM usage below the 8 KB band (see the section")
        print("     list via --check-ram-budget on a passing build), or keep")
        print("     the data ASM-only with explicit bank addressing.")
        return 1

    if fail_threshold > 0 and free_bytes < fail_threshold:
        print(f"{Colors.RED}{Colors.BOLD}FAIL: C RAM band nearly full "
              f"({free_bytes} bytes free, fail-threshold: {fail_threshold})"
              f"{Colors.RESET}")
        print("  The next RAMSECTION may not fit below $2000 — C reads of")
        print("  anything placed higher are silently wrong (defect B2).")
        return 1

    if free_bytes < warn_threshold:
        print(f"{Colors.YELLOW}WARNING: C RAM band nearly full "
              f"({free_bytes} bytes free below $2000, threshold: "
              f"{warn_threshold}){Colors.RESET}")
        biggest = sorted(band, key=lambda s: s.size, reverse=True)[:3]
        if biggest:
            print("  Largest RAM sections (refactor candidates):")
            for s in biggest:
                print(f"    {s.size:5d} bytes  {s.name}")
        return 2

    print(f"{Colors.GREEN}OK: C RAM band $0000-$1FFF: {free_bytes} bytes free "
          f"(top at ${used_top:04X}; {total} bytes in {nsections} sections)"
          f"{Colors.RESET}")
    # Chantier B2: the second band. __far C objects (QBE `.far.N` sections)
    # and lib bank-$7E state live in $7E:2000-$FFFF (56 KB, SLOT 2). No
    # threshold yet — the number is the instrument.
    far = [s for s in table.ramsections
           if s.bank == 0x7E and 0x2000 <= s.address < 0x10000]
    if far:
        far_top = max(s.address + s.size for s in far)
        far_total = sum(s.size for s in far)
        far_c = sum(s.size for s in far if s.name.startswith('.far.'))
        print(f"{Colors.GREEN}OK: far RAM band $7E:2000-$FFFF: "
              f"{0x10000 - far_top} bytes free (top at ${far_top:04X}; "
              f"{far_total} bytes in {len(far)} sections, {far_c} bytes "
              f"of C __far objects){Colors.RESET}")
    return 0


def print_symbol_search(table: SymbolTable, name: str):
    """Search for and print symbol information"""
    results = table.find_symbol(name, fuzzy=True)

    if not results:
        print(f"{Colors.YELLOW}No symbols found matching '{name}'{Colors.RESET}")
        return

    print(f"{Colors.BOLD}Found {len(results)} symbol(s):{Colors.RESET}\n")

    for sym in results:
        print(f"{Colors.CYAN}{sym.name}{Colors.RESET}")
        print(f"  Address: ${sym.bank:02X}:{sym.address:04X} (${sym.full_address:06X})")

        # Warnings
        if sym.is_in_wram_mirror:
            print(f"  {Colors.YELLOW}WARNING: In WRAM mirror range ($0000-$1FFF){Colors.RESET}")
            print(f"           This address is shared with $7E:{sym.address:04X}")

        print()


def export_json(table: SymbolTable) -> str:
    """Export memory map to JSON"""
    data = {
        'symbols': {},
        'banks': {},
        'wram_overlap_check': None
    }

    # Export all symbols
    for name, sym in table.symbols.items():
        data['symbols'][name] = {
            'bank': sym.bank,
            'address': sym.address,
            'full_address': sym.full_address,
            'in_wram_mirror': sym.is_in_wram_mirror
        }

    # Export bank summaries
    for bank, symbols in table.banks.items():
        data['banks'][f"0x{bank:02X}"] = {
            'symbol_count': len(symbols),
            'address_range': {
                'min': min(s.address for s in symbols) if symbols else 0,
                'max': max(s.address for s in symbols) if symbols else 0
            }
        }

    # Export overlap check result
    overlaps = table.check_wram_overlap()
    data['wram_overlap_check'] = {
        'has_overlap': len(overlaps) > 0,
        'overlaps': [
            {
                'bank0_symbol': o.bank0_symbol.name,
                'bank7e_symbol': o.bank7e_symbol.name,
                'address_range': f"${o.overlap_start:04X}-${o.overlap_end:04X}"
            }
            for o in overlaps
        ]
    }

    return json.dumps(data, indent=2)


def main():
    parser = argparse.ArgumentParser(
        description='WLA-DX Symbol Map Analyzer for SNES Development',
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog="""
Examples:
  symmap game.sym                          Show memory layout summary
  symmap -v game.sym                       Show detailed memory layout
  symmap --check-overlap game.sym          Check for WRAM mirror overlaps
  symmap --check-bank0-overflow game.sym   Check for bank $00 ROM overflow
  symmap --check-bank0-overflow --warn-threshold 4096 game.sym
  symmap --find monster_x game.sym         Find symbol by name
  symmap --export-json game.sym            Export to JSON format
"""
    )

    parser.add_argument('sym_file', type=Path, help='Path to .sym file')
    parser.add_argument('-v', '--verbose', action='store_true',
                        help='Show all symbols in memory layout')
    parser.add_argument('--check-overlap', action='store_true',
                        help='Check for WRAM mirror overlaps (main use case)')
    parser.add_argument('--check-ram-budget', action='store_true',
                        help='Check C RAM band ($00:0000-$1FFF) usage — the RAM '
                             'twin of the bank $00 ROM ratchet (defect B2)')
    parser.add_argument('--ram-warn-threshold', type=int, default=1024, metavar='N',
                        help='Warn when C RAM band free space drops below N bytes '
                             '(default: 1024)')
    parser.add_argument('--ram-fail-threshold', type=int, default=0, metavar='N',
                        help='Fail when C RAM band free space drops below N bytes '
                             '(default: 0 = disabled)')
    parser.add_argument('--check-bank0-overflow', action='store_true',
                        help='Check for C-generated data that spilled from bank $00')
    parser.add_argument('--warn-threshold', type=int, default=2048, metavar='N',
                        help='Free space threshold (bytes) for bank $00 warning (default: 2048)')
    parser.add_argument('--fail-threshold', type=int, default=0, metavar='N',
                        help='Free space threshold (bytes) for bank $00 imminent-overflow '
                             'hard-fail (default: 0 = disabled). Catches one-const-away-from-spill.')
    parser.add_argument('--find', metavar='NAME',
                        help='Find symbol by name (fuzzy match)')
    parser.add_argument('--export-json', action='store_true',
                        help='Export memory map to JSON')
    parser.add_argument('--no-color', action='store_true',
                        help='Disable colored output')

    args = parser.parse_args()

    # Disable colors if requested or not a TTY
    if args.no_color or not sys.stdout.isatty():
        Colors.disable()

    # Check file exists
    if not args.sym_file.exists():
        print(f"{Colors.RED}ERROR: File not found: {args.sym_file}{Colors.RESET}",
              file=sys.stderr)
        return 1

    # Parse symbol file
    table = SymbolTable()
    try:
        table.parse(args.sym_file)
    except Exception as e:
        print(f"{Colors.RED}ERROR: Failed to parse {args.sym_file}: {e}{Colors.RESET}",
              file=sys.stderr)
        return 1

    print(f"Loaded {len(table.symbols)} symbols from {args.sym_file.name}\n")

    # Handle requested operation
    if args.export_json:
        print(export_json(table))
        return 0

    if args.check_overlap:
        return print_overlap_check(table)

    if args.check_ram_budget:
        return print_ram_budget_check(table,
                                      warn_threshold=args.ram_warn_threshold,
                                      fail_threshold=args.ram_fail_threshold)

    if args.check_bank0_overflow:
        return print_bank0_overflow_check(table,
                                          warn_threshold=args.warn_threshold,
                                          fail_threshold=args.fail_threshold)

    if args.find:
        print_symbol_search(table, args.find)
        return 0

    # Default: show memory layout
    print_memory_layout(table, verbose=args.verbose)
    return 0


if __name__ == '__main__':
    sys.exit(main())
