/**
 * @file lzss.h
 * @brief LZSS (LZ77) Decompression for SNES
 *
 * Provides LZ77 decompression directly to VRAM. Used for compressed
 * tile/tilemap data generated by gfx4snes or external LZ77 tools.
 *
 * ## LZ77 Format
 *
 * - Tag byte: 0x10
 * - 3-byte little-endian uncompressed data length
 * - Flag bytes: 8 bits each (1=reference, 0=literal)
 * - References: 12-bit distance, 4-bit length (min 3 bytes)
 *
 * ## Usage
 *
 * @code
 * extern u8 compressed_tiles[], compressed_tiles_end[];
 *
 * // Decompress to VRAM during force blank
 * REG_INIDISP = 0x80;  // Force blank (required for VRAM writes)
 * LzssDecodeVram(compressed_tiles, 0x0000);
 * REG_INIDISP = 0x0F;  // Screen on, full brightness
 * @endcode
 *
 * @warning VRAM writes must happen during VBlank or force blank.
 *          LzssDecodeVram disables interrupts internally, so call it
 *          during force blank for safety.
 *
 * @author OpenSNES Team (ported from PVSnesLib by Alekmaul)
 * @copyright zlib License
 */

#ifndef OPENSNES_LZSS_H
#define OPENSNES_LZSS_H

#include <snes/types.h>

/**
 * @brief Decompress LZ77 data directly to VRAM
 *
 * Reads LZ77-compressed data from ROM/RAM and writes decompressed
 * output directly to VRAM via PPU registers. Disables interrupts
 * during decompression to prevent NMI handler from interfering.
 *
 * @param source Pointer to LZ77-compressed data (tag byte 0x10)
 * @param address VRAM word address to write decompressed data
 *
 * @note The source data must start with the LZ77 tag byte (0x10).
 *       If the tag doesn't match, the function returns immediately.
 * @note Interrupts are disabled during decompression and restored after.
 */
void LzssDecodeVram(u8 *source, u16 address);

#endif /* OPENSNES_LZSS_H */
