/**
 * @file lzss.h
 * @brief LZSS (LZ77) Decompression for SNES
 *
 * Provides LZ77 decompression directly to VRAM. Used for compressed
 * tile/tilemap data generated by gfx4snes or external LZ77 tools.
 *
 * ## LZ77 Format
 *
 * - Tag byte: 0x10
 * - 3-byte little-endian uncompressed data length
 * - Flag bytes: 8 bits each (1=reference, 0=literal)
 * - References: 12-bit distance, 4-bit length (min 3 bytes)
 *
 * ## Usage
 *
 * @code
 * extern u8 compressed_tiles[], compressed_tiles_end[];
 *
 * // Decompress to VRAM during force blank
 * REG_INIDISP = 0x80;  // Force blank (required for VRAM writes)
 * lzssDecodeVram(compressed_tiles, 0x0000);
 * REG_INIDISP = 0x0F;  // Screen on, full brightness
 * @endcode
 *
 * @warning VRAM writes must happen during VBlank or force blank.
 *          LzssDecodeVram disables interrupts internally, so call it
 *          during force blank for safety.
 *
 * @author OpenSNES Team (ported from PVSnesLib by Alekmaul)
 * @copyright zlib License
 */

#ifndef OPENSNES_LZSS_H
#define OPENSNES_LZSS_H

#include <snes/types.h>

/**
 * @brief Decompress LZ77 data directly to VRAM
 *
 * Reads LZ77-compressed data from ROM/RAM and writes decompressed
 * output directly to VRAM via PPU registers. It masks IRQs (`sei`) for the
 * duration; it does NOT mask NMI — `sei` cannot — so call it under forced
 * blank, where the NMI handler's own VRAM traffic is not a concern.
 *
 * @param source Pointer to LZ77-compressed data (tag byte 0x10)
 * @param address VRAM word address to write decompressed data
 *
 * @note The source data must start with the LZ77 tag byte (0x10).
 *       If the tag doesn't match, the function returns immediately.
 * @note IRQs are masked during decompression and restored after; NMI is not.
 * @note The source may be in any bank (the bank byte of the pointer is
 *       honoured since 2026-09-20). VMAIN is left at $00 on return.
 */
void lzssDecodeVram(const u8 *source, u16 address);

/** @brief The pre-2026-09-22 spelling of lzssDecodeVram() — the one
 *         capitalised function of the SDK. Same routine. */
OPENSNES_DEPRECATED("use lzssDecodeVram() (lower-case l, like every other function)")
void LzssDecodeVram(const u8 *source, u16 address);

#endif /* OPENSNES_LZSS_H */
