OPENSNES := $(shell cd ../../.. && pwd)

TARGET     := random.sfc
ROM_NAME   := RANDOM NUMBER DEMO

USE_LIB    := 1
LIB_MODULES := console sprite dma background text input

CSRC       := main.c

include $(OPENSNES)/make/common.mk
