OPENSNES := $(shell cd ../../.. && pwd)

TARGET     := aim_target.sfc
ROM_NAME   := AIM TARGET DEMO

USE_LIB    := 1
LIB_MODULES := console sprite dma background text input gameloop math fixed32

CSRC       := main.c

include $(OPENSNES)/make/common.mk
