# Dynamic Metasprite Engine Example Makefile

OPENSNES := $(shell cd ../../.. && pwd)
TARGET   := dynamic_metasprite.sfc
ROM_NAME := DYN_METASPRITE_DEMO

CSRC     := main.c

USE_LIB  := 1
LIB_MODULES := console sprite sprite_dynamic sprite_dynamic_meta sprite_lut dma background text input

include $(OPENSNES)/make/common.mk
