OPENSNES := $(shell cd ../../../.. && pwd)
TARGET   := transparency.sfc
ROM_NAME := OPENSNES TRANSPARENCY

USE_LIB     := 1
LIB_MODULES := console dma background sprite input

CSRC   := main.c
ASMSRC := data.asm

include $(OPENSNES)/make/common.mk
