/* blip.h — generated by opensnes-sample from blip.wav; do not edit */
#ifndef OPENSNES_SAMPLE_blip_H
#define OPENSNES_SAMPLE_blip_H

#include <snes.h>

extern u8 blip_brr[], blip_brr_end[];   /* the .incbin in assets_gen.asm (or your data.asm) */
#define blip_brr_size 684   /* bytes: 76 BRR blocks of 16 samples */
#define blip_brr_loop 0   /* byte offset of the loop point; 0 with no loop */
#define blip_brr_loops 0   /* 1 = the sample loops */
#define blip_rate 11025   /* Hz of the source; the DSP plays at 32000 */

#endif
