/* coin.h — generated by opensnes-sample from coin.wav; do not edit */
#ifndef OPENSNES_SAMPLE_coin_H
#define OPENSNES_SAMPLE_coin_H

#include <snes.h>

extern u8 coin_brr[], coin_brr_end[];   /* the .incbin in assets_gen.asm (or your data.asm) */
#define coin_brr_size 999   /* bytes: 111 BRR blocks of 16 samples */
#define coin_brr_loop 0   /* byte offset of the loop point; 0 with no loop */
#define coin_brr_loops 0   /* 1 = the sample loops */
#define coin_rate 11025   /* Hz of the source; the DSP plays at 32000 */

#endif
