OPENSNES := $(shell cd ../../../.. && pwd)
TARGET   := transparentwindow.sfc
ROM_NAME := OPENSNES TRANSPWIN

USE_LIB     := 1
LIB_MODULES := console dma background sprite input hdma math

CSRC   := main.c
ASMSRC := data.asm

include $(OPENSNES)/make/common.mk
