OPENSNES := $(shell cd ../../.. && pwd)

TARGET   := hicolor_1792.sfc
ROM_NAME := HICOLOR 1792

USE_LIB  := 1
LIB_MODULES := console dma background

CSRC   := main.c
ASMSRC := irq_stream.asm

include $(OPENSNES)/make/common.mk
