# Gradient Colors - HDMA color gradient effect on backdrop (from PVSnesLib)

OPENSNES := $(shell cd ../../../.. && pwd)

TARGET   := gradient_colors.sfc
ROM_NAME := OPENSNES GRADCOLORS

USE_LIB     := 1
LIB_MODULES := console dma background sprite hdma input math

CSRC   := main.c
ASMSRC := data.asm

include $(OPENSNES)/make/common.mk
