;----------------------------------------------------------------------
; mode7_racing — track assets (generated by gen_track.py + gfx4snes
; -M 7) and the collision class map (1 byte/tile, far-pointer read).
;----------------------------------------------------------------------

ASSET_SECTION ".rodata1"

track_til:
.incbin "res/track.pc7"
track_til_end:

track_pal:
.incbin "res/track.pal"
track_pal_end:

.ends

ASSET_SECTION ".rodata2"

track_map:
.incbin "res/track.mp7"
track_map_end:

.ends

ASSET_SECTION ".rodata3"

; 128x128 bytes: 0 = road, 1 = grass, 2 = wall. Read from C through a
; far pointer ONLY (16 KB — lives outside bank $00 by design).
track_class:
.incbin "res/track_class.bin"
track_class_end:

.ends

;----------------------------------------------------------------------
; u8 track_class_at(u16 idx) — banked-data accessor (the B2 escape).
;
; C pointer dereferences are bank-$00-hardcoded (KNOWN_LIMITATIONS:
; the compiler emits `lda.l $0000,x`), so the 16 KB class map living
; in bank $01+ CANNOT be read from C directly — the hardened
; check_bank_reads guard now fails such builds. One absolute-long
; indexed load does it right: the linker resolves the 24-bit base.
;
; cc65816 ABI: idx at 5,s after php alone; u8 return in tcc__r0.
;----------------------------------------------------------------------
.section ".trackacc_text" superfree

track_class_at:
    php
    rep #$30
    .ACCU 16
    .INDEX 16
    lda 5,s             ; idx
    tax
    sep #$20
    .ACCU 8
    lda.l track_class,x ; 24-bit base + X — reads the real bank
    rep #$20
    .ACCU 16
    and #$00FF
    sta.b tcc__r0
    plp
    rtl

.ends
