OPENSNES := $(shell cd ../../.. && pwd)

TARGET   := mode7_racing.sfc
ROM_NAME := MODE7 RACING
USE_LIB  := 1
LIB_MODULES := console dma background sprite math mode7 input

CSRC   := main.c
ASMSRC := data.asm

include $(OPENSNES)/make/common.mk
