# HiROM Demo - Demonstrates HiROM memory mapping (64KB banks)

OPENSNES := $(shell cd ../../.. && pwd)

TARGET   := hirom_demo.sfc
ROM_NAME := HIROM DEMO

USE_LIB     := 1
USE_HIROM   := 1
LIB_MODULES := console dma input sprite

CSRC   := main.c

include $(OPENSNES)/make/common.mk
