OPENSNES := $(shell cd ../../.. && pwd)

TARGET     := tiled.sfc
ROM_NAME   := TILED MAP DEMO

USE_LIB    := 1
LIB_MODULES := console sprite dma input background map

CSRC       := main.c

include $(OPENSNES)/make/common.mk
