OPENSNES := $(shell cd ../../../.. && pwd)

TARGET   := a6_farptr.sfc
ROM_NAME := A6 FARPTR TEST

USE_LIB  := 1
LIB_MODULES := console sprite dma background

CSRC   := main.c
ASMSRC := a6_sentinel.asm

include $(OPENSNES)/make/common.mk
