const t_metasprite spritehero16_metasprite0[] = {
	METASPR_ITEM(0, 0, 0, OBJ_PAL(0) | OBJ_PRIO(0)),
	METASPR_ITEM(16, 0, 1, OBJ_PAL(0) | OBJ_PRIO(0)),
	METASPR_ITEM(0, 16, 2, OBJ_PAL(0) | OBJ_PRIO(0)),
	METASPR_ITEM(16, 16, 3, OBJ_PAL(0) | OBJ_PRIO(0)),
	METASPR_ITEM(0, 32, 4, OBJ_PAL(0) | OBJ_PRIO(0)),
	METASPR_ITEM(16, 32, 5, OBJ_PAL(0) | OBJ_PRIO(0)),
	METASPR_TERM
};

const t_metasprite spritehero16_metasprite1[] = {
	METASPR_ITEM(0, 0, 6, OBJ_PAL(0) | OBJ_PRIO(0)),
	METASPR_ITEM(16, 0, 7, OBJ_PAL(0) | OBJ_PRIO(0)),
	METASPR_ITEM(0, 16, 8, OBJ_PAL(0) | OBJ_PRIO(0)),
	METASPR_ITEM(16, 16, 9, OBJ_PAL(0) | OBJ_PRIO(0)),
	METASPR_ITEM(0, 32, 10, OBJ_PAL(0) | OBJ_PRIO(0)),
	METASPR_ITEM(16, 32, 11, OBJ_PAL(0) | OBJ_PRIO(0)),
	METASPR_TERM
};

const t_metasprite spritehero16_metasprite2[] = {
	METASPR_ITEM(0, 0, 12, OBJ_PAL(0) | OBJ_PRIO(0)),
	METASPR_ITEM(16, 0, 13, OBJ_PAL(0) | OBJ_PRIO(0)),
	METASPR_ITEM(0, 16, 14, OBJ_PAL(0) | OBJ_PRIO(0)),
	METASPR_ITEM(16, 16, 15, OBJ_PAL(0) | OBJ_PRIO(0)),
	METASPR_ITEM(0, 32, 16, OBJ_PAL(0) | OBJ_PRIO(0)),
	METASPR_ITEM(16, 32, 17, OBJ_PAL(0) | OBJ_PRIO(0)),
	METASPR_TERM
};

const t_metasprite spritehero16_metasprite3[] = {
	METASPR_ITEM(0, 0, 18, OBJ_PAL(0) | OBJ_PRIO(0)),
	METASPR_ITEM(16, 0, 19, OBJ_PAL(0) | OBJ_PRIO(0)),
	METASPR_ITEM(0, 16, 20, OBJ_PAL(0) | OBJ_PRIO(0)),
	METASPR_ITEM(16, 16, 21, OBJ_PAL(0) | OBJ_PRIO(0)),
	METASPR_ITEM(0, 32, 22, OBJ_PAL(0) | OBJ_PRIO(0)),
	METASPR_ITEM(16, 32, 23, OBJ_PAL(0) | OBJ_PRIO(0)),
	METASPR_TERM
};

const t_metasprite* spritehero16_metasprites[4] = {
	spritehero16_metasprite0, spritehero16_metasprite1, spritehero16_metasprite2, spritehero16_metasprite3
};
