const t_metasprite spritehero32_metasprite0[] = {
	METASPR_ITEM(0, 0, 0, OBJ_PAL(0) | OBJ_PRIO(2)),
	METASPR_ITEM(32, 0, 1, OBJ_PAL(0) | OBJ_PRIO(2)),
	METASPR_ITEM(0, 32, 2, OBJ_PAL(0) | OBJ_PRIO(2)),
	METASPR_ITEM(32, 32, 3, OBJ_PAL(0) | OBJ_PRIO(2)),
	METASPR_TERM
};

const t_metasprite spritehero32_metasprite1[] = {
	METASPR_ITEM(0, 0, 4, OBJ_PAL(0) | OBJ_PRIO(2)),
	METASPR_ITEM(32, 0, 5, OBJ_PAL(0) | OBJ_PRIO(2)),
	METASPR_ITEM(0, 32, 6, OBJ_PAL(0) | OBJ_PRIO(2)),
	METASPR_ITEM(32, 32, 7, OBJ_PAL(0) | OBJ_PRIO(2)),
	METASPR_TERM
};

const t_metasprite spritehero32_metasprite2[] = {
	METASPR_ITEM(0, 0, 8, OBJ_PAL(0) | OBJ_PRIO(2)),
	METASPR_ITEM(32, 0, 9, OBJ_PAL(0) | OBJ_PRIO(2)),
	METASPR_ITEM(0, 32, 10, OBJ_PAL(0) | OBJ_PRIO(2)),
	METASPR_ITEM(32, 32, 11, OBJ_PAL(0) | OBJ_PRIO(2)),
	METASPR_TERM
};

const t_metasprite* spritehero32_metasprites[3] = {
	spritehero32_metasprite0, spritehero32_metasprite1, spritehero32_metasprite2
};
