const t_metasprite spritehero8_metasprite0[] = {
	METASPR_ITEM(0, 0, 0, OBJ_PAL(0) | OBJ_PRIO(2)),
	METASPR_ITEM(8, 0, 1, OBJ_PAL(0) | OBJ_PRIO(2)),
	METASPR_ITEM(0, 8, 8, OBJ_PAL(0) | OBJ_PRIO(2)),
	METASPR_ITEM(8, 8, 9, OBJ_PAL(0) | OBJ_PRIO(2)),
	METASPR_TERM
};

const t_metasprite spritehero8_metasprite1[] = {
	METASPR_ITEM(0, 0, 2, OBJ_PAL(0) | OBJ_PRIO(2)),
	METASPR_ITEM(8, 0, 3, OBJ_PAL(0) | OBJ_PRIO(2)),
	METASPR_ITEM(0, 8, 10, OBJ_PAL(0) | OBJ_PRIO(2)),
	METASPR_ITEM(8, 8, 11, OBJ_PAL(0) | OBJ_PRIO(2)),
	METASPR_TERM
};

const t_metasprite spritehero8_metasprite2[] = {
	METASPR_ITEM(0, 0, 4, OBJ_PAL(0) | OBJ_PRIO(2)),
	METASPR_ITEM(8, 0, 5, OBJ_PAL(0) | OBJ_PRIO(2)),
	METASPR_ITEM(0, 8, 12, OBJ_PAL(0) | OBJ_PRIO(2)),
	METASPR_ITEM(8, 8, 13, OBJ_PAL(0) | OBJ_PRIO(2)),
	METASPR_TERM
};

const t_metasprite spritehero8_metasprite3[] = {
	METASPR_ITEM(0, 0, 6, OBJ_PAL(0) | OBJ_PRIO(2)),
	METASPR_ITEM(8, 0, 7, OBJ_PAL(0) | OBJ_PRIO(2)),
	METASPR_ITEM(0, 8, 14, OBJ_PAL(0) | OBJ_PRIO(2)),
	METASPR_ITEM(8, 8, 15, OBJ_PAL(0) | OBJ_PRIO(2)),
	METASPR_TERM
};

const t_metasprite* spritehero8_metasprites[4] = {
	spritehero8_metasprite0, spritehero8_metasprite1, spritehero8_metasprite2, spritehero8_metasprite3
};
