# Button Test - Input Diagnostic Example

OPENSNES := $(shell cd ../../.. && pwd)
TARGET   := button_test.sfc
ROM_NAME := BUTTON TEST

CSRC     := main.c
USE_LIB  := 1
LIB_MODULES := console input text sprite dma

include $(OPENSNES)/make/common.mk
