OPENSNES := $(shell cd ../../.. && pwd)

TARGET     := scene_stack.sfc
ROM_NAME   := SCENE STACK DEMO

USE_LIB    := 1
LIB_MODULES := console sprite dma background text input scene

CSRC       := main.c

include $(OPENSNES)/make/common.mk
