OPENSNES := $(shell cd ../../../.. && pwd)

TARGET   := c_features.sfc
ROM_NAME := C FEATURES TEST

USE_LIB  := 1
LIB_MODULES := console sprite dma background

CSRC := main.c

include $(OPENSNES)/make/common.mk
