/* GENERATED by devtools/vram_layout/vram_layout.py --emit — DO NOT EDIT.
 * Source: vram.spec. Regenerate after editing the spec.
 * Validated at build by `make lint-vram` (alignment + no overlap + fit). */
#ifndef VRAM_MAP_H
#define VRAM_MAP_H

#define VRAM_SPRITES   0x0000  /* obj, 8192 words */
#define VRAM_FONT      0x2000  /* bg_char, 1536 words */
#define VRAM_TEXT_MAP  0x2800  /* bg_map, 1024 words */

#endif /* VRAM_MAP_H */
