# Video Unit Test Makefile

OPENSNES := $(shell cd ../../.. && pwd)
TARGET   := test_video.sfc
ROM_NAME := VIDEO TESTS

CSRC     := test_video.c
USE_LIB  := 1
LIB_MODULES := console video dma text sprite

include $(OPENSNES)/make/common.mk
