# HDMA Wave Demo Makefile

OPENSNES := $(shell cd ../../../.. && pwd)
TARGET   := hdma_wave.sfc
ROM_NAME := HDMA WAVE DEMO

CSRC     := main.c
USE_LIB  := 1
LIB_MODULES := console background hdma dma sprite input text math

include $(OPENSNES)/make/common.mk
