; bg_data.as — generated by opensnes-tileset 1.0.0; .include it inside an ASSET_SECTION (assets_gen.asm does)
bg_tiles:
.incbin "bg.pic"
bg_tiles_end:

bg_map:
.incbin "bg.map"
bg_map_end:

bg_pal:
.incbin "bg.pal"
bg_pal_end:

