; bg_data.as — generated by opensnes-tileset 1.0.0; one ASSET_SECTION per blob, .include it from assets_gen.asm (the build does)

ASSET_SECTION "bg_tiles"
bg_tiles:
.incbin "bg.pic"
bg_tiles_end:
.ENDS

ASSET_SECTION "bg_map"
bg_map:
.incbin "bg.map"
bg_map_end:
.ENDS

ASSET_SECTION "bg_pal"
bg_pal:
.incbin "bg.pal"
bg_pal_end:
.ENDS

