# Types Unit Test
# NOTE: Currently disabled due to WLA-DX linker issues with underscore-prefixed
# labels in RAMSECTION. The main examples build and work fine.
# TODO: Fix test harness to work with WLA-DX label scoping

.PHONY: all clean
all:
	@echo "[SKIP] test_types disabled (WLA-DX linker issue with BSS labels)"
clean:
	@echo "[SKIP] Nothing to clean"
