# Sound Effects Demo
# Uses bare-metal SPC700 programming (like 1_tone)

OPENSNES := $(shell cd ../../.. && pwd)

# ROM Configuration
TARGET   := sfx_demo.sfc
ROM_NAME := OPENSNES SFX DEMO

# Source files
CSRC     := main.c
ASMSRC   := spc.asm

# Include shared build rules
include $(OPENSNES)/make/common.mk
