OPENSNES := $(shell cd ../../.. && pwd)

TARGET   := panel_hud.sfc
ROM_NAME := PANEL HUD
USE_LIB  := 1
LIB_MODULES := console dma background panel input tile

CSRC := main.c

include $(OPENSNES)/make/common.mk
