/* tone.h — generated by opensnes-sample from tone.wav; do not edit */
#ifndef OPENSNES_SAMPLE_tone_H
#define OPENSNES_SAMPLE_tone_H

#define tone_brr_size 117   /* bytes: 13 BRR blocks of 16 samples */
#define tone_brr_loop 27   /* byte offset of the loop point; 0 with no loop */
#define tone_brr_loops 1   /* 1 = the sample loops */
#define tone_rate 16000   /* Hz of the source; the DSP plays at 32000 */

#endif
