# Joypad Input Example
# Move a sprite with the D-pad

OPENSNES := $(shell cd ../../.. && pwd)

# ROM Configuration
TARGET   := joypad.sfc
ROM_NAME := OPENSNES JOYPAD

# Source files
CSRC     := main.c

# Graphics to convert
GFXSRC   := assets/player.png
SPRITE_SIZE := 16
BPP      := 4

# Include shared build rules
include $(OPENSNES)/make/common.mk
