OPENSNES := $(shell cd ../../.. && pwd)

TARGET     := mode0.sfc
ROM_NAME   := MODE 0 4BG DEMO

USE_LIB    := 1
LIB_MODULES := console dma background

CSRC       := main.c

include $(OPENSNES)/make/common.mk
