OPENSNES := $(shell cd ../../../.. && pwd)

TARGET   := d_quals.sfc
ROM_NAME := D QUALS TEST

USE_LIB  := 1
LIB_MODULES := console sprite dma background

CSRC   := main.c


include $(OPENSNES)/make/common.mk
