#==============================================================================
# Transparency Example
# Color addition between two BG layers (landscape + scrolling clouds)
#==============================================================================

OPENSNES := $(shell cd ../../.. && pwd)

TARGET     := transparency.sfc
ROM_NAME   := TRANSPARENCY DEMO

USE_LIB    := 1
LIB_MODULES := console sprite dma background colormath

CSRC       := main.c

include $(OPENSNES)/make/common.mk
