OPENSNES := $(shell cd ../../../.. && pwd)

TARGET   := mode1scroll.sfc
ROM_NAME := OPENSNES MODE1SCROLL

USE_LIB     := 1
LIB_MODULES := console dma text background sprite input

CSRC   := main.c
ASMSRC := data.asm

include $(OPENSNES)/make/common.mk
