/* GENERATED by devtools/vram_layout/vram_layout.py --emit — DO NOT EDIT.
 * Source: vram.spec. Regenerate after editing the spec.
 * Validated at build by `make lint-vram` (alignment + no overlap + fit). */
#ifndef VRAM_MAP_H
#define VRAM_MAP_H

#define VRAM_BG2_MAP    0x1400  /* bg_map, 1024 words */
#define VRAM_BG1_MAP    0x1800  /* bg_map, 1024 words */
#define VRAM_BG1_TILES  0x4000  /* bg_char, 4096 words */
#define VRAM_BG2_TILES  0x5000  /* bg_char, 4096 words */

#endif /* VRAM_MAP_H */
