OPENSNES := $(shell cd ../../.. && pwd)

TARGET   := mode4.sfc
ROM_NAME := MODE 4 OPT
USE_LIB  := 1
LIB_MODULES := console dma background input math tile

CSRC := main.c

include $(OPENSNES)/make/common.mk
